Repository apecloud/kubeblocks, pull requests merged in 2023-11, with the labels that each got.

#5712 fix: risingwave connector crashloopbackoff on gke
  deploy/risingwave/templates/clusterdefinition.yaml
Labels: enhancement, size/XS

#5709 chore: add enabledClusterVersions for mongodb and postgresql
  deploy/mongodb/templates/_helpers.tpl
  deploy/mongodb/templates/clusterversion.yaml
  deploy/mongodb/values.yaml
  deploy/postgresql/templates/_helpers.tpl
  deploy/postgresql/templates/clusterversion.yaml
  deploy/postgresql/values.yaml
Labels: area/user-interaction, size/L

#5713 chore: adjust e2e test config
  test/e2e/testdata/smoketest/config.go
  test/e2e/testdata/smoketest/elasticsearch/00_elasticsearchcluster.yaml
  test/e2e/testdata/smoketest/etcd/07_vexpand.yaml
  test/e2e/testdata/smoketest/llm/00_llmcluster.yaml
  test/e2e/testdata/smoketest/postgresql/00_postgresqlcluster.yaml
  test/e2e/testdata/smoketest/smoketestrun.go
Labels: test, size/L

#5717 fix: milvus volume expansion failed
  deploy/milvus/templates/clusterdefinition.yaml
Labels: enhancement, size/XS

#5721 fix: cluster phase keeps in Updating after reconfiguration done
  controllers/apps/cluster_controller.go
  pkg/controller/configuration/pipeline.go
Labels: area/cluster-controller, enhancement, size/XS

#5727 fix: milvus minio volume expansion failed
  deploy/milvus/templates/clusterdefinition.yaml
  deploy/milvus/templates/clusterversion.yaml
  deploy/milvus/values.yaml
Labels: enhancement, size/S

#5722 fix: fix incompatible upgrade for qdrant from 0.6 to 0.7
  pkg/cli/util/breakingchange/upgradehandlerto0.7.go
Labels: enhancement, size/S

#5719 fix: the configuration status is incorrect occasionally (#5716)
  controllers/apps/configuration/config_annotation.go
  pkg/controllerutil/config_util.go
Labels: enhancement, approved, severity/major, size/S

#5731 fix: get lorry image from the same env
  pkg/controller/rsm/transformer_object_generation.go
Labels: enhancement, size/XS, rsm

#5720 chore: tidy up license header and import order
  deploy/zookeeper/config/zookeeper-config-constraint.cue
  pkg/lorry/engines/dbmanager_mock.go
  pkg/lorry/engines/kubernetes/client.go
  pkg/lorry/engines/mysql/config.go
  pkg/lorry/engines/mysql/user.go
  pkg/lorry/engines/postgres/user.go
  pkg/lorry/engines/redis/user.go
  pkg/lorry/util/event.go
Labels: approved, size/M

#5736 fix: pulsar updates failed after upgrading to 0.7
  deploy/apecloud-mysql/templates/backuppolicytemplate.yaml
  deploy/mongodb/templates/backuppolicytemplate.yaml
  deploy/postgresql/templates/backuppolicytemplate.yaml
  deploy/redis/templates/backuppolicytemplate.yaml
  pkg/cli/util/breakingchange/constant.go
  pkg/cli/util/breakingchange/upgradehandlerto0.7.go
Labels: enhancement, size/M

#5741 fix: remove_config_params_for_wescale
  deploy/apecloud-mysql/scripts/vttablet.sh
Labels: enhancement, size/XS

#5739 fix: security problem related to converting a string to an integer
  pkg/lorry/engines/kafka/thirdparty/retry.go
Labels: enhancement, size/XS

#5742 fix: update volumeMounts name
  deploy/openldap-cluster/templates/cluster.yaml
  deploy/openldap/templates/clusterdefinition.yaml
Labels: enhancement, approved, size/XS

#5744 fix: PolarDB-X component gms and dn restart not working
  deploy/polardbx/templates/clusterDefintion.yaml
Labels: kind/bug, enhancement, size/XS

#5746 chore: sync engine changes from wesyncer
  pkg/lorry/dcs/k8s.go
  pkg/lorry/engines/base.go
  pkg/lorry/engines/kubernetes/client.go
  pkg/lorry/engines/register/managers.go
  pkg/lorry/engines/register/managers_test.go
  pkg/lorry/engines/util.go
Labels: size/L

#5749 fix: rsm and statefulset annotation are inconsistent (#5738)
  controllers/apps/configuration/policy_util.go
  controllers/apps/configuration/reconfigure_policy.go
  controllers/apps/configuration/simple_policy.go
  controllers/apps/configuration/types.go
Labels: enhancement, size/L

#5750 fix: wrong ToClusterPhase setup in stop ops
  controllers/apps/operations/stop.go
Labels: enhancement, size/XS

#5748 feat: add official pg with zhparser extension
  deploy/official-postgresql/templates/clusterversion.yaml
Labels: feature, ci, size/S

#5760 fix: opsRequest is always running but cluster has changed successfully
  controllers/apps/opsrequest_controller.go
Labels: enhancement, size/S

#5758 chore: sync httpserver changes from wesyncer
  pkg/lorry/httpserver/apis.go
  pkg/lorry/httpserver/apis_test.go
  pkg/lorry/httpserver/server.go
  pkg/lorry/httpserver/server_test.go
  pkg/lorry/operations/fake.go
Labels: size/L

#5762 fix: add initContainers to grant volume permissions for greptimedb
  deploy/greptimedb/templates/clusterdefinition.yaml
Labels: enhancement, size/S

#5442 feat: support user-defined configmap/secrets (#4885)
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  controllers/apps/components/component.go
  controllers/apps/components/component_test.go
  controllers/apps/components/component_workload_builder.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  pkg/testutil/apps/cluster_factory.go
Labels: feature, approved, size/XL

#5714 feat: pre-check the BackupRepo by running a real job
  cmd/dataprotection/main.go
  controllers/dataprotection/backuprepo_controller.go
  controllers/dataprotection/backuprepo_controller_test.go
  controllers/dataprotection/suite_test.go
  controllers/dataprotection/types.go
  pkg/dataprotection/utils/events.go
  pkg/dataprotection/utils/utils.go
  pkg/testutil/dataprotection/backup_utils.go
Labels: area/user-interaction, feature, size/XXL

#5766 chore: remove generated DeepCopy code
  .gitignore
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  apis/extensions/v1alpha1/zz_generated.deepcopy.go
  apis/storage/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  externalapis/preflight/v1beta2/zz_generated.deepcopy.go
Labels: approved, size/XXL

#5771 fix: upgrade from 0.6.0 to 0.7.0 failed
  pkg/cli/util/breakingchange/upgradehandlerto0.7.go
Labels: enhancement, approved, size/XS

#5779 docs: fix typo in monitoring doc
  docs/user_docs/observability/monitor-database.md
Labels: documentation, enhancement, size/XS

#5752 chore: abstract e2e test configuration related
  test/e2e/testdata/config/componentresourceconstraint_custom.yaml
  test/e2e/testdata/config/custom_class.yaml
  test/e2e/testdata/config/postgresql_cv.yaml
  test/e2e/testdata/smoketest/config.go
  test/e2e/testdata/smoketest/mariadb/00_mariadbcluster.yaml
  test/e2e/testdata/smoketest/milvus/01_vscale.yaml
  test/e2e/testdata/smoketest/postgresql/07_upgrade.yaml
  test/e2e/testdata/smoketest/postgresql/08_restart.yaml
  test/e2e/testdata/smoketest/postgresql/09_reconfigure.yaml
  test/e2e/testdata/smoketest/postgresql/10_backup_basebackup.yaml
  test/e2e/testdata/smoketest/postgresql/11_backup_basebackup_restore.yaml
  test/e2e/testdata/smoketest/postgresql/12_backup_volume_snapshot.yaml
  test/e2e/testdata/smoketest/postgresql/13_backup_volume_snapshot_restore.yaml
  test/e2e/testdata/smoketest/smoketestrun.go
  test/e2e/testdata/smoketest/wesql/01_vscale.yaml
  test/e2e/testdata/smoketest/wesql/02_hscale_out.yaml
  test/e2e/testdata/smoketest/wesql/03_hscale_in.yaml
  test/e2e/testdata/smoketest/wesql/04_vexpand.yaml
  test/e2e/testdata/smoketest/wesql/05_stop.yaml
  test/e2e/testdata/smoketest/wesql/06_start.yaml
  test/e2e/testdata/smoketest/wesql/07_restart.yaml
  test/e2e/testdata/smoketest/wesql/08_reconfigure.yaml
  test/e2e/testdata/smoketest/wesql/09_backup_xtrabackup.yaml
  test/e2e/testdata/smoketest/wesql/10_backup_xtrabackup_restore.yaml
  test/e2e/testdata/smoketest/wesql/11_backup_volume_snapshot.yaml
  test/e2e/testdata/smoketest/wesql/12_backup_volume_snapshot_restore.yaml
Labels: test, size/L

#5770 feat: auto recover vllm when some of node down
  deploy/llm/templates/scripts.yaml
Labels: feature, size/M

#5789 chore: change get addon repo
  .github/workflows/release-delete.yml
  .github/workflows/release-helm-chart.yml
Labels: approved, size/S

#5790 chore: skip test remove dir
  .github/workflows/cicd-pull-request.yml
  .github/workflows/release-version.yml
Labels: test, approved, size/XS

#5787 feat: xinference
  Makefile
  deploy/helm/templates/addons/xinference-addon.yaml
  deploy/xinference-cluster/.helmignore
  deploy/xinference-cluster/Chart.yaml
  deploy/xinference-cluster/templates/NOTES.txt
  deploy/xinference-cluster/templates/_helpers.tpl
  deploy/xinference-cluster/templates/cluster.yaml
  deploy/xinference-cluster/templates/rbac.yaml
  deploy/xinference-cluster/templates/validate.yaml
  deploy/xinference-cluster/values.schema.json
  deploy/xinference-cluster/values.yaml
  deploy/xinference/Chart.yaml
  deploy/xinference/templates/NOTES.txt
  deploy/xinference/templates/_helpers.tpl
  deploy/xinference/templates/clusterdefinition.yaml
  deploy/xinference/templates/clusterversion.yaml
  deploy/xinference/templates/scripts.yaml
  deploy/xinference/values.yaml
  docs/user_docs/cli/kbcli_cluster_create.md
  pkg/cli/cluster/builtin_charts.go
Labels: feature, approved, size/L

#5788 chore: Revert "chore: remove generated DeepCopy code (#5766)"
  .gitignore
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  apis/extensions/v1alpha1/zz_generated.deepcopy.go
  apis/storage/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  externalapis/preflight/v1beta2/zz_generated.deepcopy.go
Labels: size/XXL

#5778 feat: check ip before download llm model and remove cv of cn
  deploy/llm/templates/clusterversion.yaml
  deploy/llm/templates/scripts.yaml
Labels: feature, approved, size/M

#5793 chore: add service port env for kafka exporter
  deploy/kafka/templates/clusterdefinition.yaml
Labels: size/XS

#5796 chore: tidy up addon tutorial to use add-on helm chart repo
  docs/developer_docs/integration/how-to-add-an-add-on.md
  docs/developer_docs/integration/multi-component.md
Labels: documentation, size/XS

#5797 chore: fix security issue 33
  go.mod
  go.sum
Labels: enhancement, size/S

#5800 chore: fix addon list output display
  pkg/cli/cmd/addon/addon.go
Labels: enhancement, size/M

#5801 feat: cli org & context
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli.md
  pkg/cli/cmd/auth/login.go
  pkg/cli/cmd/cli.go
  pkg/cli/cmd/context/cloud_context.go
  pkg/cli/cmd/context/cloud_context_test.go
  pkg/cli/cmd/organization/cloud_organization.go
  pkg/cli/cmd/organization/organization.go
Labels: feature, approved, size/L

#5773 fix: rsm and cluster controller delete same cm
  apis/apps/v1alpha1/type.go
  controllers/apps/transformer_cluster_deletion.go
  pkg/controller/rsm/transformer_deletion.go
  pkg/controller/rsm/transformer_deletion_test.go
  pkg/controller/rsm/utils.go
  pkg/controller/rsm/utils_test.go
Labels: bug, enhancement, size/L

#5805 fix: restore/backup exec action failed
  controllers/apps/transformer_backup_policy_tpl.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/restore_controller.go
  controllers/dataprotection/utils.go
  pkg/constant/const.go
  pkg/controller/rsm/utils.go
  pkg/dataprotection/action/action_job.go
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/restore/builder.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/manager_test.go
  pkg/dataprotection/restore/types.go
  pkg/dataprotection/types/constant.go
Labels: enhancement, approved, size/L

#5804 chore: fix deploy/helm and addon_types format
  apis/extensions/v1alpha1/addon_types.go
  config/crd/bases/extensions.kubeblocks.io_addons.yaml
  deploy/helm/crds/extensions.kubeblocks.io_addons.yaml
  deploy/helm/templates/storageclass.yaml
Labels: enhancement, size/S

#5810 docs: add 0.7 docs
  docs/developer_docs/external-component/_category_.yml
  docs/developer_docs/external-component/reference-external-component.md
  docs/img/backup-and-restore-backup-repo-1.png
  docs/img/backup-and-restore-backup-repo-2.png
  docs/img/backup-and-restore-backup-repo-3.png
  docs/user_docs/backup-and-restore/backup/backup-repo.md
  docs/user_docs/backup-and-restore/backup/configure-backuppolicy.md
  docs/user_docs/backup-and-restore/backup/on-demand-backup.md
  docs/user_docs/backup-and-restore/backup/scheduled-backup.md
  docs/user_docs/backup-and-restore/restore/pitr.md
  docs/user_docs/backup-and-restore/restore/restore-data-from-backup-set.md
  docs/user_docs/overview/supported-addons.md
Labels: documentation, size/XXL

#5813 docs: fix format bugs
  docs/user_docs/backup-and-restore/backup/backup-repo.md
Labels: documentation, bug, enhancement, size/XS

#5816 chore: adjust release workflow
  .github/workflows/package-version.yml
  .github/workflows/release-create.yml
  .github/workflows/release-delete.yml
  .github/workflows/release-helm-chart.yml
  .github/workflows/release-image.yml
  .github/workflows/release-publish.yml
  .github/workflows/release-version.yml
Labels: release, approved, size/XL

#5819 docs: modify contents
  docs/developer_docs/external-component/reference-external-component.md
  docs/user_docs/backup-and-restore/backup/backup-repo.md
Labels: documentation, size/S

#5828 chore: remove unused kbcli codes and fix typos
  .github/utils/extract_chart_n_image_list.sh
  .github/utils/generate_kbcli_sha256.py
  .goreleaser.yaml
  apis/workloads/v1alpha1/replicatedstatemachine_types.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/workloads.kubeblocks.io_replicatedstatemachines.yaml
  controllers/apps/component_controller_test.go
  controllers/apps/operations/datascript.go
  controllers/apps/operations/ops_manager.go
  controllers/apps/operations/reconfigure_util.go
  controllers/apps/operations/switchover_util.go
  controllers/apps/systemaccount_controller.go
  controllers/apps/transform_utils.go
  controllers/apps/transformer_rbac.go
  controllers/dataprotection/backuprepo_controller_test.go
  deploy/helm/Chart.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/workloads.kubeblocks.io_replicatedstatemachines.yaml
  deploy/helm/dashboards/loki.json
  go.mod
  go.sum
  hack/install_cli.ps1
  hack/install_cli.sh
  hack/install_cli_docker.sh
  pkg/class/class_utils_test.go
  pkg/configuration/config_manager/reconfiguring_wrapper_test.go
  pkg/constant/const.go
  pkg/controller/component/component_fieldref_util.go
  pkg/controller/configuration/config_template_utils.go
  pkg/controller/factory/builder_test.go
  pkg/controllerutil/requeue_errors_test.go
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/backup/utils.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/manager_test.go
  pkg/dataprotection/restore/utils.go
  pkg/lorry/dcs/dcs.go
  pkg/lorry/engines/custom/manager_test.go
  pkg/lorry/engines/etcd/manager_test.go
  pkg/lorry/engines/mock.go
  pkg/lorry/engines/mongodb/client.go
  pkg/lorry/engines/mongodb/manager.go
  pkg/lorry/engines/mysql/manager.go
  pkg/lorry/engines/mysql/manager_test.go
  pkg/lorry/engines/mysql/util.go
  pkg/lorry/engines/postgres/officalpostgres/manager_test.go
  pkg/lorry/engines/redis/manager_test.go
  pkg/lorry/engines/wesql/manager.go
  pkg/testutil/apps/constant.go
  pkg/unstructured/properties_test.go
  pkg/unstructured/viper_wrap_test.go
  test/e2e/testdata/smoketest/playgroundtest.go
  test/e2e/testdata/smoketest/smoketestrun.go
  version/version.go
  version/version_test.go
Labels: enhancement, size/XXL

#5824 feat: support KubeBlocks component postStart hook
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  controllers/apps/components/component.go
  controllers/apps/operations/switchover.go
  controllers/apps/operations/switchover_test.go
  controllers/apps/operations/switchover_util.go
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  pkg/constant/const.go
  pkg/controller/component/component.go
  pkg/controller/component/component_poststart.go
  pkg/controller/component/component_poststart_test.go
  pkg/controller/component/job_utils.go
  pkg/controller/component/job_utils_test.go
  pkg/controller/component/suite_test.go
  pkg/controller/component/type.go
  pkg/testutil/apps/base_factory.go
Labels: area/user-interaction, feature, size/XXL

#5832 chore: add tidb addon yaml
  deploy/helm/templates/addons/tidb-addon.yaml
Labels: size/M

#5842 fix: two pods are always pending after restore the mysql
  controllers/dataprotection/restore_controller_test.go
  pkg/dataprotection/restore/builder.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/manager_test.go
  pkg/testutil/dataprotection/restore_factory.go
Labels: enhancement, size/M

#5844 fix: add statefulSet and deployment rbac
  config/rbac/role.yaml
  controllers/workloads/replicatedstatemachine_controller.go
  deploy/helm/config/rbac/role.yaml
Labels: enhancement, size/L

#5845 fix: kbcli addon enable snapshot controller failed on aliyunedge
  deploy/helm/templates/addons/csi-hostpath-driver-addon.yaml
  deploy/helm/templates/addons/snapshot-controller-addon.yaml
Labels: enhancement, size/XS

#5846 chore: add compatibility handling for enterprise version data protection
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  controllers/apps/backuppolicytemplate_controller_test.go
  controllers/apps/cluster_controller_test.go
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backupschedule_controller.go
  controllers/dataprotection/restore_controller.go
  controllers/dataprotection/restore_controller_test.go
  controllers/dataprotection/types.go
  controllers/dataprotection/utils.go
  controllers/dataprotection/volumepopulator_controller.go
  controllers/dataprotection/volumepopulator_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  pkg/controller/plan/restore_test.go
  pkg/dataprotection/action/action_job.go
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/backup/scheduler.go
  pkg/dataprotection/backup/scheduler_test.go
  pkg/dataprotection/backup/types.go
  pkg/dataprotection/backup/utils.go
  pkg/dataprotection/restore/builder.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/types.go
  pkg/dataprotection/restore/utils.go
  pkg/dataprotection/utils/utils.go
  pkg/testutil/apps/backuppolicytemplate_factory.go
Labels: approved, size/XXL

#5851 fix: refactor lorry container inject
  controllers/apps/transformer_component_workload.go
  pkg/controller/component/lorry_utils.go
  pkg/controller/component/lorry_utils_test.go
  pkg/controller/factory/builder_rsm.go
Labels: enhancement, refactor, approved, size/L

#5807 chore: add builder for oteld (#4821)
  pkg/controller/builder/builder_container.go
  pkg/controller/builder/builder_container_test.go
  pkg/controller/builder/builder_daemon_set.go
  pkg/controller/builder/builder_daemon_set_test.go
  pkg/controller/builder/builder_deployment.go
  pkg/controller/builder/builder_deployment_test.go
  pkg/controller/builder/builder_pod.go
  pkg/controller/builder/builder_pod_test.go
  pkg/controllerutil/cue_value.go
  pkg/controllerutil/cue_value_test.go
Labels: area/user-interaction, approved, size/XL

#5857 chore: fix backup failed after refactor
  controllers/apps/transformer_cluster_backup_policy.go
Labels: enhancement, refactor, size/XS

#5838 chore: sync-wesyncer-to-lorry
  pkg/constant/env.go
  pkg/lorry/dcs/dcs.go
  pkg/lorry/dcs/dcs_mock.go
  pkg/lorry/dcs/k8s.go
  pkg/lorry/dcs/types.go
  pkg/lorry/engines/etcd/manager_test.go
  pkg/lorry/engines/mongodb/config.go
  pkg/lorry/engines/mysql/config.go
  pkg/lorry/engines/mysql/config_test.go
  pkg/lorry/engines/mysql/conn.go
  pkg/lorry/engines/mysql/get_replica_role.go
  pkg/lorry/engines/mysql/get_replica_role_test.go
  pkg/lorry/engines/mysql/gtid.go
  pkg/lorry/engines/mysql/gtid_test.go
  pkg/lorry/engines/mysql/json.go
  pkg/lorry/engines/mysql/json_test.go
  pkg/lorry/engines/mysql/manager.go
  pkg/lorry/engines/mysql/manager_test.go
  pkg/lorry/engines/mysql/query_test.go
  pkg/lorry/engines/mysql/util.go
  pkg/lorry/engines/mysql/util_test.go
  pkg/lorry/engines/postgres/apecloudpostgres/manager.go
  pkg/lorry/engines/postgres/apecloudpostgres/manager_test.go
  pkg/lorry/engines/postgres/config.go
  pkg/lorry/engines/postgres/config_test.go
  pkg/lorry/engines/postgres/officalpostgres/manager.go
  pkg/lorry/engines/postgres/query.go
  pkg/lorry/engines/redis/manager.go
  pkg/lorry/engines/redis/manager_test.go
  pkg/lorry/engines/wesql/config_test.go
  pkg/lorry/engines/wesql/conn.go
  pkg/lorry/engines/wesql/conn_test.go
  pkg/lorry/engines/wesql/get_replica_role.go
  pkg/lorry/engines/wesql/get_replica_role_test.go
  pkg/lorry/engines/wesql/manager.go
  pkg/lorry/engines/wesql/manager_test.go
  pkg/lorry/highavailability/ha.go
  pkg/lorry/operations/replica/checkrole.go
  pkg/lorry/operations/replica/getlag.go
  pkg/lorry/operations/sql/exec.go
  pkg/lorry/operations/sql/query.go
  pkg/lorry/operations/switchover.go
  pkg/lorry/operations/types.go
Labels: approved, size/XXL

#5858 fix: component controller event recorder panic
  cmd/manager/main.go
Labels: enhancement, approved, size/S

#5860 fix: mongodb service role selector error
  pkg/controller/component/component_definition_convertor.go
  pkg/controller/component/component_definition_convertor_test.go
Labels: enhancement, approved, size/S

#5835 docs: add supported engine version and add upgrade doc
  docs/developer_docs/external-component/reference-external-component.md
  docs/img/kubeblocks-logo-black-font.png
  docs/img/kubeblocks-logo-short-version.png
  docs/img/kubeblocks-logo-white-font.png
  docs/user_docs/backup-and-restore/backup/backup-repo.md
  docs/user_docs/backup-and-restore/introduction.md
  docs/user_docs/installation/upgrade/upgrade-kubeblocks-to-0.6.md
  docs/user_docs/installation/upgrade/upgrade-kubeblocks-to-0.7.md
  docs/user_docs/overview/supported-addons.md
Labels: documentation, size/L

#5856 chore: tidy up compile for kbcli
  .golangci.yaml
  Makefile
Labels: approved, size/S

#5862 fix: pg cluster connect fail
  pkg/lorry/engines/foxlake/commands.go
  pkg/lorry/engines/mongodb/commands.go
  pkg/lorry/engines/mysql/commands.go
  pkg/lorry/engines/nebula/commands.go
  pkg/lorry/engines/oceanbase/commands.go
  pkg/lorry/engines/postgres/commands.go
  pkg/lorry/engines/redis/commands.go
  pkg/lorry/engines/util.go
Labels: enhancement, size/S

#5830 feat: delete validation rules that prohibit adding/deleting components
  apis/apps/v1alpha1/cluster_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
Labels: feature, approved, size/S

#5867 chore: inject zero resource limit for account jobs
  controllers/apps/systemaccount_util.go
Labels: size/S

#5843 chore: use custom dbmanager if not set
  go.mod
  go.sum
  pkg/lorry/engines/models/engine_types.go
  pkg/lorry/engines/mongodb/config.go
  pkg/lorry/engines/redis/settings.go
  pkg/lorry/engines/redis/settings_test.go
  pkg/lorry/engines/register/managers.go
  pkg/lorry/engines/register/managers_test.go
  pkg/lorry/util/config/decode.go
  pkg/lorry/util/config/deepcopy.go
  pkg/lorry/util/config/deepcopy_test.go
Labels: size/XL

#5868 chore: component controller don't handle default headless service
  apis/apps/v1alpha1/componentdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/cluster_controller_test.go
  controllers/apps/transformer_component_service.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
Labels: approved, size/L

#5871 chore: set data protection resource managed-by value to kubeblocks-protection
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/backupschedule_controller.go
  controllers/dataprotection/backupschedule_controller_test.go
  controllers/dataprotection/restore_controller.go
  controllers/dataprotection/restore_controller_test.go
  controllers/dataprotection/volumepopulator_controller.go
  controllers/dataprotection/volumepopulator_controller_test.go
  pkg/constant/const.go
  pkg/dataprotection/backup/deleter.go
  pkg/dataprotection/backup/scheduler.go
  pkg/dataprotection/restore/builder.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/types.go
  pkg/dataprotection/restore/utils.go
  pkg/dataprotection/types/constant.go
Labels: approved, size/M

#5876 chore: add release node for 0.7.0
  docs/release_notes/v0.7.0/_category_.yml
  docs/release_notes/v0.7.0/v0.7.0.md
Labels: release, size/M

#5881 feat: lorry support vault
  cmd/lorry/vault/plugin.go
  controllers/apps/component_controller_test.go
  controllers/apps/transformer_component_account_provision.go
  go.mod
  go.sum
  pkg/lorry/client/client.go
  pkg/lorry/client/client_mock.go
  pkg/lorry/client/httpclient_test.go
  pkg/lorry/client/interface.go
  pkg/lorry/ctl/createuser.go
  pkg/lorry/ctl/vault_plugin.go
  pkg/lorry/operations/user/create.go
  pkg/lorry/vault/database.go
Labels: feature, size/L

#5885 fix: add RSMSpec role and roleProbe convertor
  pkg/controller/component/component_definition_convertor.go
  pkg/controller/component/component_definition_convertor_test.go
Labels: bug, enhancement, size/L

#5887 feat: support queue for opsRequest which cannot run concurrently.
  apis/apps/v1alpha1/opsrequest_conditions.go
  apis/apps/v1alpha1/opsrequest_conditions_test.go
  apis/apps/v1alpha1/opsrequest_webhook.go
  apis/apps/v1alpha1/opsrequest_webhook_test.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/webhook_suite_test.go
  controllers/apps/component_controller.go
  controllers/apps/operations/backup.go
  controllers/apps/operations/backup_test.go
  controllers/apps/operations/datascript_test.go
  controllers/apps/operations/expose_test.go
  controllers/apps/operations/horizontal_scaling.go
  controllers/apps/operations/horizontal_scaling_test.go
  controllers/apps/operations/ops_manager.go
  controllers/apps/operations/ops_progress_util_test.go
  controllers/apps/operations/ops_util.go
  controllers/apps/operations/ops_util_test.go
  controllers/apps/operations/reconfigure.go
  controllers/apps/operations/reconfigure_test.go
  controllers/apps/operations/restart.go
  controllers/apps/operations/restart_test.go
  controllers/apps/operations/restore.go
  controllers/apps/operations/restore_test.go
  controllers/apps/operations/start.go
  controllers/apps/operations/start_test.go
  controllers/apps/operations/stop.go
  controllers/apps/operations/stop_test.go
  controllers/apps/operations/switchover.go
  controllers/apps/operations/switchover_test.go
  controllers/apps/operations/type.go
  controllers/apps/operations/upgrade.go
  controllers/apps/operations/upgrade_test.go
  controllers/apps/operations/util/common_util.go
  controllers/apps/operations/util/common_util_test.go
  controllers/apps/operations/vertical_scaling.go
  controllers/apps/operations/vertical_scaling_test.go
  controllers/apps/opsrequest_controller.go
  controllers/apps/opsrequest_controller_test.go
Labels: area/user-interaction, feature, approved, size/XL

#5886 fix: lorry security problems
  pkg/lorry/client/suite_test.go
  pkg/lorry/engines/kafka/thirdparty/retry.go
  pkg/lorry/util/config/decode.go
Labels: enhancement, size/L

#5888 fix: ops is always running for multi-comps cluster
  pkg/controller/component/component.go
Labels: enhancement, size/XS

#5897 fix: get lorry container
  lorry/client/client.go
  pkg/controllerutil/pod_utils.go
Labels: enhancement, size/S

#5898 chore: optimize cluster patch post start done annotation
  pkg/controller/component/component_poststart.go
  pkg/controller/component/component_poststart_test.go
Labels: size/XS

#5900 chore: redis secondary startup waiting util primary ready
  deploy/redis/scripts/redis-start.sh
Labels: size/XS

#5901 fix: etcd check role
  pkg/controller/rsm/transformer_object_generation.go
  pkg/lorry/dcs/k8s.go
Labels: enhancement, size/S

#5903 chore: fix possible NPE when resolving credential vars
  pkg/controller/builder/builder_service_descriptor.go
  pkg/controller/component/service_descriptor_utils.go
  pkg/controller/configuration/config_template_utils.go
  pkg/controller/configuration/config_template_utils_test.go
Labels: feature, enhancement, ci, size/L

#5902 chore: fix restore controller failed test case
  controllers/dataprotection/restore_controller_test.go
  controllers/dataprotection/volumepopulator_controller_test.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/manager_test.go
  pkg/testutil/dataprotection/backup_utils.go
  pkg/testutil/dataprotection/restore_factory.go
Labels: test, enhancement, size/S

#5913 fix: get replica role from db status if ha not enabled
  pkg/lorry/engines/mysql/get_replica_role.go
  pkg/lorry/engines/mysql/get_replica_role_test.go
  pkg/lorry/highavailability/util.go
Labels: enhancement, size/L

#5907 refactor: switchover opsRequest implements with componentDefinition LifeCycleAction
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/componentdefinition_webhook_test.go
  apis/apps/v1alpha1/opsrequest_webhook.go
  apis/apps/v1alpha1/opsrequest_webhook_test.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/component_utils.go
  controllers/apps/component_utils_test.go
  controllers/apps/operations/switchover.go
  controllers/apps/operations/switchover_test.go
  controllers/apps/operations/switchover_util.go
  controllers/apps/operations/switchover_util_test.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  pkg/constant/const.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
Labels: refactor, approved, size/XL

#5911 chore: remove redundant parameters in NewClusterPlanBuilder
  controllers/apps/cluster_controller.go
  controllers/apps/cluster_plan_builder.go
  controllers/apps/cluster_plan_builder_test.go
Labels: enhancement, size/XS

#5926 chore: optimize redis default acl and sentinel startup script
  deploy/redis/scripts/redis-sentinel-start.sh
  deploy/redis/scripts/redis-start.sh
  deploy/redis/templates/clusterdefinition.yaml
Labels: size/S

#5927 chore: remove the table of contents in the readme
  README.md
Labels: documentation, size/S

#5930 chore: fix pcregrep file is too long for the internal buffer
  .github/workflows/cicd-push.yml
Labels: enhancement, approved, size/S

#5935 chore: release kubeblocks dev
  .github/workflows/release-image.yml
Labels: release, approved, size/S

#5937 docs: change pic
  README.md
  docs/img/banner-readme.jpeg
  docs/img/banner-readme.png
Labels: documentation, approved, size/XS

#5938 chore: remove useless workload builder functions
  controllers/apps/transformer_component_workload.go
  pkg/controller/component/component_definition_convertor.go
  pkg/controller/component/component_definition_convertor_test.go
  pkg/controller/configuration/tool_image_builder_test.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_rsm.go
  pkg/controller/factory/builder_test.go
Labels: approved, size/XL

#5921 chore: decouple kb and addon upgrade version
  .gitignore
  deploy/helm/depend-charts/snapshot-controller-1.7.2.tgz
  deploy/helm/templates/_addon.tpl
  deploy/helm/templates/addons/pulsar-addon.yaml
  deploy/helm/values.yaml
  pkg/lorry/engines/mysql/get_replica_role_test.go
Labels: size/M

#5948 chore: change e2e kbcli default to eks
  .github/workflows/e2e-kbcli.yml
Labels: approved, size/XS

#5947 chore: support oracle readinessProbe and kbcli cluster connect
  deploy/oracle-cluster/.helmignore
  deploy/oracle-cluster/Chart.yaml
  deploy/oracle-cluster/templates/NOTES.txt
  deploy/oracle-cluster/templates/_helpers.tpl
  deploy/oracle-cluster/templates/cluster.yaml
  deploy/oracle-cluster/templates/rbac.yaml
  deploy/oracle-cluster/templates/validate.yaml
  deploy/oracle-cluster/values.schema.json
  deploy/oracle-cluster/values.yaml
  deploy/oracle/.helmignore
  deploy/oracle/Chart.yaml
  deploy/oracle/templates/NOTES.txt
  deploy/oracle/templates/_helpers.tpl
  deploy/oracle/templates/clusterdefinition.yaml
  deploy/oracle/templates/clusterversion.yaml
  deploy/oracle/values.yaml
  lorry/engine/engine.go
  lorry/engine/oracle.go
Labels: size/L

#5954 feat: set component number
  pkg/cli/cmd/cluster/create.go
Labels: feature, size/S

#5955 feat: upload embed charts for go package
  .gitignore
  pkg/cli/cluster/charts/apecloud-mysql-cluster.tgz
  pkg/cli/cluster/charts/kafka-cluster.tgz
  pkg/cli/cluster/charts/llm-cluster.tgz
  pkg/cli/cluster/charts/mongodb-cluster.tgz
  pkg/cli/cluster/charts/postgresql-cluster.tgz
  pkg/cli/cluster/charts/redis-cluster.tgz
  pkg/cli/cluster/charts/xinference-cluster.tgz
Labels: feature, size/XS

#5959 chore: add oceanbase addon yaml
  deploy/helm/templates/addons/oceanbase-addon.yaml
Labels: size/XS

#5961 fix: immutableParameters set STATIC (#5945)
  pkg/cli/cluster/charts/apecloud-mysql-cluster.tgz
  pkg/cli/cluster/charts/kafka-cluster.tgz
  pkg/cli/cluster/charts/llm-cluster.tgz
  pkg/cli/cluster/charts/mongodb-cluster.tgz
  pkg/cli/cluster/charts/postgresql-cluster.tgz
  pkg/cli/cluster/charts/redis-cluster.tgz
  pkg/cli/cluster/charts/xinference-cluster.tgz
  pkg/cli/cmd/cluster/config_observer.go
Labels: enhancement, size/S

#5963 chore: rename cv name from ac-mysql-8.0.30-auditlog to ac-mysql-8.0.31 (#5960)
  deploy/apecloud-mysql/templates/clusterversion-auditlog.yaml
  deploy/apecloud-mysql/values.yaml
Labels: size/XS
