Repository apecloud/kubeblocks, pull requests merged in 2023-10, with the labels that each got.

#5315 fix: supply the docker error info when playground init locally failed
  internal/cli/util/version.go
Labels: documentation, enhancement, size/S

#5311 chore: refine configuration reconcile and phase
  apis/apps/v1alpha1/config.go
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  controllers/apps/configuration/configuration_controller.go
  controllers/apps/configuration/reconcile_task.go
  controllers/apps/operations/reconfigure.go
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
  internal/controller/configuration/pipeline.go
  internal/controllerutil/config_util.go
  internal/controllerutil/config_util_test.go
Labels: ci, approved, size/L

#5271 docs: add minio
  docs/img/backup-and-restore-configure-backuprepo-minio.png
  docs/node_modules/.yarn-integrity
  docs/user_docs/backup-and-restore/backup/backup-repo.md
  docs/user_docs/kubeblocks-for-mysql/configuration/configuration.md
  docs/yarn.lock
Labels: documentation, approved, size/L

#5324 docs: fix typo in mongodb config doc
  docs/user_docs/kubeblocks-for-mongodb/configuration/configuration.md
Labels: documentation, enhancement, size/XS

#5323 chore: improved prompt message for configuration reconcile
  controllers/apps/configuration/configuration_controller.go
  controllers/apps/configuration/reconcile_task.go
Labels: ci, approved, size/M

#5306 chore: improve the code refactored for backup
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  apis/dataprotection/v1alpha1/restore_types.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  config/crd/bases/dataprotection.kubeblocks.io_restores.yaml
  controllers/apps/cluster_controller.go
  controllers/apps/components/component.go
  controllers/apps/transformer_backup_policy_tpl.go
  controllers/dataprotection/actionset_controller.go
  controllers/dataprotection/backup_controller_test.go
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_restores.yaml
  internal/cli/cmd/backuprepo/list.go
  internal/controller/plan/restore.go
  internal/dataprotection/action/action_create_vs.go
  internal/dataprotection/action/action_job.go
  internal/dataprotection/action/utils.go
  internal/dataprotection/backup/deleter.go
  internal/dataprotection/restore/builder.go
  internal/dataprotection/restore/manager.go
  internal/dataprotection/utils/utils.go
  internal/testutil/apps/common_util.go
  internal/testutil/apps/constant.go
  internal/testutil/dataprotection/restore_factory.go
  test/e2e/envcheck/envcheck.go
  test/integration/controller_suite_test.go
Labels: refactor, approved, size/L

#5327 chore: adjust milestone setting rules
  .github/workflows/milestone-set.yaml
  .github/workflows/milestoneclose.yml
Labels: approved, size/S

#5319 feat: support to specify volume mode when creating clusters
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/cluster_types_test.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  controllers/apps/components/component.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  internal/controller/factory/builder.go
Labels: area/user-interaction, feature, ci, approved, size/M

#5333 feat: support to specify volume mode when creating clusters
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/cluster_types_test.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  controllers/apps/components/base_stateful.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
Labels: feature, ci, size/M

#5334 fix: reduce mongodb log size
  cmd/probe/internal/dcs/k8s.go
  cmd/probe/internal/dcs/types.go
  cmd/probe/internal/highavailability/ha.go
Labels: enhancement, size/S

#5330 docs: add installation content
  docs/user_docs/installation/install-with-helm/install-kubeblocks-with-helm.md
  docs/user_docs/installation/install-with-kbcli/install-kubeblocks-with-kbcli.md
  docs/user_docs/resource-scheduling/resource-scheduling.md
Labels: documentation, size/XS

#5240 feat: cli support describe backuppolicy
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli_cluster.md
  docs/user_docs/cli/kbcli_cluster_describe-backup-policy.md
  internal/cli/cmd/cluster/cluster.go
  internal/cli/cmd/cluster/dataprotection.go
  internal/cli/cmd/cluster/dataprotection_test.go
Labels: feature, size/L

#5337 fix: create snapshot failed on GKE
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
Labels: enhancement, size/S

#5237 fix: fix orioledb patroni etcd dependency with Service Reference
  deploy/etcd/templates/clusterdefinition.yaml
  deploy/orioledb-cluster/templates/cluster.yaml
  deploy/orioledb-cluster/values.schema.json
  deploy/orioledb-cluster/values.yaml
  deploy/orioledb/config/etcd-serve-config.tpl
  deploy/orioledb/templates/clusterdefinition.yaml
  deploy/orioledb/templates/etcd-configmap.yaml
  deploy/orioledb/templates/scripts.yaml
  internal/cli/cmd/cluster/create_util.go
Labels: enhancement, dependencies, size/M

#5326 chore: move backup cmd into dataprotection cmd
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli.md
  docs/user_docs/cli/kbcli_dataprotection.md
  docs/user_docs/cli/kbcli_dataprotection_backup.md
  docs/user_docs/cli/kbcli_dataprotection_delete-backup.md
  docs/user_docs/cli/kbcli_dataprotection_describe-backup.md
  docs/user_docs/cli/kbcli_dataprotection_list-backups.md
  docs/user_docs/cli/kbcli_dataprotection_restore.md
  internal/cli/cmd/backup/create.go
  internal/cli/cmd/backup/describe.go
  internal/cli/cmd/backup/list.go
  internal/cli/cmd/cli.go
  internal/cli/cmd/dataprotection/backup.go
  internal/cli/cmd/dataprotection/dataprotection.go
  internal/cli/cmd/dataprotection/restore.go
Labels: size/XL

#5344 chore: check and install controller-gen as required version
  Makefile
Labels: size/S

#5346 fix: volume expansion opsrequest will be probabilistic failure on GKE/EKS
  controllers/apps/operations/volume_expansion_test.go
  controllers/apps/operations/volume_expansion_updater.go
Labels: enhancement, size/S

#5348 chore: update postgresql image pgvector version to v0.5.0
  deploy/postgresql/templates/clusterversion.yaml
  deploy/postgresql/values.yaml
Labels: size/M

#5357 chore: add ha switch
  internal/constant/env.go
  lorry/binding/mysql/mysql.go
  lorry/binding/operation_volume_protection.go
  lorry/dcs/dcs.go
  lorry/dcs/k8s.go
  lorry/dcs/types.go
  lorry/highavailability/ha.go
Labels: size/L

#5364 chore: add mongodb new version
  deploy/mongodb/templates/clusterversion.yaml
Labels: size/S

#5253 feat: add pg rewind
  lorry/component/postgres/local_command.go
  lorry/component/postgres/officalpostgres/manager.go
  lorry/component/postgres/officalpostgres/manager_test.go
  lorry/component/postgres/query.go
  lorry/component/postgres/query_test.go
  lorry/component/postgres/types.go
Labels: feature, approved, size/L

#5368 chore: remove merge releasing branch
  .github/workflows/release-version.yml
Labels: approved, size/XS

#5362 docs: fix typo in mongodb example doc
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/scale-for-apecloud-mongodb.md
Labels: documentation, enhancement, size/XS

#5198 fix: fix register cluster create panic
  deploy/risingwave-cluster/values.schema.json
  docs/user_docs/cli/kbcli_cluster_register.md
  internal/cli/cluster/external_charts.go
  internal/cli/cmd/backuprepo/create.go
  internal/cli/cmd/cluster/config_observer.go
  internal/cli/cmd/cluster/config_ops.go
  internal/cli/cmd/cluster/connect.go
  internal/cli/cmd/cluster/create_subcmds.go
  internal/cli/cmd/cluster/create_util.go
  internal/cli/cmd/cluster/create_util_test.go
  internal/cli/cmd/cluster/operations.go
  internal/cli/cmd/cluster/register.go
  internal/cli/util/flags/flags.go
  internal/cli/util/flags/flags_test.go
  internal/cli/util/flags/suite_test.go
Labels: enhancement, approved, size/XL

#5342 feat: support volume populator for restore
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  apis/dataprotection/v1alpha1/types.go
  cmd/dataprotection/main.go
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  config/crd/bases/dataprotection.kubeblocks.io_restores.yaml
  config/rbac/role.yaml
  controllers/apps/cluster_controller_test.go
  controllers/apps/opsrequest_controller_test.go
  controllers/dataprotection/restore_controller.go
  controllers/dataprotection/suite_test.go
  controllers/dataprotection/types.go
  controllers/dataprotection/utils.go
  controllers/dataprotection/volumepopulator_controller.go
  controllers/dataprotection/volumepopulator_controller_test.go
  deploy/helm/config/rbac/role.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_restores.yaml
  docs/user_docs/cli/kbcli_cluster_backup.md
  docs/user_docs/cli/kbcli_cluster_restore.md
  go.mod
  internal/cli/cmd/cluster/dataprotection.go
  internal/controller/plan/restore_test.go
  internal/dataprotection/restore/builder.go
  internal/dataprotection/restore/manager.go
  internal/dataprotection/restore/types.go
  internal/dataprotection/restore/utils.go
  internal/dataprotection/types/constant.go
  internal/dataprotection/utils/envvar.go
  internal/generics/type.go
  internal/testutil/apps/pvc_factoy.go
  internal/testutil/dataprotection/backup_utils.go
  internal/testutil/dataprotection/constant.go
  internal/testutil/dataprotection/restore_factory.go
Labels: area/user-interaction, feature, approved, size/XXL

#5379 chore: remove the failure check for volumeExpansion opsRequest
  cmd/manager/main.go
  controllers/apps/operations/suite_test.go
  controllers/apps/operations/volume_expansion_test.go
  controllers/apps/operations/volume_expansion_updater.go
  controllers/apps/opsrequest_controller.go
  controllers/k8score/pvc_controller.go
  controllers/k8score/pvc_controller_test.go
  controllers/k8score/suite_test.go
Labels: size/L

#5382 chore: bump go version to 1.21 in go.mod
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  Makefile
  go.mod
  go.sum
Labels: dependencies, approved, size/M

#5377 fix: update backup policy's backup repo with cluster's backup repo…
  controllers/apps/cluster_controller_test.go
  controllers/apps/transformer_backup_policy_tpl.go
Labels: bug, enhancement, size/S

#5310 feat: baichuan2 13b
  deploy/vllm/templates/clusterdefinition.yaml
  deploy/vllm/templates/clusterversion.yaml
  deploy/vllm/templates/scripts.yaml
Labels: feature, size/M

#5397 fix: mysql xtrabackup failed and restore failed
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  config/crd/bases/dataprotection.kubeblocks.io_restores.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_restores.yaml
  internal/dataprotection/restore/builder.go
  internal/dataprotection/restore/manager.go
Labels: enhancement, size/S

#5353 fix: fix role probe failed when roleUpdateMechanism is readinessProbeEventUpdate
  cmd/lorry/main.go
  docker/Dockerfile-probe
  docker/Dockerfile-tools
  internal/controller/component/probe_utils.go
  internal/controller/rsm/transformer_object_generation.go
  internal/controller/rsm/types.go
  lorry/binding/custom/custom.go
  lorry/binding/mongodb/mongodb_test.go
  lorry/client/client_test.go
  lorry/middleware/grpc/gprc_server.go
  lorry/middleware/grpc/grpc_server_test.go
  lorry/middleware/probe/checks_middleware.go
  lorry/middleware/probe/checks_middleware_test.go
  lorry/middleware/probe/router.go
  lorry/middleware/probe/router_test.go
Labels: enhancement, approved, size/L

#5399 chore: add e2e test cases
  Makefile
  test/e2e/testdata/smoketest/clickhouse/00_clickhousecluster.yaml
  test/e2e/testdata/smoketest/clickhouse/00_milvuscluster.yaml
  test/e2e/testdata/smoketest/clickhouse/01_vscale.yaml
  test/e2e/testdata/smoketest/clickhouse/02_hscale_out.yaml
  test/e2e/testdata/smoketest/clickhouse/03_hscale_in.yaml
  test/e2e/testdata/smoketest/clickhouse/04_vexpand.yaml
  test/e2e/testdata/smoketest/clickhouse/05_stop.yaml
  test/e2e/testdata/smoketest/clickhouse/06_start.yaml
  test/e2e/testdata/smoketest/clickhouse/07_restart.yaml
  test/e2e/testdata/smoketest/elasticsearch/00_elasticsearchcluster.yaml
  test/e2e/testdata/smoketest/elasticsearch/01_vscale.yaml
  test/e2e/testdata/smoketest/elasticsearch/02_hscale_out.yaml
  test/e2e/testdata/smoketest/elasticsearch/03_hscale_in.yaml
  test/e2e/testdata/smoketest/elasticsearch/04_vexpand.yaml
  test/e2e/testdata/smoketest/elasticsearch/05_stop.yaml
  test/e2e/testdata/smoketest/elasticsearch/06_start.yaml
  test/e2e/testdata/smoketest/elasticsearch/07_restart.yaml
  test/e2e/testdata/smoketest/llm/00_llmcluster.yaml
  test/e2e/testdata/smoketest/llm/01_vscale.yaml
  test/e2e/testdata/smoketest/llm/02_hscale_out.yaml
  test/e2e/testdata/smoketest/llm/03_hscale_in.yaml
  test/e2e/testdata/smoketest/llm/04_vexpand.yaml
  test/e2e/testdata/smoketest/llm/05_stop.yaml
  test/e2e/testdata/smoketest/llm/06_start.yaml
  test/e2e/testdata/smoketest/llm/07_restart.yaml
  test/e2e/testdata/smoketest/milvus/00_milvuscluster.yaml
  test/e2e/testdata/smoketest/milvus/01_vscale.yaml
  test/e2e/testdata/smoketest/milvus/02_hscale_out.yaml
  test/e2e/testdata/smoketest/milvus/03_hscale_in.yaml
  test/e2e/testdata/smoketest/milvus/04_vexpand.yaml
  test/e2e/testdata/smoketest/milvus/05_stop.yaml
  test/e2e/testdata/smoketest/milvus/06_start.yaml
  test/e2e/testdata/smoketest/milvus/07_restart.yaml
  test/e2e/testdata/smoketest/opensearch/00_opensearchcluster.yaml
  test/e2e/testdata/smoketest/opensearch/01_vscale.yaml
  test/e2e/testdata/smoketest/opensearch/02_vexpand.yaml
  test/e2e/testdata/smoketest/opensearch/03_stop.yaml
  test/e2e/testdata/smoketest/opensearch/04_start.yaml
  test/e2e/testdata/smoketest/opensearch/05_restart.yaml
  test/e2e/testdata/smoketest/tdengine/00_tdenginecluster.yaml
  test/e2e/testdata/smoketest/tdengine/01_vexpand.yaml
  test/e2e/testdata/smoketest/tdengine/02_stop.yaml
  test/e2e/testdata/smoketest/tdengine/03_start.yaml
  test/e2e/testdata/smoketest/tdengine/04_vscale.yaml
  test/e2e/testdata/smoketest/tdengine/05_restart.yaml
  test/e2e/testdata/smoketest/tdengine/06_hscale_out.yaml
  test/e2e/testdata/smoketest/tdengine/07_hscale_in.yaml
Labels: test, size/XL

#5391 feat: check if supports volume snapshot by VolumeSnapshotClass rather than a n environment variable
  cmd/dataprotection/main.go
  cmd/manager/main.go
  controllers/apps/cluster_controller_test.go
  controllers/apps/components/hscale_volume_populator.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  internal/cli/cmd/kubeblocks/config_test.go
  internal/controllerutil/suite_test.go
  internal/controllerutil/volumesnapshot.go
  internal/controllerutil/volumesnapshot_test.go
  internal/dataprotection/action/action_create_vs.go
  internal/dataprotection/backup/deleter.go
  internal/dataprotection/backup/request.go
  internal/dataprotection/builder/builder.go
  internal/dataprotection/builder/builder_test.go
  internal/dataprotection/builder/suite_test.go
  internal/dataprotection/utils/utils.go
  internal/generics/type.go
  internal/testutil/apps/constant.go
  internal/testutil/apps/native_object_util.go
  internal/testutil/k8s/storage_util.go
  internal/testutil/type.go
  test/integration/controller_suite_test.go
Labels: area/user-interaction, feature, size/L

#5398 feat: reject to shrink volume at cluster controller
  controllers/apps/components/component.go
  controllers/apps/components/component_test.go
  controllers/apps/components/suite_test.go
  controllers/apps/components/utils_test.go
  internal/controller/graph/dag.go
  internal/controller/graph/dag_test.go
  internal/testutil/apps/pv_factoy.go
  internal/testutil/apps/pvc_factoy.go
Labels: feature, approved, size/XL

#5341 feat: cluster describe use new backup crd
  internal/cli/cluster/cluster.go
  internal/cli/cluster/types.go
  internal/cli/cmd/cluster/describe.go
  internal/cli/cmd/cluster/describe_test.go
  internal/cli/testing/fake.go
  internal/cli/types/types.go
Labels: feature, size/L

#5403 fix: merge dags lost the dependencies of sub-dags
  internal/controller/graph/dag.go
  internal/controller/graph/dag_test.go
Labels: enhancement, ci, size/S

#5405 fix: hide kbcli cloud related commands
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli.md
  docs/user_docs/cli/kbcli_context.md
  docs/user_docs/cli/kbcli_context_current.md
  docs/user_docs/cli/kbcli_context_describe.md
  docs/user_docs/cli/kbcli_context_list.md
  docs/user_docs/cli/kbcli_context_use.md
  docs/user_docs/cli/kbcli_login.md
  docs/user_docs/cli/kbcli_logout.md
  docs/user_docs/cli/kbcli_org.md
  docs/user_docs/cli/kbcli_org_current.md
  docs/user_docs/cli/kbcli_org_describe.md
  docs/user_docs/cli/kbcli_org_list.md
  docs/user_docs/cli/kbcli_org_switch.md
  go.mod
  internal/cli/cmd/cli.go
Labels: enhancement, size/XL

#5388 fix: calling getEnvByName: illegal base64 data at input byte 8
  deploy/milvus/configs/milvus-user.yaml.tpl
  internal/controller/configuration/builtin_env.go
  internal/controller/configuration/builtin_env_test.go
Labels: enhancement, size/S

#5410 fix: update mongodb checkrole
  deploy/mongodb/templates/clusterdefinition.yaml
  internal/constant/const.go
  internal/constant/env.go
  internal/controller/component/component_test.go
  internal/controller/component/lorry_utils.go
  internal/controller/component/lorry_utils_test.go
  internal/controller/plan/prepare_test.go
  lorry/binding/utils.go
Labels: enhancement, size/L

#5380 fix: fix playground timed out waiting for the condition
  docs/user_docs/cli/kbcli_playground_destroy.md
  internal/cli/cmd/kubeblocks/install.go
  internal/cli/cmd/playground/destroy.go
  internal/cli/cmd/playground/init.go
Labels: enhancement, approved, size/M

#5421 fix: lorry client
  controllers/apps/systemaccount_controller.go
  internal/constant/const.go
  internal/controller/component/lorry_utils.go
  internal/controller/component/lorry_utils_test.go
  internal/controllerutil/pod_utils.go
  lorry/client/client.go
  lorry/client/client_test.go
Labels: enhancement, size/M

#5424 chore: make csi-s3 compatible with the huawei cloud
  deploy/csi-s3/templates/attacher.yaml
  deploy/csi-s3/templates/csi-s3.yaml
  deploy/csi-s3/templates/provisioner.yaml
  deploy/csi-s3/values.yaml
  deploy/helm/templates/addons/csi-s3-addon.yaml
Labels: size/M

#5428 fix: hscale out failed for Failed to set default snapshot class
  internal/dataprotection/action/action_create_vs.go
Labels: bug, enhancement, size/M

#5434 chore: helm vllm cluster
  deploy/vllm-cluster/.helmignore
  deploy/vllm-cluster/Chart.yaml
  deploy/vllm-cluster/templates/NOTES.txt
  deploy/vllm-cluster/templates/_helpers.tpl
  deploy/vllm-cluster/templates/cluster.yaml
  deploy/vllm-cluster/templates/rbac.yaml
  deploy/vllm-cluster/templates/validate.yaml
  deploy/vllm-cluster/values.schema.json
  deploy/vllm-cluster/values.yaml
Labels: size/L

#5430 fix: fix grpc.serve block bug
  cmd/lorry/main.go
Labels: bug, enhancement, approved, size/S

#5443 fix: modify official pg setup script
  deploy/official-postgresql/scripts/setup.sh
Labels: bug, ci, size/XS

#5436 docs: update installation docs
  docs/user_docs/installation/install-with-helm/install-kubeblocks-with-helm.md
  docs/user_docs/installation/install-with-kbcli/install-kbcli.md
  docs/user_docs/installation/install-with-kbcli/install-kubeblocks-with-kbcli.md
  docs/user_docs/installation/uninstall-kbcli-and-kubeblocks.md
Labels: documentation, size/L

#5449 chore: remove unused old LLM addon
  deploy/helm/templates/addons/llm-addon.yaml
  deploy/llm-cluster/.helmignore
  deploy/llm-cluster/Chart.yaml
  deploy/llm-cluster/templates/NOTES.txt
  deploy/llm-cluster/templates/_helpers.tpl
  deploy/llm-cluster/templates/cluster.yaml
  deploy/llm-cluster/values.yaml
  deploy/llm/.helmignore
  deploy/llm/Chart.yaml
  deploy/llm/templates/NOTES.txt
  deploy/llm/templates/_helpers.tpl
  deploy/llm/templates/clusterdefinition.yaml
  deploy/llm/templates/clusterversion-chatglm2-6b.yaml
  deploy/llm/templates/clusterversion-openchat.yaml
  deploy/llm/templates/clusterversion-vicuna-13b.yaml
  deploy/llm/templates/configmap.yaml
  deploy/llm/values.yaml
Labels: dependencies, size/XL

#5445 chore: add test cases for restore
  controllers/dataprotection/restore_controller.go
  controllers/dataprotection/restore_controller_test.go
  controllers/dataprotection/suite_test.go
  controllers/dataprotection/volumepopulator_controller_test.go
  internal/dataprotection/restore/builder.go
  internal/dataprotection/restore/manager.go
  internal/dataprotection/restore/manager_test.go
  internal/dataprotection/restore/suite_test.go
  internal/dataprotection/restore/utils.go
  internal/testutil/dataprotection/constant.go
  internal/testutil/dataprotection/restore_factory.go
  test/testdata/backup/actionset.yaml
Labels: test, approved, size/XXL

#5454 chore: change e2e default cloud provider
  .github/workflows/e2e-fault.yml
  .github/workflows/e2e-kbcli.yml
  .github/workflows/e2e-performance.yml
  .github/workflows/e2e-smoke.yml
  .github/workflows/merge-e2e-smoke.yml
Labels: approved, size/M

#5451 feat: switch to using the datasafed tool for backup/restore scripts
  apis/dataprotection/v1alpha1/backuprepo_types.go
  config/crd/bases/dataprotection.kubeblocks.io_backuprepos.yaml
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/backuprepo_controller.go
  controllers/dataprotection/backuprepo_controller_test.go
  controllers/dataprotection/volumepopulator_controller.go
  deploy/apecloud-mysql/dataprotection/backup.sh
  deploy/apecloud-mysql/dataprotection/restore.sh
  deploy/helm/crds/dataprotection.kubeblocks.io_backuprepos.yaml
  deploy/helm/templates/addons/csi-s3-addon.yaml
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/storageprovider/cos.yaml
  deploy/helm/templates/storageprovider/gcs.yaml
  deploy/helm/templates/storageprovider/minio.yaml
  deploy/helm/templates/storageprovider/obs.yaml
  deploy/helm/templates/storageprovider/oss.yaml
  deploy/helm/templates/storageprovider/s3.yaml
  deploy/helm/values.yaml
  deploy/mongodb/dataprotection/backup-info-collector.sh
  deploy/mongodb/dataprotection/datafile-backup.sh
  deploy/mongodb/dataprotection/datafile-restore.sh
  deploy/mongodb/dataprotection/mongodump-backup.sh
  deploy/mongodb/dataprotection/mongodump-restore.sh
  deploy/mongodb/dataprotection/pitr-backup.sh
  deploy/mongodb/scripts/replicaset-restore.tpl
  deploy/oracle-mysql/templates/actionset-xtrabackup.yaml
  deploy/postgresql/dataprotection/backup-info-collector.sh
  deploy/postgresql/dataprotection/pg-basebackup-backup.sh
  deploy/postgresql/dataprotection/pg-basebackup-restore.sh
  deploy/postgresql/templates/actionset-pgbasebackup.yaml
  deploy/qdrant/scripts/qdrant-backup.sh
  deploy/qdrant/scripts/qdrant-restore.sh
  deploy/redis/dataprotection/backup.sh
  deploy/redis/dataprotection/restore.sh
  deploy/redis/templates/backupactionset.yaml
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli_backuprepo.md
  docs/user_docs/cli/kbcli_backuprepo_create.md
  docs/user_docs/cli/kbcli_backuprepo_describe.md
  docs/user_docs/cli/kbcli_backuprepo_list.md
  internal/cli/cmd/backuprepo/create.go
  internal/cli/cmd/backuprepo/create_test.go
  internal/cli/cmd/backuprepo/describe.go
  internal/cli/cmd/backuprepo/list.go
  internal/cli/cmd/cluster/dataprotection.go
  internal/cli/testing/fake.go
  internal/dataprotection/backup/deleter.go
  internal/dataprotection/backup/request.go
  internal/dataprotection/backup/utils.go
  internal/dataprotection/errors/errors.go
  internal/dataprotection/errors/errors_test.go
  internal/dataprotection/restore/builder.go
  internal/dataprotection/restore/manager.go
  internal/dataprotection/restore/manager_test.go
  internal/dataprotection/types/constant.go
  internal/dataprotection/utils/backuprepo.go
  internal/testutil/dataprotection/backup_utils.go
Labels: feature, approved, size/XXL

#5455 docs: update version
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/delete-mongodb-cluster.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/expand-volume.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/scale-for-apecloud-mongodb.md
Labels: documentation, approved, size/S

#5474 fix: fix the restore script for qdrant
  deploy/mongodb/templates/actionset-datafile.yaml
  deploy/mongodb/templates/actionset-dump.yaml
  deploy/qdrant/scripts/qdrant-restore.sh
  deploy/qdrant/templates/actionset-datafile.yaml
Labels: enhancement, size/S

#5422 fix: orioledb create fail by `kbcli cluster create --cluster-definition`
  docs/user_docs/cli/kbcli_cluster_create.md
  internal/cli/cluster/helper.go
  internal/cli/cluster/helper_test.go
  internal/cli/cmd/cluster/create.go
  internal/cli/cmd/cluster/create_test.go
  internal/cli/testing/fake.go
Labels: enhancement, size/L

#5478 chore: upgrade golangci lint version
  .github/workflows/cicd-pull-request.yml
  .github/workflows/release-version.yml
  Makefile
Labels: ci, approved, size/XS

#5476 fix: update mongodb memberUpdateStrategy
  deploy/mongodb/templates/clusterdefinition.yaml
Labels: test, enhancement, size/XS

#5481 chore: rename the gcs storage provider to gcs-s3comp
  deploy/helm/templates/storageprovider/gcs-s3comp.yaml
Labels: size/XS

#5394 chore: manipulate lifecycle objects by graph client
  controllers/apps/cluster_controller_test.go
  controllers/apps/cluster_plan_builder.go
  controllers/apps/components/component.go
  controllers/apps/components/component_test.go
  controllers/apps/components/component_workload_builder.go
  controllers/apps/components/utils.go
  controllers/apps/components/utils_test.go
  controllers/apps/suite_test.go
  controllers/apps/transform_restore.go
  controllers/apps/transform_utils.go
  controllers/apps/transformer_assure_meta.go
  controllers/apps/transformer_backup_policy_tpl.go
  controllers/apps/transformer_cluster_credential.go
  controllers/apps/transformer_cluster_deletion.go
  controllers/apps/transformer_cluster_status.go
  controllers/apps/transformer_component.go
  controllers/apps/transformer_halt_recovering.go
  controllers/apps/transformer_init.go
  controllers/apps/transformer_ownership.go
  controllers/apps/transformer_rbac.go
  controllers/apps/transformer_rbac_test.go
  controllers/apps/transformer_secret.go
  controllers/apps/transformer_validate_and_load_ref_resources.go
  controllers/apps/transformer_validate_enable_logs.go
  internal/cli/cmd/builder/template/component_wrapper.go
  internal/controller/graph/dag.go
  internal/controller/graph/dag_test.go
  internal/controller/model/graph_client.go
  internal/controller/model/graph_client_test.go
  internal/controller/model/transform_types.go
  internal/controller/model/transform_types_test.go
  internal/controller/model/transform_utils.go
  internal/controller/model/transform_utils_test.go
  internal/controller/rsm/plan_builder.go
  internal/controller/rsm/plan_builder_test.go
  internal/controller/rsm/suite_test.go
  internal/controller/rsm/transformer_fix_meta_test.go
  internal/controller/rsm/transformer_init.go
  internal/controller/rsm/transformer_init_test.go
  internal/controller/rsm/transformer_member_reconfiguration.go
  internal/controller/rsm/transformer_member_reconfiguration_test.go
  internal/controller/rsm/transformer_objection_generation_test.go
  internal/controller/types/lifecycle_vertex.go
Labels: area/cluster-controller, approved, size/XXL

#5417 chore: mvoe minio image to aliyun, and chart to jihulab
  deploy/helm/templates/addons/minio.yaml
Labels: size/XS

#5486 chore: fix qdrant cluster create OOM
  deploy/qdrant-cluster/templates/cluster.yaml
  deploy/qdrant/templates/clusterdefinition.yaml
Labels: enhancement, size/XS

#5479 chore: use new aliyun image registry
  config/samples/extensions_v1alpha1_addon.yaml
  deploy/apecloud-mysql/templates/actionset.yaml
  deploy/apecloud-mysql/values.yaml
  deploy/apecloud-postgresql/values.yaml
  deploy/bytebase/templates/auto-plugin.yaml
  deploy/bytebase/values.yaml
  deploy/cert-manager/templates/cert-manager.yaml
  deploy/chatgpt-retrieval-plugin/values.yaml
  deploy/csi-hostpath-driver/values.yaml
  deploy/csi-s3/values.yaml
  deploy/delphic/values.yaml
  deploy/helm/templates/addons/chaos-mesh-addon.yaml
  deploy/helm/values.yaml
  deploy/jupyter-notebook/values.yaml
  deploy/mongodb/values.yaml
  deploy/mysql/values.yaml
  deploy/neon-cluster/templates/vm-compute-node-deploy.yaml
  deploy/nyancat/values.yaml
  deploy/orioledb/values.yaml
  deploy/postgresql/values.yaml
  deploy/pulsar/values.yaml
  deploy/qdrant/values.yaml
  deploy/redis/values.yaml
  deploy/tdengine/values.yaml
  internal/controller/component/lorry_utils.go
  internal/controller/factory/builder.go
  internal/dataprotection/utils/periodical_enqueue_source_test.go
  internal/dataprotection/utils/suit_test.go
  test/e2e/testdata/smoketest/postgresql/07_cv.yaml
  test/testdata/backup/actionset.yaml
  test/testdata/backup/pitr_backuptool.yaml
Labels: approved, size/L

#5488 chore: download model in cn
  deploy/vllm/templates/clusterversion.yaml
  deploy/vllm/templates/scripts.yaml
Labels: size/S

#5467 fix: failed to reconfigure for the stateless component (#5439)
  controllers/apps/components/component.go
  controllers/apps/configuration/config_reconcile_wrapper.go
  controllers/apps/configuration/policy_util.go
  controllers/apps/configuration/reconfigure_controller.go
  controllers/apps/configuration/reconfigure_policy.go
  controllers/apps/configuration/simple_policy.go
Labels: enhancement, approved, size/M

#5425 fix: failed to reconfigure for weaviate
  internal/configuration/core/config_util.go
  internal/configuration/core/config_util_test.go
Labels: enhancement, approved, size/M

#5494 chore: vllm addon
  deploy/helm/templates/addons/vllm-addon.yaml
Labels: size/M

#5497 chore: add kbcli workflow test type
  .github/workflows/e2e-kbcli.yml
Labels: area/test, test, size/XS

#5499 fix: fix orioledb service port
  deploy/orioledb/templates/clusterdefinition.yaml
Labels: enhancement, size/XS

#5446 fix: backup example error
  docs/user_docs/cli/kbcli_cluster_backup.md
  docs/user_docs/cli/kbcli_cluster_describe-backup-policy.md
  docs/user_docs/cli/kbcli_cluster_edit-backup-policy.md
  docs/user_docs/cli/kbcli_cluster_restore.md
  internal/cli/cmd/cluster/dataprotection.go
  internal/cli/cmd/cluster/dataprotection_test.go
Labels: enhancement, size/L

#5503 chore: set GO_VERSION for release
  .github/workflows/release-version.yml
Labels: release, approved, size/XS

#5493 chore: removed dynamically changeable parameters from the immutableParameters list (#5471)
  deploy/apecloud-mysql/config/mysql8-config-effect-scope.yaml
Labels: size/M

#5512 chore: fix csi-hostpath-driver enable error
  deploy/csi-hostpath-driver/templates/statefulset.yaml
  deploy/csi-hostpath-driver/values.yaml
Labels: enhancement, approved, size/M

#5518 fix: controller crash on nil service
  internal/controller/rsm/transformer_object_generation.go
  internal/controller/rsm/transformer_objection_generation_test.go
Labels: enhancement, size/S

#5519 chore: remove invalid backup config parameters
  controllers/apps/cluster_controller_test.go
  deploy/helm/templates/configmap.yaml
  internal/constant/const.go
Labels: size/M

#5522 chore: move vllm and ggml to llm
  .github/workflows/e2e-kbcli.yml
  deploy/ggml/templates/clusterdefinition.yaml
  deploy/ggml/templates/clusterversion.yaml
  deploy/helm/templates/addons/llm-addon.yaml
  deploy/helm/values.yaml
  deploy/llm-cluster/.helmignore
  deploy/llm-cluster/Chart.yaml
  deploy/llm-cluster/templates/NOTES.txt
  deploy/llm-cluster/templates/_helpers.tpl
  deploy/llm-cluster/templates/cluster.yaml
  deploy/llm-cluster/templates/rbac.yaml
  deploy/llm-cluster/templates/validate.yaml
  deploy/llm-cluster/values.schema.json
  deploy/llm-cluster/values.yaml
  deploy/llm/Chart.yaml
  deploy/llm/templates/NOTES.txt
  deploy/llm/templates/_helpers.tpl
  deploy/llm/templates/clusterdefinition.yaml
  deploy/llm/templates/clusterversion.yaml
  deploy/llm/templates/scripts.yaml
  deploy/llm/values.yaml
  deploy/vllm-cluster/templates/_helpers.tpl
  deploy/vllm/Chart.yaml
  deploy/vllm/templates/NOTES.txt
  deploy/vllm/templates/_helpers.tpl
  deploy/vllm/values.yaml
Labels: size/L

#5523 fix: lorry request body missed
  cmd/lorry/main.go
  lorry/client/client.go
  lorry/component/kubernetes/client.go
  lorry/highavailability/ha.go
  lorry/middleware/probe/checks_middleware.go
  pkg/controller/rsm/transformer_object_generation.go
  pkg/controller/rsm/types.go
Labels: enhancement, size/M

#5525 chore: add missing resources for kustomization yaml
  config/crd/kustomization.yaml
  pkg/dataprotection/utils/periodical_enqueue_source_test.go
Labels: approved, size/XS

#5521 fix: reconfiguring parameters labels not exist (#5517)
  controllers/apps/operations/pipeline.go
  pkg/configuration/core/config_util.go
Labels: enhancement, size/M

#5528 chore: fix setup kubectl error
  .github/localflows/cicd-local.yml
  .github/localflows/github-action-locally.sh
  .github/workflows/cherry-pick.yml
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/codeql.yml
  .github/workflows/e2e-fault.yml
  .github/workflows/e2e-kbcli.yml
  .github/workflows/e2e-performance.yml
  .github/workflows/e2e-smoke.yml
  .github/workflows/issues-move.yml
  .github/workflows/merge-e2e-smoke.yml
  .github/workflows/milestoneclose.yml
  .github/workflows/package-version.yml
  .github/workflows/pull-request-check.yml
  .github/workflows/pull-request-user-interaction.yaml
  .github/workflows/release-create.yml
  .github/workflows/release-helm-chart.yml
  .github/workflows/release-image.yml
  .github/workflows/release-notes.yaml
  .github/workflows/release-publish.yml
  .github/workflows/release-sync.yml
  .github/workflows/release-version.yml
  .github/workflows/trigger-release.yml
Labels: enhancement, approved, size/L

#5529 chore: bump dev version to 0.8.0-alpha.0
  Makefile
Labels: dependencies, approved, size/XS

#5507 feat: support backup/restore mutil version cluster
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  apis/extensions/v1alpha1/zz_generated.deepcopy.go
  apis/storage/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  controllers/apps/cluster_controller_test.go
  controllers/apps/transformer_backup_policy_tpl.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/restore_controller.go
  controllers/dataprotection/restore_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/mongodb/templates/actionset-dump.yaml
  deploy/mongodb/templates/backuppolicytemplate.yaml
  deploy/postgresql/templates/actionset-pgbasebackup.yaml
  deploy/postgresql/templates/backuppolicytemplate.yaml
  externalapis/preflight/v1beta2/zz_generated.deepcopy.go
  pkg/cli/cmd/cluster/create_test.go
  pkg/common/expand.go
  pkg/common/expand_test.go
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/restore/builder.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/manager_test.go
  pkg/dataprotection/utils/utils.go
  pkg/testutil/apps/backuppolicytemplate_factory.go
  pkg/testutil/apps/constant.go
  pkg/testutil/dataprotection/constant.go
  test/testdata/backup/actionset.yaml
Labels: feature, size/XL

#5532 chore: change pr check pkgs
  .github/utils/utils.sh
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
Labels: approved, size/S

#5534 fix: backup failed for pgbasebackup and mongodump
  apis/dataprotection/v1alpha1/actionset_types.go
  config/crd/bases/dataprotection.kubeblocks.io_actionsets.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_actionsets.yaml
  deploy/mongodb/templates/backuppolicytemplate.yaml
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/manager_test.go
  pkg/testutil/dataprotection/restore_factory.go
  test/testdata/backup/actionset.yaml
Labels: enhancement, size/L

#5535 fix: update greptimedb and polardb-x port
  deploy/greptimedb/templates/clusterdefinition.yaml
  deploy/nebula/templates/clusterdefinition.yaml
  deploy/polardbx/templates/clusterDefintion.yaml
Labels: enhancement, size/S

#5541 chore: add ggml test type
  .github/workflows/e2e-kbcli.yml
Labels: test, approved, size/XS

#5542 fix: fix request body re-read problem
  Makefile
  lorry/client/client.go
Labels: enhancement, approved, size/S

#5538 docs: add note
  docs/user_docs/backup-and-restore/backup/backup-repo.md
  docs/user_docs/try-out-on-playground/try-kubeblocks-on-your-laptop.md
Labels: documentation, approved, size/XS

#5552 chore: get test pkgs from gh vars
  .github/utils/utils.sh
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/release-version.yml
Labels: test, approved, size/M

#5536 fix: recover missing replication related envs
  controllers/apps/components/component.go
  lorry/binding/custom/custom_test.go
  lorry/binding/types.go
  lorry/binding/utils.go
  pkg/constant/const.go
Labels: enhancement, approved, size/M

#5412 chore: more tests for cluster component
  controllers/apps/components/component.go
  controllers/apps/components/component_test.go
  pkg/testutil/k8s/storage_util.go
Labels: test, approved, size/XL

#5550 chore: ggml image to aliyun
  deploy/llm/templates/clusterversion.yaml
  deploy/llm/values.yaml
Labels: size/XS

#5563 chore: delete echo msg
  .github/utils/utils.sh
Labels: approved, size/XS

#5448 feat: backup cmd support more flags
  docs/user_docs/cli/kbcli_cluster_backup.md
  docs/user_docs/cli/kbcli_dataprotection_backup.md
  pkg/cli/cmd/cluster/dataprotection.go
  pkg/cli/cmd/cluster/dataprotection_test.go
  pkg/cli/cmd/dataprotection/backup.go
  pkg/cli/create/template/backup_template.cue
Labels: feature, size/L

#5556 fix: modify pg builtin name
  config/lorry/components/binding_postgresql.yaml
  lorry/middleware/probe/router.go
Labels: bug, approved, size/M

#5470 feat: opsrequest support more backup params
  apis/apps/v1alpha1/opsrequest_types.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/backup.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  pkg/cli/cmd/cluster/update.go
  pkg/dataprotection/utils/backup.go
Labels: feature, size/L

#5495 fix: failed create bench wihtout cluster name
  pkg/cli/cmd/bench/bench_test.go
  pkg/cli/cmd/bench/pgbench.go
  pkg/cli/cmd/bench/sysbench.go
  pkg/cli/cmd/bench/tpcc.go
  pkg/cli/cmd/bench/tpch.go
  pkg/cli/cmd/bench/ycsb.go
Labels: enhancement, size/L

#5565 chore: support check first level pkg test
  .github/utils/utils.sh
  .github/workflows/cicd-pull-request.yml
  .github/workflows/release-version.yml
Labels: test, approved, size/S

#5564 chore: fix unstable test of restore controller
  controllers/dataprotection/restore_controller_test.go
Labels: test, enhancement, approved, size/XS

#5562 fix: delete sigusr
  lorry/component/dbmanager.go
  lorry/ctl/options.go
  lorry/ctl/run.go
Labels: enhancement, approved, size/M

#5567 chore: add e2e test csi-s3 config
  Makefile
  test/e2e/Makefile
  test/e2e/e2e_suite_test.go
  test/e2e/testdata/config/backuprepo_oss.yaml
  test/e2e/testdata/config/backuprepo_s3.yaml
  test/e2e/testdata/smoketest/config.go
  test/e2e/testdata/smoketest/wesql/11_backup.yaml
  test/e2e/testdata/smoketest/wesql/11_backup_snapshot.yaml
  test/e2e/testdata/smoketest/wesql/12_backup_restore.yaml
  test/e2e/types.go
Labels: test, size/L

#5533 chore: add env SERVICE_PORT for collecting metrics by the oteld (#5527)
  deploy/apecloud-mysql/templates/clusterdefinition.yaml
  deploy/mongodb/templates/clusterdefinition.yaml
  deploy/postgresql/templates/clusterdefinition.yaml
  deploy/pulsar/templates/clusterdefinition.yaml
  deploy/redis/templates/clusterdefinition.yaml
Labels: approved, size/S

#5569 chore: support e2e test on k3s
  .github/workflows/e2e-kbcli.yml
Labels: test, approved, size/XS

#5514 feat: update backup expired time according completed time
  controllers/dataprotection/backup_controller.go
Labels: area/user-interaction, feature, size/S

#5551 chore: unified role probe framework
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/workloads/v1alpha1/replicatedstatemachine_types.go
  apis/workloads/v1alpha1/replicatedstatemachine_webhook_test.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/workloads.kubeblocks.io_replicatedstatemachines.yaml
  controllers/apps/components/component.go
  controllers/workloads/replicatedstatemachine_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/workloads.kubeblocks.io_replicatedstatemachines.yaml
  deploy/polardbx/templates/clusterDefintion.yaml
  pkg/common/types.go
  pkg/controller/builder/builder_replicated_state_machine.go
  pkg/controller/builder/builder_replicated_state_machine_test.go
  pkg/controller/component/lorry_utils.go
  pkg/controller/component/lorry_utils_test.go
  pkg/controller/factory/builder.go
  pkg/controller/rsm/suite_test.go
  pkg/controller/rsm/transformer_object_generation.go
  pkg/controller/rsm/transformer_objection_generation_test.go
  pkg/controller/rsm/types.go
Labels: size/XL, rsm, lorry

#5573 chore: supply AIGC demo in Jupyter addon
  deploy/jupyter-notebook/values.yaml
Labels: size/XS

#5575 chore: add baichuan replit-code codeshell
  deploy/llm/templates/clusterversion.yaml
  deploy/llm/values.yaml
Labels: size/M

#5555 chore: move component & workload cases out from cluster controller test
  controllers/apps/cluster_controller_test.go
  controllers/apps/component_controller_test.go
Labels: test, approved, size/XXL

#5574 chore: add clusters read privilege for nyancat
  deploy/nyancat/templates/clusterrole.yaml
Labels: size/XS

#5579 chore: distinguish between k3s and k8s workflow
  .github/workflows/cicd-pull-request.yml
  .github/workflows/e2e-kbcli.yml
  .github/workflows/release-version.yml
Labels: approved, size/S

#5583 chore: make 'Operation cannot be fulfilled on...' msg debug level
  controllers/apps/cluster_controller.go
  controllers/apps/cluster_plan_builder.go
  controllers/workloads/replicatedstatemachine_controller.go
  pkg/controller/rsm/plan_builder.go
Labels: area/cluster-controller, bug, size/M, rsm

#5588 fix: mongodb cluster member addr
  lorry/component/postgres/officalpostgres/manager_test.go
  lorry/dcs/types.go
Labels: enhancement, approved, size/S

#5594 fix: fix oracle-mysql backup actionSet
  deploy/oracle-mysql/templates/actionset-xtrabackup.yaml
Labels: enhancement, size/XS

#5572 docs: improve user document for using minio as backuprepo
  deploy/helm/templates/addons/minio.yaml
  docs/img/backup-and-restore-configure-backuprepo-minio-bucket-0.png
  docs/img/backup-and-restore-configure-backuprepo-minio-bucket-1.png
  docs/user_docs/backup-and-restore/backup/backup-repo.md
Labels: documentation, size/M

#5508 chore: auto infer label from clusterdef
  cmd/manager/main.go
  config/rbac/role.yaml
  controllers/apps/backuppolicytemplate_controller.go
  controllers/apps/backuppolicytemplate_controller_test.go
  controllers/apps/suite_test.go
  deploy/helm/config/rbac/role.yaml
Labels: size/L

#5585 fix: kbcli command has redundant output information
  lorry/client/client.go
Labels: enhancement, size/XS

#5597 feat: add test for dataprotection
  controllers/dataprotection/backup_controller_test.go
  pkg/dataprotection/backup/deleter_test.go
  pkg/dataprotection/backup/request_test.go
  pkg/dataprotection/backup/scheduler_test.go
  pkg/dataprotection/backup/suite_test.go
Labels: test, feature, size/L

#5604 chore: adjust backup e2e test cases
  Makefile
  test/e2e/testdata/smoketest/mongodb/09_backup_snapshot.yaml
  test/e2e/testdata/smoketest/mongodb/09_backup_volume_snapshot.yaml
  test/e2e/testdata/smoketest/mongodb/10_backup_volume_snapshot_restore.yaml
  test/e2e/testdata/smoketest/mongodb/11_backup_datafile.yaml
  test/e2e/testdata/smoketest/mongodb/12_backup_datafile_restore.yaml
  test/e2e/testdata/smoketest/postgresql/00_postgresqlcluster.yaml
  test/e2e/testdata/smoketest/postgresql/11_backup_basebackup.yaml
  test/e2e/testdata/smoketest/postgresql/11_backup_snapshot.yaml
  test/e2e/testdata/smoketest/postgresql/12_backup_basebackup_restore.yaml
  test/e2e/testdata/smoketest/postgresql/12_backup_snapshot_restore.yaml
  test/e2e/testdata/smoketest/postgresql/13_backup_volume_snapshot.yaml
  test/e2e/testdata/smoketest/postgresql/14_backup_volume_snapshot_restore.yaml
  test/e2e/testdata/smoketest/redis/09_backup_snapshot.yaml
  test/e2e/testdata/smoketest/redis/09_backup_volume_snapshot.yaml
  test/e2e/testdata/smoketest/redis/10_backup_volume_snapshot_restore.yaml
  test/e2e/testdata/smoketest/redis/11_backup_datafile.yaml
  test/e2e/testdata/smoketest/redis/12_backup_datafile_restore.yaml
  test/e2e/testdata/smoketest/smoketestrun.go
  test/e2e/testdata/smoketest/wesql/11_backup_xtrabackup.yaml
  test/e2e/testdata/smoketest/wesql/12_backup_xtrabackup_restore.yaml
  test/e2e/testdata/smoketest/wesql/13_backup_volume_snapshot.yaml
  test/e2e/testdata/smoketest/wesql/14_backup_volume_snapshot_restore.yaml
Labels: test, size/L

#5607 fix: remove gosu for pg basebackup
  deploy/official-postgresql/scripts/libpostgresql.sh
Labels: bug, size/XS

#5611 chore: tidy up backup and restore
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  apis/dataprotection/v1alpha1/restore_types.go
  apis/dataprotection/v1alpha1/types.go
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  config/crd/bases/dataprotection.kubeblocks.io_restores.yaml
  controllers/apps/component_controller_test.go
  controllers/apps/opsrequest_controller_test.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/backupschedule_controller.go
  controllers/dataprotection/gc_controller_test.go
  controllers/dataprotection/restore_controller_test.go
  controllers/dataprotection/types.go
  controllers/dataprotection/volumepopulator_controller.go
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_restores.yaml
  pkg/cli/cluster/cluster.go
  pkg/cli/cluster/cluster_test.go
  pkg/cli/cmd/bench/pgbench.go
  pkg/cli/cmd/bench/sysbench.go
  pkg/cli/cmd/bench/tpcc.go
  pkg/cli/cmd/bench/tpch.go
  pkg/cli/cmd/bench/ycsb.go
  pkg/cli/cmd/cluster/create.go
  pkg/cli/cmd/cluster/dataprotection.go
  pkg/cli/cmd/dataprotection/restore.go
  pkg/cli/testing/fake.go
  pkg/constant/const.go
  pkg/controller/factory/builder.go
  pkg/controller/plan/restore.go
  pkg/dataprotection/action/action_create_vs.go
  pkg/dataprotection/backup/scheduler.go
  pkg/dataprotection/backup/utils.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/manager_test.go
  pkg/dataprotection/restore/utils.go
  pkg/dataprotection/types/constant.go
  pkg/dataprotection/utils/utils.go
  pkg/testutil/dataprotection/restore_factory.go
  test/e2e/testdata/smoketest/wesql/12_backup_xtrabackup_restore.yaml
Labels: approved, size/L

#5620 fix: create snapshot failed if storageClass's provisioner not equals to driver name
  controllers/apps/components/hscale_volume_populator.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/backupschedule_controller_test.go
  controllers/dataprotection/gc_controller_test.go
  controllers/dataprotection/restore_controller_test.go
  pkg/controllerutil/volumesnapshot.go
  pkg/dataprotection/action/action_create_vs.go
  pkg/dataprotection/backup/request_test.go
  pkg/dataprotection/restore/manager_test.go
  pkg/dataprotection/utils/utils.go
  pkg/testutil/apps/native_object_util.go
  pkg/testutil/apps/pv_factoy.go
  pkg/testutil/dataprotection/backup_utils.go
  pkg/testutil/type.go
Labels: enhancement, size/M

#5622 chore: add polardbx addon file
  deploy/helm/templates/addons/polardbx-addon.yaml
Labels: approved, size/S

#5606 feat: support handle breaking changes during upgrading kubeblocks
  apis/dataprotection/v1alpha1/backup_types.go
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  controllers/apps/component_controller_test.go
  controllers/apps/transformer_backup_policy_tpl.go
  controllers/dataprotection/backup_controller.go
  deploy/apecloud-mysql/templates/actionset.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  deploy/postgresql/dataprotection/pg-basebackup-restore.sh
  pkg/cli/cmd/kubeblocks/install.go
  pkg/cli/cmd/kubeblocks/upgrade.go
  pkg/cli/util/breakingchange/constant.go
  pkg/cli/util/breakingchange/upgradehandlerto0.7.go
  pkg/cli/util/breakingchange/upgrader.go
  pkg/cli/util/helm/helm.go
  pkg/dataprotection/backup/deleter.go
  pkg/dataprotection/restore/manager.go
Labels: feature, size/XL

#5623 fix: pulsar create failed in huawei cloud
  deploy/helm/templates/addons/pulsar-addon.yaml
  deploy/pulsar/templates/pulsar-config-configmap.yaml
  deploy/pulsar/values.yaml
Labels: enhancement, approved, size/S

#5596 chore: Separate the registry and repository of apecloud images in helm char
  deploy/bytebase/templates/auto-plugin.yaml
  deploy/bytebase/templates/statefulset.yaml
  deploy/bytebase/values.yaml
  deploy/cert-manager/templates/cert-manager.yaml
  deploy/cert-manager/values.yaml
  deploy/csi-s3/manifest.yaml
  deploy/csi-s3/templates/_helpers.tpl
  deploy/csi-s3/templates/attacher.yaml
  deploy/csi-s3/templates/csi-s3.yaml
  deploy/csi-s3/templates/provisioner.yaml
  deploy/csi-s3/values.yaml
  deploy/neon-cluster/templates/vm-compute-node-deploy.yaml
  deploy/neon-cluster/values.yaml
  deploy/pulsar/templates/_helpers.tpl
  deploy/pulsar/templates/clusterdefinition-zookeeper.yaml
  deploy/pulsar/templates/clusterdefinition.yaml
  deploy/pulsar/values.yaml
Labels: size/L

#5624 chore: adjust e2e test cases
  Makefile
  deploy/pulsar-cluster/templates/tests/benchmark.yaml
  test/e2e/testdata/smoketest/kafka/03_vscale.yaml
  test/e2e/testdata/smoketest/kafka/06_reconfig.yaml
  test/e2e/testdata/smoketest/pulsar/00_pulsarcluster.yaml
  test/e2e/testdata/smoketest/smoketestrun.go
  test/e2e/testdata/smoketest/wesql/00_wesqlcluster.yaml
Labels: test, size/L

#5629 fix: create volume snapshot failed
  pkg/dataprotection/action/action_create_vs.go
  pkg/dataprotection/action/action_create_vs_test.go
Labels: enhancement, size/M

#5627 fix: fix orioledb restart fail due to the invalid permissions
  deploy/orioledb/templates/scripts.yaml
Labels: enhancement, size/S

#5631 fix: enable ha for mysql replication
  lorry/dcs/k8s.go
Labels: enhancement, size/XS

#5584 fix: use a more precise way to determine grpc port
  pkg/controller/rsm/transformer_object_generation.go
  pkg/controller/rsm/transformer_objection_generation_test.go
Labels: enhancement, ci, size/L

#5633 fix: leave member
  lorry/dcs/k8s.go
  lorry/middleware/probe/checks_middleware.go
Labels: enhancement, size/XS

#5570 fix: incorrect state for reconfiguring operator
  apis/apps/v1alpha1/configuration_types.go
  apis/apps/v1alpha1/opsrequest_conditions.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/components/component_test.go
  controllers/apps/configuration/config_annotation.go
  controllers/apps/configuration/configuration_controller.go
  controllers/apps/configuration/configuration_test.go
  controllers/apps/configuration/reconcile_task.go
  controllers/apps/configuration/reconfigure_controller.go
  controllers/apps/configuration/revision.go
  controllers/apps/configuration/revision_test.go
  controllers/apps/operations/ops_util.go
  controllers/apps/operations/reconfigure.go
  controllers/apps/operations/reconfigure_pipeline.go
  controllers/apps/operations/reconfigure_pipeline_test.go
  controllers/apps/operations/reconfigure_test.go
  controllers/apps/operations/reconfigure_util.go
  controllers/apps/operations/reconfigure_util_test.go
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  pkg/controller/configuration/envfrom_utils.go
  pkg/controller/configuration/operator_test.go
  pkg/controller/configuration/patch_merger.go
  pkg/controller/configuration/pipeline.go
  pkg/controller/configuration/template_wrapper.go
  pkg/controllerutil/config_util.go
  pkg/controllerutil/resource_wrapper.go
  pkg/controllerutil/resource_wrapper_test.go
  pkg/controllerutil/util.go
  pkg/testutil/k8s/k8sclient_util.go
Labels: enhancement, approved, size/XXL

#5634 chore: fix license header checker
  hack/license/header-check.sh
  lorry/middleware/grpc/grpc_server_test.go
  test/e2e/testdata/smoketest/config.go
Labels: enhancement, size/M

#5641 chore: addon update RisingWave values.yaml
  deploy/risingwave-cluster/values.yaml
Labels: approved, size/S

#5642 chore: helm lint check
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/release-helm-chart.yml
  deploy/delphic/.helmignore
  deploy/delphic/Chart.yaml
  deploy/delphic/README.md
  deploy/delphic/templates/NOTES.txt
  deploy/delphic/templates/_helpers.tpl
  deploy/delphic/templates/deployment.yaml
  deploy/delphic/templates/ingress.yaml
  deploy/delphic/templates/job.yaml
  deploy/delphic/templates/secret.yaml
  deploy/delphic/templates/service.yaml
  deploy/delphic/templates/serviceaccount.yaml
  deploy/delphic/templates/tests/test-connection.yaml
  deploy/delphic/values.yaml
Labels: size/XL

#5637 fix: support using the password of the original cluster for recovery
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  config/crd/bases/dataprotection.kubeblocks.io_restores.yaml
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/backuppolicy_controller_test.go
  controllers/dataprotection/backuprepo_controller_test.go
  controllers/dataprotection/backupschedule_controller_test.go
  controllers/dataprotection/gc_controller_test.go
  controllers/dataprotection/restore_controller_test.go
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_restores.yaml
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/templates/rbac/cluster_pod_required_role.yaml
  deploy/helm/templates/secret.yaml
  deploy/helm/values.yaml
  pkg/cli/cmd/cluster/create.go
  pkg/cli/cmd/cluster/dataprotection_test.go
  pkg/constant/const.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
  pkg/controllerutil/encryption.go
  pkg/controllerutil/encryption_test.go
  pkg/dataprotection/restore/utils.go
  pkg/dataprotection/types/constant.go
  pkg/dataprotection/utils/utils.go
  pkg/testutil/apps/clusterdef_factory.go
  pkg/testutil/apps/constant.go
  pkg/testutil/dataprotection/backup_utils.go
Labels: feature, enhancement, size/L

#5639 chore: for unsupported restore scenarios, throw an error early
  controllers/dataprotection/backup_controller_test.go
  pkg/controller/plan/restore.go
  pkg/controller/plan/restore_test.go
  test/e2e/testdata/smoketest/mongodb/10_backup_volume_snapshot_restore.yaml
  test/e2e/testdata/smoketest/mongodb/12_backup_datafile_restore.yaml
  test/e2e/testdata/smoketest/postgresql/12_backup_basebackup_restore.yaml
  test/e2e/testdata/smoketest/postgresql/14_backup_volume_snapshot_restore.yaml
  test/e2e/testdata/smoketest/redis/10_backup_volume_snapshot_restore.yaml
  test/e2e/testdata/smoketest/redis/12_backup_datafile_restore.yaml
  test/e2e/testdata/smoketest/wesql/14_backup_volume_snapshot_restore.yaml
Labels: size/M

#5645 fix: upgrade to 0.7 failed if exists qdrant cluster
  deploy/pulsar/values.yaml
  pkg/cli/util/breakingchange/constant.go
  pkg/cli/util/breakingchange/upgradehandlerto0.7.go
Labels: enhancement, approved, size/M

#5387 feat: add mariadb
  deploy/helm/templates/addons/mariadb-addon.yaml
  deploy/mariadb-cluster/.helmignore
  deploy/mariadb-cluster/Chart.yaml
  deploy/mariadb-cluster/templates/NOTES.txt
  deploy/mariadb-cluster/templates/_helpers.tpl
  deploy/mariadb-cluster/templates/cluster.yaml
  deploy/mariadb-cluster/templates/rbac.yaml
  deploy/mariadb-cluster/templates/validate.yaml
  deploy/mariadb-cluster/values.schema.json
  deploy/mariadb-cluster/values.yaml
  deploy/mariadb/.helmignore
  deploy/mariadb/Chart.yaml
  deploy/mariadb/templates/NOTES.txt
  deploy/mariadb/templates/_helpers.tpl
  deploy/mariadb/templates/clusterdefinition.yaml
  deploy/mariadb/templates/clusterversion.yaml
  deploy/mariadb/values.yaml
Labels: area/user-interaction, feature, enhancement, size/L

#5643 chore: bump grpc vertion to 1.56.3 to resolve the security issue
  go.mod
  go.sum
  pkg/cli/create/template/backup_template.cue
Labels: dependencies, size/L

#5647 fix: mongodb restore failed for datafile backup
  deploy/mongodb/dataprotection/datafile-backup.sh
  deploy/mongodb/dataprotection/datafile-restore.sh
  deploy/qdrant/scripts/qdrant-restore.sh
  deploy/redis/dataprotection/backup.sh
Labels: enhancement, approved, size/XS

#5635 feat: support zookeeper
  deploy/helm/templates/addons/zookeeper-addon.yaml
  deploy/zookeeper-cluster/.helmignore
  deploy/zookeeper-cluster/Chart.yaml
  deploy/zookeeper-cluster/templates/cluster.yaml
  deploy/zookeeper-cluster/values.yaml
  deploy/zookeeper/.helmignore
  deploy/zookeeper/Chart.yaml
  deploy/zookeeper/config/config-effect-scope.yaml
  deploy/zookeeper/config/zookeeper-config-constraint.cue
  deploy/zookeeper/config/zookeeper-config.tpl
  deploy/zookeeper/templates/_helpers.tpl
  deploy/zookeeper/templates/clusterdefinition.yaml
  deploy/zookeeper/templates/clusterversion.yaml
  deploy/zookeeper/templates/config-tpl-configmap.yaml
  deploy/zookeeper/templates/configconstraint.yaml
  deploy/zookeeper/values.yaml
Labels: area/user-interaction, feature, approved, size/XL

#5651 fix: mysql replication problem
  lorry/component/mysql/manager.go
  lorry/dcs/dcs.go
Labels: enhancement, size/XS

#5653 chore: adjust backuprepo based on oss and e2e test cases
  Makefile
  deploy/clickhouse-cluster/templates/cluster.yaml
  deploy/elasticsearch-cluster/Chart.yaml
  test/e2e/testdata/config/backuprepo_oss.yaml
  test/e2e/testdata/smoketest/clickhouse/00_clickhousecluster.yaml
  test/e2e/testdata/smoketest/clickhouse/00_milvuscluster.yaml
  test/e2e/testdata/smoketest/clickhouse/01_vscale.yaml
  test/e2e/testdata/smoketest/clickhouse/02_hscale_out.yaml
  test/e2e/testdata/smoketest/clickhouse/03_hscale_in.yaml
  test/e2e/testdata/smoketest/clickhouse/04_stop.yaml
  test/e2e/testdata/smoketest/clickhouse/04_vexpand.yaml
  test/e2e/testdata/smoketest/clickhouse/05_start.yaml
  test/e2e/testdata/smoketest/clickhouse/05_stop.yaml
  test/e2e/testdata/smoketest/clickhouse/06_restart.yaml
  test/e2e/testdata/smoketest/clickhouse/06_start.yaml
  test/e2e/testdata/smoketest/clickhouse/07_restart.yaml
  test/e2e/testdata/smoketest/config.go
  test/e2e/testdata/smoketest/elasticsearch/00_elasticsearchcluster.yaml
  test/e2e/testdata/smoketest/elasticsearch/01_vscale.yaml
  test/e2e/testdata/smoketest/elasticsearch/04_vexpand.yaml
  test/e2e/testdata/smoketest/etcd/00_etcdcluster.yaml
  test/e2e/testdata/smoketest/etcd/03_vscale.yaml
  test/e2e/testdata/smoketest/wesql/00_wesqlcluster.yaml
Labels: test, size/L

#5659 fix: workload upgrading from 0.5&0.6 to 0.7
  cmd/manager/main.go
  pkg/cli/types/types.go
  pkg/cli/util/breakingchange/upgradehandlerto0.7.go
  pkg/controller/rsm/transformer_deletion.go
  pkg/controller/rsm/transformer_status.go
Labels: enhancement, size/L, area/upgrade

#5660 fix: pg/oracle-mysql cluster is always updating after configure
  controllers/apps/configuration/config_annotation.go
  controllers/apps/configuration/reconfigure_controller.go
  controllers/apps/operations/reconfigure.go
  pkg/configuration/config_manager/reconfiguring_wrapper.go
  pkg/configuration/config_manager/reload_util.go
Labels: enhancement, size/M

#5664 chore: split multiple groups of test types
  .github/workflows/release-publish.yml
Labels: test, size/XS

#5658 chore: support auto completion for backup command
  pkg/cli/cmd/cluster/dataprotection.go
  pkg/cli/cmd/cluster/dataprotection_test.go
  pkg/cli/cmd/dataprotection/backup.go
Labels: size/L

#5657 chore: add service port for oteld
  deploy/apecloud-mysql/templates/clusterdefinition.yaml
  deploy/kafka/templates/clusterdefinition.yaml
  deploy/qdrant/templates/clusterdefinition.yaml
Labels: size/S

#5670 chore: change mariadb cluster chart name
  deploy/mariadb-cluster/Chart.yaml
Labels: approved, size/XS

#5671 chore: kbcli e2e test zookeeper and mariadb
  .github/workflows/e2e-kbcli.yml
  .github/workflows/release-publish.yml
Labels: test, approved, size/XS

#5668 docs: adjust blankspace
  docs/user_docs/backup-and-restore/backup/backup-repo.md
Labels: documentation, approved, size/S
