Repository apecloud/kubeblocks, pull requests merged in 2023-07, with the labels that each got.

#4058 chore: fix lint
  controllers/apps/components/internal/component_base_stateful.go
  internal/cli/cmd/cluster/dataprotection.go
  internal/controller/model/transform_utils_test.go
Labels: enhancement, approved, size/M

#4062 chore: wait for wal-g process exit normally
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/backuppolicy_controller_test.go
  controllers/dataprotection/restorejob_controller_test.go
  deploy/mongodb/templates/backuptool_pitr.yaml
Labels: size/XS

#4079 fix: parallel_transformer concurrent map writes
  internal/controller/model/parallel_transformer.go
  internal/controller/model/parallel_transformer_test.go
Labels: enhancement, approved, size/S

#4059 chore: update CD.spec.componentDesf.name validatation to be exact match of Cluster.spec.componentSpecs.name as this name could be default name from it.
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/clusterversion_types.go
  apis/apps/v1alpha1/configconstraint_types.go
  apis/apps/v1alpha1/type.go
  apis/dataprotection/v1alpha1/backup_types.go
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  apis/extensions/v1alpha1/addon_types.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_clusterversions.yaml
  config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  config/crd/bases/dataprotection.kubeblocks.io_restorejobs.yaml
  config/crd/bases/extensions.kubeblocks.io_addons.yaml
  controllers/dataprotection/backuppolicy_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterversions.yaml
  deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_restorejobs.yaml
  deploy/helm/crds/extensions.kubeblocks.io_addons.yaml
  deploy/helm/values.yaml
  deploy/kafka-cluster/templates/cluster.yaml
  deploy/kafka/templates/clusterdefinition.yaml
  deploy/kafka/templates/clusterversion.yaml
  deploy/prometheus-cluster/templates/cluster.yaml
  deploy/prometheus/templates/backuppolicytemplate.yaml
  deploy/prometheus/templates/clusterdefinition.yaml
  deploy/prometheus/templates/clusterversion.yaml
  internal/testutil/apps/backuppolicy_factory.go
Labels: approved, size/L

#4081 chore: replace mongo to mongosh in backup tools
  deploy/mongodb/templates/backuptool.yaml
  deploy/mongodb/templates/backuptool_pitr.yaml
Labels: approved, size/XS

#4082 fix: probe mysql binding test fail
  cmd/probe/internal/binding/mysql/mysql_test.go
Labels: test, enhancement, approved, size/XS

#4083 chore: update workloads' cue template, have podSpec.enableServiceLinks with default of false if not specified
  internal/controller/builder/cue/deployment_template.cue
  internal/controller/builder/cue/statefulset_template.cue
Labels: ci, size/XS

#4061 chore: add validation rule for immutable fields
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  apis/apps/v1alpha1/cluster_types.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  controllers/apps/cluster_status_conditions.go
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  internal/controller/builder/builder.go
Labels: size/S

#4007 fix: incompatible length if commands more than 1
  internal/controller/builder/builder_test.go
  internal/controller/builder/cue/restore_full_backup_job.cue
Labels: enhancement, size/XS

#4006 fix: start should not clone data
  controllers/apps/cluster_controller_test.go
  controllers/apps/components/internal/component_base_stateful.go
Labels: enhancement, approved, size/S

#3810 feat: support `kbcli kb compare`
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli_kubeblocks.md
  internal/cli/cmd/cluster/config_edit.go
  internal/cli/cmd/kubeblocks/compare.go
  internal/cli/cmd/kubeblocks/compare_test.go
  internal/cli/cmd/kubeblocks/install.go
  internal/cli/cmd/kubeblocks/kubeblocks.go
  internal/cli/cmd/kubeblocks/upgrade.go
  internal/cli/edit/custom_edit.go
  internal/cli/util/helm/diff.go
  internal/cli/util/helm/diff_test.go
  internal/cli/util/helm/helm.go
  internal/cli/util/util.go
Labels: feature, size/XL

#4066 fix: add kb-controller toleration as default for kubeblock installation
  Makefile
  internal/cli/cmd/kubeblocks/install.go
  internal/cli/cmd/kubeblocks/install_test.go
Labels: enhancement, size/M

#4088 feat: support redis datafile backup and restore
  deploy/postgresql/templates/scripts.yaml
  deploy/redis/scripts/redis-sentinel-setup.sh.tpl
  deploy/redis/scripts/redis-sentinel-start.sh.tpl
  deploy/redis/scripts/redis7-start.sh.tpl
  deploy/redis/templates/backuppolicytemplate.yaml
  deploy/redis/templates/backuptool.yaml
  deploy/redis/templates/clusterdefinition.yaml
  deploy/redis/templates/scripts.yaml
  test/testdata/resources/redis-scripts.yaml
Labels: area/user-interaction, feature, size/M

#4090 refactor: remove native volumesnapshot
  controllers/apps/cluster_controller_test.go
  controllers/apps/components/base_stateful_hscale.go
  controllers/apps/opsrequest_controller_test.go
  internal/controller/builder/builder.go
  internal/controller/builder/builder_test.go
  internal/controller/builder/cue/snapshot_template.cue
Labels: refactor, size/L

#4089 fix: keep compatible for backup policy pvc name
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
Labels: enhancement, size/XS

#4091 fix: "kbcli kb describe-config -A" displays the unencrypted ak/sk
  internal/cli/cmd/kubeblocks/config.go
  internal/cli/cmd/kubeblocks/config_test.go
Labels: enhancement, size/M

#4074 feat: add dataprotection isolation deployment
  cmd/manager/main.go
  controllers/apps/cluster_controller.go
  controllers/apps/cluster_controller_test.go
  controllers/apps/components/base_stateful_hscale.go
  controllers/apps/opsrequest_controller_test.go
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  internal/cli/cmd/cluster/dataprotection.go
  internal/cli/cmd/kubeblocks/compare_test.go
  internal/cli/cmd/kubeblocks/config.go
  internal/cli/util/version.go
  internal/controller/builder/builder.go
  internal/controller/builder/builder_test.go
  internal/controller/builder/cue/snapshot_template.cue
Labels: feature, approved, size/XL

#4075 feat: kbcli support show addon version and provider
  internal/cli/cmd/addon/addon.go
Labels: feature, size/XS

#4096 chore: using kblib for tdengine-cluster chart
  Makefile
  deploy/kblib/templates/_rbac.tpl
  deploy/tdengine-cluster/.helmignore
  deploy/tdengine-cluster/Chart.yaml
  deploy/tdengine-cluster/templates/_helpers.tpl
  deploy/tdengine-cluster/templates/cluster.yaml
  deploy/tdengine-cluster/templates/rbac.yaml
  deploy/tdengine-cluster/templates/role.yaml
  deploy/tdengine-cluster/templates/rolebinding.yaml
  deploy/tdengine-cluster/templates/serviceaccount.yaml
  deploy/tdengine-cluster/templates/validate.yaml
  deploy/tdengine-cluster/values.schema.json
  deploy/tdengine-cluster/values.yaml
Labels: size/L

#4094 feat: add pyroscope-server addon
  deploy/helm/templates/addons/pyroscope-addon.yaml
Labels: feature, size/M

#4103 fix: add tdengine-cluster to dep_repo helm chart in github workflow
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/release-helm-chart.yml
Labels: enhancement, size/XS

#4106 fix: remove unused keys
  controllers/apps/const.go
Labels: enhancement

#4105 fea: support startWindowMinutes for cron backup
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  controllers/apps/transformer_backup_policy_tpl.go
  controllers/dataprotection/backuppolicy_controller.go
  controllers/dataprotection/backuppolicy_controller_test.go
  deploy/apecloud-mysql/templates/backuppolicytemplate.yaml
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/mongodb/templates/backuppolicytemplate.yaml
  deploy/postgresql/templates/backuppolicytemplate.yaml
  deploy/redis/templates/backuppolicytemplate.yaml
  internal/testutil/apps/backuppolicy_factory.go
Labels: size/L

#4111 fix: update nebula-graphd for hscale
  deploy/nebula-cluster/templates/cluster.yaml
  deploy/nebula-cluster/values.yaml
  deploy/nebula/scripts/nebula-console-poststart.sh.tpl
  deploy/nebula/scripts/nebula-console-prestop.sh.tpl
  deploy/nebula/scripts/nebula-console-start.sh.tpl
  deploy/nebula/scripts/nebula-graphd-start.sh.tpl
  deploy/nebula/scripts/nebula-metad-start.sh.tpl
  deploy/nebula/scripts/nebula-storaged-start.sh.tpl
  deploy/nebula/templates/clusterdefinition.yaml
  deploy/nebula/templates/clusterversion.yaml
  deploy/nebula/templates/scripts.yaml
Labels: enhancement, size/L

#4102 chore: add validate e2e test case yamls and save test report to s3
  Makefile
  deploy/apecloud-mysql-cluster/Chart.yaml
  deploy/apecloud-mysql/Chart.yaml
  deploy/chatgpt-retrieval-plugin/Chart.yaml
  deploy/clickhouse-cluster/Chart.yaml
  deploy/clickhouse/Chart.yaml
  deploy/helm/Chart.yaml
  deploy/kafka-cluster/Chart.yaml
  deploy/kafka/Chart.yaml
  deploy/milvus-cluster/Chart.yaml
  deploy/milvus/Chart.yaml
  deploy/mongodb-cluster/Chart.yaml
  deploy/mongodb/Chart.yaml
  deploy/nyancat/Chart.yaml
  deploy/postgresql-cluster/Chart.yaml
  deploy/postgresql/Chart.yaml
  deploy/qdrant-cluster/Chart.yaml
  deploy/qdrant/Chart.yaml
  deploy/redis-cluster/Chart.yaml
  deploy/redis/Chart.yaml
  deploy/weaviate-cluster/Chart.yaml
  deploy/weaviate/Chart.yaml
  go.mod
  test/e2e/Makefile
  test/e2e/e2e_suite_test.go
  test/e2e/installation/installcheck.go
  test/e2e/testdata/smoketest/mongodb/00_mongodbcluster.yaml
  test/e2e/testdata/smoketest/postgresql/00_postgresqlcluster.yaml
  test/e2e/testdata/smoketest/postgresql/11_backup_snapshot_restore.yaml
  test/e2e/testdata/smoketest/redis/00_rediscluster.yaml
  test/e2e/testdata/smoketest/report.go
  test/e2e/testdata/smoketest/wesql/00_wesqlcluster.yaml
  test/e2e/types.go
  test/e2e/util/s3_util.go
  test/e2e/util/validate.py
Labels: test, size/L

#4112 chore: update agamotto version to v0.1.1
  deploy/apecloud-mysql/values.yaml
  deploy/helm/templates/addons/agamotto-addon.yaml
  deploy/mongodb/values.yaml
  deploy/postgresql/values.yaml
Labels: size/S

#4108 feat: add kubebench addon
  deploy/helm/templates/addons/kubebench.yaml
Labels: feature, size/M

#4087 chore: add mysql scale configuration
  deploy/apecloud-mysql/config/mysql-scale-config.tpl
  deploy/apecloud-mysql/config/mysql-scale-vtconsensus-config-constraint.cue
  deploy/apecloud-mysql/config/mysql-scale-vtgate-config-constraint.cue
  deploy/apecloud-mysql/config/mysql-scale-vttablet-config-constraint.cue
  deploy/apecloud-mysql/templates/clusterdefinition.yaml
  deploy/apecloud-mysql/templates/configconstraint.yaml
  deploy/apecloud-mysql/templates/configmap.yaml
  deploy/apecloud-mysql/templates/scripts.yaml
Labels: size/XL

#3526 feat: qdrant enhancement
  deploy/helm/dashboards/qdrant-overview.json
  deploy/helm/dashboards/weaviate.json
  deploy/qdrant/scripts/qdrant-backup.sh
  deploy/qdrant/scripts/qdrant-pre-stop.sh
  deploy/qdrant/scripts/qdrant-restore.sh
  deploy/qdrant/scripts/qdrant-setup.sh
  deploy/qdrant/templates/backuppolicytemplate.yaml
  deploy/qdrant/templates/backuptool.yaml
  deploy/qdrant/templates/clusterdefinition.yaml
  deploy/qdrant/templates/clusterversion.yaml
  deploy/qdrant/templates/configmap.yaml
  deploy/qdrant/templates/scripts.yaml
  deploy/qdrant/values.yaml
  deploy/weaviate/values.yaml
  docs/design_docs/DesignDocTemplate.md
  docs/user_docs/kubeblocks-for-mysql/apecloud-mysql-intro/apecloud-mysql-intro.md
  docs/user_docs/quick-start/try-kubeblocks-on-cloud.md
  internal/preflight/collect.go
Labels: feature, enhancement, size/XXL

#4119 chore: using agamotto to substitute redis_exporter
  deploy/helm/dashboards/redis.json
  deploy/redis/templates/clusterdefinition.yaml
  deploy/redis/templates/metrics-configmap.yaml
  deploy/redis/values.yaml
Labels: size/L

#4130 chore: exclude `zz_generated.deepcopy.go` from test coverage
  .github/utils/utils.sh
  .github/workflows/cicd-pull-request.yml
  .gitignore
  Makefile
Labels: test, approved, size/S

#3898 fix: can not start the cluster which restored from a backup and source cluster is stopped
  internal/cli/cmd/cluster/dataprotection.go
  internal/cli/cmd/cluster/dataprotection_test.go
Labels: enhancement, approved, size/M

#4133 fix: automatically cleanup fails job if logfile backup is New
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/utils.go
Labels: enhancement, approved, size/L

#4114 chore: tidy up deploy/helm/chart.yaml and Makefile
  Makefile
  deploy/helm/Chart.yaml
Labels: size/M

#4137 feat: enhance the envs for restore job and unified restore interface
  controllers/apps/cluster_controller_test.go
  controllers/apps/components/base_stateful_hscale.go
  controllers/apps/opsrequest_controller_test.go
  internal/controller/builder/builder.go
  internal/controller/builder/builder_test.go
  internal/controller/builder/cue/restore_full_backup_job.cue
  internal/controller/plan/restore.go
  internal/controller/plan/restore_test.go
Labels: feature, size/L

#4138 chore: upload coverage fork pr
  .github/workflows/cicd-pull-request.yml
Labels: approved, size/L

#4139 chore: static check
  .github/workflows/cicd-pull-request.yml
  Makefile
Labels: approved, size/XS

#4124 chore: add switchoverSpec scriptSpecSelectors API and fix switchover volumeMount failed
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/opsrequest_webhook_test.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  controllers/apps/operations/switchover_test.go
  controllers/apps/operations/switchover_util.go
  controllers/apps/operations/switchover_util_test.go
  deploy/apecloud-mysql/templates/clusterdefinition.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/mongodb/templates/clusterdefinition.yaml
  deploy/postgresql/templates/clusterdefinition.yaml
  internal/cli/testing/fake.go
  internal/controller/component/component.go
Labels: enhancement, approved, size/XXL

#3423 feat: support componentRef api
  Makefile
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/clusterdefinition_webhook.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  controllers/apps/components/base_stateful.go
  controllers/apps/components/stateless.go
  controllers/apps/components/stateless_workload.go
  deploy/apecloud-mysql/config/mysql-scale-vtconsensus-config-constraint.cue
  deploy/apecloud-mysql/config/mysql-scale-vtgate-config-constraint.cue
  deploy/apecloud-mysql/config/mysql-scale-vttablet-config-constraint.cue
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/nebula-cluster/values.yaml
  deploy/nebula/scripts/nebula-console-poststart.sh.tpl
  deploy/nebula/scripts/nebula-console-prestop.sh.tpl
  deploy/nebula/scripts/nebula-graphd-start.sh.tpl
  deploy/nebula/scripts/nebula-metad-start.sh.tpl
  deploy/nebula/scripts/nebula-storaged-start.sh.tpl
  deploy/nebula/templates/clusterdefinition.yaml
  deploy/nebula/templates/scripts.yaml
  internal/controller/builder/builder.go
  internal/controller/builder/builder_test.go
  internal/controller/component/component.go
  internal/controller/component/component_fieldref_util.go
  internal/controller/component/component_fieldref_util_test.go
  internal/controller/component/type.go
  internal/controller/plan/prepare_test.go
  internal/sqlchannel/engine/engine.go
  internal/sqlchannel/engine/nebula.go
  internal/testutil/apps/clusterdef_factory.go
Labels: feature, approved, size/XXL

#3548 feat: support external-dns
  deploy/helm/templates/addons/external-dns-addon.yaml
  deploy/helm/templates/addons/external-dns-values.yaml
  deploy/helm/values.yaml
Labels: feature, size/L

#4156 chore: add libgpgme-dev
  .github/utils/utils.sh
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/release-publish.yml
Labels: approved, size/M

#4159 fix: fix goreleaser build
  .goreleaser.yaml
Labels: enhancement, release, size/XS

#4147 chore: update etcd/clickhouse cd apis for day one creation
  cmd/probe/internal/binding/etcd/etcd.go
  deploy/clickhouse/configs/00_default_overrides.xml.tpl
  deploy/clickhouse/configs/ch-keeper_00_default_overrides.xml.tpl
  deploy/clickhouse/templates/clusterdefinition.yaml
  deploy/etcd/templates/clusterdefinition.yaml
  deploy/etcd/templates/clusterversion.yaml
Labels: size/M

#4163 chore: fix retry-after too fast.
  cmd/manager/main.go
  controllers/apps/cluster_controller.go
  controllers/apps/clusterdefinition_controller.go
  controllers/apps/clusterversion_controller.go
  controllers/apps/utils.go
Labels: enhancement, approved, size/M

#4136 feat: extend playground destroy version limitation
  internal/cli/cmd/playground/base.go
  internal/cli/cmd/playground/destroy.go
  internal/cli/cmd/playground/init.go
  internal/cli/cmd/playground/util.go
  internal/cli/cmd/playground/util_test.go
Labels: feature, size/S

#4171 fix: mongodb cluster sometimes restore failed
  deploy/mongodb/scripts/replicaset-post-start.tpl
Labels: enhancement, size/XS

#3596 chore: optimize class reference and add storage constraint
  apis/apps/v1alpha1/componentclassdefinition_types.go
  apis/apps/v1alpha1/componentclassdefinition_types_test.go
  apis/apps/v1alpha1/componentresourceconstraint_types.go
  apis/apps/v1alpha1/componentresourceconstraint_types_test.go
  apis/apps/v1alpha1/opsrequest_types.go
  config/crd/bases/apps.kubeblocks.io_componentresourceconstraints.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/class_controller.go
  controllers/apps/class_controller_test.go
  controllers/apps/cluster_controller.go
  controllers/apps/operations/vertical_scaling.go
  controllers/apps/operations/vertical_scaling_test.go
  controllers/apps/opsrequest_controller_test.go
  controllers/apps/transformer_fill_class.go
  deploy/helm/crds/apps.kubeblocks.io_componentresourceconstraints.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/templates/class/componentclassconstraint.yaml
  internal/class/class_utils.go
  internal/class/class_utils_test.go
  internal/class/types.go
  internal/class/types_test.go
  internal/cli/cmd/class/create.go
  internal/cli/cmd/class/create_test.go
  internal/cli/cmd/class/list.go
  internal/cli/cmd/cluster/cluster_test.go
  internal/cli/cmd/cluster/create.go
  internal/cli/cmd/cluster/create_test.go
  internal/cli/cmd/cluster/describe_ops.go
  internal/cli/cmd/cluster/operations.go
  internal/cli/cmd/cluster/operations_test.go
  internal/cli/create/template/cluster_operations_template.cue
  internal/cli/testing/fake.go
  internal/constant/const.go
  internal/controller/component/class_utils.go
  internal/controller/component/component.go
  internal/testutil/apps/componentclassdefinition_factory.go
  internal/testutil/apps/componentresourceconstraint_factory.go
Labels: approved, size/XXL

#4168 chore: update agamotto version with arm architecture
  deploy/apecloud-mysql/values.yaml
  deploy/helm/templates/addons/agamotto-addon.yaml
  deploy/mongodb/values.yaml
  deploy/postgresql/values.yaml
  deploy/redis/values.yaml
Labels: size/S

#4167 feat: kbcli dashboard subcommand support pyroscope server
  internal/cli/cmd/dashboard/dashboard.go
Labels: feature, size/XS

#4173 fix: snapshot failed
  controllers/dataprotection/utils.go
  internal/controller/plan/restore.go
Labels: enhancement, size/XS

#4177 chore: update all helm chart dep
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/release-helm-chart.yml
Labels: approved, size/S

#4175 feat: kbcli support kafka
  Makefile
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  deploy/apecloud-mysql-cluster/templates/cluster.yaml
  deploy/kafka-cluster/Chart.yaml
  deploy/kafka-cluster/templates/cluster.yaml
  deploy/kafka-cluster/templates/rbac.yaml
  deploy/kafka-cluster/templates/role.yaml
  deploy/kafka-cluster/templates/rolebinding.yaml
  deploy/kafka-cluster/templates/serviceaccount.yaml
  deploy/kafka-cluster/templates/tests/test-connection.yaml
  deploy/kafka-cluster/templates/validate.yaml
  deploy/kafka-cluster/values.schema.json
  deploy/kafka-cluster/values.yaml
  deploy/kafka/Chart.yaml
  deploy/kafka/configs/kafka-server-constraint.cue
  deploy/kafka/configs/kafka-server.prop.tpl
  deploy/kafka/scripts/kafka-sasl-sample.prop.tpl
  deploy/kafka/scripts/kafka-server-setup.sh.tpl
  deploy/kafka/templates/NOTES.txt
  deploy/kafka/templates/clusterdefinition.yaml
  deploy/kafka/templates/clusterversion.yaml
  deploy/kafka/values.yaml
  deploy/kblib/templates/_resources.tpl
  deploy/kblib/templates/_storages.tpl
  deploy/tdengine-cluster/templates/cluster.yaml
  docs/user_docs/cli/kbcli_cluster_create.md
  internal/cli/cluster/kafka.go
  internal/cli/cmd/cluster/create_subcmds_test.go
Labels: feature, size/XL

#4186 chore: improve makefile to build kbcli embed chart by latest version
  Makefile
Labels: test, size/XS

#3756 feat: add apecloud mysql PITR function
  deploy/apecloud-mysql/templates/backuppolicytemplate.yaml
  deploy/apecloud-mysql/templates/backuptool-pitr.yaml
  deploy/apecloud-mysql/templates/backuptool.yaml
  deploy/apecloud-mysql/templates/scripts.yaml
Labels: area/user-interaction, feature, size/L

#4178 chore: optimize redis default grafana dashboard
  deploy/helm/dashboards/redis.json
Labels: size/XXL

#4192 fix: limit 1 replica at mysql point-in-time recovery
  internal/cli/cmd/cluster/create.go
  internal/cli/cmd/cluster/create_test.go
  internal/cli/cmd/cluster/dataprotection.go
Labels: enhancement, approved, size/M

#4193 fix: change `ApeCloud-MySQL` affinity template
  .github/workflows/cicd-pull-request.yml
  deploy/apecloud-mysql-cluster/values.yaml
  deploy/kblib/templates/_schedule.tpl
  deploy/kblib/values.schema.json
  deploy/kblib/values.yaml
Labels: enhancement, approved, size/S

#4181 chore: change loki chart location from github to apecloud
  deploy/helm/templates/addons/loki-addon.yaml
  deploy/tdengine-cluster/Chart.yaml
Labels: size/S

#4198 fix: cli created cluster without expected public service
  deploy/kblib/templates/_helper.tpl
  docs/DEVELOPING.md
  docs/user_docs/cli/kbcli_cluster_create_kafka.md
  docs/user_docs/cli/kbcli_cluster_create_mongodb.md
  docs/user_docs/cli/kbcli_cluster_create_mysql.md
  docs/user_docs/cli/kbcli_cluster_create_postgresql.md
  docs/user_docs/cli/kbcli_cluster_create_redis.md
  internal/cli/cluster/cluster_chart.go
  internal/cli/cluster/cluster_chart_test.go
  internal/cli/cmd/cluster/create_subcmds.go
  internal/cli/cmd/cluster/create_subcmds_test.go
Labels: enhancement, approved, size/M

#4184 chore: fix validation failed if cpu is missing
  apis/apps/v1alpha1/componentresourceconstraint_types.go
  apis/apps/v1alpha1/componentresourceconstraint_types_test.go
Labels: enhancement, approved, size/M

#4206 chore: improve cluster helm charts, add missing info
  deploy/apecloud-mysql-cluster/templates/_helpers.tpl
  deploy/apecloud-mysql-cluster/templates/cluster.yaml
  deploy/mongodb-cluster/templates/cluster.yaml
  deploy/postgresql-cluster/templates/cluster.yaml
  deploy/redis-cluster/templates/cluster.yaml
Labels: size/S

#4179 fix: don't restart pods when kubeblocks tools image is updated
  controllers/apps/cluster_controller_test.go
  controllers/apps/components/base_stateful.go
  controllers/apps/components/stateless.go
  controllers/apps/components/utils.go
  controllers/apps/components/utils_test.go
  internal/controller/builder/cue/config_manager_sidecar.cue
  internal/controller/component/component_test.go
  internal/controller/plan/prepare_test.go
  internal/testutil/apps/cluster_consensus_test_util.go
  internal/testutil/apps/common_util.go
  internal/testutil/apps/constant.go
Labels: enhancement, size/L

#4185 chore: merge etcd,vtconsensus and vtctld components of wesql-scale into one
  deploy/apecloud-mysql-cluster/templates/_helpers.tpl
  deploy/apecloud-mysql/config/mysql-scale-config.tpl
  deploy/apecloud-mysql/config/mysql-scale-vtconsensus-config-constraint.cue
  deploy/apecloud-mysql/config/mysql-scale-vtgate-config-constraint.cue
  deploy/apecloud-mysql/config/mysql-scale-vttablet-config-constraint.cue
  deploy/apecloud-mysql/templates/clusterdefinition.yaml
  deploy/apecloud-mysql/templates/clusterversion.yaml
  deploy/apecloud-mysql/templates/scripts.yaml
Labels: size/L

#4203 chore: kafka bugfix & support jvm setting
  deploy/helm/templates/addons/migration-addon.yaml
  deploy/kafka-cluster/templates/cluster.yaml
  deploy/kafka-cluster/values.schema.json
  deploy/kafka-cluster/values.yaml
  deploy/kafka/scripts/kafka-server-setup.sh.tpl
  deploy/kafka/templates/clusterdefinition.yaml
Labels: bug, enhancement, size/L

#4215 chore: modify redis alert rules
  deploy/prometheus/config/server/rulesFiles/redis_alert_rules.yml
Labels: size/XS

#4182 feat: support datascript ops
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  apis/apps/v1alpha1/opsrequest_conditions.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/opsrequest_webhook.go
  apis/apps/v1alpha1/opsrequest_webhook_test.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/datascript.go
  controllers/apps/operations/datascript_test.go
  controllers/apps/operations/ops_manager.go
  controllers/apps/operations/ops_util.go
  controllers/apps/operations/suite_test.go
  controllers/apps/opsrequest_controller.go
  controllers/apps/systemaccount_controller.go
  controllers/apps/systemaccount_controller_test.go
  controllers/apps/systemaccount_util.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docker/Dockerfile-tools
  docs/user_docs/api-reference/backup.md
  docs/user_docs/api-reference/cluster.md
  internal/cli/cmd/cluster/dataprotection.go
  internal/cli/create/template/cluster_operations_template.cue
  internal/constant/const.go
  internal/sqlchannel/util/types.go
Labels: area/user-interaction, feature, approved, size/XXL

#4222 fix: bench support database password be empty
  docs/user_docs/cli/kbcli_cluster_create_kafka.md
  internal/cli/cmd/bench/bench.go
Labels: enhancement, size/XS

#4218 chore: function name typo
  internal/configuration/config_manager/builder.go
  internal/configuration/config_manager/config_handler.go
Labels: size/XS

#4207 feat: config support inject into EnvFrom (#4201)
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusterversions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterversions.yaml
  internal/controller/plan/prepare.go
  internal/controller/plan/prepare_test.go
  internal/testutil/apps/clusterdef_factory.go
Labels: area/user-interaction, feature, approved, size/L

#4223 docs: update slack url
  README.md
Labels: documentation, size/XS

#4229 chore: fix send chart msg error
  .github/workflows/release-helm-chart.yml
Labels: enhancement, approved, size/XS

#4231 chore: remote unsupported character from API doc
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  docs/user_docs/api-reference/backup.md
  docs/user_docs/api-reference/cluster.md
Labels: documentation, approved, size/M

#4237 chore: add env kubeblocks charts images
  deploy/helm/templates/deployment.yaml
Labels: approved, size/XS

#4238 chore: format alignment
  deploy/helm/templates/deployment.yaml
Labels: approved, size/XS

#4205 chore: improve the prompt for edit-config (#4202)
  internal/cli/cmd/cluster/config_edit.go
  internal/configuration/reconfigure_util.go
  internal/configuration/reconfigure_util_test.go
Labels: approved, size/M

#4227 feat: add metrics dashboard for loki instance
  deploy/helm/dashboards/container-log.json
  deploy/helm/dashboards/loki.json
  deploy/helm/values.yaml
Labels: feature, size/XXL

#4247 feat: add grafana dashboards for multi-level database clusters overview
  deploy/helm/dashboards/kubeblocks-home.json
  deploy/helm/dashboards/kubeblocks-postgresql-detail.json
  deploy/helm/dashboards/kubeblocks-postgresql-overview.json
  deploy/helm/dashboards/kubeletstats.json
  deploy/prometheus/config/server/rulesFiles/kubelet_alert_rules.yml
  deploy/prometheus/config/server/serverFiles/prometheus.yml
Labels: feature, size/XXL

#4249 chore: generate envfrom object for kbcli builder tpl and adjust pulsar helm template
  deploy/pulsar/templates/clusterdefinition.yaml
  deploy/pulsar/templates/configconstraints.yaml
  internal/cli/cmd/builder/template/component_wrapper.go
  internal/controller/plan/prepare.go
  internal/controller/plan/prepare_test.go
Labels: size/L

#4230 feat: support to create default storage class and use it
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/cluster_types_test.go
  deploy/helm/templates/_helpers.tpl
  deploy/helm/templates/configmap.yaml
  deploy/helm/templates/storageclass.yaml
  deploy/helm/values.yaml
  internal/constant/const.go
Labels: feature, size/M

#4250 fix: inconsistent generated plural
  apis/dataprotection/v1alpha1/backuprepo_types.go
  config/crd/bases/dataprotection.kubeblocks.io_backuprepos.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_dataprotection_backuprepos.yaml
  config/crd/patches/webhook_in_dataprotection_backuprepos.yaml
  config/rbac/dataprotection_backuprepo_editor_role.yaml
  config/rbac/dataprotection_backuprepo_viewer_role.yaml
  config/rbac/role.yaml
  controllers/dataprotection/backuprepo_controller.go
  deploy/helm/config/rbac/role.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuprepos.yaml
  docs/user_docs/api-reference/backup.md
Labels: enhancement, approved, size/M

#4236 chore: bench support auto generate name
  docs/user_docs/cli/kbcli_bench_pgbench.md
  docs/user_docs/cli/kbcli_bench_sysbench.md
  internal/cli/cmd/bench/bench.go
  internal/cli/cmd/bench/bench_test.go
  internal/cli/cmd/bench/pgbench.go
  internal/cli/cmd/bench/sysbench.go
  internal/cli/util/util.go
Labels: size/M

#4258 feat: cluster wait for sub resources deleted
  controllers/apps/cluster_controller_test.go
  controllers/apps/opsrequest_controller_test.go
  controllers/apps/transformer_cluster_deletion.go
Labels: feature, approved, size/M

#4256 feat: kbcli backuprepo create
  controllers/dataprotection/backuprepo_controller.go
  deploy/csi-s3/Chart.yaml
  deploy/csi-s3/templates/driver.yaml
  deploy/csi-s3/values.yaml
  deploy/helm/templates/storageprovider/minio.yaml
  deploy/helm/templates/storageprovider/oss.yaml
  deploy/helm/templates/storageprovider/s3.yaml
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli.md
  go.mod
  internal/cli/cmd/backuprepo/backuprepo.go
  internal/cli/cmd/backuprepo/backuprepo_test.go
  internal/cli/cmd/backuprepo/create.go
  internal/cli/cmd/backuprepo/create_test.go
  internal/cli/cmd/backuprepo/suite_test.go
  internal/cli/cmd/cli.go
  internal/cli/testing/fake.go
  internal/cli/types/types.go
  internal/cli/util/flags/flags.go
Labels: feature, approved, size/XXL

#4261 fix: rbac_templdate use wrong namespace
  internal/controller/builder/cue/rbac_template.cue
Labels: enhancement, size/XS

#4097 fix: nil pointer dereference when configurationSchema has empty CUE field
  internal/cli/util/util.go
  internal/cli/util/util_test.go
Labels: enhancement, approved, size/S

#3850 feat: kbcli support connect wesql with vtgate
  deploy/apecloud-mysql/templates/clusterdefinition.yaml
  deploy/postgresql/templates/configconstraint-14.yaml
  internal/cli/cmd/cluster/connect.go
  internal/sqlchannel/engine/engine_test.go
  internal/sqlchannel/engine/mysql.go
Labels: feature, size/S

#4257 feat: cli and helm do not create rbac resources by default
  deploy/kblib/templates/_rbac.tpl
  deploy/kblib/values.schema.json
  deploy/kblib/values.yaml
  deploy/postgresql-cluster/templates/rbac.yaml
  docs/user_docs/cli/kbcli_cluster_create.md
  docs/user_docs/cli/kbcli_cluster_create_kafka.md
  docs/user_docs/cli/kbcli_cluster_create_mongodb.md
  docs/user_docs/cli/kbcli_cluster_create_mysql.md
  docs/user_docs/cli/kbcli_cluster_create_postgresql.md
  docs/user_docs/cli/kbcli_cluster_create_redis.md
  docs/user_docs/cli/kbcli_cluster_delete.md
  internal/cli/cluster/cluster_chart.go
  internal/cli/cmd/cluster/create.go
  internal/cli/cmd/cluster/create_util.go
  internal/cli/cmd/cluster/delete.go
Labels: feature, approved, size/M

#4233 chore: add wesql-scale monitor configuration
  deploy/apecloud-mysql/templates/_helpers.tpl
  deploy/apecloud-mysql/templates/agamotto-configmap.yaml
  deploy/apecloud-mysql/templates/clusterdefinition.yaml
  deploy/apecloud-mysql/templates/scripts.yaml
  deploy/helm/dashboards/mysql-proxy.json
Labels: size/XXL

#4268 fix: test-cluster already exist test
  controllers/apps/cluster_plan_builder_test.go
Labels: test, enhancement, size/S

#4266 fix: Keep env in order to avoid make sts restart
  internal/controller/builder/builder.go
Labels: enhancement, size/S

#4270 chore: cache docker gha
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/release-helm-chart.yml
  .github/workflows/release-image.yml
  docker/Dockerfile-tools
Labels: documentation

#4269 chore: change kubebench group
  internal/cli/cmd/bench/pgbench.go
  internal/cli/cmd/bench/sysbench.go
  internal/cli/types/types.go
Labels: size/XS

#4248 chore: docker build cache
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/release-helm-chart.yml
  .github/workflows/release-image.yml
  docker/Dockerfile
  docker/Dockerfile-tools
  docker/docker.mk
Labels: documentation, approved, size/M

#4273 chore: kubebench group change
  internal/cli/cmd/bench/pgbench.go
  internal/cli/cmd/bench/sysbench.go
  internal/cli/types/types.go
Labels: size/XS

#4265 chore: code tidy up, refactor duplicated codes
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/opsrequest_webhook.go
  controllers/apps/cluster_controller_test.go
  controllers/apps/components/stateful_set.go
  controllers/apps/components/utils.go
  controllers/apps/components/utils_test.go
  controllers/apps/components/workload_controller.go
  controllers/apps/operations/switchover.go
  controllers/apps/operations/switchover_util.go
Labels: refactor, approved, size/M

#4276 fix: kbcli set componentserviceaccontName
  controllers/apps/transformer_rbac.go
  internal/cli/cmd/cluster/create.go
Labels: enhancement, size/S

#4278 fix: set empty default storage class
  apis/apps/v1alpha1/cluster_types.go
Labels: enhancement, approved, size/XS

#4281 doc: fix the capitalization issue
  docs/user_docs/installation/install-kbcli.md
Labels: documentation, enhancement, size/XS

#4280 fix: create a default sa if probes is required and serviceaccountname not set
  controllers/apps/transformer_rbac.go
  controllers/apps/transformer_rbac_test.go
  internal/controller/component/component.go
Labels: enhancement, size/S

#4252 fix: use database client instead of sqlchannel
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/release-image.yml
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/datascript.go
  controllers/apps/operations/datascript_test.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  docker/Dockerfile-datascript
  docker/docker.mk
  docs/user_docs/api-reference/cluster.md
  internal/cli/cmd/cluster/connect.go
  internal/constant/const.go
  internal/controller/builder/cue/rbac_template.cue
  internal/sqlchannel/client.go
  internal/sqlchannel/engine/engine.go
  internal/sqlchannel/engine/engine_test.go
  internal/sqlchannel/engine/mongodb.go
  internal/sqlchannel/engine/mysql.go
  internal/sqlchannel/engine/nebula.go
  internal/sqlchannel/engine/postgresql.go
  internal/sqlchannel/engine/redis.go
Labels: enhancement, approved, size/XXL

#4294 chore: tidy up Pulsar chart, add debugEnabled value
  deploy/pulsar/templates/_helpers.tpl
  deploy/pulsar/templates/clusterdefinition.yaml
  deploy/pulsar/templates/clusterversion.yaml
  deploy/pulsar/values.yaml
Labels: bug, size/L

#4297 chore: add bookeeper dashboards and bugfix
  deploy/helm/dashboards/pulsar-bookkeeper.json
  deploy/pulsar-cluster/templates/cluster.yaml
  deploy/pulsar/templates/agamotto-configmap.yaml
  deploy/pulsar/templates/clusterdefinition.yaml
Labels: bug, enhancement, size/XXL

#4191 feat: sqlchannel support replication mysql ha
  cmd/probe/internal/binding/base.go
  cmd/probe/internal/binding/base_test.go
  cmd/probe/internal/binding/mongodb/mongodb.go
  cmd/probe/internal/binding/mongodb/mongodb_test.go
  cmd/probe/internal/binding/mysql/mysql.go
  cmd/probe/internal/binding/mysql/mysql_test.go
  cmd/probe/internal/binding/utils.go
  cmd/probe/internal/component/dbmanager.go
  cmd/probe/internal/component/kubernetes/client.go
  cmd/probe/internal/component/mongodb/config.go
  cmd/probe/internal/component/mongodb/config_test.go
  cmd/probe/internal/component/mongodb/manager.go
  cmd/probe/internal/component/mongodb/types.go
  cmd/probe/internal/component/mysql/config.go
  cmd/probe/internal/component/mysql/manager.go
  cmd/probe/internal/component/mysql/util.go
  cmd/probe/internal/dcs/dcs.go
  cmd/probe/internal/dcs/k8s.go
  cmd/probe/internal/dcs/types.go
  cmd/probe/internal/highavailability/ha.go
  cmd/probe/internal/middleware/http/probe/checks_middleware.go
  cmd/probe/main.go
  controllers/apps/components/replication_set_utils.go
  deploy/mysql-cluster/.helmignore
  deploy/mysql-cluster/Chart.yaml
  deploy/mysql-cluster/templates/NOTES.txt
  deploy/mysql-cluster/templates/_helpers.tpl
  deploy/mysql-cluster/templates/cluster.yaml
  deploy/mysql-cluster/templates/rbac.yaml
  deploy/mysql-cluster/templates/validate.yaml
  deploy/mysql-cluster/values.schema.json
  deploy/mysql-cluster/values.yaml
  deploy/mysql/.helmignore
  deploy/mysql/Chart.yaml
  deploy/mysql/config/mysql-config.tpl
  deploy/mysql/templates/NOTES.txt
  deploy/mysql/templates/_helpers.tpl
  deploy/mysql/templates/class.yaml
  deploy/mysql/templates/clusterdefinition.yaml
  deploy/mysql/templates/clusterversion.yaml
  deploy/mysql/templates/configconstraint.yaml
  deploy/mysql/templates/configmap.yaml
  deploy/mysql/templates/scripts.yaml
  deploy/mysql/values.yaml
  internal/cli/cmd/cluster/create.go
  internal/cli/create/create.go
  internal/constant/const.go
  internal/sqlchannel/util/types.go
Labels: feature, approved, size/XXL

#4299 fix: kafka add add-on yaml
  deploy/helm/templates/addons/kafka-addon.yaml
  deploy/kafka/Chart.yaml
Labels: enhancement, size/M

#4296 chore: set smaller cpu cores for apecloud-mysql proxy
  deploy/apecloud-mysql-cluster/templates/_helpers.tpl
Labels: size/S

#4295 fix: split the wesql-scale configuration to avoid confusion and add table_acl_config_mode config item
  deploy/apecloud-mysql-cluster/templates/_helpers.tpl
  deploy/apecloud-mysql/config/mysql-scale-vtconsensus-config.tpl
  deploy/apecloud-mysql/config/mysql-scale-vtgate-config.tpl
  deploy/apecloud-mysql/config/mysql-scale-vttablet-config-constraint.cue
  deploy/apecloud-mysql/config/mysql-scale-vttablet-config.tpl
  deploy/apecloud-mysql/templates/clusterdefinition.yaml
  deploy/apecloud-mysql/templates/configmap.yaml
  deploy/apecloud-mysql/templates/scripts.yaml
  deploy/apecloud-mysql/values.yaml
Labels: enhancement, size/M

#4307 chore: add version bump
  .github/workflows/release-helm-chart.yml
Labels: dependencies, approved, size/XS

#4308 chore: rm bump version prefix v
  .github/workflows/release-helm-chart.yml
Labels: enhancement, dependencies, approved, size/XS

#4306 chore: move dashboards to the corresponding cd helm charts
  deploy/apecloud-mysql/dashboards/mysql-proxy.json
  deploy/apecloud-mysql/dashboards/mysql.json
  deploy/apecloud-mysql/templates/grafana/configmap-dashboards.yaml
  deploy/kafka/dashboards/jmx.json
  deploy/kafka/dashboards/kafka.json
  deploy/kafka/templates/grafana/configmap-dashboards.yaml
  deploy/mongodb/dashboards/mongodb.json
  deploy/mongodb/templates/grafana/configmap-dashboards.yaml
  deploy/postgresql/dashboards/postgresql.json
  deploy/postgresql/templates/grafana/configmap-dashboards.yaml
  deploy/qdrant/dashboards/qdrant-overview.json
  deploy/qdrant/templates/grafana/configmap-dashboards.yaml
  deploy/redis/dashboards/redis.json
  deploy/redis/templates/grafana/configmap-dashboards.yaml
  deploy/tdengine/dashboards/tdengine.json
  deploy/tdengine/templates/grafana/configmap-dashboards.yaml
  deploy/weaviate/dashboards/weaviate.json
  deploy/weaviate/templates/grafana/configmap-dashboards.yaml
Labels: size/L

#4315 chore: rm default prefix aliyun registry
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/release-helm-chart.yml
Labels: enhancement, approved, size/S

#4317 chore: add pulsar charts build
  Makefile
  test/e2e/testdata/smoketest/mongodb/00_mongodbcluster.yaml
  test/e2e/testdata/smoketest/postgresql/00_postgresqlcluster.yaml
  test/e2e/testdata/smoketest/pulsar/00_pulsarcluster.yaml
  test/e2e/testdata/smoketest/redis/00_rediscluster.yaml
  test/e2e/testdata/smoketest/wesql/00_wesqlcluster.yaml
Labels: size/L

#4302 chore: cli create cluster with dry-run output all resources include rbac
  deploy/apecloud-mysql-cluster/templates/_helpers.tpl
  internal/cli/cmd/cluster/create_subcmds.go
Labels: approved, size/XS

#4292 fix: fix the mismatched clusterdefiniton with cv cause buildcomponent panic
  internal/controller/component/component.go
Labels: enhancement, size/XS

#4327 chore: pulsar set annotation to ignore resource constraint
  deploy/pulsar-cluster/templates/_tplvalues.tpl
  deploy/pulsar-cluster/templates/cluster.yaml
  deploy/pulsar-cluster/values.yaml
Labels: size/S

#4325 fix: update service object but not proto
  controllers/apps/components/base.go
Labels: enhancement, size/S

#4331 fix: pulsar bookkeeper dashboard load fail
  deploy/pulsar/dashboards/pulsar-bookkeeper.json
  deploy/pulsar/templates/grafana/configmap-dashboards.yaml
Labels: enhancement, size/L

#4322 chore: update pulsar broker default replicas to 3
  deploy/pulsar-cluster/templates/cluster.yaml
  deploy/pulsar-cluster/templates/validate.yaml
  deploy/pulsar-cluster/values.yaml
Labels: approved, size/S

#4343 fix start pulsar bug
  deploy/pulsar/templates/scripts.yaml
Labels: bug, enhancement, size/XS

#4336 chore: fixed configuration changes maybe not take effect, add ut for envfrom
  controllers/apps/operations/reconfigure.go
  controllers/apps/operations/reconfigure_util.go
  controllers/apps/operations/reconfigure_util_test.go
  internal/controller/plan/envfrom_utils.go
  internal/controller/plan/envfrom_utils_test.go
  internal/controller/plan/prepare.go
  internal/controller/plan/prepare_test.go
  internal/testutil/k8s/k8sclient_util.go
  test/testdata/config/envfrom-constraint.yaml
Labels: enhancement, approved, size/XL

#4333 chore: create default BackupRepo during installation
  deploy/csi-s3/values.yaml
  deploy/helm/templates/addons/csi-s3-addon.yaml
  deploy/helm/templates/backuprepo.yaml
  deploy/helm/templates/storageprovider/minio.yaml
  deploy/helm/templates/storageprovider/oss.yaml
  deploy/helm/templates/storageprovider/s3.yaml
  deploy/helm/values.yaml
Labels: area/user-interaction, approved, size/M

#4345 chore: improved reconfiguring status progress (#4344)
  deploy/pulsar/templates/configconstraints.yaml
  internal/configuration/config_manager/config_handler.go
  internal/configuration/config_manager/config_handler_test.go
Labels: approved, size/M

#4351 fix: rset updates the wrong pod when setting primary annotation
  controllers/apps/components/replication_set.go
  deploy/postgresql/templates/scripts.yaml
  deploy/redis/templates/scripts.yaml
Labels: enhancement, size/S

#4352 chore: improved reconfiguring status progress, fix reconfigure operation bug
  controllers/apps/operations/reconfigure.go
  controllers/apps/operations/reconfigure_util.go
  controllers/apps/operations/reconfigure_util_test.go
  deploy/pulsar/templates/configconstraints.yaml
  internal/configuration/config_manager/config_handler.go
  internal/configuration/config_manager/config_handler_test.go
  internal/controller/plan/envfrom_utils.go
  internal/controller/plan/envfrom_utils_test.go
  internal/controller/plan/prepare.go
  internal/controller/plan/prepare_test.go
  internal/testutil/k8s/k8sclient_util.go
  test/testdata/config/envfrom-constraint.yaml
Labels: bug, enhancement, size/XL

#4353 chore: add pulsar cluster helm tests
  apis/apps/v1alpha1/clusterdefinition_types.go
  deploy/pulsar-cluster/templates/_helpers.tpl
  deploy/pulsar-cluster/templates/tests/benchmark.yaml
  deploy/pulsar-cluster/values.yaml
  deploy/pulsar/config/broker-env.tpl
  deploy/pulsar/templates/clusterdefinition.yaml
Labels: test, size/L

#4355 add pulsar bookies auto recovery switch
  deploy/pulsar-cluster/templates/validate.yaml
  deploy/pulsar/config/bookies-config.tpl
  deploy/pulsar/templates/clusterdefinition.yaml
Labels: approved, size/S

#4347 fix: create cluster check KubeBlocks manager ConfigMap default storage class
  internal/cli/cluster/helper_test.go
  internal/cli/cmd/cluster/cluster_test.go
  internal/cli/cmd/cluster/create.go
  internal/cli/cmd/cluster/update_test.go
  internal/cli/cmd/kubeblocks/kubeblocks_objects_test.go
  internal/cli/testing/fake.go
  internal/cli/types/types.go
  internal/cli/util/util.go
  internal/cli/util/util_test.go
Labels: enhancement, size/L

#4357 fix: revert redis and postgresql start script retry times
  deploy/postgresql/templates/scripts.yaml
  deploy/redis/templates/scripts.yaml
Labels: enhancement, size/XS

#4356 chore: check nil err before checking IsNotFound
  controllers/apps/cluster_plan_builder.go
Labels: size/XS

#4350 fix: adjust the search order of backup PVCs
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/utils.go
Labels: enhancement, size/M

#4363 fix: preflight failed when metric unready
  internal/cli/cmd/kubeblocks/data/kubeblocks_base_preflight.yaml
  internal/cli/cmd/kubeblocks/preflight.go
  internal/cli/cmd/kubeblocks/preflight_test.go
  internal/preflight/analyzer/analyze_result.go
  internal/preflight/analyzer/analyze_result_test.go
  internal/preflight/analyzer/kb_storage_class.go
  internal/preflight/analyzer/kb_storage_class_test.go
  internal/preflight/analyzer/kb_taint.go
  internal/preflight/collect.go
Labels: enhancement, size/L

#4366 fix: remove field resourceConstraintRef
  deploy/apecloud-mysql/templates/class.yaml
  deploy/helm/templates/class/componentclassconstraint.yaml
  deploy/mysql/templates/class.yaml
  internal/cli/cmd/class/template.go
  internal/cli/testing/testdata/class.yaml
  internal/cli/testing/testdata/custom_class.yaml
  test/e2e/testdata/smoketest/wesql/02_custom_class.yaml
Labels: enhancement, approved, size/M

#4373 chore: add five pulsar dashboards
  deploy/pulsar/dashboards/pulsar-bookie.json
  deploy/pulsar/dashboards/pulsar-broker.json
  deploy/pulsar/dashboards/pulsar-proxy.json
  deploy/pulsar/dashboards/pulsar-recovery.json
  deploy/pulsar/dashboards/pulsar-zookeeper.json
Labels: size/XXL

#4369 fix: incorrect component images
  controllers/apps/operations/reconfigure_util.go
  internal/cli/cluster/cluster.go
  internal/cli/util/util.go
  internal/cli/util/util_test.go
Labels: enhancement, approved, size/S

#4382 fix: pulsar zookeeper dashboard metric name error
  deploy/pulsar/dashboards/pulsar-zookeeper.json
Labels: enhancement, size/S

#4380 chore: support kubernetes clusterDomain for template
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  apis/extensions/v1alpha1/zz_generated.deepcopy.go
  apis/storage/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  cmd/manager/main.go
  externalapis/preflight/v1beta2/zz_generated.deepcopy.go
  internal/cli/cmd/builder/template/template.go
  internal/constant/const.go
  internal/controller/plan/config_template.go
  internal/controller/plan/config_template_test.go
Labels: approved, size/M

#4381 feat: add vmagent addon
  deploy/helm/templates/addons/vmagent-addon.yaml
Labels: feature, size/M

#4285 feat: support LLM
  deploy/helm/templates/addons/llm-addon.yaml
  deploy/llm-cluster/.helmignore
  deploy/llm-cluster/Chart.yaml
  deploy/llm-cluster/templates/NOTES.txt
  deploy/llm-cluster/templates/_helpers.tpl
  deploy/llm-cluster/templates/cluster.yaml
  deploy/llm-cluster/values.yaml
  deploy/llm/.helmignore
  deploy/llm/Chart.yaml
  deploy/llm/templates/NOTES.txt
  deploy/llm/templates/_helpers.tpl
  deploy/llm/templates/clusterdefinition.yaml
  deploy/llm/templates/clusterversion-chatglm2-6b.yaml
  deploy/llm/templates/clusterversion-openchat.yaml
  deploy/llm/templates/clusterversion-vicuna-13b.yaml
  deploy/llm/templates/configmap.yaml
  deploy/llm/values.yaml
Labels: feature, approved, size/XL

#4387 fix: create cluster when DEFAULT_STORAGE_CLASS not exist
  internal/cli/cmd/cluster/cluster_test.go
  internal/cli/cmd/cluster/create.go
Labels: enhancement, size/S

#4390 fix: unexpected storage after describing ops
  internal/cli/cmd/cluster/describe_ops.go
Labels: enhancement, size/XS

#4362 chore: rename constraints to rules
  apis/apps/v1alpha1/componentresourceconstraint_types.go
  apis/apps/v1alpha1/componentresourceconstraint_types_test.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentresourceconstraints.yaml
  controllers/apps/class_controller.go
  controllers/apps/class_controller_test.go
  controllers/apps/opsrequest_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_componentresourceconstraints.yaml
  deploy/helm/templates/class/componentclassconstraint.yaml
  internal/class/class_utils.go
  internal/class/types.go
  internal/class/types_test.go
  internal/cli/cmd/class/create.go
  internal/cli/cmd/cluster/cluster_test.go
  internal/cli/cmd/cluster/operations_test.go
  internal/cli/testing/testdata/resource-constraint-general-without-selector.yaml
  internal/cli/testing/testdata/resource-constraint-general.yaml
  internal/cli/testing/testdata/resource-constraint-memory-optimized.yaml
  internal/testutil/apps/componentresourceconstraint_factory.go
  test/e2e/testdata/smoketest/wesql/01_componentresourceconstraint_custom.yaml
Labels: approved, size/L

#4341 feat: mongodb ha support
  cmd/probe/cli/options.go
  cmd/probe/cli/run.go
  cmd/probe/cli/util.go
  cmd/probe/internal/component/dbmanager.go
  cmd/probe/internal/component/mongodb/client.go
  cmd/probe/internal/component/mongodb/config.go
  cmd/probe/internal/component/mongodb/config_test.go
  cmd/probe/internal/component/mongodb/manager.go
  cmd/probe/internal/component/mongodb/replset.go
  cmd/probe/internal/component/mongodb/roles.go
  cmd/probe/internal/component/mongodb/types.go
  cmd/probe/internal/component/mongodb/users.go
  cmd/probe/internal/component/mysql/manager.go
  cmd/probe/internal/highavailability/ha.go
Labels: feature, approved, size/XL

#4393 chore: tidy up license header
  cmd/probe/internal/dcs/dcs.go
  cmd/probe/internal/dcs/k8s.go
  cmd/probe/internal/dcs/types.go
  cmd/probe/internal/highavailability/ha.go
  cmd/reloader/template/main.go
  cmd/reloader/template/safeclient.go
  controllers/apps/cluster_plan_builder_test.go
  controllers/apps/operations/datascript.go
  controllers/apps/operations/datascript_test.go
  controllers/apps/utils_test.go
  controllers/dataprotection/cue/manifests_updater.cue
  deploy/pulsar/config/broker-config-constraint.cue
  internal/configuration/config_manager/config_handler.go
  internal/configuration/config_manager/logger.go
  internal/configuration/config_manager/proc_util.go
  internal/configuration/config_manager/proc_util_test.go
  internal/configuration/config_manager/type.go
  internal/configuration/util/shell_util.go
  internal/configuration/util/shell_util_test.go
  internal/controller/plan/template_merger.go
  internal/controller/plan/template_merger_test.go
  internal/controller/plan/tool_image_builder.go
  test/e2e/testdata/smoketest/report.go
  test/e2e/util/s3_util.go
Labels: approved, size/L

#4389 chore: "kbcli cluster edit-backup-policy" supports updating backup repo
  docs/user_docs/cli/kbcli_cluster_edit-backup-policy.md
  internal/cli/cmd/cluster/dataprotection.go
  internal/cli/cmd/cluster/dataprotection_test.go
Labels: size/M

#4392 chore: tidy up configspec cluster.local
  deploy/clickhouse/configs/00_default_overrides.xml.tpl
  deploy/clickhouse/configs/ch-keeper_00_default_overrides.xml.tpl
  deploy/kafka/scripts/kafka-exporter-setup.sh.tpl
  deploy/kafka/scripts/kafka-server-setup.sh.tpl
  internal/cli/cmd/builder/template/template_test.go
Labels: size/S

#4388 chore: revert prometheus helm chart
  .gitignore
  deploy/helm/templates/addons/prometheus-addon.yaml
  deploy/helm/templates/grafana/configmaps-datasources.yaml
  deploy/helm/templates/prometheus/alertmanager.yaml
  deploy/helm/values.yaml
  deploy/prometheus-cluster/.helmignore
  deploy/prometheus-cluster/Chart.yaml
  deploy/prometheus-cluster/templates/_helpers.tpl
  deploy/prometheus-cluster/templates/cluster.yaml
  deploy/prometheus-cluster/templates/clusterrole.yaml
  deploy/prometheus-cluster/templates/clusterrolebinding.yaml
  deploy/prometheus-cluster/templates/serviceaccount.yaml
  deploy/prometheus-cluster/templates/validate.yaml
  deploy/prometheus-cluster/values.yaml
  deploy/prometheus/.helmignore
  deploy/prometheus/Chart.yaml
  deploy/prometheus/config/alertmanager/alertmanager.yml
  deploy/prometheus/config/server/rulesFiles/kafka_alert_rules.yml
  deploy/prometheus/config/server/rulesFiles/kubelet_alert_rules.yml
  deploy/prometheus/config/server/rulesFiles/mongodb_alert_rules.yml
  deploy/prometheus/config/server/rulesFiles/mysql_alert_rules.yml
  deploy/prometheus/config/server/rulesFiles/postgresql_alert_rules.yml
  deploy/prometheus/config/server/rulesFiles/redis_alert_rules.yml
  deploy/prometheus/config/server/serverFiles/prometheus.yml
  deploy/prometheus/templates/_helpers.tpl
  deploy/prometheus/templates/backuppolicytemplate.yaml
  deploy/prometheus/templates/clusterdefinition.yaml
  deploy/prometheus/templates/clusterversion.yaml
  deploy/prometheus/templates/configconstraint.yaml
  deploy/prometheus/templates/configmap.yaml
  deploy/prometheus/values.yaml
  internal/cli/cmd/dashboard/dashboard.go
Labels: size/XXL

#4394 chore: remove kbcli uninstall obj check
  internal/cli/cmd/kubeblocks/uninstall.go
Labels: size/S

#4319 Feature/sqlchannel add pg
  cmd/probe/internal/binding/postgres/postgres.go
  cmd/probe/internal/binding/postgres/postgres_test.go
  cmd/probe/internal/component/postgres/config.go
  cmd/probe/internal/component/postgres/config_test.go
  cmd/probe/internal/component/postgres/manager.go
  cmd/probe/internal/component/postgres/types.go
  cmd/probe/internal/component/postgres/types_test.go
  cmd/probe/internal/component/util.go
  cmd/probe/internal/dcs/types.go
  cmd/probe/internal/highavailability/ha.go
  go.mod
  go.sum
Labels: feature, approved, size/XXL

#4396 chore: rename agamotto addon
  deploy/helm/templates/addons/agamotto-addon.yaml
Labels: size/S

#4395 chore: merge multi envfrom-related configmaps into one configmap
  internal/controller/plan/envfrom_utils.go
  internal/controller/plan/envfrom_utils_test.go
  internal/controller/plan/prepare_test.go
Labels: size/L

#4400 chore: removed configconstraint dependence on configspec.name, using env TOOLS_SCRIPTS_PATH
  deploy/pulsar/templates/configconstraints.yaml
  internal/configuration/config_manager/builder.go
  internal/controller/builder/builder.go
  internal/controller/builder/builder_test.go
  internal/controller/plan/prepare.go
  internal/controller/plan/tool_image_builder.go
Labels: approved, size/M
