Repository apecloud/kubeblocks, pull requests merged in 2023-12, with the labels that each got.

#5967 fix: send event retry failed
  lorry/binding/base.go
  lorry/binding/utils.go
  lorry/dcs/dcs.go
  lorry/highavailability/ha.go
Labels: enhancement, size/S

#5968 chore: add oceanbase addon yaml
  deploy/helm/templates/addons/oceanbase-addon.yaml
Labels: size/M

#5966 chore: release charts image by manual
  .github/workflows/cicd-push.yml
  .github/workflows/release-image.yml
  .github/workflows/release-publish.yml
Labels: release, approved, size/S

#5973 fix: failed to transform cue to openapischema (#5969)
  deploy/apecloud-mysql/config/mysql8-config-constraint.cue
Labels: enhancement, size/XS

#5939 chore: fix dev container image
  .devcontainer/devcontainer.json
  docker/Dockerfile-dev
  docker/library-scripts/kubectl-helm-debian.sh
  go.mod
  go.sum
Labels: enhancement, size/L

#5977 chore: set resource for kb init container and addon job
  controllers/extensions/addon_controller_stages.go
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
Labels: size/M

#5978 fix: stop and stop pulsar failed which creating by kbcli
  pkg/cli/cluster/charts/apecloud-mysql-cluster.tgz
  pkg/cli/cluster/charts/kafka-cluster.tgz
  pkg/cli/cluster/charts/llm-cluster.tgz
  pkg/cli/cluster/charts/mongodb-cluster.tgz
  pkg/cli/cluster/charts/postgresql-cluster.tgz
  pkg/cli/cluster/charts/redis-cluster.tgz
  pkg/cli/cluster/charts/xinference-cluster.tgz
  pkg/cli/cmd/cluster/create.go
Labels: enhancement, size/M

#5981 docs: update slack link
  README.md
Labels: documentation, size/XS

#5979 chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`
  go.mod
  go.sum
  pkg/configuration/core/config_patch_test.go
  pkg/controller/component/component_class_types_test.go
  pkg/controller/component/component_class_utils.go
Labels: size/S

#5993 chore: cleanup restore resources failed after restoring a cluster successfully
  controllers/dataprotection/restore_controller.go
Labels: approved, size/XS

#5997 chore: add influxdb addon
  deploy/helm/templates/addons/influxdb-addon.yaml
Labels: approved, size/XS

#5919 feat: API to reference cluster resources in Env and templates
  apis/apps/v1alpha1/builtin_vars.go
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/component_controller.go
  controllers/apps/component_controller_test.go
  controllers/apps/component_utils.go
  controllers/apps/component_utils_test.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/componentdefinition_controller_test.go
  controllers/apps/operations/switchover_util.go
  controllers/apps/transformer_component_tls.go
  controllers/apps/transformer_component_vars.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  pkg/constant/const.go
  pkg/constant/env.go
  pkg/constant/pattern.go
  pkg/constant/tls.go
  pkg/controller/builder/builder_component_definition.go
  pkg/controller/component/component_definition_convertor.go
  pkg/controller/component/component_definition_convertor_test.go
  pkg/controller/component/component_fieldref_util.go
  pkg/controller/component/service_reference.go
  pkg/controller/component/service_reference_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
  pkg/controller/configuration/builtin_env_test.go
  pkg/controller/configuration/builtin_functions.go
  pkg/controller/configuration/config_template.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
  pkg/controller/plan/tls_utils.go
  pkg/controller/plan/tls_utils_test.go
  pkg/controller/rsm/transformer_object_generation.go
  pkg/controller/rsm/transformer_objection_generation_test.go
  pkg/generics/type.go
  pkg/gotemplate/tpl_engine.go
  pkg/lorry/client/suite_test.go
  pkg/lorry/dcs/k8s.go
  pkg/lorry/engines/base.go
  pkg/lorry/engines/custom/suite_test.go
  pkg/lorry/engines/etcd/suite_test.go
  pkg/lorry/engines/mysql/manager_test.go
  pkg/lorry/engines/mysql/suite_test.go
  pkg/lorry/engines/redis/suite_test.go
  pkg/lorry/grpcserver/suite_test.go
  pkg/lorry/operations/volume/suite_test.go
  pkg/testutil/apps/componentdefinition_factory.go
Labels: feature, size/XXL

#6002 fix: improve lorry performance
  lorry/binding/base.go
  lorry/dcs/k8s.go
  lorry/highavailability/ha.go
  lorry/util/util.go
Labels: enhancement, size/S

#5994 feat: support reconfigure operation for multi component (#5906)
  apis/apps/v1alpha1/opsrequest_conditions.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/opsrequest_webhook.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/ops_util.go
  controllers/apps/operations/reconfigure.go
  controllers/apps/operations/reconfigure_pipeline.go
  controllers/apps/operations/type.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  pkg/unstructured/xml_config.go
Labels: area/user-interaction, feature, size/XXL

#6000 chore: remove conn credential from comp definition
  apis/apps/v1alpha1/clusterdefinition_webhook_test.go
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/component_controller.go
  controllers/apps/component_controller_test.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/componentdefinition_controller_test.go
  controllers/apps/systemaccount_controller.go
  controllers/apps/systemaccount_util.go
  controllers/apps/systemaccount_util_test.go
  controllers/apps/transformer_component_credential.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  go.mod
  pkg/constant/const.go
  pkg/constant/pattern.go
  pkg/controller/builder/builder_component_definition.go
  pkg/controller/component/lorry_utils.go
  pkg/controller/component/rsm_convertor.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/configuration/builtin_env.go
  pkg/controller/configuration/builtin_env_test.go
  pkg/controller/factory/builder.go
  pkg/controllerutil/pod_utils_test.go
  pkg/testutil/apps/componentdefinition_factory.go
  pkg/testutil/apps/constant.go
Labels: size/XL

#5995 feat: kb-0.7 support reconfigure operation for multi component (#5906)
  apis/apps/v1alpha1/opsrequest_conditions.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/opsrequest_webhook.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/ops_util.go
  controllers/apps/operations/reconfigure.go
  controllers/apps/operations/reconfigure_pipeline.go
  controllers/apps/operations/type.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  pkg/cli/cmd/cluster/config_edit.go
  pkg/cli/cmd/cluster/config_ops.go
  pkg/cli/cmd/cluster/describe_ops.go
  pkg/cli/create/template/cluster_operations_template.cue
  pkg/unstructured/xml_config.go
Labels: feature, size/XXL

#6011 chore: install crds after deploy kubeblocks
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/release-helm-chart.yml
Labels: size/S

#6012 chore: trigger release cn kubeblocks io
  .github/utils/utils.sh
  .github/workflows/cicd-push.yml
Labels: release, approved, size/S

#6021 chore: refine lorry request
  cmd/lorry/main.go
  lorry/dcs/k8s.go
Labels: size/S

#6023 refactor: private function to public
  Makefile
  deploy/clickhouse-cluster/templates/cluster.yaml
  deploy/clickhouse-cluster/values.yaml
  deploy/kblib/templates/_metadata.tpl
  docs/user_docs/cli/kbcli_cluster_create_llm.md
  docs/user_docs/cli/kbcli_cluster_create_xinference.md
  docs/user_docs/cli/kbcli_clusterdefinition_list-service-reference.md
  pkg/cli/cluster/builtin_charts.go
  pkg/cli/cluster/charts/apecloud-mysql-cluster.tgz
  pkg/cli/cluster/charts/clickhouse-cluster.tgz
  pkg/cli/cluster/charts/kafka-cluster.tgz
  pkg/cli/cluster/charts/llm-cluster.tgz
  pkg/cli/cluster/charts/milvus-cluster.tgz
  pkg/cli/cluster/charts/mongodb-cluster.tgz
  pkg/cli/cluster/charts/neon-cluster.tgz
  pkg/cli/cluster/charts/postgresql-cluster.tgz
  pkg/cli/cluster/charts/qdrant-cluster.tgz
  pkg/cli/cluster/charts/redis-cluster.tgz
  pkg/cli/cluster/charts/weaviate-cluster.tgz
  pkg/cli/cluster/charts/xinference-cluster.tgz
  pkg/cli/cluster/cluster_chart.go
  pkg/cli/cmd/cluster/create_subcmds.go
  pkg/cli/cmd/cluster/create_subcmds_test.go
Labels: refactor, size/L

#6022 feat: set and limit the shm volume size as mem requirements
  pkg/controller/component/component.go
  pkg/controller/component/component_test.go
Labels: feature, size/L

#6027 chore: support nodeport service for redis sentinel
  deploy/redis-cluster/templates/sentinel-nodeport-service.yaml
  deploy/redis-cluster/values.yaml
Labels: size/M

#6019 chore: fix specify all resource image registry
  deploy/helm/templates/_addon.tpl
  deploy/helm/templates/_helpers.tpl
  deploy/helm/templates/applications/alertmanager-webhook-adaptor-values.yaml
  deploy/helm/templates/applications/apecloud-otel-collector-values.yaml
  deploy/helm/templates/applications/grafana-values.yaml
  deploy/helm/templates/applications/prometheus-values.yaml
  deploy/helm/templates/applications/snapshot-controller-values.yaml
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/values.yaml
Labels: enhancement, ci, size/L

#6029 chore: fix redis-cluster sentinel values schema json
  deploy/redis-cluster/values.schema.json
Labels: enhancement, size/M

#6030 fix: tls CA cert not working
  controllers/apps/components/component_workload_builder.go
  pkg/controller/plan/tls_utils.go
Labels: bug, enhancement, size/XS

#6024 feat: support setting the range of replicas for components
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/component_controller_test.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/transformer_component_validation.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  pkg/controller/builder/builder_component_definition.go
  pkg/controller/component/component_definition_convertor.go
  pkg/testutil/apps/componentdefinition_factory.go
Labels: feature, approved, size/L

#6017 chore: support vars reference and escaping
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: approved, size/L

#6033 fix: kb install panic when user have no permission
  docs/user_docs/cli/kbcli_cluster_create_redis.md
  pkg/cli/cluster/charts/apecloud-mysql-cluster.tgz
  pkg/cli/cluster/charts/clickhouse-cluster.tgz
  pkg/cli/cluster/charts/kafka-cluster.tgz
  pkg/cli/cluster/charts/llm-cluster.tgz
  pkg/cli/cluster/charts/milvus-cluster.tgz
  pkg/cli/cluster/charts/mongodb-cluster.tgz
  pkg/cli/cluster/charts/neon-cluster.tgz
  pkg/cli/cluster/charts/postgresql-cluster.tgz
  pkg/cli/cluster/charts/qdrant-cluster.tgz
  pkg/cli/cluster/charts/redis-cluster.tgz
  pkg/cli/cluster/charts/weaviate-cluster.tgz
  pkg/cli/cluster/charts/xinference-cluster.tgz
  pkg/cli/cmd/kubeblocks/kubeblocks_objects.go
  pkg/cli/cmd/kubeblocks/util.go
Labels: enhancement, size/M

#6028 chore: migrate dashboard to gemini and adjust dashboard job name
  deploy/helm/dashboards/kubeblocks-postgresql-detail.json
  deploy/helm/dashboards/kubeblocks-postgresql-overview.json
  deploy/helm/dashboards/kubeletstats.json
  deploy/helm/dashboards/node.json
Labels: size/XXL

#6039 feat: OceanBase supports Primary-Secondary Tenants
  deploy/oceanbase-cluster/Chart.yaml
  deploy/oceanbase-cluster/templates/_helpers.tpl
  deploy/oceanbase-cluster/templates/cluster.yaml
  deploy/oceanbase-cluster/templates/rbac.yaml
  deploy/oceanbase-cluster/templates/role.yaml
  deploy/oceanbase-cluster/templates/rolebinding.yaml
  deploy/oceanbase-cluster/templates/serviceaccount.yaml
  deploy/oceanbase-cluster/values.yaml
  deploy/oceanbase/Chart.yaml
  deploy/oceanbase/scripts/bootstrap.sh
  deploy/oceanbase/scripts/entrypoint.sh
  deploy/oceanbase/scripts/sql.sh
  deploy/oceanbase/templates/_helpers.tpl
  deploy/oceanbase/templates/clusterdefinition.yaml
  deploy/oceanbase/templates/scripts.yaml
  deploy/oceanbase/values.yaml
Labels: area/user-interaction, feature, enhancement, size/XL

#6058 docs: adjust format metadata
  i18n/zh-cn/user-docs/kubeblocks-for-mysql/proxy/_category_.yml
Labels: documentation, size/XS

#6064 chore: release addons charts after kubeblocks
  .github/workflows/release-helm-chart.yml
Labels: release, approved, size/XS

#6048 fix: force rsync status from configuration.status (#6045)
  controllers/apps/operations/reconfigure.go
Labels: enhancement, size/S

#6067 docs: adjust cn docs format
  i18n/zh-cn/img/create-and-connect-databases-overview.jpg
  i18n/zh-cn/user-docs/backup-and-restore/backup/backup-repo.md
  i18n/zh-cn/user-docs/backup-and-restore/backup/configure-backup-policy.md
  i18n/zh-cn/user-docs/backup-and-restore/overview.md
  i18n/zh-cn/user-docs/create-and-connect-databases/connect-to-database-in-production-environment.md
  i18n/zh-cn/user-docs/create-and-connect-databases/connect-to-database-in-testing-environment.md
  i18n/zh-cn/user-docs/create-and-connect-databases/create-database-cluster.md
  i18n/zh-cn/user-docs/create-and-connect-databases/overview-on-connect-databases.md
  i18n/zh-cn/user-docs/handle-an-exception/full-disk-lock.md
  i18n/zh-cn/user-docs/installation/install-with-helm/install-kubeblocks-with-helm.md
  i18n/zh-cn/user-docs/installation/install-with-kbcli/install-kbcli.md
  i18n/zh-cn/user-docs/installation/install-with-kbcli/install-kubeblocks-with-kbcli.md
  i18n/zh-cn/user-docs/installation/uninstall-kubeblocks-and-kbcli.md
  i18n/zh-cn/user-docs/kubeblocks-for-kafka/cluster-management/connect-to-a-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-kafka/cluster-management/create-a-kafka-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/cluster-management/switch-over-a-mongodb-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/migration/migration-by-kbcli.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql/cluster-management/create-and-connect-a-mysql-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql/migration/migration-aws-dms.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql/migration/migration-kbcli.md
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/cluster-management/create-and-connect-a-postgresql-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-redis/cluster-management/create-and-connect-to-a-redis-cluster.md
  i18n/zh-cn/user-docs/observability/access-log.md
  i18n/zh-cn/user-docs/observability/advanced-log.md
  i18n/zh-cn/user-docs/observability/configure-alert.md
  i18n/zh-cn/user-docs/observability/monitor-database.md
  i18n/zh-cn/user-docs/overview/database-engines-supported.md
  i18n/zh-cn/user-docs/overview/introduction.md
  i18n/zh-cn/user-docs/resource-scheduling/resource-scheduling.md
  i18n/zh-cn/user-docs/try-out-on-playground/try-kubeblocks-on-cloud.md
  i18n/zh-cn/user-docs/try-out-on-playground/try-kubeblocks-on-local-host.md
  i18n/zh-cn/user-docs/user-management/manage-user-accounts.md
Labels: documentation, size/XL

#6070 docs: adjust kafka docs format
  i18n/zh-cn/user-docs/kubeblocks-for-kafka/cluster-management/connect-to-a-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-kafka/cluster-management/create-a-kafka-cluster.md
Labels: documentation, size/XS

#6072 docs: adjust content
  docs/user_docs/kubeblocks-for-mysql/configuration/configuration.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql/proxy/_category_.yml
Labels: documentation, approved, size/XS

#6075 chore: render ob parameters from tpl
  deploy/oceanbase-cluster/values.yaml
  deploy/oceanbase/config/oceanbase-config.tpl
  deploy/oceanbase/scripts/bootstrap.sh
  deploy/oceanbase/templates/clusterdefinition.yaml
  deploy/oceanbase/templates/configmap.yaml
Labels: size/M

#6037 chore: support component lifecycle action postProvision
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/opsrequest_webhook_test.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/component_controller.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/operations/switchover.go
  controllers/apps/operations/switchover_test.go
  controllers/apps/operations/switchover_util.go
  controllers/apps/transformer_component_post_provision.go
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  pkg/controller/component/component_definition_convertor.go
  pkg/controller/component/component_definition_convertor_test.go
  pkg/controller/component/component_post_provision.go
  pkg/controller/component/component_post_provision_test.go
  pkg/controller/component/job_utils.go
  pkg/controller/component/job_utils_test.go
  pkg/controller/component/lorry_utils.go
  pkg/controller/component/lorry_utils_test.go
  pkg/testutil/apps/base_factory.go
  pkg/testutil/apps/constant.go
Labels: size/XXL

#6078 chore: move storage provider controller to the pod of DP
  cmd/dataprotection/main.go
  cmd/manager/main.go
  deploy/helm/templates/deployment.yaml
Labels: size/S

#6076 fix: mongodb config deepcopy
  pkg/lorry/engines/mongodb/client.go
  pkg/lorry/engines/mongodb/config.go
  pkg/lorry/engines/mongodb/config_test.go
  pkg/lorry/engines/mongodb/manager.go
Labels: enhancement, size/L

#6077 chore: fix component definition vars env render
  pkg/controller/component/vars.go
Labels: enhancement, size/XS

#6086 chore: revert redis
  deploy/redis-cluster/values.schema.json
Labels: size/S

#6087 chore: add values.schema.json for OB
  deploy/oceanbase-cluster/templates/_helpers.tpl
  deploy/oceanbase-cluster/templates/cluster.yaml
  deploy/oceanbase-cluster/values.schema.json
  deploy/oceanbase-cluster/values.yaml
Labels: size/L

#6085 chore: fixed the target pod for backup and restore
  apis/apps/v1alpha1/opsrequest_types.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/dataprotection/utils.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/utils/utils.go
  pkg/testutil/dataprotection/backup_utils.go
Labels: enhancement, size/M

#6089 chore: cherry-pick clickhouse addon to kb-release-0.7
  deploy/clickhouse/configs/00_default_overrides.xml.tpl
  deploy/clickhouse/configs/clickhouse-config-constraint.cue
  deploy/clickhouse/configs/user.xml.tpl
  deploy/clickhouse/templates/_helpers.tpl
  deploy/clickhouse/templates/clusterdefinition.yaml
  deploy/clickhouse/templates/configconstraints.yaml
  deploy/clickhouse/templates/configmap.yaml
Labels: release, size/XXL

#6034 chore: add comment for backup deletionPolicy
  apis/dataprotection/v1alpha1/actionset_types.go
  apis/dataprotection/v1alpha1/backup_types.go
Labels: size/XS

#6092 Support/update mysql templates
  deploy/mysql/config/mysql-config.tpl
  deploy/mysql/config/mysql-reload.tpl
  deploy/mysql/config/mysql5.7-config.tpl
  deploy/mysql/config/mysql8-config-constraint.cue
  deploy/mysql/config/mysql8-config-effect-scope.yaml
  deploy/mysql/config/mysql8.0-config.tpl
  deploy/mysql/templates/clusterdefinition.yaml
  deploy/mysql/templates/clusterversion.yaml
  deploy/mysql/templates/config-constraint.yaml
  deploy/mysql/templates/config-templates.yaml
  deploy/mysql/templates/configconstraint.yaml
  deploy/mysql/templates/configmap.yaml
  deploy/mysql/templates/scripts.yaml
  lorry/component/mysql/manager.go
Labels: size/XXL

#6091 fix: empty parameter update cause restart (#6090)
  pkg/configuration/core/reconfigure_util.go
  pkg/configuration/core/reconfigure_util_test.go
Labels: enhancement, size/S

#6101 fix: add the description of wal_level in the pg configconstrant file
  deploy/postgresql/config/pg12-config-constraint.cue
  deploy/postgresql/config/pg14-config-constraint.cue
Labels: enhancement, size/XS

#6104 feat: mysql semi sync
  deploy/mysql/config/mysql8.0-config.tpl
  deploy/mysql/templates/config-constraint.yaml
  deploy/mysql/templates/scripts.yaml
  lorry/component/mysql/manager.go
Labels: feature, size/M

#6096 fix: disable KB_COMP_REPLICAS envvar to prevent pods from being restarted at h-scale
  apis/apps/v1alpha1/type.go
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  controllers/apps/component_controller_test.go
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  pkg/controller/component/vars.go
Labels: bug, enhancement, size/M

#6107 chore: remove KubeBlocks type roleArbitrator and replace with Lorry
  apis/apps/v1alpha1/componentdefinition_types.go
  controllers/apps/transformer_component_status.go
  pkg/controller/component/component_definition_convertor.go
Labels: size/XS

#6108 fix: mysql follow
  lorry/component/mysql/manager.go
  lorry/highavailability/ha.go
Labels: enhancement, size/S

#6073 feat: Support for configuring addon registry
  deploy/apecloud-mysql/templates/_helpers.tpl
  deploy/apecloud-mysql/templates/clusterversion-auditlog.yaml
  deploy/apecloud-mysql/templates/clusterversion.yaml
  deploy/apecloud-mysql/values.yaml
  deploy/bytebase/templates/_helpers.tpl
  deploy/bytebase/templates/auto-plugin.yaml
  deploy/bytebase/templates/statefulset.yaml
  deploy/bytebase/values.yaml
  deploy/cert-manager/templates/cert-manager.yaml
  deploy/cert-manager/values.yaml
  deploy/clickhouse/values.yaml
  deploy/csi-s3/manifest.yaml
  deploy/csi-s3/templates/_helpers.tpl
  deploy/csi-s3/templates/attacher.yaml
  deploy/csi-s3/templates/csi-s3.yaml
  deploy/csi-s3/templates/provisioner.yaml
  deploy/csi-s3/values.yaml
  deploy/kafka/values.yaml
  deploy/llm/templates/clusterversion.yaml
  deploy/llm/values.yaml
  deploy/mongodb/templates/clusterdefinition.yaml
  deploy/mongodb/values.yaml
  deploy/orioledb/templates/clusterdefinition.yaml
  deploy/orioledb/templates/clusterversion.yaml
  deploy/orioledb/values.yaml
  deploy/postgresql/templates/clusterdefinition.yaml
  deploy/postgresql/templates/clusterversion.yaml
  deploy/postgresql/values.yaml
  deploy/pulsar/templates/_helpers.tpl
  deploy/pulsar/templates/clusterdefinition-zookeeper.yaml
  deploy/pulsar/templates/clusterdefinition.yaml
  deploy/pulsar/values.yaml
  deploy/qdrant/templates/actionset-datafile.yaml
  deploy/qdrant/templates/clusterdefinition.yaml
  deploy/qdrant/templates/clusterversion.yaml
  deploy/qdrant/values.yaml
  deploy/redis/templates/clusterdefinition.yaml
  deploy/redis/values.yaml
  docs/user_docs/cli/kbcli_cluster_create_redis.md
  pkg/cli/cluster/charts/apecloud-mysql-cluster.tgz
  pkg/cli/cluster/charts/clickhouse-cluster.tgz
  pkg/cli/cluster/charts/kafka-cluster.tgz
  pkg/cli/cluster/charts/llm-cluster.tgz
  pkg/cli/cluster/charts/milvus-cluster.tgz
  pkg/cli/cluster/charts/mongodb-cluster.tgz
  pkg/cli/cluster/charts/neon-cluster.tgz
  pkg/cli/cluster/charts/postgresql-cluster.tgz
  pkg/cli/cluster/charts/qdrant-cluster.tgz
  pkg/cli/cluster/charts/redis-cluster.tgz
  pkg/cli/cluster/charts/weaviate-cluster.tgz
  pkg/cli/cluster/charts/xinference-cluster.tgz
Labels: feature, size/L

#6113 fix: inject initContainers and containers zero resources if they are empty
  controllers/apps/operations/datascript.go
  controllers/apps/operations/switchover_util.go
  controllers/dataprotection/backuprepo_controller.go
  pkg/controller/component/component_post_provision.go
  pkg/dataprotection/action/action_exec.go
  pkg/dataprotection/utils/backuprepo.go
Labels: bug, enhancement, approved, size/M

#6114 fix: initContainers and containers zero resources if they are empty
  controllers/apps/operations/datascript.go
  controllers/apps/operations/switchover_util.go
  pkg/dataprotection/action/action_exec.go
  pkg/dataprotection/utils/backuprepo.go
Labels: enhancement

#6115 chore: decrease switchover time cost
  lorry/component/mysql/manager.go
  lorry/dcs/k8s.go
  lorry/highavailability/ha.go
Labels: size/M

#6118 chore: refind ob with hostnetwork and host path SC to restart in-place
  deploy/oceanbase-cluster/templates/_helpers.tpl
  deploy/oceanbase-cluster/templates/cluster.yaml
  deploy/oceanbase-cluster/values.schema.json
  deploy/oceanbase-cluster/values.yaml
  deploy/oceanbase/scripts/bootstrap.sh
  deploy/oceanbase/scripts/entrypoint.sh
  deploy/oceanbase/templates/clusterdefinition.yaml
  deploy/oceanbase/templates/clusterversion.yaml
Labels: size/L

#6121 fix: add selectorLabel for addon CR
  deploy/helm/templates/_addon.tpl
  deploy/helm/templates/addons/apecloud-mysql-addon.yaml
  deploy/helm/templates/addons/elasticsearch-addon.yaml
  deploy/helm/templates/addons/foxlake-addon.yaml
  deploy/helm/templates/addons/greptimedb-addon.yaml
  deploy/helm/templates/addons/influxdb-addon.yaml
  deploy/helm/templates/addons/kafka-addon.yaml
  deploy/helm/templates/addons/llm-addon.yaml
  deploy/helm/templates/addons/mariadb-addon.yaml
  deploy/helm/templates/addons/milvus-addon.yaml
  deploy/helm/templates/addons/mongodb-addon.yaml
  deploy/helm/templates/addons/mysql-addon.yaml
  deploy/helm/templates/addons/nebula-addon.yaml
  deploy/helm/templates/addons/neon-addon.yaml
  deploy/helm/templates/addons/oceanbase-addon.yaml
  deploy/helm/templates/addons/opensearch-addon.yaml
  deploy/helm/templates/addons/oracle-mysql-addon.yaml
  deploy/helm/templates/addons/orioledb-addon.yaml
  deploy/helm/templates/addons/polardbx-addon.yaml
  deploy/helm/templates/addons/postgresql-addon.yaml
  deploy/helm/templates/addons/pulsar-addon.yaml
  deploy/helm/templates/addons/qdrant-addon.yaml
  deploy/helm/templates/addons/redis-addon.yaml
  deploy/helm/templates/addons/risingwave-addon.yaml
  deploy/helm/templates/addons/starrocks-addon.yaml
  deploy/helm/templates/addons/tdengine-addon.yaml
  deploy/helm/templates/addons/tidb-addon.yaml
  deploy/helm/templates/addons/weaviate-addon.yaml
  deploy/helm/templates/addons/xinference-addon.yaml
  deploy/helm/templates/addons/zookeeper-addon.yaml
Labels: enhancement, size/M

#6125 chore: add ck addon
  deploy/helm/templates/addons/clickhouse-addon.yaml
Labels: size/M

#6122 chore: support backup target for backupMethod
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/utils.go
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  pkg/testutil/dataprotection/backup_utils.go
Labels: approved, size/XXL

#6128 chore: fix kafka and ck label
  deploy/clickhouse/templates/_helpers.tpl
  deploy/kafka/templates/_helpers.tpl
Labels: enhancement, size/S

#6080 fix: foxlake connect command
  pkg/lorry/engines/foxlake/commands.go
Labels: enhancement, size/XS

#6109 chore: improve Lorry performance
  cmd/lorry/main.go
  pkg/lorry/dcs/k8s.go
  pkg/lorry/dcs/types.go
  pkg/lorry/engines/mysql/manager.go
  pkg/lorry/engines/mysql/manager_test.go
  pkg/lorry/highavailability/ha.go
  pkg/lorry/operations/replica/checkrole.go
  pkg/lorry/util/event.go
Labels: approved, size/L

#6117 chore: update openapischema and add lables for kbcli report subcommand
  controllers/apps/configuration/config_util.go
  pkg/controller/configuration/pipeline.go
Labels: approved, size/XS

#6093 chore: fix cluster connect Database Env
  pkg/lorry/engines/opengauss/commands.go
Labels: enhancement, size/XS

#6135 support: kbcli config image registry
  pkg/cli/cmd/addon/addon.go
  pkg/cli/cmd/kubeblocks/install.go
  pkg/cli/types/config.go
  pkg/cli/types/types.go
Labels: size/M

#6133 fix: etcd connect error
  pkg/lorry/engines/register/managers.go
Labels: enhancement, approved, size/XS

#6138 chore: set timezone for backup schedule
  pkg/dataprotection/backup/scheduler.go
  pkg/dataprotection/utils/utils.go
  pkg/dataprotection/utils/utils_test.go
Labels: size/L

#6141 chore: do not use latest image tag
  deploy/apecloud-mysql/values.yaml
  deploy/apecloud-postgresql/templates/clusterdefinition.yaml
  deploy/elasticsearch/templates/clusterversion.yaml
  deploy/greptimedb/templates/clusterdefinition.yaml
  deploy/qdrant/values.yaml
  pkg/controller/rsm/types.go
Labels: test, size/S

#6139 feat: add switchover to lorry client
  pkg/lorry/client/client.go
  pkg/lorry/client/httpclient_test.go
  pkg/lorry/dcs/types.go
  pkg/lorry/operations/replica/switchover.go
Labels: feature, size/L

#6144 fix: orioledb etcd host error
  deploy/orioledb/config/etcd-serve-config.tpl
Labels: enhancement, size/XS

#6145 chore: upgrade lorry client switchover
  go.mod
  pkg/lorry/client/client_mock.go
  pkg/lorry/client/interface.go
  pkg/lorry/ctl/switchover.go
Labels: approved, size/M

#6143 chore: fix oceanbase image repo
  deploy/oceanbase/values.yaml
Labels: enhancement, size/XS

#6150 fix: remove config output to log
  pkg/cli/cmd/cli.go
Labels: enhancement, size/XS

#6152 chore: remove SA
  deploy/greptimedb/Chart.yaml
  deploy/greptimedb/templates/clusterdefinition.yaml
  deploy/greptimedb/templates/serviceaccount.yaml
Labels: size/S

#6148 fix: issues regarding the upgrade from 0.7 to 0.8
  controllers/apps/transformer_cluster_component_status.go
  controllers/apps/transformer_component_workload.go
Labels: enhancement, size/XS

#6149 fix: new different lorry client with different envs
  controllers/apps/transformer_component_account_provision.go
  pkg/lorry/client/client.go
Labels: enhancement, size/M

#6157 feat: add mysql errors and slow logs
  deploy/mysql/config/mysql-config.tpl
  deploy/mysql/config/mysql5.7-config.tpl
  deploy/mysql/dashboards/mysql.json
  deploy/mysql/templates/actionset-volumesnapshot.yaml
  deploy/mysql/templates/backuppolicytemplate.yaml
  deploy/mysql/templates/clusterdefinition.yaml
  deploy/mysql/templates/clusterversion.yaml
  deploy/mysql/templates/configconstraint.yaml
  deploy/mysql/templates/configmap.yaml
  deploy/mysql/values.yaml
Labels: feature, size/M

#6153 fix: switchover before member leaving
  controllers/apps/component_controller_test.go
  controllers/apps/transformer_component_workload.go
Labels: enhancement, size/M

#6155 chore: remove unused code of consensusSetStatus and replicationSetStatus
  controllers/apps/component_utils.go
  controllers/apps/component_utils_test.go
  test/integration/redis_hscale_test.go
Labels: size/L

#6158 chore: update lorry new client
  controllers/apps/systemaccount_controller.go
  controllers/apps/transformer_component_account_provision.go
  controllers/apps/transformer_component_workload.go
  pkg/lorry/client/client.go
Labels: size/XS

#6162 fix: invalid template in storageprovider/oss.yaml
  deploy/helm/templates/storageprovider/oss.yaml
Labels: enhancement, size/XS

#6166 chore: fix xtrabackup tag
  deploy/apecloud-mysql/values.yaml
Labels: enhancement, size/XS

#5815 feat: add apis for rsm managing pods
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/replicatedstatemachine_types.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  config/crd/bases/workloads.kubeblocks.io_replicatedstatemachines.yaml
  controllers/apps/component_utils.go
  controllers/apps/operations/horizontal_scaling.go
  controllers/apps/operations/ops_progress_util.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_component_workload.go
  controllers/apps/transformer_component_workload_test.go
  controllers/workloads/replicatedstatemachine_controller.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/workloads.kubeblocks.io_replicatedstatemachines.yaml
  deploy/helm/templates/rbac/cluster_pod_required_role.yaml
  go.mod
  go.sum
  pkg/controller/builder/builder_component.go
  pkg/controller/builder/builder_pod.go
  pkg/controller/builder/builder_replicated_state_machine.go
  pkg/controller/component/component.go
  pkg/controller/component/pod_utils.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/factory/builder.go
  pkg/controller/rsm/suite_test.go
  pkg/controller/rsm/transformer_deletion.go
  pkg/controller/rsm/transformer_deletion_test.go
  pkg/controller/rsm/transformer_object_generation.go
  pkg/controller/rsm/transformer_objection_generation_test.go
  pkg/controller/rsm/transformer_pod_generation.go
  pkg/controller/rsm/transformer_status.go
  pkg/controller/rsm/transformer_status_test.go
  pkg/controller/rsm/transformer_update_strategy.go
  pkg/controller/rsm/types.go
  pkg/controller/rsm/utils.go
  pkg/controllerutil/controller_common.go
Labels: area/user-interaction, feature, approved, size/XXL

#6174 fix: render pod template to pod when build pod
  controllers/apps/operations/ops_progress_util.go
  pkg/controller/builder/builder_pod.go
  pkg/controller/rsm/transformer_pod_generation.go
  pkg/controller/rsm/transformer_status.go
Labels: enhancement, size/S

#6182 chore: auto approve by workflow
  .github/workflows/auto-approve.yml
Labels: size/S

#6178 fix: cluster can't be deleted after KB upgraded from 0.6 to 0.7
  controllers/apps/transformer_cluster_deletion.go
Labels: size/XS

#6183 fix: use empty priorityClassName for csi-driver-nfs when in GKE
  deploy/helm/templates/applications/csi-driver-nfs-addon.yaml
Labels: size/XS

#6168 chore: avoid using the latest image tag
  pkg/controller/rsm/types.go
Labels: test, size/XS

#6185 chore: add flink e2e test
  .github/workflows/e2e-kbcli.yml
  .github/workflows/release-publish.yml
Labels: size/S

#6170 chore: expand built-in envs in postProvision action
  apis/apps/v1alpha1/componentdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  go.mod
  pkg/controller/component/component_post_provision.go
  pkg/controller/component/component_post_provision_test.go
Labels: size/L

#6116 feat: support pod-level service definition and variable reference
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/transformer_cluster_service.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  pkg/constant/const.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: area/user-interaction, feature, size/XL

#6171 fix: role check failed after upgrade from 0.7 to 0.8
  pkg/controller/rsm/transformer_object_generation.go
  pkg/controller/rsm/transformer_objection_generation_test.go
Labels: enhancement, size/M

#6190 fix: mongodb connect error
  pkg/lorry/engines/mongodb/commands.go
Labels: size/XS

#6191 chore: remove create role from mysql super user
  pkg/lorry/engines/mysql/user.go
Labels: size/XS

#6192 fix: watch the Configuration object in component controller
  controllers/apps/cluster_controller.go
  controllers/apps/component_controller.go
Labels: size/XS

#6194 fix: size computation for allocation may overflow
  controllers/apps/component_controller_test.go
  controllers/apps/configuration/policy_util.go
  controllers/apps/operations/switchover_util.go
  pkg/common/utils.go
  pkg/configuration/core/configtemplate_util.go
  pkg/controller/component/vars.go
  pkg/controllerutil/stateful_set_utils.go
  pkg/controllerutil/stateful_set_utils_test.go
  pkg/controllerutil/util.go
  test/integration/controller_suite_test.go
  test/integration/mysql_ha_test.go
  test/integration/mysql_reconfigure_test.go
  test/integration/redis_hscale_test.go
Labels: size/M

#6189 fix: re-render config after tls config changed
  controllers/apps/tls_utils_test.go
  controllers/apps/transformer_component_tls.go
  pkg/configuration/core/type.go
Labels: size/M

#6106 docs: helm-installation-docs
  docs/user_docs/installation/install-with-helm/install-kubeblocks-with-helm.md
  docs/user_docs/installation/uninstall-kbcli-and-kubeblocks.md
  docs/user_docs/kubeblocks-for-kafka/cluster-management/expand-volume.md
  docs/user_docs/kubeblocks-for-kafka/cluster-management/scale.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/expand-volume.md
  docs/user_docs/kubeblocks-for-mongodb/configuration/configuration.md
  docs/user_docs/kubeblocks-for-mysql/configuration/configuration.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/scale-for-a-postgresql-cluster.md
  docs/user_docs/kubeblocks-for-pulsar/cluster-management/expand-volume.md
  docs/user_docs/kubeblocks-for-vector-database/manage-vector-databases.md
Labels: documentation, approved, size/L

#6196 bugfix: exec k8s config as input
  pkg/lorry/client/client.go
  pkg/lorry/client/k8sexec_client.go
Labels: size/S

#6201 fix: backward compatible expose opsRequest with legacy services
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/operations/expose.go
  controllers/apps/transformer_cluster_service.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  pkg/controller/factory/builder.go
Labels: size/L

#6207 fix: exec client empty panic
  pkg/lorry/client/client.go
  pkg/lorry/client/k8sexec_client.go
Labels: size/S

#6209 fix: cronjob schedule is overrided
  pkg/dataprotection/backup/scheduler.go
Labels: size/XS

#6211 chore: fix failed test case
  controllers/dataprotection/backupschedule_controller_test.go
  pkg/dataprotection/backup/scheduler.go
  pkg/dataprotection/backup/utils.go
Labels: size/M

#6208 feat: support manage host ports if the pod is in the host network
  cmd/manager/main.go
  controllers/apps/component_controller.go
  controllers/apps/suite_test.go
  controllers/apps/transformer_cluster_deletion.go
  controllers/apps/transformer_component_host_port.go
  controllers/apps/transformer_component_load_resources.go
  pkg/constant/const.go
  pkg/controllerutil/controller_common.go
Labels: area/user-interaction, approved, size/L

#6212 chore: update redis version to 0.8.0
  deploy/helm/templates/addons/redis-addon.yaml
Labels: size/XS

#6215 fix: multiple static port conflict
  controllers/apps/transformer_component_host_port.go
  pkg/controllerutil/controller_common.go
Labels: enhancement, approved, size/S

#6213 chore: improve config template render for hostNetwork
  controllers/apps/configuration/configuration_controller.go
  controllers/apps/configuration/reconcile_task.go
  controllers/apps/transformer_component_configuration.go
  pkg/controller/component/component.go
  pkg/controller/configuration/builtin_env_test.go
  pkg/controller/configuration/config_template.go
  pkg/controller/configuration/config_template_test.go
  pkg/controller/configuration/pipeline.go
  pkg/controller/configuration/template_merger_test.go
  pkg/controller/configuration/template_wrapper_test.go
Labels: approved, size/L

#6202 fix: watch but not owned configuration object
  controllers/apps/component_controller.go
Labels: size/S

#6218 chore: handle update conflict
  controllers/apps/suite_test.go
  pkg/controllerutil/controller_common.go
Labels: approved, size/M

#6217 feat: support backup and restore for oceanbase
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/dataprotection/v1alpha1/backup_types.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  controllers/apps/cluster_controller.go
  controllers/apps/component_controller.go
  controllers/apps/operations/backup.go
  controllers/apps/operations/restore.go
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/apps/transformer_component_rbac.go
  controllers/apps/transformer_component_restore.go
  controllers/dataprotection/backup_controller.go
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  pkg/controller/plan/restore.go
  pkg/controller/plan/restore_test.go
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/restore/builder.go
  pkg/dataprotection/restore/types.go
  pkg/dataprotection/restore/utils.go
  pkg/dataprotection/utils/backup.go
  pkg/dataprotection/utils/envvar.go
Labels: feature, approved, size/L

#6220 fix: distinguish the componentdef on different addons (#6219)
  pkg/controller/component/synthesize_component.go
Labels: enhancement, size/XS

#6216 feat: lorry support ob
  config/lorry/components/binding_oceanbase.yaml
  pkg/lorry/dcs/k8s.go
  pkg/lorry/engines/mysql/config.go
  pkg/lorry/engines/oceanbase/config.go
  pkg/lorry/engines/oceanbase/config_test.go
  pkg/lorry/engines/oceanbase/conn.go
  pkg/lorry/engines/oceanbase/get_replica_role.go
  pkg/lorry/engines/oceanbase/get_replica_role_test.go
  pkg/lorry/engines/oceanbase/manager.go
  pkg/lorry/engines/oceanbase/switchover.go
  pkg/lorry/engines/register/managers.go
  pkg/lorry/operations/replica/switchover.go
Labels: feature, approved, size/XL

#6223 fix: replace scrapePort if pod is in host network
  controllers/apps/component_controller.go
  controllers/apps/transformer_component_host_port.go
  pkg/controllerutil/controller_common.go
Labels: enhancement, approved, size/L

#6221 fix: auto creating component obj when upgrade to KubeBlocks v0.8.0
  controllers/apps/transformer_cluster_component.go
Labels: enhancement, approved, size/S

#6222 fix: watch but not own existed workload objects
  controllers/apps/component_controller.go
  controllers/apps/transformer_component_status.go
Labels: enhancement, size/XS

#6231 fix: revert "distinguish the componentdef on different addons #6219"
  pkg/controller/component/synthesize_component.go
Labels: enhancement, size/XS

#6230 chore: fix backup failed for oceanbase
  controllers/apps/transformer_cluster_backup_policy.go
  pkg/controller/plan/restore.go
Labels: enhancement, approved, size/XS

#6237 feat: config-manager support host network (#6235)
  cmd/manager/main.go
  controllers/apps/configuration/policy_util.go
  pkg/configuration/config_manager/builder.go
  pkg/configuration/config_manager/handler_util.go
  pkg/constant/const.go
  pkg/controller/configuration/config_utils.go
Labels: area/user-interaction, feature, size/M

#6226 feat: lorry support host network
  apis/apps/v1alpha1/componentdefinition_types.go
  config/lorry/components/binding_oceanbase.yaml
  controllers/apps/componentdefinition_controller.go
  controllers/apps/transformer_component_host_port.go
  pkg/constant/const.go
  pkg/controller/component/lorry_utils.go
  pkg/controller/component/lorry_utils_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/rsm/transformer_object_generation.go
  pkg/lorry/engines/mysql/config.go
  pkg/lorry/engines/mysql/config_test.go
  pkg/lorry/engines/mysql/manager.go
  pkg/lorry/engines/oceanbase/config.go
  pkg/lorry/engines/oceanbase/get_replica_role.go
  pkg/lorry/engines/oceanbase/get_replica_role_test.go
  pkg/lorry/engines/oceanbase/manager.go
  pkg/lorry/engines/oceanbase/switchover.go
  pkg/lorry/operations/volume/protect.go
Labels: feature, approved, size/L

#6240 chore: incorrect conversion between integer types
  pkg/controller/configuration/config_template.go
Labels: enhancement, approved, size/XS

#6229 chore: split kubeblocks and kbcli release workflow
  .github/workflows/release-crds.yml
  .github/workflows/release-image.yml
  .github/workflows/release-publish.yml
Labels: release, size/L

#6242 chore: support restore backoffLimit
  apis/dataprotection/v1alpha1/restore_types.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/dataprotection.kubeblocks.io_restores.yaml
  controllers/apps/operations/custom.go
  deploy/helm/crds/dataprotection.kubeblocks.io_restores.yaml
  pkg/dataprotection/restore/builder.go
  pkg/dataprotection/restore/types.go
  pkg/dataprotection/types/types.go
Labels: approved, size/M

#6243 chore: backward compatible with AppNameLabelKey label in KubeBlocks v0.8.0
  pkg/controller/factory/builder.go
Labels: approved, size/XS

#6241 chore: change golang image to 1.21-alpine
  docker/Dockerfile
  docker/Dockerfile-dataprotection
  docker/Dockerfile-tools
Labels: size/XS

#6246 chore: fix oceanbase switchover
  pkg/lorry/dcs/k8s.go
  pkg/lorry/highavailability/ha.go
Labels: enhancement, size/XS

#6249 chore: adjust release crds
  .github/workflows/release-crds.yml
Labels: release, approved, size/M

#6248 chore: fix oceanbase lorry port adaptor
  cmd/lorry/main.go
  controllers/apps/transformer_component_host_port.go
  pkg/controller/component/port_utils.go
  pkg/controller/component/port_utils_test.go
  pkg/lorry/highavailability/ha.go
Labels: enhancement, approved, size/M

#6260 chore: update apecloud-mysql version
  deploy/helm/templates/addons/apecloud-mysql-addon.yaml
Labels: size/XS

#6268 chore: update OB addon version
  deploy/helm/templates/addons/oceanbase-addon.yaml
Labels: size/XS

#6262 chore: support ob dynamic port by ENV
  pkg/lorry/engines/oceanbase/commands.go
Labels: size/S

#6274 chore: restore ops failed for pitr
  controllers/apps/operations/restore.go
Labels: approved, size/XS

#6275 chore: support oceanbase running without primary
  apis/workloads/v1alpha1/replicatedstatemachine_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/workloads.kubeblocks.io_replicatedstatemachines.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/workloads.kubeblocks.io_replicatedstatemachines.yaml
  pkg/constant/const.go
  pkg/controller/rsm/utils.go
Labels: size/M

#6252 chore: add lorry http port env to container
  controllers/apps/transformer_component_host_port.go
  pkg/constant/env.go
  pkg/controller/component/lorry_utils.go
Labels: size/M

#6288 fix: pgsql creates backup failed when using componentDefinition
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  controllers/apps/transformer_cluster_backup_policy.go
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  pkg/testutil/apps/backuppolicytemplate_factory.go
Labels: enhancement, approved, size/L

#6291 chore: reduce the chance of test failures
  controllers/apps/component_controller_test.go
  controllers/apps/suite_test.go
Labels: test, size/S
