Repository apecloud/kubeblocks, pull requests merged in 2023-06, with the labels that each got.

#3597 docs: adjust docs 5.0
  docs/user_docs/README.md
  docs/user_docs/installation/enable-addons.md
  docs/user_docs/installation/install-kubeblocks.md
  docs/user_docs/kubeblocks-for-mongodb/_category_.yml
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
  docs/user_docs/kubeblocks-for-mysql/cluster-management/create-and-connect-a-mysql-cluster.md
  docs/user_docs/kubeblocks-for-mysql/configuration/configuration.md
  docs/user_docs/kubeblocks-for-mysql/high-availability/high-availability.md
  docs/user_docs/kubeblocks-for-mysql/migration/migration.md
  docs/user_docs/kubeblocks-for-postgresql/_category_.yml
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/create-and-connect-a-postgresql-cluster.md
  docs/user_docs/kubeblocks-for-postgresql/configuration/configuration.md
  docs/user_docs/kubeblocks-for-postgresql/high-availability/high-availability.md
  docs/user_docs/kubeblocks-for-postgresql/migration/migration_postgresql.md
  docs/user_docs/kubeblocks-for-redis/cluster-management/create-and-connect-a-redis-cluster.md
  docs/user_docs/kubeblocks-for-redis/configuration/configuration.md
  docs/user_docs/kubeblocks-for-redis/high-availability/high-availability.md
  docs/user_docs/kubeblocks-for-vector-database/_category_.yml
  docs/user_docs/kubeblocks-for-vector-database/chatgpt-retrieval-plugin-with-kubeblocks.md
  docs/user_docs/observability/access-logs.md
  docs/user_docs/observability/alert.md
  docs/user_docs/observability/monitor-database.md
  docs/user_docs/quick-start/try-kubeblocks-on-cloud.md
  docs/user_docs/quick-start/try-kubeblocks-on-your-laptop.md
Labels: documentation

#3600 docs: adjust docs 5.0 (#3597)
  docs/user_docs/README.md
  docs/user_docs/installation/enable-addons.md
  docs/user_docs/installation/install-kubeblocks.md
  docs/user_docs/kubeblocks-for-mongodb/_category_.yml
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
  docs/user_docs/kubeblocks-for-mysql/cluster-management/create-and-connect-a-mysql-cluster.md
  docs/user_docs/kubeblocks-for-mysql/configuration/configuration.md
  docs/user_docs/kubeblocks-for-mysql/high-availability/high-availability.md
  docs/user_docs/kubeblocks-for-mysql/migration/migration.md
  docs/user_docs/kubeblocks-for-postgresql/_category_.yml
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/create-and-connect-a-postgresql-cluster.md
  docs/user_docs/kubeblocks-for-postgresql/configuration/configuration.md
  docs/user_docs/kubeblocks-for-postgresql/high-availability/high-availability.md
  docs/user_docs/kubeblocks-for-postgresql/migration/migration_postgresql.md
  docs/user_docs/kubeblocks-for-redis/cluster-management/create-and-connect-a-redis-cluster.md
  docs/user_docs/kubeblocks-for-redis/configuration/configuration.md
  docs/user_docs/kubeblocks-for-redis/high-availability/high-availability.md
  docs/user_docs/kubeblocks-for-vector-database/_category_.yml
  docs/user_docs/kubeblocks-for-vector-database/chatgpt-retrieval-plugin-with-kubeblocks.md
  docs/user_docs/observability/access-logs.md
  docs/user_docs/observability/alert.md
  docs/user_docs/observability/monitor-database.md
  docs/user_docs/quick-start/try-kubeblocks-on-cloud.md
  docs/user_docs/quick-start/try-kubeblocks-on-your-laptop.md
Labels: documentation

#3603 chore: add cla.json
  .github/workflows/cla.yml
Labels: approved

#3585 chore: tidy up Docker makefile jobs
  CODEOWNERS
  MAINTAINERS.md
  Makefile
  docker/docker.mk
Labels: documentation, approved

#3606 chore: change readme badge
  README.md
Labels: documentation, approved

#3608 docs: docs 0.5 rel readme
  README.md
Labels: documentation

#3590 chore: fix check probe failed and remove invalid events of cluster
  controllers/apps/components/internal/component_base.go
  controllers/apps/components/internal/component_base_stateful.go
  internal/controller/lifecycle/cluster_status_conditions.go
  internal/controller/lifecycle/transform_utils.go
  internal/controllerutil/requeue_errors.go
Labels: enhancement

#3609 chore: add legal info into contributing doc
  docs/CONTRIBUTING.md
Labels: documentation

#3503 feat: cli plugin support auto completion like kubectl
  internal/cli/cmd/cli.go
Labels: feature

#3605 chore: fixed 'Incorrect conversion between integer types' code alert
  go.mod
  go.sum
  internal/cli/cmd/addon/addon.go
  internal/cli/cmd/cluster/create.go
Labels: enhancement, approved

#3611 chore: remove cla.yml
  .github/workflows/cla.yml
Labels: test, approved

#3613 chore: sync v0.5 release notes
  docs/release_notes/template.md
  docs/release_notes/v0.5.0.md
  docs/release_notes/v0.5.0/v0.5.0.md
Labels: release

#3560 fix: set component name to build connection credential
  controllers/apps/components/consensus/component_consensus_workload.go
  controllers/apps/components/internal/component_workload.go
  controllers/apps/components/replication/component_replication_workload.go
  controllers/apps/components/stateless/component_stateless_workload.go
  internal/cli/cmd/builder/template/workflow.go
  internal/controller/builder/builder.go
  internal/controller/builder/builder_test.go
  internal/controller/lifecycle/transformer_cluster_credential.go
  internal/controller/plan/prepare_test.go
  internal/controller/plan/template_wrapper.go
Labels: enhancement, approved

#3568 chore: fix typos
  config/samples/extensions_v1alpha1_addon.yaml
  controllers/apps/systemaccount_controller.go
  deploy/apecloud-mysql-cluster/values.yaml
  deploy/apecloud-mysql-scale-cluster/values.yaml
  deploy/apecloud-mysql/templates/scripts.yaml
  deploy/clickhouse-cluster/values.yaml
  deploy/etcd-cluster/values.yaml
  deploy/helm/dashboards/weaviate-overview.json
  deploy/kafka-cluster/values.yaml
  deploy/mongodb-cluster/values.yaml
  deploy/postgresql/config/pg12-config-constraint.cue
  deploy/postgresql/config/pg14-config-constraint.cue
  deploy/redis-cluster/values.yaml
  internal/cli/cmd/cluster/cluster_test.go
  internal/cli/cmd/cluster/create.go
  internal/cli/cmd/clusterdefinition/list_components.go
  internal/cli/cmd/clusterversion/clusterversion.go
  internal/cli/cmd/clusterversion/set_default_test.go
  internal/cli/cmd/kubeblocks/kubeblocks_objects_test.go
  internal/cli/cmd/kubeblocks/status.go
  internal/cli/cmd/plugin/plugin.go
  internal/cli/testing/fake.go
  internal/cli/testing/fake_test.go
  internal/cli/util/util.go
  internal/cli/util/version.go
  internal/constant/const.go
  internal/controller/lifecycle/cluster_plan_builder.go
  internal/controller/lifecycle/transform_utils.go
  internal/controller/lifecycle/transformer_halt_recovering.go
  internal/sqlchannel/client_test.go
  test/e2e/testdata/smoketest/playgroundtest.go
  test/testdata/cue_testdata/pg14.cue
  test/testdata/cue_testdata/pg14_openapi.json
Labels: enhancement

#3615 docs: fix bugs in category docs
  docs/CONTRIBUTING.md
  docs/user_docs/kubeblocks-for-mysql/cluster-management/create-and-connect-a-mysql-cluster.md
  docs/user_docs/kubeblocks-for-mysql/cluster-management/scale-for-apecloud-mysql.md
  docs/user_docs/kubeblocks-for-mysql/cluster-type/_category_.yml
  docs/user_docs/kubeblocks-for-mysql/cluster-type/cluster-types.md
  docs/user_docs/kubeblocks-for-mysql/cluster-type/customize-class-type.md
Labels: documentation, bug, enhancement

#3616 fix: enable consensus_set controller by feature gate
  cmd/manager/main.go
Labels: feature, enhancement, approved

#3583 feat: cli set plugin bin dir in code issue3582
  internal/cli/cmd/cli.go
  internal/cli/cmd/plugin/types.go
  internal/cli/util/util.go
  internal/controller/consensusset/transformer_deletion.go
  internal/controller/consensusset/transformer_update_strategy.go
Labels: feature

#3623 fix: change to correct schema to solve snapshot event loss problem
  controllers/dataprotection/backup_controller.go
Labels: enhancement

#3629 fix: job not found
  controllers/apps/systemaccount_controller_test.go
Labels: enhancement

#3641 chore: pull chaos mesh images from apecloud
  deploy/helm/templates/addons/chaos-mesh-addon.yaml
Labels: area/user-interaction, feature

#3574 chore: add probe timeout for mongodb
  cmd/probe/internal/binding/base.go
  cmd/probe/internal/binding/base_test.go
  cmd/probe/internal/binding/mysql/mysql.go
  cmd/probe/internal/binding/postgres/postgres.go
  cmd/probe/internal/binding/utils.go
  cmd/probe/internal/middleware/http/probe/checks_middleware.go
Labels: approved

#3619 chore: do not create fsnotify.Watcher when using sync mode (#3617)
  cmd/reloader/app/cmd.go
  internal/configuration/config_manager/volume_watcher.go
Labels: approved

#3647 chore: zip license and readme.md with kbcli for krew
  .github/workflows/release-publish.yml
Labels: documentation

#3633 chore: update controllers/extensions/addon_controller_test.go for more code coverage
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  Makefile
  controllers/extensions/addon_controller_stages.go
  controllers/extensions/addon_controller_test.go
  docker/Dockerfile
  docker/Dockerfile-cli
  go.mod
  go.sum
  test/testdata/addon/addon.yaml
Labels: test, approved

#3651 fix: cli playground error when repeatedly init
  internal/cli/cloudprovider/k3d.go
  internal/cli/cmd/kubeblocks/install.go
  internal/cli/cmd/playground/init.go
Labels: enhancement

#3656 chore: release failed test case
  internal/cli/cmd/kubeblocks/config_test.go
Labels: test, release

#3267 fix: failed to build image (#3266)
  docker/Dockerfile
  docker/Dockerfile-tools
Labels: enhancement

#3653 docs: adjust web links
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/CONTRIBUTING.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
  docs/user_docs/kubeblocks-for-mysql/cluster-management/create-and-connect-a-mysql-cluster.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/create-and-connect-a-postgresql-cluster.md
  docs/user_docs/kubeblocks-for-redis/cluster-management/create-and-connect-a-redis-cluster.md
  docs/user_docs/quick-start/try-kubeblocks-on-your-laptop.md
  install.sh
Labels: documentation

#3655 fix: cli playground error when repeatedly init
  internal/cli/cloudprovider/k3d.go
  internal/cli/cmd/kubeblocks/install.go
  internal/cli/cmd/playground/init.go
Labels: enhancement

#3640 chore: update kbcli doc
  docs/DEVELOPING.md
Labels: documentation

#3662 feat: support arm64 xtrabackup for apecloud mysql backup tool.
  deploy/apecloud-mysql-scale/templates/backuptool.yaml
  deploy/apecloud-mysql/templates/backuptool.yaml
Labels: feature

#3664 fix: licensing description
  cmd/probe/README.md
  cmd/reloader/README.md
Labels: enhancement

#3604 chore: fix incorrect conversion between integer types
  controllers/apps/configuration/reconfigure_policy.go
  internal/configuration/util/math.go
  internal/configuration/util/math_test.go
Labels: enhancement, approved

#3663 chore: remove internal doc link
  cmd/probe/README.md
  cmd/probe/internal/binding/etcd/etcd.go
  cmd/probe/internal/binding/kafka/kafka.go
  cmd/probe/internal/binding/mongodb/mongodb.go
  cmd/probe/internal/binding/mysql/mysql.go
  cmd/probe/internal/binding/postgres/postgres.go
  cmd/reloader/README.md
Labels: documentation

#3539 feat: add k8s info for `kbcli kb status`
  internal/cli/cmd/builder/template/template_test.go
  internal/cli/cmd/kubeblocks/status.go
  internal/cli/cmd/kubeblocks/status_test.go
Labels: feature, enhancement, approved

#3654 chore: refactor internal/controller/lifecycle/ pkg contents to controllers/apps/ for codecov
  controllers/apps/cluster_controller.go
  controllers/apps/cluster_controller_test.go
  controllers/apps/cluster_plan_builder.go
  controllers/apps/cluster_status_conditions.go
  controllers/apps/opsrequest_controller_test.go
  controllers/apps/suite_test.go
  controllers/apps/transform_restore.go
  controllers/apps/transform_types.go
  controllers/apps/transform_utils.go
  controllers/apps/transform_utils_test.go
  controllers/apps/transformer_assure_meta.go
  controllers/apps/transformer_backup_policy_tpl.go
  controllers/apps/transformer_cluster_credential.go
  controllers/apps/transformer_cluster_deletion.go
  controllers/apps/transformer_cluster_status.go
  controllers/apps/transformer_component.go
  controllers/apps/transformer_config.go
  controllers/apps/transformer_fill_class.go
  controllers/apps/transformer_halt_recovering.go
  controllers/apps/transformer_init.go
  controllers/apps/transformer_ownership.go
  controllers/apps/transformer_secret.go
  controllers/apps/transformer_validate_and_load_ref_resources.go
  controllers/apps/transformer_validate_enable_logs.go
  controllers/apps/transformers_parallel.go
  internal/controller/lifecycle/transform_utils_test.go
Labels: refactor, approved

#3650 feat: check chaos-mesh if enable before injecting faults
  internal/cli/cmd/fault/fault.go
  internal/cli/cmd/fault/fault_http_test.go
Labels: area/cli, feature

#3677 fix: only call leader when scale
  deploy/apecloud-mysql/templates/scripts.yaml
Labels: enhancement

#3556 feat: h-scale by backup tool
  apis/apps/v1alpha1/type.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  controllers/apps/cluster_controller_test.go
  controllers/apps/cluster_plan_builder.go
  controllers/apps/components/component_workload_controller_test.go
  controllers/apps/components/internal/component_base_stateful.go
  controllers/apps/components/internal/component_base_stateful_hscale.go
  controllers/apps/components/internal/component_base_stateful_hscale_backup.go
  controllers/apps/opsrequest_controller_test.go
  controllers/apps/suite_test.go
  controllers/apps/transformer_assure_meta.go
  deploy/apecloud-mysql/templates/backuppolicytemplateforhscale.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  go.mod
  internal/constant/const.go
  internal/controller/builder/builder.go
  internal/controller/builder/builder_test.go
  internal/controller/builder/cue/backup_job_template.cue
  internal/controller/builder/cue/pvc_template.cue
  internal/controller/builder/cue/restore_full_backup_job.cue
  internal/controller/component/type.go
  internal/controller/plan/restore.go
Labels: feature

#3679 test: add ut test case for dataprotection v1alpha1
  apis/dataprotection/v1alpha1/backup_types_test.go
  apis/dataprotection/v1alpha1/backuppolicy_types_test.go
Labels: test

#3701 docs: modify backup docs
  docs/user_docs/kubeblocks-for-mongodb/backup-and-restore/data-file-backup-and-restore.md
  docs/user_docs/kubeblocks-for-mysql/backup-and-restore/data-file-backup-and-restore.md
  docs/user_docs/kubeblocks-for-postgresql/backup-and-restore/data-file-backup-and-restore.md
  docs/user_docs/kubeblocks-for-postgresql/backup-and-restore/pitr-for-postgresql.md
Labels: documentation

#3704 fix: a typo in doc
  docs/user_docs/kubeblocks-for-redis/cluster-management/create-and-connect-a-redis-cluster.md
Labels: documentation, enhancement

#3698 chore：update kbcli version, add a highlight and fix the script error for https://kubeblocks.io/ doc
  docs/user_docs/installation/install-kbcli.md
Labels: documentation, enhancement

#3709 doc: add the powershell administrator hits
  docs/user_docs/installation/install-kbcli.md
  docs/user_docs/installation/uninstall-kbcli-and-kubeblocks.md
  docs/user_docs/kubeblocks-for-redis/cluster-management/create-and-connect-a-redis-cluster.md
  docs/user_docs/quick-start/try-kubeblocks-on-your-laptop.md
Labels: documentation

#3694 chore: set pr size label
  .github/utils/utils.sh
  .github/workflows/pull-request-label-size.yaml
Labels: size/M

#3712 fix: nakedret error
  cmd/probe/internal/binding/postgres/postgres.go
  controllers/apps/systemaccount_controller_test.go
Labels: enhancement

#3689 chore: update controllers/extensions/addon_controller_test.go
  apis/extensions/v1alpha1/addon_types.go
  apis/extensions/v1alpha1/addon_types_test.go
  controllers/extensions/addon_controller_test.go
  go.mod
Labels: test, approved

#3718 chore: fix fork branch workflow no secret
  .github/utils/utils.sh
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/pull-request-label-size.yaml
Labels: enhancement, approved, size/S

#3710 fix: make build & push dev-container
  .devcontainer/devcontainer.json
  docker/docker.mk
  internal/controller/builder/cue/backup_job_template.cue
  internal/controller/builder/cue/pvc_template.cue
  internal/controller/builder/cue/restore_full_backup_job.cue
Labels: enhancement, size/M

#3713 fix: fix the file name error in kubeblocks.io
  docs/user_docs/installation/uninstall-kbcli-and-kubeblocks.md
Labels: enhancement, size/XS

#3683 chore: upgrade agamotto image for mongodb
  deploy/helm/values.yaml
  deploy/mongodb/values.yaml
Labels: size/S

#3627 feat: kbcli dashboard support to open specified character type.
  deploy/helm/dashboards/cadvisor.json
  deploy/helm/dashboards/jmx.json
  deploy/helm/dashboards/kafka.json
  deploy/helm/dashboards/mongodb.json
  deploy/helm/dashboards/mysql.json
  deploy/helm/dashboards/node.json
  deploy/helm/dashboards/postgresql.json
  deploy/helm/dashboards/redis.json
  deploy/helm/dashboards/weaviate-overview.json
  docs/user_docs/cli/kbcli_dashboard_open.md
  internal/cli/cmd/dashboard/dashboard.go
  internal/cli/cmd/dashboard/dashboard_test.go
  internal/cli/cmd/dashboard/grafana_direct.go
  internal/cli/cmd/dashboard/grafana_direct_test.go
Labels: feature, ci, size/L

#3660 chore: add cluster.spec.componentSpecs validation rule for .candidateInstance
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/clusterdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
Labels: size/M

#3726 chore: redis prohibits passwordless access by default
  cmd/probe/internal/binding/redis/redis.go
  deploy/redis/config/redis7-config.tpl
  deploy/redis/scripts/redis-sentinel-setup.sh.tpl
  deploy/redis/scripts/redis-sentinel-start.sh.tpl
  deploy/redis/scripts/redis7-start.sh.tpl
  deploy/redis/templates/clusterdefinition.yaml
  deploy/redis/templates/scripts.yaml
Labels: approved, size/L

#3722 fix: change preflight checks rule for low spec machine in test case
  internal/cli/testing/testdata/hostpreflight.yaml
  internal/cli/testing/testdata/hostpreflight_nil.yaml
Labels: test, enhancement, approved, size/S

#3741 chore: tidy Makefile; remove fmt and vet jobs from tests related jobs dependencies
  Makefile
Labels: test, ci, approved, size/XS

#3745 chore: upgrade apecloud-cd action version
  .github/workflows/release-sync.yml
Labels: enhancement, size/S

#3734 chore: update unstable testcases and add events for failed jobs
  controllers/apps/systemaccount_controller.go
  controllers/apps/systemaccount_controller_test.go
  controllers/apps/systemaccount_util_test.go
Labels: test, approved, size/L

#3738 fix: cluster phase is incorrect when pod is not ready during component is Running/Failed/Abnormal
  controllers/apps/components/consensus/consensus.go
  controllers/apps/components/consensus/consensus_test.go
  controllers/apps/components/internal/component_base.go
  controllers/apps/components/replication/replication.go
  controllers/apps/components/replication/replication_test.go
  controllers/apps/components/stateful/stateful.go
  controllers/apps/components/stateful/stateful_test.go
  controllers/apps/components/stateless/stateless.go
  controllers/apps/components/stateless/stateless_test.go
  controllers/apps/components/types/component.go
Labels: enhancement, size/L

#3731 docs: add linux uninstallation
  docs/img/kubeblocks-architecture.png
  docs/img/kubeblocks-structure-new.jpg
  docs/user_docs/installation/install-kbcli.md
  docs/user_docs/installation/uninstall-kbcli-and-kubeblocks.md
  docs/user_docs/introduction/introduction.md
Labels: documentation, size/S

#3714 chore: pick connection-auth-error related fixes to release
  controllers/apps/systemaccount_controller.go
  controllers/apps/systemaccount_controller_test.go
  controllers/apps/systemaccount_util.go
  controllers/apps/systemaccount_util_test.go
Labels: enhancement, release, approved, size/XL

#3765 chore: make test parallel run on ubuntu-latest
  .github/utils/utils.sh
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/release-version.yml
Labels: test, approved, size/L

#3621 fix: remove remain secrets after uninstalling kubeblocks when addon CRD is uninstalled before kubeblocks
  internal/cli/cmd/kubeblocks/uninstall.go
  internal/cli/cmd/kubeblocks/uninstall_test.go
  internal/cli/util/helm/helm.go
Labels: bug, enhancement, size/M

#3761 feat: delete pvcs immediately after scale in
  controllers/apps/cluster_controller_test.go
  controllers/apps/cluster_status_event_handler.go
  controllers/apps/components/internal/component_base_stateful.go
  controllers/apps/components/internal/component_base_stateful_hscale.go
  internal/controller/builder/builder.go
  internal/controller/builder/builder_test.go
  internal/controller/builder/cue/delete_pvc_cron_job_template.cue
Labels: feature, size/XL

#3776 chore: update checkrole method from curl to httpget
  internal/controller/component/probe_utils.go
Labels: approved, size/S

#3780 fix: redis cluster stop succeed but start failed
  deploy/redis/scripts/redis7-start.sh.tpl
  deploy/redis/templates/clusterdefinition.yaml
  deploy/redis/templates/scripts.yaml
Labels: enhancement, size/S

#3781 fix: hscale inconsistent sc with cluster
  controllers/apps/components/internal/component_base_stateful_hscale_backup.go
  internal/controller/builder/builder_test.go
  internal/controller/builder/cue/pvc_template.cue
Labels: enhancement, approved, size/S

#3788 chore: push test rollback to runs on gke
  .github/workflows/cicd-push.yml
Labels: test, approved, size/M

#3790 fix: forbidden pre-release trigger winget auto-publish action
  .github/workflows/release-sync.yml
Labels: enhancement, release, size/XS

#3764 fix: cli not logged as error in memcache discovery client
  internal/cli/cmd/cli.go
  internal/cli/cmd/cli_test.go
  internal/cli/cmd/playground/init.go
Labels: enhancement, size/M

#3803 feat: replace mysql-exporter with agamotto
  deploy/apecloud-mysql/templates/agamotto-configmap.yaml
  deploy/apecloud-mysql/templates/clusterdefinition.yaml
  deploy/apecloud-mysql/values.yaml
Labels: feature, size/M

#3766 fix: remove the backup pod from kbcli cluster describe
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/type.go
  internal/cli/cluster/cluster.go
  internal/cli/cluster/cluster_test.go
  internal/constant/const.go
Labels: enhancement, approved, size/M

#3754 fix: vscale/volumeExpand takes not affect
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/opsrequest_webhook.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
Labels: enhancement, size/S

#3796 feat: support User-defined environment variables
  internal/constant/const.go
  internal/controller/builder/builder.go
  internal/controller/builder/builder_test.go
Labels: feature, size/M

#3806 chore: not check fork PR branch name
  .github/utils/utils.sh
  .github/workflows/pull-request-check.yml
  .github/workflows/pull-request-label-size.yaml
Labels: approved

#3800 feat: change monitor scrape annotations for uniqueness
  controllers/apps/components/util/component_utils.go
  controllers/apps/components/util/component_utils_test.go
  deploy/helm/dashboards/mysql-deprecated.json
  deploy/helm/dashboards/node-deprecated.json
  deploy/helm/dashboards/postgresql-deprecated.json
  deploy/helm/templates/addons/agamotto-addon.yaml
  deploy/helm/values.yaml
  internal/controller/builder/cue/headless_service_template.cue
Labels: feature, size/XXL

#3785 feat: support kafka with kraft mode
  deploy/helm/dashboards/kafka.json
  deploy/kafka-cluster/templates/_helpers.tpl
  deploy/kafka-cluster/templates/cluster.yaml
  deploy/kafka-cluster/values.yaml
  deploy/kafka/configs/kafka-server-constraint.cue
  deploy/kafka/configs/kafka-server.prop.tpl
  deploy/kafka/scripts/kafka-env.sh
  deploy/kafka/scripts/kafka-exporter-setup.sh.tpl
  deploy/kafka/scripts/kafka-sasl-sample.prop.tpl
  deploy/kafka/scripts/kafka-server-setup.sh.tpl
  deploy/kafka/scripts/kafka-ssl.prop.tpl
  deploy/kafka/scripts/libkafka.sh
  deploy/kafka/templates/clusterdefinition.yaml
  deploy/kafka/templates/clusterversion.yaml
  deploy/kafka/templates/configconstraint.yaml
  deploy/kafka/templates/scripts.yaml
  deploy/kafka/templates/storageclass.yaml
  deploy/kafka/values.yaml
Labels: feature, size/XXL

#3804 feat: replace pg-exporter with agamotto
  deploy/postgresql/templates/agamotto-configmap.yaml
  deploy/postgresql/templates/clusterdefinition.yaml
  deploy/postgresql/templates/clusterversion.yaml
  deploy/postgresql/values.yaml
Labels: feature, size/L

#3594 feat: kbcli check the validity of the cluster name
  internal/cli/cmd/cluster/cluster_test.go
  internal/cli/cmd/cluster/create.go
Labels: feature, size/M

#3819 chore: fix docs are incorrect for datafile backup
  docs/user_docs/kubeblocks-for-mongodb/backup-and-restore/data-file-backup-and-restore.md
  docs/user_docs/kubeblocks-for-mysql/backup-and-restore/data-file-backup-and-restore.md
  docs/user_docs/kubeblocks-for-postgresql/backup-and-restore/data-file-backup-and-restore.md
  docs/user_docs/kubeblocks-for-postgresql/backup-and-restore/pitr-for-postgresql.md
Labels: documentation, enhancement, approved, size/S

#3818 chore: revert postgresql wal_segment_size to default value 16M
  deploy/postgresql/templates/clusterdefinition.yaml
Labels: size/XS

#3736 feat: cli playground destroy should check cloud provider version
  internal/cli/cloudprovider/k3d.go
  internal/cli/cloudprovider/provider.go
  internal/cli/cloudprovider/types.go
  internal/cli/cmd/playground/base.go
Labels: feature, size/S

#3777 docs: update try-kubeblocks-on-cloud.md for potential security issue
  docs/user_docs/quick-start/try-kubeblocks-on-cloud.md
Labels: documentation, size/S

#3817 feat: h-scale policy auto failover with backup type
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/clusterdefinition_webhook.go
  apis/apps/v1alpha1/clusterdefinition_webhook_test.go
  apis/apps/v1alpha1/type.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  controllers/apps/cluster_controller_test.go
  controllers/apps/components/internal/component_base_stateful.go
  controllers/apps/components/internal/component_base_stateful_hscale.go
  controllers/apps/components/internal/component_base_stateful_hscale_backup.go
  controllers/apps/opsrequest_controller_test.go
  deploy/apecloud-mysql/templates/clusterdefinition.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
Labels: feature, size/L

#3830 fix: merge service annotations has logic error
  internal/controller/lifecycle/cluster_plan_builder.go
  internal/controller/lifecycle/cluster_plan_utils.go
  internal/controller/lifecycle/cluster_plan_utils_test.go
Labels: enhancement

#3746 feat: cli playground init on local should check the docker version
  go.mod
  go.sum
  internal/cli/cmd/playground/init.go
  internal/cli/cmd/playground/init_test.go
  internal/cli/util/system.go
  internal/cli/util/version.go
  internal/cli/util/version_test.go
  version/version.go
Labels: feature, documentation, size/M

#3815 feat: cli alert support config SMTP
  internal/cli/cmd/alert/add_receiver.go
  internal/cli/cmd/alert/add_receiver_test.go
  internal/cli/cmd/alert/alter.go
  internal/cli/cmd/alert/config_smtpserver.go
  internal/cli/cmd/alert/config_smtpserver_test.go
  internal/cli/cmd/alert/delete_receiver.go
  internal/cli/cmd/alert/delete_receiver_test.go
  internal/cli/cmd/alert/list_receivers.go
  internal/cli/cmd/alert/list_receivers_test.go
  internal/cli/cmd/alert/util.go
  internal/cli/cmd/alert/util_test.go
Labels: feature, approved, size/L

#3671 feat: support prometheus cluster by kubeblocks
  deploy/helm/templates/grafana/configmaps-datasources.yaml
  deploy/prometheus-cluster/.helmignore
  deploy/prometheus-cluster/Chart.yaml
  deploy/prometheus-cluster/templates/_helpers.tpl
  deploy/prometheus-cluster/templates/cluster.yaml
  deploy/prometheus-cluster/templates/clusterrole.yaml
  deploy/prometheus-cluster/templates/clusterrolebinding.yaml
  deploy/prometheus-cluster/templates/serviceaccount.yaml
  deploy/prometheus-cluster/templates/validate.yaml
  deploy/prometheus-cluster/values.yaml
  deploy/prometheus/.helmignore
  deploy/prometheus/Chart.yaml
  deploy/prometheus/config/alertmanager/alertmanager.yml
  deploy/prometheus/config/server/rulesFiles/kafka_alert_rules.yml
  deploy/prometheus/config/server/rulesFiles/mongodb_alert_rules.yaml
  deploy/prometheus/config/server/rulesFiles/mysql_alert_rules.yml
  deploy/prometheus/config/server/rulesFiles/postgresql_alert_rules.yml
  deploy/prometheus/config/server/rulesFiles/redis_alert_rules.yml
  deploy/prometheus/config/server/serverFiles/prometheus.yml
  deploy/prometheus/templates/_helpers.tpl
  deploy/prometheus/templates/backuppolicytemplate.yaml
  deploy/prometheus/templates/clusterdefinition.yaml
  deploy/prometheus/templates/clusterversion.yaml
  deploy/prometheus/templates/configconstraint.yaml
  deploy/prometheus/templates/configmap.yaml
  deploy/prometheus/values.yaml
Labels: area/user-interaction, feature, size/XXL

#3833 chore: refactor code for merge service annotations
  .gitignore
  controllers/apps/components/internal/component_base.go
  controllers/apps/components/util/component_utils.go
  controllers/apps/components/util/component_utils_test.go
Labels: refactor, size/M

#3832 feat: support warning version difference between kbcli and kubeblocks
  internal/cli/cmd/version/version.go
Labels: feature, size/XS

#3791 fix: resolve apecloud mysql-scale backup/restore, hscale and reconfig…
  deploy/apecloud-mysql-scale/scripts/mysql-reload.tpl
  deploy/apecloud-mysql-scale/templates/backuppolicytemplateforhscale.yaml
  deploy/apecloud-mysql-scale/templates/backuptool.yaml
  deploy/apecloud-mysql-scale/templates/clusterdefinition.yaml
  deploy/apecloud-mysql-scale/templates/configconstraint.yaml
Labels: area/user-interaction, enhancement, size/S

#3821 feat: kbcli class create support auto completion
  internal/cli/cmd/class/create.go
Labels: feature, approved, size/M

#3849 fix: failed to create JSONPatch (#3839)
  internal/unstructured/yaml_config.go
  internal/unstructured/yaml_config_test.go
  test/testdata/config_encoding/prometheus.yaml
Labels: enhancement, size/L

#3845 chore: new badge
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/codeql.yml
  README.md
Labels: size/M

#3778 fix: mongodb metrics sidecar fail after upgrade kubeblocks from 0.5 to 0.6
  controllers/apps/components/internal/component_base_stateful.go
  deploy/mongodb/templates/clusterdefinition.yaml
  deploy/mongodb/templates/metrics-configmap.yaml
  internal/constant/const.go
  internal/controller/plan/template_wrapper.go
Labels: enhancement, size/M

#3550 chore: support postgresql 12.15.0 and 14.8.0
  deploy/postgresql-cluster/Chart.yaml
  deploy/postgresql/templates/clusterversion.yaml
Labels: size/M

#3855 chore: makefile excludes generated clientset
  Makefile
  deploy/kafka/configs/kafka-server-constraint.cue
  internal/configuration/config_manager/builder_test.go
  internal/configuration/config_patch_test.go
  internal/configuration/type_test.go
  internal/controller/builder/cue/headless_service_template.cue
  internal/controller/plan/tool_image_builder.go
Labels: size/L

#3836 chore: set pod spec's default fields to avoid updating workload unexpectedly
  controllers/apps/components/internal/component_base_stateful.go
  controllers/apps/components/stateless/component_stateless.go
  controllers/apps/components/util/component_utils.go
  controllers/apps/components/util/component_utils_test.go
  internal/controller/builder/builder.go
Labels: size/L

#3829 fix: failed to install redis addon
  deploy/redis-demo-for-dynamic-switchover/Chart.yaml
  deploy/redis-demo-for-dynamic-switchover/templates/backuppolicytemplate.yaml
Labels: enhancement, approved, size/S

#3862 fix: revert volume name of mongodb metrics config
  deploy/mongodb/templates/clusterdefinition.yaml
Labels: enhancement, size/XS

#3864 feat: stateless support reconfiguring operation (#3831)
  apis/apps/v1alpha1/opsrequest_conditions.go
  controllers/apps/configuration/config_util.go
  controllers/apps/configuration/policy_util.go
  controllers/apps/configuration/policy_util_test.go
  controllers/apps/configuration/reconfigure_policy.go
  controllers/apps/configuration/reconfigurerequest_controller.go
  controllers/apps/configuration/simple_policy.go
  controllers/apps/configuration/simple_policy_test.go
  controllers/apps/configuration/types.go
  internal/configuration/config.go
Labels: feature, approved, size/XL

#3875 chore: kbcli e2e test workflow
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/e2e-kbcli.yml
  .github/workflows/release-helm-chart.yml
  .github/workflows/release-image.yml
  .github/workflows/release-publish.yml
Labels: test, approved, size/L

#3873 chore: helm chart default use aliyun docker registry
  deploy/mongodb/templates/_helpers.tpl
  deploy/mongodb/templates/clusterdefinition.yaml
  deploy/mongodb/templates/clusterversion.yaml
  deploy/mongodb/templates/sharding-clusterversion.yaml
  deploy/mongodb/values.yaml
  deploy/postgresql/values.yaml
  deploy/redis/templates/_helpers.tpl
  deploy/redis/templates/clusterdefinition.yaml
  deploy/redis/templates/clusterversion.yaml
  deploy/redis/values.yaml
Labels: documentation, approved, size/M

#3877 chore: rm CodeQL PR
  .github/workflows/codeql.yml
Labels: approved, size/XS

#3860 feat: support restore cluster via `kbcli cluster create`
  docs/user_docs/cli/kbcli_cluster_create.md
  internal/cli/cmd/cluster/create.go
  internal/cli/cmd/cluster/create_test.go
  internal/cli/cmd/cluster/dataprotection.go
Labels: area/user-interaction, feature, approved, size/L

#3854 feat: support mongo pitr
  apis/dataprotection/v1alpha1/backup_types.go
  apis/dataprotection/v1alpha1/backup_types_test.go
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  apis/dataprotection/v1alpha1/backuppolicy_types_test.go
  apis/dataprotection/v1alpha1/backuptool_types.go
  apis/dataprotection/v1alpha1/types.go
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuptools.yaml
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/backuppolicy_controller.go
  controllers/dataprotection/backuppolicy_controller_test.go
  controllers/dataprotection/cue/manifests_updater.cue
  controllers/dataprotection/restorejob_controller_test.go
  controllers/dataprotection/type.go
  controllers/dataprotection/utils.go
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuptools.yaml
  deploy/mongodb-cluster/templates/role.yaml
  deploy/mongodb/templates/_helpers.tpl
  deploy/mongodb/templates/backuppolicytemplate.yaml
  deploy/mongodb/templates/backuptool.yaml
  deploy/mongodb/templates/backuptool_pitr.yaml
  deploy/mongodb/templates/clusterversion.yaml
  deploy/mongodb/templates/sharding-clusterversion.yaml
  deploy/mongodb/values.yaml
  internal/cli/cmd/cluster/create.go
  internal/constant/const.go
  internal/controller/plan/restore.go
  internal/controller/plan/restore_test.go
  internal/controllerutil/errors.go
  internal/controllerutil/errors_test.go
  internal/controllerutil/pod_utils.go
  internal/testutil/apps/backuppolicy_factory.go
  test/integration/backup_mysql_test.go
Labels: area/user-interaction, feature, approved, size/XXL

#3538 chore: component set to use synthesized component
  controllers/apps/components/consensus/component_consensus.go
  controllers/apps/components/consensus/consensus.go
  controllers/apps/components/internal/component_base.go
  controllers/apps/components/internal/component_set.go
  controllers/apps/components/replication/component_replication.go
  controllers/apps/components/replication/replication.go
  controllers/apps/components/stateful/component_stateful.go
  controllers/apps/components/stateful/stateful.go
  controllers/apps/components/stateless/component_stateless.go
  controllers/apps/components/stateless/stateless.go
  controllers/apps/components/types/component.go
Labels: size/L

#3885 chore: add image registry for pgbouncer image
  deploy/postgresql/templates/clusterversion.yaml
Labels: approved, size/XS

#3881 fix: add tolerations for cronjob
  controllers/dataprotection/backuppolicy_controller.go
  controllers/dataprotection/backuppolicy_controller_test.go
  controllers/dataprotection/cue/cronjob.cue
  controllers/dataprotection/type.go
  internal/cli/cmd/cluster/create_test.go
  internal/cli/cmd/cluster/dataprotection_test.go
Labels: enhancement, approved, size/M

#3891 chore: support mongodb snapshot
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  apis/dataprotection/v1alpha1/backup_types.go
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  controllers/apps/cluster_controller_test.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/utils.go
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/mongodb/scripts/backup-log-collector.tpl
  deploy/mongodb/templates/backuppolicytemplate.yaml
  deploy/mongodb/templates/backuptool_pitr.yaml
  deploy/mongodb/templates/clusterdefinition.yaml
  deploy/mongodb/templates/scriptstemplate.yaml
Labels: approved, size/L

#3866 fix: output more friendly when run `kbcli cluster vscale` with invalid input
  internal/cli/cmd/cluster/operations.go
  internal/cli/cmd/cluster/operations_test.go
Labels: enhancement, size/M

#3895 chore: support legitimacy validation for logfile backup and display availablePods for running backup
  apis/dataprotection/v1alpha1/backup_types.go
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  controllers/apps/cluster_controller_test.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/backuppolicy_controller.go
  controllers/dataprotection/backuppolicy_controller_test.go
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  internal/cli/cmd/cluster/dataprotection.go
  internal/cli/cmd/cluster/dataprotection_test.go
  internal/controllerutil/errors.go
Labels: approved, size/L

#3902 chore: auto create volumesnapshotclass
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/cue/cronjob.cue
  deploy/helm/values.yaml
  internal/controller/builder/builder.go
  internal/controller/builder/cue/volumesnapshotclass.cue
  internal/controllerutil/volumesnapshot.go
Labels: approved, size/L

#3904 chore: use container command instead of args for backup command
  apis/dataprotection/v1alpha1/backup_types.go
  controllers/apps/transformer_backup_policy_tpl.go
  controllers/dataprotection/backup_controller.go
  deploy/apecloud-mysql-scale/templates/backuptool.yaml
  deploy/apecloud-mysql/templates/backuptool.yaml
  deploy/mongodb/templates/backuppolicytemplate.yaml
  deploy/mongodb/templates/backuptool.yaml
  deploy/mongodb/templates/backuptool_pitr.yaml
  deploy/postgresql/templates/backuptool-pitr.yaml
  deploy/postgresql/templates/backuptool.yaml
  internal/controller/builder/builder.go
  internal/controller/builder/cue/restore_job_template.cue
  internal/controller/plan/restore.go
  test/testdata/backup/backuptool.yaml
Labels: size/L

#3901 chore: have Addon's chartLocationURL attribute setup as '.Values.addonChartLocationBase' template value (#3899)
  deploy/helm/templates/addons/alertmanager-webhook-adaptor-addon.yaml
  deploy/helm/templates/addons/apecloud-mysql-addon.yaml
  deploy/helm/templates/addons/aws-loadbalancer-controller-addon.yaml
  deploy/helm/templates/addons/csi-driver-addon.yaml
  deploy/helm/templates/addons/csi-hostpath-driver-addon.yaml
  deploy/helm/templates/addons/csi-s3-addon.yaml
  deploy/helm/templates/addons/grafana-addon.yaml
  deploy/helm/templates/addons/migration-addon.yaml
  deploy/helm/templates/addons/milvus-addon.yaml
  deploy/helm/templates/addons/mongodb-addon.yaml
  deploy/helm/templates/addons/nyancat-addon.yaml
  deploy/helm/templates/addons/postgresql-addon.yaml
  deploy/helm/templates/addons/prometheus-addon.yaml
  deploy/helm/templates/addons/qdrant-addon.yaml
  deploy/helm/templates/addons/redis-addon.yaml
  deploy/helm/templates/addons/snapshot-controller-addon.yaml
  deploy/helm/templates/addons/weaviate-addon.yaml
  deploy/helm/values.yaml
Labels: size/M

#3886 chore: not cancel push main workflow
  .github/workflows/cicd-push.yml
Labels: size/XS

#3903 feat: add loki dashboard for kubernetes pods log
  deploy/helm/dashboards/container-log.json
  deploy/helm/templates/grafana/configmaps-datasources.yaml
  internal/cli/cmd/dashboard/dashboard.go
  internal/cli/cmd/dashboard/grafana_direct.go
Labels: feature, size/L

#3883 fix: configmap mounted with subPath do not update when changed (#3870)
  internal/configuration/config_manager/handler_util.go
  internal/configuration/config_manager/handler_util_test.go
  internal/configuration/config_util.go
  internal/configuration/config_util_test.go
  internal/controller/plan/prepare.go
  internal/gotemplate/tpl_engine.go
Labels: enhancement, approved, size/L

#3909 feat: cli plugin adopt the block index repository
  controllers/apps/configuration/config_util.go
  controllers/apps/configuration/reconfigurerequest_controller.go
  go.mod
  go.sum
  internal/cli/cmd/plugin/types.go
  internal/cli/cmd/plugin/utils.go
  internal/controllerutil/volumesnapshot.go
Labels: area/user-interaction, feature, size/M

#3890 chore: unify platform software for kbcli
  .github/workflows/release-publish.yml
  .goreleaser.yaml
Labels: size/L

#3892 chore: add .github/utils/extract_chart_n_image_list.sh for extracting KB chart URL and image repo tag
  .github/utils/extract_chart_n_image_list.sh
Labels: size/M

#3917 chore: fix e2e kbcli test
  .github/workflows/e2e-kbcli.yml
Labels: test, enhancement, approved, size/XS

#3918 fix: set failed when volumesnapshot config error (#3816)
  controllers/dataprotection/backuppolicy_controller.go
Labels: enhancement

#3716 feat: support nebulagraph
  deploy/nebula-cluster/Chart.yaml
  deploy/nebula-cluster/templates/NOTES.txt
  deploy/nebula-cluster/templates/_helpers.tpl
  deploy/nebula-cluster/templates/cluster.yaml
  deploy/nebula-cluster/values.yaml
  deploy/nebula/Chart.yaml
  deploy/nebula/configs/nebula-graphd.conf.tpl
  deploy/nebula/configs/nebula-metad.conf.tpl
  deploy/nebula/configs/nebula-storaged.conf.tpl
  deploy/nebula/scripts/nebula-graphd-start.sh.tpl
  deploy/nebula/scripts/nebula-metad-start.sh.tpl
  deploy/nebula/scripts/nebula-storaged-start.sh.tpl
  deploy/nebula/templates/NOTES.txt
  deploy/nebula/templates/_helpers.tpl
  deploy/nebula/templates/backuppolicytemplate.yaml
  deploy/nebula/templates/clusterdefinition.yaml
  deploy/nebula/templates/clusterversion.yaml
  deploy/nebula/templates/configconstraint.yaml
  deploy/nebula/templates/configmap.yaml
  deploy/nebula/templates/scripts.yaml
  deploy/nebula/values.yaml
Labels: area/user-interaction, feature, size/XXL

#3923 chore: rm artifacthub badge
  README.md
Labels: approved, size/XS

#3922 chore: support unique logfile backup for statefulSetKind
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backuppolicy_controller.go
  controllers/dataprotection/backuppolicy_controller_test.go
  controllers/dataprotection/utils.go
Labels: size/L

#3930 chore: tls_utils.go coverage to 90.0%
  internal/controller/builder/builder.go
  internal/controller/builder/builder_secret.go
  internal/controller/builder/builder_secret_test.go
  internal/controller/builder/cue/tls_certs_secret_template.cue
  internal/controller/plan/tls_utils.go
  internal/controller/plan/tls_utils_test.go
Labels: area/lifecycle, size/L

#3924 feat: addon support to set private registry
  deploy/helm/templates/addons/agamotto-addon.yaml
  deploy/helm/templates/addons/alertmanager-webhook-adaptor-addon.yaml
  deploy/helm/templates/addons/apecloud-mysql-addon.yaml
  deploy/helm/templates/addons/aws-loadbalancer-controller-addon.yaml
  deploy/helm/templates/addons/chaos-mesh-addon.yaml
  deploy/helm/templates/addons/csi-driver-addon.yaml
  deploy/helm/templates/addons/csi-hostpath-driver-addon.yaml
  deploy/helm/templates/addons/csi-s3-addon.yaml
  deploy/helm/templates/addons/grafana-addon.yaml
  deploy/helm/templates/addons/loki-addon.yaml
  deploy/helm/templates/addons/migration-addon.yaml
  deploy/helm/templates/addons/milvus-addon.yaml
  deploy/helm/templates/addons/mongodb-addon.yaml
  deploy/helm/templates/addons/nyancat-addon.yaml
  deploy/helm/templates/addons/opensearch-addon.yaml
  deploy/helm/templates/addons/postgresql-addon.yaml
  deploy/helm/templates/addons/prometheus-addon.yaml
  deploy/helm/templates/addons/qdrant-addon.yaml
  deploy/helm/templates/addons/redis-addon.yaml
  deploy/helm/templates/addons/snapshot-controller-addon.yaml
  deploy/helm/templates/addons/weaviate-addon.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
Labels: feature, size/L

#3931 chore: revise wrapper dir
  .goreleaser.yaml
Labels: size/XS

#3933 chore: fix staticcheck error
  internal/controller/builder/builder.go
  internal/controller/rsm/pod_role_event_handler_test.go
Labels: enhancement, size/S

#3942 chore: optimize release kbcli
  .github/workflows/release-image.yml
  .github/workflows/release-publish.yml
Labels: release, approved, size/L

#3943 fix: pitr recoverable time is incorrect
  apis/dataprotection/v1alpha1/backup_types.go
Labels: enhancement

#3947 fix: missing volumesnapshotclass rbac
  config/rbac/role.yaml
  controllers/dataprotection/backup_controller.go
  deploy/helm/config/rbac/role.yaml
Labels: enhancement, size/M

#3956 fix: mongodb post start script
  deploy/mongodb/scripts/replicaset-post-start.tpl
Labels: enhancement

#3954 fix: mongodb post start script
  deploy/mongodb/scripts/replicaset-post-start.tpl
Labels: enhancement, size/XS

#3959 chore: rename chaos-mesh addon
  deploy/helm/templates/addons/chaos-mesh-addon.yaml
Labels: size/XS

#3936 chore: disable performance schema for smaller class
  deploy/apecloud-mysql/config/mysql8-config.tpl
Labels: size/XS

#3869 feat: add prometheus cluster into addons
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/release-helm-chart.yml
  .gitignore
  deploy/helm/templates/addons/prometheus-addon.yaml
  deploy/helm/templates/grafana/configmaps-datasources.yaml
  deploy/helm/templates/prometheus/alertmanager.yaml
  deploy/helm/values.yaml
  deploy/prometheus-cluster/Chart.yaml
  deploy/prometheus-cluster/templates/cluster.yaml
  deploy/prometheus-cluster/values.yaml
  deploy/prometheus/Chart.yaml
  deploy/prometheus/config/server/serverFiles/prometheus.yml
  deploy/prometheus/templates/configmap.yaml
  internal/cli/cmd/dashboard/dashboard.go
Labels: area/user-interaction, feature, size/XXL

#3967 chore: delete release schedule
  .github/utils/utils.sh
  .github/workflows/release-delete.yml
  .github/workflows/release-helm-chart.yml
  .github/workflows/release-image.yml
  .github/workflows/release-publish.yml
Labels: release, approved, size/M

#3969 fix: inaccurate comparison of kbcli and kubeblock version
  internal/cli/cmd/version/version.go
  internal/cli/cmd/version/version_test.go
Labels: enhancement, size/M

#3972 fix: mongodb pod terminating take too long time
  deploy/mongodb/scripts/replicaset-post-start.tpl
Labels: enhancement

#3971 fix: mongodb pod terminating takes too long time
  deploy/mongodb/scripts/replicaset-post-start.tpl
Labels: enhancement, approved, size/S

#3944 feat: add addon for nebula.
  deploy/helm/templates/addons/nebula-addon.yaml
Labels: area/user-interaction, feature, size/M

#3976 chore: fix gh token
  .github/workflows/release-helm-chart.yml
  .github/workflows/release-image.yml
  .github/workflows/release-publish.yml
Labels: enhancement, approved, size/XS

#3935 fix: mysql hscale restore file
  deploy/apecloud-mysql/templates/backuppolicytemplateforhscale.yaml
  deploy/apecloud-mysql/templates/backuptoolforhscale.yaml
Labels: enhancement, size/M

#3986 fix: reset password for mongodb restore
  deploy/mongodb/scripts/replicaset-post-start.tpl
Labels: enhancement

#3982 fix: rename rule config path and add staticParameters
  deploy/prometheus/config/server/rulesFiles/mongodb_alert_rules.yml
  deploy/prometheus/config/server/serverFiles/prometheus.yml
  deploy/prometheus/templates/configconstraint.yaml
Labels: area/user-interaction, enhancement, size/XS

#3979 fix: recoverable time incorrect
  apis/dataprotection/v1alpha1/backup_types.go
  apis/dataprotection/v1alpha1/backup_types_test.go
  deploy/mongodb/templates/backuptool_pitr.yaml
Labels: enhancement, size/S

#3958 chore: support replicationSet rolling update with role strategy
  apis/apps/v1alpha1/clusterdefinition_types.go
  controllers/apps/components/component_status_test.go
  controllers/apps/components/consensus/consensus.go
  controllers/apps/components/consensus/consensus_utils.go
  controllers/apps/components/replication/replication.go
  controllers/apps/components/replication/replication_test.go
  controllers/apps/components/replication/replication_utils.go
  controllers/apps/components/stateful/stateful.go
Labels: approved, size/L

#3978 fix: fix default install version for kubeblocks
  .goreleaser.yaml
Labels: enhancement, size/S
