Repository apecloud/kubeblocks, pull requests merged in 2023-09, with the labels that each got.

#4954 feat: mongodb support ft
  deploy/mongodb/Chart.yaml
  deploy/mongodb/scripts/replicaset-post-start.tpl
  deploy/mongodb/scripts/replicaset-restore.tpl
  deploy/mongodb/scripts/replicaset-setup.tpl
  deploy/mongodb/templates/clusterversion.yaml
  internal/sqlchannel/engine/mongodb.go
Labels: feature

#4960 feat: mongodb support ft
  deploy/mongodb/Chart.yaml
  deploy/mongodb/scripts/backup-log-collector.tpl
  deploy/mongodb/scripts/replicaset-post-start.tpl
  deploy/mongodb/scripts/replicaset-restore.tpl
  deploy/mongodb/scripts/replicaset-setup.tpl
  deploy/mongodb/templates/backuptool.yaml
  deploy/mongodb/templates/backuptool_pitr.yaml
  deploy/mongodb/templates/clusterversion.yaml
  deploy/mongodb/templates/scriptstemplate.yaml
  internal/sqlchannel/engine/mongodb.go
Labels: feature, size/L

#4970 fix: run test e2e on lacal add create clusterrole
  Makefile
  test/e2e/testdata/smoketest/playgroundtest.go
  test/e2e/testdata/smoketest/smoketestrun.go
  test/e2e/util/smoke_util.go
Labels: test, enhancement, approved, size/M

#4957 fix: remove neon's remaining resources
  Makefile
  deploy/cert-manager/Chart.yaml
  deploy/cert-manager/templates/NOTES.txt
  deploy/cert-manager/templates/cert-manager.yaml
  deploy/cert-manager/values.yaml
  deploy/neon-cluster/templates/vm-compute-node-deploy.yaml
  deploy/neon-cluster/values.schema.json
  deploy/neon/crds/multus-crd.yaml
  deploy/neon/crds/multus.yaml
  deploy/neon/templates/NOTES.txt
  deploy/neon/templates/multus-deploy.yaml
  docs/user_docs/cli/kbcli_cluster_create.md
  internal/cli/cluster/neon.go
  internal/cli/cmd/fault/fault.go
Labels: enhancement, approved, size/XXL

#4969 chore: merged e2e smoke test
  .github/utils/utils.sh
  .github/workflows/cicd-merge.yml
  .github/workflows/merge-e2e-smoke.yml
Labels: test, approved, size/L

#4979 chore: fix branch deleted when merged
  .github/workflows/merge-e2e-smoke.yml
Labels: enhancement, approved, size/S

#4965 fix: failed to update opsrequest (#4951)
  controllers/apps/operations/reconfigure_util.go
  internal/configuration/core/config_util.go
  internal/configuration/core/config_util_test.go
Labels: enhancement, size/M

#4866 fix: double check for kb upgrade
  docs/user_docs/cli/kbcli_kubeblocks_upgrade.md
  internal/cli/cmd/accounts/delete.go
  internal/cli/cmd/cluster/operations.go
  internal/cli/cmd/kubeblocks/install.go
  internal/cli/cmd/kubeblocks/list_versions_test.go
  internal/cli/cmd/kubeblocks/upgrade.go
  internal/cli/cmd/kubeblocks/upgrade_test.go
  internal/cli/delete/delete.go
  internal/cli/util/helm/helm.go
  internal/cli/util/prompt/prompt.go
Labels: enhancement, size/M

#4983 docs: adjust docs tabs
  docs/developer_docs/api-reference/_category_.yml
  docs/developer_docs/api-reference/add-on.md
  docs/developer_docs/api-reference/backup.md
  docs/developer_docs/api-reference/cluster.md
  docs/developer_docs/fault_injection/_category_.yaml
  docs/developer_docs/fault_injection/aws-fault.md
  docs/developer_docs/fault_injection/dns-faults.md
  docs/developer_docs/fault_injection/gcp-fault.md
  docs/developer_docs/fault_injection/http-fault.md
  docs/developer_docs/fault_injection/introduction.md
  docs/developer_docs/fault_injection/io-faults.md
  docs/developer_docs/fault_injection/network-faults.md
  docs/developer_docs/fault_injection/pod-faults.md
  docs/developer_docs/fault_injection/prerequisite.md
  docs/developer_docs/fault_injection/stress-fault.md
  docs/developer_docs/fault_injection/time-fault.md
  docs/developer_docs/integration/_category_.yaml
  docs/developer_docs/integration/add-ons-of-kubeblocks.md
  docs/developer_docs/integration/backup-and-restore.md
  docs/developer_docs/integration/how-to-add-an-add-on.md
  docs/developer_docs/overview.md
  docs/user_docs/kubeblocks-for-mongodb/kubeblocks-for-mongodb.md
  docs/user_docs/kubeblocks-for-mongodb/migration/migration-kbcli.md
  docs/user_docs/kubeblocks-for-mysql/cluster-management/switchover.md
  docs/user_docs/kubeblocks-for-mysql/high-availability/high-availability.md
  docs/user_docs/kubeblocks-for-mysql/kubeblocks-for-mysql.md
  docs/user_docs/kubeblocks-for-mysql/migration/migration-kbcli.md
  docs/user_docs/kubeblocks-for-mysql/proxy/apecloud-mysql-proxy.md
  docs/user_docs/kubeblocks-for-postgresql/kubeblocks-for-postgresql.md
  docs/user_docs/kubeblocks-for-postgresql/migration/migration-postgresql.md
  docs/user_docs/kubeblocks-for-redis/kubeblocks-for-redis.md
Labels: documentation, size/XL

#4985 fix: fix jupyter-hub enable fail in GKE
  deploy/helm/templates/addons/jupyterhub-addon.yaml
Labels: enhancement, size/XS

#4966 fix: failed to update statefulSet for rsm component when reconfiguring
  controllers/apps/configuration/config_reconcile_wrapper.go
  controllers/apps/configuration/reconfigurerequest_controller.go
Labels: enhancement, approved, size/S

#4989 docs: fix invalid links
  docs/developer_docs/overview.md
Labels: documentation, enhancement, size/XS

#4991 docs: adjust sidebar position
  docs/developer_docs/api-reference/_category_.yml
  docs/developer_docs/fault_injection/_category_.yaml
  docs/developer_docs/integration/_category_.yaml
Labels: documentation, size/XS

#4990 fix: Use eventTime to obtain a more precise timestamp for the event.
  cmd/probe/internal/binding/utils.go
Labels: enhancement, ci, size/XS

#4982 fix: compare and select pods by ordinal at scale-in
  controllers/apps/components/base_stateful.go
Labels: enhancement, approved, size/XS

#5002 docs: fix format bugs
  docs/developer_docs/integration/backup-and-restore.md
  docs/developer_docs/integration/how-to-add-an-add-on.md
Labels: documentation, bug, enhancement, size/XL

#5008 fix: mongodb restore
  deploy/mongodb/scripts/replicaset-setup.tpl
Labels: enhancement, approved, size/XS

#5011 docs: update addon docs
  docs/developer_docs/integration/backup-and-restore.md
  docs/developer_docs/integration/how-to-add-an-add-on.md
Labels: documentation, size/L

#5021 fix: remove security context of etcd component
  deploy/greptimedb/templates/clusterdefinition.yaml
Labels: enhancement, size/XS

#5016 feat: add addon for minio
  deploy/helm/templates/addons/minio.yaml
  internal/cli/cmd/dashboard/dashboard.go
Labels: area/user-interaction, feature, size/M

#4924 feat: cli create/update support backup flags
  docs/user_docs/cli/kbcli_cluster_create.md
  docs/user_docs/cli/kbcli_cluster_update.md
  go.mod
  internal/cli/cmd/cluster/create.go
  internal/cli/cmd/cluster/create_test.go
  internal/cli/cmd/cluster/update.go
  internal/cli/create/template/cluster_template.cue
Labels: feature, size/L

#4992 feat: opsrequest support backup
  apis/apps/v1alpha1/opsrequest_conditions.go
  apis/apps/v1alpha1/opsrequest_conditions_test.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/backup.go
  controllers/apps/operations/backup_test.go
  controllers/apps/operations/type.go
  controllers/apps/operations/util/common_util.go
  controllers/apps/operations/util/common_util_test.go
  controllers/apps/opsrequest_controller.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
Labels: feature, size/L

#5023 chore: add e2e test cases
  Makefile
  test/e2e/testdata/smoketest/greptimedb/00_greptimedbcluster.yaml
  test/e2e/testdata/smoketest/greptimedb/01_vexpand.yaml
  test/e2e/testdata/smoketest/greptimedb/02_stop.yaml
  test/e2e/testdata/smoketest/greptimedb/03_start.yaml
  test/e2e/testdata/smoketest/greptimedb/04_vscale.yaml
  test/e2e/testdata/smoketest/greptimedb/05_restart.yaml
  test/e2e/testdata/smoketest/greptimedb/06_hscale.yaml
  test/e2e/testdata/smoketest/nebula/00_nebulacluster.yaml
  test/e2e/testdata/smoketest/nebula/01_vexpand.yaml
  test/e2e/testdata/smoketest/nebula/02_stop.yaml
  test/e2e/testdata/smoketest/nebula/03_start.yaml
  test/e2e/testdata/smoketest/nebula/04_vscale.yaml
  test/e2e/testdata/smoketest/nebula/05_restart.yaml
  test/e2e/testdata/smoketest/nebula/06_hscale.yaml
  test/e2e/testdata/smoketest/risingwave/00_risingwavecluster.yaml
  test/e2e/testdata/smoketest/risingwave/01_stop.yaml
  test/e2e/testdata/smoketest/risingwave/02_start.yaml
  test/e2e/testdata/smoketest/risingwave/03_vscale.yaml
  test/e2e/testdata/smoketest/risingwave/04_restart.yaml
  test/e2e/testdata/smoketest/risingwave/05_hscale.yaml
  test/e2e/testdata/smoketest/starrocks/00_starrocksbcluster.yaml
  test/e2e/testdata/smoketest/starrocks/01_vexpand.yaml
  test/e2e/testdata/smoketest/starrocks/02_stop.yaml
  test/e2e/testdata/smoketest/starrocks/03_start.yaml
  test/e2e/testdata/smoketest/starrocks/04_vscale.yaml
  test/e2e/testdata/smoketest/starrocks/05_restart.yaml
  test/e2e/testdata/smoketest/starrocks/06_hscale.yaml
  test/e2e/util/smoke_util.go
Labels: test, approved, size/XL

#5029 fix: kbcli connect mongodb
  deploy/mongodb/dataprotection/backup-info-collector.sh
  deploy/mongodb/dataprotection/pitr-backup.sh
  deploy/mongodb/scripts/replicaset-restore.tpl
  deploy/mongodb/scripts/replicaset-setup.tpl
  deploy/mongodb/templates/scriptstemplate.yaml
  internal/controller/builder/builder.go
  internal/sqlchannel/engine/mongodb.go
Labels: enhancement, size/S

#5032 fix: mongodb connect
  deploy/mongodb/scripts/replicaset-restore.tpl
  deploy/mongodb/scripts/replicaset-setup.tpl
  deploy/mongodb/templates/scriptstemplate.yaml
  internal/sqlchannel/engine/mongodb.go
Labels: enhancement, size/S

#4947 fix: cluster phase changed to running when role probe not ready
  controllers/apps/cluster_controller_test.go
  controllers/apps/components/component.go
  controllers/apps/components/rsm_set.go
  controllers/apps/components/rsm_set_test.go
  controllers/apps/components/stateful_set.go
  controllers/apps/components/stateless_set.go
  controllers/apps/components/status_test.go
  controllers/apps/components/utils.go
  controllers/apps/components/utils_test.go
  controllers/apps/operations/restart.go
  controllers/apps/opsrequest_controller_test.go
  internal/controller/rsm/suite_test.go
  internal/controller/rsm/transformer_member_reconfiguration.go
  internal/controller/rsm/transformer_member_reconfiguration_test.go
  internal/controller/rsm/transformer_status.go
  internal/controller/rsm/utils.go
  internal/testutil/apps/cluster_consensus_test_util.go
  internal/testutil/k8s/rsm_util.go
Labels: area/cluster-controller, enhancement, size/L

#5024 chore: add options --set logCollector.enabled for apecloud-mysql addon
  deploy/apecloud-mysql/templates/_helpers.tpl
  deploy/apecloud-mysql/templates/clusterdefinition.yaml
  deploy/apecloud-mysql/values.yaml
Labels: size/S

#5042 chore: add options --set logCollector.enabled for apecloud-mysql addon
  deploy/apecloud-mysql/templates/_helpers.tpl
  deploy/apecloud-mysql/templates/clusterdefinition.yaml
  deploy/apecloud-mysql/values.yaml
Labels: size/S

#4994 fix: use data volume as restore tmp dir for apecloud-mysql
  deploy/apecloud-mysql/templates/backuptool.yaml
  deploy/apecloud-mysql/templates/backuptoolforhscale.yaml
Labels: enhancement, size/S

#5039 feat: storage provider add obs, the huaweicloud object stroage
  deploy/helm/templates/addons/csi-s3-addon.yaml
  deploy/helm/templates/storageprovider/obs.yaml
Labels: area/user-interaction, feature, size/M

#5043 chore: upload gitlab asset error retry
  .github/utils/release_gitlab.sh
Labels: approved, size/S

#4988 fix: improve official pg
  cmd/probe/internal/component/postgres/apecloudpostgres/manager.go
  cmd/probe/internal/component/postgres/manager.go
  cmd/probe/internal/component/postgres/officalpostgres/manager.go
  cmd/probe/internal/component/postgres/officalpostgres/manager_test.go
  cmd/probe/internal/component/postgres/types.go
Labels: enhancement, approved, size/L

#5051 fix: fix some hard-code addonChartURL
  deploy/helm/templates/addons/bytebase-addon.yaml
  deploy/helm/templates/addons/jupyter-notebook-addon.yaml
  deploy/helm/templates/addons/orioledb-addon.yaml
Labels: enhancement, size/S

#4739 feat: config for monitoring oracle-mysql cluster
  deploy/oracle-mysql/templates/clusterdefinition.yaml
  deploy/oracle-mysql/templates/clusterversion.yaml
Labels: feature, approved, size/S

#5058 chore: support risingwave addon
  deploy/helm/templates/addons/risingwave-addon.yaml
Labels: approved, size/M

#5069 chore: rephrase pg conn example
  controllers/apps/transformer_cluster_status.go
  internal/configuration/openapi/cue_gen_openapi.go
  internal/sqlchannel/engine/postgresql.go
Labels: approved, size/S

#5071 fix: Refine error message of k8s version check
  internal/cli/cmd/kubeblocks/data/ack_preflight.yaml
  internal/cli/cmd/kubeblocks/data/eks_preflight.yaml
  internal/cli/cmd/kubeblocks/data/gke_preflight.yaml
  internal/cli/cmd/kubeblocks/data/kubeblocks_base_preflight.yaml
  internal/cli/cmd/kubeblocks/data/tke_preflight.yaml
Labels: enhancement, approved, size/S

#5052 feat: kbcli cluster register cmd for cluster create config
  Makefile
  deploy/orioledb-cluster/values.schema.json
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli_cluster.md
  docs/user_docs/cli/kbcli_cluster_create.md
  internal/cli/cluster/builtin_charts.go
  internal/cli/cluster/cluster_chart.go
  internal/cli/cluster/external_charts.go
  internal/cli/cluster/kafka.go
  internal/cli/cluster/mongodb.go
  internal/cli/cluster/mysql.go
  internal/cli/cluster/neon.go
  internal/cli/cluster/postgresql.go
  internal/cli/cluster/redis.go
  internal/cli/cluster/register.go
  internal/cli/cluster/register_test.go
  internal/cli/cmd/cluster/cluster.go
  internal/cli/cmd/cluster/create_subcmds.go
  internal/cli/cmd/cluster/register.go
  internal/cli/cmd/cluster/register_test.go
  internal/cli/types/types.go
  internal/cli/util/helm/downloader.go
Labels: feature, size/XL

#5073 feat: Lorry support PolarX
  cmd/lorry/main.go
  config/lorry/components/binding_polarx.yaml
  lorry/binding/polardbx/polardbx.go
  lorry/component/mysql/config.go
  lorry/component/polardbx/config.go
  lorry/component/polardbx/manager.go
Labels: area/user-interaction, feature, approved, size/L

#5086 chore: make lorry change compatible
  docker/Dockerfile-tools
  docker/Dockerfile-tools.bk
Labels: size/L

#5013 chore: mount data volume to the lorry container identically to the db container
  controllers/apps/components/consensus_set_utils.go
  internal/constant/env.go
  internal/controller/component/probe_utils.go
Labels: approved, size/M

#5092 chore: add more e2e test type
  .github/workflows/e2e-kbcli.yml
  .github/workflows/e2e-smoke.yml
Labels: test, approved, size/S

#4993 chore: sync opsrequest status for reconfiguring (#4953)
  controllers/apps/operations/reconfigure.go
  controllers/apps/operations/reconfigure_test.go
Labels: approved, size/S

#4937 chore: check containers.volumeMounts and containers.envFrom (#4421)
  controllers/apps/configuration/config_related_helper.go
  controllers/apps/configuration/config_util.go
  internal/configuration/core/type.go
  internal/controller/plan/envfrom_utils.go
  internal/controller/plan/envfrom_utils_test.go
  internal/controller/plan/prepare_test.go
  internal/controllerutil/pod_utils.go
  internal/controllerutil/pod_utils_test.go
  internal/controllerutil/volume_util.go
Labels: approved, size/M

#5082 feat: support `kbcli cluster register` for local charts
  internal/cli/cmd/cluster/register.go
  internal/cli/cmd/cluster/register_test.go
Labels: feature, size/L

#5100 docs: update backup docs
  docs/user_docs/backup-and-restore/backup/backup-repo.md
Labels: documentation, size/L

#5105 chore: not checkout fork from main
  .github/workflows/cicd-pull-request.yml
Labels: size/XS

#5104 chore: update rw values
  deploy/risingwave-cluster/values.schema.json
  deploy/risingwave-cluster/values.yaml
Labels: size/M

#5102 fix: solving the problem of private image
  controllers/apps/components/utils.go
Labels: enhancement, approved, size/XS

#5112 chore: service reference config template render support cross namespace
  controllers/apps/servicedescriptor_controller_test.go
  internal/controller/plan/config_template.go
  internal/controller/plan/config_template_utils.go
  internal/controller/plan/config_template_utils_test.go
  internal/controller/plan/service_descriptor_utils.go
Labels: approved, size/S

#5072 feat: pg parse history
  lorry/component/postgres/local_command.go
  lorry/component/postgres/officalpostgres/manager.go
  lorry/component/postgres/types.go
  lorry/component/postgres/types_test.go
Labels: feature, approved, size/L

#5054 chore: build cluster phase by observation
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/opsrequest_webhook_test.go
  apis/apps/v1alpha1/type.go
  apis/workloads/v1alpha1/replicatedstatemachine_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  config/crd/bases/workloads.kubeblocks.io_replicatedstatemachines.yaml
  controllers/apps/cluster_controller_test.go
  controllers/apps/components/base.go
  controllers/apps/components/base_stateful.go
  controllers/apps/components/base_stateful_hscale.go
  controllers/apps/components/base_stateful_legacy.go
  controllers/apps/components/rsm_set.go
  controllers/apps/components/rsm_set_test.go
  controllers/apps/components/stateless.go
  controllers/apps/components/status.go
  controllers/apps/components/status_test.go
  controllers/apps/components/utils.go
  controllers/apps/operations/datascript_test.go
  controllers/apps/operations/expose.go
  controllers/apps/operations/horizontal_scaling.go
  controllers/apps/operations/horizontal_scaling_test.go
  controllers/apps/operations/ops_progress_util_test.go
  controllers/apps/operations/ops_util.go
  controllers/apps/operations/reconfigure.go
  controllers/apps/operations/reconfigure_test.go
  controllers/apps/operations/restart.go
  controllers/apps/operations/restart_test.go
  controllers/apps/operations/start.go
  controllers/apps/operations/stop.go
  controllers/apps/operations/suite_test.go
  controllers/apps/operations/switchover.go
  controllers/apps/operations/upgrade.go
  controllers/apps/operations/upgrade_test.go
  controllers/apps/operations/vertical_scaling.go
  controllers/apps/operations/vertical_scaling_test.go
  controllers/apps/opsrequest_controller_test.go
  controllers/apps/systemaccount_controller_test.go
  controllers/apps/transformer_cluster_deletion.go
  controllers/apps/transformer_cluster_status.go
  controllers/apps/transformer_init.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/workloads.kubeblocks.io_replicatedstatemachines.yaml
  internal/cli/cmd/cluster/list_test.go
  internal/controller/builder/builder.go
  internal/controller/rsm/suite_test.go
  internal/controller/rsm/transformer_member_reconfiguration_test.go
  internal/controller/rsm/transformer_object_generation.go
  internal/controller/rsm/transformer_status.go
  internal/controller/rsm/transformer_status_test.go
  internal/controller/rsm/types.go
  internal/controller/rsm/utils.go
  internal/controller/rsm/utils_test.go
  internal/testutil/k8s/rsm_util.go
  test/integration/mysql_reconfigure_test.go
Labels: area/cluster-controller, approved, size/XXL

#5116 chore: fix helm package error
  deploy/foxlake/Chart.yaml
Labels: enhancement, approved, size/XS

#5097 feat: add support for OpenLDAP addon
  deploy/openldap-cluster/.helmignore
  deploy/openldap-cluster/Chart.yaml
  deploy/openldap-cluster/templates/_helpers.tpl
  deploy/openldap-cluster/templates/cluster.yaml
  deploy/openldap-cluster/templates/serviceaccount.yaml
  deploy/openldap-cluster/templates/tests/test-connection.yaml
  deploy/openldap-cluster/values.yaml
  deploy/openldap/.helmignore
  deploy/openldap/Chart.yaml
  deploy/openldap/templates/NOTES.txt
  deploy/openldap/templates/_helpers.tpl
  deploy/openldap/templates/clusterVersion.yaml
  deploy/openldap/templates/clusterdefinition.yaml
  deploy/openldap/templates/tests/test-connection.yaml
  deploy/openldap/values.yaml
Labels: area/user-interaction, feature, size/L

#5056 fix: kb upgrade check case insensitive
  internal/cli/cmd/kubeblocks/upgrade.go
  internal/cli/util/prompt/prompt.go
Labels: enhancement, size/XS

#5118 docs: update vscale docs
  docs/user_docs/kubeblocks-for-kafka/cluster-management/scale.md
  docs/user_docs/kubeblocks-for-kafka/configuration/_category_.yml
  docs/user_docs/kubeblocks-for-kafka/configuration/configuration.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/scale-for-apecloud-mongodb.md
  docs/user_docs/kubeblocks-for-mysql/cluster-management/scale-for-apecloud-mysql.md
  docs/user_docs/kubeblocks-for-mysql/configuration/configuration.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/scale-for-a-postgresql-cluster.md
  docs/user_docs/kubeblocks-for-postgresql/configuration/configuration.md
  docs/user_docs/kubeblocks-for-pulsar/cluster-management/scale-for-pulsar.md
  docs/user_docs/kubeblocks-for-redis/cluster-management/scale-for-a-redis-cluster.md
  docs/user_docs/kubeblocks-for-redis/configuration/configuration.md
Labels: documentation, approved, size/L

#5125 fix: recover monitor annotations
  controllers/apps/components/base_stateful.go
  controllers/apps/components/base_stateful_hscale.go
  controllers/apps/components/consensus_workload.go
  controllers/apps/components/replication_workload.go
  controllers/apps/components/rsm_workload.go
  controllers/apps/components/stateless_workload.go
  controllers/apps/components/workload_builder.go
  controllers/apps/transformer_cluster_credential.go
  controllers/apps/transformer_rbac.go
  controllers/apps/transformer_rbac_test.go
  controllers/dataprotection/backup_controller.go
  internal/cli/cmd/builder/template/component_wrapper.go
  internal/controller/builder/builder_base.go
  internal/controller/builder/suite_test.go
  internal/controller/factory/builder.go
  internal/controller/factory/builder_test.go
  internal/controller/factory/cue/backup_job_template.cue
  internal/controller/factory/cue/backup_manifests_template.cue
  internal/controller/factory/cue/config_manager_sidecar.cue
  internal/controller/factory/cue/config_template.cue
  internal/controller/factory/cue/conn_credential_template.cue
  internal/controller/factory/cue/deployment_template.cue
  internal/controller/factory/cue/env_config_template.cue
  internal/controller/factory/cue/headless_service_template.cue
  internal/controller/factory/cue/pdb_template.cue
  internal/controller/factory/cue/pvc_template.cue
  internal/controller/factory/cue/rbac_template.cue
  internal/controller/factory/cue/restore_job_template.cue
  internal/controller/factory/cue/service_template.cue
  internal/controller/factory/cue/statefulset_template.cue
  internal/controller/factory/cue/volumesnapshotclass.cue
  internal/controller/factory/suite_test.go
  internal/controller/plan/builtin_functions.go
  internal/controller/plan/prepare.go
  internal/controller/plan/prepare_test.go
  internal/controller/plan/restore.go
  internal/controller/plan/template_wrapper.go
  internal/controller/plan/tls_utils.go
  internal/controller/plan/tls_utils_test.go
  internal/controller/plan/tool_image_builder.go
  internal/controller/plan/tool_image_builder_test.go
  internal/controller/rsm/transformer_object_generation.go
  internal/controller/rsm/types.go
  internal/controller/rsm/utils.go
  internal/controller/rsm/utils_test.go
Labels: area/cluster-controller, enhancement, size/XL

#5124 feat: Support Oceanbase Cluster
  deploy/oceanbase-cluster/.helmignore
  deploy/oceanbase-cluster/Chart.yaml
  deploy/oceanbase-cluster/templates/NOTES.txt
  deploy/oceanbase-cluster/templates/_helpers.tpl
  deploy/oceanbase-cluster/templates/cluster.yaml
  deploy/oceanbase-cluster/templates/role.yaml
  deploy/oceanbase-cluster/templates/rolebinding.yaml
  deploy/oceanbase-cluster/templates/serviceaccount.yaml
  deploy/oceanbase-cluster/values.yaml
  deploy/oceanbase/.helmignore
  deploy/oceanbase/Chart.yaml
  deploy/oceanbase/templates/NOTES.txt
  deploy/oceanbase/templates/_helpers.tpl
  deploy/oceanbase/templates/clusterdefinition.yaml
  deploy/oceanbase/templates/clusterversion.yaml
  deploy/oceanbase/values.yaml
  internal/cli/create/template/cluster_template.cue
  lorry/engine/oceanbase.go
Labels: area/user-interaction, feature, size/L

#5128 chore: change jupyterhub addonChartLocationURL
  .github/utils/release_gitlab.sh
  deploy/helm/templates/addons/jupyterhub-addon.yaml
Labels: approved, size/S

#5132 fix: staticcheck error
  lorry/engine/oceanbase.go
Labels: enhancement, size/S

#5127 fix: optimize record role change event time accuracy
  controllers/apps/components/consensus_set_utils.go
  controllers/apps/components/replication_set_utils.go
  controllers/k8score/event_controller_test.go
  controllers/k8score/role_change_event_handler.go
  internal/controller/builder/builder_event.go
Labels: enhancement, approved, size/M

#5133 chore: e2e test support skip specified test case
  Makefile
  deploy/mongodb-cluster/values.yaml
  test/e2e/Makefile
  test/e2e/e2e_suite_test.go
  test/e2e/testdata/smoketest/mongodb/00_mongodbcluster.yaml
  test/e2e/testdata/smoketest/mongodb/08_backup_snapshot_restore.yaml
  test/e2e/testdata/smoketest/postgresql/11_backup_snapshot_restore.yaml
  test/e2e/testdata/smoketest/redis/11_backup_snapshot_restore.yaml
  test/e2e/testdata/smoketest/smoketestrun.go
  test/e2e/testdata/smoketest/wesql/14_backup_snapshot_restore.yaml
  test/e2e/types.go
Labels: test, ci, size/M

#5147 fix: fatal errors after dapr removed
  cmd/lorry/main.go
  go.mod
  go.sum
  lorry/binding/utils.go
  lorry/highavailability/ha.go
Labels: enhancement, size/S, lorry

#5157 chore: support performance test
  .github/workflows/e2e-performance.yml
Labels: test, approved, size/M

#5117 feat: kbcli support backup subcommnad
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli.md
  docs/user_docs/cli/kbcli_backup.md
  docs/user_docs/cli/kbcli_backup_create.md
  docs/user_docs/cli/kbcli_backup_delete.md
  docs/user_docs/cli/kbcli_backup_describe.md
  docs/user_docs/cli/kbcli_backup_list.md
  docs/user_docs/cli/kbcli_cluster_register.md
  internal/cli/cmd/backup/backup.go
  internal/cli/cmd/backup/create.go
  internal/cli/cmd/backup/delete.go
  internal/cli/cmd/backup/describe.go
  internal/cli/cmd/backup/list.go
  internal/cli/cmd/bench/bench.go
  internal/cli/cmd/cli.go
  internal/cli/cmd/cluster/dataprotection.go
  internal/cli/cmd/cluster/dataprotection_test.go
  internal/cli/util/completion.go
Labels: area/user-interaction, feature, size/XL

#5142 feat: support qdrant web-ui and qdrant 1.5.0
  deploy/qdrant-cluster/Chart.yaml
  deploy/qdrant-cluster/templates/_helpers.tpl
  deploy/qdrant-cluster/templates/cluster.yaml
  deploy/qdrant-cluster/templates/rbac.yaml
  deploy/qdrant-cluster/templates/validate.yaml
  deploy/qdrant-cluster/values.schema.json
  deploy/qdrant-cluster/values.yaml
  deploy/qdrant/Chart.yaml
  deploy/qdrant/templates/_helpers.tpl
  deploy/qdrant/templates/clusterdefinition.yaml
  deploy/qdrant/templates/clusterversion.yaml
  deploy/qdrant/values.yaml
Labels: area/user-interaction, feature, size/L

#5156 fix: unsupported engine type oceanbase
  lorry/engine/engine.go
  lorry/engine/oceanbase.go
Labels: enhancement, approved, size/S

#5153 fix: nil pointer reference error for configuration reconcile (#5152)
  controllers/apps/configuration/reconcile_task.go
  internal/controller/component/component.go
  internal/controller/component/component_test.go
  internal/controller/configuration/pipeline.go
  internal/controller/configuration/pipeline_test.go
Labels: enhancement, ci, size/L

#5126 feat: pg get checkpoint end
  lorry/component/postgres/local_command.go
  lorry/component/postgres/officalpostgres/manager.go
  lorry/component/postgres/types.go
  lorry/component/postgres/types_test.go
Labels: feature, approved, size/M

#5151 fix: code security
  controllers/apps/components/base_stateful.go
  lorry/component/kafka/thirdparty/retry.go
Labels: enhancement, size/XS

#5167 chore: support aliyun new registry
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/release-delete.yml
  .github/workflows/release-helm-chart.yml
  .github/workflows/release-image.yml
Labels: approved, size/M

#5131 chore: update elasticsearch to version 8.8.2
  deploy/elasticsearch/Chart.yaml
  deploy/elasticsearch/templates/clusterdefinition.yaml
  deploy/elasticsearch/values.yaml
Labels: size/XS

#5165 fix: fix cluster register the same command, absolute path error and pre-check
  go.mod
  internal/cli/cluster/builtin_charts.go
  internal/cli/cluster/cluster_chart.go
  internal/cli/cluster/external_charts.go
  internal/cli/cluster/register.go
  internal/cli/cluster/register_test.go
  internal/cli/cmd/cluster/register.go
  internal/cli/cmd/cluster/register_test.go
Labels: area/user-interaction, enhancement, size/L

#5155 feat: kbcli cluster create for multiple volumeClaimTemplates
  docs/user_docs/cli/kbcli_cluster_create.md
  internal/cli/cmd/cluster/create.go
  internal/cli/cmd/cluster/create_test.go
Labels: area/user-interaction, feature, size/L

#5172 fix: modify pg lag check
  lorry/component/postgres/officalpostgres/manager.go
  lorry/component/postgres/officalpostgres/manager_test.go
Labels: enhancement, size/L

#5059 fix: the stoptime can be nil
  apis/dataprotection/v1alpha1/backup_types.go
Labels: bug, enhancement, size/S

#5179 fix: oceanbase cluster restart
  deploy/oceanbase/templates/clusterdefinition.yaml
Labels: bug, enhancement, approved, size/S

#5183 chore: distinguish jihulab url
  .github/workflows/e2e-kbcli.yml
  .github/workflows/release-delete.yml
  .github/workflows/release-helm-chart.yml
  deploy/mongodb-sharding-cluster/Chart.yaml
  deploy/vllm/Chart.yaml
Labels: approved, size/S

#5195 fix: update oracle mysql cv
  deploy/oracle-mysql/templates/clusterversion.yaml
Labels: enhancement, size/XS

#5200 fix: hscale without lorry
  controllers/apps/components/base_stateful.go
  lorry/client/client.go
Labels: enhancement, size/XS

#5205 chore: change addon nvidia-gpu-exporter addonChartLocationBase
  deploy/helm/templates/addons/nvidia-gpu-exporter-addon.yaml
Labels: approved, size/XS

#5177 feat: support PVC based backup repo
  apis/storage/v1alpha1/storageprovider_types.go
  config/crd/bases/storage.kubeblocks.io_storageproviders.yaml
  controllers/dataprotection/backuprepo_controller.go
  controllers/dataprotection/backuprepo_controller_test.go
  controllers/dataprotection/type.go
  deploy/helm/crds/storage.kubeblocks.io_storageproviders.yaml
  deploy/helm/templates/storageprovider/pvc.yaml
Labels: area/user-interaction, feature, size/L

#5192 chore: add e2e test cases
  Makefile
  test/e2e/testdata/smoketest/foxlake/06_hscale_up.yaml
  test/e2e/testdata/smoketest/oceanbase/00_oceanbasecluster.yaml
  test/e2e/testdata/smoketest/oceanbase/01_vscale.yaml
  test/e2e/testdata/smoketest/oceanbase/02_stop.yaml
  test/e2e/testdata/smoketest/oceanbase/03_start.yaml
  test/e2e/testdata/smoketest/oceanbase/04_vexpand.yaml
  test/e2e/testdata/smoketest/oceanbase/05_restart.yaml
  test/e2e/testdata/smoketest/oceanbase/06_hscale_up.yaml
  test/e2e/testdata/smoketest/oceanbase/07_hscale_down.yaml
  test/e2e/testdata/smoketest/official-postgresql/00_official_pgcluster.yaml
  test/e2e/testdata/smoketest/official-postgresql/01_vscale.yaml
  test/e2e/testdata/smoketest/official-postgresql/02_stop.yaml
  test/e2e/testdata/smoketest/official-postgresql/03_start.yaml
  test/e2e/testdata/smoketest/official-postgresql/04_vexpand.yaml
  test/e2e/testdata/smoketest/official-postgresql/05_restart.yaml
  test/e2e/testdata/smoketest/official-postgresql/06_hscale_up.yaml
  test/e2e/testdata/smoketest/official-postgresql/07_hscale_down.yaml
  test/e2e/testdata/smoketest/openldap/00_openldapcluster.yaml
  test/e2e/testdata/smoketest/openldap/01_vscale.yaml
  test/e2e/testdata/smoketest/openldap/02_stop.yaml
  test/e2e/testdata/smoketest/openldap/03_start.yaml
  test/e2e/testdata/smoketest/openldap/04_restart.yaml
  test/e2e/testdata/smoketest/openldap/05_hscale_up.yaml
  test/e2e/testdata/smoketest/openldap/06_hscale_down.yaml
  test/e2e/testdata/smoketest/orioledb/00_orioledbcluster.yaml
  test/e2e/testdata/smoketest/orioledb/01_vscale.yaml
  test/e2e/testdata/smoketest/orioledb/02_stop.yaml
  test/e2e/testdata/smoketest/orioledb/03_start.yaml
  test/e2e/testdata/smoketest/orioledb/04_vexpand.yaml
  test/e2e/testdata/smoketest/orioledb/05_restart.yaml
  test/e2e/testdata/smoketest/orioledb/06_hscale_up.yaml
  test/e2e/testdata/smoketest/orioledb/07_hscale_down.yaml
Labels: test, approved, size/XL

#5219 chore: remove useless component types
  controllers/apps/components/base.go
  controllers/apps/components/component.go
  controllers/apps/components/component_workload_builder.go
  controllers/apps/components/rsm_component.go
  controllers/apps/components/rsm_workload.go
  controllers/apps/components/types.go
Labels: size/XXL

#5218 fix: expose error info correctly when preflight
  internal/preflight/analyzer/kb_storage_class.go
  internal/preflight/analyzer/kb_taint.go
  internal/preflight/collect.go
Labels: enhancement, size/S

#5212 fix: fix kbcli login
  internal/cli/cmd/auth/authorize/authenticator/callback_html/complete.html
  internal/cli/cmd/auth/authorize/authenticator/callback_html/error.html
  internal/cli/cmd/auth/authorize/authenticator/callback_listener.go
  internal/cli/cmd/auth/authorize/cached_provider.go
  internal/cli/cmd/auth/authorize/token_provider.go
  internal/cli/cmd/cluster/register.go
Labels: area/cli, enhancement, size/S

#5161 docs: add new addon docs and update config docs
  docs/developer_docs/integration/environment-variables-and-placeholders.md
  docs/developer_docs/integration/how-to-add-an-add-on.md
  docs/developer_docs/integration/monitoring.md
  docs/developer_docs/integration/multi-component.md
  docs/developer_docs/integration/parameter-configuration.md
  docs/developer_docs/integration/parameter-template.md
  docs/img/addon-confirm-config-changes.png
  docs/img/addon-interactive-config-editor.png
  docs/img/addon-monitoring-signin.png
  docs/img/nebula-aichitecture.png
  docs/img/nebula-inter-component-ref.png
  docs/user_docs/backup-and-restore/backup/backup-repo.md
  docs/user_docs/kubeblocks-for-kafka/configuration/configuration.md
  docs/user_docs/kubeblocks-for-mongodb/configuration/configuration.md
  docs/user_docs/kubeblocks-for-mongodb/migration/feature-and-limit-list-mongodb.md
  docs/user_docs/kubeblocks-for-mysql/configuration/configuration.md
  docs/user_docs/kubeblocks-for-postgresql/configuration/configuration.md
  docs/user_docs/kubeblocks-for-pulsar/configuration/configuration.md
  docs/user_docs/kubeblocks-for-redis/configuration/configuration.md
  docs/user_docs/kubeblocks-for-vector-database/manage-vector-databases.md
Labels: documentation, approved, size/XXL

#4996 feat: support huawei cloud and set provide
  apis/extensions/v1alpha1/addon_types.go
  apis/extensions/v1alpha1/type.go
  config/crd/bases/extensions.kubeblocks.io_addons.yaml
  deploy/helm/crds/extensions.kubeblocks.io_addons.yaml
  deploy/helm/templates/_helpers.tpl
  deploy/helm/templates/addons/snapshot-controller-addon.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/templates/storageclass.yaml
  deploy/helm/values.yaml
  internal/constant/const.go
Labels: area/user-interaction, feature, size/L

#5225 fix: kbcli report with sc and pvc
  controllers/apps/configuration/configuration_controller.go
  internal/cli/cmd/report/report.go
  internal/controller/plan/prepare.go
Labels: enhancement, approved, size/S

#5201 fix: failed to get pods (#5141)
  controllers/apps/configuration/parallel_upgrade_policy.go
  controllers/apps/configuration/parallel_upgrade_policy_test.go
  controllers/apps/configuration/policy_util.go
  controllers/apps/configuration/rolling_upgrade_policy.go
  controllers/apps/configuration/simple_policy.go
  controllers/apps/configuration/sync_upgrade_policy.go
  controllers/apps/configuration/types.go
  internal/common/stateful_set_utils.go
Labels: enhancement, approved, size/L

#5215 chore: remove depends cv/cd (#5211)
  apis/apps/v1alpha1/configuration_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  controllers/apps/configuration/configuration_controller.go
  controllers/apps/configuration/configuration_test.go
  controllers/apps/configuration/reconcile_task.go
  controllers/apps/operations/reconfigure_test.go
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
  internal/controller/builder/builder_configuration.go
  internal/controller/builder/builder_configuration_test.go
  internal/controller/configuration/operator_test.go
  internal/controller/configuration/pipeline.go
  internal/controller/configuration/pipeline_test.go
Labels: approved, size/L

#5204 chore: preflight support aws us region
  internal/cli/cmd/kubeblocks/data/eks_hostpreflight.yaml
Labels: approved, size/XS

#5231 chore: Add test kbcli cases
  .github/workflows/e2e-kbcli.yml
Labels: test, size/XS

#5230 fix: add special handling for isPodReady
  lorry/highavailability/ha.go
Labels: bug, ci, size/XS

#5235 fix: recover missing lorry env
  internal/constant/const.go
  internal/controller/component/probe_utils.go
  internal/controller/component/probe_utils_test.go
  internal/controller/rsm/transformer_object_generation.go
  internal/controller/rsm/types.go
  lorry/binding/base.go
Labels: area/cluster-controller, enhancement, size/L

#5236 fix: fix openldap VolumeExpansion ops failed
  deploy/openldap-cluster/templates/cluster.yaml
  deploy/openldap-cluster/values.yaml
  deploy/openldap/templates/clusterdefinition.yaml
Labels: enhancement, approved, size/XS

#5217 feat: tplengine support customized syntax (#5210)
  internal/gotemplate/functional_test.go
  internal/gotemplate/tpl_engine.go
  internal/gotemplate/tpl_engine_test.go
Labels: area/user-interaction, feature, approved, size/L

#4967 fix: check VolumeSnapshot for each cluster
  controllers/apps/cluster_controller_test.go
  controllers/apps/components/hscale_volume_populator.go
  controllers/apps/opsrequest_controller_test.go
  internal/testutil/k8s/storage_util.go
Labels: enhancement, approved, size/L

#5245 feat: Integrate PolarDB-X into KubeBlocks.
  deploy/polardbx-cluster/.helmignore
  deploy/polardbx-cluster/Chart.yaml
  deploy/polardbx-cluster/templates/NOTES.txt
  deploy/polardbx-cluster/templates/_helpers.tpl
  deploy/polardbx-cluster/templates/cluster.yaml
  deploy/polardbx-cluster/values.yaml
  deploy/polardbx/.helmignore
  deploy/polardbx/Chart.yaml
  deploy/polardbx/dashboards/polardbx-overview.json
  deploy/polardbx/scripts/gms-init.sql
  deploy/polardbx/scripts/gms-metadata.tpl
  deploy/polardbx/scripts/metadb-setup.tpl
  deploy/polardbx/scripts/xstore-post-start.tpl
  deploy/polardbx/scripts/xstore-setup.tpl
  deploy/polardbx/templates/NOTES.txt
  deploy/polardbx/templates/_helpers.tpl
  deploy/polardbx/templates/clusterDefintion.yaml
  deploy/polardbx/templates/clusterVersion.yaml
  deploy/polardbx/templates/configmap-dashboards.yaml
  deploy/polardbx/templates/scriptstemplate.yaml
  deploy/polardbx/values.yaml
Labels: area/user-interaction, feature, size/XXL

#5226 docs: update pg and config docs
  docs/user_docs/kubeblocks-for-kafka/configuration/configuration.md
  docs/user_docs/kubeblocks-for-mongodb/configuration/configuration.md
  docs/user_docs/kubeblocks-for-mysql/configuration/configuration.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/restart-a-postgresql-cluster.md
  docs/user_docs/kubeblocks-for-postgresql/configuration/configuration.md
  docs/user_docs/kubeblocks-for-pulsar/cluster-management/create-pulsar-cluster-on-kubeblocks.md
  docs/user_docs/kubeblocks-for-pulsar/configuration/configuration.md
  docs/user_docs/kubeblocks-for-redis/configuration/configuration.md
Labels: documentation, size/XL

#5239 fix: kbcli kubeblocks upgrade malformed version
  internal/cli/cmd/kubeblocks/upgrade.go
  internal/cli/cmd/kubeblocks/upgrade_test.go
Labels: enhancement, size/S

#5248 fix: [FAIL] Cluster Controller test cluster Failed/Abnormal phase
  controllers/apps/cluster_controller_test.go
Labels: area/cluster-controller, test, enhancement, size/XS

#5252 chore: fix typo in polardbx chart
  deploy/polardbx/Chart.yaml
Labels: enhancement, size/XS

#5255 docs: fix typos in mysql intro
  docs/user_docs/kubeblocks-for-mysql/apecloud-mysql-intro/apecloud-mysql-intro.md
Labels: documentation, enhancement, size/XS

#5257 fix: datascript supports specifing pods using selectors
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/datascript.go
  controllers/apps/operations/datascript_test.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docker/Dockerfile-datascript
  lorry/engine/engine_test.go
  lorry/engine/redis.go
Labels: enhancement, ci, size/L

#5260 fix: probe crash when create cm failed
  cmd/probe/internal/highavailability/ha.go
Labels: enhancement, size/XS

#5261 fix: failed to configuration-controller ut (#5249)
  controllers/apps/configuration/configuration_controller.go
  controllers/apps/configuration/configuration_controller_test.go
  controllers/apps/configuration/reconcile_task.go
  controllers/apps/operations/reconfigure_test.go
  internal/controller/configuration/pipeline.go
  internal/controller/configuration/template_wrapper.go
Labels: enhancement, approved, size/M

#5259 fix: Upgrade consensusSpec to rsmSpec for PolarDB-X.
  deploy/polardbx/templates/clusterDefintion.yaml
Labels: enhancement, size/M

#5264 chore: split jihulab chart url to addons and applications
  .github/workflows/release-helm-chart.yml
Labels: approved, size/XS

#5265 chore: make lorry role probe timeout configurable
  deploy/mongodb/values.yaml
  internal/controller/rsm/transformer_object_generation.go
  internal/controller/rsm/types.go
  lorry/binding/base.go
  lorry/binding/types.go
Labels: size/S, rsm, lorry

#5266 chore: workload type validation rules in CD
  apis/apps/v1alpha1/clusterdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
Labels: area/cluster-controller, size/S

#5275 docs: update slack link
  README.md
Labels: documentation, size/XS

#5277 chore: update helm chart index
  .github/workflows/release-delete.yml
Labels: approved, size/XS

#5268 chore: tidy imports to fix lint errors
  controllers/apps/components/types.go
  controllers/apps/configuration/revision.go
  controllers/apps/configuration/revision_test.go
  controllers/apps/operations/pipeline.go
  controllers/apps/transformer_cluster_credential.go
  controllers/dataprotection/backup_controller.go
  internal/controller/configuration/configuration_test.go
  internal/controller/configuration/tool_image_builder.go
Labels: enhancement, size/S

#5263 feat: support direct access to the backup repo
  apis/dataprotection/v1alpha1/backuprepo_types.go
  apis/storage/v1alpha1/storageprovider_types.go
  config/crd/bases/dataprotection.kubeblocks.io_backuprepos.yaml
  config/crd/bases/storage.kubeblocks.io_storageproviders.yaml
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backuprepo_controller.go
  controllers/dataprotection/backuprepo_controller_test.go
  controllers/dataprotection/type.go
  deploy/helm/crds/dataprotection.kubeblocks.io_backuprepos.yaml
  deploy/helm/crds/storage.kubeblocks.io_storageproviders.yaml
  deploy/helm/templates/storageprovider/cos.yaml
  deploy/helm/templates/storageprovider/gcs.yaml
  deploy/helm/templates/storageprovider/minio.yaml
  deploy/helm/templates/storageprovider/obs.yaml
  deploy/helm/templates/storageprovider/oss.yaml
  deploy/helm/templates/storageprovider/s3.yaml
  go.mod
Labels: area/user-interaction, feature, size/XL

#5282 chore: delete controller-gen cache
  .github/localflows/cicd-local.yml
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
Labels: approved, size/S

#5284 fix: lorryclient is nil check
  controllers/apps/components/component.go
  internal/controllerutil/util.go
Labels: enhancement, size/S

#5227 fix: the error message retunred
  internal/cli/cmd/bench/bench.go
  internal/cli/cmd/bench/pgbench.go
  internal/cli/cmd/bench/sysbench.go
  internal/cli/cmd/bench/ycsb.go
Labels: bug, enhancement, size/S

#5290 chore: auto set issue and pr milestone
  .github/workflows/e2e-performance.yml
  .github/workflows/milestone-set.yaml
  .github/workflows/pull-request-label-size.yaml
Labels: approved, size/M

#5280 fix: SyncEnvConfigmap panic for configuration controller (#5243)
  controllers/apps/configuration/configuration_controller.go
  internal/controller/configuration/pipeline.go
Labels: enhancement, size/XS

#5281 fix: component.BuildComponent painc when configuration.spec.ComponentName donot exist in the cluster.spec.componentSpecs
  controllers/apps/configuration/configuration_controller.go
  controllers/apps/configuration/configuration_controller_test.go
Labels: enhancement, size/M

#5293 chore: workaround of goland code inspector bug which fails to infer generic pointer type
  controllers/apps/components/utils.go
  controllers/apps/configuration/config_related_helper.go
  internal/cli/cmd/builder/template/k8s_resource.go
  internal/generics/type.go
  internal/testutil/apps/common_util.go
Labels: bug, size/L

#5289 chore: bump go version from 1.20.5 to 1.21
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/codeql.yml
  .github/workflows/release-helm-chart.yml
  .github/workflows/release-image.yml
  .github/workflows/release-publish.yml
  .goreleaser.yaml
  docker/Dockerfile
  docker/Dockerfile-dataprotection
  docker/Dockerfile-dev
  docker/Dockerfile-probe
  docker/Dockerfile-tools
Labels: dependencies, size/M

#5301 chore: Revert 'chore(deps): bump github.com/cyphar/filepath-securejoin from 0.2.3 to 0.2.4'
  go.mod
  go.sum
Labels: dependencies, size/L

#5246 fix: lorry leave member
  lorry/binding/base.go
  lorry/client/client.go
  lorry/component/dbmanager.go
Labels: enhancement, approved, size/M

#5309 chore: COPY go. mod instead of bind
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/release-image.yml
  docker/Dockerfile
  docker/Dockerfile-dataprotection
  docker/Dockerfile-tools
Labels: size/S

#5305 feat: cli plugin adapt the change of block index repository
  internal/cli/cmd/plugin/types.go
Labels: area/user-interaction, feature, size/XS
