Repository apecloud/kubeblocks, pull requests merged in 2023-08, with the labels that each got.

#4439 chore: setup rbac for volume protection
  config/rbac/role.yaml
  controllers/apps/cluster_controller.go
  controllers/apps/transformer_cluster_deletion.go
  controllers/apps/transformer_ownership.go
  controllers/apps/transformer_rbac.go
  controllers/apps/transformer_rbac_test.go
  deploy/helm/config/rbac/role.yaml
  deploy/helm/templates/rbac/cluster_pod_required_role.yaml
  deploy/helm/templates/rbac/rbac_manager_role.yaml
  deploy/helm/values.yaml
  internal/cli/cmd/cluster/create.go
  internal/cli/cmd/cluster/delete.go
  internal/controller/builder/builder.go
  internal/controller/builder/builder_test.go
  internal/controller/builder/cue/rbac_template.cue
  internal/controller/component/probe_utils.go
  internal/controller/component/probe_utils_test.go
Labels: approved, size/L

#4555 feat: add the --show-password flag to control the display of passwords.
  docs/user_docs/cli/kbcli_cluster_connect.md
  internal/cli/cmd/cluster/connect.go
  internal/cli/cmd/cluster/connect_test.go
Labels: feature, size/M

#4475 fix: make mysql-scale cluster 'enabled-all-logs' work properly
  deploy/apecloud-mysql-cluster/templates/_helpers.tpl
  deploy/apecloud-mysql/config/mysql-scale-vtconsensus-config-constraint.cue
  deploy/apecloud-mysql/config/mysql-scale-vtconsensus-config.tpl
  deploy/apecloud-mysql/config/mysql-scale-vtgate-config-constraint.cue
  deploy/apecloud-mysql/config/mysql-scale-vtgate-config.tpl
  deploy/apecloud-mysql/config/mysql-scale-vttablet-config-constraint.cue
  deploy/apecloud-mysql/config/mysql-scale-vttablet-config.tpl
  deploy/apecloud-mysql/templates/clusterdefinition.yaml
  deploy/apecloud-mysql/templates/scripts.yaml
  deploy/apecloud-mysql/values.yaml
  internal/cli/cmd/cluster/update.go
Labels: enhancement, size/L

#4559 chore: modify handleRoleChange DAG update to patch
  controllers/apps/components/replication_set.go
  controllers/apps/components/replication_set_test.go
Labels: size/XS

#4560 chore: rename RetryWindowMinutes to StartingDeadlineMinutes
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  controllers/apps/cluster_controller_test.go
  controllers/apps/transformer_backup_policy_tpl.go
  controllers/dataprotection/backuppolicy_controller.go
  controllers/dataprotection/backuppolicy_controller_test.go
  deploy/apecloud-mysql/templates/backuppolicytemplate.yaml
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/mongodb/templates/backuppolicytemplate.yaml
  deploy/postgresql/templates/backuppolicytemplate.yaml
  deploy/redis/templates/backuppolicytemplate.yaml
  docs/user_docs/api-reference/add-on.md
  docs/user_docs/api-reference/backup.md
  docs/user_docs/api-reference/cluster.md
  internal/testutil/apps/backuppolicy_factory.go
Labels: size/XL

#4561 fix: modify config pool
  cmd/probe/internal/component/postgres/config.go
Labels: bug, enhancement, approved, size/XS

#4541 chore: refine reconfigure reconcile code
  controllers/apps/configuration/config_reconcile_wrapper.go
  controllers/apps/configuration/config_related_helper.go
  controllers/apps/configuration/config_util.go
  controllers/apps/configuration/reconfigurerequest_controller.go
Labels: ci, approved, size/L

#4556 fix: update enable-all-logs may cause multiple components to update wrong parameters (#4553)
  internal/cli/cmd/cluster/update.go
Labels: enhancement, approved, size/M

#4567 fix: redis account not save to file as expected
  deploy/redis/templates/clusterdefinition.yaml
  deploy/redis/templates/scripts.yaml
Labels: enhancement, approved, size/S

#4570 chore: support redis rolecheck delay
  cmd/probe/internal/binding/redis/redis.go
  cmd/probe/internal/binding/redis/redis_test.go
Labels: size/S

#4569 chore: modify field statements.update attributed
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/clusterdefinition_webhook.go
  apis/apps/v1alpha1/clusterdefinition_webhook_test.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  controllers/apps/systemaccount_util.go
  deploy/apecloud-mysql/config/mysql-scale-vtgate-config-constraint.cue
  deploy/apecloud-mysql/config/mysql-scale-vttablet-config-constraint.cue
  deploy/apecloud-mysql/config/mysql8-config-constraint.cue
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  docs/user_docs/api-reference/cluster.md
  internal/controller/builder/cue/rbac_template.cue
Labels: approved, size/L

#4568 fix: shutdown redis-server when create replication relationship failed and update postgresql start scripts
  deploy/postgresql/templates/scripts.yaml
  deploy/redis/scripts/redis7-start.sh.tpl
  deploy/redis/templates/clusterdefinition.yaml
  deploy/redis/templates/scripts.yaml
Labels: enhancement, approved, size/M

#4534 feat: mongodb diskfull lock
  cmd/probe/internal/binding/base.go
  cmd/probe/internal/binding/custom/custom.go
  cmd/probe/internal/binding/etcd/etcd.go
  cmd/probe/internal/binding/kafka/kafka.go
  cmd/probe/internal/binding/kafka/kafka_test.go
  cmd/probe/internal/binding/mongodb/mongodb.go
  cmd/probe/internal/binding/mysql/mysql.go
  cmd/probe/internal/binding/mysql/mysql_test.go
  cmd/probe/internal/binding/operation_volume_protection.go
  cmd/probe/internal/binding/operation_volume_protection_test.go
  cmd/probe/internal/binding/postgres/postgres.go
  cmd/probe/internal/binding/postgres/postgres_test.go
  cmd/probe/internal/binding/redis/redis.go
  cmd/probe/internal/binding/redis/redis_test.go
  cmd/probe/internal/binding/utils.go
  cmd/probe/internal/component/dbmanager.go
  cmd/probe/internal/component/mongodb/manager.go
  cmd/probe/internal/component/mongodb/types.go
  cmd/probe/internal/component/mysql/manager.go
  cmd/probe/internal/component/postgres/manager.go
  cmd/probe/internal/highavailability/ha.go
  internal/sqlchannel/util/types.go
Labels: feature, size/XL

#4575 feat: support kbcli auto-publish for chocolatey
  .github/workflows/release-sync.yml
Labels: area/user-interaction, feature, size/S

#4539 feat: kbcli `compare` command supports more clear KB upgrade version information.
  docs/user_docs/cli/kbcli_kubeblocks_compare.md
  internal/cli/cmd/kubeblocks/compare.go
  internal/cli/cmd/kubeblocks/compare_test.go
  internal/cli/util/helm/diff.go
  internal/cli/util/helm/diff_test.go
Labels: feature, size/XL

#4571 fix: delete cluster role binding at cluster deletion
  controllers/apps/cluster_controller_test.go
  controllers/apps/transform_utils.go
  controllers/apps/transformer_cluster_deletion.go
Labels: enhancement, size/L

#4582 fix: volume expand is not compatible with 0.5
  apis/apps/v1alpha1/opsrequest_webhook.go
  internal/constant/const.go
Labels: enhancement, size/M

#4558 feat: add tpcc for kbcli bench
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli_bench.md
  docs/user_docs/cli/kbcli_bench_tpcc.md
  go.mod
  go.sum
  internal/cli/cmd/bench/bench.go
  internal/cli/cmd/bench/tpcc.go
  internal/cli/types/types.go
Labels: area/user-interaction, feature, size/L

#4594 chore: revert unnecessary API constraints
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  apis/dataprotection/v1alpha1/backup_types.go
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  config/crd/bases/dataprotection.kubeblocks.io_restorejobs.yaml
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_restorejobs.yaml
Labels: size/M

#4596 chore: improve mysql addon chart location url
  deploy/helm/templates/addons/mysql-addon.yaml
Labels: size/XS

#4597 chore: revert the max length limitation added for Addon and ClusterVersion
  apis/apps/v1alpha1/clusterversion_types.go
  apis/extensions/v1alpha1/addon_types.go
  config/crd/bases/apps.kubeblocks.io_clusterversions.yaml
  config/crd/bases/extensions.kubeblocks.io_addons.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterversions.yaml
  deploy/helm/crds/extensions.kubeblocks.io_addons.yaml
Labels: size/XS

#4592 feat(deploy): add ClusterDefinition and Cluster example for RisingWave
  deploy/risingwave-cluster/.helmignore
  deploy/risingwave-cluster/Chart.yaml
  deploy/risingwave-cluster/templates/NOTES.txt
  deploy/risingwave-cluster/templates/_helpers.tpl
  deploy/risingwave-cluster/templates/cluster.yaml
  deploy/risingwave-cluster/values.yaml
  deploy/risingwave/.helmignore
  deploy/risingwave/Chart.yaml
  deploy/risingwave/config/risingwave-compute-envs.tpl
  deploy/risingwave/config/risingwave-config.tpl
  deploy/risingwave/config/risingwave-connector-envs.tpl
  deploy/risingwave/templates/NOTES.txt
  deploy/risingwave/templates/_helpers.tpl
  deploy/risingwave/templates/clusterdefinition.yaml
  deploy/risingwave/templates/clusterversion.yaml
  deploy/risingwave/templates/risingwave-compute-envs-configmap.yaml
  deploy/risingwave/templates/risingwave-config-configmap.yaml
  deploy/risingwave/templates/risingwave-connector-envs-configmap.yaml
  deploy/risingwave/values.yaml
Labels: feature, size/XXL

#4602 fix: remove hard coded service account in template
  deploy/apecloud-mysql/templates/clustertemplate.yaml
Labels: enhancement, size/XS

#4600 chore: support smartengine
  deploy/apecloud-mysql/config/mysql8-config-constraint.cue
  deploy/apecloud-mysql/config/mysql8-config-effect-scope.yaml
  deploy/apecloud-mysql/config/mysql8-config.tpl
  deploy/apecloud-mysql/scripts/mysql-reload.tpl
  deploy/apecloud-mysql/values.yaml
Labels: approved, size/S

#4607 chore: rename parameter name prefix xengine_ to smartengine_ for apecloud_mysql
  deploy/apecloud-mysql/config/mysql8-config-constraint.cue
  deploy/apecloud-mysql/config/mysql8-config-effect-scope.yaml
  deploy/apecloud-mysql/config/mysql8-config.tpl
  deploy/apecloud-mysql/scripts/mysql-reload.tpl
  deploy/apecloud-mysql/values.yaml
Labels: enhancement, size/M

#4601 chore: remove image setting from apecloud-mysql cluster definition
  deploy/apecloud-mysql/templates/clusterdefinition.yaml
  deploy/apecloud-mysql/templates/clusterversion.yaml
Labels: size/S

#4619 chore: scale KubeBlocks replicas to 0 before upgrade
  internal/cli/cmd/kubeblocks/upgrade.go
Labels: size/M

#4616 fix: support backup for oracle mysql
  deploy/helm/templates/addons/oracle-mysql-addon.yaml
  deploy/oracle-mysql-cluster/Chart.yaml
  deploy/oracle-mysql-cluster/templates/cluster.yaml
  deploy/oracle-mysql-cluster/templates/rbac.yaml
  deploy/oracle-mysql-cluster/values.yaml
  deploy/oracle-mysql/Chart.yaml
  deploy/oracle-mysql/templates/backuppolicytemplate.yaml
  deploy/oracle-mysql/templates/backuptool.yaml
  deploy/oracle-mysql/templates/clusterdefinition.yaml
  deploy/oracle-mysql/values.yaml
Labels: enhancement, approved, size/M

#4604 fix: kbcli bench return proper message when kubebench is not enabled
  internal/cli/cmd/bench/bench.go
Labels: enhancement, size/S

#4621 fix: pitr restore for multi-component failed
  internal/cli/cmd/cluster/create.go
  internal/cli/cmd/cluster/dataprotection.go
  internal/controller/plan/restore.go
  internal/controller/plan/restore_test.go
  internal/testutil/apps/cluster_factory.go
Labels: enhancement, size/M

#4614 fix: halt recovery failed caused by different unit of resources
  controllers/apps/transform_utils.go
  controllers/apps/transform_utils_test.go
  controllers/apps/transformer_halt_recovering.go
Labels: enhancement, approved, size/M

#4613 fix: remove peer failed when the shard is still in deleting
  deploy/qdrant/scripts/qdrant-pre-stop.sh
  deploy/qdrant/templates/clusterdefinition.yaml
Labels: enhancement, approved, size/S

#4631 fix: opensearch addon enable failed
  deploy/opensearch/templates/NOTES.txt
  deploy/opensearch/templates/clusterversion.yaml
  deploy/opensearch/values.yaml
Labels: enhancement, approved, size/S

#4626 fix: sa creation problem for template
  controllers/apps/transformer_rbac.go
Labels: enhancement, approved, size/S

#4642 chore: update helm charts logo url
  deploy/apecloud-mysql/Chart.yaml
  deploy/helm/Chart.yaml
  deploy/mysql-cluster/Chart.yaml
  deploy/mysql/Chart.yaml
  deploy/oracle-mysql-cluster/Chart.yaml
  deploy/oracle-mysql/Chart.yaml
  deploy/postgresql/Chart.yaml
  deploy/tdengine-cluster/Chart.yaml
Labels: size/S

#4644 chore: add artifact hub badge
  README.md
Labels: size/XS

#4627 feat: pg add lock and unlock
  cmd/probe/internal/binding/postgres/postgres.go
  cmd/probe/internal/component/postgres/manager.go
Labels: feature, size/M

#4606 chore: Optimizing wal log parameters for small-size instances, e.g: Sealos instances
  deploy/postgresql/config/pg12-config.tpl
  deploy/postgresql/config/pg14-config.tpl
  internal/cli/cmd/builder/template/util.go
  internal/controller/plan/builtin_functions.go
  internal/controller/plan/config_template.go
  internal/controller/plan/config_template_test.go
  internal/controllerutil/pod_utils.go
  internal/controllerutil/pod_utils_test.go
Labels: approved, size/L

#4650 chore: dynamic render the value of innodb_redo_log_capacity (#4480)
  deploy/apecloud-mysql/config/mysql8-config.tpl
Labels: ci, approved, size/S

#4648 fix: postgresql/redis cluster hscale ops status is incorrect
  controllers/apps/cluster_plan_builder.go
  controllers/apps/components/base.go
  internal/controller/graph/dag.go
  internal/controller/graph/dag_test.go
  internal/controller/rsm/plan_builder.go
Labels: enhancement, size/M

#4651 chore: Optimizing wal log parameters for small-size instances, e.g: Sealos instances
  deploy/postgresql/config/pg12-config.tpl
  deploy/postgresql/config/pg14-config.tpl
  internal/cli/cmd/builder/template/util.go
  internal/controller/plan/builtin_functions.go
  internal/controller/plan/config_template.go
  internal/controller/plan/config_template_test.go
  internal/controllerutil/pod_utils.go
  internal/controllerutil/pod_utils_test.go
Labels: size/L

#4652 chore: dynamic render the value of innodb_redo_log_capacity
  deploy/apecloud-mysql/config/mysql8-config.tpl
Labels: ci

#4656 chore: sync helm charts release latest
  .github/workflows/release-sync.yml
Labels: test, release, approved, size/XS

#4653 fix: get cd and cv from backup if creating cluster by backup
  internal/cli/cmd/cluster/create.go
Labels: enhancement, size/XS

#4659 fix: hscale failed if disabled snapshot
  controllers/apps/cluster_controller_test.go
  controllers/apps/components/base_stateful_hscale.go
Labels: enhancement, size/M

#4664 fix: volume expand is blocked after upgrading to 0.6
  controllers/apps/operations/volume_expansion.go
Labels: enhancement, size/S

#4673 fix: volume expansion ops failed
  apis/apps/v1alpha1/opsrequest_webhook.go
  apis/apps/v1alpha1/opsrequest_webhook_test.go
Labels: enhancement, size/S

#4679 fix: qdrant cluster ops is always running
  deploy/qdrant/templates/clusterdefinition.yaml
Labels: enhancement, approved, size/XS

#3048 feat: add support for FoxLake
  deploy/foxlake-cluster/.helmignore
  deploy/foxlake-cluster/Chart.yaml
  deploy/foxlake-cluster/templates/NOTES.txt
  deploy/foxlake-cluster/templates/_helpers.tpl
  deploy/foxlake-cluster/templates/cluster.yaml
  deploy/foxlake-cluster/templates/clusterrolebinding.yaml
  deploy/foxlake-cluster/templates/serviceaccount.yaml
  deploy/foxlake-cluster/templates/validate.yaml
  deploy/foxlake-cluster/values.yaml
  deploy/foxlake/.helmignore
  deploy/foxlake/Chart.yaml
  deploy/foxlake/templates/NOTES.txt
  deploy/foxlake/templates/_helpers.tpl
  deploy/foxlake/templates/clusterdefinition.yaml
  deploy/foxlake/templates/clusterrole.yaml
  deploy/foxlake/templates/clusterversion.yaml
  deploy/foxlake/values.yaml
  deploy/helm/templates/addons/foxlake-addon.yaml
  internal/sqlchannel/engine/engine.go
  internal/sqlchannel/engine/engine_test.go
  internal/sqlchannel/engine/foxlake.go
  internal/sqlchannel/engine/foxlake_test.go
Labels: area/user-interaction, feature, size/XL

#4678 chore: move wesql switchover script to scriptSpec configMap
  deploy/apecloud-mysql/templates/clusterdefinition.yaml
  deploy/apecloud-mysql/templates/scripts.yaml
Labels: size/S

#4623 feat: kbcli bench support only cleanup, prepare or run
  docs/user_docs/cli/kbcli_bench_pgbench.md
  docs/user_docs/cli/kbcli_bench_sysbench.md
  docs/user_docs/cli/kbcli_bench_tpcc.md
  docs/user_docs/cli/kbcli_bench_ycsb.md
  go.mod
  go.sum
  internal/cli/cmd/bench/bench.go
  internal/cli/cmd/bench/pgbench.go
  internal/cli/cmd/bench/sysbench.go
  internal/cli/cmd/bench/tpcc.go
  internal/cli/cmd/bench/ycsb.go
Labels: area/user-interaction, feature, size/L

#4658 fix: delete PVCs before updating STS at scaling-in
  controllers/apps/components/base_stateful.go
Labels: enhancement, size/XS

#4681 chore: monitor-database.md spelling mistake
  docs/user_docs/observability/monitor-database.md
Labels: enhancement, size/XS

#4680 chore: adjust the file permissions of the configmap volumes
  deploy/apecloud-mysql/templates/clusterdefinition.yaml
  deploy/mongodb/templates/clusterdefinition.yaml
  deploy/mongodb/templates/sharding-clusterdefinition.yaml
  deploy/mysql/templates/clusterdefinition.yaml
  deploy/nebula/templates/clusterdefinition.yaml
  deploy/postgresql/templates/clusterdefinition.yaml
  deploy/postgresql/templates/clusterversion.yaml
  deploy/pulsar/templates/clusterdefinition.yaml
  deploy/qdrant/templates/clusterdefinition.yaml
  deploy/redis-demo-for-dynamic-switchover/templates/clusterdefinition.yaml
  deploy/redis/templates/clusterdefinition.yaml
  deploy/tdengine/templates/clusterdefinition.yaml
Labels: approved, size/M

#4676 fix: failed to update with --enable-all-logs (#4672)
  internal/cli/cmd/cluster/update.go
  internal/cli/cmd/cluster/update_test.go
Labels: enhancement, approved, size/S

#4603 feat: improve pgsql pitr and support restore from wal-g datafile
  apis/dataprotection/v1alpha1/backup_types.go
  apis/dataprotection/v1alpha1/backuptool_types.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuptools.yaml
  controllers/apps/cluster_controller_test.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/backuppolicy_controller.go
  controllers/dataprotection/backuppolicy_controller_test.go
  controllers/dataprotection/restorejob_controller.go
  controllers/dataprotection/utils.go
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuptools.yaml
  deploy/mongodb/scripts/backup-log-collector.sh
  deploy/mongodb/templates/backuptool_pitr.yaml
  deploy/mongodb/templates/scriptstemplate.yaml
  deploy/postgresql/dataprotection/backup-info-collector.sh
  deploy/postgresql/dataprotection/fetch-wal-log.sh
  deploy/postgresql/dataprotection/pitr-backup.sh
  deploy/postgresql/dataprotection/pitr-restore.sh
  deploy/postgresql/templates/backuppolicytemplate.yaml
  deploy/postgresql/templates/backuptool-pgbasebackup.yaml
  deploy/postgresql/templates/backuptool-pitr.yaml
  deploy/postgresql/templates/backuptool-wal-g.yaml
  deploy/postgresql/templates/scripts.yaml
  internal/constant/const.go
  internal/controller/plan/restore.go
  internal/controller/plan/restore_test.go
  internal/controllerutil/errors.go
Labels: feature, size/XL

#4689 fix: failed to update with --enable-all-logs
  internal/cli/cmd/cluster/update.go
  internal/cli/cmd/cluster/update_test.go
Labels: enhancement, size/M

#4674 fix: distinguish ops for kbcli confirm
  internal/cli/cmd/accounts/delete.go
  internal/cli/cmd/cluster/operations.go
  internal/cli/delete/delete.go
  internal/cli/util/prompt/prompt.go
Labels: enhancement, size/M

#4688 fix: kafka definition bugfix about conn credential and volume expand
  deploy/kafka-cluster/templates/cluster.yaml
  deploy/kafka/templates/clusterdefinition.yaml
Labels: bug, enhancement, size/L

#4690 fix: mongodb restore problem
  cmd/probe/internal/component/mongodb/manager.go
  deploy/mongodb/scripts/replicaset-setup.tpl
Labels: enhancement, size/S

#4696 fix: failed to create cluster with --set-file
  internal/cli/cmd/cluster/create.go
Labels: enhancement, size/XS

#4668 feat: bench support toleration
  docs/user_docs/cli/kbcli_bench_pgbench.md
  docs/user_docs/cli/kbcli_bench_sysbench.md
  docs/user_docs/cli/kbcli_bench_tpcc.md
  docs/user_docs/cli/kbcli_bench_ycsb.md
  go.mod
  go.sum
  internal/cli/cmd/bench/bench.go
  internal/cli/cmd/bench/bench_test.go
  internal/cli/cmd/bench/pgbench.go
  internal/cli/cmd/bench/sysbench.go
  internal/cli/cmd/bench/tpcc.go
  internal/cli/cmd/bench/ycsb.go
Labels: area/user-interaction, feature, size/L

#4695 feat: migrate the scripts files in configmap to the helmscripts directory
  deploy/apecloud-mysql/config/mysql-reload.tpl
  deploy/apecloud-mysql/scripts/agamotto.sh
  deploy/apecloud-mysql/scripts/binlog-collector.sh
  deploy/apecloud-mysql/scripts/etcd-post-start.sh
  deploy/apecloud-mysql/scripts/etcd.sh
  deploy/apecloud-mysql/scripts/pre-stop.sh
  deploy/apecloud-mysql/scripts/set_config_variables.sh
  deploy/apecloud-mysql/scripts/setup.sh
  deploy/apecloud-mysql/scripts/switchover-with-candidate.sh
  deploy/apecloud-mysql/scripts/switchover-without-candidate.sh
  deploy/apecloud-mysql/scripts/vtconsensus.sh
  deploy/apecloud-mysql/scripts/vtctld.sh
  deploy/apecloud-mysql/scripts/vtgate.sh
  deploy/apecloud-mysql/scripts/vttablet.sh
  deploy/apecloud-mysql/scripts/wait-for-service.sh
  deploy/apecloud-mysql/templates/_helpers.tpl
  deploy/apecloud-mysql/templates/configmap.yaml
  deploy/apecloud-mysql/templates/scripts.yaml
  deploy/postgresql/config/patroni-reload.tpl
  deploy/postgresql/config/restart-parameter.yaml
  deploy/postgresql/scripts/backup-info-collector.sh
  deploy/postgresql/scripts/generate_patroni_yaml.py
  deploy/postgresql/scripts/init_container.sh
  deploy/postgresql/scripts/pgbouncer_setup.sh
  deploy/postgresql/scripts/setup.sh
  deploy/postgresql/templates/_helpers.tpl
  deploy/postgresql/templates/patroni-reload.yaml
  deploy/postgresql/templates/scripts.yaml
  deploy/pulsar/scripts/check-bookies.sh
  deploy/pulsar/scripts/init-bookies.sh
  deploy/pulsar/scripts/init-broker-sysctl.sh
  deploy/pulsar/scripts/init-broker.sh
  deploy/pulsar/scripts/init-proxy.sh
  deploy/pulsar/scripts/merge_pulsar_config.py
  deploy/pulsar/scripts/prestop-bookies.sh
  deploy/pulsar/scripts/start-bookies-recovery.sh
  deploy/pulsar/scripts/start-bookies.sh
  deploy/pulsar/scripts/start-proxy.sh
  deploy/pulsar/scripts/start-zookeeper.sh
  deploy/pulsar/scripts/zookeeper.py
  deploy/pulsar/templates/_helpers.tpl
  deploy/pulsar/templates/scripts.yaml
  deploy/redis/scripts/redis-ping.sh
  deploy/redis/scripts/redis-preStop.sh
  deploy/redis/scripts/redis-sentinel-ping.sh
  deploy/redis/scripts/redis-sentinel-post-start.sh
  deploy/redis/scripts/redis-sentinel-setup.sh
  deploy/redis/scripts/redis-sentinel-start.sh
  deploy/redis/scripts/redis-start.sh
  deploy/redis/templates/_helpers.tpl
  deploy/redis/templates/scripts.yaml
  docs/user_docs/cli/cli.md
  docs/user_docs/cli/kbcli_builder.md
  internal/cli/cmd/builder/builder.go
  internal/cli/cmd/builder/template/template.go
  internal/cli/cmd/builder/template/template_test.go
  internal/cli/cmd/builder/template/util.go
  internal/cli/cmd/builder/tools/migrate_scripts.go
Labels: area/user-interaction, feature, approved, size/XXL

#4704 fix: modify pg isDBStartReady
  cmd/probe/internal/component/postgres/manager.go
Labels: enhancement, size/S

#4698 fix: keep volumes size consistent after scale-out
  controllers/apps/cluster_controller_test.go
  controllers/apps/components/base_stateful_hscale.go
Labels: enhancement, size/XL

#4707 chore: update generate release notes script and set default gh_env to release-0.6
  .github/utils/generate_release_notes.py
  .github/utils/gh_env
Labels: enhancement, release, size/S

#4702 feat: support bytebase
  deploy/bytebase/.helmignore
  deploy/bytebase/Chart.yaml
  deploy/bytebase/templates/_helpers.tpl
  deploy/bytebase/templates/service.yaml
  deploy/bytebase/templates/statefulset.yaml
  deploy/bytebase/values.yaml
  deploy/helm/templates/addons/bytebase-addon.yaml
  internal/cli/cmd/dashboard/dashboard.go
Labels: area/user-interaction, feature, size/L

#4712 chore: fix delete gh cache error
  .github/workflows/release-publish.yml
Labels: enhancement, approved, size/XS

#4706 fix: simplified api auto create first component
  controllers/apps/transformer_rbac_test.go
  internal/controller/component/component.go
  internal/controller/component/component_test.go
Labels: enhancement, approved, size/M

#4715 chore: add postgresql 12.14.0 clusterVersion for backward compatibility
  deploy/postgresql/templates/clusterversion.yaml
Labels: size/M

#4719 fix: Kafka access control under different networks & ConfigConstraint fix
  deploy/kafka-cluster/templates/cluster.yaml
  deploy/kafka/configs/kafka-server-constraint.cue
  deploy/kafka/scripts/kafka-server-setup.sh.tpl
  deploy/kafka/templates/clusterdefinition.yaml
  deploy/kafka/templates/configconstraint.yaml
Labels: enhancement, size/XL

#4716 fix: mongodb single node problem
  cmd/probe/internal/dcs/dcs.go
  cmd/probe/internal/dcs/types.go
Labels: enhancement, size/S

#4711 chore: bump dependency version
  cmd/probe/internal/middleware/http/probe/checks_middleware.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_clustertemplates.yaml
  config/crd/bases/apps.kubeblocks.io_clusterversions.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuptools.yaml
  config/crd/bases/dataprotection.kubeblocks.io_restorejobs.yaml
  config/crd/bases/workloads.kubeblocks.io_replicatedstatemachines.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clustertemplates.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterversions.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuptools.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_restorejobs.yaml
  deploy/helm/crds/workloads.kubeblocks.io_replicatedstatemachines.yaml
  docs/user_docs/api-reference/backup.md
  docs/user_docs/api-reference/cluster.md
  go.mod
  go.sum
  internal/cli/cmd/accounts/delete.go
  internal/cli/cmd/addon/addon.go
  internal/cli/cmd/auth/authorize/token_provider.go
  internal/cli/cmd/bench/bench.go
Labels: dependencies, size/XXL

#4730 fix: oracle-mysql config
  deploy/oracle-mysql/config/oracle-mysql-config-constraint.cue
  deploy/oracle-mysql/config/oracle-mysql-config.tpl
  deploy/oracle-mysql/config/oracle-mysql-perf-config.tpl
  deploy/oracle-mysql/scripts/oracle-mysql-reload.tpl
  deploy/oracle-mysql/templates/clusterdefinition.yaml
  deploy/oracle-mysql/templates/clusterversion.yaml
  deploy/oracle-mysql/templates/configconstraint.yaml
  deploy/oracle-mysql/templates/configmap-perf.yaml
  deploy/oracle-mysql/templates/configmap.yaml
  deploy/oracle-mysql/templates/scripts.yaml
Labels: area/user-interaction, enhancement, size/L

#4731 fix: backward compatibility upgrade postgresql from v0.5.1 to v0.6.0
  deploy/postgresql/templates/scripts.yaml
Labels: enhancement, size/S

#4737 chore: support kbcli e2e upgrade test
  .github/workflows/e2e-kbcli.yml
Labels: test, approved, size/S

#4736 chore: apecloud mysql add file size collector and purge expired files for logfile
  deploy/apecloud-mysql/dataprotection/pitr-backup.sh
  deploy/apecloud-mysql/dataprotection/pitr-restore.sh
  deploy/apecloud-mysql/scripts/binlog-collector.sh
  deploy/apecloud-mysql/scripts/snapshot-backup-collector.sh
  deploy/apecloud-mysql/templates/backuppolicytemplate.yaml
  deploy/apecloud-mysql/templates/backuptool-pitr.yaml
  deploy/apecloud-mysql/templates/backuptool.yaml
Labels: approved, size/L

#4726 feat: support mongo dump backup script
  apis/dataprotection/v1alpha1/backup_types.go
  apis/dataprotection/v1alpha1/backup_types_test.go
  apis/dataprotection/v1alpha1/backuptool_types.go
  controllers/apps/components/base_stateful_hscale.go
  deploy/mongodb/dataprotection/backup-info-collector.sh
  deploy/mongodb/dataprotection/pitr-backup.sh
  deploy/mongodb/templates/backuppolicytemplate.yaml
  deploy/mongodb/templates/backuptool.yaml
  deploy/mongodb/templates/backuptool_mongodump.yaml
  deploy/mongodb/templates/backuptool_pitr.yaml
  internal/controller/plan/restore.go
  internal/controller/plan/restore_test.go
Labels: area/user-interaction, feature, size/XL

#4634 feat: improve mysql ha
  cmd/probe/internal/binding/mysql/mysql.go
  cmd/probe/internal/component/dbmanager.go
  cmd/probe/internal/component/mongodb/manager.go
  cmd/probe/internal/component/mysql/get_role.go
  cmd/probe/internal/component/mysql/gtid.go
  cmd/probe/internal/component/mysql/manager.go
  cmd/probe/internal/component/postgres/manager.go
  cmd/probe/internal/component/util.go
  cmd/probe/internal/dcs/k8s.go
  cmd/probe/internal/dcs/types.go
  cmd/probe/internal/highavailability/ha.go
Labels: feature, size/XL

#4738 chore: using snapshot time
  controllers/dataprotection/backup_controller.go
  deploy/apecloud-mysql/dataprotection/pitr-restore.sh
  deploy/apecloud-mysql/scripts/snapshot-backup-collector.sh
  deploy/apecloud-mysql/templates/backuppolicytemplate.yaml
  deploy/mongodb/scripts/backup-log-collector.sh
  deploy/mongodb/templates/backuppolicytemplate.yaml
  deploy/mongodb/templates/scriptstemplate.yaml
  deploy/postgresql/scripts/backup-info-collector.sh
  deploy/postgresql/templates/backuppolicytemplate.yaml
Labels: size/M

#4732 fix: backward compatibility upgrade postgresql from v0.5.1 to v0.6.0
  deploy/postgresql/scripts/setup.sh
Labels: enhancement, size/S

#4733 chore: generate prepuller daemonset to warm kubeblocks images
  .github/utils/extract_chart_n_image_list.sh
Labels: size/M

#4720 chore: rollback the CRDs of ClusterTemplate and ClusterFamily
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/clusterfamily_types.go
  apis/apps/v1alpha1/clustertemplate_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusterfamilies.yaml
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_clustertemplates.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_apps_clusterfamilies.yaml
  config/crd/patches/cainjection_in_apps_clustertemplates.yaml
  config/crd/patches/webhook_in_apps_clusterfamilies.yaml
  config/crd/patches/webhook_in_apps_clustertemplates.yaml
  config/rbac/apps_clusterfamily_editor_role.yaml
  config/rbac/apps_clusterfamily_viewer_role.yaml
  config/rbac/apps_clustertemplate_editor_role.yaml
  config/rbac/apps_clustertemplate_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/apps_v1alpha1_clusterfamily.yaml
  config/samples/apps_v1alpha1_clustertemplate.yaml
  controllers/apps/cluster_plan_builder.go
  controllers/apps/cluster_plan_builder_test.go
  controllers/apps/clusterfamily_controller.go
  controllers/apps/clustertemplate_controller.go
  controllers/apps/components/component.go
  controllers/apps/components/status_test.go
  controllers/apps/transform_restore.go
  controllers/apps/transformer_cluster_credential.go
  controllers/apps/transformer_component.go
  controllers/apps/transformer_rbac.go
  controllers/apps/transformer_validate_and_load_ref_resources.go
  controllers/apps/utils.go
  controllers/apps/utils_test.go
  deploy/apecloud-mysql/templates/clusterdefinition.yaml
  deploy/apecloud-mysql/templates/clusterfamily.yaml
  deploy/apecloud-mysql/templates/clustertemplate.yaml
  deploy/helm/config/rbac/role.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterfamilies.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clustertemplates.yaml
  deploy/mysql-cluster/values.schema.json
  deploy/mysql-cluster/values.yaml
  docs/user_docs/api-reference/cluster.md
  go.mod
  internal/cli/cmd/builder/template/component_wrapper.go
  internal/controller/builder/builder_test.go
  internal/controller/component/affinity_utils_test.go
  internal/controller/component/component.go
  internal/controller/component/component_test.go
  internal/controller/plan/envfrom_utils_test.go
  internal/controller/plan/prepare_test.go
  internal/controller/plan/template_wrapper_test.go
  internal/controller/plan/tool_image_builder_test.go
Labels: size/XXL

#4710 feat: vllm
  deploy/vllm/Chart.yaml
  deploy/vllm/templates/NOTES.txt
  deploy/vllm/templates/_helpers.tpl
  deploy/vllm/templates/clusterdefinition.yaml
  deploy/vllm/templates/clusterversion.yaml
  deploy/vllm/templates/scripts.yaml
  deploy/vllm/values.yaml
Labels: feature, approved, size/L

#4757 chore: fix container of backup pod misses resources
  controllers/dataprotection/backup_controller.go
  internal/controller/builder/builder.go
  internal/controllerutil/container_util.go
Labels: enhancement

#4758 chore: fix container of backup pod misses resources
  controllers/dataprotection/backup_controller.go
  internal/controller/builder/builder.go
  internal/controllerutil/container_util.go
Labels: enhancement, size/M

#4763 feat: replace to stateful deploy kind for pgsql wal archive
  controllers/dataprotection/backuppolicy_controller.go
  controllers/dataprotection/utils.go
  deploy/mongodb/dataprotection/pitr-backup.sh
  deploy/postgresql/dataprotection/pitr-backup.sh
  deploy/postgresql/templates/backuptool-pitr.yaml
Labels: area/user-interaction, feature, size/L

#4742 feat: sqlchannel improve ha
  cmd/probe/internal/component/dbmanager.go
  cmd/probe/internal/dcs/dcs.go
  cmd/probe/internal/dcs/k8s.go
  cmd/probe/internal/highavailability/ha.go
  go.mod
  go.sum
  internal/constant/env.go
Labels: feature, size/L

#4755 fix: fix bin/kbcli for no any parameters
  internal/cli/cmd/cli.go
Labels: enhancement, size/XS

#4767 chore: amend regex to match log-error configuration
  deploy/apecloud-mysql/values.yaml
Labels: approved, size/XS

#4770 fix: redis may restore fail
  deploy/apecloud-mysql/templates/backuptool.yaml
  deploy/apecloud-mysql/templates/backuptoolforhscale.yaml
  deploy/mongodb/templates/backuptool.yaml
  deploy/oracle-mysql/templates/backuptool.yaml
  deploy/redis/templates/backuptool.yaml
Labels: enhancement, approved, size/S

#4776 fix: mysql datafile restore fail
  deploy/apecloud-mysql/templates/backuptool.yaml
  deploy/apecloud-mysql/templates/backuptoolforhscale.yaml
  deploy/oracle-mysql/templates/backuptool.yaml
Labels: enhancement, approved, size/S

#4740 chore: update pulsar configconstraints
  deploy/pulsar/config/broker-config-constraint.cue
  deploy/pulsar/config/broker-config.tpl
  deploy/pulsar/config/proxy-config-constraint.cue
  deploy/pulsar/scripts/merge_pulsar_config.py
  deploy/pulsar/templates/clusterdefinition.yaml
  test/e2e/util/analyze_report.go
Labels: approved, size/XXL

#4771 fix: role changed event out of order when kubeblocks failure
  apis/workloads/v1alpha1/replicatedstatemachine_webhook_test.go
  cmd/probe/internal/dcs/types.go
  controllers/apps/components/consensus_set_utils.go
  controllers/apps/components/replication_set_utils.go
  controllers/apps/components/replication_set_utils_test.go
  controllers/k8score/event_controller_test.go
  controllers/k8score/role_change_event_handler.go
  controllers/workloads/replicatedstatemachine_controller_test.go
  internal/constant/const.go
  internal/controller/builder/builder_event.go
Labels: enhancement, approved, size/L

#4775 chore: add e2e test report
  deploy/apecloud-mysql-cluster/Chart.yaml
  deploy/apecloud-mysql/Chart.yaml
  deploy/chatgpt-retrieval-plugin/Chart.yaml
  deploy/clickhouse-cluster/Chart.yaml
  deploy/clickhouse/Chart.yaml
  deploy/helm/Chart.yaml
  deploy/kafka-cluster/Chart.yaml
  deploy/kafka/Chart.yaml
  deploy/milvus-cluster/Chart.yaml
  deploy/milvus/Chart.yaml
  deploy/mongodb-cluster/Chart.yaml
  deploy/mongodb/Chart.yaml
  deploy/nyancat/Chart.yaml
  deploy/postgresql-cluster/Chart.yaml
  deploy/postgresql/Chart.yaml
  deploy/qdrant-cluster/Chart.yaml
  deploy/qdrant/Chart.yaml
  deploy/redis-cluster/Chart.yaml
  deploy/redis/Chart.yaml
  deploy/tdengine-cluster/Chart.yaml
  deploy/tdengine/Chart.yaml
  deploy/weaviate-cluster/Chart.yaml
  deploy/weaviate/Chart.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/testdata/smoketest/analyze_report.go
  test/e2e/testdata/smoketest/mongodb/00_mongodbcluster.yaml
  test/e2e/testdata/smoketest/postgresql/00_postgresqlcluster.yaml
  test/e2e/testdata/smoketest/redis/00_rediscluster.yaml
  test/e2e/testdata/smoketest/report.go
  test/e2e/testdata/smoketest/smoketestrun.go
  test/e2e/testdata/smoketest/wesql/00_wesqlcluster.yaml
  test/e2e/testdata/smoketest/wesql/04_hscale_up.yaml
  test/e2e/testdata/smoketest/wesql/05_hscale_down.yaml
  test/e2e/types.go
  test/e2e/util/analyze_report.go
  test/e2e/util/smoke_util.go
Labels: test, size/L

#4786 chore: use aliyun image registry
  deploy/pulsar/values.yaml
Labels: size/XS

#4787 fix: add validation for componentRef
  apis/apps/v1alpha1/clusterdefinition_webhook.go
  apis/apps/v1alpha1/clusterdefinition_webhook_test.go
  deploy/kafka/configs/kafka-server-constraint.cue
  deploy/pulsar/config/broker-config-constraint.cue
  deploy/pulsar/config/proxy-config-constraint.cue
  internal/controller/component/component_fieldref_util.go
Labels: enhancement, approved, size/XXL

#4789 fix: sometimes hscale mysql failed in ack
  controllers/apps/components/base_stateful_hscale.go
  deploy/helm/templates/addons/snapshot-controller-addon.yaml
  deploy/redis/templates/backuptool.yaml
Labels: enhancement, size/S

#4792 fix: update election weight if needed when apecloud-mysql do a switchover
  deploy/apecloud-mysql/config/mysql8-config.tpl
  deploy/apecloud-mysql/templates/scripts.yaml
  test/testdata/cue_testdata/wesql.cnf
  test/testdata/resources/mysql-consensus-config-template.yaml
Labels: enhancement, size/M

#4790 fix: update election weight if needed when apecloud-mysql do a switchover
  deploy/apecloud-mysql/config/mysql8-config.tpl
  deploy/apecloud-mysql/scripts/switchover-with-candidate.sh
  deploy/apecloud-mysql/scripts/switchover-without-candidate.sh
  test/testdata/cue_testdata/wesql.cnf
  test/testdata/resources/mysql-consensus-config-template.yaml
Labels: enhancement, size/M

#4783 feat: sqlchannel improve ha
  cmd/probe/internal/component/dbmanager.go
  cmd/probe/internal/component/postgres/config.go
  cmd/probe/internal/component/postgres/config_test.go
  cmd/probe/internal/component/postgres/manager.go
  cmd/probe/internal/component/postgres/types.go
  cmd/probe/internal/component/postgres/types_test.go
  cmd/probe/internal/highavailability/ha.go
Labels: feature, size/L

#4735 feat: support jupyter
  deploy/helm/templates/addons/jupyter-notebook-addon.yaml
  deploy/helm/templates/addons/jupyterhub-addon.yaml
  deploy/jupyter-notebook/.helmignore
  deploy/jupyter-notebook/Chart.yaml
  deploy/jupyter-notebook/templates/NOTES.txt
  deploy/jupyter-notebook/templates/_helpers.tpl
  deploy/jupyter-notebook/templates/deployment.yaml
  deploy/jupyter-notebook/templates/jupyterPVC.yaml
  deploy/jupyter-notebook/templates/service.yaml
  deploy/jupyter-notebook/values.yaml
  internal/cli/cmd/dashboard/dashboard.go
Labels: area/user-interaction, feature, size/L

#4802 docs: add v0.6.0 release notes
  docs/release_notes/v0.6.0/v0.6.0.md
Labels: documentation, release, size/L

#4806 chore: adjust e2e test report info
  deploy/apecloud-mysql-cluster/Chart.yaml
  deploy/apecloud-mysql/Chart.yaml
  deploy/chatgpt-retrieval-plugin/Chart.yaml
  deploy/clickhouse-cluster/Chart.yaml
  deploy/clickhouse/Chart.yaml
  deploy/helm/Chart.yaml
  deploy/kafka-cluster/Chart.yaml
  deploy/kafka/Chart.yaml
  deploy/milvus-cluster/Chart.yaml
  deploy/milvus/Chart.yaml
  deploy/mongodb-cluster/Chart.yaml
  deploy/mongodb/Chart.yaml
  deploy/nyancat/Chart.yaml
  deploy/postgresql-cluster/Chart.yaml
  deploy/postgresql/Chart.yaml
  deploy/qdrant-cluster/Chart.yaml
  deploy/qdrant/Chart.yaml
  deploy/redis-cluster/Chart.yaml
  deploy/redis/Chart.yaml
  deploy/tdengine-cluster/Chart.yaml
  deploy/tdengine/Chart.yaml
  deploy/weaviate-cluster/Chart.yaml
  deploy/weaviate/Chart.yaml
  test/e2e/testdata/smoketest/analyze_report.go
  test/e2e/testdata/smoketest/mongodb/00_mongodbcluster.yaml
  test/e2e/testdata/smoketest/postgresql/00_postgresqlcluster.yaml
  test/e2e/testdata/smoketest/redis/00_rediscluster.yaml
  test/e2e/testdata/smoketest/redis/07_vexpand.yaml
  test/e2e/testdata/smoketest/wesql/00_wesqlcluster.yaml
  test/e2e/util/smoke_util.go
Labels: test, size/L

#4765 chore: prepuller agamotto image
  .github/utils/extract_chart_n_image_list.sh
Labels: size/XS

#4800 fix: select ClusterRoleBinding w/o ManagedBy label at deletion
  controllers/apps/transform_utils.go
  controllers/apps/transformer_cluster_deletion.go
Labels: enhancement, size/S

#4810 chore: pulsar set storageClassName not take effect
  deploy/pulsar-cluster/templates/cluster.yaml
Labels: size/XS

#4822 feat: add GreptimeDB support
  deploy/greptimedb-cluster/.helmignore
  deploy/greptimedb-cluster/Chart.yaml
  deploy/greptimedb-cluster/templates/NOTES.txt
  deploy/greptimedb-cluster/templates/_helpers.tpl
  deploy/greptimedb-cluster/templates/cluster.yaml
  deploy/greptimedb-cluster/values.yaml
  deploy/greptimedb/.helmignore
  deploy/greptimedb/Chart.yaml
  deploy/greptimedb/templates/NOTES.txt
  deploy/greptimedb/templates/_helpers.tpl
  deploy/greptimedb/templates/clusterdefinition.yaml
  deploy/greptimedb/templates/clusterversion.yaml
  deploy/greptimedb/templates/configmap.yaml
  deploy/greptimedb/templates/serviceaccount.yaml
  deploy/greptimedb/values.yaml
  deploy/helm/templates/addons/greptimedb-addon.yaml
Labels: area/user-interaction, feature, size/XL

#4818 chore: change delphic chart deps version
  .github/utils/extract_chart_n_image_list.sh
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  Makefile
  deploy/apecloud-mysql-cluster/Chart.yaml
  deploy/apecloud-mysql/Chart.yaml
  deploy/chatgpt-retrieval-plugin/Chart.yaml
  deploy/clickhouse-cluster/Chart.yaml
  deploy/clickhouse/Chart.yaml
  deploy/delphic/Chart.yaml
  deploy/helm/Chart.yaml
  deploy/helm/templates/addons/foxlake-addon.yaml
  deploy/kafka-cluster/Chart.yaml
  deploy/kafka/Chart.yaml
  deploy/milvus-cluster/Chart.yaml
  deploy/milvus/Chart.yaml
  deploy/mongodb-cluster/Chart.yaml
  deploy/mongodb-sharding-cluster/Chart.yaml
  deploy/mongodb/Chart.yaml
  deploy/mysql-cluster/Chart.yaml
  deploy/mysql/Chart.yaml
  deploy/nyancat/Chart.yaml
  deploy/oracle-mysql-cluster/Chart.yaml
  deploy/oracle-mysql/Chart.yaml
  deploy/postgresql-cluster/Chart.yaml
  deploy/postgresql/Chart.yaml
  deploy/pulsar-cluster/Chart.yaml
  deploy/pulsar/Chart.yaml
  deploy/qdrant-cluster/Chart.yaml
  deploy/qdrant/Chart.yaml
  deploy/redis-cluster/Chart.yaml
  deploy/redis/Chart.yaml
  deploy/tdengine-cluster/Chart.yaml
  deploy/tdengine/Chart.yaml
  deploy/weaviate-cluster/Chart.yaml
  deploy/weaviate/Chart.yaml
Labels: dependencies, approved, size/M

#4814 feat: support GPU monitoring by integrating with the nvidia-gpu-exporter
  deploy/helm/dashboards/nvidia-gpu-exporter.json
  deploy/helm/templates/addons/nvidia-gpu-exporter-addon.yaml
Labels: area/user-interaction, feature, approved, size/XXL

#4635 feat: support elasticsearch
  deploy/elasticsearch-cluster/.helmignore
  deploy/elasticsearch-cluster/Chart.yaml
  deploy/elasticsearch-cluster/templates/NOTES.txt
  deploy/elasticsearch-cluster/templates/_helpers.tpl
  deploy/elasticsearch-cluster/templates/cluster.yaml
  deploy/elasticsearch-cluster/values.yaml
  deploy/elasticsearch/.helmignore
  deploy/elasticsearch/Chart.yaml
  deploy/elasticsearch/TODO
  deploy/elasticsearch/configs/elasticsearch.yaml.tpl
  deploy/elasticsearch/templates/NOTES.txt
  deploy/elasticsearch/templates/_helpers.tpl
  deploy/elasticsearch/templates/clusterdefinition.yaml
  deploy/elasticsearch/templates/clusterversion.yaml
  deploy/elasticsearch/templates/configconstraint.yaml
  deploy/elasticsearch/templates/configmap.yaml
  deploy/elasticsearch/values.yaml
  deploy/helm/templates/addons/elasticsearch-addon.yaml
Labels: feature, approved, size/XL

#4831 chore: check all commits change file Chinese
  .github/utils/utils.sh
  .github/workflows/cicd-push.yml
Labels: approved, size/S

#4833 chore: run e2e test on local branch-based
  Makefile
  test/e2e/Makefile
  test/e2e/e2e_suite_test.go
  test/e2e/testdata/smoketest/mongodb/00_mongodbcluster.yaml
  test/e2e/testdata/smoketest/postgresql/00_postgresqlcluster.yaml
  test/e2e/testdata/smoketest/pulsar/00_pulsarcluster.yaml
  test/e2e/testdata/smoketest/redis/00_rediscluster.yaml
  test/e2e/testdata/smoketest/smoketestrun.go
  test/e2e/testdata/smoketest/wesql/00_wesqlcluster.yaml
Labels: test, approved, size/M

#4825 feat: wesql scale support connection pool size config
  deploy/apecloud-mysql/config/mysql-scale-vttablet-config-constraint.cue
  deploy/apecloud-mysql/config/mysql-scale-vttablet-config.tpl
  deploy/apecloud-mysql/scripts/vttablet.sh
Labels: feature, size/S

#4836 fix: smoketest upgrade image required error
  test/e2e/testdata/smoketest/postgresql/07_cv.yaml
  test/e2e/testdata/smoketest/redis/08_cv.yaml
  test/e2e/testdata/smoketest/wesql/07_cv.yaml
Labels: test, enhancement, approved, size/M

#4817 feat: bench list add --all-namespaces
  docs/user_docs/cli/kbcli_bench_list.md
  internal/cli/cmd/bench/bench.go
Labels: feature, size/XS

#4780 feat: add auto signup and KB clusters auto injection to Bytebase
  deploy/bytebase/Chart.yaml
  deploy/bytebase/templates/auto-plugin.yaml
  deploy/bytebase/templates/script.yaml
  deploy/helm/templates/addons/bytebase-addon.yaml
Labels: area/user-interaction, feature, size/L

#4835 fix: guarantee to leave from the replication membership before delete replicas
  controllers/apps/cluster_controller_test.go
  controllers/apps/components/base_stateful.go
  controllers/apps/opsrequest_controller_test.go
  deploy/apecloud-mysql/scripts/pre-stop.sh
  internal/sqlchannel/client.go
Labels: enhancement, size/L

#4830 fix: remove chinese characters
  deploy/elasticsearch-cluster/values.yaml
Labels: enhancement, size/XS

#4829 fix: update hard-coded replicas to config
  deploy/vllm/templates/clusterversion.yaml
  deploy/vllm/templates/scripts.yaml
Labels: bug, enhancement, size/M

#4781 feat: quantize llm on cpu by ggml
  deploy/ggml/Chart.yaml
  deploy/ggml/templates/NOTES.txt
  deploy/ggml/templates/_helpers.tpl
  deploy/ggml/templates/clusterdefinition.yaml
  deploy/ggml/templates/clusterversion.yaml
  deploy/ggml/values.yaml
Labels: feature, size/L

#4844 fix: run e2e test helm install CD and CV
  Makefile
  test/e2e/Makefile
Labels: test, enhancement, approved, size/S

#4803 feat: support delete configuration parameters (#4773)
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/configuration/sync_upgrade_policy.go
  controllers/apps/operations/reconfigure_util.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/user_docs/cli/kbcli_cluster_configure.md
  docs/user_docs/cli/kbcli_cluster_edit-config.md
  internal/cli/cmd/cluster/config_edit.go
  internal/cli/cmd/cluster/config_ops.go
  internal/cli/cmd/cluster/config_ops_test.go
  internal/cli/cmd/cluster/config_util.go
  internal/cli/cmd/cluster/config_wrapper.go
  internal/cli/cmd/cluster/operations.go
  internal/cli/create/template/cluster_operations_template.cue
  internal/cli/util/util.go
  internal/cli/util/util_test.go
  internal/configuration/config.go
  internal/configuration/config_manager/reload_util.go
  internal/configuration/config_patch_util.go
  internal/configuration/config_test.go
  internal/configuration/config_util.go
  internal/configuration/config_util_test.go
  internal/configuration/reconfigure_util.go
  internal/configuration/type.go
  internal/configuration/util/pointer.go
  internal/configuration/util/pointer_test.go
  internal/controller/plan/template_merger.go
  internal/unstructured/properties.go
  internal/unstructured/redis_config.go
  internal/unstructured/redis_config_test.go
  internal/unstructured/type.go
  internal/unstructured/viper_wrap.go
  internal/unstructured/xml_config.go
  internal/unstructured/xml_config_test.go
  internal/unstructured/yaml_config.go
  internal/unstructured/yaml_config_test.go
Labels: area/configuration, area/user-interaction, feature, approved, size/L

#4797 feat: support orioledb
  deploy/helm/templates/addons/orioledb-addon.yaml
  deploy/orioledb-cluster/.helmignore
  deploy/orioledb-cluster/Chart.yaml
  deploy/orioledb-cluster/templates/NOTES.txt
  deploy/orioledb-cluster/templates/_helpers.tpl
  deploy/orioledb-cluster/templates/cluster.yaml
  deploy/orioledb-cluster/templates/rbac.yaml
  deploy/orioledb-cluster/templates/validate.yaml
  deploy/orioledb-cluster/values.schema.json
  deploy/orioledb-cluster/values.yaml
  deploy/orioledb/.helmignore
  deploy/orioledb/Chart.yaml
  deploy/orioledb/config/orioledb-config-constraint.cue
  deploy/orioledb/config/orioledb-config-effect-scope.yaml
  deploy/orioledb/config/orioledb-config.tpl
  deploy/orioledb/config/pgbouncer-ini.tpl
  deploy/orioledb/scripts/patroni-reload.tpl
  deploy/orioledb/scripts/restart-parameter.yaml
  deploy/orioledb/templates/NOTES.txt
  deploy/orioledb/templates/_helpers.tpl
  deploy/orioledb/templates/agamotto-configmap.yaml
  deploy/orioledb/templates/clusterdefinition.yaml
  deploy/orioledb/templates/clusterversion.yaml
  deploy/orioledb/templates/configconstraint.yaml
  deploy/orioledb/templates/configmap.yaml
  deploy/orioledb/templates/metrics-configmap-14.yaml
  deploy/orioledb/templates/patroni-reload.yaml
  deploy/orioledb/templates/pgbouncer-configmap.yaml
  deploy/orioledb/templates/scripts.yaml
  deploy/orioledb/values.yaml
Labels: area/user-interaction, feature, size/XXL

#4849 chore: auto cherry-pick workflow
  .github/workflows/cherry-pick.yml
Labels: approved, size/S

#4777 refactor: enable rsm by default
  apis/workloads/v1alpha1/replicatedstatemachine_types.go
  cmd/manager/main.go
  config/crd/bases/workloads.kubeblocks.io_replicatedstatemachines.yaml
  controllers/apps/cluster_controller_test.go
  controllers/apps/cluster_status_event_handler_test.go
  controllers/apps/components/base.go
  controllers/apps/components/base_stateful.go
  controllers/apps/components/base_stateful_legacy.go
  controllers/apps/components/component.go
  controllers/apps/components/rsm_set_test.go
  controllers/apps/components/status_test.go
  controllers/apps/opsrequest_controller_test.go
  controllers/apps/tls_utils_test.go
  controllers/apps/transformer_cluster_deletion.go
  controllers/workloads/replicatedstatemachine_controller.go
  deploy/etcd-cluster/templates/cluster.yaml
  deploy/helm/crds/workloads.kubeblocks.io_replicatedstatemachines.yaml
  internal/controller/builder/builder.go
  internal/controller/graph/dag.go
  internal/controller/graph/dag_test.go
  internal/controller/rsm/suite_test.go
  internal/controller/rsm/transformer_deletion_test.go
  internal/controller/rsm/transformer_member_reconfiguration_test.go
  internal/controller/rsm/transformer_object_generation.go
  internal/controller/rsm/transformer_objection_generation_test.go
  internal/controller/rsm/transformer_status_test.go
  internal/controller/rsm/transformer_update_strategy.go
  internal/controller/rsm/transformer_update_strategy_test.go
  internal/controller/rsm/utils.go
  internal/controllerutil/util.go
Labels: refactor, size/XL, rsm

#4808 feat: verify the parameters are allowed to be modified (#4804)
  internal/cli/cmd/cluster/config_edit.go
  internal/cli/cmd/cluster/config_ops.go
  internal/cli/util/util.go
  internal/configuration/reconfigure_util.go
Labels: area/configuration, area/user-interaction, feature, approved, size/M

#4842 feat: add lorry support for wesql
  cmd/probe/internal/binding/base.go
  cmd/probe/internal/binding/operation_volume_protection_test.go
  cmd/probe/internal/component/dbmanager.go
  cmd/probe/internal/component/mongodb/manager.go
  cmd/probe/internal/component/mysql/json.go
  cmd/probe/internal/component/mysql/manager.go
  cmd/probe/internal/component/mysql/query.go
  cmd/probe/internal/component/mysql/query_test.go
  cmd/probe/internal/component/mysql/wesql_conn.go
  cmd/probe/internal/component/mysql/wesql_get_role.go
  cmd/probe/internal/component/mysql/wesql_manager.go
  cmd/probe/internal/component/postgres/manager.go
  cmd/probe/internal/dcs/dcs.go
  cmd/probe/internal/dcs/k8s.go
  cmd/probe/internal/dcs/types.go
  cmd/probe/internal/highavailability/ha.go
  cmd/probe/main.go
Labels: feature, approved, size/XXL

#4819 fix: tolerate null values for non-string type (#4741)
  internal/configuration/cue_util.go
  internal/configuration/cue_visitor.go
  internal/configuration/cue_visitor_test.go
  internal/configuration/util/unstructured.go
Labels: enhancement, approved, size/M

#4855 fix: improve frontend and configmap for greptimedb
  deploy/greptimedb-cluster/Chart.yaml
  deploy/greptimedb/Chart.yaml
  deploy/greptimedb/templates/clusterdefinition.yaml
  deploy/greptimedb/values.yaml
Labels: enhancement, approved, size/L

#4851 chore: delete redis-demo example
  deploy/redis-demo-for-dynamic-switchover/.helmignore
  deploy/redis-demo-for-dynamic-switchover/Chart.yaml
  deploy/redis-demo-for-dynamic-switchover/config/redis7-config-constraint.cue
  deploy/redis-demo-for-dynamic-switchover/config/redis7-config-effect-scope.yaml
  deploy/redis-demo-for-dynamic-switchover/config/redis7-config-secondary-render.tpl
  deploy/redis-demo-for-dynamic-switchover/config/redis7-config.tpl
  deploy/redis-demo-for-dynamic-switchover/config/redis7-sentinel-config.tpl
  deploy/redis-demo-for-dynamic-switchover/scripts/redis-process-switchover.sh
  deploy/redis-demo-for-dynamic-switchover/scripts/redis-reload.sh
  deploy/redis-demo-for-dynamic-switchover/scripts/redis-replicas-update.sh
  deploy/redis-demo-for-dynamic-switchover/scripts/redis-sentinel-process-replicas-lables.sh
  deploy/redis-demo-for-dynamic-switchover/scripts/redis-sentinel-setup.sh.tpl
  deploy/redis-demo-for-dynamic-switchover/scripts/redis-sentinel-start.sh.tpl
  deploy/redis-demo-for-dynamic-switchover/templates/_helpers.tpl
  deploy/redis-demo-for-dynamic-switchover/templates/backuppolicytemplate.yaml
  deploy/redis-demo-for-dynamic-switchover/templates/clusterdefinition.yaml
  deploy/redis-demo-for-dynamic-switchover/templates/clusterversion.yaml
  deploy/redis-demo-for-dynamic-switchover/templates/configconstraint-sentinel.yaml
  deploy/redis-demo-for-dynamic-switchover/templates/configconstraint.yaml
  deploy/redis-demo-for-dynamic-switchover/templates/configmap.yaml
  deploy/redis-demo-for-dynamic-switchover/templates/scripts.yaml
  deploy/redis-demo-for-dynamic-switchover/values.yaml
Labels: approved, size/XXL

#4859 chore: set goreleaser prerelease true
  .goreleaser.yaml
Labels: release, approved, size/XS

#4863 docs: fix invalid links
  docs/user_docs/backup-and-restore/backup-repo.md
  docs/user_docs/fault_injection/aws-fault.md
  docs/user_docs/fault_injection/dns-faults.md
  docs/user_docs/fault_injection/gcp-fault.md
  docs/user_docs/fault_injection/prerequisite.md
  docs/user_docs/fault_injection/time-fault.md
  docs/user_docs/kubeblocks-for-kafka/cluster-management/connect-to-a-cluster.md
  docs/user_docs/kubeblocks-for-kafka/cluster-management/create-a-kafka-cluster.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/switchover.md
  docs/user_docs/kubeblocks-for-mongodb/migration/migration-kbcli.md
  docs/user_docs/kubeblocks-for-mysql/cluster-management/create-and-connect-a-mysql-cluster.md
  docs/user_docs/kubeblocks-for-mysql/cluster-management/scale-for-apecloud-mysql.md
  docs/user_docs/kubeblocks-for-mysql/configuration/configuration.md
  docs/user_docs/kubeblocks-for-mysql/high-availability/high-availability.md
  docs/user_docs/kubeblocks-for-mysql/migration/migration-aws-dms.md
  docs/user_docs/kubeblocks-for-mysql/migration/migration-kbcli.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/create-and-connect-a-postgresql-cluster.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/switchover.md
  docs/user_docs/kubeblocks-for-postgresql/configuration/configuration.md
  docs/user_docs/kubeblocks-for-postgresql/high-availability/high-availability.md
  docs/user_docs/kubeblocks-for-postgresql/migration/migration_postgresql.md
  docs/user_docs/kubeblocks-for-redis/cluster-management/create-and-connect-a-redis-cluster.md
  docs/user_docs/kubeblocks-for-redis/cluster-management/scale-for-a-redis-cluster.md
  docs/user_docs/kubeblocks-for-redis/configuration/configuration.md
  docs/user_docs/kubeblocks-for-redis/high-availability/high-availability.md
  docs/user_docs/kubeblocks-for-vector-database/chatgpt-retrieval-plugin-with-kubeblocks.md
  docs/user_docs/observability/access-logs.md
  docs/user_docs/playground/try-kubeblocks-on-cloud.md
  docs/user_docs/playground/try-kubeblocks-on-your-laptop.md
  docs/user_docs/quick-start/try-kubeblocks-on-cloud.md
Labels: documentation, enhancement, size/L

#4812 chore: support all configuration file update (#4809)
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/opsrequest_webhook.go
  apis/apps/v1alpha1/opsrequest_webhook_test.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/reconfigure_util.go
  controllers/apps/operations/reconfigure_util_test.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/user_docs/cli/kbcli_cluster_configure.md
  docs/user_docs/cli/kbcli_cluster_edit-config.md
  internal/cli/cmd/cluster/config_edit.go
  internal/cli/cmd/cluster/config_observer.go
  internal/cli/cmd/cluster/config_ops.go
  internal/cli/cmd/cluster/config_resource.go
  internal/cli/cmd/cluster/config_util.go
  internal/cli/cmd/cluster/config_wrapper.go
  internal/cli/cmd/cluster/operations.go
  internal/cli/create/template/cluster_operations_template.cue
Labels: area/configuration, area/user-interaction, approved, size/L

#4868 docs: fix build errors
  docs/user_docs/fault_injection/prerequisite.md
  docs/user_docs/kubeblocks-for-vector-database/chatgpt-retrieval-plugin-with-kubeblocks.md
  docs/user_docs/observability/access-logs.md
  docs/user_docs/try-out-on-cloud/try-kubeblocks-on-cloud.md
Labels: documentation, enhancement, size/XL

#4865 fix: access namespaced resources with in-namespace option
  controllers/apps/components/base_stateful_hscale.go
  controllers/apps/components/consensus_set_utils.go
  controllers/apps/components/utils.go
  controllers/dataprotection/backup_controller.go
Labels: enhancement, size/S

#4870 docs: fix format errors
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
  docs/user_docs/kubeblocks-for-mongodb/migration/migration-kbcli.md
  docs/user_docs/kubeblocks-for-mysql/migration/migration-aws-dms.md
  docs/user_docs/kubeblocks-for-mysql/migration/migration-kbcli.md
  docs/user_docs/kubeblocks-for-mysql/proxy/apecloud-mysql-proxy.md
  docs/user_docs/kubeblocks-for-postgresql/migration/migration-postgresql.md
  docs/user_docs/kubeblocks-for-redis/cluster-management/create-and-connect-a-redis-cluster.md
Labels: documentation, enhancement, size/S

#4839 fix: stop exposing internal port of wesql-scale
  deploy/apecloud-mysql/templates/clusterdefinition.yaml
Labels: enhancement, size/S

#4853 chore: remove useless scripts for mongodb
  deploy/mongodb/templates/scriptstemplate.yaml
Labels: size/S

#4662 chore: support neon database
  deploy/helm/templates/addons/neon-addon.yaml
  deploy/neon-cluster/Chart.yaml
  deploy/neon-cluster/scripts/compute.sh
  deploy/neon-cluster/scripts/entrypoint.sh
  deploy/neon-cluster/scripts/spec.json
  deploy/neon-cluster/scripts/spec_prep_docker.json
  deploy/neon-cluster/templates/NOTES.txt
  deploy/neon-cluster/templates/_helpers.tpl
  deploy/neon-cluster/templates/cluster.yaml
  deploy/neon-cluster/templates/vm-compute-node-deploy.yaml
  deploy/neon-cluster/values.yaml
  deploy/neon/Chart.yaml
  deploy/neon/crds/multus.yaml
  deploy/neon/crds/neonvm-crd.yaml
  deploy/neon/neonvm/.helmignore
  deploy/neon/neonvm/Chart.yaml
  deploy/neon/neonvm/templates/neonvm.yaml
  deploy/neon/neonvm/values.yaml
  deploy/neon/templates/NOTES.txt
  deploy/neon/templates/_helpers.tpl
  deploy/neon/templates/autoscale-scheduler.yaml
  deploy/neon/templates/autoscaler-agent.yaml
  deploy/neon/templates/clusterdefinition.yaml
  deploy/neon/templates/clusterversion.yaml
  deploy/neon/templates/neonvm-deploy.yaml
  deploy/neon/templates/whereabouts.yaml
  deploy/neon/values.yaml
Labels: size/XXL

#4875 refactor: do object merging in build phase
  controllers/apps/components/base_stateful.go
  internal/controller/builder/builder.go
  internal/controller/rsm/plan_builder.go
  internal/controller/rsm/transformer_object_generation.go
Labels: refactor, size/L, rsm

#4414 feat: sqlchannel add apepg
  cmd/probe/internal/binding/postgres/postgres.go
  cmd/probe/internal/component/dbmanager.go
  cmd/probe/internal/component/mysql/manager.go
  cmd/probe/internal/component/mysql/wesql_manager.go
  cmd/probe/internal/component/postgres/apecloudpostgres/manager.go
  cmd/probe/internal/component/postgres/apecloudpostgres/manager_test.go
  cmd/probe/internal/component/postgres/config.go
  cmd/probe/internal/component/postgres/config_test.go
  cmd/probe/internal/component/postgres/manager.go
  cmd/probe/internal/component/postgres/manager_test.go
  cmd/probe/internal/component/postgres/officalpostgres/manager.go
  cmd/probe/internal/component/postgres/officalpostgres/manager_test.go
  cmd/probe/internal/component/postgres/query.go
  cmd/probe/internal/component/postgres/query_test.go
  cmd/probe/internal/component/postgres/types.go
  cmd/probe/internal/component/postgres/types_test.go
  cmd/probe/internal/dcs/k8s.go
  cmd/probe/internal/dcs/types.go
  cmd/probe/internal/highavailability/ha.go
  cmd/probe/internal/util.go
  deploy/apecloud-postgresql-cluster/.helmignore
  deploy/apecloud-postgresql-cluster/Chart.yaml
  deploy/apecloud-postgresql-cluster/templates/NOTES.txt
  deploy/apecloud-postgresql-cluster/templates/_helpers.tpl
  deploy/apecloud-postgresql-cluster/templates/cluster.yaml
  deploy/apecloud-postgresql-cluster/templates/rbac.yaml
  deploy/apecloud-postgresql-cluster/templates/validate.yaml
  deploy/apecloud-postgresql-cluster/values.schema.json
  deploy/apecloud-postgresql-cluster/values.yaml
  deploy/apecloud-postgresql/.helmignore
  deploy/apecloud-postgresql/Chart.yaml
  deploy/apecloud-postgresql/config/pg12-config-constraint.cue
  deploy/apecloud-postgresql/config/pg12-config.tpl
  deploy/apecloud-postgresql/templates/_helpers.tpl
  deploy/apecloud-postgresql/templates/class.yaml
  deploy/apecloud-postgresql/templates/clusterdefinition.yaml
  deploy/apecloud-postgresql/templates/clusterversion.yaml
  deploy/apecloud-postgresql/templates/configconstraint.yaml
  deploy/apecloud-postgresql/templates/configmap.yaml
  deploy/apecloud-postgresql/templates/scripts.yaml
  deploy/apecloud-postgresql/values.yaml
  go.mod
  go.sum
Labels: feature, approved, size/XXL

#4872 fix: keep reconciling after deletion with DoNotTerminate policy
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/cluster_types_test.go
  apis/apps/v1alpha1/cluster_webhook.go
  apis/apps/v1alpha1/opsrequest_webhook_test.go
  controllers/apps/transformer_cluster_credential.go
  controllers/apps/transformer_cluster_status.go
  controllers/apps/transformer_component.go
  controllers/apps/transformer_init.go
  controllers/apps/transformer_validate_and_load_ref_resources.go
  controllers/apps/transformer_validate_enable_logs.go
Labels: enhancement, ci, size/M

#4834 feat: lorry support join and leave member
  cmd/probe/cli/switchover.go
  cmd/probe/internal/binding/base.go
  cmd/probe/internal/binding/mysql/mysql.go
  cmd/probe/internal/binding/mysql/mysql_test.go
  cmd/probe/internal/util.go
  internal/sqlchannel/client.go
  internal/sqlchannel/client_test.go
  internal/sqlchannel/util/types.go
Labels: feature, approved, size/L

#4878 chore: add label for crds
  Makefile
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_clusterversions.yaml
  config/crd/bases/apps.kubeblocks.io_componentclassdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_componentresourceconstraints.yaml
  config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuprepos.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuptools.yaml
  config/crd/bases/dataprotection.kubeblocks.io_restorejobs.yaml
  config/crd/bases/extensions.kubeblocks.io_addons.yaml
  config/crd/bases/storage.kubeblocks.io_storageproviders.yaml
  config/crd/bases/workloads.kubeblocks.io_replicatedstatemachines.yaml
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterversions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentclassdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentresourceconstraints.yaml
  deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuprepos.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuptools.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_restorejobs.yaml
  deploy/helm/crds/extensions.kubeblocks.io_addons.yaml
  deploy/helm/crds/storage.kubeblocks.io_storageproviders.yaml
  deploy/helm/crds/workloads.kubeblocks.io_replicatedstatemachines.yaml
  docs/user_docs/api-reference/cluster.md
Labels: approved, size/L

#4861 fix: not create clusterrolebinding when volumeprotection is disabled
  controllers/apps/transformer_rbac.go
  controllers/apps/transformer_rbac_test.go
  internal/controller/component/component_test.go
  internal/controller/plan/prepare_test.go
  internal/testutil/apps/constant.go
Labels: enhancement, approved, size/L

#4887 chore: support e2e test on gke
  .github/workflows/e2e-kbcli.yml
Labels: test, approved, size/M

#4889 chore: fix typo
  .github/workflows/e2e-kbcli.yml
Labels: enhancement, approved, size/XS

#4890 docs: readme link 404
  README.md
Labels: documentation, size/XS

#4880 chore: fix doc typos
  docs/user_docs/installation/install-with-helm/install-kubeblocks-with-helm.md
Labels: documentation, enhancement, approved, size/XS
