Repository apecloud/kubeblocks, pull requests merged in 2024-01, with the labels that each got.

#6293 chore: fix the generation annotation of RSM was updated unexpectedly
  controllers/apps/transformer_component_workload.go
  pkg/controller/component/rsm_convertor.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/factory/builder.go
Labels: enhancement, approved, size/M

#6295 chore: opengauss command register
  pkg/lorry/engines/models/engine_types.go
  pkg/lorry/engines/register/managers.go
Labels: size/XS

#6298 fix: delete StatefulSetWorkload in SynthesizedComponent
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
Labels: enhancement, size/S

#6296 chore: support oracle connect
  pkg/lorry/engines/models/engine_types.go
  pkg/lorry/engines/oracle/commands.go
  pkg/lorry/engines/oracle/commands_test.go
  pkg/lorry/engines/oracle/suite_test.go
  pkg/lorry/engines/register/managers.go
Labels: size/L

#6299 chore: fix update tools image test random fail
  controllers/apps/component_controller_test.go
Labels: test, enhancement, approved, size/M

#6302 chore: set cd/cv controller concurrency as default
  controllers/apps/clusterdefinition_controller.go
  controllers/apps/clusterversion_controller.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/const.go
  pkg/constant/const.go
Labels: approved, size/M

#6261 chore: refine the resources watched by cluster controller
  controllers/apps/cluster_controller.go
Labels: approved, size/M

#6303 chore: add version label for application addon CRs
  deploy/helm/templates/applications/alertmanager-webhook-adaptor-addon.yaml
  deploy/helm/templates/applications/apecloud-otel-collector-addon.yaml
  deploy/helm/templates/applications/aws-loadbalancer-controller-addon.yaml
  deploy/helm/templates/applications/bytebase-addon.yaml
  deploy/helm/templates/applications/cert-manager-addon.yaml
  deploy/helm/templates/applications/chaos-mesh-addon.yaml
  deploy/helm/templates/applications/csi-driver-addon.yaml
  deploy/helm/templates/applications/csi-driver-nfs-addon.yaml
  deploy/helm/templates/applications/csi-hostpath-driver-addon.yaml
  deploy/helm/templates/applications/csi-s3-addon.yaml
  deploy/helm/templates/applications/external-dns-addon.yaml
  deploy/helm/templates/applications/grafana-addon.yaml
  deploy/helm/templates/applications/jupyter-notebook-addon.yaml
  deploy/helm/templates/applications/jupyterhub-addon.yaml
  deploy/helm/templates/applications/kubebench-addon.yaml
  deploy/helm/templates/applications/loki-addon.yaml
  deploy/helm/templates/applications/migration-addon.yaml
  deploy/helm/templates/applications/minio.yaml
  deploy/helm/templates/applications/nvidia-gpu-exporter-addon.yaml
  deploy/helm/templates/applications/nyancat-addon.yaml
  deploy/helm/templates/applications/prometheus-addon.yaml
  deploy/helm/templates/applications/pyroscope-addon.yaml
  deploy/helm/templates/applications/snapshot-controller-addon.yaml
  deploy/helm/templates/applications/vmagent-addon.yaml
Labels: size/M

#6308 chore: fix manifest check
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
Labels: enhancement, size/S

#6306 chore: upgrade envtest to 1.26.1 to fix the k8s API validation error
  Makefile
Labels: test, enhancement, approved, size/XS

#6307 chore: fix update tools image test random fail
  controllers/apps/component_controller_test.go
Labels: test, enhancement, size/S

#6314 chore: reduce csi-s3 memory usage
  deploy/helm/templates/storageprovider/cos.yaml
  deploy/helm/templates/storageprovider/gcs-s3comp.yaml
  deploy/helm/templates/storageprovider/minio.yaml
  deploy/helm/templates/storageprovider/obs.yaml
  deploy/helm/templates/storageprovider/oss.yaml
  deploy/helm/templates/storageprovider/s3.yaml
Labels: size/S

#6276 feat: support rerender for configuration-related updated (#6273)
  apis/apps/v1alpha1/configuration_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  controllers/apps/transformer_component_tls.go
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
  pkg/constant/payload.go
  pkg/controllerutil/config_util.go
  pkg/controllerutil/config_util_test.go
Labels: area/user-interaction, feature, approved, size/L

#6309 chore: update datasafed to 0.0.6
  deploy/helm/values.yaml
Labels: size/XS

#6315 fix: the status of cluster is Abnormal at creating
  controllers/apps/component_controller_test.go
  controllers/apps/transformer_cluster_status.go
Labels: enhancement, approved, size/M

#6313 chore: limit the nvidia-gpu-exporter only available on the EKS
  deploy/helm/templates/applications/nvidia-gpu-exporter-addon.yaml
Labels: approved, size/XS

#6311 chore: use rsm env configmap to inject env, avoiding to update pod spec
  controllers/apps/transformer_component_host_port.go
  pkg/controller/component/lorry_utils.go
  pkg/controller/rsm/transformer_object_generation.go
  pkg/controller/rsm/transformer_objection_generation_test.go
  pkg/controllerutil/pod_utils.go
Labels: size/L

#6287 chore: refactor cluster and component service api
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/cluster_controller_test.go
  controllers/apps/transformer_cluster_service.go
  controllers/apps/transformer_component_service.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  pkg/constant/const.go
  pkg/controller/builder/builder_component_definition.go
  pkg/controller/component/component_definition_convertor.go
  pkg/controller/component/component_definition_convertor_test.go
  pkg/controller/component/type.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
  pkg/testutil/apps/cluster_factory.go
  pkg/testutil/apps/componentdefinition_factory.go
  pkg/testutil/apps/constant.go
Labels: refactor, approved, size/XL

#6318 fix: keep lorry spec unchanged when upgrading from 0.7 to 0.8
  controllers/apps/component_utils.go
  controllers/apps/transformer_component_workload.go
  pkg/controller/rsm/transformer_object_generation.go
  pkg/lorry/client/httpclient.go
  pkg/lorry/ctl/switchover.go
Labels: enhancement, size/M

#6263 chore: replace roclient with reader
  controllers/apps/cluster_plan_builder.go
  controllers/apps/component_plan_builder.go
  controllers/apps/transform_types.go
  controllers/apps/transformer_component_tls.go
  pkg/controller/client/readonly_client.go
  pkg/controller/component/service_descriptor_utils.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/workload_utils.go
  pkg/controller/configuration/config_template.go
  pkg/controller/graph/transformer.go
  pkg/controller/model/transform_utils_test.go
  pkg/controller/plan/tls_utils.go
  pkg/controller/rsm/types.go
  pkg/controller/rsm/utils.go
  pkg/controllerutil/volumesnapshot.go
  pkg/gotemplate/tpl_engine.go
Labels: approved, size/L

#6301 chore: remove useless fields and labels
  pkg/constant/const.go
  pkg/controller/component/lorry_utils_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/rsm/transformer_object_generation.go
Labels: approved, size/M

#6316 chore: remove deprecated cluster status
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/cluster_types_test.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  controllers/apps/component_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
Labels: approved, size/L

#6324 fix: kb crash when inject probe
  pkg/controller/rsm/transformer_object_generation.go
Labels: enhancement, size/S

#6264 feat: support oceanbase failover
  controllers/apps/component_controller_test.go
  controllers/apps/transformer_component_workload.go
  pkg/lorry/client/client.go
  pkg/lorry/client/client_mock.go
  pkg/lorry/client/httpclient_test.go
  pkg/lorry/client/interface.go
  pkg/lorry/ctl/switchover.go
  pkg/lorry/engines/oceanbase/failover.go
  pkg/lorry/engines/oceanbase/switchover.go
  pkg/lorry/operations/replica/switchover.go
  pkg/lorry/operations/types.go
Labels: feature, approved, size/L

#5068 chore: improve the readability of probe's README.md
  pkg/lorry/README.md
Labels: documentation, size/S

#6327 chore: rsm use exec role probe by default
  pkg/controller/rsm/transformer_object_generation.go
  pkg/controller/rsm/transformer_objection_generation_test.go
Labels: size/M

#6323 fix: keep env vars order to be compatible with existed cluster
  apis/apps/v1alpha1/type.go
  controllers/apps/component_controller_test.go
  controllers/apps/transformer_component_load_resources.go
  controllers/apps/transformer_component_vars.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
  pkg/controller/factory/builder_test.go
Labels: feature, enhancement, size/XL

#6330 chore: improve rsm role probe compatibility for upgrading
  pkg/controller/rsm/transformer_object_generation.go
Labels: size/S

#6317 chore: support podSelection Strategy "All"
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/gc_controller_test.go
  controllers/dataprotection/utils.go
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/backup/request_test.go
  pkg/dataprotection/backup/utils.go
Labels: approved, size/L

#6325 chore: refactor expose operation request api
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/expose.go
  controllers/apps/operations/expose_test.go
  controllers/apps/transformer_cluster_service.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
Labels: refactor, size/XL

#6334 docs: update slack link
  README.md
Labels: documentation, size/XS

#6332 fix: be compatible about service account name and config-manager sidecar env
  controllers/apps/transformer_component_vars.go
  pkg/constant/pattern.go
  pkg/controller/component/component.go
  pkg/controller/component/type.go
  pkg/controller/component/vars.go
  pkg/controller/configuration/config_utils.go
  pkg/controller/factory/builder_test.go
Labels: enhancement, size/L

#6333 fix: remove the host ports configmap when uninstall the kubeblocks
  cmd/manager/main.go
  controllers/apps/suite_test.go
  deploy/helm/templates/configmap.yaml
  deploy/helm/templates/deployment.yaml
  pkg/constant/const.go
  pkg/controllerutil/controller_common.go
Labels: enhancement, approved, size/M

#6329 chore: update addon version and reduce built-in addons
  deploy/helm/templates/addons/apecloud-mysql-addon.yaml
  deploy/helm/templates/addons/greptimedb-addon.yaml
  deploy/helm/templates/addons/influxdb-addon.yaml
  deploy/helm/templates/addons/mariadb-addon.yaml
  deploy/helm/templates/addons/nebula-addon.yaml
  deploy/helm/templates/addons/neon-addon.yaml
  deploy/helm/templates/addons/oracle-mysql-addon.yaml
  deploy/helm/templates/addons/orioledb-addon.yaml
  deploy/helm/templates/addons/redis-addon.yaml
  deploy/helm/templates/addons/risingwave-addon.yaml
  deploy/helm/templates/addons/starrocks-addon.yaml
  deploy/helm/templates/addons/tdengine-addon.yaml
  deploy/helm/templates/addons/tidb-addon.yaml
  deploy/helm/templates/addons/zookeeper-addon.yaml
  deploy/helm/templates/pre-delete-addon-job.yaml
Labels: size/L

#6337 chore: improve opsDefinition to support switchover by lorry
  apis/apps/v1alpha1/opsdefinition_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsdefinitions.yaml
  controllers/apps/operations/custom.go
  deploy/helm/crds/apps.kubeblocks.io_opsdefinitions.yaml
  deploy/helm/opsdefinitions/switchover.yaml
  deploy/helm/templates/opsdefinition.yaml
  pkg/common/env_resolve.go
Labels: size/XL

#6339 fix: label selector for pod affinity and topology spread constraint
  pkg/controller/component/affinity_utils.go
Labels: enhancement, size/XS

#6336 fix: set default update strategy for RSM
  pkg/controller/component/rsm_convertor.go
Labels: enhancement, size/M

#6335 chore: fix rsm updateStrategy is empty after an upgrade
  controllers/apps/transformer_component_workload.go
Labels: test, enhancement, approved, size/XS

#6341 fix: pass the existed component service to RSM
  controllers/apps/transformer_cluster_service.go
  controllers/apps/transformer_component_service.go
  controllers/apps/transformer_component_workload.go
Labels: enhancement, size/M

#6347 chore: update switchover param
  deploy/helm/opsdefinitions/switchover.yaml
Labels: approved, size/S

#6349 fix: backup can not find service account name
  controllers/apps/operations/custom.go
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/apps/transformer_component_rbac.go
  pkg/constant/pattern.go
  pkg/controller/component/synthesize_component.go
Labels: enhancement, approved, size/S

#6353 chore: Revert "fix: set default update strategy for RSM"
  pkg/controller/component/rsm_convertor.go
Labels: enhancement, approved, size/M

#6352 chore: auto upgrade addons version
  .github/workflows/release-version.yml
Labels: approved, size/M

#6354 fix: sts annotations were lost when merging
  pkg/controller/rsm/transformer_object_generation.go
Labels: enhancement, approved, size/S

#6265 chore: helper functions to support running with multiple k8s clusters
  cmd/manager/main.go
  controllers/apps/cluster_controller.go
  controllers/apps/cluster_plan_builder.go
  controllers/apps/cluster_plan_builder_test.go
  controllers/apps/component_controller.go
  controllers/apps/component_plan_builder.go
  controllers/apps/component_plan_builder_test.go
  controllers/apps/transformer_cluster_ownership.go
  controllers/apps/transformer_component_ownership.go
  controllers/apps/transformer_component_workload.go
  controllers/apps/transformer_secret.go
  controllers/apps/utils.go
  pkg/constant/const.go
  pkg/controller/component/component_post_provision.go
  pkg/controller/model/graph_client.go
  pkg/controller/model/graph_client_test.go
  pkg/controller/model/graph_options.go
  pkg/controller/model/transform_types.go
  pkg/controller/multicluster/client.go
  pkg/controller/multicluster/manager.go
  pkg/controller/multicluster/options.go
  pkg/controller/multicluster/placement.go
  pkg/controller/multicluster/setup.go
  pkg/controller/rsm/plan_builder.go
  pkg/controller/rsm/utils.go
Labels: approved, size/XXL

#6356 chore: delete needs release kbcli
  .github/workflows/release-version.yml
Labels: release, approved, size/XS

#6102 chore: pass credential vars through valueFrom
  controllers/apps/component_controller_test.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: approved, size/L

#6355 chore: keep rsm role probe spec unchange when cluster has no modifications
  controllers/apps/component_utils.go
  controllers/apps/component_utils_test.go
  controllers/apps/transformer_component_workload.go
  pkg/controller/rsm/transformer_object_generation.go
  pkg/controllerutil/pod_utils.go
Labels: size/L

#6362 fix: keep compatible for update strategy, SA name and access mode
  controllers/apps/transformer_component_rbac.go
  pkg/constant/pattern.go
  pkg/controller/component/component.go
  pkg/controller/component/component_definition_convertor.go
  pkg/controller/component/component_definition_convertor_test.go
  pkg/controller/component/rsm_convertor.go
  pkg/controller/factory/builder_test.go
Labels: enhancement, approved, size/M

#6350 chore: add cluster validation of componentDefRef and componentDef
  apis/apps/v1alpha1/cluster_types.go
  controllers/apps/transformer_cluster_api_normalization.go
  pkg/constant/const.go
  pkg/constant/pattern.go
  pkg/controller/component/component.go
Labels: size/M

#6365 fix: serial update strategy for replication workloads
  pkg/controller/component/component_definition_convertor.go
Labels: enhancement, size/XS

#6370 chore: postProvision action support inject envFrom vars
  controllers/apps/transformer_component_service.go
  pkg/controller/component/component_post_provision.go
  pkg/controller/component/vars.go
Labels: size/M

#6361 chore: support delete action for backup
  apis/dataprotection/v1alpha1/actionset_types.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/dataprotection.kubeblocks.io_actionsets.yaml
  controllers/apps/component_controller_test.go
  controllers/dataprotection/backup_controller_test.go
  deploy/helm/crds/dataprotection.kubeblocks.io_actionsets.yaml
  deploy/helm/opsdefinitions/switchover.yaml
  pkg/dataprotection/backup/deleter.go
  pkg/dataprotection/backup/deleter_test.go
Labels: size/L

#6376 fix: parallel expose failed
  controllers/apps/operations/expose.go
Labels: enhancement, approved, size/XS

#6382 fix: component account provision skip initAccount
  controllers/apps/component_controller_test.go
  controllers/apps/transformer_component_account_provision.go
Labels: enhancement, approved, size/XS

#6385 chore: fix upload jihu chart rate limit
  .github/workflows/release-helm-chart.yml
  docker/custom-scripts/fetch-all-helm-charts.sh
Labels: enhancement, approved, size/M

#6388 fix: set update strategy for RSM workloads
  pkg/controller/component/component_definition_convertor.go
Labels: enhancement, approved, size/XS

#6373 chore: change base image of kubeblocks-csi-driver addon to alpine
  deploy/helm/templates/applications/csi-driver-addon.yaml
Labels: size/XS

#6391 chore: change base image of kubeblocks-csi-driver addon to alpine
  deploy/helm/templates/applications/csi-driver-addon.yaml
Labels: size/XS

#6389 feat: integrate with Kopia for database backup
  apis/dataprotection/v1alpha1/backup_types.go
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  deploy/helm/values.yaml
  pkg/dataprotection/backup/deleter.go
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/backup/utils.go
  pkg/dataprotection/restore/builder.go
  pkg/dataprotection/restore/utils.go
  pkg/dataprotection/types/constant.go
  pkg/dataprotection/utils/backuprepo.go
Labels: area/user-interaction, feature, size/L

#6387 feat: rsm custom handler command support args params
  apis/apps/v1alpha1/clusterdefinition_webhook_test.go
  apis/workloads/v1alpha1/replicatedstatemachine_types.go
  apis/workloads/v1alpha1/replicatedstatemachine_webhook_test.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/workloads.kubeblocks.io_replicatedstatemachines.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/workloads.kubeblocks.io_replicatedstatemachines.yaml
  pkg/controller/component/component_definition_convertor.go
  pkg/controller/component/component_definition_convertor_test.go
  pkg/controller/component/rsm_convertor.go
  pkg/controller/component/rsm_convertor_test.go
  pkg/controller/rsm/utils.go
  pkg/controller/rsm/utils_test.go
Labels: feature, size/L

#6368 docs: fix link
  docs/developer_docs/integration/how-to-add-an-add-on.md
  i18n/zh-cn/developer-docs/api-reference/add-on.md
  i18n/zh-cn/developer-docs/api-reference/backup.md
  i18n/zh-cn/developer-docs/api-reference/cluster.md
  i18n/zh-cn/developer-docs/overview.md
Labels: documentation, enhancement, approved, size/XXL

#6396 docs: fix link
  docs/developer_docs/external-component/_category_.yml
  docs/developer_docs/overview.md
  docs/user_docs/kubeblocks-for-kafka/cluster-management/connect-to-a-cluster.md
  i18n/zh-cn/developer-docs/integration/how-to-add-an-add-on.md
  i18n/zh-cn/developer-docs/overview.md
  i18n/zh-cn/user-docs/kubeblocks-for-kafka/cluster-management/connect-to-a-cluster.md
Labels: documentation, enhancement, size/M

#6398 chore: sync annotations of the backupSchedule failed
  controllers/apps/transformer_cluster_backup_policy.go
Labels: approved, size/XS

#6404 fix: parallel expose failed
  controllers/apps/operations/expose.go
Labels: enhancement, approved, size/XS

#6402 docs: adjust blankspace
  docs/developer_docs/external-component/reference-external-component.md
  docs/developer_docs/integration/how-to-add-an-add-on.md
  docs/user_docs/kubeblocks-for-kafka/cluster-management/connect-to-a-cluster.md
  i18n/zh-cn/developer-docs/integration/how-to-add-an-add-on.md
  i18n/zh-cn/user-docs/kubeblocks-for-kafka/cluster-management/connect-to-a-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql/cluster-management/create-and-connect-a-mysql-cluster.md
Labels: documentation, size/M

#6407 docs: adjust cn dev docs
  i18n/zh-cn/developer-docs/api-reference/add-on.md
  i18n/zh-cn/developer-docs/api-reference/backup.md
  i18n/zh-cn/developer-docs/api-reference/cluster.md
  i18n/zh-cn/developer-docs/fault_injection/time-fault.md
  i18n/zh-cn/developer-docs/integration/_category_.yml
  i18n/zh-cn/developer-docs/integration/backup-and-restore.md
  i18n/zh-cn/developer-docs/integration/how-to-add-an-add-on.md
  i18n/zh-cn/developer-docs/integration/monitoring.md
  i18n/zh-cn/developer-docs/integration/multi-component.md
  i18n/zh-cn/developer-docs/integration/parameter-configuration.md
  i18n/zh-cn/developer-docs/integration/parameter-template.md
  i18n/zh-cn/developer-docs/overview.md
Labels: documentation, size/XXL

#6408 chore: remove hacky compDefName in synthesizedComp
  pkg/controller/component/synthesize_component.go
  pkg/controller/factory/builder.go
Labels: approved, size/S

#6405 chore: don't pass default credential if not needed
  pkg/controller/component/rsm_convertor.go
Labels: approved, size/S

#6409 chore: refine default vars provided by KB
  apis/apps/v1alpha1/type.go
Labels: approved, size/S

#6411 fix: restore pg failed with componentDefinition api
  controllers/apps/transformer_component_account.go
Labels: enhancement, size/S

#6415 fix: create job failed with no this sa for custom ops
  controllers/apps/operations/custom.go
Labels: enhancement, approved, size/S

#6410 chore: keep env vars compatible only with existing clusters
  controllers/apps/component_controller_test.go
  controllers/apps/transformer_component_vars.go
  pkg/controller/component/vars.go
Labels: approved, size/M

#6417 chore: update built-in addons version
  deploy/helm/templates/addons/clickhouse-addon.yaml
  deploy/helm/templates/addons/weaviate-addon.yaml
Labels: size/XS

#6414 fix: delete statefulset when deleting clusters
  controllers/apps/transformer_cluster_deletion.go
Labels: enhancement, size/XS

#6418 chore: set ck addon autoInstall to true
  deploy/helm/templates/addons/clickhouse-addon.yaml
Labels: size/XS

#6420 chore: compatible 0.7 api for actionSet
  apis/dataprotection/v1alpha1/actionset_types.go
  config/crd/bases/dataprotection.kubeblocks.io_actionsets.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_actionsets.yaml
Labels: approved, size/XS

#6421 chore: keep the FQDN env var format for existing clusters
  pkg/controller/component/vars.go
Labels: size/S

#6423 fix: switchover failed
  controllers/apps/operations/custom.go
Labels: enhancement, approved, size/M

#6416 feat: support autoTrigger
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/configconstraint_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
  controllers/apps/transformer_cluster_credential.go
  controllers/apps/transformer_component_host_port.go
  deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
  pkg/configuration/config_manager/builder_test.go
  pkg/configuration/config_manager/handler_util.go
  pkg/configuration/config_manager/handler_util_test.go
  pkg/controller/rsm/transformer_pod_generation.go
  pkg/lorry/engines/oceanbase/get_replica_role_test.go
Labels: area/user-interaction, feature, size/L

#6424 fix: mysql switchover failed
  apis/apps/v1alpha1/opsdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_opsdefinitions.yaml
  controllers/apps/operations/custom.go
  deploy/helm/crds/apps.kubeblocks.io_opsdefinitions.yaml
  deploy/helm/opsdefinitions/switchover.yaml
Labels: enhancement, approved, size/S

#6429 chore: fix switchover failed if no candidate specified
  deploy/helm/opsdefinitions/switchover.yaml
Labels: enhancement, ci, approved, size/XS

#6432 chore: do not disable enabled addons when upgrade
  deploy/helm/templates/_addon.tpl
  deploy/helm/templates/addons/apecloud-mysql-addon.yaml
  deploy/helm/templates/addons/milvus-addon.yaml
  deploy/helm/templates/addons/pulsar-addon.yaml
Labels: size/L

#6442 chore: fix enable archive to create many ops
  controllers/apps/transformer_cluster_backup_policy.go
Labels: enhancement, approved, size/XS

#6443 chore: fix expose ops consensus leader name
  controllers/apps/operations/expose.go
Labels: enhancement, size/XS

#6445 chore: add release note for v0.8.0
  docs/release_notes/v0.8.0/_category_.yml
  docs/release_notes/v0.8.0/v0.8.0.md
Labels: release, size/L

#6448 fix: zap flags not be added
  cmd/manager/main.go
Labels: enhancement, size/XS

#6447 doc: Update v0.8.0.md
  docs/release_notes/v0.8.0/v0.8.0.md
Labels: documentation, size/S

#6425 chore: refine simplified cluster API
  apis/apps/v1alpha1/cluster_types.go
  pkg/controller/apiconversion/simplified_cluster_api.go
  pkg/controller/component/affinity_utils.go
Labels: approved, size/M

#6426 chore: limit the use of two kinds definition API simultaneously
  apis/apps/v1alpha1/cluster_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
Labels: approved, size/XS

#6427 chore: remove PDB as it's not used since 0.7
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/cluster_types_test.go
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/clusterdefinition_types_test.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  controllers/apps/component_controller.go
  controllers/apps/configuration/reconfigure_policy.go
  controllers/apps/transformer_component_deletion.go
  controllers/apps/transformer_component_pdb.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  pkg/controller/builder/builder_daemon_set_test.go
  pkg/controller/builder/builder_deployment_test.go
  pkg/controller/builder/builder_pdb.go
  pkg/controller/builder/builder_pdb_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
  pkg/generics/type.go
Labels: approved, size/L

#5853 chore: support array field update (#5852)
  controllers/apps/operations/reconfigure_util.go
  pkg/configuration/core/config.go
  pkg/configuration/core/config_util.go
  pkg/unstructured/xml_config.go
  pkg/unstructured/xml_config_test.go
Labels: approved, size/M

#6444 chore: fix goconst lint error for golangci-lint version >= 1.54.2
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  apis/extensions/v1alpha1/zz_generated.deepcopy.go
  apis/storage/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  controllers/apps/operations/backup_test.go
  controllers/apps/operations/reconfigure_pipeline_test.go
  controllers/apps/transformer_component_rbac.go
  controllers/apps/transformer_component_rbac_test.go
  controllers/apps/transformer_component_status.go
  controllers/apps/transformer_component_workload.go
  controllers/dataprotection/backup_controller_test.go
  externalapis/preflight/v1beta2/zz_generated.deepcopy.go
  pkg/constant/const.go
  pkg/constant/pattern.go
  pkg/gotemplate/tpl_engine_test.go
  pkg/lorry/engines/mysql/manager.go
  pkg/lorry/engines/oceanbase/switchover.go
  pkg/lorry/engines/wesql/conn_test.go
Labels: enhancement, ci, size/M

#6441 chore: refactor developing docs
  README.md
  docs/00 - index.md
  docs/01 - build.md
  docs/02 - test.md
  docs/03 - debug.md
  docs/04 - basics.md
  docs/DEVELOPING.md
Labels: feature, documentation, refactor, approved, size/XL

#6456 chore: upgrade golangci lint version
  .github/workflows/cicd-pull-request.yml
  .github/workflows/release-version.yml
  Makefile
  docker/Dockerfile-dev
Labels: ci, approved, size/XS

#6458 chore: change workflow user to apecloud inc
  .github/workflows/cherry-pick.yml
  .github/workflows/merge-e2e-smoke.yml
  .github/workflows/pull-request-check.yml
Labels: approved, size/XS

#6461 fix: mongdb hscale down
  pkg/lorry/engines/mongodb/manager.go
Labels: enhancement, size/XS

#6459 chore: auto get addons dir list for release charts
  .github/workflows/release-helm-chart.yml
Labels: release, approved, size/M

#6464 fix: set default update strategy for RSM
  pkg/controller/component/rsm_convertor.go
Labels: enhancement, size/M

#6468 feat: support time zone for restore time
  .golangci.yaml
  apis/dataprotection/v1alpha1/backup_types.go
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  controllers/apps/operations/restore.go
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  pkg/dataprotection/backup/deleter.go
  pkg/dataprotection/restore/builder.go
  pkg/dataprotection/restore/manager_test.go
  pkg/dataprotection/restore/utils.go
  pkg/dataprotection/types/constant.go
  test/testdata/backup/actionset.yaml
Labels: feature, approved, size/L

#6467 chore: refine component API and cleanup unused fields
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_component_validation.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  pkg/controller/builder/builder_component.go
  pkg/controller/component/component.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/testutil/apps/component_factory.go
Labels: approved, size/M

#6476 fix: mysql replication initialization and failover
  controllers/apps/transformer_component_workload.go
  pkg/lorry/dcs/types.go
  pkg/lorry/engines/mysql/get_replica_role.go
  pkg/lorry/engines/mysql/manager.go
  pkg/lorry/engines/mysql/manager_test.go
  pkg/lorry/engines/mysql/util.go
  pkg/lorry/engines/postgres/officalpostgres/manager.go
  pkg/lorry/highavailability/ha.go
  pkg/lorry/httpserver/server.go
  pkg/lorry/operations/replica/checkrole.go
  pkg/lorry/operations/volume/protect.go
  pkg/lorry/operations/volume/protect_test.go
Labels: enhancement, approved, size/L

#6481 fix: invalid job name
  controllers/apps/operations/datascript.go
  controllers/dataprotection/backuprepo_controller.go
  pkg/dataprotection/backup/deleter.go
  pkg/dataprotection/backup/utils.go
Labels: enhancement, size/S

#6485 chore: add DP_TARGET_POD_ROLE env for backup
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/types/constant.go
Labels: approved, size/XS

#6491 docs: fix intro docs
  docs/developer_docs/integration/how-to-add-an-add-on.md
  docs/developer_docs/integration/monitoring.md
  docs/user_docs/overview/supported-addons.md
  i18n/zh-cn/developer-docs/fault_injection/dns-faults.md
  i18n/zh-cn/developer-docs/integration/backup-and-restore.md
  i18n/zh-cn/developer-docs/integration/how-to-add-an-add-on.md
  i18n/zh-cn/developer-docs/integration/monitoring.md
  i18n/zh-cn/developer-docs/integration/multi-component.md
  i18n/zh-cn/developer-docs/integration/parameter-configuration.md
  i18n/zh-cn/developer-docs/integration/parameter-template.md
  i18n/zh-cn/user-docs/kubeblocks-for-kafka/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-mysql/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-mysql/configuration/configuration.md
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-pulsar/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-redis/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-vector-database/_category_.yml
  i18n/zh-cn/user-docs/overview/database-engines-supported.md
Labels: documentation, enhancement, size/M

#6498 fix: mongodb leave member context deadline exceeded
  pkg/lorry/dcs/k8s.go
  pkg/lorry/engines/mongodb/manager.go
Labels: enhancement, approved, size/S

#6499 chore: hscale uses available backup method if volume snapshot is unsupported
  controllers/apps/component_hscale_volume_populator.go
Labels: approved, size/XS

#6501 chore: fix lorry log
  pkg/lorry/dcs/k8s.go
Labels: enhancement, approved, size/XS

#6465 fix: --zap-log-level not take effect
  cmd/manager/main.go
Labels: enhancement, size/S

#6508 chore: custom host port range
  cmd/manager/main.go
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  pkg/constant/const.go
  pkg/controllerutil/controller_common.go
Labels: size/L

#6510 chore: update postgresql addon version to 0.8.0
  deploy/helm/templates/addons/postgresql-addon.yaml
Labels: approved, size/XS

#6515 chore: skip check zh-cn dir
  .github/workflows/cicd-push.yml
Labels: approved, size/XS

#6496 docs: update 0.8 docs
  README.md
  docs/user_docs/installation/upgrade/upgrade-kubeblocks-to-0.7.md
  docs/user_docs/installation/upgrade/upgrade-kubeblocks-to-0.8.md
  docs/user_docs/overview/introduction.md
  i18n/zh-cn/user-docs/installation/upgrade/upgrade-kubeblocks-to-0.7.md
  i18n/zh-cn/user-docs/installation/upgrade/upgrade-kubeblocks-to-0.8.md
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/kubeblocks-for-mongodb.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql/kubeblocks-for-mysql.md
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/kubeblocks-for-postgresql.md
  i18n/zh-cn/user-docs/kubeblocks-for-pulsar/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-redis/kubeblocks-for-redis.md
Labels: documentation, approved, size/L

#6514 fix: allow comment symbols (\# and \;) inside value for ini format
  go.mod
  pkg/unstructured/viper_wrap.go
  pkg/unstructured/viper_wrap_test.go
Labels: enhancement, size/S

#6509 chore: custom host port range (#6508)
  cmd/manager/main.go
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  pkg/constant/const.go
  pkg/controllerutil/controller_common.go
Labels: approved, size/L

#6521 chore: refine lorry dns check
  pkg/lorry/dcs/k8s.go
  pkg/lorry/engines/mysql/manager.go
  pkg/lorry/engines/mysql/util.go
  pkg/lorry/highavailability/ha.go
  pkg/lorry/httpserver/apis.go
  pkg/lorry/util/ping.go
Labels: size/L

#6519 feat: support minReadySeconds api in componentDef
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/workloads/v1alpha1/replicatedstatemachine_types.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/workloads.kubeblocks.io_replicatedstatemachines.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/workloads.kubeblocks.io_replicatedstatemachines.yaml
  pkg/controller/builder/builder_replicated_state_machine.go
  pkg/controller/builder/builder_replicated_state_machine_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/factory/builder.go
  pkg/controller/rsm/transformer_object_generation.go
Labels: area/user-interaction, feature, size/M

#6524 chore: add reset master
  pkg/lorry/engines/mysql/manager.go
Labels: size/S

#6523 feat: support log collector to collect the pod logs when backup and restore are failed
  controllers/dataprotection/backupschedule_controller.go
  controllers/dataprotection/log_collection_controller.go
  controllers/dataprotection/log_collection_controller_test.go
  controllers/dataprotection/suite_test.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/utils.go
  pkg/dataprotection/types/constant.go
Labels: area/user-interaction, feature, size/L

#6525 chore: improve the owned check for data protection job
  controllers/dataprotection/log_collection_controller.go
Labels: approved, size/XS

#6527 docs: update backup and restore docs
  docs/user_docs/backup-and-restore/backup/on-demand-backup.md
  docs/user_docs/backup-and-restore/backup/scheduled-backup.md
  docs/user_docs/backup-and-restore/restore/restore-data-from-backup-set.md
  docs/user_docs/overview/supported-addons.md
  i18n/zh-cn/user-docs/backup-and-restore/backup/on-demand-backup.md
  i18n/zh-cn/user-docs/backup-and-restore/restore/restore-data-from-backup-set.md
  i18n/zh-cn/user-docs/overview/database-engines-supported.md
Labels: documentation, approved, size/L

#6533 chore: check availableReplicas of sts only if minReadySeconds is set
  controllers/apps/configuration/policy_util.go
  controllers/apps/transformer_component_status.go
  pkg/controller/rsm/transformer_status.go
  pkg/controller/rsm/utils.go
  pkg/controllerutil/stateful_set_utils.go
  pkg/controllerutil/stateful_set_utils_test.go
Labels: size/M

#6534 chore: disable the AvailableReplicas check for RSM ready
  pkg/controller/rsm/utils.go
  pkg/controllerutil/stateful_set_utils.go
  pkg/controllerutil/stateful_set_utils_test.go
Labels: size/M

#6536 fix: restore from backup failed after expose the service
  apis/apps/v1alpha1/opsrequest_types.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/restore.go
  controllers/apps/operations/restore_test.go
  controllers/apps/operations/suite_test.go
  controllers/apps/transformer_cluster_service.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
Labels: enhancement, approved, size/L

#6542 chore: test e2e on k3s 1.21
  .github/workflows/e2e-kbcli-k3s.yml
Labels: test, approved, size/XS

#6547 docs: add backup and restore workflow
  docs/user_docs/backup-and-restore/introduction.md
  i18n/zh-cn/user-docs/backup-and-restore/overview.md
Labels: documentation, size/M

#6554 chore: mark ComponentClassDefinition and ComponentResourceConstraint as deprecated
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/componentclassdefinition_types.go
  apis/apps/v1alpha1/componentresourceconstraint_types.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  apis/extensions/v1alpha1/zz_generated.deepcopy.go
  apis/storage/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentclassdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_componentresourceconstraints.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentclassdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentresourceconstraints.yaml
  externalapis/preflight/v1beta2/zz_generated.deepcopy.go
Labels: approved, size/M

#6545 feat: publish not ready addresses for default headless service
  pkg/controller/builder/builder_service.go
  pkg/controller/builder/builder_service_test.go
  pkg/controller/component/component_definition_convertor.go
  pkg/controller/rsm/transformer_object_generation.go
Labels: area/user-interaction, feature, approved, size/S

#6555 fix/KB_CLUSTER_UID env error
  pkg/controller/rsm/transformer_object_generation.go
  pkg/controller/rsm/transformer_objection_generation_test.go
Labels: enhancement, size/XS

#6557 fix: keep KB_CLUSTER_UID env
  .github/workflows/cherry-pick.yml
  .github/workflows/merge-e2e-smoke.yml
  .github/workflows/pull-request-check.yml
  .golangci.yaml
  pkg/constant/env.go
  pkg/controller/factory/builder.go
  pkg/controller/rsm/transformer_object_generation.go
Labels: bug, enhancement, size/S

#6558 docs: update 0.8 docs
  docs/user_docs/backup-and-restore/backup/backup-repo.md
  docs/user_docs/handle-an-exception/full-disk-lock.md
  docs/user_docs/kubeblocks-for-mysql/proxy/apecloud-mysql-proxy.md
  docs/user_docs/kubeblocks-for-pulsar/cluster-management/create-pulsar-cluster-on-kubeblocks.md
  i18n/zh-cn/user-docs/backup-and-restore/backup/backup-repo.md
  i18n/zh-cn/user-docs/handle-an-exception/full-disk-lock.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql/proxy/apecloud-mysql-proxy.md
  i18n/zh-cn/user-docs/kubeblocks-for-pulsar/cluster-management/create-pulsar-cluster-on-kb.md
Labels: documentation, size/M

#6548 chore: refine mysql semisync
  pkg/lorry/engines/mysql/get_replica_role.go
  pkg/lorry/engines/mysql/get_replica_role_test.go
  pkg/lorry/engines/mysql/manager.go
  pkg/lorry/engines/mysql/manager_test.go
  pkg/lorry/engines/mysql/semei_sync_test.go
  pkg/lorry/engines/mysql/semi_sync.go
Labels: size/XL

#6561 chore:refine lorry util
  apis/apps/v1alpha1/componentdefinition_types.go
  cmd/manager/main.go
  pkg/constant/const.go
  pkg/constant/env.go
  pkg/constant/lorry.go
  pkg/controller/component/lorry_utils.go
  pkg/controller/component/lorry_utils_test.go
  pkg/controller/component/synthesize_component.go
Labels: approved, size/L

#6564 chore: update redis query result parser
  pkg/lorry/engines/redis/query.go
Labels: size/S

#6567 fix: mysql role probe with two primaries
  pkg/lorry/engines/mysql/manager.go
  pkg/lorry/engines/mysql/semei_sync_test.go
  pkg/lorry/engines/mysql/semi_sync.go
Labels: enhancement, approved, size/XS

#6570 chore: can not update backupPolicy manually
  controllers/apps/transformer_cluster_backup_policy.go
Labels: approved, size/S
