Repository apecloud/kubeblocks, pull requests merged in 2024-06, with the labels that each got.

#7468 chore: using the actual service name to resolve service objects
  controllers/apps/operations/custom.go
  controllers/apps/operations/custom/utils.go
  controllers/apps/operations/expose.go
  controllers/apps/operations/switchover.go
  controllers/apps/operations/upgrade.go
  pkg/controller/component/component.go
  pkg/controller/component/service_descriptor_utils_test.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: approved, size/XXL

#7470 chore: using the actual service name to resolve service objects (#7468)
  controllers/apps/operations/custom.go
  controllers/apps/operations/custom/utils.go
  controllers/apps/operations/expose.go
  controllers/apps/operations/switchover.go
  controllers/apps/operations/upgrade.go
  pkg/controller/component/component.go
  pkg/controller/component/service_descriptor_utils_test.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: size/XXL

#7459 chore: support specifying the system account password through the cluster API
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/component_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_component.go
  pkg/controller/component/component.go
  pkg/controller/component/synthesize_component.go
  pkg/testutil/apps/cluster_factory.go
Labels: approved, size/XL

#7471 chore: support specifying the system account password through the cluster API
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/component_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_component.go
  pkg/controller/component/component.go
  pkg/controller/component/synthesize_component.go
  pkg/testutil/apps/cluster_factory.go
Labels: size/XL

#7475 fix: mongodb promote crash
  pkg/lorry/engines/mongodb/manager.go
Labels: approved, size/S

#7474 chore: all comps ready check with generation
  controllers/apps/component_controller_test.go
  controllers/apps/transformer_cluster_component.go
Labels: approved, size/S

#7290 refactor: reuse SchedulingPolicy struct for the scheduling policy definition of InstanceTemplate
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/instanceset_types.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  pkg/controller/component/its_convertor.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
Labels: area/user-interaction, size/XXL, pre-approve

#7480 chore: fix pre-approve run test
  .github/workflows/cicd-pull-request.yml
Labels: approved, size/XS

#7481 chore: Revert "refactor: reuse SchedulingPolicy struct for the scheduling policy definition of InstanceTemplate (#7290)"
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/instanceset_types.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  pkg/controller/component/rsm_convertor.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
Labels: size/XXL

#7478 fix: config-manager container connot use hostnetwork (#7477)
  pkg/constant/const.go
  pkg/controller/configuration/config_utils.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
Labels: approved, size/M

#7487 fix: component status is empty when postProvision action execute in runtimeReady condition
  pkg/controller/component/action_post_provision.go
Labels: approved, size/XS

#7488 fix: update cluster info when retry cluster initialization
  pkg/lorry/dcs/k8s.go
  pkg/lorry/highavailability/ha.go
Labels: approved, size/S

#7492 chore: apply the cluster.spec.backup to BackupSchedule
  controllers/apps/backuppolicytemplate_controller_test.go
  controllers/apps/cluster_controller_test.go
  controllers/apps/component_controller_test.go
  controllers/apps/transformer_cluster_backup_policy.go
  pkg/testutil/dataprotection/constant.go
  test/testdata/backup/pitr_backuptool.yaml
Labels: approved, size/L

#7493 chore: release host-network ports at the component termination
  controllers/apps/transformer_cluster_deletion.go
  controllers/apps/transformer_component_deletion.go
Labels: approved, size/S

#7485 feat: extend h-sacle api to support 'scaleOut' and 'scaleIn' operation
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/opsrequest_webhook.go
  apis/apps/v1alpha1/opsrequest_webhook_test.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/instanceset_types.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/component_controller_test.go
  controllers/apps/component_hscale_volume_populator.go
  controllers/apps/component_utils_test.go
  controllers/apps/operations/horizontal_scaling.go
  controllers/apps/operations/horizontal_scaling_test.go
  controllers/apps/operations/ops_comp_helper.go
  controllers/apps/operations/ops_progress_util.go
  controllers/apps/operations/ops_progress_util_test.go
  controllers/apps/operations/ops_util.go
  controllers/apps/operations/ops_util_test.go
  controllers/apps/operations/queue_util.go
  controllers/apps/operations/rebuild_instance_test.go
  controllers/apps/operations/restart.go
  controllers/apps/operations/start.go
  controllers/apps/operations/stop.go
  controllers/apps/operations/suite_test.go
  controllers/apps/operations/type.go
  controllers/apps/operations/upgrade.go
  controllers/apps/operations/upgrade_test.go
  controllers/apps/operations/vertical_scaling.go
  controllers/apps/operations/vertical_scaling_test.go
  controllers/apps/operations/volume_expansion.go
  controllers/apps/opsrequest_controller_test.go
  controllers/apps/transformer_component_service.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/workload_utils.go
  pkg/controller/instanceset/instance_util.go
  pkg/controllerutil/cluster_utils.go
  pkg/testutil/apps/cluster_instance_set_test_util.go
Labels: area/user-interaction, approved, size/XXL

#7504 docs: fix docs errors
  docs/cli_docs/kubeblocks-for-redis/configuration/configuration.md
Labels: size/S, pre-approve

#7507 docs: check and update part of 0.9 docs
  docs/api_docs/connect_database/connect-database-in-testing-environment.md
  docs/api_docs/installation/install-kubeblocks.md
  docs/api_docs/installation/uninstall-kbcli-and-kubeblocks.md
  docs/api_docs/installation/uninstall-kubeblocks.md
  docs/api_docs/installation/upgrade/upgrade-kubeblocks-to-0.9.md
  docs/api_docs/maintenance/in-place-update/_category_.yaml
  docs/api_docs/maintenance/in-place-update/ignore-vertical-scale.md
  docs/api_docs/maintenance/in-place-update/overview.md
  docs/api_docs/observability/monitor-database.md
  docs/api_docs/overview/concept.md
  docs/api_docs/overview/supported-addons.md
  docs/cli_docs/overview/supported-addons.md
  docs/cli_docs/user-management/manage_user_accounts.md
Labels: approved, size/XL

#7509 chore: reconcile horizontal scaling opsRequest by InstanceSet
  controllers/apps/component_utils_test.go
  controllers/apps/operations/horizontal_scaling_test.go
  controllers/apps/operations/ops_progress_util.go
  controllers/apps/operations/ops_progress_util_test.go
  controllers/apps/operations/ops_util_test.go
  controllers/apps/operations/start_test.go
  controllers/apps/operations/stop_test.go
  controllers/apps/opsrequest_controller_test.go
  pkg/constant/const.go
  pkg/controller/instanceset/in_place_update_util.go
  pkg/controller/instanceset/reconciler_revision_update.go
  pkg/controller/instanceset/reconciler_revision_update_test.go
  pkg/controller/instanceset/reconciler_status.go
  pkg/controller/instanceset/reconciler_status_test.go
  pkg/controller/instanceset/reconciler_update_test.go
  pkg/controller/instanceset/revision_util.go
  pkg/controller/instanceset/revision_util_test.go
  pkg/controller/instanceset/utils.go
  pkg/testutil/apps/base_factory.go
  pkg/testutil/apps/cluster_instance_set_test_util.go
  pkg/testutil/apps/instance_set_factoy.go
Labels: approved, size/L

#7512 chore: filter duplicate volumeMounts in render lifeCycle action job
  pkg/controller/component/action_utils.go
Labels: approved, size/XS

#7456 fix: controller-gen panic on go 1.22
  Makefile
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/apps/v1beta1/zz_generated.deepcopy.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  apis/experimental/v1alpha1/zz_generated.deepcopy.go
  apis/extensions/v1alpha1/zz_generated.deepcopy.go
  apis/storage/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/legacy/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_clusterversions.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_componentversions.yaml
  config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  config/crd/bases/apps.kubeblocks.io_opsdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  config/crd/bases/apps.kubeblocks.io_servicedescriptors.yaml
  config/crd/bases/dataprotection.kubeblocks.io_actionsets.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuprepos.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backupschedules.yaml
  config/crd/bases/dataprotection.kubeblocks.io_restores.yaml
  config/crd/bases/dataprotection.kubeblocks.io_storageproviders.yaml
  config/crd/bases/experimental.kubeblocks.io_nodecountscalers.yaml
  config/crd/bases/extensions.kubeblocks.io_addons.yaml
  config/crd/bases/storage.kubeblocks.io_storageproviders.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterversions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentversions.yaml
  deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/apps.kubeblocks.io_servicedescriptors.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_actionsets.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuprepos.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backupschedules.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_restores.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_storageproviders.yaml
  deploy/helm/crds/experimental.kubeblocks.io_nodecountscalers.yaml
  deploy/helm/crds/extensions.kubeblocks.io_addons.yaml
  deploy/helm/crds/storage.kubeblocks.io_storageproviders.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  externalapis/preflight/v1beta2/zz_generated.deepcopy.go
Labels: approved, size/XXL

#7448 fix: add labels of component when generating secret of tls
  controllers/apps/transformer_component_tls_test.go
  pkg/controller/plan/tls_utils.go
  pkg/controller/plan/tls_utils_test.go
Labels: size/S, pre-approve

#7500 chore: remove dependence on characterType
  go.mod
  pkg/configuration/config_manager/builder.go
  pkg/configuration/config_manager/handler_util.go
  pkg/controller/configuration/config_utils.go
  pkg/controller/configuration/tool_image_builder_test.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
Labels: approved, size/L

#7515 chore: clean up restoreFromBackup annotation
  pkg/controller/plan/restore.go
Labels: size/S

#7494 chore: delete components ordered at cluster deletion
  controllers/apps/cluster_controller.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_cluster_component_test.go
  controllers/apps/transformer_cluster_deletion.go
  controllers/apps/transformer_cluster_deletion_test.go
  controllers/apps/transformer_cluster_halt.go
  controllers/apps/transformer_cluster_load_resources.go
Labels: approved, size/L

#7516 chore: wait for cluster to available when enable pitr
  pkg/dataprotection/backup/scheduler.go
Labels: approved, size/S

#7517 chore: wait for cluster to available when enable pitr
  pkg/dataprotection/backup/scheduler.go
Labels: size/S

#7521 chore: lifecycle action done annotation validation
  pkg/controller/component/action_utils.go
Labels: approved, size/S

#7514 chore: clean up restoreFromBackup annotation key for the cluster
  controllers/apps/transformer_cluster_credential.go
  controllers/apps/transformer_cluster_restore.go
  controllers/apps/transformer_component_account_provision.go
  pkg/controller/plan/restore.go
Labels: approved, size/M

#7526 fix: parameter validation failed with units
  pkg/configuration/validate/cue_visitor_test.go
  pkg/configuration/validate/cuelang_expansion.go
Labels: approved, size/S

#7534 chore: update continuous backup to Completed when cluster is stopped
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/dataprotection/backup_controller.go
Labels: approved, size/S

#7539 chore: support sharding component for rebuild instance and custom ops
  controllers/apps/operations/custom.go
  controllers/apps/operations/custom/utils.go
  controllers/apps/operations/custom_workflow.go
  controllers/apps/operations/horizontal_scaling.go
  controllers/apps/operations/ops_util.go
  controllers/apps/operations/rebuild_instance.go
  controllers/apps/operations/upgrade.go
  pkg/controller/component/component.go
Labels: approved, size/L

#7542 chore: classification of const variables
  controllers/apps/operations/volume_expansion.go
  pkg/constant/annotations.go
  pkg/constant/backup.go
  pkg/constant/config.go
  pkg/constant/const.go
  pkg/constant/errors.go
  pkg/constant/finalizer.go
  pkg/constant/flag.go
  pkg/constant/labels.go
  pkg/constant/lorry.go
  pkg/constant/role.go
  pkg/constant/service_descriptor.go
  pkg/constant/viper_config.go
  pkg/controller/apiconversion/simplified_cluster_api.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/instanceset/instance_util.go
Labels: approved, size/XL

#7547 fix: default function cause value always be true
  deploy/helm/templates/deployment.yaml
Labels: size/XS, pre-approve

#7548 chore: ignore the schedule error when creating a pod
  controllers/apps/operations/rebuild_instance.go
  controllers/apps/transformer_component_status.go
  pkg/controllerutil/pod_utils.go
  pkg/dataprotection/action/action_stateful.go
Labels: size/S

#7549 chore: collected logs of backup/restore are overwrited
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/log_collection_controller.go
  pkg/dataprotection/restore/utils.go
  pkg/dataprotection/types/constant.go
Labels: approved, size/S

#7540 feat: support PodManagementPolicy for the instanceSet controller
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/synthesize_component.go
Labels: approved, size/L

#7546 fix: using Orphan PropagationPolicy when deleting the RSM objects
  controllers/apps/transformer_component_workload_upgrade.go
Labels: approved, size/M

#7553 chore: update readme
  README.md
Labels: approved, size/M

#7554 chore: pick support PodManagementPolicy for the instanceSet controller
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/synthesize_component.go
Labels: size/L

#7531 fix: doMerge panic error (#7530)
  controllers/apps/operations/reconfigure_pipeline.go
Labels: approved, size/S

#7561 chore: force delete target pod during rebuilding instance when spec.force is true
  controllers/apps/operations/rebuild_instance.go
Labels: approved, size/XS

#7564 fix: h-scale ops failed but pod is created successfully
  controllers/apps/operations/horizontal_scaling.go
  controllers/apps/operations/ops_comp_helper.go
  controllers/apps/operations/ops_progress_util.go
  controllers/apps/operations/ops_util.go
  controllers/apps/operations/ops_util_test.go
  pkg/testutil/k8s/pod_util.go
Labels: approved, size/L

#7560 fix: workload scale-in process was incorrectly skipped
  controllers/apps/transformer_component_workload.go
Labels: approved, size/XS

#7569 chore: support multiple init system accounts
  apis/apps/v1alpha1/componentdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/componentdefinition_controller.go
  controllers/apps/componentdefinition_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_component_definition.go
  pkg/controller/component/its_convertor.go
  pkg/controller/component/lorry_utils.go
Labels: approved, size/S

#7572 chore: support multiple init system accounts
  apis/apps/v1alpha1/componentdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/componentdefinition_controller.go
  controllers/apps/componentdefinition_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_component_definition.go
  pkg/controller/component/lorry_utils.go
  pkg/controller/component/rsm_convertor.go
Labels: size/M

#7565 chore: delete pod services at h-scale in
  controllers/apps/component_controller_test.go
  controllers/apps/transformer_component_service.go
  controllers/apps/transformer_component_service_test.go
  pkg/controller/component/workload_utils.go
Labels: approved, size/L

#7544 feat: support user-defined annotations, env and volumes
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/transformer_cluster_component.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_component.go
  pkg/controller/component/component.go
  pkg/controller/component/component_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/synthesize_component_test.go
  pkg/controller/component/type.go
  pkg/controller/factory/builder.go
  pkg/testutil/apps/constant.go
Labels: area/user-interaction, approved, size/XXL

#7575 feat: support user-defined annotations, env and volumes
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/transformer_cluster_component.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_component.go
  pkg/controller/component/component.go
  pkg/controller/component/component_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/factory/builder.go
  pkg/testutil/apps/constant.go
Labels: size/XXL

#7567 feat: FQDN support clusterDomain
  pkg/controller/component/suite_test.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: approved, size/M

#7580 chore: update lorry logs
  pkg/lorry/engines/polardbx/get_replica_role.go
  pkg/lorry/engines/redis/get_replica_role.go
  pkg/lorry/engines/wesql/get_replica_role.go
Labels: approved, size/S

#7587 feat: support user-defined annotations, env and volumes
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/transformer_cluster_component.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_component.go
  pkg/controller/component/component.go
  pkg/controller/component/component_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/factory/builder.go
  pkg/testutil/apps/constant.go
Labels: size/XXL

#7563 docs: KubeBlocks for MySQL Configure cluster parameters
  docs/user_docs/kubeblocks-for-mysql/configuration/configuration.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql/configuration/configuration.md
Labels: size/XS, pre-approve

#7584 fix: support idempotency for account provision
  pkg/lorry/client/httpclient_test.go
  pkg/lorry/engines/mysql/user.go
  pkg/lorry/engines/postgres/query.go
  pkg/lorry/engines/redis/user.go
  pkg/lorry/operations/user/create.go
Labels: approved, size/S

#7590 chore: fix opsRequest panic and clean code
  controllers/apps/operations/custom.go
  controllers/apps/operations/ops_comp_helper.go
  controllers/apps/operations/ops_progress_util.go
Labels: approved, size/M

#7592 fix: test InPlacePodVerticalScaling all the time
  pkg/controller/instanceset/in_place_update_util.go
  pkg/controller/instanceset/in_place_update_util_test.go
Labels: approved, size/S

#7594 chore: support to run a opsRequest after the dependent opsRequests are succeed.
  controllers/apps/operations/ops_manager.go
  controllers/apps/operations/ops_util_test.go
  controllers/apps/opsrequest_controller.go
  controllers/apps/opsrequest_controller_test.go
  pkg/constant/annotations.go
Labels: approved, size/L

#7595 chore: support to run a opsRequest after the dependent opsRequests are succeed.
  controllers/apps/operations/ops_manager.go
  controllers/apps/opsrequest_controller.go
  pkg/constant/const.go
Labels: size/M

#7593 feat: support user-defined labels
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/transformer_cluster_component.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_component.go
  pkg/controller/component/component.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/factory/builder.go
Labels: approved, size/L

#7600 chore: Revert remove dependence on characterType (#7500)
  go.mod
  pkg/configuration/config_manager/builder.go
  pkg/configuration/config_manager/handler_util.go
  pkg/controller/configuration/config_utils.go
  pkg/controller/configuration/tool_image_builder_test.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
Labels: size/L

#7601 feat: support user-defined labels
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/transformer_cluster_component.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_component.go
  pkg/controller/component/component.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/factory/builder.go
Labels: size/L

#7605 feat: support user-defined labels
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/transformer_cluster_component.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_component.go
  pkg/controller/component/component.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/factory/builder.go
Labels: size/L

#7602 fix: opsRequest can not run forcibly after updating spec.force to true
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  controllers/apps/operations/queue_util.go
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/M

#7608 chore: support available condition for instanceSet and update the succeess condition check for h-scale opsRequest
  apis/workloads/v1alpha1/instanceset_types.go
  controllers/apps/operations/ops_progress_util.go
  controllers/apps/opsrequest_controller.go
  controllers/apps/transformer_component_workload.go
  controllers/workloads/instanceset_controller.go
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/instanceset/reconciler_status.go
  pkg/controller/instanceset/reconciler_status_test.go
  pkg/controller/kubebuilderx/controller.go
Labels: approved, size/L

#7543 feat: new kb agent v2
  cmd/kb_agent/main.go
  pkg/constant/env.go
  pkg/kb_agent/cronjobs/checkrole.go
  pkg/kb_agent/cronjobs/checkrole_test.go
  pkg/kb_agent/cronjobs/job.go
  pkg/kb_agent/cronjobs/manager.go
  pkg/kb_agent/handlers/action.go
  pkg/kb_agent/handlers/action_test.go
  pkg/kb_agent/handlers/errors.go
  pkg/kb_agent/handlers/exec_handler.go
  pkg/kb_agent/handlers/grpc_handler.go
  pkg/kb_agent/handlers/interface.go
  pkg/kb_agent/httpserver/apis.go
  pkg/kb_agent/httpserver/config.go
  pkg/kb_agent/httpserver/endpoint.go
  pkg/kb_agent/httpserver/errors.go
  pkg/kb_agent/httpserver/server.go
  pkg/kb_agent/util/command.go
  pkg/kb_agent/util/command_test.go
  pkg/kb_agent/util/event.go
  pkg/kb_agent/util/k8s_client.go
  pkg/kb_agent/util/types.go
Labels: approved, size/XXL

#7616 chore: support to volume snapshot a shard cluster
  controllers/dataprotection/volumepopulator_controller.go
  pkg/dataprotection/action/action_create_vs.go
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/utils.go
Labels: approved, size/M

#7621 chore: delete related running restore resource to release pvc when cancelling the horizontal scaling
  controllers/apps/operations/horizontal_scaling.go
  controllers/apps/opsrequest_controller_test.go
Labels: approved, size/M

#7622 chore: delete related running restore resource to release pvc when cancelling the horizontal scaling
  controllers/apps/operations/horizontal_scaling.go
Labels: size/M

#7611 chore: switch aliyun image registry infracreate to apecloud
  config/samples/extensions_v1alpha1_addon.yaml
  deploy/helm/templates/_helpers.tpl
  deploy/helm/templates/applications/chaos-mesh-addon.yaml
  deploy/helm/values.yaml
  pkg/controller/component/lorry_utils.go
  pkg/controller/instanceset/revision_util_test.go
  test/e2e/testdata/config/postgresql_cv.yaml
  test/testdata/backup/actionset.yaml
Labels: approved, size/M

#7627 chore: auto install mysql addon
  deploy/helm/templates/addons/mysql-addon.yaml
Labels: approved, size/XS

#7628 chore: update examples
  examples/apecloud-mysql/cluster-cmpd.yaml
  examples/apecloud-mysql/cluster-proxy.yaml
  examples/apecloud-mysql/cluster.yaml
  examples/apecloud-mysql/restore-cmpd.yaml
  examples/apecloud-mysql/restore.yaml
  examples/mongodb/cluster.yaml
  examples/mongodb/restore.yaml
  examples/mysql/cluster.yaml
  examples/mysql/restore.yaml
  examples/postgresql/cluster-cmpd.yaml
  examples/postgresql/cluster.yaml
  examples/postgresql/restore-cmpd.yaml
  examples/postgresql/restore.yaml
  examples/pulsar/cluster-cmpd.yaml
  examples/pulsar/cluster-service-descriptor.yaml
  examples/pulsar/cluster-zookeeper-separate.yaml
  examples/pulsar/cluster.yaml
  examples/qdrant/backup.yaml
  examples/qdrant/cluster-cmpd.yaml
  examples/qdrant/cluster.yaml
  examples/qdrant/restore-cmpd.yaml
  examples/qdrant/restore.yaml
  examples/redis/README.md
  examples/redis/cluster-cd-topology.yaml
  examples/redis/cluster-cmpd.yaml
  examples/redis/cluster-sharding.yaml
  examples/redis/cluster.yaml
  examples/redis/restore-cmpd.yaml
  examples/redis/restore.yaml
Labels: size/L

#7630 fix: volume expansion failed with offline instances
  controllers/apps/transformer_component_workload.go
Labels: approved, size/XS

#7633 fix: when modifying the ops status to Aborted, there are legacy ops annotations for the cluster
  controllers/apps/opsrequest_controller.go
Labels: approved, size/S

#7634 chore: compatible with a special usage of cmpd host-network
  pkg/controller/component/utils.go
Labels: approved, size/S

#7632 fix: add a user check before creating
  controllers/apps/component_controller_test.go
  controllers/apps/transformer_component_account_provision.go
Labels: approved, size/XS

#7639 fix: type assert crash
  pkg/lorry/client/client.go
Labels: approved, size/XS

#7635 fix: volume expansion hang when existing offlineInstances
  controllers/apps/component_controller_test.go
  controllers/apps/operations/volume_expansion.go
  controllers/apps/transformer_component_workload.go
Labels: approved, size/M

#7638 fix: conversion between minor versions (#7503)
  cmd/helmhook/hook/conversion.go
  cmd/helmhook/hook/prepare.go
  cmd/helmhook/hook/types.go
Labels: approved, size/S

#7643 chore: do not override grafna value with clear text passwd
  deploy/helm/values.yaml
Labels: approved, size/XS

#7645 chore: support to restore new cluster and hscale with backup when cluster specifies the instance template
  controllers/apps/component_hscale_volume_populator.go
  controllers/apps/operations/rebuild_instance.go
  controllers/apps/operations/restore.go
  controllers/apps/transformer_component_status.go
  controllers/apps/transformer_component_workload.go
  pkg/controller/component/workload_utils.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
  pkg/controller/plan/restore.go
  pkg/controller/plan/restore_test.go
Labels: approved, size/L

#7649 chore: update redis examples
  examples/redis/restore-cmpd.yaml
Labels: size/XS

#7647 chore: compatible with a special usage of cmpd host-network
  pkg/controller/component/definition_convertor.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/utils.go
Labels: approved, size/M

#7573 chore: remove webhooks of all crds
  PROJECT
  apis/apps/v1alpha1/cluster_webhook.go
  apis/apps/v1alpha1/cluster_webhook_test.go
  apis/apps/v1alpha1/clusterdefinition_webhook.go
  apis/apps/v1alpha1/clusterdefinition_webhook_test.go
  apis/apps/v1alpha1/clusterversion_types.go
  apis/apps/v1alpha1/clusterversion_webhook.go
  apis/apps/v1alpha1/clusterversion_webhook_test.go
  apis/apps/v1alpha1/component_webhook.go
  apis/apps/v1alpha1/componentdefinition_webhook.go
  apis/apps/v1alpha1/componentdefinition_webhook_test.go
  apis/apps/v1alpha1/componentversion_webhook.go
  apis/apps/v1alpha1/configconstraint_conversion.go
  apis/apps/v1alpha1/opsrequest_conditions_test.go
  apis/apps/v1alpha1/opsrequest_validation.go
  apis/apps/v1alpha1/opsrequest_webhook_test.go
  apis/apps/v1alpha1/servicedescriptor_webhook.go
  apis/apps/v1alpha1/servicedescriptor_webhook_test.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/webhook_suite_test.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/apps/v1beta1/configconstraint_conversion.go
  apis/apps/v1beta1/configconstraint_webhook.go
  apis/apps/v1beta1/webhook_suite_test.go
  apis/apps/v1beta1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/instanceset_webhook.go
  apis/workloads/v1alpha1/instanceset_webhook_test.go
  apis/workloads/v1alpha1/webhook_suite_test.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  cmd/helmhook/hook/multiversion/configconstraint.go
  cmd/manager/main.go
  config/webhook/manifests.yaml
  controllers/apps/operations/suite_test.go
  controllers/apps/suite_test.go
  controllers/apps/transformer_component_status.go
  controllers/workloads/suite_test.go
Labels: approved, size/XXL

#7650 chore: update slack link
  README.md
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/cluster-management/switch-over-a-mongodb-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/configuration/configure-cluster-parameters.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql/cluster-management/switchover.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql/configuration/configuration.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql/proxy/apecloud-mysql-proxy.md
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/cluster-management/switchover.md
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/configuration/configuration.md
  i18n/zh-cn/user-docs/kubeblocks-for-pulsar/configuration/configuration.md
  i18n/zh-cn/user-docs/kubeblocks-for-redis/configuration/configure-cluster-parameters.md
Labels: approved, size/M

#7654 fix: volume expansion hang after rebuilding instance
  controllers/apps/operations/rebuild_instance.go
Labels: approved, size/XS

#7574 chore: delete sub-resources with order when cluster is deleted
  controllers/apps/transformer_cluster_deletion.go
  controllers/apps/transformer_cluster_deletion_test.go
  controllers/apps/transformer_component_deletion.go
Labels: approved, size/M

#7637 chore: lifecycleAction jobSpec set default template pod serviceAccountName
  pkg/controller/component/action_utils.go
Labels: approved, size/XS

#7656 chore: lifecycle action job cleaned waiting for action-done-annotation patched
  controllers/apps/transformer_component_deletion.go
  pkg/controller/component/action_utils.go
Labels: approved, size/XS

#7660 chore: backupSchedule controller watches the continuous backup
  controllers/dataprotection/backupschedule_controller.go
Labels: approved, size/S

#7662 fix: restore mongo crash
  pkg/controller/plan/restore.go
Labels: approved, size/XS

#7665 chore:update redis example restore
  examples/redis/restore.yaml
Labels: approved, size/S

#7668 chore: set component ownership to objects before return premature stop error
  controllers/apps/transformer_component_ownership.go
  controllers/apps/transformer_component_restore.go
  controllers/apps/transformer_component_workload_upgrade.go
Labels: approved, size/S
