Repository apecloud/kubeblocks, pull requests merged in 2024-10, with the labels that each got.

#8220 fix: preConditionDeadlineSeconds of the opsRequest is invalid when creating some opsRequests together
  apis/operations/v1alpha1/opsrequest_validation.go
  pkg/constant/ops.go
  pkg/operations/ops_manager.go
  pkg/operations/ops_util.go
Labels: approved, size/L

#8240 chore: support backup and restore SystemAccounts
  controllers/apps/transformer_component_account.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/utils.go
  pkg/constant/const.go
  pkg/controller/factory/builder.go
  pkg/dataprotection/restore/utils.go
  pkg/testutil/dataprotection/backup_utils.go
Labels: size/L, pre-approve

#8239 chore: get rid of golang.org/x/exp/{constraints,slices} modules
  apis/operations/v1alpha1/opsrequest_validation.go
  controllers/apps/cluster_controller_test.go
  controllers/apps/cluster_status_conditions.go
  controllers/apps/clusterdefinition_controller.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/configuration/reconfigure_policy.go
  controllers/apps/configuration/rolling_upgrade_policy.go
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/apps/transformer_cluster_service_test.go
  controllers/apps/transformer_component_account_provision.go
  controllers/apps/transformer_component_service_test.go
  controllers/apps/transformer_component_workload.go
  controllers/dataprotection/log_collection_controller.go
  controllers/dataprotection/volumepopulator_controller.go
  controllers/experimental/reconciler_scale_target_cluster.go
  controllers/experimental/reconciler_update_status.go
  controllers/extensions/addon_controller_stages.go
  controllers/operations/opsrequest_controller.go
  controllers/operations/opsrequest_controller_test.go
  go.mod
  go.sum
  pkg/configuration/util/math.go
  pkg/configuration/util/math_test.go
  pkg/controller/component/component_version.go
  pkg/controller/component/service_reference.go
  pkg/controller/instanceset/in_place_update_util.go
  pkg/controller/instanceset/reconciler_instance_alignment_test.go
  pkg/controller/instanceset/reconciler_update_test.go
  pkg/controller/kubebuilderx/plan_builder_test.go
  pkg/controllerutil/util.go
  pkg/controllerutil/util_test.go
  pkg/operations/ops_progress_util.go
  pkg/operations/ops_util.go
  pkg/operations/queue_util.go
  pkg/operations/rebuild_instance.go
  pkg/operations/rebuild_instance_test.go
  pkg/operations/stop.go
Labels: approved, size/L

#8224 chore: remove rsm to its upgrade
  apis/workloads/legacy/doc.go
  apis/workloads/legacy/groupversion_info.go
  apis/workloads/legacy/register.go
  apis/workloads/legacy/replicatedstatemachine_types.go
  apis/workloads/legacy/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/rbac/role.yaml
  controllers/apps/component_controller.go
  controllers/apps/component_controller_test.go
  controllers/apps/component_plan_builder.go
  controllers/apps/suite_test.go
  controllers/apps/transformer_component_workload_upgrade.go
  controllers/operations/suite_test.go
  deploy/helm/config/rbac/role.yaml
  hack/docgen/api/main.go
Labels: approved, size/XXL

#8238 feat: cmpv supports images of the lifecycle action and the user-managed
  apis/apps/v1/componentversion_types.go
  config/crd/bases/apps.kubeblocks.io_componentversions.yaml
  controllers/apps/componentversion_controller.go
  controllers/apps/componentversion_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_componentversions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/component_version.go
  pkg/testutil/apps/component_version_util.go
Labels: approved, size/L

#8213 docs: add how to get kbcli and kb version in docs
  docs/user_docs/installation/install-with-helm/install-kubeblocks.md
  docs/user_docs/installation/install-with-kbcli/install-kbcli.md
  docs/user_docs/installation/install-with-kbcli/install-kubeblocks-with-kbcli.md
Labels: approved, size/S

#8244 chore: cleanup the APIs pkg deps and keep them compact
  apis/extensions/v1alpha1/addon_types_test.go
  apis/extensions/v1alpha1/type.go
  controllers/extensions/addon_controller_test.go
  pkg/testutil/type.go
Labels: approved, size/M

#8245 chore: service-ref supports to refer services from different namespace
  pkg/controller/component/service_reference.go
  pkg/controller/component/service_reference_test.go
  pkg/controller/component/vars.go
  pkg/controller/component/workload_utils.go
Labels: approved, size/M

#8221 feat: custom opsRequest supports to input parameters from cm and secret
  apis/operations/v1alpha1/opsrequest_types.go
  apis/operations/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
  pkg/operations/custom.go
  pkg/operations/custom/utils.go
  pkg/operations/custom_test.go
  pkg/operations/ops_manager.go
Labels: approved, size/L

#8219 docs: merge apecloud mysql and es API docs
  docs/img/failure_simulation_connect_cluster_after.png
  docs/img/failure_simulation_connect_cluster_follower.png
  docs/img/failure_simulation_connect_three_pods.png
  docs/img/failure_simulation_connect_two_pods.png
  docs/img/failure_simulation_delete_follower_pod.png
  docs/img/failure_simulation_delete_pod.png
  docs/img/failure_simulation_delete_three_pods.png
  docs/img/failure_simulation_delete_two_pods.png
  docs/img/failure_simulation_describe_cluster.png
  docs/img/failure_simulation_describe_cluster_2.png
  docs/img/failure_simulation_describe_cluster_after.png
  docs/img/failure_simulation_describe_cluster_follower.png
  docs/img/failure_simulation_describe_three_pods.png
  docs/img/failure_simulation_describe_two_pods.png
  docs/user_docs/connect_database/connect-database-in-production-environment.md
  docs/user_docs/handle-an-exception/handle-a-cluster-exception.md
  docs/user_docs/kubeblocks-for-apecloud-mysql/cluster-management/create-and-connect-an-apecloud-mysql-cluster.md
  docs/user_docs/kubeblocks-for-apecloud-mysql/cluster-management/delete-mysql-cluster.md
  docs/user_docs/kubeblocks-for-apecloud-mysql/cluster-management/expand-volume.md
  docs/user_docs/kubeblocks-for-apecloud-mysql/cluster-management/restart-mysql-cluster.md
  docs/user_docs/kubeblocks-for-apecloud-mysql/cluster-management/scale-for-apecloud-mysql.md
  docs/user_docs/kubeblocks-for-apecloud-mysql/cluster-management/stop-start-a-cluster.md
  docs/user_docs/kubeblocks-for-apecloud-mysql/cluster-management/switchover.md
  docs/user_docs/kubeblocks-for-apecloud-mysql/configuration/configuration.md
  docs/user_docs/kubeblocks-for-apecloud-mysql/high-availability/high-availability.md
  docs/user_docs/kubeblocks-for-apecloud-mysql/kubeblocks-for-apecloud-mysql.md
  docs/user_docs/kubeblocks-for-apecloud-mysql/proxy/apecloud-mysql-proxy.md
  docs/user_docs/kubeblocks-for-elasticsearch/manage-elasticsearch.md
Labels: approved, size/XXL

#8229 docs: merge kafka, milvus, mongodb, mysql, pg api docs into user docs
  docs/img/pgsql-ha-after.png
  docs/img/pgsql-ha-before.png
  docs/img/pgsql-ha-pg_stat_replication.png
  docs/user_docs/kubeblocks-for-kafka/cluster-management/connect-to-a-cluster.md
  docs/user_docs/kubeblocks-for-kafka/cluster-management/create-a-kafka-cluster.md
  docs/user_docs/kubeblocks-for-kafka/cluster-management/delete-kafka-cluster.md
  docs/user_docs/kubeblocks-for-kafka/cluster-management/expand-volume.md
  docs/user_docs/kubeblocks-for-kafka/cluster-management/restart-a-kafka-cluster.md
  docs/user_docs/kubeblocks-for-kafka/cluster-management/scale.md
  docs/user_docs/kubeblocks-for-kafka/cluster-management/start-stop-a-cluster.md
  docs/user_docs/kubeblocks-for-kafka/configuration/configuration.md
  docs/user_docs/kubeblocks-for-kafka/kubeblocks-for-kafka.md
  docs/user_docs/kubeblocks-for-milvus/manage-milvus.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/delete-mongodb-cluster.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/expand-volume.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/restart-mongodb-cluster.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/scale-for-mongodb.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/start-stop-a-cluster.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/switchover.md
  docs/user_docs/kubeblocks-for-mongodb/configuration/configuration.md
  docs/user_docs/kubeblocks-for-mongodb/kubeblocks-for-mongodb.md
  docs/user_docs/kubeblocks-for-mysql-community-edition/cluster-management/create-and-connect-a-mysql-cluster.md
  docs/user_docs/kubeblocks-for-mysql-community-edition/cluster-management/delete-mysql-cluster.md
  docs/user_docs/kubeblocks-for-mysql-community-edition/cluster-management/expand-volume.md
  docs/user_docs/kubeblocks-for-mysql-community-edition/cluster-management/restart-mysql-cluster.md
  docs/user_docs/kubeblocks-for-mysql-community-edition/cluster-management/scale-for-mysql.md
  docs/user_docs/kubeblocks-for-mysql-community-edition/cluster-management/stop-start-a-cluster.md
  docs/user_docs/kubeblocks-for-mysql-community-edition/cluster-management/switchover.md
  docs/user_docs/kubeblocks-for-mysql-community-edition/configuration/configuration.md
  docs/user_docs/kubeblocks-for-mysql-community-edition/high-availability/high-availability.md
  docs/user_docs/kubeblocks-for-mysql-community-edition/kubeblocks-for-mysql-community-edition.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/create-and-connect-a-postgresql-cluster.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/delete-a-postgresql-cluster.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/expand-volume.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/restart-a-postgresql-cluster.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/scale-for-a-postgresql-cluster.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/start-stop-a-cluster.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/switchover.md
  docs/user_docs/kubeblocks-for-postgresql/configuration/configuration.md
  docs/user_docs/kubeblocks-for-postgresql/high-availability/high-availability.md
  docs/user_docs/kubeblocks-for-postgresql/kubeblocks-for-postgresql.md
  docs/user_docs/kubeblocks-for-postgresql/postgresql-connection-pool/postgresql-connection-pool.md
Labels: approved, size/XXL

#8254 docs: fix format bugs for merging api docs
  docs/user_docs/kubeblocks-for-kafka/cluster-management/start-stop-a-cluster.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/delete-mongodb-cluster.md
  docs/user_docs/kubeblocks-for-mysql-community-edition/cluster-management/scale-for-mysql.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/start-stop-a-cluster.md
Labels: approved, size/XL

#8253 chore: remove dependency on github.com/containers/common
  go.mod
  go.sum
  test/testutils/helm.go
  test/testutils/utils.go
Labels: approved, size/M

#8261 chore: fix release chart error
  .github/workflows/release-helm-chart.yml
Labels: approved, size/XS

#8266 fix: the scheduling policy of the component is lost
  controllers/apps/cluster_controller_test.go
  controllers/apps/transformer_cluster_component.go
Labels: approved, size/M

#8251 chore: use generic sets instead of the deprecated one
  cmd/helmhook/hook/crd.go
  pkg/common/env_resolve.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/reconciler_instance_alignment.go
  pkg/controller/instanceset/reconciler_update.go
Labels: approved, size/S

#8270 chore: add /recheck-cla bot instruction
  .github/workflows/recheck-cla.yml
Labels: approved, size/M

#8267 chore: fix a test case in log_collection_controller_test.go
  controllers/dataprotection/log_collection_controller_test.go
Labels: approved, size/XS

#8265 fix: flaky test cases in component_controller_test.go
  controllers/apps/cluster_controller_test.go
  controllers/apps/component_controller_test.go
  controllers/apps/transformer_component_tls_test.go
  pkg/testutil/apps/cluster_util.go
  pkg/testutil/apps/component_util.go
Labels: approved, size/M

#8273 chore: change test type
  .github/workflows/release-image.yml
Labels: approved, size/XS

#8274 chore: tidy up ops and component controller codes
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  controllers/apps/component_plan_builder.go
  controllers/operations/opsrequest_controller.go
  pkg/operations/ops_manager.go
  pkg/operations/ops_util.go
Labels: approved, size/S

#8268 fix: nil ptr on upgrade hook job
  cmd/helmhook/hook/prepare.go
  cmd/helmhook/hook/utils.go
Labels: approved, size/XS

#8272 chore: introduce the new definition CRD to describe sharding
  PROJECT
  apis/apps/v1/shardingdefinition_types.go
  apis/apps/v1/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/crd/bases/apps.kubeblocks.io_shardingdefinitions.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_apps_shardingdefinitions.yaml
  config/crd/patches/webhook_in_apps_shardingdefinitions.yaml
  config/rbac/apps_shardingdefinition_editor_role.yaml
  config/rbac/apps_shardingdefinition_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/apps_v1_shardingdefinition.yaml
  controllers/apps/const.go
  controllers/apps/shardingdefinition_controller.go
  controllers/apps/shardingdefinition_controller_test.go
  controllers/apps/suite_test.go
  deploy/helm/config/rbac/role.yaml
  deploy/helm/crds/apps.kubeblocks.io_shardingdefinitions.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/client/clientset/versioned/typed/apps/v1/apps_client.go
  pkg/client/clientset/versioned/typed/apps/v1/fake/fake_apps_client.go
  pkg/client/clientset/versioned/typed/apps/v1/fake/fake_shardingdefinition.go
  pkg/client/clientset/versioned/typed/apps/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/apps/v1/shardingdefinition.go
  pkg/client/informers/externalversions/apps/v1/interface.go
  pkg/client/informers/externalversions/apps/v1/shardingdefinition.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/apps/v1/expansion_generated.go
  pkg/client/listers/apps/v1/shardingdefinition.go
  pkg/constant/labels.go
  pkg/generics/type.go
  pkg/testutil/apps/shardingdefinition_factory.go
Labels: approved, size/XXL

#8281 fix: vertical scaling the instance templates failed
  pkg/controller/component/component.go
  pkg/dataprotection/restore/utils.go
  pkg/operations/ops_progress_util.go
  pkg/operations/ops_util_test.go
  pkg/operations/restart.go
  pkg/operations/upgrade.go
  pkg/operations/vertical_scaling.go
  pkg/operations/vertical_scaling_test.go
Labels: approved, size/L

#8284 fix: dataprotection crash
  config/rbac/role.yaml
  controllers/dataprotection/backup_controller.go
  deploy/helm/config/rbac/role.yaml
Labels: approved, size/M

#8286 fix: restore pirt nil pointer bug
  pkg/dataprotection/restore/manager.go
Labels: approved, size/S

#8285 fix: restore pitr nil pointer bug
  pkg/dataprotection/restore/manager.go
Labels: approved, size/XS

#8280 feat: KB install support specifiy addon list and remove loki addon
  deploy/helm/templates/addons/apecloud-mysql-addon.yaml
  deploy/helm/templates/addons/etcd-addon.yaml
  deploy/helm/templates/addons/kafka-addon.yaml
  deploy/helm/templates/addons/llm-addon.yaml
  deploy/helm/templates/addons/mongodb-addon.yaml
  deploy/helm/templates/addons/mysql-addon.yaml
  deploy/helm/templates/addons/postgresql-addon.yaml
  deploy/helm/templates/addons/pulsar-addon.yaml
  deploy/helm/templates/addons/qdrant-addon.yaml
  deploy/helm/templates/addons/redis-addon.yaml
  deploy/helm/templates/applications/alertmanager-webhook-adaptor-addon.yaml
  deploy/helm/templates/applications/alertmanager-webhook-adaptor-values.yaml
  deploy/helm/templates/applications/apecloud-otel-collector-addon.yaml
  deploy/helm/templates/applications/apecloud-otel-collector-values.yaml
  deploy/helm/templates/applications/aws-loadbalancer-controller-addon.yaml
  deploy/helm/templates/applications/aws-loadbalancer-controller-values.yaml
  deploy/helm/templates/applications/csi-driver-addon.yaml
  deploy/helm/templates/applications/csi-driver-nfs-addon.yaml
  deploy/helm/templates/applications/csi-hostpath-driver-addon.yaml
  deploy/helm/templates/applications/csi-hostpath-driver-values.yaml
  deploy/helm/templates/applications/grafana-addon.yaml
  deploy/helm/templates/applications/grafana-values.yaml
  deploy/helm/templates/applications/loki-addon.yaml
  deploy/helm/templates/applications/loki-values.yaml
  deploy/helm/templates/applications/prometheus-addon.yaml
  deploy/helm/templates/applications/prometheus-values.yaml
  deploy/helm/templates/applications/snapshot-controller-addon.yaml
  deploy/helm/templates/applications/snapshot-controller-values.yaml
  deploy/helm/templates/applications/vmagent-addon.yaml
  deploy/helm/templates/applications/vmagent-values.yaml
  deploy/helm/templates/grafana/configmaps-datasources.yaml
  deploy/helm/values.yaml
Labels: size/L, pre-approve

#8287 chore: remove kubeblocks-csi-driver file
  deploy/helm/templates/applications/csi-driver-addon.yaml
  deploy/helm/values.yaml
Labels: size/M, pre-approve

#8289 fix: instance is always pending when the component replicas is 1 and enable the pitr and using the cloud disk
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  pkg/dataprotection/backup/utils.go
Labels: approved, size/M

#8290 fix: instance is always pending when the component replicas is 1 and enable the pitr and using the cloud disk
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  pkg/dataprotection/backup/utils.go
Labels: approved, size/M

#8276 chore: support provisioning clusters by sharding definitions
  apis/apps/v1/cluster_types.go
  apis/apps/v1/clusterdefinition_types.go
  apis/apps/v1/deprecated.go
  apis/apps/v1/types.go
  apis/apps/v1/zz_generated.deepcopy.go
  apis/operations/v1alpha1/opsrequest_validation.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  controllers/apps/cluster_controller.go
  controllers/apps/cluster_controller_test.go
  controllers/apps/cluster_plan_builder.go
  controllers/apps/cluster_status_conditions.go
  controllers/apps/clusterdefinition_controller.go
  controllers/apps/clusterdefinition_controller_test.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/componentversion_controller.go
  controllers/apps/shardingdefinition_controller.go
  controllers/apps/transformer_cluster_api_normalization.go
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_cluster_component_status.go
  controllers/apps/transformer_cluster_component_status_test.go
  controllers/apps/transformer_cluster_component_test.go
  controllers/apps/transformer_cluster_deletion.go
  controllers/apps/transformer_cluster_deletion_test.go
  controllers/apps/transformer_cluster_meta.go
  controllers/apps/transformer_cluster_normalization.go
  controllers/apps/transformer_cluster_placement.go
  controllers/apps/transformer_cluster_restore.go
  controllers/apps/transformer_cluster_service.go
  controllers/apps/transformer_cluster_service_test.go
  controllers/apps/transformer_cluster_sharding_account.go
  controllers/apps/transformer_cluster_shared_account.go
  controllers/apps/transformer_cluster_status.go
  controllers/apps/transformer_cluster_validation.go
  controllers/apps/transformer_cluster_validation_test.go
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/pattern.go
  pkg/controller/component/component.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/utils.go
  pkg/controller/component/utils_test.go
  pkg/controllerutil/cluster_utils.go
  pkg/controllerutil/cluster_utils_test.go
  pkg/controllerutil/sharding_utils.go
  pkg/controllerutil/sharding_utils_test.go
  pkg/operations/ops_comp_helper.go
  pkg/operations/ops_util.go
  pkg/operations/restart.go
  pkg/operations/start.go
  pkg/operations/stop.go
  pkg/operations/upgrade.go
  pkg/operations/volume_expansion.go
  pkg/testutil/apps/cluster_factory.go
Labels: approved, size/XXL

#8294 fix: restore failed when cluster is create by cd/cv
  controllers/dataprotection/backup_controller.go
Labels: approved, size/XS

#8262 docs: add 0.9.1 upgrade guides and update related commands in 0.9.0
  docs/user_docs/upgrade/faq.md
  docs/user_docs/upgrade/upgrade with helm/upgrade-kubeblocks-to-0.9.md
  docs/user_docs/upgrade/upgrade with kbcli/upgrade-kubeblocks-to-0.9.md
  docs/user_docs/upgrade/upgrade-with-helm/_category_.yml
  docs/user_docs/upgrade/upgrade-with-helm/upgrade-kubeblocks-to-0.8.md
  docs/user_docs/upgrade/upgrade-with-helm/upgrade-kubeblocks-to-0.9.1.md
  docs/user_docs/upgrade/upgrade-with-helm/upgrade-kubeblocks-to-0.9.md
  docs/user_docs/upgrade/upgrade-with-kbcli/_category_.yml
  docs/user_docs/upgrade/upgrade-with-kbcli/upgrade-kubeblocks-to-0.8.md
  docs/user_docs/upgrade/upgrade-with-kbcli/upgrade-kubeblocks-to-0.9.1.md
  docs/user_docs/upgrade/upgrade-with-kbcli/upgrade-kubeblocks-to-0.9.md
  i18n/zh-cn/user-docs/overview/database-engines-supported.md
Labels: approved, size/XL

#8300 docs: sync upgrade guide
  docs/user_docs/upgrade/faq.md
  docs/user_docs/upgrade/upgrade with helm/upgrade-kubeblocks-to-0.9.md
  docs/user_docs/upgrade/upgrade with kbcli/upgrade-kubeblocks-to-0.9.md
  docs/user_docs/upgrade/upgrade-with-helm/_category_.yml
  docs/user_docs/upgrade/upgrade-with-helm/upgrade-kubeblocks-to-0.8.md
  docs/user_docs/upgrade/upgrade-with-helm/upgrade-kubeblocks-to-0.9.1.md
  docs/user_docs/upgrade/upgrade-with-helm/upgrade-kubeblocks-to-0.9.md
  docs/user_docs/upgrade/upgrade-with-kbcli/_category_.yml
  docs/user_docs/upgrade/upgrade-with-kbcli/upgrade-kubeblocks-to-0.8.md
  docs/user_docs/upgrade/upgrade-with-kbcli/upgrade-kubeblocks-to-0.9.1.md
  docs/user_docs/upgrade/upgrade-with-kbcli/upgrade-kubeblocks-to-0.9.md
  i18n/zh-cn/user-docs/overview/database-engines-supported.md
Labels: approved, size/XL

#8301 docs: update upgrade docs
  docs/user_docs/upgrade/faq.md
  docs/user_docs/upgrade/upgrade-with-helm/upgrade-kubeblocks-to-0.9.1.md
Labels: approved, size/XS

#8302 docs: sync upgrade guide
  docs/user_docs/upgrade/faq.md
  docs/user_docs/upgrade/upgrade-with-helm/upgrade-kubeblocks-to-0.9.1.md
Labels: approved, size/XS

#8303 fix: backup and restore bug
  apis/dataprotection/v1alpha1/backup_types.go
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  controllers/apps/component_controller.go
  controllers/apps/component_controller_test.go
  controllers/apps/component_hscale_volume_populator.go
  controllers/dataprotection/backup_controller.go
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  pkg/controller/factory/builder.go
  pkg/dataprotection/restore/utils.go
  pkg/operations/restore.go
  pkg/testutil/dataprotection/utils.go
Labels: approved, size/S

#8308 fix: cluster conversion NPE
  apis/apps/v1alpha1/cluster_conversion.go
Labels: approved, size/S

#8315 chore: release snapshot.storage.k8s.yaml crds
  .github/workflows/release-crds.yml
  deploy/helm/crds/snapshot/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  deploy/helm/crds/snapshot/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  deploy/helm/crds/snapshot/snapshot.storage.k8s.io_volumesnapshots.yaml
Labels: approved, size/XL

#8319 chore: fix delete backup and restore bug
  cmd/dataprotection/main.go
  controllers/apps/component_controller.go
  controllers/apps/component_controller_test.go
  controllers/apps/component_hscale_volume_populator.go
  controllers/apps/transformer_cluster_status.go
  pkg/constant/labels.go
  pkg/controller/factory/builder.go
  pkg/dataprotection/backup/deleter.go
  pkg/testutil/dataprotection/utils.go
Labels: approved, size/S

#8323 fix: cluster is running without role check
  pkg/controller/instanceset/utils.go
Labels: approved, size/XS

#8322 fix: cluster running without role check
  pkg/controller/instanceset/utils.go
  pkg/dataprotection/backup/deleter.go
Labels: approved, size/XS

#8299 feat: support for defining the orders of components created dynamically
  apis/apps/v1/clusterdefinition_types.go
  apis/apps/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  controllers/apps/clusterdefinition_controller.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_cluster_component_status_test.go
  controllers/apps/transformer_cluster_component_test.go
  controllers/apps/transformer_cluster_normalization.go
  controllers/apps/transformer_cluster_validation.go
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: area/user-interaction, approved, size/L

#8325 chore: improve calculate mysql buffer pool size
  pkg/controller/configuration/builtin_functions.go
  pkg/controller/configuration/config_template_test.go
Labels: approved, size/M

#8329 fix: restore failed due to incorrect backup path
  controllers/apps/cluster_controller_test.go
  controllers/apps/transformer_cluster_backup_policy.go
Labels: approved, size/XS

#8138 fix: endless affinity list when there's a DataPlaneAffinity
  pkg/controller/scheduling/scheduling_utils.go
  pkg/controller/scheduling/scheduling_utils_test.go
  pkg/testutil/apps/cluster_factory.go
Labels: approved, size/M

#8337 fix: replicas of the backup's sts is 0
  controllers/dataprotection/backup_controller_test.go
  pkg/dataprotection/action/action_stateful.go
Labels: approved, size/S

#8336 fix: replicas of the backup's sts is 0
  controllers/apps/opsrequest_controller_test.go
  controllers/dataprotection/backup_controller_test.go
  pkg/dataprotection/action/action_stateful.go
Labels: approved, size/S

#8343 chore: improve calculate mysql buffer pool size in 0.9
  pkg/controller/configuration/builtin_functions.go
  pkg/controller/configuration/config_template_test.go
Labels: approved, size/M

#8345 fix: config-related resource cannot be cleaned up after disable addons
  controllers/apps/componentdefinition_controller.go
  controllers/apps/configuration/config_util.go
Labels: approved, size/M

#8354 feat: toggle to disable helm render-time validation of encryptionKeySecretKeyRef
  deploy/helm/templates/_dataprotection.tpl
  deploy/helm/values.yaml
Labels: size/S, pre-approve

#8200 fix: check data field for user provided tls
  pkg/controller/plan/tls_utils.go
  pkg/controller/plan/tls_utils_test.go
Labels: approved, size/M

#8366 chore: update cluster print colums
  apis/apps/v1/cluster_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
Labels: approved, size/S

#8358 fix: don't delete config resources while deleting the cluster definition CRs
  controllers/apps/clusterdefinition_controller.go
Labels: approved, size/XS

#8084 chore: filter events to reconcile by CRD API version
  cmd/dataprotection/main.go
  cmd/manager/main.go
  controllers/apps/backuppolicytemplate_controller.go
  controllers/apps/class_controller.go
  controllers/apps/cluster_controller.go
  controllers/apps/cluster_plan_builder.go
  controllers/apps/clusterdefinition_controller.go
  controllers/apps/clusterversion_controller.go
  controllers/apps/component_controller.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/componentversion_controller.go
  controllers/apps/configuration/configconstraint_controller.go
  controllers/apps/configuration/configuration_controller.go
  controllers/apps/configuration/reconfigure_controller.go
  controllers/apps/opsdefinition_controller.go
  controllers/apps/opsrequest_controller.go
  controllers/apps/servicedescriptor_controller.go
  controllers/apps/systemaccount_controller.go
  controllers/dataprotection/actionset_controller.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backuppolicy_controller.go
  controllers/dataprotection/backuprepo_controller.go
  controllers/dataprotection/backupschedule_controller.go
  controllers/dataprotection/gc_controller.go
  controllers/dataprotection/log_collection_controller.go
  controllers/dataprotection/restore_controller.go
  controllers/dataprotection/storageprovider_controller.go
  controllers/dataprotection/volumepopulator_controller.go
  controllers/experimental/nodecountscaler_controller.go
  controllers/extensions/addon_controller.go
  controllers/k8score/event_controller.go
  controllers/storage/storageprovider_controller.go
  controllers/workloads/instanceset_controller.go
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  pkg/constant/annotations.go
  pkg/controllerutil/predicate.go
Labels: approved, size/L

#8365 fix: custom ops failed when the component is a shard component
  controllers/apps/operations/custom.go
  controllers/apps/operations/custom/utils.go
  controllers/apps/operations/custom_test.go
  controllers/apps/operations/ops_manager.go
Labels: approved, size/L

#8370 fix: custom ops failed when the component is a shard component
  pkg/operations/custom.go
  pkg/operations/custom/utils.go
  pkg/operations/custom_test.go
  pkg/operations/upgrade.go
Labels: approved, size/L

#8372 fix: switchover ops is alwasy running
  controllers/apps/operations/switchover_test.go
  pkg/controller/component/job_utils.go
  pkg/controller/component/job_utils_test.go
Labels: size/S
