Repository apecloud/kubeblocks, pull requests merged in 2024-08, with the labels that each got.

#7902 feat: support FeatureGateComponentReplicasAnnotation feature gate
  cmd/manager/main.go
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  pkg/constant/flag.go
  pkg/controller/factory/builder.go
Labels: approved, size/S

#7909 docs: fix image errors
  docs/api_docs/kubeblocks-for-apecloud-mysql/high-availability/high-availability.md
  docs/api_docs/kubeblocks-for-apecloud-mysql/proxy/apecloud-mysql-proxy.md
  docs/api_docs/kubeblocks-for-elasticsearch/manage-elasticsearch.md
  docs/api_docs/kubeblocks-for-kafka/configuration/configuration.md
  docs/user_docs/maintenance/_category_.yaml
  docs/user_docs/maintenance/backup-and-restore/_category_.yaml
  docs/user_docs/maintenance/backup-and-restore/backup/_category_.yaml
  docs/user_docs/maintenance/backup-and-restore/backup/backup-repo.md
  docs/user_docs/maintenance/backup-and-restore/backup/configure-backuppolicy.md
  docs/user_docs/maintenance/backup-and-restore/backup/on-demand-backup.md
  docs/user_docs/maintenance/backup-and-restore/backup/scheduled-backup.md
  docs/user_docs/maintenance/backup-and-restore/introduction.md
  docs/user_docs/maintenance/backup-and-restore/restore/_category_.yaml
  docs/user_docs/maintenance/backup-and-restore/restore/pitr.md
  docs/user_docs/maintenance/backup-and-restore/restore/restore-data-from-backup-set.md
  docs/user_docs/maintenance/resource-scheduling/_category_.yml
  docs/user_docs/maintenance/resource-scheduling/resource-scheduling.md
Labels: approved, size/M

#7891 feat: set workload image pull secrets
  cmd/dataprotection/main.go
  cmd/manager/main.go
  controllers/apps/operations/custom/action_exec.go
  controllers/apps/operations/datascript.go
  controllers/apps/operations/rebuild_instance_inplace.go
  controllers/dataprotection/utils.go
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/templates/serviceaccount.yaml
  pkg/constant/const.go
  pkg/controller/builder/builder_pod.go
  pkg/controller/builder/builder_service_account.go
  pkg/controller/factory/builder.go
  pkg/controllerutil/pod_utils.go
  pkg/controllerutil/pod_utils_test.go
Labels: approved, size/L

#7788 chore: disable zero replicas by default
  controllers/apps/component_controller_test.go
  controllers/apps/transformer_component_validation.go
Labels: approved, size/M

#7915 chore: Removed name length limit for config template (#5841)
  apis/apps/v1alpha1/type.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
Labels: approved, size/S

#7775 chore: remove volumes from cd
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  controllers/apps/component_hscale_volume_populator.go
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/labels.go
  pkg/controller/apiconversion/simplified_cluster_api.go
  pkg/controller/component/definition_convertor.go
  pkg/controller/component/definition_convertor_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
  pkg/controller/plan/restore_test.go
  pkg/testutil/apps/constant.go
  pkg/testutil/apps/pvc_factoy.go
Labels: approved, size/L

#7767 chore: remove the character-type
  apis/apps/v1alpha1/clusterdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  controllers/apps/operations/datascript.go
  controllers/apps/transformer_component_tls.go
  controllers/apps/transformer_component_tls_test.go
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/lorry.go
  pkg/controller/component/definition_convertor.go
  pkg/controller/component/definition_convertor_test.go
  pkg/controller/component/lorry_utils_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/factory/builder_test.go
  pkg/controller/plan/tls_utils.go
  pkg/testutil/apps/componentdefinition_factory.go
  pkg/testutil/apps/constant.go
Labels: approved, size/L

#7768 chore: remove comp and service reference from cd
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/cluster_types_test.go
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  controllers/apps/transformer_component_vars.go
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/definition_convertor.go
  pkg/controller/component/definition_convertor_test.go
  pkg/controller/component/fieldref_util.go
  pkg/controller/component/fieldref_util_test.go
  pkg/controller/component/service_descriptor_utils_test.go
  pkg/controller/component/service_reference_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/testutil/apps/clusterdef_factory.go
Labels: approved, size/XXL

#7771 chore: remove config & script templates and log configs from cd
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/cluster_types_test.go
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/clusterdefinition_types_test.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  controllers/apps/cluster_controller_test.go
  controllers/apps/clusterdefinition_controller.go
  controllers/apps/clusterdefinition_controller_test.go
  controllers/apps/component_controller_test.go
  controllers/apps/configuration/config_util.go
  controllers/apps/configuration/config_util_test.go
  controllers/apps/configuration/configconstraint_controller.go
  controllers/apps/configuration/configconstraint_controller_test.go
  controllers/apps/configuration/configuration_controller_test.go
  controllers/apps/configuration/configuration_test.go
  controllers/apps/configuration/policy_util_test.go
  controllers/apps/operations/reconfigure_test.go
  controllers/apps/operations/suite_test.go
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/configuration/core/configtemplate_util.go
  pkg/configuration/core/configtemplate_util_test.go
  pkg/controller/component/definition_convertor.go
  pkg/controller/component/definition_convertor_test.go
  pkg/controller/configuration/configuration_test.go
  pkg/controller/configuration/envfrom_utils_test.go
  pkg/controller/configuration/operator_test.go
  pkg/controller/configuration/pipeline_test.go
  pkg/controller/configuration/resource_wrapper_test.go
  pkg/controller/configuration/template_wrapper_test.go
  pkg/controller/configuration/tool_image_builder_test.go
  pkg/controller/instanceset/object_builder.go
  pkg/controller/plan/restore_test.go
  pkg/kb_agent/cronjobs/checkrole.go
  pkg/kb_agent/cronjobs/job_test.go
  pkg/kb_agent/cronjobs/manager_test.go
  pkg/kb_agent/handlers/exec_handler_test.go
  pkg/kb_agent/handlers/grpc_handler_test.go
  pkg/kb_agent/httpserver/apis_test.go
  pkg/kb_agent/httpserver/server_test.go
  pkg/lorry/engines/dbmanager_mock.go
  pkg/testutil/apps/cluster_instance_set_test_util.go
  pkg/testutil/apps/clusterdef_factory.go
Labels: approved, size/XXL

#7776 chore: remove services, accounts and post-start from cd
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/clusterdefinition_types_test.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  controllers/apps/cluster_controller_test.go
  controllers/apps/component_controller_test.go
  controllers/apps/componentdefinition_controller_test.go
  controllers/apps/operations/expose.go
  controllers/apps/operations/expose_test.go
  controllers/apps/transformer_cluster_credential.go
  controllers/apps/transformer_cluster_service.go
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/component_test.go
  pkg/controller/component/definition_convertor.go
  pkg/controller/component/definition_convertor_test.go
  pkg/controller/factory/builder_test.go
  pkg/testutil/apps/clusterdef_factory.go
  pkg/testutil/apps/constant.go
Labels: approved, size/XXL

#7765 chore: remove the conn-credential
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  controllers/apps/cluster_controller.go
  controllers/apps/operations/datascript.go
  controllers/apps/operations/datascript_test.go
  controllers/apps/operations/switchover_util.go
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/apps/transformer_cluster_credential.go
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  go.mod
  pkg/configuration/config_manager/handler_util.go
  pkg/constant/const.go
  pkg/constant/pattern.go
  pkg/controller/component/component_test.go
  pkg/controller/component/its_convertor.go
  pkg/controller/component/lorry_utils.go
  pkg/controller/component/service_descriptor_utils.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/configuration/builtin_env.go
  pkg/controller/configuration/config_utils.go
  pkg/controller/configuration/tool_image_builder_test.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
  pkg/testutil/apps/clusterdef_factory.go
Labels: approved, size/XL

#7831 feat: support filtering backup target pods by the alternative label selector
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  config/crd/bases/dataprotection.kubeblocks.io_restores.yaml
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/utils.go
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_restores.yaml
  docs/developer_docs/api-reference/backup.md
  docs/developer_docs/api-reference/cluster.md
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/utils/utils.go
Labels: approved, size/XXL

#7929 chore: fix cluster is always running when existing running opsRequest
  controllers/apps/opsrequest_controller.go
Labels: approved, size/XS

#7936 fix: use len function to check targetPods slice
  controllers/dataprotection/utils.go
Labels: approved, size/XS

#7937 chore: avoid dependency on pkg k8s.io/kubernetes
  apis/apps/v1alpha1/cluster_types.go
  cmd/manager/main.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_opsdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  config/crd/bases/dataprotection.kubeblocks.io_restores.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/transform_utils.go
  controllers/apps/transform_utils_test.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_restores.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  docs/developer_docs/api-reference/cluster.md
  go.mod
  go.sum
  pkg/client/informers/externalversions/factory.go
  pkg/constant/flag.go
  pkg/controller/builder/builder_instance_set_test.go
  pkg/controller/builder/builder_pvc.go
  pkg/controller/builder/builder_pvc_test.go
  pkg/controller/builder/builder_stateful_set_test.go
  pkg/controller/configuration/config_template_test.go
  pkg/controller/instanceset/in_place_update_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/suite_test.go
  pkg/controller/kubebuilderx/plan_builder_test.go
  pkg/controllerutil/pod_utils_test.go
  pkg/lorry/client/k8sexec_client.go
  pkg/testutil/apps/cluster_util.go
  pkg/testutil/apps/native_object_util.go
  pkg/testutil/apps/pvc_factoy.go
  pkg/testutil/dataprotection/restore_factory.go
  test/e2e/e2e_suite_test.go
  test/e2e/util/client.go
  test/e2e/util/common.go
Labels: approved, size/XXL

#7940 chore: remove cd ref from backup policy template
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  controllers/apps/backuppolicytemplate_controller.go
  controllers/apps/backuppolicytemplate_controller_test.go
  controllers/apps/cluster_controller_test.go
  controllers/apps/component_hscale_volume_populator.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/apps/transformer_component_rbac.go
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/labels.go
  pkg/controller/plan/restore_test.go
  pkg/testutil/apps/backuppolicytemplate_factory.go
Labels: approved, size/L

#7905 fix: generate rbac permissions to list deployments
  config/rbac/role.yaml
  controllers/extensions/addon_controller.go
  deploy/helm/config/rbac/role.yaml
Labels: approved, size/S

#7955 chore: split push check and test
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
Labels: approved, size/L

#7956 fix: Rectify the Issue with 'timeoutSecond' Parameter functioning wrong…
  controllers/apps/operations/ops_manager.go
Labels: size/XS, pre-approve

#7957 fix: lorry crash when using hostnetwork
  controllers/apps/transformer_component_hostnetwork.go
Labels: approved, size/S

#7953 chore: increase the range of maxReplicasLimit and set default value o…
  apis/apps/v1alpha1/componentdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/transformer_component_validation.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
Labels: size/S, pre-approve

#7961 chore: update social media links
  README.md
Labels: approved, size/S

#7859 feat: support backuppolicy specify port by name.
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/restore_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  docs/developer_docs/api-reference/backup.md
  docs/developer_docs/api-reference/cluster.md
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/restore/builder.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/utils/envvar.go
  pkg/dataprotection/utils/utils.go
  pkg/testutil/dataprotection/backup_utils.go
  pkg/testutil/dataprotection/constant.go
Labels: size/XL, pre-approve

#7907 chore: re-define the switchover action
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/opsrequest_validation.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/operations/switchover_util.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/XXL

#7966 chore: fix staticcheck errors
  controllers/apps/configuration/config_util.go
  controllers/apps/configuration/configuration_controller.go
  controllers/extensions/addon_controller_stages.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/kb_agent/handlers/errors.go
  pkg/lorry/client/httpclient.go
  pkg/lorry/client/httpclient_test.go
  pkg/lorry/engines/models/errors.go
Labels: approved, size/M

#7972 chore: skip check docs pr issue
  .github/utils/issue_link.sh
Labels: approved, size/XS

#7970 docs: Align case for Maintenance label
  docs/user_docs/maintenance/_category_.yaml
Labels: size/XS, pre-approve

#7971 chore: lifecycle action job supports default cluster tolerations
  controllers/apps/operations/switchover_util.go
  pkg/controller/component/action_utils.go
Labels: approved, size/M

#7975 chore: lifecycle action job supports default cluster tolerations
  controllers/apps/operations/switchover_util.go
  pkg/controller/component/component_post_provision.go
  staticcheck.conf
Labels: size/M

#7979 chore: trigger all branch push
  .github/workflows/cicd-push.yml
Labels: size/M

#7980 chore: cherry pick cicd workflow optimize
  .github/utils/issue_link.sh
  .github/workflows/cherry-pick.yml
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/codeql.yml
  .github/workflows/e2e-fault.yml
  .github/workflows/e2e-performance.yml
  .github/workflows/e2e-smoke.yml
  .github/workflows/issues-addtoproject.yml
  .github/workflows/issues-labeluserdoc.yml
  .github/workflows/issues-move.yml
  .github/workflows/issues-tagstale.yml
  .github/workflows/merge-e2e-smoke.yml
  .github/workflows/milestone-set.yaml
  .github/workflows/milestoneclose.yml
  .github/workflows/package-version.yml
  .github/workflows/pull-request-check.yml
  .github/workflows/pull-request-label-approve.yaml
  .github/workflows/pull-request-label-size.yaml
  .github/workflows/pull-request-review.yaml
  .github/workflows/pull-request-stats.yml
  .github/workflows/pull-request-user-interaction.yaml
  .github/workflows/release-create.yml
  .github/workflows/release-delete.yml
  .github/workflows/release-helm-chart.yml
  .github/workflows/release-notes.yaml
  .github/workflows/release-sync.yml
  .github/workflows/release-version.yml
  .github/workflows/renew-issue.yml
  .github/workflows/trigger-release.yml
  README.md
Labels: approved, size/XL

#7968 chore: remove datascript ops
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/release-image.yml
  apis/apps/v1alpha1/opsrequest_conditions.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/opsrequest_validation.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/datascript.go
  controllers/apps/operations/datascript_test.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  docker/Dockerfile-datascript
  docker/docker.mk
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/const.go
Labels: approved, size/XXL

#7977 feat: add validation for PodUpdatePolicy
  apis/apps/v1alpha1/cluster_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
Labels: size/S, pre-approve

#7978 feat: Supports upper-layer modification of the InstanceSet's UpdateStrategy
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/instanceset_types.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/configuration/reconfigure_policy.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_component_workload.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  pkg/controller/builder/builder_component.go
  pkg/controller/builder/builder_instance_set.go
  pkg/controller/builder/builder_instance_set_test.go
  pkg/controller/component/component.go
  pkg/controller/component/rsm_convertor.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/factory/builder_test.go
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/instanceset/reconciler_update_test.go
  pkg/controller/instanceset/revision_util_test.go
  pkg/controller/instanceset/update_plan.go
  pkg/controller/instanceset/update_plan_test.go
  pkg/testutil/apps/instance_set_factoy.go
Labels: size/XL, pre-approve

#7984 feat: add validation for PodUpdatePolicy
  apis/apps/v1alpha1/cluster_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
Labels: size/S, pre-approve

#7986 chore: support to reference cluster and service type in vars
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: approved, size/L

#7985 chore: obtain pods for specific roles
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: approved, size/L

#8004 docs: fix cn doc errors
  i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/kubeblocks-for-apecloud-mysql.md
Labels: approved, size/XS

#8003 chore: upgrade release addon workflow version
  .github/workflows/release-helm-chart.yml
Labels: approved, size/XS

#8005 docs: fix cn doc errors
  i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/kubeblocks-for-apecloud-mysql.md
Labels: approved, size/XS

#7993 fix: simply fix panic when service ports changed
  controllers/apps/transformer_cluster_service.go
Labels: approved, size/XS

#8010 chore: fix null addon.spec.helm.installValues value
  deploy/helm/templates/_addon.tpl
  deploy/helm/templates/applications/alertmanager-webhook-adaptor-addon.yaml
  deploy/helm/templates/applications/apecloud-otel-collector-addon.yaml
  deploy/helm/templates/applications/aws-loadbalancer-controller-addon.yaml
  deploy/helm/templates/applications/csi-driver-addon.yaml
  deploy/helm/templates/applications/csi-driver-nfs-addon.yaml
  deploy/helm/templates/applications/csi-hostpath-driver-addon.yaml
  deploy/helm/templates/applications/grafana-addon.yaml
  deploy/helm/templates/applications/loki-addon.yaml
  deploy/helm/templates/applications/prometheus-addon.yaml
  deploy/helm/templates/applications/snapshot-controller-addon.yaml
  deploy/helm/templates/applications/vmagent-addon.yaml
Labels: approved, size/M

#7990 chore: take template vars as dynamic parameters of action
  pkg/controller/component/lifecycle/kbagent.go
Labels: approved, size/M

#7969 chore: impl switchover, post-provision and pre-terminate with kb-agent
  apis/apps/v1alpha1/componentdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/component_controller.go
  controllers/apps/operations/switchover_util.go
  controllers/apps/transformer_component_account_provision.go
  controllers/apps/transformer_component_deletion.go
  controllers/apps/transformer_component_post_provision.go
  controllers/apps/transformer_component_pre_terminate.go
  controllers/apps/transformer_component_restore.go
  controllers/apps/transformer_component_workload.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/action_post_provision.go
  pkg/controller/component/action_post_provision_test.go
  pkg/controller/component/action_pre_terminate.go
  pkg/controller/component/action_pre_terminate_test.go
  pkg/controller/component/action_utils.go
  pkg/controller/component/action_utils_test.go
  pkg/controller/component/lifecycle/kbagent.go
  pkg/controller/component/lifecycle/lfa_account.go
  pkg/controller/component/lifecycle/lfa_common.go
  pkg/controller/component/lifecycle/lfa_component.go
  pkg/controller/component/lifecycle/lfa_member.go
  pkg/controller/component/lifecycle/lfa_role.go
  pkg/controller/component/lifecycle/lifecycle.go
  pkg/controller/job/job_utils.go
  pkg/controller/plan/restore.go
  pkg/controller/plan/restore_test.go
Labels: approved, size/XXL

#8012 chore: set action env for kb-agent container
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/kbagent.go
Labels: approved, size/XL

#8002 feat: support generate primary and public key for sshd
  go.mod
  go.sum
  pkg/gotemplate/sshkeygenerator.go
  pkg/gotemplate/sshkeygenerator_test.go
  pkg/gotemplate/tpl_engine.go
  pkg/gotemplate/tpl_engine_test.go
Labels: area/user-interaction, approved, size/L

#8009 chore: incorrect responses of kbagent under different request situations
  pkg/kbagent/proto/proto.go
  pkg/kbagent/service/action.go
  pkg/kbagent/service/action_test.go
  pkg/kbagent/service/command.go
  pkg/kbagent/service/command_test.go
  pkg/kbagent/service/probe_test.go
  pkg/kbagent/service/service_test.go
  pkg/kbagent/service/suite_test.go
Labels: approved, size/XL

#8015 chore: provision accounts with the role selector in Action
  controllers/apps/transformer_component_account_provision.go
Labels: approved, size/S

#8020 chore: fix helm invalid null values
  deploy/helm/templates/applications/apecloud-otel-collector-addon.yaml
  deploy/helm/templates/applications/csi-driver-nfs-addon.yaml
  deploy/helm/templates/applications/grafana-addon.yaml
  deploy/helm/templates/applications/loki-addon.yaml
Labels: approved, size/S

#8021 chore: fix helm invalid null values (#8020)
  deploy/helm/templates/applications/apecloud-otel-collector-addon.yaml
  deploy/helm/templates/applications/csi-driver-nfs-addon.yaml
  deploy/helm/templates/applications/grafana-addon.yaml
  deploy/helm/templates/applications/loki-addon.yaml
Labels: size/S

#8014 chore: test cases for kb-agent and lifecycle actions in controller
  pkg/controller/component/kbagent_test.go
  pkg/controller/component/lifecycle/errors.go
  pkg/controller/component/lifecycle/kbagent.go
  pkg/controller/component/lifecycle/lfa_component.go
  pkg/controller/component/lifecycle/lfa_member.go
  pkg/controller/component/lifecycle/lfa_role.go
  pkg/controller/component/lifecycle/lifecycle.go
  pkg/controller/component/lifecycle/lifecycle_test.go
  pkg/controller/component/lifecycle/suite_test.go
Labels: approved, size/XXL

#8035 chore: remove all scope of the opsDefinition
  apis/apps/v1alpha1/opsdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_opsdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsdefinitions.yaml
Labels: size/XS

#8036 chore: remove some KB CRDs from the resource category all
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/componentresourceconstraint_types.go
  apis/apps/v1alpha1/opsdefinition_types.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/servicedescriptor_types.go
  apis/dataprotection/v1alpha1/restore_types.go
  apis/experimental/v1alpha1/nodecountscaler_types.go
  apis/workloads/legacy/replicatedstatemachine_types.go
  apis/workloads/v1alpha1/instanceset_types.go
  config/crd/bases/apps.kubeblocks.io_componentresourceconstraints.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_opsdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  config/crd/bases/apps.kubeblocks.io_servicedescriptors.yaml
  config/crd/bases/dataprotection.kubeblocks.io_restores.yaml
  config/crd/bases/experimental.kubeblocks.io_nodecountscalers.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentresourceconstraints.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/apps.kubeblocks.io_servicedescriptors.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_restores.yaml
  deploy/helm/crds/experimental.kubeblocks.io_nodecountscalers.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
Labels: approved, size/M

#8030 chore: support component short name var reference
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: approved, size/M

#8026 chore: remove the deprecated StorageProvider CRD
  PROJECT
  apis/storage/v1alpha1/doc.go
  apis/storage/v1alpha1/groupversion_info.go
  apis/storage/v1alpha1/register.go
  apis/storage/v1alpha1/storageprovider_types.go
  apis/storage/v1alpha1/type.go
  apis/storage/v1alpha1/zz_generated.deepcopy.go
  cmd/dataprotection/main.go
  cmd/manager/main.go
  config/crd/bases/storage.kubeblocks.io_storageproviders.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_storage_storageproviders.yaml
  config/crd/patches/webhook_in_storage_storageproviders.yaml
  config/rbac/role.yaml
  config/rbac/storage_storageprovider_editor_role.yaml
  config/rbac/storage_storageprovider_viewer_role.yaml
  controllers/apps/cluster_plan_builder.go
  controllers/dataprotection/backuprepo_controller.go
  controllers/dataprotection/backuprepo_controller_test.go
  controllers/dataprotection/suite_test.go
  controllers/storage/const.go
  controllers/storage/storageprovider_controller.go
  controllers/storage/storageprovider_controller_test.go
  controllers/storage/suite_test.go
  deploy/helm/config/rbac/role.yaml
  deploy/helm/crds/storage.kubeblocks.io_storageproviders.yaml
  deploy/helm/templates/storageprovider/legacy.yaml
  hack/client-sdk-gen.sh
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/storage/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/storage/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/storage/v1alpha1/fake/fake_storage_client.go
  pkg/client/clientset/versioned/typed/storage/v1alpha1/fake/fake_storageprovider.go
  pkg/client/clientset/versioned/typed/storage/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/storage/v1alpha1/storage_client.go
  pkg/client/clientset/versioned/typed/storage/v1alpha1/storageprovider.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/storage/interface.go
  pkg/client/informers/externalversions/storage/v1alpha1/interface.go
  pkg/client/informers/externalversions/storage/v1alpha1/storageprovider.go
  pkg/client/listers/storage/v1alpha1/expansion_generated.go
  pkg/client/listers/storage/v1alpha1/storageprovider.go
  pkg/dataprotection/backup/suite_test.go
Labels: approved, size/XXL

#8046 chore: remove legacy cluster DAG execute priority
  controllers/apps/cluster_plan_builder.go
Labels: approved, size/S

#8049 docs: update slack link
  README.md
Labels: approved, size/XS

#8056 chore: add etcd addon
  deploy/helm/templates/addons/etcd-addon.yaml
Labels: approved, size/S

#8057 chore: add etcd addon
  deploy/helm/templates/addons/etcd-addon.yaml
Labels: approved, size/S

#8059 feat: support NoRSMEnv feature gate
  cmd/manager/main.go
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  pkg/constant/flag.go
  pkg/controller/instanceset/object_builder.go
  pkg/controller/instanceset/reconciler_assistant_object.go
Labels: approved, size/S

#8060 feat: support NoRSMEnv feature gate (#8059)
  cmd/manager/main.go
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  pkg/constant/flag.go
  pkg/controller/instanceset/object_builder.go
  pkg/controller/instanceset/reconciler_assistant_object.go
Labels: approved, size/S
