Repository apecloud/kubeblocks, pull requests merged in 2024-02, with the labels that each got.

#6569 fix: support strong random passwd with mixed cases
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  apis/extensions/v1alpha1/zz_generated.deepcopy.go
  apis/storage/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  externalapis/preflight/v1beta2/zz_generated.deepcopy.go
  pkg/controller/factory/builder.go
  pkg/testutil/apps/clusterdef_factory.go
Labels: enhancement, approved, size/M

#6571 improve: provide more annotation control capabilities to control Comp…
  controllers/apps/transformer_component_service.go
  pkg/constant/const.go
Labels: size/M

#6575 chore: remove cluster component backward compatible code
  controllers/apps/transformer_cluster_component.go
Labels: approved, size/S

#6583 chore: do not inject lorry if unnecessary
  pkg/controller/component/lorry_utils.go
  pkg/lorry/engines/mysql/semi_sync_test.go
Labels: size/S

#6577 feat: lorry support apecloud pg
  config/lorry/components/binding_apecloud_postgresql.yaml
  pkg/constant/const.go
  pkg/lorry/engines/postgres/apecloudpostgres/manager.go
  pkg/lorry/engines/postgres/apecloudpostgres/manager_test.go
  pkg/lorry/engines/postgres/config.go
  pkg/lorry/engines/postgres/config_test.go
  pkg/lorry/highavailability/util.go
Labels: feature, size/M

#6585 fix: the backupPolicy can not add custom backupMethod
  controllers/apps/transformer_cluster_backup_policy.go
Labels: enhancement, approved, size/XS

#6580 chore: Split operator and addon for Separate Caching
  .github/workflows/release-sync.yml
Labels: approved, size/XS

#6587 fix: fix datasafed config for GCS
  deploy/helm/templates/storageprovider/gcs-s3comp.yaml
Labels: enhancement, size/XS

#6586 chore: update ob addon name
  deploy/helm/templates/addons/oceanbase-addon.yaml
Labels: approved, size/XS

#6590 fix: do not set CRON_TZ for cronJob schedule if kubernetes version less than 1.22
  go.mod
  pkg/dataprotection/backup/utils.go
  pkg/dataprotection/backup/utils_test.go
  pkg/dataprotection/utils/utils.go
  pkg/dataprotection/utils/utils_test.go
Labels: enhancement, size/L

#6568 chore: component definition system account support seed
  apis/apps/v1alpha1/clusterdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/transformer_component_account.go
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  pkg/common/password.go
  pkg/common/password_test.go
Labels: approved, size/L

#6494 feat: manage dedicated ServiceAccount for dataprotection worker pods
  cmd/dataprotection/main.go
  config/rbac/role.yaml
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/backuprepo_controller.go
  controllers/dataprotection/backuprepo_controller_test.go
  controllers/dataprotection/backupschedule_controller.go
  controllers/dataprotection/backupschedule_controller_test.go
  controllers/dataprotection/restore_controller.go
  controllers/dataprotection/restore_controller_test.go
  controllers/dataprotection/suite_test.go
  controllers/dataprotection/utils.go
  controllers/dataprotection/utils_test.go
  controllers/dataprotection/volumepopulator_controller.go
  controllers/dataprotection/volumepopulator_controller_test.go
  deploy/helm/config/rbac/role.yaml
  deploy/helm/templates/_dataprotection.tpl
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/rbac/clusterrole.yaml
  deploy/helm/templates/rbac/clusterrole_binding.yaml
  deploy/helm/templates/rbac/dataprotection_exec_worker_clusterrole.yaml
  deploy/helm/templates/rbac/dataprotection_exec_worker_clusterrolebinding.yaml
  deploy/helm/templates/serviceaccount.yaml
  deploy/helm/values.yaml
  pkg/dataprotection/backup/deleter.go
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/backup/scheduler.go
  pkg/dataprotection/restore/builder.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/manager_test.go
  pkg/dataprotection/types/constant.go
Labels: area/user-interaction, feature, size/XL

#6598 chore: support to set image pull secrets for addon chart image
  deploy/helm/templates/serviceaccount.yaml
  deploy/helm/values.yaml
Labels: approved, size/XS

#6597 fix: add tolerations to backuprepo precheck pods
  controllers/dataprotection/backuprepo_controller.go
Labels: enhancement, size/XS

#6601 docs: update supported engine features
  docs/user_docs/overview/supported-addons.md
  i18n/zh-cn/user-docs/overview/database-engines-supported.md
Labels: feature, documentation, size/S

#6605 fix: use restore.Spec.ServiceAccountName if not empty
  controllers/dataprotection/restore_controller.go
Labels: enhancement, size/XS

#6610 chore: refine controller.configuration, clean code redundancy and tidy up
  controllers/apps/configuration/configuration_controller.go
  controllers/apps/transformer_component_configuration.go
  pkg/controller/component/component.go
  pkg/controller/configuration/builtin_env_test.go
  pkg/controller/configuration/builtin_functions.go
  pkg/controller/configuration/builtin_objects.go
  pkg/controller/configuration/config_template.go
  pkg/controller/configuration/config_template_test.go
  pkg/controller/configuration/hostnetwork_utils.go
  pkg/controller/configuration/pipeline.go
  pkg/controller/configuration/template_merger_test.go
  pkg/controller/configuration/template_wrapper_test.go
Labels: approved, size/XL

#6612 chore: support kubeblocks operator metrics and gc runtime metrics (#6611)
  cmd/manager/main.go
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  go.mod
  go.sum
  pkg/constant/metrics.go
  pkg/metrics/runtime.go
Labels: area/user-interaction, approved, size/L

#6541 chore: add mysql/pg replication lag alert rule (#6540)
  deploy/helm/values.yaml
Labels: area/user-interaction, approved, size/S

#6603 feat(addon): Add version validation for Addon spec
  apis/extensions/v1alpha1/addon_types.go
Labels: feature, size/XS

#6617 chore: update api reference doc
  Makefile
  apis/apps/v1alpha1/doc.go
  apis/dataprotection/v1alpha1/doc.go
  apis/extensions/v1alpha1/doc.go
  docs/developer_docs/api-reference/add-on.md
  docs/developer_docs/api-reference/backup.md
  docs/developer_docs/api-reference/cluster.md
  docs/user_docs/lorryctl/cli.md
  docs/user_docs/lorryctl/lorryctl.md
  docs/user_docs/lorryctl/lorryctl_createuser.md
  docs/user_docs/lorryctl/lorryctl_deleteuser.md
  docs/user_docs/lorryctl/lorryctl_describeuser.md
  docs/user_docs/lorryctl/lorryctl_grant-role.md
  docs/user_docs/lorryctl/lorryctl_listsystemaccounts.md
  docs/user_docs/lorryctl/lorryctl_listusers.md
  docs/user_docs/lorryctl/lorryctl_revoke-role.md
  docs/user_docs/lorryctl/lorryctl_run.md
  docs/user_docs/lorryctl/lorryctl_switchover.md
  docs/user_docs/lorryctl/lorryctl_vault-plugin.md
Labels: documentation, size/XXL

#6620 chore: auto gen apis doc
  .github/utils/utils.sh
  .github/workflows/cicd-push.yml
  docs/developer_docs/api-reference/add-on.md
  docs/developer_docs/api-reference/backup.md
  docs/developer_docs/api-reference/cluster.md
Labels: documentation, size/M

#6618 chore: update api-reference doc
  .github/utils/utils.sh
  .github/workflows/cicd-push.yml
  Makefile
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/doc.go
  apis/apps/v1alpha1/opsdefinition_types.go
  apis/apps/v1alpha1/type.go
  apis/dataprotection/v1alpha1/doc.go
  apis/dataprotection/v1alpha1/restore_types.go
  apis/extensions/v1alpha1/addon_types.go
  apis/extensions/v1alpha1/doc.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_opsdefinitions.yaml
  config/crd/bases/dataprotection.kubeblocks.io_restores.yaml
  config/crd/bases/extensions.kubeblocks.io_addons.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsdefinitions.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_restores.yaml
  deploy/helm/crds/extensions.kubeblocks.io_addons.yaml
  docs/developer_docs/api-reference/add-on.md
  docs/developer_docs/api-reference/backup.md
  docs/developer_docs/api-reference/cluster.md
  docs/user_docs/lorryctl/cli.md
  docs/user_docs/lorryctl/lorryctl.md
  docs/user_docs/lorryctl/lorryctl_createuser.md
  docs/user_docs/lorryctl/lorryctl_deleteuser.md
  docs/user_docs/lorryctl/lorryctl_describeuser.md
  docs/user_docs/lorryctl/lorryctl_grant-role.md
  docs/user_docs/lorryctl/lorryctl_listsystemaccounts.md
  docs/user_docs/lorryctl/lorryctl_listusers.md
  docs/user_docs/lorryctl/lorryctl_revoke-role.md
  docs/user_docs/lorryctl/lorryctl_run.md
  docs/user_docs/lorryctl/lorryctl_switchover.md
  docs/user_docs/lorryctl/lorryctl_vault-plugin.md
Labels: documentation, approved, size/XXL

#6628 chore: change e2e test type
  .github/workflows/e2e-kbcli-k3s.yml
  .github/workflows/e2e-kbcli.yml
  .github/workflows/release-image.yml
Labels: test, approved, size/S

#6632 chore: tidy up API docs
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/clusterversion_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/componentclassdefinition_types.go
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/configconstraint_types.go
  apis/apps/v1alpha1/opsdefinition_types.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/servicedescriptor_types.go
  apis/apps/v1alpha1/type.go
  apis/dataprotection/v1alpha1/actionset_types.go
  apis/dataprotection/v1alpha1/backup_types.go
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  apis/dataprotection/v1alpha1/restore_types.go
  apis/dataprotection/v1alpha1/types.go
  apis/workloads/v1alpha1/replicatedstatemachine_types.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_clusterversions.yaml
  config/crd/bases/apps.kubeblocks.io_componentclassdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  config/crd/bases/apps.kubeblocks.io_opsdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  config/crd/bases/apps.kubeblocks.io_servicedescriptors.yaml
  config/crd/bases/dataprotection.kubeblocks.io_actionsets.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  config/crd/bases/dataprotection.kubeblocks.io_restores.yaml
  config/crd/bases/workloads.kubeblocks.io_replicatedstatemachines.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterversions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentclassdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/apps.kubeblocks.io_servicedescriptors.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_actionsets.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_restores.yaml
  deploy/helm/crds/workloads.kubeblocks.io_replicatedstatemachines.yaml
  docs/developer_docs/api-reference/backup.md
  docs/developer_docs/api-reference/cluster.md
Labels: documentation, size/XXL

#6579 chore: component post provision action support sharding topology
  pkg/controller/component/component_post_provision.go
  pkg/controller/component/component_post_provision_test.go
Labels: size/L

#6631 fix: remove duplicated ports on exposing
  controllers/apps/operations/expose.go
Labels: enhancement, approved, size/XS

#6626 chore: disable previous backup schedule if cluster backup method changed
  apis/apps/v1alpha1/cluster_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  controllers/apps/transformer_cluster_backup_policy.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/dataprotection/backup/scheduler.go
  pkg/dataprotection/utils/utils.go
Labels: ci, size/L

#6623 chore: refine backup policy template with GPT prompt
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: size/XL

#6644 chore: refine opsRequest/opsDefinition/BackupPolicyTemplate api doc
  apis/apps/v1alpha1/opsdefinition_types.go
  apis/apps/v1alpha1/opsrequest_types.go
  cmd/dataprotection/main.go
  config/crd/bases/apps.kubeblocks.io_opsdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: documentation, size/XXL

#6649 chore: refine add-on api doc
  apis/extensions/v1alpha1/addon_types.go
  apis/extensions/v1alpha1/doc.go
  config/crd/bases/extensions.kubeblocks.io_addons.yaml
  deploy/helm/crds/extensions.kubeblocks.io_addons.yaml
  docs/developer_docs/api-reference/add-on.md
Labels: documentation, size/XXL

#6636 chore: improve reload error log
  cmd/reloader/app/cmd.go
  pkg/configuration/config_manager/volume_watcher.go
Labels: approved, size/S

#6648 fix: dynamic parameters and static parameters are modified together for partoni postgresql, and the dynamic parameters do not take effect (#5450)
  apis/apps/v1alpha1/configconstraint_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
  controllers/apps/configuration/combine_upgrade_policy.go
  controllers/apps/configuration/combine_upgrade_policy_test.go
  controllers/apps/configuration/reconfigure_policy.go
  controllers/apps/configuration/sync_upgrade_policy.go
  deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/configuration/core/reconfigure_util.go
  pkg/configuration/core/reconfigure_util_test.go
Labels: enhancement, approved, size/L

#6660 chore: output more information when hscale failed
  config/rbac/dataprotection_backuptool_editor_role.yaml
  config/rbac/dataprotection_backuptool_viewer_role.yaml
  controllers/apps/component_hscale_volume_populator.go
  controllers/apps/transformer_component_status.go
  deploy/helm/templates/rbac/dataprotection_backuptool_editor_role.yaml
  deploy/helm/templates/rbac/dataprotection_backuptool_viewer_role.yaml
Labels: approved, size/L

#6662 chore: test kubeblocks on k8s 1.20
  deploy/helm/Chart.yaml
Labels: test, size/XS

#6663 chore: fix ci options parse error
  .github/workflows/e2e-kbcli-k3s.yml
Labels: enhancement, ci, size/S

#6637 chore: ignore policy/v1 discovery error at cluster deletion
  controllers/apps/transform_utils.go
  controllers/apps/transform_utils_test.go
Labels: size/M

#6667 chore: refine ServiceDescriptor & Component & ComponentDefinition API doc with GPT prompt
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/servicedescriptor_types.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_servicedescriptors.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_servicedescriptors.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: documentation, approved, size/XXL

#6665 fix: reconfiguring does not take effect (#6664)
  controllers/apps/configuration/reconfigure_policy.go
Labels: enhancement, approved, size/XS

#6669 chore: update RSM API doc by GPT
  apis/workloads/v1alpha1/replicatedstatemachine_types.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/workloads.kubeblocks.io_replicatedstatemachines.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/workloads.kubeblocks.io_replicatedstatemachines.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: documentation, size/XXL

#6658 chore: Decoupling the dependency between clusterComponent and configuration naming rules
  controllers/apps/component_controller.go
Labels: dependencies, approved, size/S

#6574 chore: pod inherit cluster labels by default
  controllers/apps/transformer_cluster_api_normalization.go
Labels: approved, size/XS

#6659 chore: refine configuration api doc (#6656)
  apis/apps/v1alpha1/config.go
  apis/apps/v1alpha1/configconstraint_types.go
  apis/apps/v1alpha1/configuration_types.go
  apis/apps/v1alpha1/type.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusterversions.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterversions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: documentation, approved, size/XXL

#6672 chore: set generate password allow repeat to true
  pkg/common/password.go
Labels: size/XS

#6678 docs: update cn installation doc
  i18n/zh-cn/user-docs/installation/install-with-helm/install-kubeblocks-with-helm.md
Labels: documentation, size/M

#6679 docs: fix format bugs in cn docs
  i18n/zh-cn/user-docs/installation/install-with-helm/install-kubeblocks-with-helm.md
Labels: documentation, bug, enhancement, size/S

#6674 chore: refine dataprotection api doc
  apis/dataprotection/v1alpha1/actionset_types.go
  apis/dataprotection/v1alpha1/backup_types.go
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  apis/dataprotection/v1alpha1/backupschedule_types.go
  apis/dataprotection/v1alpha1/restore_types.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/dataprotection.kubeblocks.io_actionsets.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backupschedules.yaml
  config/crd/bases/dataprotection.kubeblocks.io_restores.yaml
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_actionsets.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backupschedules.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_restores.yaml
  docs/developer_docs/api-reference/backup.md
Labels: documentation, size/XXL

#6687 feat: compatible with cronjob v1beta1
  cmd/dataprotection/main.go
  controllers/apps/component_hscale_volume_populator.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backupschedule_controller.go
  deploy/helm/templates/rbac/clusterrole.yaml
  pkg/controllerutil/suite_test.go
  pkg/controllerutil/volumesnapshot.go
  pkg/dataprotection/action/action.go
  pkg/dataprotection/action/action_create_vs.go
  pkg/dataprotection/action/action_exec.go
  pkg/dataprotection/action/action_job.go
  pkg/dataprotection/action/suite_test.go
  pkg/dataprotection/backup/deleter.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/utils/compat_client.go
  pkg/dataprotection/utils/compat_client_test.go
  pkg/dataprotection/utils/suit_test.go
  pkg/dataprotection/utils/utils.go
  pkg/dataprotection/utils/volumesnapshot.go
Labels: feature, size/XL

#6691 docs: fix indent
  i18n/zh-cn/user-docs/backup-and-restore/backup/backup-repo.md
  i18n/zh-cn/user-docs/kubeblocks-for-kafka/configuration/configuration.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql/proxy/apecloud-mysql-proxy.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql/proxy/introduction.md
  i18n/zh-cn/user-docs/observability/access-log.md
  i18n/zh-cn/user-docs/observability/configure-alert.md
Labels: documentation, enhancement, size/M

#6474 feat: lorry support executing action commands
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/componentdefinition_controller.go
  controllers/apps/componentdefinition_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/env.go
  pkg/controller/component/component_definition_convertor.go
  pkg/controller/component/component_definition_convertor_test.go
  pkg/controller/component/lorry_utils.go
  pkg/controller/component/lorry_utils_test.go
  pkg/controller/component/rsm_convertor.go
  pkg/controller/rsm/types.go
  pkg/lorry/operations/replica/checkrole.go
  pkg/lorry/util/command.go
  pkg/testutil/apps/constant.go
Labels: feature, size/XL

#6668 chore: Remove reload dependency on CharacterType (#6666)
  pkg/configuration/config_manager/config_handler.go
  pkg/configuration/config_manager/config_handler_test.go
  pkg/configuration/config_manager/reload_util.go
  pkg/controller/factory/builder.go
Labels: area/user-interaction, dependencies, approved, size/S

#6689 feat: mongodb supports connections from outside k8s using host network
  pkg/lorry/dcs/k8s.go
  pkg/lorry/dcs/types.go
  pkg/lorry/engines/base.go
  pkg/lorry/engines/custom/manager.go
  pkg/lorry/engines/dbmanager_mock.go
  pkg/lorry/engines/interface.go
  pkg/lorry/engines/mock.go
  pkg/lorry/engines/mongodb/commands.go
  pkg/lorry/engines/mongodb/manager.go
  pkg/lorry/engines/mysql/manager.go
  pkg/lorry/engines/postgres/manager.go
  pkg/lorry/engines/wesql/manager.go
  pkg/lorry/highavailability/ha.go
Labels: feature, approved, size/L

#6670 chore: build pod management policy from update strategy
  pkg/controller/component/rsm_convertor.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
Labels: area/user-interaction, size/M

#6693 chore: update api marker
  apis/apps/v1alpha1/componentdefinition_types.go
  docs/developer_docs/api-reference/cluster.md
Labels: size/XS

#6695 chore: do not generate lorryctl docs
  Makefile
  docs/user_docs/lorryctl/cli.md
  docs/user_docs/lorryctl/lorryctl.md
  docs/user_docs/lorryctl/lorryctl_createuser.md
  docs/user_docs/lorryctl/lorryctl_deleteuser.md
  docs/user_docs/lorryctl/lorryctl_describeuser.md
  docs/user_docs/lorryctl/lorryctl_grant-role.md
  docs/user_docs/lorryctl/lorryctl_listsystemaccounts.md
  docs/user_docs/lorryctl/lorryctl_listusers.md
  docs/user_docs/lorryctl/lorryctl_revoke-role.md
  docs/user_docs/lorryctl/lorryctl_run.md
  docs/user_docs/lorryctl/lorryctl_switchover.md
  docs/user_docs/lorryctl/lorryctl_vault-plugin.md
Labels: documentation, size/XL

#6697 chore: release ent addons chart
  .github/workflows/cicd-push.yml
  .github/workflows/release-helm-chart.yml
  .github/workflows/release-version.yml
Labels: release, size/L

#6715 fix: backup and restore failed when using hostnetwork
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  pkg/dataprotection/restore/builder.go
  pkg/dataprotection/utils/envvar.go
  pkg/dataprotection/utils/utils.go
Labels: enhancement, approved, size/M

#6713 chore: refine random generator
  pkg/controller/factory/builder.go
Labels: approved, size/XS

#6712 fix: expose with empty componentName
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/opsrequest_webhook.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/expose.go
  controllers/apps/operations/expose_test.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  pkg/lorry/engines/dbmanager_mock.go
Labels: enhancement, approved, size/L
