Repository apecloud/kubeblocks, pull requests merged in 2024-05, with the labels that each got.

#7233 fix: rename rsm webhooks to instanceset webhooks
  deploy/helm/templates/admission/webhookconfiguration.yaml
Labels: approved, size/S

#7231 chore: remove empty lines in api-doc
  docs/developer_docs/api-reference/add-on.md
  docs/developer_docs/api-reference/backup.md
  docs/developer_docs/api-reference/cluster.md
  hack/docgen/api/main.go
Labels: approved, size/XS

#7235 chore: update acpg switchover and delete cmpd for mongo
  examples/apecloud-postgresql/switchover.yaml
  examples/mongodb/README.md
  examples/mongodb/cluster-cmpd.yaml
Labels: size/M

#7232 chore: should report error when resolving partial required objects
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: size/L

#7228 fix: check if continuous backup was created via backupschedule
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
Labels: approved, size/M

#7105 fix: make provider and version of addon consistent (#7007)
  controllers/extensions/addon_controller.go
  controllers/extensions/addon_controller_stages.go
  controllers/extensions/addon_controller_test.go
  controllers/extensions/const.go
Labels: approved, size/L

#7237 fix: delete cluster failed after scaling out
  controllers/apps/transformer_component_deletion.go
  controllers/dataprotection/backup_controller.go
Labels: approved, size/XS

#7239 fix: exclude data-protection pods from kb service
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/templates/service.yaml
Labels: approved, size/XS

#7230 chore: update opsRequest and opsDefinition api
  apis/apps/v1alpha1/opsdefinition_types.go
  apis/apps/v1alpha1/opsrequest_conditions.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/opsrequest_webhook.go
  apis/apps/v1alpha1/opsrequest_webhook_test.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/backup.go
  controllers/apps/operations/custom.go
  controllers/apps/operations/custom/action_exec.go
  controllers/apps/operations/custom/action_workload.go
  controllers/apps/operations/custom/utils.go
  controllers/apps/operations/custom/workload_job.go
  controllers/apps/operations/custom/workload_pod.go
  controllers/apps/operations/custom_test.go
  controllers/apps/operations/datascript_test.go
  controllers/apps/operations/expose.go
  controllers/apps/operations/ops_util.go
  controllers/apps/operations/rebuild_instance.go
  controllers/apps/operations/reconfigure.go
  controllers/apps/operations/restore.go
  controllers/apps/operations/restore_test.go
  controllers/apps/opsrequest_controller.go
  deploy/helm/crds/apps.kubeblocks.io_opsdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/templates/opsdefinition.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/dataprotection/backup/scheduler.go
  pkg/testutil/apps/opsrequest_util.go
Labels: approved, size/XXL

#7241 chore: remove restore pass in examples
  examples/mogdb/restore.yaml
  examples/mongodb/restore-cmpd.yaml
  examples/mongodb/restore.yaml
  examples/qdrant/restore-cmpd.yaml
  examples/qdrant/restore.yaml
Labels: size/M

#7243 chore: set lifeCycleAction retryPolicy to execute job backoffLimit
  pkg/controller/component/component_lifecycle_action_utils.go
Labels: approved, size/XS

#7192 fix: set backuppolicy.spec.backofflimit to default value
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/dataprotection/backuppolicy_controller.go
  controllers/dataprotection/backuppolicy_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
Labels: approved, size/S

#7246 chore: git ignore client-sdk-gen generated temp directory
  .gitignore
Labels: approved, size/XS

#7245 fix: upgrade opsRequest is always running
  controllers/apps/operations/restart.go
  controllers/apps/operations/upgrade.go
  controllers/apps/operations/upgrade_test.go
  controllers/apps/operations/vertical_scaling.go
Labels: approved, size/M

#7249 chore: update monitor to monitorEnabled for solr and risingwave
  examples/risingwave/cluster.yaml
  examples/solr/cluster.yaml
Labels: size/XS

#7236 chore: refine configconstraint api
  apis/apps/v1alpha1/configconstraint_conversion.go
  apis/apps/v1alpha1/configconstraint_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/apps/v1beta1/configconstraint_types.go
  apis/apps/v1beta1/configconstraint_webhook.go
  apis/apps/v1beta1/meta.go
  apis/apps/v1beta1/zz_generated.deepcopy.go
  cmd/reloader/template/main.go
  config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
  controllers/apps/configuration/config_util.go
  controllers/apps/configuration/policy_util_test.go
  controllers/apps/configuration/reconfigure_controller.go
  controllers/apps/configuration/reconfigure_policy.go
  controllers/apps/configuration/sync_upgrade_policy.go
  controllers/apps/configuration/sync_upgrade_policy_test.go
  controllers/apps/operations/reconfigure_pipeline.go
  controllers/apps/operations/reconfigure_util.go
  deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/configuration/config_manager/builder.go
  pkg/configuration/config_manager/builder_test.go
  pkg/configuration/config_manager/config_handler.go
  pkg/configuration/config_manager/config_handler_test.go
  pkg/configuration/config_manager/handler_util.go
  pkg/configuration/config_manager/handler_util_test.go
  pkg/configuration/config_manager/reload_util.go
  pkg/configuration/config_manager/reload_util_test.go
  pkg/configuration/config_manager/type.go
  pkg/configuration/core/config.go
  pkg/configuration/core/config_patch_util.go
  pkg/configuration/core/config_patch_util_test.go
  pkg/configuration/core/config_test.go
  pkg/configuration/core/config_util.go
  pkg/configuration/core/config_util_test.go
  pkg/configuration/core/reconfigure_util.go
  pkg/configuration/core/reconfigure_util_test.go
  pkg/configuration/validate/config_validate.go
  pkg/configuration/validate/config_validate_test.go
  pkg/controller/configuration/envfrom_utils.go
  pkg/controller/configuration/operator_test.go
  pkg/controller/configuration/pipeline.go
  pkg/controller/configuration/pipeline_test.go
  pkg/controller/configuration/template_merger.go
  pkg/controller/configuration/template_merger_test.go
  pkg/controller/configuration/template_wrapper_test.go
  pkg/controller/configuration/tool_image_builder_test.go
  pkg/controllerutil/config_util.go
  pkg/controllerutil/config_util_test.go
  test/testdata/config/config-constraint.yaml
  test/testdata/config/envfrom-constraint.yaml
  test/testdata/operations_config/config-constraint.yaml
  test/testdata/resources/mysql-config-constraint-not-validate.yaml
  test/testdata/resources/mysql-config-constraint.yaml
  test/testdata/resources/mysql-consensus-config-constraint.yaml
Labels: approved, size/XXL

#7244 fix: unstable dataprotection unit test
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/backuprepo_controller_test.go
  controllers/dataprotection/backupschedule_controller_test.go
  controllers/dataprotection/gc_controller_test.go
  controllers/dataprotection/log_collection_controller_test.go
  controllers/dataprotection/restore_controller_test.go
  controllers/dataprotection/storageprovider_controller_test.go
Labels: approved, size/M

#7251 chore: remove cloud-provider-secret yaml
  deploy/helm/templates/applications/csi-s3-addon.yaml
  deploy/helm/templates/cloud-provider-secret.yaml
  deploy/helm/values.yaml
Labels: approved, size/M

#7206 fix: improve redis get role
  cmd/lorry/main.go
  pkg/common/types.go
  pkg/constant/env.go
  pkg/controller/component/lorry_utils.go
  pkg/controller/instanceset/pod_role_event_handler.go
  pkg/lorry/engines/redis/get_replica_role.go
  pkg/lorry/engines/redis/manager.go
  pkg/lorry/engines/redis/redis.go
  pkg/lorry/operations/replica/checkrole.go
Labels: approved, size/L

#7252 chore: create consistent backup policy name create by cd and cmpd
  controllers/apps/transformer_cluster_backup_policy.go
Labels: approved, size/S

#7255 chore: switchover operation support new api without clusterDefinition
  controllers/apps/operations/custom.go
  controllers/apps/operations/custom/utils.go
  controllers/apps/operations/expose.go
  controllers/apps/operations/switchover.go
  pkg/controller/component/component.go
Labels: approved, size/M

#7259 chore: reconfigure controller supports new api without clusterDefinition
  controllers/apps/configuration/config_reconcile_wrapper.go
Labels: approved, size/XS

#7263 chore: Compatible with ops api: clusterRef is renamed to clusterName
  controllers/apps/operations/reconfigure.go
Labels: approved, size/XS

#7265 fix: continuous backup will be deleted if cluster is deleted and pitr restore time format is invalid
  controllers/apps/operations/custom.go
  controllers/dataprotection/backup_controller.go
  pkg/dataprotection/backup/scheduler.go
  pkg/dataprotection/restore/utils.go
Labels: approved, size/XS

#7267 fix: duplicate volumemounts for the config-manager container (#7266)
  apis/apps/v1beta1/meta.go
  pkg/configuration/validate/config_validate.go
Labels: approved, size/XS

#7256 fix: remove the validation for cluster comp spec in webhook
  apis/apps/v1alpha1/cluster_webhook.go
  apis/apps/v1alpha1/cluster_webhook_test.go
Labels: approved, size/M

#7262 fix: replicas env error after h-scale
  pkg/controller/instanceset/object_builder.go
  pkg/controller/instanceset/object_builder_test.go
Labels: approved, size/M

#7270 fix: Mongodb config file permissions are too large (#7188)
  cmd/manager/main.go
Labels: approved, size/XS

#7182 fix: removed vmagent addon promethues scrape job (#7180)
  deploy/helm/templates/applications/vmagent-addon.yaml
  deploy/helm/templates/applications/vmagent-values.yaml
  deploy/helm/values.yaml
Labels: approved, size/L

#7077 fix: Check if the constraints on the kb version in annotations match (#6981)
  controllers/extensions/addon_controller_stages.go
  controllers/extensions/addon_controller_test.go
  controllers/extensions/const.go
Labels: approved, size/L

#7276 chore: update go.mod
  go.mod
Labels: approved, size/XS

#7275 fix: provision system accounts for legacy definitions
  controllers/apps/transformer_component_account_provision.go
Labels: approved, size/XS

#7153 feat: support to reference config across clusters
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_clusterversions.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterversions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_component.go
  pkg/controller/component/component.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/synthesize_component_test.go
Labels: area/user-interaction, approved, size/XXL

#7281 chore: mongodb is promoted problem
  pkg/lorry/engines/mongodb/manager.go
Labels: approved, size/XS

#7278 fix: Fixed null pointer error bug and added addon checks to support Kubernetes versions prior to 1.25.
  controllers/extensions/addon_controller_stages.go
  controllers/extensions/addon_controller_test.go
  controllers/extensions/const.go
Labels: approved, size/M

#7280 chore: tidy up built-in addons
  deploy/helm/templates/addons/clickhouse-addon.yaml
  deploy/helm/templates/addons/elasticsearch-addon.yaml
  deploy/helm/templates/addons/foxlake-addon.yaml
  deploy/helm/templates/addons/milvus-addon.yaml
  deploy/helm/templates/addons/oceanbase-addon.yaml
  deploy/helm/templates/addons/opensearch-addon.yaml
  deploy/helm/templates/addons/polardbx-addon.yaml
  deploy/helm/templates/addons/weaviate-addon.yaml
  deploy/helm/templates/addons/xinference-addon.yaml
  deploy/helm/templates/applications/bytebase-addon.yaml
  deploy/helm/templates/applications/jupyter-notebook-addon.yaml
  deploy/helm/templates/applications/jupyterhub-addon.yaml
Labels: approved, size/L

#7282 chore: determine the node port certainly at resolving service vars
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: approved, size/L

#7289 chore: fix trigger fork pr test
  .github/workflows/pull-request-label-approve.yaml
Labels: approved, size/S

#7288 chore: update clusterDefRef is optional in backupPolicyTemplate API
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  controllers/apps/backuppolicytemplate_controller.go
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/M

#7277 chore: cluster reconciliation premature stop
  controllers/apps/transformer_cluster_component.go
Labels: approved, size/XS

#7295 chore: staticcheck for fork pr test ci
  .github/workflows/cicd-pull-request.yml
Labels: approved, size/XS

#7296 chore: remove duplicated import
  controllers/apps/transformer_cluster_component.go
Labels: approved, size/XS

#7274 fix: addon controller adds support for checking if an addon is used by a cluster before deleting or disabling it.
  controllers/extensions/addon_controller_stages.go
  controllers/extensions/addon_controller_test.go
  controllers/extensions/suite_test.go
Labels: approved, size/L

#7297 chore: logical dead-lock if components provision and update orders out-of-order
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_cluster_component_test.go
Labels: approved, size/L

#7299 fix: add lorry ports to hostnetwork
  pkg/controller/component/lorry_utils.go
Labels: approved, size/S

#7285 chore: upgrade opsRequest is compatible with ComponentDefinition and ComponentVersion
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/opsrequest_webhook.go
  apis/apps/v1alpha1/opsrequest_webhook_test.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/componentversion_controller.go
  controllers/apps/componentversion_controller_test.go
  controllers/apps/operations/upgrade.go
  controllers/apps/operations/upgrade_test.go
  controllers/apps/opsrequest_controller.go
  controllers/apps/transformer_component_load_resources.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/component_version.go
  pkg/controller/component/component_version_test.go
  pkg/testutil/apps/component_version_util.go
  pkg/testutil/apps/opsrequest_util.go
Labels: approved, size/XXL

#7305 chore: support to create backupPolicy with multi-components that refers the same componentDefinition
  controllers/apps/operations/backup.go
  controllers/apps/transformer_cluster_backup_policy.go
Labels: size/M

#7304 chore: use prometheus operators servicemonitor to replace metricsstoreintegration api
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/cluster_plan_builder.go
  controllers/apps/component_controller.go
  controllers/apps/component_controller_test.go
  controllers/apps/monitor_integration_utils.go
  controllers/apps/suite_test.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_component_prometheus_integration.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  go.mod
  go.sum
  pkg/controller/builder/builder_component.go
  pkg/controller/component/component.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/generics/type.go
  pkg/testutil/apps/cluster_factory.go
  test/testdata/monitor/crd/monitoring.coreos.com_servicemonitors.yaml
Labels: approved, size/XXL

#7307 chore: add custom to builtin handler
  controllers/apps/componentdefinition_controller.go
Labels: approved, size/XS

#7312 chore: merge monitor-related and configconstraint api
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/configconstraint_conversion.go
  apis/apps/v1alpha1/configconstraint_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/apps/v1beta1/configconstraint_types.go
  apis/apps/v1beta1/meta.go
  apis/apps/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
  controllers/apps/componentSidecarContainerTransformer.go
  controllers/apps/component_controller.go
  controllers/apps/component_utils.go
  controllers/apps/configuration/config_util.go
  controllers/apps/configuration/sync_upgrade_policy.go
  controllers/apps/configuration/sync_upgrade_policy_test.go
  controllers/apps/suite_test.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_component_monitor_transformer.go
  controllers/apps/transformer_component_validation.go
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
  docs/developer_docs/api-reference/cluster.md
  go.mod
  go.sum
  pkg/common/monitor.go
  pkg/common/types.go
  pkg/configuration/config_manager/builder.go
  pkg/configuration/config_manager/builder_test.go
  pkg/configuration/config_manager/config_handler_test.go
  pkg/configuration/config_manager/handler_util.go
  pkg/configuration/config_manager/type.go
  pkg/configuration/validate/config_validate.go
  pkg/configuration/validate/config_validate_test.go
  pkg/controller/builder/builder_component.go
  pkg/controller/builder/builder_monitor_service.go
  pkg/controller/builder/builder_monitor_service_test.go
  pkg/controller/component/component.go
  pkg/controller/component/component_definition_convertor.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/factory/builder.go
  pkg/controllerutil/config_util_test.go
  pkg/controllerutil/metrics.go
  pkg/testutil/apps/common_util.go
  pkg/testutil/apps/constant.go
  test/testdata/config/config-constraint.yaml
  test/testdata/operations_config/config-constraint.yaml
  test/testdata/resources/mysql-config-constraint.yaml
  test/testdata/resources/mysql-consensus-config-constraint.yaml
Labels: size/XXL

#7311 chore: fix role handler
  controllers/k8score/event_controller_test.go
  pkg/controller/instanceset/pod_role_event_handler.go
  pkg/controller/instanceset/pod_role_event_handler_test.go
  pkg/controller/instanceset/types.go
  pkg/lorry/util/types.go
Labels: approved, size/S

#7302 chore: support to reference host-network ports
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/transformer_component_hostnetwork.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/component_definition_convertor.go
  pkg/controller/component/component_definition_convertor_test.go
  pkg/controller/component/utils.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
  pkg/controllerutil/controller_common.go
Labels: approved, size/XL

#7318 chore: add pre-approve label test for fork pr
  .github/workflows/cicd-pull-request.yml
  .github/workflows/pull-request-label-approve.yaml
Labels: approved, size/XS

#7317 chore: support to create backupPolicy with multi-components that refers the same componentDefinition
  controllers/apps/cluster_controller_test.go
  controllers/apps/component_controller_test.go
  controllers/apps/operations/ops_comp_helper.go
  controllers/apps/operations/volume_expansion.go
  controllers/apps/opsrequest_controller_test.go
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/apps/transformer_cluster_restore.go
  pkg/controller/component/synthesize_component.go
  pkg/controllerutil/sharding_utils.go
  pkg/testutil/apps/backuppolicytemplate_factory.go
Labels: approved, size/L

#7293 chore: ignore zz_generated.deepcopy.go files for gofmt and goimports
  Makefile
  pkg/controller/builder/builder_cluster_test.go
Labels: approved, size/XS

#7322 fix: pod update forever when resources.requests is nil
  pkg/controller/instanceset/in_place_update_util.go
Labels: approved, size/XS

#7323 fix: configmap 'xxx-rsm-env' not found
  controllers/apps/transformer_component_workload_upgrade.go
  pkg/controller/instanceset/utils.go
  pkg/controller/kubebuilderx/plan_builder_test.go
Labels: approved, size/S

#7315 chore: default value for host-network port references
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: approved, size/M

#7321 Revert "fix: exclude data-protection pods from kb service (#7239)"
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/templates/service.yaml
Labels: approved, size/XS

#7326 chore: remove unused field `Service` of InstanceSet
  apis/workloads/v1alpha1/instanceset_types.go
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/configuration/policy_util_test.go
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_instance_set.go
  pkg/controller/builder/builder_instance_set_test.go
  pkg/controller/factory/builder.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/object_builder.go
  pkg/controller/instanceset/object_builder_test.go
  pkg/controller/instanceset/suite_test.go
Labels: approved, size/M

#7328 fix: nil ptr on empty service descriptor
  pkg/controller/component/service_reference.go
Labels: approved, size/XS

#7310 fix: configuration mounted in subpath mode do not support dynamic update (#7306)
  controllers/apps/configuration/reconfigure_policy.go
  pkg/configuration/config_manager/config_handler.go
  pkg/configuration/config_manager/handler_util.go
  pkg/configuration/config_manager/handler_util_test.go
  pkg/configuration/config_manager/reload_util.go
  pkg/controller/configuration/config_utils.go
Labels: approved, size/L

#7330 chore: fix to sync cluster.spec.backup for each backupSchedule if exists muilt backupSchedule for same componentDef.
  controllers/apps/transformer_cluster_backup_policy.go
  pkg/dataprotection/backup/utils.go
Labels: approved, size/S

#7329 chore: remove dependency of synthesized component in lifecycle action excute
  controllers/apps/transformer_component_post_provision.go
  controllers/apps/transformer_component_restore.go
  pkg/controller/component/action_post_provision.go
  pkg/controller/component/action_post_provision_test.go
  pkg/controller/component/action_pre_terminate.go
  pkg/controller/component/action_pre_terminate_test.go
  pkg/controller/component/action_utils.go
  pkg/controller/component/action_utils_test.go
Labels: approved, size/L

#7332 fix: configuration mounted in subpath mode do not support dynamic update for pick release-0.8
  pkg/configuration/config_manager/config_handler.go
  pkg/configuration/config_manager/handler_util.go
  pkg/configuration/config_manager/handler_util_test.go
  pkg/configuration/config_manager/reload_util.go
  pkg/controller/configuration/config_utils.go
Labels: size/L

#7331 chore: fix 'go list' error
  go.mod
Labels: approved, size/S

#7335 chore: remove mock StatefulSet in pkg controllerutil&testutil (#7174)
  controllers/apps/operations/switchover_util.go
  pkg/controllerutil/pod_utils.go
  pkg/controllerutil/pod_utils_test.go
  pkg/controllerutil/stateful_set_utils.go
  pkg/controllerutil/stateful_set_utils_test.go
  pkg/testutil/apps/constant.go
  pkg/testutil/k8s/deployment_util.go
  pkg/testutil/k8s/instance_set_util.go
  pkg/testutil/k8s/pod_util.go
  pkg/testutil/k8s/statefulset_util.go
  pkg/testutil/type.go
Labels: size/XL

#7337 chore: fix 'make manifests inconsistent' error
  go.sum
Labels: approved, size/XS

#7338 fix: lint error
  pkg/testutil/apps/constant.go
Labels: size/XS

#7336 chore: emit InstanceSet event
  controllers/workloads/instanceset_controller.go
  pkg/controller/kubebuilderx/controller.go
  pkg/controller/kubebuilderx/plan_builder.go
Labels: approved, size/M

#7342 chore: refactor out copyAndMergeSts
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
Labels: approved, size/S

#7341 chore: merge updatable fields of service owned by InstanceSet
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
Labels: approved, size/S

#7344 chore: refactor out mergeMetadataMap
  pkg/controller/instanceset/instance_util.go
Labels: approved, size/S

#7345 chore: support to ignore role check during rebuilding instance
  controllers/apps/operations/rebuild_instance.go
  controllers/apps/operations/rebuild_instance_test.go
Labels: approved, size/M

#7346 chore: remove unused field `AlternativeServices` of InstanceSet
  apis/workloads/v1alpha1/instanceset_types.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/transformer_component_workload.go
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_instance_set.go
  pkg/controller/builder/builder_instance_set_test.go
  pkg/controller/instanceset/object_builder.go
  pkg/controller/instanceset/reconciler_assistant_object.go
Labels: approved, size/XXL

#7349 chore: no need to watch Pod in Component Controller anymore
  controllers/apps/component_controller.go
Labels: approved, size/S

#7351 chore: no need to watch StatefulSet in InstanceSet Controller anymore
  controllers/workloads/instanceset_controller.go
Labels: approved, size/XS

#7352 fix: add labels to distinguish kb and dataprotection
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
Labels: approved, size/M

#7354 chore: add labels to distinguish kb and dataprotection (#7352)
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
Labels: size/M

#7355 chore: fix rebuild ob instance failed due to no pod to be selected by label
  controllers/apps/operations/rebuild_instance.go
Labels: approved, size/XS

#7356 chore: udpate DP toleration and affinity
  deploy/helm/templates/dataprotection.yaml
Labels: approved, size/XS

#7358 fix: ob rebuild instance failed
  controllers/apps/operations/rebuild_instance.go
Labels: size/XS

#7357 chore: recover hasFailedAndTimeOutPod
  pkg/controller/instanceset/reconciler_status.go
Labels: approved, size/S

#7363 chore: typoes in extraLabels
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
Labels: approved, size/S

#7364 chore: workflow adjustment
  .github/workflows/cherry-pick.yml
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/e2e-fault.yml
  .github/workflows/e2e-performance.yml
  .github/workflows/e2e-smoke.yml
  .github/workflows/issues-addtoproject.yml
  .github/workflows/issues-labeluserdoc.yml
  .github/workflows/issues-move.yml
  .github/workflows/issues-tagstale.yml
  .github/workflows/merge-e2e-smoke.yml
  .github/workflows/milestone-set.yaml
  .github/workflows/milestoneclose.yml
  .github/workflows/package-version.yml
  .github/workflows/pull-request-check.yml
  .github/workflows/pull-request-label-approve.yaml
  .github/workflows/pull-request-label-size.yaml
  .github/workflows/pull-request-review.yaml
  .github/workflows/pull-request-stats.yml
  .github/workflows/pull-request-user-interaction.yaml
  .github/workflows/release-create.yml
  .github/workflows/release-delete.yml
  .github/workflows/release-helm-chart.yml
  .github/workflows/release-notes.yaml
  .github/workflows/release-sync.yml
  .github/workflows/release-version.yml
  .github/workflows/renew-issue.yml
  .github/workflows/trigger-release.yml
  README.md
Labels: approved, size/L

#7361 chore: wait to create pod rather than exit with Failed status when pod scheduling is blocked during instance rebuilding.
  controllers/apps/operations/rebuild_instance.go
  pkg/controller/instanceset/reconciler_status.go
  pkg/controllerutil/pod_utils.go
  pkg/dataprotection/action/action_stateful.go
Labels: approved, size/S

#7365 fix: make pvc creation idempotent
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/reconciler_instance_alignment.go
  pkg/controller/instanceset/reconciler_instance_alignment_test.go
Labels: approved, size/L

#7366 chore: replace "_" with "-" when generate secret name
  pkg/constant/pattern.go
Labels: approved, size/XS

#7367 chore: add length and pattern validation for service name
  apis/apps/v1alpha1/type.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
Labels: approved, size/M

#7369 chore: make all controllers enabled by helm values
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
Labels: approved, size/S

#7371 chore: make all feature gates enabled by helm values
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
Labels: approved, size/S

#7375 fix: when a component does not specify componentDefRef, each component will create a backupPolicy
  controllers/apps/transformer_cluster_backup_policy.go
Labels: size/XS

#7374 chore: ut for IsInstanceSetReady
  pkg/controller/instanceset/utils_test.go
Labels: approved, size/M

#7380 chore: remove roleArbitrator from componentDefinition
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_component_definition.go
  pkg/controller/component/definition_convertor.go
  pkg/controller/component/definition_convertor_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/testutil/apps/componentdefinition_factory.go
Labels: approved, size/L

#7378 chore: remove unused code and rename rsm convertor
  pkg/constant/pattern.go
  pkg/controller/component/its_convertor.go
  pkg/controller/component/its_convertor_test.go
Labels: approved, size/M

#7373 chore: remove component resources from config built-in objects
  pkg/controller/configuration/builtin_env_test.go
  pkg/controller/configuration/builtin_objects.go
  pkg/controller/configuration/config_template.go
  pkg/controller/configuration/config_template_test.go
  pkg/controller/configuration/pipeline.go
  pkg/controller/configuration/template_merger_test.go
  pkg/controller/configuration/template_wrapper_test.go
Labels: approved, size/L

#7370 chore: remove host-network ports from config built-in objects
  controllers/apps/configuration/configuration_controller.go
  controllers/apps/configuration/reconcile_task.go
  controllers/apps/transformer_component_configuration.go
  pkg/controller/component/component.go
  pkg/controller/configuration/builtin_objects.go
  pkg/controller/configuration/config_template.go
  pkg/controller/configuration/hostnetwork_utils.go
Labels: approved, size/L

#7347 chore: build template vars when reconfigure
  controllers/apps/configuration/configuration_controller.go
Labels: approved, size/S

#7381 chore: release hosts port support componentSpec and shardingSpec
  controllers/apps/transformer_cluster_deletion.go
Labels: approved, size/XS

#7368 chore: remove system account controller
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/type_test.go
  cmd/manager/main.go
  controllers/apps/component_controller.go
  controllers/apps/const.go
  controllers/apps/suite_test.go
  controllers/apps/systemaccount_controller.go
  controllers/apps/systemaccount_controller_test.go
  controllers/apps/systemaccount_util.go
  controllers/apps/systemaccount_util_test.go
  controllers/apps/utils.go
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/XXL

#7384 chore: refine opsRequest opsService and deletePolicy api doc
  apis/apps/v1alpha1/opsrequest_types.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/S

#7362 fix: record the failed message in the status condition if the restore…
  controllers/dataprotection/restore_controller.go
  controllers/dataprotection/restore_controller_test.go
  controllers/dataprotection/utils.go
  pkg/dataprotection/restore/types.go
  pkg/dataprotection/restore/utils.go
Labels: approved, size/M

#7388 fix: missing svc related feature gates in backup
  controllers/dataprotection/backup_controller.go
Labels: size/S

#7389 chore: refine configConstraint api doc
  apis/apps/v1alpha1/configconstraint_types.go
  config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
  deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/M

#7392 chore: upgrade release-charts version
  .github/workflows/release-helm-chart.yml
Labels: approved, size/XS

#7395 fix: panic error
  controllers/apps/transformer_cluster_backup_policy.go
Labels: approved, size/XS

#7398 chore: pod maybe re-create multi times due to consistent spec.
  controllers/apps/cluster_controller_test.go
  pkg/controller/scheduling/scheduling_utils.go
Labels: approved, size/S

#7386 chore: postProvision supports Immediately and RuntimeReady preCondition
  apis/apps/v1alpha1/componentdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/transformer_component_post_provision.go
  controllers/apps/transformer_component_restore.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/action_post_provision.go
  pkg/controller/component/action_post_provision_test.go
  pkg/controller/component/action_pre_terminate.go
  pkg/controller/component/action_pre_terminate_test.go
  pkg/controller/component/action_utils.go
  pkg/controller/component/action_utils_test.go
  pkg/controller/instanceset/utils.go
Labels: approved, size/L

#7404 chore: update slack link
  README.md
Labels: approved, size/XS

#7407 chore: log deleting object kind and remove invalid condition
  controllers/apps/transformer_cluster_deletion.go
  controllers/apps/transformer_cluster_restore.go
Labels: approved, size/XS

#7403 chore: vars supports referencing the pod FQDN list of a component
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: approved, size/L

#7408 chore: auto add componentDefinition to the labels of the backupPolicyTemplate
  controllers/apps/backuppolicytemplate_controller.go
  controllers/apps/backuppolicytemplate_controller_test.go
  controllers/apps/cluster_controller_test.go
  controllers/apps/transformer_cluster_backup_policy.go
Labels: approved, size/S

#7406 chore: Update create-and-connect-to-a-redis-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-redis/cluster-management/create-and-connect-to-a-redis-cluster.md
Labels: size/XS, pre-approve

#7409 chore: set component condition when load resource provision failed
  controllers/apps/transformer_component_load_resources.go
Labels: approved, size/XS

#7405 fix: scripts volume permission (#7298)
  apis/apps/v1alpha1/type.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusterversions.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterversions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controllerutil/volume_util.go
  pkg/controllerutil/volume_util_test.go
Labels: approved, size/L

#7416 fix: respect OfflineInstances in horizontal scaling
  controllers/apps/component_hscale_volume_populator.go
  controllers/apps/transformer_component_service.go
  controllers/apps/transformer_component_workload.go
Labels: approved, size/S

#7390 fix: both replicas in a OceanBase Cluster have the primary role assigned
  pkg/lorry/engines/redis/get_replica_role.go
  pkg/lorry/engines/redis/manager.go
  pkg/lorry/operations/replica/checkrole.go
Labels: approved, size/M

#7411 chore: expression for vars value
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: approved, size/L

#7420 fix: use time's UnixMicro as event version instead of RFC3339Nano format
  controllers/k8score/event_controller_test.go
  pkg/controller/instanceset/pod_role_event_handler.go
  pkg/lorry/operations/replica/checkrole.go
Labels: approved, size/S

#7427 docs: update redis docs
  docs/api_docs/kubeblocks-for-redis/cluster-management/create-and-connect-a-redis-cluster.md
Labels: approved, size/M

#7428 fix: api docs
  docs/api_docs/kubeblocks-for-apecloud-mysql/cluster-management/create-and-connect-a-mysql-cluster.md
  docs/api_docs/kubeblocks-for-kafka/cluster-management/create-a-kafka-cluster.md
  docs/api_docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
  docs/api_docs/kubeblocks-for-mysql-community-edition/cluster-management/create-and-connect-a-mysql-cluster.md
  docs/api_docs/kubeblocks-for-postgresql/cluster-management/create-and-connect-a-postgresql-cluster.md
  docs/api_docs/maintenance/in-place-update/overview.md
  docs/cli_docs/installation/uninstall-kbcli-and-kubeblocks.md
  docs/cli_docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
  docs/cli_docs/kubeblocks-for-postgresql/cluster-management/create-and-connect-a-postgresql-cluster.md
Labels: approved, size/M

#7429 fix: api docs build error
  docs/api_docs/kubeblocks-for-redis/cluster-management/create-and-connect-a-redis-cluster.md
  docs/api_docs/kubeblocks-for-vector-database/manage-vector-databases.md
Labels: approved, size/S

#7431 chore: remove fork pre-approve label
  .github/workflows/pull-request-label-approve.yaml
Labels: approved, size/S

#7421 chore: remove cluster status event handler
  controllers/apps/cluster_status_event_handler.go
  controllers/apps/cluster_status_event_handler_test.go
  controllers/apps/utils.go
  controllers/apps/utils_test.go
  controllers/k8score/const.go
  controllers/k8score/event_controller.go
  controllers/k8score/event_controller_test.go
  controllers/k8score/event_handler.go
  controllers/k8score/event_utils.go
  controllers/k8score/types.go
  pkg/constant/const.go
  pkg/controllerutil/controller_common.go
  pkg/controllerutil/controller_common_test.go
Labels: approved, size/XL

#7430 fix: update checkrole to handle normal case of role snapshot
  pkg/lorry/client/httpclient_test.go
  pkg/lorry/engines/base.go
  pkg/lorry/engines/models/errors.go
  pkg/lorry/engines/models/replca_role_types.go
  pkg/lorry/engines/oceanbase/get_replica_role.go
  pkg/lorry/grpcserver/grpc_server_test.go
  pkg/lorry/grpcserver/suite_test.go
  pkg/lorry/httpserver/apis.go
  pkg/lorry/httpserver/server_test.go
  pkg/lorry/operations/component/post_provision.go
  pkg/lorry/operations/component/pre_terminate.go
  pkg/lorry/operations/replica/checkrole.go
  pkg/lorry/util/types.go
Labels: approved, size/L

#7415 fix: cluster creation error when serviceVersion is not set in ComponentDefinition
  controllers/apps/componentversion_controller.go
  controllers/apps/componentversion_controller_test.go
Labels: approved, size/M, pre-approve

#7440 docs: fix docs errors
  docs/api_docs/kubeblocks-for-apecloud-mysql/_category_.yml
  docs/api_docs/kubeblocks-for-apecloud-mysql/apecloud-mysql-intro/apecloud-mysql-intro.md
  docs/api_docs/kubeblocks-for-apecloud-mysql/kubeblocks-for-mysql.md
  docs/api_docs/kubeblocks-for-mysql-community-edition/kubeblocks-for-mysql-community-edition.md
Labels: approved, size/S

#7441 docs: update apecloud mysql docs
  docs/api_docs/kubeblocks-for-apecloud-mysql/kubeblocks-for-apecloud-mysql.md
Labels: size/XS

#7438 fix: create backup failed when cluster phase is Updating
  controllers/apps/operations/backup.go
  controllers/apps/operations/backup_test.go
Labels: approved, size/M

#7437 chore: host field for service-ref
  apis/apps/v1alpha1/servicedescriptor_types.go
  apis/apps/v1alpha1/servicedescriptor_webhook.go
  apis/apps/v1alpha1/servicedescriptor_webhook_test.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_servicedescriptors.yaml
  controllers/apps/servicedescriptor_controller.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_servicedescriptors.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/const.go
  pkg/controller/builder/builder_service_descriptor.go
  pkg/controller/builder/builder_service_descriptor_test.go
  pkg/controller/component/service_descriptor_utils.go
  pkg/controller/component/service_descriptor_utils_test.go
  pkg/controller/component/service_reference.go
  pkg/controller/component/service_reference_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/synthesize_component_test.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
  pkg/testutil/apps/servicedescriptor_factory.go
Labels: approved, size/XL

#7444 fix: pitr restore failed when continuous backup occurs error in New phase
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/backuprepo_controller.go
  pkg/dataprotection/backup/scheduler.go
Labels: approved, size/M

#7451 chore: improve comment format
  apis/apps/v1alpha1/servicedescriptor_types.go
  config/crd/bases/apps.kubeblocks.io_servicedescriptors.yaml
  deploy/helm/crds/apps.kubeblocks.io_servicedescriptors.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/S

#7449 chore: host field for service-ref
  apis/apps/v1alpha1/servicedescriptor_types.go
  apis/apps/v1alpha1/servicedescriptor_webhook.go
  apis/apps/v1alpha1/servicedescriptor_webhook_test.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_servicedescriptors.yaml
  controllers/apps/servicedescriptor_controller.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_servicedescriptors.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/const.go
  pkg/controller/builder/builder_service_descriptor.go
  pkg/controller/builder/builder_service_descriptor_test.go
  pkg/controller/component/service_descriptor_utils.go
  pkg/controller/component/service_descriptor_utils_test.go
  pkg/controller/component/service_reference.go
  pkg/controller/component/service_reference_test.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
  pkg/testutil/apps/servicedescriptor_factory.go
Labels: size/XL

#7453 chore: restore action phase is incorrect when the job is failed
  controllers/dataprotection/log_collection_controller.go
Labels: approved, size/XS

#7450 fix: switchover ops is always running when the job is failed
  controllers/apps/operations/switchover.go
  pkg/controller/job/job_utils.go
Labels: approved, size/S

#7454 chore: reset ob stangby role when restore
  pkg/lorry/engines/oceanbase/get_replica_role.go
  pkg/lorry/engines/oceanbase/get_replica_role_test.go
  pkg/lorry/operations/replica/checkrole.go
Labels: approved, size/S

#7452 chore: support declaring a service-ref as optional
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/service_descriptor_utils.go
  pkg/controller/component/service_descriptor_utils_test.go
Labels: approved, size/M

#7462 chore: consistent implementation of isLeader and getRole for MongoDB.
  pkg/lorry/engines/mongodb/manager.go
Labels: approved, size/S

#7460 fix: volume-expand ops is always running but the volume expansion has been successful.
  controllers/apps/operations/volume_expansion.go
  controllers/apps/operations/volume_expansion_test.go
Labels: approved, size/M

#7461 chore: existing multi continuous backup when the backupSchedule has been re-created
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backupschedule_controller.go
  pkg/dataprotection/backup/scheduler.go
  pkg/dataprotection/backup/scheduler_test.go
  pkg/dataprotection/backup/utils.go
Labels: approved, size/L

#7466 chore: remove scheduling judgments when determining whether pod is Failed
  controllers/apps/component_controller_test.go
  controllers/apps/operations/rebuild_instance.go
  pkg/controller/instanceset/reconciler_status.go
  pkg/controllerutil/pod_utils.go
  pkg/dataprotection/action/action_stateful.go
Labels: approved, size/M

#7443 fix: permission issue for updating/creating CRDs in the KubeBlocks upgrade hook job
  config/rbac/role.yaml
  controllers/apps/configuration/configconstraint_controller.go
  deploy/helm/config/rbac/role.yaml
  deploy/helm/templates/kubeblocks-upgrade-hook.yaml
  deploy/helm/templates/rbac/clusterrole.yaml
Labels: approved, size/M

#7469 chore: auto-sync cluster backup spec to backupSchedule
  controllers/apps/transformer_cluster_backup_policy.go
Labels: size/M
