Repository apecloud/kubeblocks, pull requests merged in 2024-04, with the labels that each got.

#6928 fix: set securityContext.runAsUser for backupRepo pre-check job
  controllers/dataprotection/backuprepo_controller.go
Labels: enhancement, size/S

#6929 chore: support webhook conversion for configconstraints crd (#6801)
  config/rbac/role.yaml
  controllers/apps/configuration/configconstraint_controller.go
  deploy/helm/config/rbac/role.yaml
  deploy/helm/templates/admission/webhookconfiguration.yaml
  deploy/helm/templates/configconstraint-conversion-patch.yaml
  deploy/helm/values.yaml
Labels: approved, size/L

#6932 chore: removed deprecated sdk and update controller-runtime version
  apis/apps/v1/webhook_suite_test.go
  apis/apps/v1alpha1/webhook_suite_test.go
  apis/workloads/v1alpha1/webhook_suite_test.go
  cmd/dataprotection/main.go
  cmd/manager/main.go
  controllers/apps/configuration/suite_test.go
  controllers/apps/operations/suite_test.go
  controllers/apps/operations/util/suite_test.go
  controllers/apps/suite_test.go
  controllers/dataprotection/suite_test.go
  controllers/extensions/addon_controller_test.go
  controllers/k8score/suite_test.go
  controllers/storage/suite_test.go
  controllers/workloads/suite_test.go
  go.mod
  go.sum
  pkg/controller/component/suite_test.go
  pkg/controller/configuration/suite_test.go
  pkg/controller/factory/suite_test.go
  pkg/controller/multicluster/setup.go
  pkg/controller/plan/suite_test.go
  pkg/dataprotection/action/suite_test.go
  pkg/dataprotection/backup/suite_test.go
  pkg/dataprotection/restore/suite_test.go
  pkg/metrics/runtime.go
  test/integration/controller_suite_test.go
Labels: approved, size/L

#6941 chore: fix release issue move error
  .github/workflows/issues-move.yml
Labels: enhancement, release, approved, size/XS

#6945 chore: update apis license header
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/component_webhook.go
  apis/apps/v1alpha1/componentdefinition_webhook.go
  apis/apps/v1alpha1/componentversion_types.go
  apis/apps/v1alpha1/componentversion_webhook.go
  apis/apps/v1alpha1/config.go
  apis/apps/v1alpha1/config_meta.go
  apis/apps/v1alpha1/configconstraint_conversion.go
  apis/apps/v1alpha1/configconstraint_types_test.go
  apis/apps/v1alpha1/configuration_types.go
  apis/apps/v1alpha1/doc.go
  apis/apps/v1alpha1/opsdefinition_types.go
  apis/apps/v1alpha1/servicedescriptor_types.go
  apis/apps/v1alpha1/servicedescriptor_types_test.go
  apis/apps/v1alpha1/servicedescriptor_webhook.go
  apis/apps/v1alpha1/servicedescriptor_webhook_test.go
  apis/apps/v1beta1/configconstraint_conversion.go
  apis/apps/v1beta1/configconstraint_types_test.go
  apis/apps/v1beta1/configconstraint_webhook.go
  apis/apps/v1beta1/doc.go
  apis/apps/v1beta1/groupversion_info.go
  apis/apps/v1beta1/meta.go
  apis/apps/v1beta1/type.go
  apis/apps/v1beta1/webhook_suite_test.go
  apis/dataprotection/v1alpha1/doc.go
  apis/dataprotection/v1alpha1/restore_types.go
  apis/extensions/v1alpha1/doc.go
  apis/workloads/v1alpha1/doc.go
  apis/workloads/v1alpha1/groupversion_info.go
  apis/workloads/v1alpha1/replicatedstatemachine_types.go
  apis/workloads/v1alpha1/replicatedstatemachine_webhook.go
  apis/workloads/v1alpha1/replicatedstatemachine_webhook_test.go
  apis/workloads/v1alpha1/webhook_suite_test.go
  controllers/apps/configuration/combine_upgrade_policy.go
  controllers/apps/configuration/combine_upgrade_policy_test.go
  controllers/apps/configuration/relatedresource.go
  controllers/apps/transformer_component_hostnetwork.go
  controllers/apps/transformer_component_parameters.go
  hack/license/header-check.sh
  pkg/common/password.go
  pkg/common/password_test.go
  pkg/constant/metrics.go
  pkg/controller/configuration/builtin_objects.go
  pkg/controller/configuration/hostnetwork_utils.go
  pkg/dataprotection/action/action_stateful.go
  pkg/dataprotection/utils/compat_client.go
  pkg/lorry/util/command.go
  pkg/metrics/runtime.go
Labels: size/XL

#6950 chore: update api-reference doc
  apis/apps/v1alpha1/type.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: documentation, size/M

#6947 chore: requeue to wait pre terminate action job cleaned before component deleting
  controllers/apps/transformer_component_deletion.go
  pkg/controller/component/component_pre_terminate.go
Labels: approved, size/XS

#6956 chore: add extra envs for component provision and terminate actions
  pkg/controller/component/component_lifecycle_action_utils.go
  pkg/controller/component/component_lifecycle_action_utils_test.go
  pkg/controllerutil/sharding_utils.go
Labels: approved, size/L

#6907 fix: compatible with clusters that have all definitions set
  controllers/apps/transformer_cluster_load_resources.go
  controllers/apps/transformer_cluster_load_resources_test.go
Labels: enhancement, size/L

#6935 chore: update victoria-metric-agent addon docs (#6859)
  docs/user_docs/observability/monitor-database.md
  i18n/zh-cn/user-docs/observability/monitor-database.md
Labels: documentation, approved, size/XS

#6942 chore: set DNS policy as ClusterFirstWithHostNet in host-network
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/transformer_component_hostnetwork.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/component_definition_convertor.go
  pkg/controller/component/component_definition_convertor_test.go
Labels: approved, size/L

#6934 feat: make comp services overridable in cluster API
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_cluster_service.go
  controllers/apps/transformer_component_load_resources.go
  controllers/apps/transformer_component_service.go
  controllers/apps/transformer_component_vars.go
  controllers/apps/transformer_component_workload.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/flag.go
  pkg/controller/builder/builder_component.go
  pkg/controller/component/component.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: feature, approved, size/XXL

#6972 fix: stop/hscale opsRequests are always running in 0.9
  controllers/apps/component_utils_test.go
  controllers/apps/operations/ops_progress_util.go
  controllers/apps/operations/ops_util.go
  controllers/apps/operations/type.go
  pkg/controller/component/workload_utils.go
  pkg/controller/kubebuilderx/reconciler.go
Labels: enhancement, size/L

#6971 fix: cluster is always updating after v-scale
  go.mod
  pkg/controller/rsm/suite_test.go
  pkg/controller/rsm/transformer_status_test.go
  pkg/controller/rsm/transformer_update_strategy_test.go
  pkg/controller/rsm/update_plan.go
  pkg/controller/rsm/update_plan_test.go
  pkg/controller/rsm2/reconciler_revision_update.go
  pkg/controller/rsm2/reconciler_revision_update_test.go
  pkg/controller/rsm2/reconciler_status.go
  pkg/controller/rsm2/reconciler_status_test.go
  pkg/controller/rsm2/reconciler_update.go
  pkg/controller/rsm2/reconciler_update_test.go
  pkg/controller/rsm2/revision_util.go
  pkg/controller/rsm2/revision_util_test.go
  pkg/controller/rsm2/types.go
  pkg/controller/rsmcommon/revision_util.go
  pkg/controller/rsmcommon/revision_util_test.go
  pkg/controller/rsmcommon/suite_test.go
Labels: enhancement, size/L

#6959 fix: update excluded directories in header-check script
  Makefile
  hack/license/header-check.sh
Labels: enhancement, size/XS

#6975 chore: fix source files' license
  go.mod
  go.sum
  hack/license/header-check.sh
  pkg/lorry/engines/kafka/auth.go
  pkg/lorry/engines/kafka/consumer.go
  pkg/lorry/engines/kafka/kafka.go
  pkg/lorry/engines/kafka/manager.go
  pkg/lorry/engines/kafka/metadata.go
  pkg/lorry/engines/kafka/metadata_test.go
  pkg/lorry/engines/kafka/producer.go
  pkg/lorry/engines/kafka/sarama_log_bridge.go
  pkg/lorry/engines/kafka/sasl_oauthbearer.go
  pkg/lorry/engines/kafka/scram_client.go
  pkg/lorry/engines/kafka/thirdparty/retry.go
  pkg/lorry/engines/kafka/utils.go
  pkg/lorry/engines/redis/metadata.go
  pkg/lorry/engines/redis/redis.go
  pkg/lorry/engines/redis/settings.go
  pkg/lorry/engines/redis/settings_test.go
  pkg/lorry/util/config/decode.go
Labels: size/XXL

#6973 chore: fix panic when the specified comp-def is not found
  controllers/apps/componentversion_controller.go
Labels: approved, size/XS

#6980 chore: support to list from graph when resolving pod-service vars
  controllers/apps/transformer_component_vars.go
  pkg/controller/component/vars.go
Labels: approved, size/M

#6978 chore: ci check license header
  .github/workflows/cicd-push.yml
Labels: size/S

#6958 feat: support specified instance scale down
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/replicatedstatemachine_types.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  config/crd/bases/workloads.kubeblocks.io_replicatedstatemachines.yaml
  controllers/apps/operations/horizontal_scaling.go
  controllers/apps/operations/horizontal_scaling_test.go
  controllers/apps/operations/ops_progress_util_test.go
  controllers/apps/operations/ops_util_test.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_component_workload.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/workloads.kubeblocks.io_replicatedstatemachines.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_component.go
  pkg/controller/builder/builder_replicated_state_machine_test.go
  pkg/controller/component/component.go
  pkg/controller/component/rsm_convertor.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/rsm/utils.go
  pkg/controller/rsm2/instance_util.go
  pkg/controller/rsm2/instance_util_test.go
  pkg/controller/rsm2/reconciler_deletion.go
  pkg/controller/rsm2/reconciler_instance_alignment.go
  pkg/controller/rsm2/reconciler_instance_alignment_test.go
  pkg/controller/rsm2/reconciler_revision_update.go
  pkg/controller/rsm2/reconciler_status_test.go
  pkg/controller/rsm2/reconciler_update.go
  pkg/controller/rsm2/reconciler_update_test.go
  pkg/controller/rsm2/suite_test.go
  pkg/controller/rsm2/types.go
  pkg/testutil/apps/cluster_factory.go
Labels: feature, ci, size/XXL

#6985 fix: cluster is always in 'Deleting' after upgrade from 0.8.2 to 0.9
  controllers/apps/transformer_cluster_deletion.go
  controllers/apps/transformer_component_deletion.go
  pkg/controller/model/transform_utils.go
Labels: size/M

#6994 chore: add maxLength validation for componentDefinition component service name
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/type.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/M

#6996 chore: remove explicit reference to node-port
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: approved, size/L

#7003 chore: bot repeat approve
  .github/workflows/auto-approve.yml
Labels: size/XS

#7001 feat: support cluster RuntimeClassName configuration
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/replicatedstatemachine_types.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  config/crd/bases/workloads.kubeblocks.io_replicatedstatemachines.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/workloads.kubeblocks.io_replicatedstatemachines.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/rsm_convertor.go
  pkg/controller/rsm2/instance_util.go
Labels: size/M

#7000 feat: support pod in-place update
  cmd/manager/main.go
  controllers/apps/systemaccount_util.go
  go.mod
  go.sum
  pkg/controller/builder/builder_pod.go
  pkg/controller/rsm/update_plan.go
  pkg/controller/rsm2/in_place_update_util.go
  pkg/controller/rsm2/in_place_update_util_test.go
  pkg/controller/rsm2/instance_util.go
  pkg/controller/rsm2/instance_util_test.go
  pkg/controller/rsm2/reconciler_instance_alignment.go
  pkg/controller/rsm2/reconciler_revision_update.go
  pkg/controller/rsm2/reconciler_revision_update_test.go
  pkg/controller/rsm2/reconciler_status.go
  pkg/controller/rsm2/reconciler_status_test.go
  pkg/controller/rsm2/reconciler_update.go
  pkg/controller/rsm2/reconciler_update_test.go
  pkg/controller/rsm2/revision_util.go
  pkg/controller/rsm2/revision_util_test.go
  pkg/controller/rsm2/types.go
  pkg/controller/rsm2/utils.go
  pkg/controller/rsmcommon/revision_util.go
  pkg/controller/rsmcommon/revision_util_test.go
  pkg/controller/rsmcommon/suite_test.go
Labels: size/XXL

#7006 feat: service-ref supports referencing from new API objects
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/pattern.go
  pkg/controller/component/mock_reader.go
  pkg/controller/component/service_descriptor_utils.go
  pkg/controller/component/service_descriptor_utils_test.go
  pkg/controller/component/service_reference.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: area/user-interaction, size/XXL

#7017 feat: support in-place update for pod
  .github/workflows/auto-approve.yml
  .github/workflows/cicd-push.yml
  Makefile
  cmd/manager/main.go
  controllers/apps/systemaccount_util.go
  controllers/apps/transformer_component_deletion.go
  docs/user_docs/observability/monitor-database.md
  go.mod
  go.sum
  hack/license/header-check.sh
  i18n/zh-cn/user-docs/observability/monitor-database.md
  pkg/controller/builder/builder_pod.go
  pkg/controller/component/component_lifecycle_action_utils.go
  pkg/controller/component/component_lifecycle_action_utils_test.go
  pkg/controller/component/component_pre_terminate.go
  pkg/controller/rsm/update_plan.go
  pkg/controller/rsm2/in_place_update_util.go
  pkg/controller/rsm2/in_place_update_util_test.go
  pkg/controller/rsm2/instance_util.go
  pkg/controller/rsm2/instance_util_test.go
  pkg/controller/rsm2/reconciler_instance_alignment.go
  pkg/controller/rsm2/reconciler_revision_update.go
  pkg/controller/rsm2/reconciler_revision_update_test.go
  pkg/controller/rsm2/reconciler_status.go
  pkg/controller/rsm2/reconciler_status_test.go
  pkg/controller/rsm2/reconciler_update.go
  pkg/controller/rsm2/reconciler_update_test.go
  pkg/controller/rsm2/revision_util.go
  pkg/controller/rsm2/types.go
  pkg/controller/rsm2/utils.go
  pkg/controller/rsmcommon/revision_util.go
  pkg/controller/rsmcommon/revision_util_test.go
  pkg/controller/rsmcommon/suite_test.go
  pkg/controllerutil/sharding_utils.go
  pkg/lorry/engines/kafka/auth.go
  pkg/lorry/engines/kafka/consumer.go
  pkg/lorry/engines/kafka/kafka.go
  pkg/lorry/engines/kafka/manager.go
  pkg/lorry/engines/kafka/metadata.go
  pkg/lorry/engines/kafka/metadata_test.go
  pkg/lorry/engines/kafka/producer.go
  pkg/lorry/engines/kafka/sarama_log_bridge.go
  pkg/lorry/engines/kafka/sasl_oauthbearer.go
  pkg/lorry/engines/kafka/scram_client.go
  pkg/lorry/engines/kafka/thirdparty/retry.go
  pkg/lorry/engines/kafka/utils.go
  pkg/lorry/engines/redis/metadata.go
  pkg/lorry/engines/redis/redis.go
  pkg/lorry/engines/redis/settings.go
  pkg/lorry/engines/redis/settings_test.go
  pkg/lorry/util/config/decode.go
Labels: size/XXL

#7018 chore: release install KubeBlocks kubectl yaml
  .github/workflows/release-crds.yml
  deploy/helm/templates/addons/clickhouse-addon.yaml
  deploy/helm/templates/addons/foxlake-addon.yaml
  deploy/helm/templates/addons/kafka-addon.yaml
  deploy/helm/templates/addons/opensearch-addon.yaml
  deploy/helm/templates/addons/polardbx-addon.yaml
  deploy/helm/templates/addons/postgresql-addon.yaml
  deploy/helm/templates/addons/pulsar-addon.yaml
  deploy/helm/templates/addons/qdrant-addon.yaml
  deploy/helm/templates/addons/redis-addon.yaml
  deploy/helm/templates/addons/weaviate-addon.yaml
  deploy/helm/templates/tests/test-connection.yaml
Labels: size/M

#7032 chore: pod-service supports non-sequential pod ordinals
  controllers/apps/transformer_component_service.go
  pkg/constant/const.go
  pkg/controller/rsm2/instance_util.go
Labels: size/M

#7030 chore: default create backup repo miss accessMethod
  deploy/helm/templates/backuprepo.yaml
Labels: size/XS

#7035 fix: allow service-ref not defined in legacy API
  pkg/controller/component/service_descriptor_utils.go
  pkg/controller/component/service_descriptor_utils_test.go
Labels: size/M

#7033 chore: do not update images when the definition or version of spec has not changed
  controllers/apps/component_controller_test.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/componentversion_controller.go
  controllers/apps/componentversion_controller_test.go
  controllers/apps/transformer_cluster_load_resources.go
  controllers/apps/transformer_component_meta.go
  controllers/apps/transformer_component_workload.go
  pkg/constant/annotations.go
  pkg/constant/const.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/configuration/tool_image_builder_test.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
  pkg/testutil/apps/component_factory.go
  pkg/testutil/apps/componentversion_factory.go
  pkg/testutil/apps/constant.go
Labels: size/L

#7043 chore: print out the service version for component
  apis/apps/v1alpha1/component_types.go
  config/crd/bases/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
Labels: size/S

#7049 fix: restart not working
  pkg/controller/rsm2/in_place_update_util.go
  pkg/controller/rsm2/in_place_update_util_test.go
  pkg/controller/rsm2/instance_util_test.go
  pkg/controller/rsm2/suite_test.go
Labels: size/L

#7051 chore: do not update images when the definition or version of spec has not changed
  controllers/apps/component_controller_test.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/componentversion_controller.go
  controllers/apps/componentversion_controller_test.go
  controllers/apps/transformer_cluster_load_resources.go
  controllers/apps/transformer_component_meta.go
  controllers/apps/transformer_component_workload.go
  pkg/constant/annotations.go
  pkg/constant/const.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/configuration/tool_image_builder_test.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
  pkg/testutil/apps/component_factory.go
  pkg/testutil/apps/componentversion_factory.go
  pkg/testutil/apps/constant.go
Labels: size/L

#7042 fix: apepg-leave-member-failed
  pkg/lorry/engines/postgres/apecloudpostgres/manager.go
  pkg/lorry/engines/postgres/apecloudpostgres/manager_test.go
  pkg/lorry/engines/postgres/query.go
Labels: size/M

#7054 chore: delete related-configmap and configuration resources
  controllers/apps/transformer_cluster_deletion.go
Labels: size/XS

#7047 chore: remove unused annotations and clean code
  controllers/apps/operations/rebuild_instance.go
  controllers/apps/transformer_component_hostnetwork.go
  pkg/constant/const.go
Labels: size/S

#7055 chore: fix backup apecloud mysql failed
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/dataprotection/backuppolicy_controller_test.go
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
Labels: size/S

#7059 docs: fix migration docs
  docs/user_docs/kubeblocks-for-mongodb/migration/migration-kbcli.md
  docs/user_docs/kubeblocks-for-mysql/migration/migration-kbcli.md
  docs/user_docs/kubeblocks-for-postgresql/migration/migration-postgresql.md
Labels: size/S

#7056 fix: reconfigure not working
  pkg/controller/rsm2/in_place_update_util.go
  pkg/controller/rsm2/in_place_update_util_test.go
  pkg/controller/rsm2/instance_util_test.go
Labels: size/M

#7060 fix: recover MAX_PLAIN_REVISION_COUNT
  pkg/controller/rsm2/revision_util.go
Labels: size/XS

#7065 fix: do update in reverse ordinal order
  pkg/controller/rsm2/reconciler_update.go
  pkg/controller/rsm2/reconciler_update_test.go
Labels: size/S

#7053 chore: delete related-configmap and configuration resources
  controllers/apps/transformer_cluster_deletion.go
  controllers/apps/transformer_component_deletion.go
Labels: size/XS

#7075 chore: remove useless log
  pkg/controller/kubebuilderx/controller.go
Labels: size/XS

#7062 fix: delete leave member in ha loop
  pkg/lorry/client/httpclient_test.go
  pkg/lorry/dcs/types.go
  pkg/lorry/highavailability/ha.go
  pkg/lorry/operations/replica/leave.go
Labels: size/L

#7066 chore: fix leave member error when pod ordinal is not continuous
  controllers/apps/transformer_component_service.go
  controllers/apps/transformer_component_workload.go
Labels: size/M

#7079 fix: Serial UpdateStrategy not working without roles
  pkg/controller/rsm/update_plan.go
Labels: size/XS

#7064 chore: component definition delete handler reference check
  controllers/apps/componentdefinition_controller.go
  controllers/apps/transformer_component_meta.go
  pkg/controller/component/component.go
Labels: size/S

#7081 chore: update maintainer list
  MAINTAINERS.md
Labels: size/XS

#7082 chore: rsm using builtin selectors&finalizer for secondary objects
  pkg/controller/kubebuilderx/plan_builder.go
  pkg/controller/kubebuilderx/reconciler.go
  pkg/controller/kubebuilderx/reconciler_test.go
  pkg/controller/kubebuilderx/utils.go
  pkg/controller/kubebuilderx/utils_test.go
  pkg/controller/rsm/suite_test.go
  pkg/controller/rsm/transformer_deletion_test.go
  pkg/controller/rsm/transformer_object_generation.go
  pkg/controller/rsm/transformer_objection_generation_test.go
  pkg/controller/rsm2/instance_util.go
  pkg/controller/rsm2/reconciler_assistant_object.go
  pkg/controller/rsm2/reconciler_fix_meta.go
  pkg/controller/rsm2/reconciler_fix_meta_test.go
  pkg/controller/rsm2/tree_loader.go
  pkg/controller/rsm2/types.go
  pkg/controller/rsm2/utils.go
Labels: size/L

#7068 chore: remove isSharding field of the backupPolicyTemplate
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  controllers/apps/transformer_cluster_backup_policy.go
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
Labels: size/M

#7076 chore: build synthesizedComponent comp2CompDef supports shardingSpecs
  pkg/controller/component/synthesize_component.go
Labels: size/M

#7090 fix: resources merging failed
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/suite_test.go
Labels: size/M

#7088 chore: should report error when resolving partial required objects
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: size/L

#7057 fix: nil pointer when allocating host-ports
  controllers/apps/transformer_component_hostnetwork.go
Labels: size/XS

#7044 chore: rename cluster-ref to service selector
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/opsrequest_webhook_test.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/service_descriptor_utils.go
  pkg/controller/component/service_descriptor_utils_test.go
Labels: size/M

#7091 fix: instance template role label update failed
  controllers/k8score/event_controller_test.go
  pkg/controller/rsm/pod_role_event_handler.go
  pkg/controller/rsm/pod_role_event_handler_test.go
Labels: size/M

#7083 chore: adapt StorageProvider and BackupRepo to support multi-cluster mode
  cmd/dataprotection/main.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backuprepo_controller.go
  controllers/dataprotection/backupschedule_controller.go
  controllers/dataprotection/restore_controller.go
  controllers/dataprotection/utils.go
  controllers/dataprotection/utils_test.go
  controllers/dataprotection/volumepopulator_controller.go
  controllers/storage/storageprovider_controller.go
  deploy/helm/templates/dataprotection.yaml
  pkg/controller/multicluster/options.go
  pkg/controllerutil/controller_common.go
  pkg/dataprotection/utils/utils.go
Labels: size/L

#7071 feat: support to specify k8s scheduling policy in cluster API
  .github/utils/typos.toml
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/cluster_controller_test.go
  controllers/apps/operations/datascript.go
  controllers/apps/systemaccount_util.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_component.go
  pkg/controller/component/component.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/plan/restore.go
  pkg/controller/scheduling/scheduling_utils.go
  pkg/controller/scheduling/scheduling_utils_test.go
  pkg/controller/scheduling/suite_test.go
Labels: area/user-interaction, size/XXL

#7061 chore: improve api doc
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/clusterversion_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/configconstraint_types.go
  apis/apps/v1alpha1/configuration_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1beta1/configconstraint_types.go
  apis/workloads/v1alpha1/instanceset_types.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_clusterversions.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterversions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: size/XXL

#7096 chore: cherry pick improve-api-doc to 0.9
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/clusterversion_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/configconstraint_types.go
  apis/apps/v1alpha1/configuration_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1beta1/configconstraint_types.go
  apis/workloads/v1alpha1/instanceset_types.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_clusterversions.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterversions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: size/XXL

#6997 feat: refactor monitor-related api and support sidecar containers
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/config_meta.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_clusterversions.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  controllers/apps/componentSidecarContainerTransformer.go
  controllers/apps/component_controller.go
  controllers/apps/component_utils.go
  controllers/apps/configuration/config_util.go
  controllers/apps/systemaccount_controller_test.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_component_hostnetwork.go
  controllers/apps/transformer_component_validation.go
  controllers/apps/transformer_component_workload.go
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterversions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
  docs/developer_docs/api-reference/cluster.md
  go.mod
  pkg/constant/const.go
  pkg/constant/metrics.go
  pkg/controller/apiconversion/simplified_cluster_api.go
  pkg/controller/builder/builder_component.go
  pkg/controller/builder/builder_component_definition.go
  pkg/controller/component/component.go
  pkg/controller/component/component_definition_convertor.go
  pkg/controller/component/component_definition_convertor_test.go
  pkg/controller/component/component_test.go
  pkg/controller/component/monitor_utils.go
  pkg/controller/component/monitor_utils_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/configuration/config_utils.go
  pkg/controller/configuration/configuration_test.go
  pkg/controller/configuration/envfrom_utils.go
  pkg/controller/configuration/envfrom_utils_test.go
  pkg/controller/configuration/pipeline.go
  pkg/controller/configuration/tool_image_builder_test.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
  pkg/controllerutil/metrics.go
  pkg/controllerutil/volume_util.go
  pkg/controllerutil/volume_util_test.go
  pkg/metrics/runtime.go
  pkg/testutil/apps/cluster_factory.go
  pkg/testutil/apps/clusterdef_factory.go
  pkg/testutil/apps/component_factory.go
  pkg/testutil/apps/componentdefinition_factory.go
Labels: area/user-interaction, size/XXL

#7102 feat: cherry-pick monitor-related api (#6997)
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/config_meta.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_clusterversions.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  controllers/apps/componentSidecarContainerTransformer.go
  controllers/apps/component_controller.go
  controllers/apps/component_utils.go
  controllers/apps/configuration/config_util.go
  controllers/apps/systemaccount_controller_test.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_component_hostnetwork.go
  controllers/apps/transformer_component_validation.go
  controllers/apps/transformer_component_workload.go
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterversions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
  docs/developer_docs/api-reference/cluster.md
  go.mod
  pkg/constant/const.go
  pkg/constant/metrics.go
  pkg/controller/apiconversion/simplified_cluster_api.go
  pkg/controller/builder/builder_component.go
  pkg/controller/builder/builder_component_definition.go
  pkg/controller/component/component.go
  pkg/controller/component/component_definition_convertor.go
  pkg/controller/component/component_definition_convertor_test.go
  pkg/controller/component/component_test.go
  pkg/controller/component/monitor_utils.go
  pkg/controller/component/monitor_utils_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/configuration/config_utils.go
  pkg/controller/configuration/configuration_test.go
  pkg/controller/configuration/envfrom_utils.go
  pkg/controller/configuration/envfrom_utils_test.go
  pkg/controller/configuration/pipeline.go
  pkg/controller/configuration/tool_image_builder_test.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
  pkg/controllerutil/metrics.go
  pkg/controllerutil/volume_util.go
  pkg/controllerutil/volume_util_test.go
  pkg/metrics/runtime.go
  pkg/testutil/apps/cluster_factory.go
  pkg/testutil/apps/clusterdef_factory.go
  pkg/testutil/apps/component_factory.go
  pkg/testutil/apps/componentdefinition_factory.go
Labels: size/XXL

#7094 chore: optimize PR approve trigger make test
  .github/workflows/cicd-pull-request.yml
  .github/workflows/pull-request-label-approve.yaml
  .github/workflows/pull-request-review.yaml
Labels: approved, size/M

#7106 chore: change approve label gh token
  .github/workflows/pull-request-label-approve.yaml
  .github/workflows/pull-request-review.yaml
Labels: approved, size/XS

#7108 chore: change pr test check conditions
  .github/workflows/cicd-pull-request.yml
Labels: approved, size/XS

#7104 chore: fix codeblocks indent when generate apidoc
  docs/developer_docs/api-reference/add-on.md
  docs/developer_docs/api-reference/backup.md
  docs/developer_docs/api-reference/cluster.md
  hack/docgen/api/main.go
Labels: approved, size/L

#7087 feat: support upgrade from the RSM API to the InstanceSet API
  apis/workloads/legacy/doc.go
  apis/workloads/legacy/groupversion_info.go
  apis/workloads/legacy/register.go
  apis/workloads/legacy/replicatedstatemachine_types.go
  apis/workloads/legacy/zz_generated.deepcopy.go
  cmd/manager/main.go
  controllers/apps/component_controller.go
  controllers/apps/component_plan_builder.go
  controllers/apps/suite_test.go
  controllers/apps/transformer_component_workload_upgrade.go
  controllers/workloads/instanceset_controller.go
  controllers/workloads/instanceset_controller_test.go
  hack/docgen/api/main.go
  pkg/constant/const.go
  pkg/controller/handler/label_finder.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/reconciler_revision_update.go
  pkg/controller/instanceset/suite_test.go
  pkg/controller/kubebuilderx/utils.go
  pkg/controller/model/graph_client.go
  pkg/controller/model/graph_options.go
  pkg/controller/model/transform_types.go
  pkg/controller/rsm/suite_test.go
  pkg/controller/rsm/transformer_member_reconfiguration_test.go
  pkg/controller/rsm/transformer_object_generation.go
  pkg/controller/rsm/transformer_update_strategy_test.go
  pkg/controller/rsm/types.go
  pkg/controller/rsm/utils.go
  pkg/controller/rsm/utils_test.go
Labels: approved, size/XXL

#7109 chore: change pr trigger on
  .github/workflows/cicd-pull-request.yml
Labels: approved, size/XS

#7110 fix: restart in wrong order
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/reconciler_instance_alignment.go
  pkg/controller/instanceset/reconciler_instance_alignment_test.go
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/instanceset/reconciler_update_test.go
Labels: approved, size/M

#7111 chore: remove ReplicaProvider
  cmd/manager/main.go
  controllers/workloads/instanceset_controller.go
  controllers/workloads/instanceset_controller_test.go
  pkg/controller/instanceset/types.go
  pkg/controller/instanceset/utils.go
  pkg/controller/instanceset/utils_test.go
Labels: approved, size/L

#7112 chore: remove RSM_COMPATIBILITY_MODE
  cmd/manager/main.go
  controllers/workloads/instanceset_controller.go
  pkg/controller/rsm/transformer_object_generation.go
  pkg/controller/rsm/types.go
  pkg/controller/rsm/utils.go
Labels: approved, size/M

#7113 chore: update slack link
  README.md
  docs/user_docs/kubeblocks-for-mongodb/migration/migration-kbcli.md
  docs/user_docs/kubeblocks-for-mysql/migration/migration-kbcli.md
  docs/user_docs/kubeblocks-for-postgresql/migration/migration-postgresql.md
Labels: approved, size/XS

#7120 fix: no permissions for crd list&watch
  config/rbac/role.yaml
  controllers/apps/component_controller.go
  deploy/helm/config/rbac/role.yaml
Labels: approved, size/XS

#7124 fix: oceanbase switchover failed with wrong password
  pkg/lorry/dcs/k8s.go
  pkg/lorry/dcs/types.go
  pkg/lorry/engines/oceanbase/config.go
  pkg/lorry/engines/oceanbase/conn.go
  pkg/lorry/engines/oceanbase/get_replica_role.go
Labels: approved, size/M

#7127 chore: remove mock StatefulSet from unit tests
  apis/workloads/v1alpha1/groupversion_info.go
  apis/workloads/v1alpha1/instanceset_webhook.go
  controllers/apps/cluster_status_event_handler_test.go
  controllers/apps/component_controller_test.go
  controllers/apps/component_utils_test.go
  controllers/apps/configuration/configuration_test.go
  controllers/apps/configuration/policy_util.go
  controllers/apps/configuration/policy_util_test.go
  controllers/apps/operations/backup_test.go
  controllers/apps/operations/horizontal_scaling_test.go
  controllers/apps/operations/ops_progress_util_test.go
  controllers/apps/operations/rebuild_instance_test.go
  controllers/apps/operations/restart_test.go
  controllers/apps/operations/suite_test.go
  controllers/apps/operations/switchover_test.go
  controllers/apps/operations/switchover_util_test.go
  controllers/apps/operations/vertical_scaling_test.go
  controllers/apps/opsrequest_controller_test.go
  controllers/apps/suite_test.go
  controllers/apps/systemaccount_controller_test.go
  controllers/apps/transformer_component_workload_upgrade.go
  controllers/workloads/instanceset_controller_test.go
  pkg/constant/const.go
  pkg/controller/factory/builder_test.go
  pkg/controller/instanceset/types.go
  pkg/controller/instanceset/utils.go
  pkg/generics/type.go
  pkg/testutil/apps/cluster_instance_set_test_util.go
  pkg/testutil/apps/cluster_replication_test_util.go
  pkg/testutil/apps/cluster_stateless_test_util.go
  pkg/testutil/apps/deployment_factoy.go
  pkg/testutil/apps/statefulset_factoy.go
Labels: approved, size/XL

#7125 feat: support referencing pre-defined secret as encryptionKey
  apis/dataprotection/v1alpha1/types.go
  controllers/apps/transformer_cluster_backup_policy.go
  deploy/helm/templates/_dataprotection.tpl
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  pkg/constant/const.go
Labels: area/user-interaction, approved, size/M

#7101 feat: compatible shardingSpecs and instances for cluster
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/opsrequest_types_test.go
  apis/apps/v1alpha1/opsrequest_webhook.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/instanceset_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/operations/custom.go
  controllers/apps/operations/custom/action_exec.go
  controllers/apps/operations/custom/action_workload.go
  controllers/apps/operations/custom/utils.go
  controllers/apps/operations/custom_test.go
  controllers/apps/operations/custom_workflow.go
  controllers/apps/operations/expose.go
  controllers/apps/operations/expose_test.go
  controllers/apps/operations/horizontal_scaling.go
  controllers/apps/operations/horizontal_scaling_test.go
  controllers/apps/operations/ops_comp_helper.go
  controllers/apps/operations/ops_manager.go
  controllers/apps/operations/ops_progress_util.go
  controllers/apps/operations/ops_progress_util_test.go
  controllers/apps/operations/ops_util.go
  controllers/apps/operations/ops_util_test.go
  controllers/apps/operations/restart.go
  controllers/apps/operations/start.go
  controllers/apps/operations/stop.go
  controllers/apps/operations/type.go
  controllers/apps/operations/upgrade.go
  controllers/apps/operations/vertical_scaling.go
  controllers/apps/operations/vertical_scaling_test.go
  controllers/apps/operations/volume_expansion.go
  controllers/apps/opsrequest_controller_test.go
  controllers/apps/transformer_component_service.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/const.go
  pkg/controller/component/rsm_convertor.go
  pkg/controller/instanceset/instance_util.go
  pkg/controllerutil/cluster_utils.go
  pkg/testutil/apps/cluster_instance_set_test_util.go
Labels: area/user-interaction, approved, size/XXL

#7093 chore: disable dynamic reload of immutable parameters (#7089)
  controllers/apps/operations/reconfigure_pipeline.go
  controllers/apps/operations/reconfigure_pipeline_test.go
  controllers/apps/operations/reconfigure_util.go
  pkg/controllerutil/config_util.go
  pkg/controllerutil/config_util_test.go
Labels: approved, size/L

#7130 chore: component secondary resources do not add cluster finalizer
  controllers/apps/transformer_component_ownership.go
  pkg/controller/model/transform_utils.go
  pkg/controllerutil/controller_common.go
Labels: approved, size/S

#7136 chore: refactor out ConvertInstanceSetToSTS
  controllers/apps/component_hscale_volume_populator.go
  controllers/apps/transformer_component_status.go
  controllers/apps/transformer_component_tls_test.go
  controllers/apps/transformer_component_workload.go
  pkg/controller/instanceset/utils.go
Labels: approved, size/L

#7137 chore: move IsOwnedByInstanceSet from pkg instanceset to apps
  controllers/apps/transform_utils.go
  controllers/apps/transform_utils_test.go
  controllers/apps/transformer_cluster_deletion.go
  controllers/apps/transformer_component_deletion.go
  pkg/controller/instanceset/utils.go
  pkg/controller/instanceset/utils_test.go
Labels: approved, size/M

#7139 chore: rename param rsm/sts to its
  cmd/manager/main.go
  controllers/apps/cluster_status_event_handler.go
  controllers/apps/component_controller_test.go
  controllers/apps/configuration/rolling_upgrade_policy_test.go
  controllers/apps/opsrequest_controller_test.go
  controllers/apps/transformer_cluster_deletion.go
  controllers/k8score/event_controller_test.go
  controllers/k8score/event_handler.go
  deploy/helm/values.yaml
  pkg/configuration/core/type.go
  pkg/constant/const.go
  pkg/constant/pattern.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
  pkg/controller/instanceset/object_builder.go
  pkg/controller/instanceset/pod_role_event_handler.go
  pkg/controller/instanceset/pod_role_event_handler_test.go
  pkg/controller/instanceset/reconciler_status.go
  pkg/controller/instanceset/revision_util_test.go
  pkg/controller/instanceset/types.go
  pkg/controller/instanceset/update_plan.go
  pkg/controller/instanceset/utils.go
  pkg/controller/instanceset/utils_test.go
  pkg/controller/plan/restore.go
Labels: approved, size/L

#7142 chore: rename param rsm/sts to its (#7139)
  cmd/manager/main.go
  controllers/apps/cluster_status_event_handler.go
  controllers/apps/component_controller_test.go
  controllers/apps/configuration/rolling_upgrade_policy_test.go
  controllers/apps/opsrequest_controller_test.go
  controllers/apps/transformer_cluster_deletion.go
  controllers/k8score/event_controller_test.go
  controllers/k8score/event_handler.go
  deploy/helm/values.yaml
  pkg/configuration/core/type.go
  pkg/constant/const.go
  pkg/constant/pattern.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
  pkg/controller/instanceset/object_builder.go
  pkg/controller/instanceset/pod_role_event_handler.go
  pkg/controller/instanceset/pod_role_event_handler_test.go
  pkg/controller/instanceset/reconciler_status.go
  pkg/controller/instanceset/revision_util_test.go
  pkg/controller/instanceset/types.go
  pkg/controller/instanceset/update_plan.go
  pkg/controller/instanceset/utils.go
  pkg/controller/instanceset/utils_test.go
  pkg/controller/plan/restore.go
Labels: size/L

#7141 fix: install ops crd failed in k8s 1.28
  apis/apps/v1alpha1/opsrequest_types.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
Labels: approved, size/XS

#7148 chore: remove InstanceSet dependency from cluster_controller_test.go
  controllers/apps/cluster_controller_test.go
Labels: approved, size/S

#7147 chore: replace 'shardingName' to isSharding of opsRequest.componentOps
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/opsrequest_webhook.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/custom.go
  controllers/apps/operations/custom/action_exec.go
  controllers/apps/operations/custom/action_workload.go
  controllers/apps/operations/custom/utils.go
  controllers/apps/operations/custom_test.go
  controllers/apps/operations/custom_workflow.go
  controllers/apps/operations/horizontal_scaling.go
  controllers/apps/operations/ops_comp_helper.go
  controllers/apps/operations/ops_progress_util.go
  controllers/apps/operations/start.go
  controllers/apps/operations/stop.go
  controllers/apps/operations/volume_expansion.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/XL

#7146 feat: support KB_POD_LIST env
  apis/apps/v1alpha1/cluster_types.go
  apis/workloads/v1alpha1/instanceset_types.go
  controllers/apps/transformer_component_service.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/object_builder.go
  pkg/controller/instanceset/reconciler_instance_alignment_test.go
  pkg/controller/instanceset/reconciler_update_test.go
Labels: approved, size/L

#7151 chore: add cluster labels to continouns backup and support do postReady restore
  apis/apps/v1alpha1/opsrequest_types.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/cluster_controller.go
  controllers/apps/operations/rebuild_instance.go
  controllers/apps/operations/restore.go
  controllers/apps/transformer_cluster_restore.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/const.go
  pkg/controller/plan/restore.go
  pkg/dataprotection/backup/scheduler.go
  pkg/dataprotection/restore/utils.go
Labels: size/L

#7152 chore: support do postReady restore after cluster running and fix rebuildInstance bug
  apis/apps/v1alpha1/opsrequest_types.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/rebuild_instance.go
  controllers/apps/operations/restore.go
  controllers/apps/transformer_cluster_restore.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/const.go
  pkg/controller/plan/restore.go
  pkg/dataprotection/backup/scheduler.go
  pkg/dataprotection/restore/utils.go
Labels: approved, size/L

#7038 chore: update pg and redis cli example
  pkg/lorry/engines/postgres/commands.go
  pkg/lorry/engines/redis/commands.go
Labels: approved, size/XS

#7158 chore: fix workflow apt-get update error
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/codeql.yml
  .github/workflows/release-version.yml
Labels: approved, size/XS

#7154 fix: ut unstable failed
  controllers/dataprotection/gc_controller_test.go
Labels: approved, size/XS

#7160 chore: improve api comments for OpsRequest & OpsDefinition
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/configuration_types.go
  apis/apps/v1alpha1/opsdefinition_types.go
  apis/apps/v1alpha1/opsrequest_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  config/crd/bases/apps.kubeblocks.io_opsdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
  go.mod
Labels: approved, size/XXL

#7161 chore: improve api comments for OpsRequest & OpsDefinition in 0.9
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/configuration_types.go
  apis/apps/v1alpha1/opsdefinition_types.go
  apis/apps/v1alpha1/opsrequest_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  config/crd/bases/apps.kubeblocks.io_opsdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: size/XXL

#7119 chore: support control and data clusters can be the same one
  cmd/dataprotection/main.go
  cmd/manager/main.go
  pkg/controller/multicluster/client.go
  pkg/controller/multicluster/manager.go
  pkg/controller/multicluster/options.go
  pkg/controller/multicluster/setup.go
  pkg/controller/multicluster/types.go
Labels: approved, size/L

#7133 chore: support load balancer service in multi-cluster
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/systemaccount_controller.go
  controllers/apps/transformer_cluster_placement.go
  controllers/apps/transformer_component_service.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/annotations.go
  pkg/constant/const.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
  pkg/controller/multicluster/placement.go
Labels: approved, size/XL

#7162 fix: oceanbase healthcheck in oracle mode
  pkg/lorry/dcs/k8s.go
  pkg/lorry/engines/oceanbase/manager.go
Labels: approved, size/M

#7067 feat: config-manager support custom tools image (#6957)
  apis/apps/v1beta1/configconstraint_types.go
  apis/apps/v1beta1/meta.go
  apis/apps/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
  deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/configuration/config_manager/handler_util.go
  pkg/constant/config.go
  pkg/controller/configuration/config_utils.go
  pkg/controller/configuration/tool_image_builder.go
  pkg/controller/configuration/tool_image_builder_test.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
Labels: area/user-interaction, approved, size/L

#7131 chore: remove update primary index in component controller
  controllers/apps/transformer_component_status.go
Labels: approved, size/M

#7155 feat: support to reference other components vars
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: approved, size/XL

#7164 fix: lorry get cluster pod list
  pkg/lorry/dcs/k8s.go
Labels: approved, size/XS

#7166 chore: fix multi-cluster client judgment condition
  pkg/controller/multicluster/client.go
Labels: approved, size/XS

#7165 chore: support to abort last running opsRequest with same kind when using 'force' flag
  apis/apps/v1alpha1/opsrequest_conditions.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/opsrequest_webhook.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/horizontal_scaling.go
  controllers/apps/operations/horizontal_scaling_test.go
  controllers/apps/operations/ops_comp_helper.go
  controllers/apps/operations/ops_util.go
  controllers/apps/operations/ops_util_test.go
  controllers/apps/operations/restart.go
  controllers/apps/operations/start.go
  controllers/apps/operations/stop.go
  controllers/apps/operations/upgrade.go
  controllers/apps/operations/vertical_scaling.go
  controllers/apps/operations/vertical_scaling_test.go
  controllers/apps/opsrequest_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/XXL

#7168 feat: support InstanceSet status conditions
  apis/workloads/v1alpha1/instanceset_types.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/transformer_component_status.go
  controllers/workloads/instanceset_controller.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/pod_utils.go
  pkg/controller/factory/builder.go
  pkg/controller/instanceset/reconciler_revision_update.go
  pkg/controller/instanceset/reconciler_status.go
  pkg/controller/instanceset/reconciler_status_test.go
  pkg/controller/instanceset/update_plan.go
  pkg/controller/instanceset/utils.go
  pkg/controller/instanceset/utils_test.go
  pkg/testutil/k8s/instance_set_util.go
Labels: approved, size/XXL

#7172 chore: emit InvalidSpec event
  cmd/manager/main.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/types.go
Labels: approved, size/S

#7173 chore: remove outdated integration test
  Makefile
  test/integration/backup_mysql_test.go
  test/integration/controller_suite_test.go
  test/integration/mysql_ha_test.go
  test/integration/mysql_reconfigure_test.go
  test/integration/mysql_scale_test.go
  test/integration/redis_hscale_test.go
Labels: approved, size/XXL

#7174 chore: remove mock StatefulSet in pkg controllerutil&testutil
  controllers/apps/operations/switchover_util.go
  pkg/controllerutil/pod_utils.go
  pkg/controllerutil/pod_utils_test.go
  pkg/controllerutil/stateful_set_utils.go
  pkg/controllerutil/stateful_set_utils_test.go
  pkg/testutil/apps/constant.go
  pkg/testutil/k8s/deployment_util.go
  pkg/testutil/k8s/instance_set_util.go
  pkg/testutil/k8s/pod_util.go
  pkg/testutil/k8s/statefulset_util.go
  pkg/testutil/type.go
Labels: approved, size/XL

#7175 chore: remove updatePodReplicaLabel4Scaling
  controllers/apps/transformer_component_workload.go
Labels: approved, size/S

#7176 fix: remove InstanceFailure condition when no failure
  pkg/controller/instanceset/reconciler_status.go
  pkg/controller/instanceset/reconciler_status_test.go
Labels: approved, size/XS

#7179 chore: refine serviceRef and componentService api doc
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/type.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/L

#7181 fix: wrong usage of condition.LastTransitionTime
  controllers/apps/transformer_component_status.go
  pkg/controller/instanceset/reconciler_status.go
Labels: approved, size/S

#7187 chore: support component name vars reference
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: approved, size/M

#7189 chore: update leave member action's envs
  pkg/lorry/engines/custom/manager.go
Labels: approved, size/XS

#7195 chore: support switch to disable ha duing doring opsRequest
  controllers/apps/operations/ops_manager.go
  controllers/apps/operations/ops_util.go
  controllers/apps/operations/ops_util_test.go
  pkg/constant/const.go
Labels: approved, size/L

#7171 chore: support to disable unavailable k8s clusters
  cmd/dataprotection/main.go
  cmd/manager/main.go
  controllers/apps/transformer_component_status.go
  controllers/apps/transformer_component_workload.go
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  pkg/controller/multicluster/client.go
  pkg/controller/multicluster/client_unavailable.go
  pkg/controller/multicluster/error.go
  pkg/controller/multicluster/setup.go
  pkg/dataprotection/utils/volumesnapshot.go
Labels: approved, size/XL

#7205 chore: fix create example cmpd error
  examples/apecloud-mysql/cluster-cmpd.yaml
  examples/mongodb/cluster-cmpd.yaml
  examples/mongodb/restore-cmpd.yaml
  examples/postgresql/cluster-cmpd.yaml
  examples/postgresql/restore-cmpd.yaml
  examples/pulsar/cluster-cmpd.yaml
  examples/qdrant/cluster-cmpd.yaml
  examples/qdrant/restore-cmpd.yaml
  examples/redis/restore-cmpd.yaml
  examples/weaviate/cluster-cmpd.yaml
Labels: approved, size/S

#7208 chore: fix vscale comments
  examples/apecloud-mysql/verticalscale.yaml
  examples/apecloud-postgresql/verticalscale.yaml
  examples/camellia-redis-proxy/verticalscale.yaml
  examples/doris/verticalscale.yaml
  examples/etcd/verticalscale.yaml
  examples/halo/verticalscale.yaml
  examples/influxdb/verticalscale.yaml
  examples/kafka/verticalscale.yaml
  examples/mariadb/verticalscale.yaml
  examples/minio/verticalscale.yaml
  examples/mogdb/verticalscale.yaml
  examples/mongodb/verticalscale.yaml
  examples/mysql/verticalscale.yaml
  examples/official-postgresql/verticalscale.yaml
  examples/openldap/verticalscale.yaml
  examples/oracle-mysql/verticalscale.yaml
  examples/oracle/verticalscale.yaml
  examples/orioledb/verticalscale.yaml
  examples/postgresql/verticalscale.yaml
  examples/qdrant/verticalscale.yaml
  examples/redis/verticalscale.yaml
  examples/solr/verticalscale.yaml
  examples/tdengine/verticalscale.yaml
  examples/weaviate/verticalscale.yaml
  examples/xinference/verticalscale.yaml
  examples/yashandb/verticalscale.yaml
  examples/zookeeper/verticalscale.yaml
Labels: size/S

#7217 chore: add cmpd to readme of ob
  examples/oceanbase/README.md
Labels: size/S

#7219 chore: improve api-doc
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/configconstraint_types.go
  apis/apps/v1alpha1/configuration_types.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/servicedescriptor_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/apps/v1beta1/configconstraint_types.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_clusterversions.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  config/crd/bases/apps.kubeblocks.io_servicedescriptors.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterversions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/apps.kubeblocks.io_servicedescriptors.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/XXL

#7221 chore: improve apidoc misc, merge to 0.9
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/configconstraint_types.go
  apis/apps/v1alpha1/configuration_types.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/servicedescriptor_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/apps/v1beta1/configconstraint_types.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_clusterversions.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  config/crd/bases/apps.kubeblocks.io_servicedescriptors.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterversions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/apps.kubeblocks.io_servicedescriptors.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: size/XXL

#7224 update example for milvus and some vscale
  examples/clickhouse/verticalscale.yaml
  examples/elasticsearch/verticalscale.yaml
  examples/flink/verticalscale.yaml
  examples/foxlake/verticalscale.yaml
  examples/greptimedb/verticalscale.yaml
  examples/milvus/README.md
  examples/milvus/restart.yaml
  examples/milvus/verticalscale.yaml
  examples/nebula/verticalscale.yaml
  examples/opensearch/verticalscale.yaml
  examples/pika/verticalscale.yaml
  examples/polardbx/verticalscale.yaml
  examples/pulsar/verticalscale.yaml
  examples/risingwave/verticalscale.yaml
  examples/starrocks/verticalscale.yaml
  examples/tidb/verticalscale.yaml
Labels: size/M

#7226 chore: add example cluster refs
  examples/pulsar/cluster-cmpd.yaml
  examples/pulsar/cluster-service-descriptor.yaml
  examples/pulsar/cluster-zookeeper-separate.yaml
  examples/pulsar/cluster.yaml
  examples/risingwave/cluster.yaml
  examples/solr/cluster.yaml
Labels: approved, size/L

#7227 chore: change example refs cluster readme
  examples/orioledb/cluster.yaml
  examples/pulsar/README.md
  examples/risingwave/README.md
  examples/risingwave/cluster.yaml
  examples/solr/README.md
Labels: approved, size/S
