Repository apecloud/kubeblocks, pull requests merged in 2024-12, with the labels that each got.

#8553 fix: add Selective backupType
  apis/dataprotection/v1alpha1/actionset_types.go
  config/crd/bases/dataprotection.kubeblocks.io_actionsets.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_actionsets.yaml
  docs/developer_docs/api-reference/backup.md
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/restore/utils.go
  pkg/testutil/dataprotection/utils.go
Labels: approved, size/S

#8559 chore: opsDef support prefix match
  apis/operations/v1alpha1/opsdefinition_types.go
  pkg/operations/custom/utils.go
Labels: approved, size/S

#8538 chore: support to define and reference the TLS
  apis/apps/v1/componentdefinition_types.go
  apis/apps/v1/shardingdefinition_types.go
  apis/apps/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_shardingdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_sidecardefinitions.yaml
  controllers/apps/component_controller.go
  controllers/apps/component_controller_test.go
  controllers/apps/transformer_cluster_sharding_account.go
  controllers/apps/transformer_cluster_sharding_tls.go
  controllers/apps/transformer_component_tls.go
  controllers/apps/transformer_component_tls_test.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_shardingdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_sidecardefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/payload.go
  pkg/constant/tls.go
  pkg/controller/component/vars.go
  pkg/controller/configuration/builtin_functions.go
  pkg/controller/plan/tls.go
  pkg/controller/plan/tls_test.go
Labels: approved, size/XXL

#8563 fix: no kind xxx is registered
  cmd/manager/main.go
  controllers/trace/informer_manager.go
Labels: approved, size/S

#8521 chore: filter events to reconcile by CRD API version
  controllers/apps/cluster_controller.go
  controllers/apps/clusterdefinition_controller.go
  controllers/apps/component_controller.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/componentversion_controller.go
  controllers/apps/configuration/configconstraint_controller.go
  controllers/apps/configuration/configuration_controller.go
  controllers/apps/configuration/reconfigure_controller.go
  controllers/apps/servicedescriptor_controller.go
  controllers/apps/shardingdefinition_controller.go
  controllers/apps/sidecardefinition_controller.go
  controllers/apps/transformer_cluster_normalization.go
  controllers/apps/transformer_cluster_validation.go
  controllers/dataprotection/actionset_controller.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backuppolicy_controller.go
  controllers/dataprotection/backuppolicytemplate_controller.go
  controllers/dataprotection/backuprepo_controller.go
  controllers/dataprotection/backupschedule_controller.go
  controllers/dataprotection/gc_controller.go
  controllers/dataprotection/log_collection_controller.go
  controllers/dataprotection/restore_controller.go
  controllers/dataprotection/storageprovider_controller.go
  controllers/dataprotection/volumepopulator_controller.go
  controllers/experimental/nodecountscaler_controller.go
  controllers/extensions/addon_controller.go
  controllers/k8score/event_controller.go
  controllers/operations/opsdefinition_controller.go
  controllers/operations/opsrequest_controller.go
  controllers/workloads/instanceset_controller.go
  controllers/workloads/instanceset_controller_test.go
  pkg/constant/annotations.go
  pkg/controller/component/component.go
  pkg/controller/factory/builder.go
  pkg/controllerutil/predicate.go
  pkg/testutil/apps/clusterdef_factory.go
  pkg/testutil/apps/componentdefinition_factory.go
  pkg/testutil/apps/componentversion_factory.go
Labels: approved, size/L

#8445 chore: merge same events for kbagent
  deploy/helm/templates/rbac/cluster_pod_required_role.yaml
  pkg/kbagent/service/command.go
  pkg/kbagent/util/event.go
Labels: approved, size/M

#8566 chore: disable reconciliation tracing by default
  deploy/helm/templates/deployment.yaml
Labels: approved, size/XS

#8565 chore: support kbagent multi ports allocate hostnetwork port
  controllers/apps/transformer_component_hostnetwork.go
  controllers/apps/transformer_component_hostnetwork_test.go
Labels: approved, size/L

#8569 chore: change github.ref to github.ref_name
  .github/workflows/release-helm-chart.yml
Labels: approved, size/S

#8384 feat: implement memberjoin action release 0.9
  controllers/apps/transformer_component_workload.go
  pkg/constant/annotations.go
Labels: approved, size/L

#8573 chore: change cherry-pick token
  .github/workflows/cherry-pick.yml
Labels: approved, size/XS

#8579 docs: fix format bugs
  docs/developer_docs/integration/environment-variables-and-placeholders.md
  docs/developer_docs/integration/multi-component.md
  docs/user_docs/connect_database/connect-database-in-production-environment.md
  docs/user_docs/installation/install-addons.md
  i18n/zh-cn/developer-docs/integration/environment-variables-and-placeholders.md
  i18n/zh-cn/developer-docs/integration/multi-component.md
  i18n/zh-cn/user-docs/connect-databases/connect-to-database-in-production-environment.md
  i18n/zh-cn/user-docs/installation/install-addons.md
Labels: approved, size/L

#8580 docs: fix format bugs
  docs/developer_docs/integration/environment-variables-and-placeholders.md
  docs/developer_docs/integration/multi-component.md
  docs/user_docs/connect_database/connect-database-in-production-environment.md
  docs/user_docs/installation/install-addons.md
  i18n/zh-cn/developer-docs/integration/environment-variables-and-placeholders.md
  i18n/zh-cn/developer-docs/integration/multi-component.md
  i18n/zh-cn/user-docs/connect-databases/connect-to-database-in-production-environment.md
  i18n/zh-cn/user-docs/installation/install-addons.md
Labels: approved, size/L

#8576 chore: unmarshal errors when create api using kubebuilder
  PROJECT
Labels: approved, size/XS

#8581 chore: prioritize exact match for service version
  pkg/controller/component/component_version.go
  pkg/controller/component/component_version_test.go
Labels: approved, size/L

#8584 feat: support cluster upgrade from cd/cv to cmpd/cmpv
  controllers/apps/transformer_cluster_component.go
  pkg/lorry/engines/mysql/manager.go
Labels: approved, size/XS

#8571 feat: support update label/annotations for underlying pods and improve restart ops
  controllers/apps/cluster_controller_test.go
  controllers/apps/transformer_component_account.go
  controllers/apps/transformer_component_service.go
  controllers/apps/transformer_component_workload.go
  pkg/controller/factory/builder.go
  pkg/controller/plan/tls.go
  pkg/controllerutil/util.go
  pkg/operations/restart.go
  pkg/operations/restart_test.go
Labels: approved, size/L

#8018 feat: replace image registry dynamically
  cmd/dataprotection/main.go
  cmd/manager/main.go
  controllers/apps/component_controller_test.go
  controllers/apps/suite_test.go
  controllers/apps/transformer_component_workload.go
  controllers/extensions/addon_controller_stages.go
  go.mod
  go.sum
  pkg/constant/viper_config.go
  pkg/controllerutil/image_util.go
  pkg/controllerutil/image_util_test.go
  pkg/dataprotection/backup/deleter.go
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/restore/builder.go
  pkg/dataprotection/utils/backuprepo.go
  pkg/viperx/viperx.go
Labels: approved, size/XL

#8591 fix: recreate pod without containers ready condition
  pkg/controller/instanceset/reconciler_update.go
Labels: approved, size/XS

#8596 docs: fix bugs in rabbitmq doc
  docs/user_docs/kubeblocks-for-rabbitmq/manage-rabbitmq.md
Labels: approved, size/L

#8601 chore: hostNetwork annotation key switch supports sharding topology
  controllers/apps/transformer_cluster_component.go
Labels: approved, size/S

#8600 fix: cluster phase are empty in a long time
  controllers/apps/transformer_cluster_status.go
Labels: approved, size/XS

#8595 chore: remove the delay for updating the tools image
  controllers/apps/component_controller_test.go
  controllers/apps/component_utils.go
  controllers/apps/component_utils_test.go
  controllers/apps/transformer_component_workload.go
  pkg/controllerutil/pod_utils_test.go
Labels: approved, size/L

#8605 fix: DP_DB_HOST env is missing
  pkg/dataprotection/restore/builder.go
Labels: approved, size/S

#8607 chore: kb upgrade with dualOperatorsMode failed
  deploy/helm/templates/deployment.yaml
  pkg/constant/const.go
Labels: size/XS

#8608 fix: dataprotection start bug with dualOperatorsMode
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
Labels: approved, size/XS

#8611 fix: Check if the SQL is valid when creating a MySQL account.
  pkg/lorry/engines/mysql/user.go
Labels: approved, size/XS

#8578 chore: remove instanceset's role probe
  apis/workloads/v1/instanceset_types.go
  apis/workloads/v1/zz_generated.deepcopy.go
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/transformer_component_workload.go
  controllers/workloads/instanceset_controller_test.go
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_instance_set.go
  pkg/controller/builder/builder_instance_set_test.go
  pkg/controller/factory/builder_test.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/object_builder.go
  pkg/controller/instanceset/object_builder_test.go
  pkg/controller/instanceset/pod_role_event_handler.go
  pkg/controller/instanceset/pod_role_event_handler_test.go
  pkg/controller/instanceset/suite_test.go
  pkg/controller/instanceset/types.go
  pkg/controller/instanceset/utils.go
  pkg/controller/instanceset/utils_test.go
Labels: approved, size/XL

#8614 chore: prioritize exact match for service version
  pkg/controller/component/component_version.go
  pkg/controller/component/component_version_test.go
Labels: approved, size/L

#8588 chore: refactor parameters partII: refactor template render
  cmd/reloader/template/main.go
  controllers/apps/configuration/config_reconcile_wrapper.go
  controllers/apps/configuration/configuration_controller.go
  controllers/apps/configuration/configuration_controller_test.go
  controllers/apps/configuration/configuration_test.go
  controllers/apps/configuration/reconcile_task.go
  controllers/apps/configuration/reconfigure_controller.go
  controllers/apps/configuration/relatedresource.go
  controllers/apps/transformer_component_configuration.go
  pkg/controller/configuration/config_template.go
  pkg/controller/configuration/configuration_test.go
  pkg/controller/configuration/operator.go
  pkg/controller/configuration/operator_test.go
  pkg/controller/configuration/pipeline.go
  pkg/controller/configuration/pipeline_test.go
  pkg/controller/configuration/resource_wrapper.go
  pkg/controller/configuration/resource_wrapper_test.go
  pkg/controller/configuration/template_merger.go
  pkg/controller/configuration/template_merger_test.go
  pkg/controller/configuration/template_wrapper.go
  pkg/controller/configuration/template_wrapper_test.go
  pkg/controller/configuration/tool_image_builder.go
  pkg/controller/plan/prepare.go
  pkg/controller/plan/prepare_test.go
  pkg/controller/render/builtin_env.go
  pkg/controller/render/builtin_env_test.go
  pkg/controller/render/builtin_functions.go
  pkg/controller/render/builtin_functions_test.go
  pkg/controller/render/builtin_objects.go
  pkg/controller/render/render_utils.go
  pkg/controller/render/suite_test.go
  pkg/controller/render/template_render.go
  pkg/controller/render/template_render_test.go
  pkg/controller/render/types.go
  pkg/controllerutil/config_util.go
  pkg/operations/reconfigure.go
  pkg/operations/reconfigure_pipeline.go
Labels: approved, size/XXL

#8612 chore: filtering v1 version events fails when no changes have been made to the ClusterDefinition.
  apis/apps/v1alpha1/cluster_conversion.go
  apis/apps/v1alpha1/conversion.go
  controllers/apps/transformer_cluster_normalization.go
  controllers/apps/transformer_component_init.go
  deploy/helm/templates/rbac/apps_sidecardefinition_editor_role.yaml
Labels: approved, size/L

#8590 chore: refactor parameters partIII: removed deprecated api and tools to do rerender on pods
  apis/apps/v1/componentdefinition_types.go
  apis/apps/v1/zz_generated.deepcopy.go
  cmd/cmd.mk
  cmd/reloader/template/main.go
  cmd/reloader/template/safeclient.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docker/Dockerfile-tools
  docs/developer_docs/api-reference/cluster.md
  pkg/configuration/config_manager/builder.go
  pkg/configuration/config_manager/builder_test.go
  pkg/controller/builder/builder_configuration.go
  pkg/controller/configuration/tool_image_builder.go
  pkg/controller/configuration/tool_image_builder_test.go
Labels: approved, size/XL

#8621 chore: rename the shards provision/terminate actions to add/remove
  apis/apps/v1/shardingdefinition_types.go
  apis/apps/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_shardingdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_shardingdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/M

#8632 fix: checkrole for mongodb and mysql
  pkg/lorry/engines/mongodb/get_replica_role.go
  pkg/lorry/engines/mongodb/manager.go
  pkg/lorry/engines/mysql/get_replica_role.go
Labels: approved, size/S

#8634 chore: component annotations updated failed
  controllers/apps/cluster_controller_test.go
  controllers/apps/transformer_cluster_component.go
Labels: approved, size/S

#8627 fix: the decimal value of the default mount mode for TLS secrets
  apis/apps/v1/componentdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/S

#8630 fix: filter 0.9 api events bug
  cmd/manager/main.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/opsrequest_controller.go
  controllers/apps/transformer_cluster_init.go
  controllers/apps/transformer_component_init.go
  pkg/controller/instanceset/reconciler_api_version.go
  pkg/controller/kubebuilderx/plan_builder.go
  pkg/controller/kubebuilderx/plan_builder_test.go
Labels: approved, size/M

#8631 chore: filter events for 1.0 api version
  apis/apps/v1alpha1/cluster_conversion.go
  apis/workloads/v1alpha1/instanceset_conversion.go
  apis/workloads/v1alpha1/instanceset_types.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/transformer_cluster_init.go
  controllers/operations/opsrequest_controller.go
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/instanceset/reconciler_api_version.go
  pkg/controllerutil/predicate.go
Labels: approved, size/L

#8636 chore: remove built-in KB_* envs
  pkg/controller/component/vars.go
Labels: approved, size/M

#8639 fix: reset mongodb role when it is unhealthy
  pkg/lorry/operations/replica/checkrole.go
Labels: approved, size/XS

#8647 fix: schedule policy of restore pod is incorrect
  pkg/controller/plan/restore.go
Labels: approved, size/M

#8640 fix: sharding reconfigure
  apis/apps/v1alpha1/opsrequest_webhook.go
  controllers/apps/operations/reconfigure.go
Labels: approved, size/M

#8648 chore: set default values for roleProbe
  pkg/controller/component/rsm_convertor.go
Labels: approved, size/S

#8644 fix: empty labels and annotations in the component API
  apis/apps/v1/component_types.go
Labels: approved, size/XS

#8646 fix: schedule policy of restore pod is incorrect
  pkg/controller/plan/restore.go
Labels: approved, size/S

#8652 chore: sort cmpv.status.serviceVersions according to the semantic version
  controllers/apps/componentversion_controller.go
  controllers/apps/componentversion_controller_test.go
Labels: approved, size/S

#8656 chore: fix some flaky test cases
  controllers/apps/component_controller_test.go
Labels: approved, size/S

#8657 fix: reconfigure panic
  controllers/apps/operations/reconfigure.go
Labels: approved, size/XS

#8655 chore: remove pulsar, llm from defualt installed addons
  deploy/helm/scripts/change_kb_release.sh
  deploy/helm/templates/addons/apecloud-mysql-addon.yaml
  deploy/helm/templates/addons/kafka-addon.yaml
  deploy/helm/templates/addons/mongodb-addon.yaml
  deploy/helm/templates/addons/mysql-addon.yaml
  deploy/helm/templates/addons/postgresql-addon.yaml
  deploy/helm/templates/addons/pulsar-addon.yaml
  deploy/helm/templates/addons/qdrant-addon.yaml
  deploy/helm/templates/addons/rabbitmq-addon.yaml
  deploy/helm/templates/addons/redis-addon.yaml
  deploy/helm/values.yaml
  examples/llm/README.md
  examples/llm/cluster.yaml
  examples/llm/restart.yaml
  examples/llm/start.yaml
  examples/llm/stop.yaml
  test/e2e/testdata/smoketest/llm/00_llmcluster.yaml
  test/e2e/testdata/smoketest/llm/01_vscale.yaml
  test/e2e/testdata/smoketest/llm/02_hscale_out.yaml
  test/e2e/testdata/smoketest/llm/03_hscale_in.yaml
  test/e2e/testdata/smoketest/llm/04_vexpand.yaml
  test/e2e/testdata/smoketest/llm/05_stop.yaml
  test/e2e/testdata/smoketest/llm/06_start.yaml
  test/e2e/testdata/smoketest/llm/07_restart.yaml
Labels: approved, size/L

#8659 fix: nilptr for memberjoin
  controllers/apps/transformer_component_workload.go
Labels: approved, size/S

#8661 fix: update role label failed when switchover
  controllers/k8score/event_controller_test.go
  pkg/controller/instanceset/pod_role_event_handler.go
Labels: approved, size/XS

#8662 chore: enhance MySQL get role accuracy
  pkg/lorry/dcs/k8s.go
  pkg/lorry/dcs/types.go
  pkg/lorry/engines/mysql/get_replica_role.go
Labels: approved, size/S

#8635 chore: forbidden vars value and valueFrom are specified
  controllers/apps/componentdefinition_controller.go
  controllers/apps/componentdefinition_controller_test.go
Labels: approved, size/S

#8643 fix: sharding cluster can not be deleted
  controllers/apps/cluster_plan_builder.go
  controllers/apps/transformer_cluster_component.go
Labels: approved, size/M

#8633 docs: update monitoring docs
  docs/user_docs/kubeblocks-for-apecloud-mysql/proxy/apecloud-mysql-proxy.md
  docs/user_docs/kubeblocks-for-elasticsearch/manage-elasticsearch.md
  docs/user_docs/kubeblocks-for-pulsar/cluster-management/create-pulsar-cluster-on-kubeblocks.md
  docs/user_docs/kubeblocks-for-qdrant/manage-qdrant.md
  docs/user_docs/observability/monitor-database.md
  docs/user_docs/try-out-on-playground/try-kubeblocks-on-cloud.md
  docs/user_docs/try-out-on-playground/try-kubeblocks-on-your-laptop.md
  i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/proxy/apecloud-mysql-proxy.md
  i18n/zh-cn/user-docs/kubeblocks-for-elasticsearch/manage-elasticsearch.md
  i18n/zh-cn/user-docs/kubeblocks-for-pulsar/cluster-management/create-pulsar-cluster-on-kb.md
  i18n/zh-cn/user-docs/observability/monitor-database.md
  i18n/zh-cn/user-docs/try-out-on-playground/try-kubeblocks-on-cloud.md
  i18n/zh-cn/user-docs/try-out-on-playground/try-kubeblocks-on-local-host.md
Labels: approved, size/XXL

#8668 docs: adjust monitoring docs format and doc order
  docs/user_docs/handle-an-exception/_category_.yml
  docs/user_docs/kubeblocks-for-elasticsearch/_category_.yml
  docs/user_docs/kubeblocks-for-kafka/_category_.yml
  docs/user_docs/kubeblocks-for-milvus/_category_.yml
  docs/user_docs/kubeblocks-for-mongodb/_category_.yml
  docs/user_docs/kubeblocks-for-mysql-community-edition/_category_.yml
  docs/user_docs/kubeblocks-for-postgresql/_category_.yml
  docs/user_docs/kubeblocks-for-pulsar/_category_.yml
  docs/user_docs/kubeblocks-for-qdrant/_category_.yml
  docs/user_docs/kubeblocks-for-rabbitmq/_category_.yml
  docs/user_docs/kubeblocks-for-redis/_category_.yml
  docs/user_docs/kubeblocks-for-starrocks/_category_.yml
  docs/user_docs/maintenance/_category_.yaml
  docs/user_docs/maintenance/instance-template/_category_.yml
  docs/user_docs/maintenance/instance-template/how-to-use-instance-template.md
  docs/user_docs/maintenance/instance-template/introduction.md
  docs/user_docs/observability/_category_.yml
  docs/user_docs/observability/monitor-database.md
  docs/user_docs/user-management/_category_.yml
  i18n/zh-cn/user-docs/connect-databases/_category_.yml
  i18n/zh-cn/user-docs/handle-an-exception/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-elasticsearch/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-kafka/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-milvus/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-mysql-community-edition/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-pulsar/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-qdrant/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-rabbitmq/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-redis/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-starrocks/_category_.yml
  i18n/zh-cn/user-docs/maintenance/_category_.yml
  i18n/zh-cn/user-docs/observability/_category_.yml
  i18n/zh-cn/user-docs/observability/monitor-database.md
  i18n/zh-cn/user-docs/user-management/_category_.yml
Labels: approved, size/L

#8670 fix: mysql support kbadmin
  pkg/lorry/engines/mysql/config.go
Labels: approved, size/M

#8674 chore: improve update cmpd labels when check the configSpecs
  controllers/apps/configuration/config_util.go
  pkg/lorry/engines/mysql/config.go
Labels: approved, size/S

#8682 fix: mysql tests
  pkg/lorry/engines/mysql/get_replica_role_test.go
Labels: approved, size/XS

#8684 chore: skip the component definition that is not supported by the current operator
  controllers/apps/componentdefinition_controller.go
Labels: approved, size/XS

#8675 chore: convert lifecycleActions of the cmpd between v1 and v1alpha1
  apis/apps/v1alpha1/componentdefinition_conversion.go
Labels: approved, size/M

#8688 fix: reconfigure fetch original value
  controllers/apps/operations/reconfigure_util.go
Labels: approved, size/S

#8645 chore: let switchover action determine whether to do switchover
  apis/apps/v1/componentdefinition_types.go
  apis/operations/v1alpha1/opsrequest_types.go
  apis/operations/v1alpha1/opsrequest_validation.go
  apis/workloads/v1/instanceset_types.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/transformer_component_workload.go
  controllers/apps/transformer_component_workload_test.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/lifecycle/kbagent.go
  pkg/controller/component/lifecycle/lfa_member.go
  pkg/operations/switchover.go
  pkg/operations/switchover_test.go
  pkg/operations/switchover_util.go
  pkg/testutil/apps/kb_agent_util.go
Labels: approved, size/XL

#8695 chore: auto update kbcli user docs workflow
  .github/workflows/release-version.yml
Labels: approved, size/M

#8702 chore: replace prefix match with compDefMatched
  controllers/apps/componentversion_controller.go
Labels: approved, size/XS

#8704 docs: sync monitoring docs to release 0.9
  docs/user_docs/handle-an-exception/_category_.yml
  docs/user_docs/kubeblocks-for-apecloud-mysql/proxy/apecloud-mysql-proxy.md
  docs/user_docs/kubeblocks-for-elasticsearch/_category_.yml
  docs/user_docs/kubeblocks-for-elasticsearch/manage-elasticsearch.md
  docs/user_docs/kubeblocks-for-kafka/_category_.yml
  docs/user_docs/kubeblocks-for-milvus/_category_.yml
  docs/user_docs/kubeblocks-for-mongodb/_category_.yml
  docs/user_docs/kubeblocks-for-mysql-community-edition/_category_.yml
  docs/user_docs/kubeblocks-for-postgresql/_category_.yml
  docs/user_docs/kubeblocks-for-pulsar/_category_.yml
  docs/user_docs/kubeblocks-for-pulsar/cluster-management/create-pulsar-cluster-on-kubeblocks.md
  docs/user_docs/kubeblocks-for-qdrant/_category_.yml
  docs/user_docs/kubeblocks-for-qdrant/manage-qdrant.md
  docs/user_docs/kubeblocks-for-rabbitmq/_category_.yml
  docs/user_docs/kubeblocks-for-redis/_category_.yml
  docs/user_docs/kubeblocks-for-starrocks/_category_.yml
  docs/user_docs/maintenance/_category_.yaml
  docs/user_docs/maintenance/instance-template/_category_.yml
  docs/user_docs/maintenance/instance-template/how-to-use-instance-template.md
  docs/user_docs/maintenance/instance-template/introduction.md
  docs/user_docs/observability/_category_.yml
  docs/user_docs/observability/monitor-database.md
  docs/user_docs/try-out-on-playground/try-kubeblocks-on-cloud.md
  docs/user_docs/try-out-on-playground/try-kubeblocks-on-your-laptop.md
  docs/user_docs/user-management/_category_.yml
  i18n/zh-cn/user-docs/connect-databases/_category_.yml
  i18n/zh-cn/user-docs/handle-an-exception/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/proxy/apecloud-mysql-proxy.md
  i18n/zh-cn/user-docs/kubeblocks-for-elasticsearch/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-elasticsearch/manage-elasticsearch.md
  i18n/zh-cn/user-docs/kubeblocks-for-kafka/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-milvus/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-mysql-community-edition/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-pulsar/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-pulsar/cluster-management/create-pulsar-cluster-on-kb.md
  i18n/zh-cn/user-docs/kubeblocks-for-qdrant/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-rabbitmq/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-redis/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-starrocks/_category_.yml
  i18n/zh-cn/user-docs/maintenance/_category_.yml
  i18n/zh-cn/user-docs/observability/_category_.yml
  i18n/zh-cn/user-docs/observability/monitor-database.md
  i18n/zh-cn/user-docs/try-out-on-playground/try-kubeblocks-on-cloud.md
  i18n/zh-cn/user-docs/try-out-on-playground/try-kubeblocks-on-local-host.md
  i18n/zh-cn/user-docs/user-management/_category_.yml
Labels: approved, size/XXL

#8701 chore: update no matched cmpd and serviceVersion msg
  controllers/apps/componentversion_controller.go
Labels: approved, size/XS

#8691 fix: redis get role overtime
  pkg/lorry/engines/redis/get_replica_role.go
  pkg/lorry/engines/redis/manager.go
  pkg/lorry/engines/redis/redis.go
Labels: approved, size/M

#8705 feat: support to set the pod anti-affinity for a shard
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_cluster_component_test.go
  pkg/constant/flag.go
Labels: approved, size/L

#8712 chore: improve cluster conversion
  apis/apps/v1alpha1/cluster_conversion.go
Labels: approved, size/L

#8713 chore: move Update apis doc ahead Update kbcli doc
  .github/workflows/release-version.yml
Labels: approved, size/M

#8714 chore: not release apecloud-addons chart
  .github/workflows/release-helm-chart.yml
Labels: approved, size/L

#8715 fix: restore ops info is not deleted in cluster.annotations when restore is done
  pkg/operations/restore.go
Labels: approved, size/XS

#8717 fix: restore ops info is not deleted in cluster.annotations when restore is done
  controllers/apps/operations/restore.go
Labels: approved, size/XS

#8718 fix: vscale ops is always running when need to rerender configuration
  controllers/apps/cluster_controller_test.go
  controllers/apps/transformer_component_workload.go
Labels: approved, size/M

#8728 chore: support to handle the old cd/cmpv when using dual operator mode
  deploy/helm/scripts/change_addon_release.sh
  deploy/helm/scripts/change_kb_release.sh
  deploy/helm/scripts/post_install_1.0_addon.sh
  deploy/helm/scripts/pre_install_1.0_addon.sh
Labels: approved, size/L

#8716 chore: helm values for registry config
  deploy/helm/templates/configmap.yaml
  deploy/helm/values.yaml
Labels: approved, size/S
