Repository apecloud/kubeblocks, pull requests merged in 2024-07, with the labels that each got.

#7671 chore: modify the certificate validity period
  pkg/controller/plan/tls_utils.go
Labels: approved, size/XS

#7664 docs: fix 0.9 docs
  docs/api_docs/handle-an-exception/full-disk-lock.md
  docs/api_docs/instance-template/how-to-use-instance-template.md
  docs/api_docs/instance-template/introduction.md
  docs/api_docs/kubeblocks-for-apecloud-mysql/cluster-management/create-and-connect-a-mysql-cluster.md
  docs/api_docs/kubeblocks-for-kafka/cluster-management/create-a-kafka-cluster.md
  docs/api_docs/kubeblocks-for-redis/redis-cluster-mode.md
  docs/api_docs/maintenance/backup-and-restore/backup/configure-backuppolicy.md
  docs/api_docs/maintenance/cross-k8s-deployment/cross-k8s-deployment.md
  docs/api_docs/maintenance/in-place-update/ignore-vertical-scale.md
  docs/api_docs/maintenance/in-place-update/overview.md
  docs/api_docs/maintenance/scale/scale-for-specified-instance.md
  docs/api_docs/maintenance/scale/vertical-and-horizontal-scale.md
  docs/api_docs/observability/alert.md
  docs/api_docs/observability/monitor-database.md
  docs/img/api-monitoring.png
  docs/user_docs/kubeblocks-for-kafka/configuration/configuration.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/switchover.md
  docs/user_docs/kubeblocks-for-mongodb/configuration/configuration.md
  docs/user_docs/kubeblocks-for-mysql/cluster-management/switchover.md
  docs/user_docs/kubeblocks-for-mysql/configuration/configuration.md
  docs/user_docs/kubeblocks-for-mysql/proxy/apecloud-mysql-proxy.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/switchover.md
  docs/user_docs/kubeblocks-for-postgresql/configuration/configuration.md
  docs/user_docs/kubeblocks-for-pulsar/configuration/configuration.md
  docs/user_docs/observability/monitor-database.md
  i18n/zh-cn/developer-docs/integration/parameter-template.md
  i18n/zh-cn/user-docs/kubeblocks-for-kafka/cluster-management/expand-volume.md
Labels: approved, size/L

#7676 fix: upgrade `rsm-env` object
  controllers/apps/transformer_component_workload_upgrade.go
  pkg/controller/instanceset/instance_util.go
Labels: approved, size/M

#7681 fix: upgrade `rsm-env` object (#7676)
  controllers/apps/transformer_component_workload_upgrade.go
  pkg/controller/instanceset/instance_util.go
Labels: size/M

#7684 fix: upgrade hang and can not cancel the v-scale if supporting vertical scaling in place.
  controllers/apps/operations/horizontal_scaling.go
  controllers/apps/operations/ops_comp_helper.go
  controllers/apps/operations/ops_progress_util.go
  controllers/apps/operations/ops_util_test.go
  controllers/apps/operations/restart.go
  controllers/apps/operations/type.go
  controllers/apps/operations/upgrade.go
  controllers/apps/operations/vertical_scaling.go
  controllers/apps/operations/volume_expansion.go
  controllers/apps/opsrequest_controller.go
Labels: approved, size/M

#7683 chore: replace default headless svc servicePorts
  pkg/controller/instanceset/instance_util.go
Labels: approved, size/XS

#7690 fix: call lorry failed when pod is pending and it has no lorry container
  pkg/lorry/client/httpclient.go
Labels: approved, size/S

#7677 chore: don't set placement annotation if no multi-cluster configured
  controllers/apps/transformer_component_workload.go
  pkg/controller/component/component.go
Labels: approved, size/S

#7696 fix: volumeMount duplicated (#7692)
  apis/apps/v1beta1/meta.go
Labels: approved, size/S

#7701 chore: release addons cluster chart
  .github/workflows/release-helm-chart.yml
Labels: approved, size/S

#7709 fix: redis display password
  pkg/lorry/engines/redis/commands.go
Labels: size/XS

#7693 chore: remove the default role selector in expose
  apis/apps/v1alpha1/opsrequest_types.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/expose.go
  controllers/apps/operations/expose_test.go
  controllers/apps/opsrequest_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/M

#7711 chore: use the static build binary of curl
  docker/Dockerfile-tools
  pkg/controller/component/lorry_utils.go
  pkg/lorry/client/k8sexec_client.go
Labels: approved, size/S

#7707 feat: add instance template public api
  pkg/controller/instanceset/instance_template_util.go
Labels: area/user-interaction, size/M, pre-approve

#7702 chore: merge user defined labels to its template
  controllers/apps/transformer_component_workload.go
Labels: approved, size/XS

#7713 chore: revert "compatible with a special usage of cmpd host-network #7647)"
  pkg/controller/component/definition_convertor.go
  pkg/controller/component/synthesize_component.go
Labels: approved, size/S

#7568 docs: supplement content of developer documentation
  docs/01 - build.md
Labels: size/M, pre-approve

#7721 chore: fix header license check FAIL
  .github/workflows/release-helm-chart.yml
  pkg/controller/instanceset/instance_template_util.go
Labels: approved, size/S

#7680 feat: add a timeoutSeconds field to check if the opsRequest is running timed out
  apis/apps/v1alpha1/opsrequest_conditions.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/ops_manager.go
  controllers/apps/operations/ops_util.go
  controllers/apps/opsrequest_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: area/user-interaction, approved, size/L

#7728 feat: example expose roleSelector specified
  examples/apecloud-mysql/expose-disable.yaml
  examples/apecloud-mysql/expose-enable.yaml
  examples/mongodb/expose-disable.yaml
  examples/mongodb/expose-enable.yaml
  examples/mysql/expose-disable.yaml
  examples/mysql/expose-enable.yaml
  examples/postgresql/expose-disable.yaml
  examples/postgresql/expose-enable.yaml
  examples/redis/expose-disable.yaml
  examples/redis/expose-enable.yaml
Labels: size/S

#7724 chore: filter duplicate custom volume mounts
  controllers/apps/transformer_component_custom_volumes.go
Labels: approved, size/S

#7732 fix: backup job envfrom not take effect
  pkg/dataprotection/backup/request.go
Labels: approved, size/XS

#7738 chore: update doc of cluster's serviceaccount name
  apis/apps/v1alpha1/cluster_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/M

#7739 fix: automatically create a ServiceAccount by default if any lifecycle actions are present
  controllers/apps/transformer_component_rbac.go
Labels: approved, size/S

#7607 feat: InstanceSet supports Instance global ordinal for each InstanceTemplate
  apis/apps/v1alpha1/cluster_types.go
  apis/workloads/v1alpha1/instanceset_types.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/component_hscale_volume_populator.go
  controllers/apps/operations/horizontal_scaling.go
  controllers/apps/operations/start.go
  controllers/apps/operations/stop.go
  controllers/apps/operations/vertical_scaling.go
  controllers/apps/operations/volume_expansion.go
  controllers/apps/transformer_component_service.go
  controllers/apps/transformer_component_status.go
  controllers/apps/transformer_component_workload.go
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  pkg/controller/component/vars.go
  pkg/controller/component/workload_utils.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/object_builder.go
  pkg/controller/instanceset/object_builder_test.go
  pkg/controller/instanceset/reconciler_assistant_object.go
  pkg/controller/instanceset/reconciler_revision_update.go
Labels: area/user-interaction, size/XXL, pre-approve

#7746 feat: InstanceSet supports Instance global ordinal for each InstanceTemplate
  apis/apps/v1alpha1/cluster_types.go
  apis/workloads/v1alpha1/instanceset_types.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/component_hscale_volume_populator.go
  controllers/apps/operations/horizontal_scaling.go
  controllers/apps/operations/start.go
  controllers/apps/operations/stop.go
  controllers/apps/operations/vertical_scaling.go
  controllers/apps/operations/volume_expansion.go
  controllers/apps/transformer_component_service.go
  controllers/apps/transformer_component_status.go
  controllers/apps/transformer_component_workload.go
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  pkg/controller/component/vars.go
  pkg/controller/component/workload_utils.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/object_builder.go
  pkg/controller/instanceset/object_builder_test.go
  pkg/controller/instanceset/reconciler_assistant_object.go
  pkg/controller/instanceset/reconciler_revision_update.go
Labels: size/XXL

#7745 feat: use scheduling policy for instance template
  apis/apps/v1alpha1/SchedulingPolicy.go
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/instanceset_types.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  pkg/controller/component/rsm_convertor.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
Labels: size/XXL

#7737 fix: custom ops can not be scheduled the target node when using volumeMounts in opsDefinition
  controllers/apps/operations/custom/action_workload.go
Labels: approved, size/XS

#7762 chore: spec.preConditionDeadlineSeconds of the opsRequest is invalid
  apis/apps/v1alpha1/opsrequest_validation.go
  controllers/apps/operations/ops_manager.go
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/L

#7763 fix: unstable test case
  controllers/apps/operations/ops_util_test.go
Labels: approved, size/XS

#7778 chore: fix lint error
  apis/apps/v1alpha1/scheduling_policy.go
  apis/workloads/v1alpha1/instanceset_types.go
  config/crd/bases/apps.kubeblocks.io_servicedescriptors.yaml
  deploy/helm/crds/apps.kubeblocks.io_servicedescriptors.yaml
  pkg/controller/instanceset/instance_template_util.go
  pkg/controller/instanceset/instance_util_test.go
Labels: size/M

#7710 feat: support to rebuild the instance with scaling replicas horizontally
  apis/apps/v1alpha1/opsrequest_types.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/rebuild_instance.go
  controllers/apps/operations/rebuild_instance_inplace.go
  controllers/apps/operations/rebuild_instance_test.go
  controllers/apps/operations/vertical_scaling.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/const.go
  pkg/testutil/apps/cluster_instance_set_test_util.go
Labels: area/user-interaction, approved, size/XXL

#7780 chore: add account provision action support
  pkg/constant/lorry.go
  pkg/controller/component/lorry_utils.go
  pkg/lorry/engines/custom/manager.go
  pkg/lorry/operations/user/create.go
Labels: approved, size/M

#7725 feat: support start and stop through cluster API
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/component_controller_test.go
  controllers/apps/operations/start.go
  controllers/apps/operations/start_test.go
  controllers/apps/operations/stop.go
  controllers/apps/operations/stop_test.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_component_status.go
  controllers/apps/transformer_component_workload.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/annotations.go
  pkg/controller/builder/builder_component.go
  pkg/controller/component/component.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/component/workload_utils.go
  pkg/testutil/apps/cluster_factory.go
Labels: approved, size/XL

#7783 feat: support start and stop through cluster API
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/component_controller_test.go
  controllers/apps/operations/start.go
  controllers/apps/operations/start_test.go
  controllers/apps/operations/stop.go
  controllers/apps/operations/stop_test.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_component_status.go
  controllers/apps/transformer_component_workload.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/const.go
  pkg/controller/builder/builder_component.go
  pkg/controller/component/component.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/component/workload_utils.go
  pkg/testutil/apps/cluster_factory.go
Labels: size/XL

#7782 chore: limit the min replicas for scale-in
  controllers/apps/component_controller_test.go
  controllers/apps/transformer_component_validation.go
Labels: approved, size/L

#7784 chore: add example for redis topology for replication-twemproxy
  examples/redis/cluster-cd-topology-twemproxy.yaml
Labels: approved, size/L

#7787 fix: stop and start ops is hang
  controllers/apps/operations/ops_progress_util.go
Labels: approved, size/XS

#7785 chore: Add compatibility for old addons that specify the account provision action but do not actually work
  controllers/apps/component_controller_test.go
  controllers/apps/transformer_component_account_provision.go
  pkg/controller/component/lorry_utils.go
  pkg/lorry/client/client.go
  pkg/lorry/client/client_mock.go
  pkg/lorry/client/httpclient_test.go
  pkg/lorry/client/interface.go
  pkg/lorry/ctl/createuser.go
  pkg/lorry/engines/base.go
  pkg/lorry/engines/custom/manager.go
  pkg/lorry/engines/dbmanager_mock.go
  pkg/lorry/engines/interface.go
  pkg/lorry/engines/models/userinfo.go
  pkg/lorry/engines/mysql/user.go
  pkg/lorry/engines/postgres/user.go
  pkg/lorry/engines/redis/user.go
  pkg/lorry/operations/user/create.go
  pkg/lorry/operations/user/describe_test.go
  pkg/lorry/vault/database.go
Labels: approved, size/L

#7792 fix: ops crash
  controllers/apps/operations/restore.go
Labels: approved, size/XS

#7770 chore: add some good-first-issue comments
  controllers/apps/component_hscale_volume_populator.go
  controllers/apps/transformer_component_account.go
  controllers/apps/transformer_component_account_provision.go
  controllers/apps/transformer_component_tls.go
  controllers/apps/transformer_component_workload.go
  controllers/extensions/addon_controller.go
  pkg/configuration/config_manager/handler_util.go
  pkg/controller/configuration/config_utils.go
  pkg/controller/configuration/operator.go
  pkg/controller/configuration/template_wrapper.go
Labels: approved, size/M

#7798 docs: fix broken links
  docs/api_docs/installation/install-addons.md
  docs/api_docs/installation/install-kubeblocks.md
  docs/api_docs/installation/upgrade/_category_.yml
  docs/api_docs/kubeblocks-for-apecloud-mysql/cluster-management/create-and-connect-an-apecloud-mysql-cluster.md
  docs/api_docs/kubeblocks-for-elasticsearch/manage-elasticsearch.md
  docs/api_docs/kubeblocks-for-kafka/cluster-management/create-a-kafka-cluster.md
  docs/api_docs/kubeblocks-for-milvus/manage-milvus.md
  docs/api_docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
  docs/api_docs/kubeblocks-for-mysql-community-edition/cluster-management/create-and-connect-a-mysql-cluster.md
  docs/api_docs/kubeblocks-for-postgresql/cluster-management/create-and-connect-a-postgresql-cluster.md
  docs/api_docs/kubeblocks-for-pulsar/cluster-management/create-pulsar-cluster-on-kubeblocks.md
  docs/api_docs/kubeblocks-for-qdrant/manage-qdrant.md
  docs/api_docs/kubeblocks-for-redis/cluster-management/create-and-connect-a-redis-cluster.md
  docs/api_docs/kubeblocks-for-weaviate/manage-weaviate.md
Labels: approved, size/M

#7743 feat: Support user-specified podUpdatePolicy
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/instanceset_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  pkg/controller/builder/builder_component.go
  pkg/controller/builder/builder_instance_set.go
  pkg/controller/builder/builder_instance_set_test.go
  pkg/controller/component/component.go
  pkg/controller/component/its_convertor.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/instanceset/reconciler_update_test.go
  pkg/controller/instanceset/types.go
Labels: area/user-interaction, size/L, pre-approve

#7781 feat: Add TemplatesStatus field to InstanceSetStatus
  apis/workloads/v1alpha1/instanceset_types.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  pkg/controller/instanceset/reconciler_status.go
  pkg/controller/instanceset/reconciler_status_test.go
Labels: area/user-interaction, size/L, pre-approve

#7806 feat: cmpd immutable check as default
  controllers/apps/component_controller_test.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/componentdefinition_controller_test.go
  pkg/constant/annotations.go
  pkg/testutil/apps/componentdefinition_factory.go
Labels: area/user-interaction, approved, size/L

#7818 feat: cmpd immutable check as default
  controllers/apps/component_controller_test.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/componentdefinition_controller_test.go
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/annotations.go
  pkg/testutil/apps/componentdefinition_factory.go
Labels: size/L

#7817 chore: udpate ob root passwd env name
  pkg/lorry/engines/oceanbase/config.go
Labels: approved, size/S

#7811 chore: change host-network in cmpd as immutable
  apis/apps/v1alpha1/componentdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/componentdefinition_controller.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/L

#7815 fix: failed to prometheus scrape metrics (#7800)
  deploy/helm/values.yaml
  pkg/controller/factory/builder.go
Labels: approved, size/XS

#7824 fix: mysql/wesql has no slow log (#7823)
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
Labels: approved, size/XS

#7827 chore: pick mysql/wesql has no slow log
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
Labels: size/XS

#7812 chore: refine Action and Probe definition
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/operations/switchover_util.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/action_post_provision_test.go
  pkg/controller/component/action_pre_terminate_test.go
  pkg/controller/component/action_utils.go
  pkg/controller/component/action_utils_test.go
  pkg/controller/component/definition_convertor.go
  pkg/controller/component/definition_convertor_test.go
  pkg/controller/component/its_convertor.go
  pkg/controller/component/its_convertor_test.go
  pkg/controller/component/lorry_utils.go
  pkg/controller/component/lorry_utils_test.go
  pkg/testutil/apps/constant.go
Labels: approved, size/XXL

#7799 fix: backuppolicy depends on component in cluster controller
  controllers/apps/transformer_cluster_backup_policy.go
Labels: approved, size/XS

#7834 fix: configuration parameters do not take effect after rerenderd (#7833)
  pkg/controller/configuration/pipeline.go
Labels: approved, size/XS

#7825 chore: adjust port name to number port (#7804)
  pkg/common/monitor.go
  pkg/common/monitor_test.go
Labels: approved, size/L

#7840 chore: set component ownership when resolve component vars error
  controllers/apps/transformer_component_ownership.go
  controllers/apps/transformer_component_vars.go
Labels: approved, size/S

#7838 chore: adapt lorry for oceanbase replication change into one component
  pkg/lorry/dcs/k8s.go
Labels: approved, size/S

#7845 chore: add wechat contact info
  README.md
  docs/img/wechat-assistant.jpg
Labels: approved, size/XS

#7857 fix: cannot scheduled the pod which is created by custom opsRequest when the instance exists anti-affinity
  controllers/apps/operations/custom/action_exec.go
  controllers/apps/operations/custom/utils.go
  controllers/apps/operations/custom/workload_job.go
  controllers/apps/operations/custom/workload_pod.go
Labels: approved, size/S

#7855 docs: change pic size and correct grammar
  README.md
Labels: approved, size/S

#7866 chore: remove unused application addons
  deploy/helm/templates/applications/chaos-mesh-addon.yaml
  deploy/helm/templates/applications/csi-s3-addon.yaml
  deploy/helm/templates/applications/external-dns-addon.yaml
  deploy/helm/templates/applications/external-dns-values.yaml
  deploy/helm/templates/applications/kubebench-addon.yaml
  deploy/helm/templates/applications/migration-addon.yaml
  deploy/helm/templates/applications/minio.yaml
  deploy/helm/templates/applications/nvidia-gpu-exporter-addon.yaml
  deploy/helm/templates/applications/nyancat-addon.yaml
  deploy/helm/templates/applications/pyroscope-addon.yaml
  deploy/helm/values.yaml
Labels: approved, size/XL

#7852 feat: support to specify k8s scheduling policy in cluster API
  .github/utils/typos.toml
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/cluster_controller_test.go
  controllers/apps/operations/datascript.go
  controllers/apps/systemaccount_util.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_component.go
  pkg/controller/component/component.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/plan/restore.go
  pkg/controller/scheduling/scheduling_utils.go
  pkg/controller/scheduling/scheduling_utils_test.go
  pkg/controller/scheduling/suit_test.go
Labels: size/XXL

#7703 feat: support backup and restore SystemAccounts
  controllers/apps/transformer_component_account.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/utils.go
  pkg/constant/annotations.go
  pkg/constant/backup.go
  pkg/controller/factory/builder.go
  pkg/dataprotection/restore/utils.go
  pkg/testutil/dataprotection/backup_utils.go
Labels: size/L, pre-approve

#7850 feat: support customized controller user-agent
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/release-image.yml
  Makefile
  cmd/dataprotection/main.go
  cmd/manager/main.go
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  docker/Dockerfile
  docker/docker.mk
  pkg/controllerutil/util.go
  version/version.go
Labels: area/user-interaction, approved, size/L

#7867 feat: support customized controller user-agent (#7850)
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/release-image.yml
  Makefile
  cmd/dataprotection/main.go
  cmd/manager/main.go
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  docker/Dockerfile
  docker/docker.mk
  pkg/controllerutil/util.go
  version/version.go
Labels: size/L

#7863 fix: using right doc to offline instance(#7862)
  docs/api_docs/maintenance/scale/scale-for-specified-instance.md
Labels: size/S, pre-approve

#7810 chore: add check tls and uint testing
  controllers/apps/transformer_component_tls.go
  controllers/apps/transformer_component_tls_test.go
Labels: approved, size/M

#7716 fix: use ca gen cert file insteat of selfsign ca
  pkg/controller/plan/tls_utils.go
Labels: size/M, pre-approve

#7872 fix: create multi pod failed when the pod selection strategy is All for custom ops
  controllers/apps/operations/custom/action_workload.go
Labels: approved, size/XS

#7873 fix: podUpdatePolicy update issue
  controllers/apps/transformer_cluster_component.go
Labels: size/XS, pre-approve

#7764 chore: remove clusterdefinition.spec.type
  apis/apps/v1alpha1/clusterdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/labels.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
Labels: approved, size/M

#7766 chore: remove metric and monitor from clusterdefinition
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/component.go
  pkg/controller/component/definition_convertor.go
Labels: approved, size/L

#7877 chore: remove monitor from cmpdHash function
  controllers/apps/componentdefinition_controller.go
Labels: size/XS, pre-approve

#7830 feat: Support setting ParallelPodManagement concurrency
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/instanceset_types.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_component_workload.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  pkg/controller/builder/builder_component.go
  pkg/controller/builder/builder_instance_set.go
  pkg/controller/builder/builder_instance_set_test.go
  pkg/controller/component/component.go
  pkg/controller/component/its_convertor.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/instanceset/reconciler_instance_alignment.go
  pkg/controller/instanceset/reconciler_instance_alignment_test.go
  pkg/controller/instanceset/utils.go
  pkg/controller/instanceset/utils_test.go
Labels: area/user-interaction, size/L, pre-approve

#7879 feat: Support setting ParallelPodManagement concurrency
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/instanceset_types.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_component_workload.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  pkg/controller/builder/builder_component.go
  pkg/controller/builder/builder_instance_set.go
  pkg/controller/builder/builder_instance_set_test.go
  pkg/controller/component/component.go
  pkg/controller/component/rsm_convertor.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/instanceset/reconciler_instance_alignment.go
  pkg/controller/instanceset/reconciler_instance_alignment_test.go
  pkg/controller/instanceset/utils.go
  pkg/controller/instanceset/utils_test.go
Labels: size/L

#7880 fix: PodUpdatePolicy field cannot be synchronized from component to instanceSet
  controllers/apps/transformer_component_workload.go
Labels: size/XS, pre-approve

#7885 chore: update slack link
  README.md
Labels: approved, size/XS

#7884 fix: duplicate volume name when the pod selection strategy is All for custom ops
  controllers/apps/operations/custom/action_workload.go
Labels: approved, size/XS

#7883 chore: handle update orders for stop
  controllers/apps/component_controller_test.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_cluster_component_test.go
Labels: approved, size/L

#7878 chore: remove the HTTP action
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/XXL

#7841 fix: do not call memberleave if the action is undefined
  controllers/apps/component_controller_test.go
  controllers/apps/transformer_component_workload.go
Labels: approved, size/M

#7882 chore: add the region field to the minio StorageProvider
  deploy/helm/templates/storageprovider/legacy.yaml
  deploy/helm/templates/storageprovider/minio.yaml
Labels: approved, size/S

#7897 fix: redis cluster phase is always empty
  controllers/apps/transformer_cluster_backup_policy.go
Labels: approved, size/XS

#7898 fix: avoid concurrency is 0
  pkg/controller/instanceset/utils.go
  pkg/controller/instanceset/utils_test.go
Labels: size/S, pre-approve

#7839 chore: add Retry and Commit control methods to kubebuilderx
  controllers/experimental/nodecountscaler_controller.go
  controllers/experimental/reconciler_scale_target_cluster.go
  controllers/experimental/reconciler_scale_target_cluster_test.go
  controllers/experimental/reconciler_update_status.go
  controllers/experimental/reconciler_update_status_test.go
  controllers/workloads/instanceset_controller.go
  pkg/controller/instanceset/in_place_update_util_test.go
  pkg/controller/instanceset/reconciler_assistant_object.go
  pkg/controller/instanceset/reconciler_assistant_object_test.go
  pkg/controller/instanceset/reconciler_deletion.go
  pkg/controller/instanceset/reconciler_deletion_test.go
  pkg/controller/instanceset/reconciler_fix_meta.go
  pkg/controller/instanceset/reconciler_fix_meta_test.go
  pkg/controller/instanceset/reconciler_instance_alignment.go
  pkg/controller/instanceset/reconciler_instance_alignment_test.go
  pkg/controller/instanceset/reconciler_revision_update.go
  pkg/controller/instanceset/reconciler_revision_update_test.go
  pkg/controller/instanceset/reconciler_status.go
  pkg/controller/instanceset/reconciler_status_test.go
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/instanceset/reconciler_update_test.go
  pkg/controller/kubebuilderx/controller.go
  pkg/controller/kubebuilderx/controller_test.go
  pkg/controller/kubebuilderx/reconciler.go
Labels: approved, size/XL

#7896 fix: avoid override original static env
  pkg/controller/component/synthesize_component.go
Labels: size/XS, pre-approve
