Repository apecloud/kubeblocks, pull requests merged in 2024-11, with the labels that each got.

#8291 fix: switchover failed when component contains instance templates
  apis/operations/v1alpha1/opsrequest_types.go
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
  pkg/operations/switchover_util.go
Labels: approved, size/M

#8212 feat: introduce the available probe and condition for component
  apis/apps/v1/componentdefinition_types.go
  apis/apps/v1/types.go
  apis/apps/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/componentdefinition_controller.go
  controllers/apps/componentdefinition_controller_test.go
  controllers/apps/transformer_cluster_status.go
  controllers/apps/transformer_component_service.go
  controllers/apps/transformer_component_status.go
  controllers/k8score/event_controller.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/available.go
  pkg/controller/component/available_test.go
  pkg/controller/component/kbagent.go
  pkg/controller/component/suite_test.go
  pkg/controller/component/workload_utils.go
  pkg/controller/instanceset/pod_role_event_handler.go
  pkg/kbagent/proto/proto.go
  pkg/kbagent/service/probe.go
  pkg/kbagent/service/probe_test.go
  pkg/kbagent/util/event.go
  pkg/testutil/apps/componentdefinition_factory.go
Labels: approved, size/XXL

#8385 feat: support image rolling update
  go.mod
  pkg/controller/instanceset/in_place_update_util.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/instanceset/reconciler_update_test.go
Labels: area/user-interaction, approved, size/L

#8389 feat: support image rolling update (#8385)
  go.mod
  pkg/controller/instanceset/in_place_update_util.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/instanceset/reconciler_update_test.go
Labels: approved, size/L

#8393 fix: the parameter of membername is wrong for leavemember
  pkg/lorry/client/client.go
Labels: approved, size/XS

#8341 chore: refine the component phases and remove the Abnormal phase
  apis/apps/v1/cluster_types.go
  apis/apps/v1/component_types.go
  apis/apps/v1/deprecated.go
  apis/apps/v1/types.go
  apis/operations/v1alpha1/opsrequest_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  controllers/apps/cluster_controller_test.go
  controllers/apps/component_controller_test.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/componentdefinition_controller_test.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_cluster_component_status.go
  controllers/apps/transformer_cluster_component_status_test.go
  controllers/apps/transformer_cluster_component_test.go
  controllers/apps/transformer_cluster_status.go
  controllers/apps/transformer_component_account_provision.go
  controllers/apps/transformer_component_deletion.go
  controllers/apps/transformer_component_pre_terminate.go
  controllers/apps/transformer_component_status.go
  controllers/operations/opsrequest_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/available.go
  pkg/controller/component/lifecycle/kbagent.go
  pkg/controller/plan/restore.go
  pkg/controller/plan/restore_test.go
  pkg/controllerutil/pod_utils.go
  pkg/operations/custom_test.go
  pkg/operations/expose.go
  pkg/operations/horizontal_scaling_test.go
  pkg/operations/ops_comp_helper.go
  pkg/operations/ops_progress_util_test.go
  pkg/operations/ops_util_test.go
  pkg/operations/rebuild_instance.go
  pkg/operations/rebuild_instance_test.go
  pkg/operations/reconfigure_test.go
  pkg/operations/restart_test.go
  pkg/operations/suite_test.go
  pkg/operations/switchover.go
  pkg/operations/switchover_test.go
  pkg/operations/upgrade_test.go
  pkg/operations/vertical_scaling_test.go
  pkg/operations/volume_expansion_test.go
  pkg/testutil/apps/cluster_util.go
  pkg/testutil/apps/component_util.go
Labels: approved, size/XL

#8368 chore: enhance logging for more detailed information
  pkg/kbagent/server/httpserver.go
  pkg/kbagent/service/action.go
Labels: approved, size/M

#8381 feat: support for defining the orders of components created dynamically
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  controllers/apps/clusterdefinition_controller.go
  controllers/apps/transformer_cluster_api_normalization.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_cluster_component_test.go
  controllers/apps/transformer_cluster_load_resources.go
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: area/user-interaction, approved, size/L

#8400 fix: port names of the headless service are conflict
  pkg/controller/instanceset/object_builder.go
  pkg/controller/instanceset/object_builder_test.go
Labels: approved, size/M

#8397 chore: fix unstable UT in storageprovider_controller_test.go
  controllers/dataprotection/storageprovider_controller_test.go
  pkg/testutil/apps/common_util.go
Labels: approved, size/S

#8324 chore: removed agamotto addon
  deploy/helm/templates/_helpers.tpl
  deploy/helm/templates/applications/apecloud-otel-collector-addon.yaml
  deploy/helm/templates/applications/apecloud-otel-collector-values.yaml
  deploy/helm/values.yaml
  pkg/controller/instanceset/revision_util_test.go
Labels: approved, size/L

#8406 chore: keep role label when doing image in-place update
  pkg/controller/instanceset/in_place_update_util.go
Labels: approved, size/S

#8297 fix: align pitr backup retention with cluster retentionPeriod
  controllers/apps/transformer_cluster_backup_policy.go
Labels: approved, size/XS

#8407 chore: add minReadySeconds to mutable field
  controllers/apps/componentdefinition_controller.go
  controllers/apps/componentdefinition_controller_test.go
Labels: approved, size/XS

#8335 fix: build config-manager container NPE
  pkg/controller/configuration/operator_test.go
  pkg/controller/configuration/tool_image_builder.go
Labels: approved, size/M

#8409 chore: add minReadySeconds to mutable field
  controllers/apps/componentdefinition_controller.go
  controllers/apps/componentdefinition_controller_test.go
Labels: approved, size/XS

#8408 chore: keep role label when doing image in-place update (#8406)
  pkg/controller/instanceset/in_place_update_util.go
Labels: approved, size/S

#8410 fix: align pitr backup retention with cluster retentionPeriod in back…
  controllers/apps/transformer_cluster_backup_policy.go
Labels: approved, size/XS

#8378 chore: remove service field in instanceset
  apis/workloads/v1/instanceset_types.go
  apis/workloads/v1/zz_generated.deepcopy.go
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/transformer_component_workload.go
  controllers/workloads/instanceset_controller_test.go
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_instance_set.go
  pkg/controller/builder/builder_instance_set_test.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/object_builder.go
  pkg/controller/instanceset/object_builder_test.go
  pkg/controller/instanceset/reconciler_assistant_object.go
  pkg/controller/instanceset/reconciler_instance_alignment_test.go
  pkg/controller/instanceset/reconciler_revision_update_test.go
  pkg/controller/instanceset/suite_test.go
  pkg/controller/instanceset/utils.go
  pkg/controller/instanceset/utils_test.go
Labels: approved, size/XXL

#8418 chore: upgrade e2e test k8s version 1.30
  .github/workflows/e2e-fault.yml
  .github/workflows/e2e-kbcli-k3s.yml
  .github/workflows/e2e-kbcli.yml
  .github/workflows/e2e-performance.yml
  .github/workflows/e2e-smoke.yml
Labels: approved, size/S

#8415 chore: wait for container ready at least for minReadySeconds when doing image rolling update
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/reconciler_update.go
Labels: approved, size/S

#8412 chore: remove curl and grpc probe binaries from tools image
  docker/Dockerfile-tools
  pkg/controller/component/kbagent.go
Labels: approved, size/S

#8417 chore: upgrade ops is always running
  pkg/operations/upgrade.go
Labels: approved, size/S

#8420 chore: upgrade ops always running
  controllers/apps/operations/upgrade.go
Labels: approved, size/S

#8421 chore: add e2e test k8s 1.30
  .github/workflows/e2e-fault.yml
  .github/workflows/e2e-kbcli-k3s.yml
  .github/workflows/e2e-kbcli.yml
  .github/workflows/e2e-performance.yml
  .github/workflows/e2e-smoke.yml
Labels: size/M

#8424 fix: lost event during image rolling update
  pkg/controller/instanceset/reconciler_update.go
Labels: approved, size/XS

#8426 chore: refine containers ready condition during image rolling update
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/instanceset/reconciler_update_test.go
Labels: approved, size/M

#8399 chore: support to install coversion webhook when install kb 1.0
  cmd/helmhook/hook/addon.go
  cmd/helmhook/hook/conversion.go
  cmd/helmhook/hook/cr.go
  cmd/helmhook/hook/crd.go
  cmd/helmhook/hook/logger.go
  cmd/helmhook/hook/multiversion/configconstraint.go
  cmd/helmhook/hook/prepare.go
  cmd/helmhook/hook/stop.go
  cmd/helmhook/hook/types.go
  cmd/helmhook/hook/utils.go
  cmd/helmhook/main.go
  config/rbac/role.yaml
  controllers/extensions/addon_controller.go
  deploy/helm/config/rbac/role.yaml
  deploy/helm/scripts/change_crs_release.sh
  deploy/helm/templates/_helpers.tpl
  deploy/helm/templates/admission/webhookconfiguration.yaml
  deploy/helm/templates/configconstraint-conversion-patch.yaml
  deploy/helm/templates/conversion-patch-hook.yaml
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/templates/kubeblocks-upgrade-hook.yaml
  deploy/helm/templates/rbac/apps_cluster_viewer_role.yaml
  deploy/helm/templates/rbac/apps_clusterdefinition_viewer_role.yaml
  deploy/helm/templates/rbac/apps_configconstraint_viewer_role.yaml
  deploy/helm/templates/rbac/auth_proxy_role_binding.yaml
  deploy/helm/templates/rbac/cluster_pod_required_role.yaml
  deploy/helm/templates/rbac/clusterrole.yaml
  deploy/helm/templates/rbac/clusterrole_binding.yaml
  deploy/helm/templates/rbac/dataprotection_backup_viewer_role.yaml
  deploy/helm/templates/rbac/dataprotection_backuppolicy_viewer_role.yaml
  deploy/helm/templates/rbac/dataprotection_backuppolicytemplate_role.yaml
  deploy/helm/templates/rbac/dataprotection_exec_worker_clusterrolebinding.yaml
  deploy/helm/templates/rbac/dataprotection_restore_viewer_role.yaml
  deploy/helm/templates/rbac/experimental_nodecountscaler_viewer_role.yaml
  deploy/helm/templates/rbac/extensions_addon_viewer_role.yaml
  deploy/helm/templates/rbac/leader_election_role_binding.yaml
  deploy/helm/templates/rbac/operations_opsdefinition_role.yaml
  deploy/helm/templates/rbac/operations_opsrequest_role.yaml
  deploy/helm/templates/rbac/opsrequest_editor_role.yaml
  deploy/helm/templates/rbac/opsrequest_viewer_role.yaml
  deploy/helm/templates/rbac/workloads_instanceset_viewer_role.yaml
  deploy/helm/templates/rbac/workloads_replicatedstatemachine_viewer_role.yaml
  deploy/helm/templates/validate.yaml
  deploy/helm/values.yaml
  docker/Dockerfile-tools
Labels: approved, size/XXL

#8428 fix: switchover ops delayed successfully
  controllers/apps/operations/switchover.go
  controllers/apps/operations/switchover_test.go
  controllers/apps/operations/switchover_util.go
  controllers/apps/operations/switchover_util_test.go
Labels: approved, size/S

#8429 chore: refine containers ready condition during image rolling update
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/instanceset/reconciler_update_test.go
Labels: approved, size/M

#8430 chore: support to restore the account of the sharding cluster
  controllers/apps/operations/restore.go
  controllers/apps/transformer_cluster_shared_account.go
  controllers/apps/transformer_component_account.go
  controllers/dataprotection/backup_controller.go
  pkg/controller/factory/builder.go
Labels: size/M

#8433 chore: support to delete failed backups when deleting cluster
  controllers/apps/cluster_controller_test.go
  controllers/apps/operations/backup.go
  controllers/apps/transform_utils.go
  controllers/apps/transformer_cluster_deletion.go
  pkg/constant/const.go
Labels: approved, size/M

#8435 chore: support to delete failed backups when deleting cluster
  controllers/apps/cluster_controller_test.go
  controllers/apps/transform_utils.go
  controllers/apps/transformer_cluster_deletion.go
  pkg/constant/backup.go
  pkg/constant/labels.go
  pkg/operations/backup.go
Labels: approved, size/M

#8438 chore: lifecycle action support target pod role selector
  pkg/controller/component/component_lifecycle_action_utils.go
Labels: approved, size/S

#8422 chore: pick build config-manager container NPE (#8335)
  pkg/controller/configuration/operator_test.go
  pkg/controller/configuration/tool_image_builder.go
Labels: approved, size/M

#8434 chore: support to restore the account of the sharding cluster
  controllers/apps/transformer_cluster_sharding_account.go
  controllers/apps/transformer_component_account.go
  controllers/dataprotection/backup_controller.go
  pkg/controller/factory/builder.go
  pkg/operations/restore.go
Labels: approved, size/M

#8388 refactor: extract CharacterType from TLS configuration
  controllers/apps/transformer_component_tls.go
  controllers/apps/transformer_component_tls_test.go
  pkg/controller/plan/tls_utils.go
  pkg/controller/plan/tls_utils_test.go
Labels: size/L, pre-approve

#8447 chore: keep globale resources
  deploy/helm/templates/_helpers.tpl
  deploy/helm/templates/backuprepo.yaml
  deploy/helm/templates/rbac/apps_backuppolicytemplate_editor_role.yaml
  deploy/helm/templates/rbac/apps_cluster_editor_role.yaml
  deploy/helm/templates/rbac/apps_clusterdefinition_editor_role.yaml
  deploy/helm/templates/rbac/apps_configconstraint_editor_role.yaml
  deploy/helm/templates/rbac/auth_proxy_client_clusterrole.yaml
  deploy/helm/templates/rbac/auth_proxy_role.yaml
  deploy/helm/templates/rbac/cluster_pod_required_role.yaml
  deploy/helm/templates/rbac/clusterrole.yaml
  deploy/helm/templates/rbac/dataprotection_backup_editor_role.yaml
  deploy/helm/templates/rbac/dataprotection_backuppolicy_editor_role.yaml
  deploy/helm/templates/rbac/dataprotection_exec_worker_clusterrole.yaml
  deploy/helm/templates/rbac/dataprotection_restore_editor_role.yaml
  deploy/helm/templates/rbac/experimental_nodecountscaler_editor_role.yaml
  deploy/helm/templates/rbac/extensions_addon_editor_role.yaml
  deploy/helm/templates/rbac/leader_election_role.yaml
  deploy/helm/templates/rbac/rbac_manager_role.yaml
  deploy/helm/templates/rbac/workloads_instanceset_editor_role.yaml
  deploy/helm/templates/storageprovider/cos.yaml
  deploy/helm/templates/storageprovider/ftp.yaml
  deploy/helm/templates/storageprovider/gcs-s3comp.yaml
  deploy/helm/templates/storageprovider/minio.yaml
  deploy/helm/templates/storageprovider/nfs.yaml
  deploy/helm/templates/storageprovider/obs.yaml
  deploy/helm/templates/storageprovider/oss.yaml
  deploy/helm/templates/storageprovider/pvc.yaml
  deploy/helm/templates/storageprovider/s3.yaml
  deploy/helm/values.yaml
Labels: approved, size/M

#8395 feat: support memberjoin action
  controllers/apps/transformer_component_workload.go
  controllers/apps/transformer_component_workload_test.go
  controllers/apps/utils.go
  pkg/constant/annotations.go
  pkg/testutil/apps/kb_agent_util.go
  pkg/testutil/k8s/pod_util.go
Labels: area/user-interaction, approved, size/XL

#8456 fix: the pod of the custom ops is always pending
  controllers/apps/operations/custom/action_exec.go
  controllers/apps/operations/custom/action_workload.go
  controllers/apps/operations/custom/utils.go
  controllers/apps/operations/custom_test.go
Labels: approved, size/M

#8457 chore: fix install 1.0 bug when existing KB 0.9
  deploy/helm/templates/conversion-patch-hook.yaml
  deploy/helm/templates/rbac/shardingdefinition_editor_role.yaml
Labels: approved, size/M

#8454 feat: deployment in helm chart can define extra annotations and envir…
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
Labels: size/M, pre-approve

#8453 feat: deployment in helm chart can define extra annotations and envir…
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
Labels: size/M, pre-approve

#8466 feat: support recreate pod update policy
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  apis/workloads/v1alpha1/instanceset_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/instanceset/reconciler_update.go
Labels: approved, size/M

#8473 fix: the component controller is not notified when a backup for h-scale becomes ready
  controllers/apps/transformer_component_workload.go
  controllers/apps/transformer_component_workload_test.go
Labels: approved, size/M

#8479 chore: change feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/issues-labeluserdoc.yml
  .github/workflows/pull-request-user-interaction.yaml
Labels: approved, size/XS

#7869 feat: allow pod in place update to cowork with mutating admission webhook
  pkg/controller/instanceset/in_place_update_util.go
  pkg/controller/instanceset/in_place_update_util_test.go
Labels: approved, size/S

#8480 feat: support component-level stop and start capabilities (cherry-pick 934e0ed)
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/ops_comp_helper.go
  controllers/apps/operations/restart.go
  controllers/apps/operations/restart_test.go
  controllers/apps/operations/start.go
  controllers/apps/operations/start_test.go
  controllers/apps/operations/stop.go
  controllers/apps/operations/stop_test.go
  controllers/apps/operations/suite_test.go
  controllers/apps/transformer_cluster_status.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/testutil/apps/cluster_instance_set_test_util.go
Labels: approved, size/XL

#8436 docs: merge mongodb, redis, and milvus cn api docs into user docs
  docs/user_docs/kubeblocks-for-apecloud-mysql/cluster-management/stop-start-a-cluster.md
  docs/user_docs/kubeblocks-for-apecloud-mysql/proxy/apecloud-mysql-proxy.md
  docs/user_docs/kubeblocks-for-milvus/manage-milvus.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/start-stop-a-cluster.md
  docs/user_docs/kubeblocks-for-mongodb/configuration/configuration.md
  docs/user_docs/kubeblocks-for-mysql-community-edition/cluster-management/stop-start-a-cluster.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/start-stop-a-cluster.md
  docs/user_docs/kubeblocks-for-postgresql/high-availability/high-availability.md
  docs/user_docs/kubeblocks-for-redis/cluster-management/stop-start-a-redis-cluster.md
  docs/user_docs/overview/supported-addons.md
  i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/cluster-management/create-and-connect-a-mysql-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/cluster-management/delete-mysql-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/cluster-management/expand-volume.md
  i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/cluster-management/restart-mysql-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/cluster-management/scale-for-apecloud-mysql.md
  i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/cluster-management/stop-start-a-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/cluster-management/switchover.md
  i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/proxy/apecloud-mysql-proxy.md
  i18n/zh-cn/user-docs/kubeblocks-for-milvus/manage-milvus.md
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/cluster-management/delete-a-mongodb-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/cluster-management/expand-volume.md
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/cluster-management/restart-mongodb-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/cluster-management/scale-for-a-mongodb-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/cluster-management/stop-start-a-mongodb-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/cluster-management/switch-over-a-mongodb-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/configuration/configure-cluster-parameters.md
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/kubeblocks-for-mongodb.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql-community-edition/cluster-management/create-and-connect-a-mysql-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql-community-edition/cluster-management/delete-mysql-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql-community-edition/cluster-management/expand-volume.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql-community-edition/cluster-management/restart-mysql-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql-community-edition/cluster-management/scale-for-mysql.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql-community-edition/cluster-management/stop-start-a-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql-community-edition/cluster-management/switchover.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql-community-edition/high-availability/high-availability.md
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/cluster-management/create-and-connect-a-postgresql-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/cluster-management/delete-a-postgresql-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/cluster-management/expand-volume.md
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/cluster-management/restart-a-postgresql-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/cluster-management/scale-for-a-postgresql-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/cluster-management/start-stop-a-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/cluster-management/switchover.md
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/high-availability/high-availability.md
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/postgresql-connection-pool/postgresql-connection-pool.md
  i18n/zh-cn/user-docs/kubeblocks-for-redis/cluster-management/create-and-connect-to-a-redis-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-redis/cluster-management/delete-a-redis-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-redis/cluster-management/expand-volume.md
  i18n/zh-cn/user-docs/kubeblocks-for-redis/cluster-management/restart-a-redis-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-redis/cluster-management/scale-for-a-redis-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-redis/cluster-management/stop-start-a-redis-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-redis/configuration/configure-cluster-parameters.md
  i18n/zh-cn/user-docs/kubeblocks-for-redis/high-availability/high-availability.md
  i18n/zh-cn/user-docs/kubeblocks-for-redis/kubeblocks-for-redis.md
  i18n/zh-cn/user-docs/kubeblocks-for-redis/redis-cluster-mode.md
  i18n/zh-cn/user-docs/overview/database-engines-supported.md
Labels: approved, size/XXL

#8312 chore: support for defining sidecars independently
  PROJECT
  apis/apps/v1/component_types.go
  apis/apps/v1/sidecardefinition_types.go
  apis/apps/v1/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_sidecardefinitions.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_apps_sidecardefinitions.yaml
  config/crd/patches/webhook_in_apps_sidecardefinitions.yaml
  config/rbac/apps_sidecardefinition_editor_role.yaml
  config/rbac/apps_sidecardefinition_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/apps_v1_sidecardefinition.yaml
  controllers/apps/const.go
  controllers/apps/sidecardefinition_controller.go
  controllers/apps/sidecardefinition_controller_test.go
  controllers/apps/suite_test.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_component_vars.go
  controllers/apps/transformer_component_workload.go
  deploy/helm/config/rbac/role.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_sidecardefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/client/clientset/versioned/typed/apps/v1/apps_client.go
  pkg/client/clientset/versioned/typed/apps/v1/fake/fake_apps_client.go
  pkg/client/clientset/versioned/typed/apps/v1/fake/fake_sidecardefinition.go
  pkg/client/clientset/versioned/typed/apps/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/apps/v1/sidecardefinition.go
  pkg/client/informers/externalversions/apps/v1/interface.go
  pkg/client/informers/externalversions/apps/v1/sidecardefinition.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/apps/v1/expansion_generated.go
  pkg/client/listers/apps/v1/sidecardefinition.go
  pkg/constant/labels.go
  pkg/controller/builder/builder_component.go
  pkg/controller/component/component.go
  pkg/controller/component/sidecar.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/component/utils.go
  pkg/generics/type.go
  pkg/testutil/apps/sidecardefinition_factory.go
Labels: approved, size/XXL

#8482 chore: lorry share volume with container
  pkg/controller/component/lorry_utils.go
Labels: approved, size/S

#8232 feat: support validate policy of opsrequest
  apis/operations/v1alpha1/opsrequest_validation.go
  pkg/constant/ops.go
  pkg/operations/horizontal_scaling.go
  pkg/operations/horizontal_scaling_test.go
  pkg/operations/ops_progress_util_test.go
  pkg/operations/ops_util_test.go
Labels: size/L, pre-approve

#8488 chore: remove clusterDefName from synthesized component
  pkg/controller/component/type.go
  pkg/controller/configuration/config_template_test.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
Labels: approved, size/L

#8491 chore: add scripts to change the addon release owner
  deploy/helm/scripts/change_addon_release.sh
  deploy/helm/scripts/change_kb_release.sh
Labels: approved, size/S

#8493 chore: update the pod image that does not have a registry and repository specified
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
Labels: approved, size/S

#8505 fix: wrong its ready condition during image in-place update
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/reconciler_status.go
  pkg/controller/instanceset/reconciler_status_test.go
  pkg/controller/instanceset/reconciler_update.go
Labels: approved, size/L

#8494 chore: ensure the observedGeneration and phase of the component remain consistent
  controllers/apps/transformer_component_status.go
Labels: approved, size/M

#8503 chore: remove hacky for hostNetwork configuration
  controllers/apps/configuration/configuration_controller.go
  controllers/apps/transformer_component_configuration.go
  pkg/controller/component/component.go
Labels: approved, size/M

#8509 fix: wrong its ready condition during image in-place update
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/reconciler_status.go
  pkg/controller/instanceset/reconciler_status_test.go
  pkg/controller/instanceset/reconciler_update.go
Labels: approved, size/L

#8492 fix: apepg address with cluster domain in 0.9
  pkg/lorry/engines/postgres/config.go
  pkg/lorry/engines/postgres/config_test.go
Labels: approved, size/XS

#8504 chore: proper handling for null probes or streaming in kbagent
  pkg/controller/component/kbagent_test.go
  pkg/kbagent/setup.go
Labels: approved, size/M

#8508 chore: should not execute other transformers when the cluster is deleted
  controllers/apps/transformer_cluster_deletion.go
Labels: approved, size/S

#8506 chore: reconcile to preserve the default service type
  apis/apps/v1/cluster_types.go
  apis/apps/v1/component_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/transformer_component_service.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/synthesize_component.go
Labels: approved, size/M

#8440 chore: fix a flaky test
  controllers/apps/cluster_controller_test.go
  pkg/controllerutil/cluster_utils_test.go
  pkg/controllerutil/sharding_utils_test.go
Labels: approved, size/XS

#8515 chore: probes are lost when streaming actions are not specified
  pkg/kbagent/setup.go
Labels: approved, size/XS

#8523 fix: BackupRepo render template with default values
  controllers/dataprotection/backuprepo_controller.go
  controllers/dataprotection/backuprepo_controller_test.go
Labels: size/L, pre-approve

#8526 fix: the member leave action failed, but the controller considers it successful
  controllers/apps/transformer_component_workload.go
Labels: approved, size/XS

#8527 fix: BackupRepo render template with default values (#8523) (pick to release-0.9)
  controllers/dataprotection/backuprepo_controller.go
  controllers/dataprotection/backuprepo_controller_test.go
Labels: size/L, pre-approve

#8529 chore: remove dependency on sigs.k8s.io/kustomize/api/image
  go.mod
  pkg/controller/instanceset/instance_util.go
Labels: approved, size/M

#8530 chore: support to h-scale shard count(pick from d3029e42)
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/opsrequest_webhook.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/horizontal_scaling.go
  controllers/apps/operations/horizontal_scaling_test.go
  controllers/apps/operations/ops_comp_helper.go
  controllers/apps/operations/ops_progress_util.go
  controllers/apps/operations/type.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controllerutil/sharding_utils.go
Labels: size/L

#8531 fix: start the workload before scaling out
  apis/apps/v1/component_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  controllers/apps/component_controller_test.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/transformer_cluster_status.go
  controllers/apps/transformer_component_status.go
  controllers/apps/transformer_component_workload.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/annotations.go
Labels: approved, size/L

#8502 chore: redis support hostnetwork in 0.9
  pkg/lorry/engines/redis/manager.go
  pkg/lorry/engines/redis/redis.go
Labels: approved, size/S

#8535 fix: the component controller is not notified upon restore completion
  controllers/apps/component_controller.go
Labels: approved, size/XS

#8540 chore: remove dependency on sigs.k8s.io/kustomize/api/image (#8529)
  go.mod
  pkg/controller/instanceset/instance_util.go
Labels: approved, size/M

#8541 fix: preConditionDeadlineSeconds of the opsRequest is invalid when creating some opsRequests together (pick from c65ed8c3)
  apis/apps/v1alpha1/opsrequest_webhook.go
  controllers/apps/operations/ops_manager.go
  controllers/apps/operations/ops_util.go
  pkg/constant/annotations.go
Labels: approved, size/L

#8517 chore: hostNetwork supports sharding
  controllers/apps/transformer_cluster_api_normalization.go
  pkg/controller/component/utils.go
Labels: approved, size/S

#8543 chore: some reconciliation trace related corner cases fixed
  controllers/trace/informer_manager.go
  controllers/trace/reconciler_tree.go
  controllers/trace/resources_validator.go
  controllers/trace/suite_test.go
  controllers/trace/type.go
  pkg/constant/const.go
  pkg/controller/kubebuilderx/plan_builder.go
  pkg/controller/kubebuilderx/plan_builder_test.go
Labels: approved, size/M

#8485 docs: fix format and link bugs and add rabbitmq docs
  docs/user_docs/connect_database/connect-database-in-production-environment.md
  docs/user_docs/installation/install-with-helm/install-kubeblocks.md
  docs/user_docs/installation/install-with-kbcli/install-kubeblocks-with-kbcli.md
  i18n/zh-cn/user-docs/connect-databases/connect-to-database-in-production-environment.md
  i18n/zh-cn/user-docs/create_database/overview-of-create-database.md
  i18n/zh-cn/user-docs/installation/install-with-helm/install-kubeblocks.md
  i18n/zh-cn/user-docs/installation/install-with-kbcli/install-kubeblocks-with-kbcli.md
  i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/cluster-management/create-and-connect-an-apecloud-mysql-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-elasticsearch/manage-elasticsearch.md
  i18n/zh-cn/user-docs/kubeblocks-for-rabbitmq/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-rabbitmq/manage-rabbitmq.md
  i18n/zh-cn/user-docs/kubeblocks-for-redis/redis-cluster-mode.md
  i18n/zh-cn/user-docs/kubeblocks-for-starrocks/manage-starrocks.md
  i18n/zh-cn/user-docs/kubeblocks-for-weaviate/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-weaviate/manage-weaviate.md
  i18n/zh-cn/user-docs/kubeblocks-for-xinference/_category_.yml
  i18n/zh-cn/user-docs/kubeblocks-for-xinference/manage-xinference.md
Labels: approved, size/XXL

#8472 feat: support backup and restore parameters
  apis/dataprotection/v1alpha1/actionset_types.go
  apis/dataprotection/v1alpha1/backup_types.go
  apis/dataprotection/v1alpha1/backupschedule_types.go
  apis/dataprotection/v1alpha1/restore_types.go
  apis/dataprotection/v1alpha1/types.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  apis/operations/v1alpha1/opsrequest_types.go
  apis/operations/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/dataprotection.kubeblocks.io_actionsets.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backupschedules.yaml
  config/crd/bases/dataprotection.kubeblocks.io_restores.yaml
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/dataprotection/actionset_controller.go
  controllers/dataprotection/actionset_controller_test.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/backuppolicytemplate_controller.go
  controllers/dataprotection/backuppolicytemplate_controller_test.go
  controllers/dataprotection/backupschedule_controller_test.go
  controllers/dataprotection/restore_controller_test.go
  deploy/helm/crds/dataprotection.kubeblocks.io_actionsets.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backupschedules.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_restores.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/backup.md
  pkg/common/openapiv3schema.go
  pkg/constant/backup.go
  pkg/controller/builder/builder_component.go
  pkg/controller/plan/restore.go
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/backup/scheduler.go
  pkg/dataprotection/backup/utils.go
  pkg/dataprotection/restore/builder.go
  pkg/dataprotection/restore/utils.go
  pkg/dataprotection/utils/backup.go
  pkg/dataprotection/utils/envvar.go
  pkg/dataprotection/utils/utils.go
  pkg/operations/backup.go
  pkg/operations/custom.go
  pkg/operations/restore.go
  pkg/testutil/dataprotection/backup_utils.go
  pkg/testutil/dataprotection/backuppolicytemplate_factory.go
  pkg/testutil/dataprotection/constant.go
  pkg/testutil/dataprotection/restore_factory.go
  pkg/testutil/dataprotection/utils.go
Labels: area/user-interaction, approved, size/XXL

#8547 docs: fix bugs in installation docs
  docs/user_docs/installation/install-kubeblocks.md
  docs/user_docs/overview/supported-addons.md
  i18n/zh-cn/user-docs/installation/install-kubeblocks.md
Labels: approved, size/M

#8554 docs: sync installation and overview docs from the main branch
  docs/user_docs/installation/install-kubeblocks.md
  docs/user_docs/overview/supported-addons.md
  i18n/zh-cn/user-docs/installation/install-kubeblocks.md
Labels: approved, size/M

#8545 chore: remove the built-in function for generating ssh keys
  go.mod
  go.sum
  pkg/gotemplate/sshkeygenerator.go
  pkg/gotemplate/sshkeygenerator_test.go
  pkg/gotemplate/tpl_engine.go
  pkg/gotemplate/tpl_engine_test.go
Labels: approved, size/L

#8550 fix: restore ops is always creating
  pkg/operations/restore.go
Labels: approved, size/XS

#8522 chore: filter events to reconcile by CRD API version
  cmd/dataprotection/main.go
  cmd/manager/main.go
  controllers/apps/backuppolicytemplate_controller.go
  controllers/apps/opsrequest_controller.go
  controllers/apps/servicedescriptor_controller.go
  controllers/apps/systemaccount_controller.go
  controllers/experimental/nodecountscaler_controller.go
  pkg/constant/const.go
  pkg/controllerutil/predicate.go
Labels: approved, size/L
