Repository apecloud/kubeblocks, pull requests merged in 2024-03, with the labels that each got.

#6717 chore: e2e support test on aks
  .github/workflows/e2e-fault.yml
  .github/workflows/e2e-kbcli.yml
  .github/workflows/e2e-smoke.yml
  .github/workflows/package-version.yml
  .github/workflows/release-version.yml
Labels: test, approved, size/M

#6641 feat: supports to specify namespaces that the operator should manage
  cmd/dataprotection/main.go
  cmd/manager/main.go
  controllers/apps/backuppolicytemplate_controller.go
  controllers/apps/class_controller.go
  controllers/apps/cluster_controller.go
  controllers/apps/clusterdefinition_controller.go
  controllers/apps/clusterversion_controller.go
  controllers/apps/component_controller.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/configuration/configconstraint_controller.go
  controllers/apps/configuration/configuration_controller.go
  controllers/apps/configuration/reconfigure_controller.go
  controllers/apps/opsdefinition_controller.go
  controllers/apps/opsrequest_controller.go
  controllers/apps/servicedescriptor_controller.go
  controllers/apps/systemaccount_controller.go
  controllers/dataprotection/actionset_controller.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backuppolicy_controller.go
  controllers/dataprotection/backuprepo_controller.go
  controllers/dataprotection/backupschedule_controller.go
  controllers/dataprotection/gc_controller.go
  controllers/dataprotection/log_collection_controller.go
  controllers/dataprotection/restore_controller.go
  controllers/dataprotection/volumepopulator_controller.go
  controllers/extensions/addon_controller.go
  controllers/k8score/event_controller.go
  controllers/storage/storageprovider_controller.go
  controllers/workloads/replicatedstatemachine_controller.go
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  pkg/constant/flag.go
  pkg/controllerutil/predicate.go
Labels: area/user-interaction, feature, ci, size/L

#6705 feat: support to declare the host-network capabilities
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/component_controller.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/componentdefinition_controller_test.go
  controllers/apps/transformer_component_host_port.go
  controllers/apps/transformer_component_hostnetwork.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/apiutil/hostnetwork.go
  pkg/constant/const.go
  pkg/constant/flag.go
  pkg/controller/component/component_definition_convertor.go
  pkg/controller/component/component_definition_convertor_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
  pkg/controller/configuration/hostnetwork_utils.go
  pkg/controllerutil/controller_common.go
  pkg/testutil/apps/componentdefinition_factory.go
Labels: feature, size/XXL

#6629 chore: reconfigure reconcile decouples cd/cv (#6609)
  apis/apps/v1alpha1/configuration_types.go
  controllers/apps/configuration/config_reconcile_wrapper.go
  controllers/apps/configuration/reconfigure_controller.go
  controllers/apps/configuration/relatedresource.go
Labels: ci, approved, size/L

#6725 chore: retain the restore cr after the cluster recovery is completed.
  pkg/controller/plan/restore.go
Labels: size/S

#6729 chore: remove opsrequest reconfigure dependence on cd/dv
  controllers/apps/configuration/configuration_controller.go
  controllers/apps/operations/reconfigure.go
  pkg/controller/configuration/resource_wrapper.go
Labels: approved, size/S

#6724 feat: support ComponentDefinition custom annotations and Component inherit Cluster annotations
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/cluster_plan_builder.go
  controllers/apps/component_controller_test.go
  controllers/apps/component_utils.go
  controllers/apps/component_utils_test.go
  controllers/apps/transformer_cluster_api_normalization.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_component_status.go
  controllers/apps/transformer_component_vars.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/annotations.go
  pkg/controller/component/component.go
  pkg/controller/component/component_post_provision_test.go
  pkg/controller/component/service_descriptor_utils.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
Labels: feature, approved, size/L

#6740 fix: ob create failed sometimes.
  controllers/apps/transformer_component_configuration.go
Labels: enhancement, size/S

#6686 chore: refine config constraint specs
  apis/apps/v1alpha1/configconstraint_types.go
  config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
  deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: size/XL

#6723 feat: support encryption for backup data
  apis/dataprotection/v1alpha1/backup_types.go
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  apis/dataprotection/v1alpha1/types.go
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/utils.go
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  deploy/helm/values.yaml
  docs/developer_docs/api-reference/backup.md
  pkg/dataprotection/backup/deleter.go
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/restore/builder.go
  pkg/dataprotection/types/constant.go
  pkg/dataprotection/utils/backuprepo.go
Labels: area/user-interaction, feature, size/L

#6735 feat: refactor the opsDefinition to support task orchestration.
  apis/apps/v1alpha1/opsdefinition_types.go
  apis/apps/v1alpha1/opsrequest_conditions.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/custom.go
  controllers/apps/operations/custom/action.go
  controllers/apps/operations/custom/action_exec.go
  controllers/apps/operations/custom/action_workload.go
  controllers/apps/operations/custom/utils.go
  controllers/apps/operations/custom/workload_job.go
  controllers/apps/operations/custom/workload_pod.go
  controllers/apps/operations/custom_test.go
  controllers/apps/operations/custom_workflow.go
  controllers/apps/operations/ops_manager.go
  controllers/apps/operations/ops_progress_util.go
  controllers/apps/opsrequest_controller.go
  deploy/helm/crds/apps.kubeblocks.io_opsdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/opsdefinitions/switchover.yaml
  deploy/helm/templates/rbac/cluster_pod_required_role.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/common/utils.go
  pkg/constant/const.go
  pkg/controllerutil/pod_utils.go
  test/testdata/resources/mysql-opsdefinition-sql.yaml
Labels: area/user-interaction, feature, refactor, size/XXL

#6727 fix: get apepg role
  go.mod
  go.sum
  pkg/lorry/engines/postgres/apecloudpostgres/manager.go
  pkg/lorry/engines/postgres/apecloudpostgres/manager_test.go
  pkg/lorry/util/ping.go
Labels: enhancement, size/M

#6745 docs: fix cn docs format bugs
  i18n/zh-cn/developer-docs/integration/backup-and-restore.md
  i18n/zh-cn/developer-docs/integration/how-to-add-an-add-on.md
  i18n/zh-cn/developer-docs/integration/parameter-template.md
  i18n/zh-cn/user-docs/kubeblocks-for-redis/cluster-management/create-and-connect-to-a-redis-cluster.md
  i18n/zh-cn/user-docs/observability/configure-alert.md
  i18n/zh-cn/user-docs/observability/monitor-database.md
Labels: documentation, bug, enhancement, size/M

#6750 fix: backup failed if the k8s exists the same name crds
  controllers/apps/operations/custom/action_workload.go
  pkg/dataprotection/backup/request.go
Labels: enhancement, approved, size/XS

#6748 chore: refine mysql replication lag checking
  pkg/lorry/dcs/k8s.go
  pkg/lorry/engines/mysql/manager.go
  pkg/lorry/engines/mysql/manager_test.go
Labels: approved, size/XS

#6753 feat: support dynamic reload selected parameters policy (#6741) (#6742)
  apis/apps/v1alpha1/configconstraint_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/configuration/combine_upgrade_policy.go
  controllers/apps/configuration/combine_upgrade_policy_test.go
  controllers/apps/configuration/reconfigure_policy.go
  controllers/apps/configuration/sync_upgrade_policy.go
  deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/configuration/core/constraint.go
Labels: feature, size/L

#6751 fix: etcd role probe
  pkg/controller/component/component_definition_convertor.go
  pkg/controller/component/component_definition_convertor_test.go
  pkg/controller/component/lorry_utils.go
  pkg/controller/component/lorry_utils_test.go
  pkg/lorry/engines/mysql/get_replica_role.go
Labels: enhancement, approved, size/S

#6754 docs: adjust cn docs format
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/cluster-management/scale-for-a-mongodb-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/configuration/configure-cluster-parameters.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql/configuration/configuration.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql/proxy/introduction.md
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/configuration/configuration.md
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/migration/migration-postgresql.md
  i18n/zh-cn/user-docs/kubeblocks-for-pulsar/cluster-management/expand-volume.md
  i18n/zh-cn/user-docs/kubeblocks-for-pulsar/configuration/configuration.md
  i18n/zh-cn/user-docs/kubeblocks-for-redis/configuration/configure-cluster-parameters.md
Labels: documentation, size/M

#6760 docs: adjust en docs format
  docs/user_docs/kubeblocks-for-kafka/cluster-management/create-a-kafka-cluster.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/switchover.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/restart-a-postgresql-cluster.md
  docs/user_docs/kubeblocks-for-pulsar/cluster-management/create-pulsar-cluster-on-kubeblocks.md
  docs/user_docs/kubeblocks-for-vector-database/manage-vector-databases.md
Labels: documentation, size/S

#6752 docs: add terminology doc
  docs/developer_docs/api-reference/_category_.yml
  docs/developer_docs/external-component/_category_.yml
  docs/developer_docs/integration/_category_.yaml
  docs/developer_docs/terminology.md
Labels: documentation, size/M

#6768 fix: restore svc bug
  controllers/apps/operations/restore.go
  controllers/apps/operations/restore_test.go
Labels: bug, enhancement, approved, size/M

#6766 fix: failed to reconrigure operation (#674)
  controllers/apps/operations/reconfigure_util.go
  pkg/configuration/core/config_util.go
Labels: enhancement, approved, size/L

#6771 fix: do not restart pg when upgrading kb
  pkg/controller/component/rsm_convertor.go
Labels: enhancement, approved, size/XS

#6779 feat: support pitr
  controllers/apps/transformer_component_status.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backupschedule_controller.go
  controllers/dataprotection/restore_controller.go
  controllers/dataprotection/volumepopulator_controller.go
  pkg/controllerutil/pod_utils.go
  pkg/dataprotection/action/action_stateful.go
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/backup/scheduler.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/utils.go
  pkg/dataprotection/types/constant.go
Labels: feature, size/XL

#6781 chore: add more options for geesefs
  deploy/helm/templates/storageprovider/cos.yaml
  deploy/helm/templates/storageprovider/gcs-s3comp.yaml
  deploy/helm/templates/storageprovider/minio.yaml
  deploy/helm/templates/storageprovider/obs.yaml
  deploy/helm/templates/storageprovider/oss.yaml
  deploy/helm/templates/storageprovider/s3.yaml
Labels: size/M

#6787 fix: restore cluster failed if exists node port service
  controllers/apps/operations/restore.go
Labels: enhancement, size/S

#6764 chore: add reconcile workers for cluster and component controller.
  cmd/manager/main.go
  controllers/apps/cluster_controller.go
  controllers/apps/component_controller.go
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  pkg/constant/const.go
Labels: ci, size/S

#6690 fix: support automatic updating of resource-related parameters when v-scale and h-scale (#6273)
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusterversions.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  controllers/apps/component_controller.go
  controllers/apps/transformer_component_parameters.go
  controllers/apps/transformer_component_tls.go
  controllers/apps/transformer_component_tls_test.go
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterversions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/payload.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/configuration/config_utils.go
  pkg/controller/configuration/configuration_test.go
  pkg/controller/configuration/pipeline.go
  pkg/controllerutil/config_util.go
Labels: area/user-interaction, enhancement, approved, size/L

#6783 chore: Adjust the pod phase of prometheus scrape service metrics
  deploy/helm/values.yaml
Labels: approved, size/XS

#6793 fix: configmap not found error during the cluster deleting and refine code (#6792)
  apis/apps/v1alpha1/config_meta.go
  apis/apps/v1alpha1/configconstraint_types.go
  apis/apps/v1alpha1/configuration_types.go
  controllers/apps/clusterdefinition_controller_test.go
  controllers/apps/configuration/config_util.go
  controllers/apps/configuration/configconstraint_controller.go
  controllers/apps/configuration/configconstraint_controller_test.go
  controllers/apps/configuration/configuration_controller.go
  pkg/constant/const.go
  pkg/testutil/apps/common_util.go
Labels: enhancement, approved, size/L

#6795 fix: mogdb role probe
  controllers/apps/component_utils.go
  pkg/controller/component/lorry_utils.go
Labels: enhancement, size/XS

#6782 docs: add cn terminology docs
  i18n/zh-cn/developer-docs/terminology.md
Labels: documentation, size/M

#6799 fix: convert rsmSpec roles
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  apis/extensions/v1alpha1/zz_generated.deepcopy.go
  apis/storage/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  externalapis/preflight/v1beta2/zz_generated.deepcopy.go
  pkg/controller/component/component_definition_convertor.go
Labels: enhancement, size/M

#6800 docs: fix sidebar position
  i18n/zh-cn/developer-docs/api-reference/_category_.yml
  i18n/zh-cn/developer-docs/external-component/_category_.yml
  i18n/zh-cn/developer-docs/integration/_category_.yml
Labels: documentation, enhancement, size/XS

#6791 chore: get pod minReadySeconds from new api
  controllers/apps/configuration/policy_util_test.go
  controllers/apps/configuration/reconfigure_policy.go
  controllers/apps/configuration/rolling_upgrade_policy_test.go
Labels: approved, size/M

#6802 chore: remove unsed fields
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  pkg/lorry/engines/dbmanager_mock.go
Labels: size/M

#6804 chore: e2e support test on aks cn
  .github/workflows/e2e-fault.yml
  .github/workflows/e2e-kbcli-k3s.yml
  .github/workflows/e2e-kbcli.yml
  .github/workflows/e2e-performance.yml
  .github/workflows/e2e-smoke.yml
Labels: test, size/S

#6805 fix: reconcile workers is not effective
  cmd/manager/main.go
  deploy/helm/templates/deployment.yaml
Labels: enhancement, ci, approved, size/XS

#6807 chore: support to configurate the qps and burst for client config
  cmd/dataprotection/main.go
  cmd/manager/main.go
  controllers/apps/cluster_controller.go
  controllers/apps/opsrequest_controller.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/log_collection_controller.go
  controllers/dataprotection/types.go
  controllers/workloads/replicatedstatemachine_controller.go
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  pkg/constant/const.go
  pkg/controllerutil/util.go
  pkg/dataprotection/types/constant.go
  pkg/viperx/viperx.go
Labels: approved, size/L

#6814 chore: configuration controller support to configurate MaxConcurrentReconciles
  controllers/apps/configuration/configuration_controller.go
  controllers/apps/configuration/reconfigure_controller.go
Labels: ci, approved, size/S

#6817 chore: render the tool image for switchover opsDefinition
  cmd/dataprotection/main.go
  deploy/helm/opsdefinitions/switchover-preconditions
  deploy/helm/opsdefinitions/switchover.yaml
  deploy/helm/templates/opsdefinition.yaml
Labels: size/L

#6819 fix: make StorageProviders respect the custom endpoint setting
  deploy/helm/templates/storageprovider/cos.yaml
  deploy/helm/templates/storageprovider/obs.yaml
  deploy/helm/templates/storageprovider/oss.yaml
Labels: enhancement, size/S

#6821 chore: add e2e test type
  .github/workflows/e2e-kbcli-k3s.yml
  .github/workflows/e2e-kbcli.yml
  .github/workflows/release-image.yml
Labels: test, approved, size/XS

#6828 feat: supports to run opsRequest forcibly and queuing based on opsRequest type
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/opsrequest_webhook.go
  apis/apps/v1alpha1/type.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/custom.go
  controllers/apps/operations/expose.go
  controllers/apps/operations/horizontal_scaling.go
  controllers/apps/operations/horizontal_scaling_test.go
  controllers/apps/operations/ops_manager.go
  controllers/apps/operations/ops_progress_util.go
  controllers/apps/operations/ops_progress_util_test.go
  controllers/apps/operations/ops_util.go
  controllers/apps/operations/ops_util_test.go
  controllers/apps/operations/queue_util.go
  controllers/apps/operations/reconfigure.go
  controllers/apps/operations/restart.go
  controllers/apps/operations/start.go
  controllers/apps/operations/start_test.go
  controllers/apps/operations/stop.go
  controllers/apps/operations/switchover.go
  controllers/apps/operations/type.go
  controllers/apps/operations/upgrade.go
  controllers/apps/operations/vertical_scaling.go
  controllers/apps/operations/vertical_scaling_test.go
  controllers/apps/opsrequest_controller.go
  controllers/apps/opsrequest_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/opsdefinitions/switchover-preconditions
  deploy/helm/opsdefinitions/switchover.yaml
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/opsdefinition.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/plan/restore.go
  pkg/controllerutil/errors.go
Labels: feature, ci, approved, size/XXL

#6831 fix: expose role from rsmSpec
  controllers/apps/operations/expose.go
Labels: enhancement, approved, size/XS

#6835 docs: update slack link
  README.md
Labels: documentation, size/XS

#6836 fix: role probe custom handler for script without bash
  controllers/apps/component_utils.go
  controllers/apps/transformer_component_workload.go
  pkg/lorry/engines/custom/get_replica_role.go
Labels: enhancement, approved, size/M

#6839 fix: etcd role probe failed when upgrade
  pkg/lorry/engines/custom/get_replica_role.go
  pkg/lorry/engines/custom/manager.go
Labels: enhancement, size/XS

#6845 fix: adapt shell cmd for custom handler
  pkg/lorry/engines/custom/get_replica_role.go
Labels: enhancement, size/XS

#6846 fix: mogdb role probe
  pkg/lorry/engines/custom/get_replica_role.go
Labels: enhancement, approved, size/S

#6784 chore: fix typo
  i18n/zh-cn/developer-docs/integration/monitoring.md
Labels: enhancement, size/XS

#6850 fix: return none error if no commands
  pkg/lorry/client/httpclient_test.go
  pkg/lorry/engines/custom/manager.go
  pkg/lorry/util/command.go
Labels: enhancement, approved, size/L

#6853 chore: adapt lorry timeout for long run actions
  pkg/lorry/client/httpclient.go
  pkg/lorry/client/httpclient_test.go
Labels: bug, enhancement, size/M

#6854 chore: add envs for member leave action
  pkg/lorry/engines/custom/manager.go
Labels: size/XS

#6862 chore: support ipv6 (#6857)
  cmd/reloader/app/cmd.go
  cmd/reloader/main.go
  controllers/apps/configuration/policy_util.go
Labels: approved, size/M

#6864 fix: nil pointer when no roles set
  pkg/controller/rsm/transformer_member_reconfiguration.go
  pkg/controller/rsm/transformer_object_generation.go
  pkg/controller/rsm/utils.go
Labels: enhancement, size/XS

#6866 docs: update docs directory content
  docs/00 - index.md
  docs/CONTRIBUTING.md
  docs/CONTRIBUTING_DOCS.md
Labels: documentation, size/M

#6876 fix: service.spec.ipFamilies field incorrectly overwritten
  controllers/apps/transformer_cluster_service.go
Labels: enhancement, ci, size/XS

#6877 fix: dual stack service reconcile error
  controllers/apps/transformer_cluster_service.go
Labels: enhancement, ci, size/XS

#6852 chore: ci check generate
  .github/workflows/cicd-push.yml
Labels: ci, approved, size/S

#6872 feat: support to rebuild instance
  apis/apps/v1alpha1/opsrequest_conditions.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/component_utils_test.go
  controllers/apps/operations/custom.go
  controllers/apps/operations/custom_workflow.go
  controllers/apps/operations/horizontal_scaling.go
  controllers/apps/operations/ops_progress_util.go
  controllers/apps/operations/rebuild_instance.go
  controllers/apps/operations/rebuild_instance_test.go
  controllers/apps/operations/restart.go
  controllers/apps/operations/upgrade.go
  controllers/apps/opsrequest_controller.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_pod.go
  pkg/controller/plan/restore.go
  pkg/controllerutil/util.go
  pkg/dataprotection/utils/utils.go
  pkg/testutil/apps/cluster_consensus_test_util.go
  pkg/testutil/apps/cluster_util.go
Labels: area/user-interaction, feature, size/XXL

#6874 feat: BackupRepo supports specifying prefix of storage path
  apis/dataprotection/v1alpha1/backuprepo_types.go
  config/crd/bases/dataprotection.kubeblocks.io_backuprepos.yaml
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/backuprepo_controller.go
  deploy/helm/crds/dataprotection.kubeblocks.io_backuprepos.yaml
  docs/developer_docs/api-reference/backup.md
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/backup/utils.go
Labels: area/user-interaction, feature, enhancement, ci, approved, size/M

#6880 feat: add "insecure" option for S3 storage providers
  deploy/helm/templates/storageprovider/cos.yaml
  deploy/helm/templates/storageprovider/gcs-s3comp.yaml
  deploy/helm/templates/storageprovider/minio.yaml
  deploy/helm/templates/storageprovider/obs.yaml
  deploy/helm/templates/storageprovider/oss.yaml
  deploy/helm/templates/storageprovider/s3.yaml
Labels: area/user-interaction, feature, size/M

#6884 chore: fix GitHub Security Lab Vulnerability Report
  .github/workflows/cicd-pull-request.yml
  .github/workflows/pull-request-check.yml
Labels: enhancement, approved, size/S

#6883 fix: volume expand failed
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/rsm2/replica_util.go
  pkg/controller/rsm2/replica_util_test.go
Labels: enhancement, size/S

#6887 fix: starrocks lorry container inject
  pkg/controller/component/lorry_utils.go
Labels: enhancement, approved, size/XS

#6881 fix：Update guidance documentation to include the --show-password para…
  docs/img/connect_database_with_CLI_or_SDK_client.png
  docs/user_docs/connect_database/connect-database-in-testing-environment.md
  docs/user_docs/try-out-on-playground/try-kubeblocks-on-cloud.md
  docs/user_docs/try-out-on-playground/try-kubeblocks-on-your-laptop.md
  i18n/zh-cn/img/connect-to-database-in-testing-env.png
  i18n/zh-cn/user-docs/create-and-connect-databases/connect-to-database-in-testing-environment.md
  i18n/zh-cn/user-docs/try-out-on-playground/try-kubeblocks-on-cloud.md
  i18n/zh-cn/user-docs/try-out-on-playground/try-kubeblocks-on-local-host.md
Labels: documentation, enhancement, size/S

#6865 feat: support instance templates compression
  controllers/apps/component_controller_test.go
  controllers/apps/transformer_component_status.go
  go.mod
  pkg/controller/builder/builder_replicated_state_machine.go
  pkg/controller/builder/builder_replicated_state_machine_test.go
  pkg/controller/factory/builder.go
  pkg/controller/kubebuilderx/controller.go
  pkg/controller/kubebuilderx/controller_test.go
  pkg/controller/kubebuilderx/object_tree_to_dag_transformer.go
  pkg/controller/kubebuilderx/object_tree_to_dag_transformer_test.go
  pkg/controller/kubebuilderx/plan_builder.go
  pkg/controller/kubebuilderx/plan_builder_test.go
  pkg/controller/kubebuilderx/reconciler.go
  pkg/controller/rsm/transformer_object_generation.go
  pkg/controller/rsm2/reconciler_assistant_object.go
  pkg/controller/rsm2/reconciler_replicas_alignment.go
  pkg/controller/rsm2/reconciler_revision_update.go
  pkg/controller/rsm2/reconciler_revision_update_test.go
  pkg/controller/rsm2/reconciler_status.go
  pkg/controller/rsm2/reconciler_status_test.go
  pkg/controller/rsm2/reconciler_update.go
  pkg/controller/rsm2/reconciler_update_test.go
  pkg/controller/rsm2/replica_util.go
  pkg/controller/rsm2/replica_util_test.go
  pkg/controller/rsm2/revision_util.go
  pkg/controller/rsm2/revision_util_test.go
  pkg/controller/rsm2/suite_test.go
  pkg/controller/rsm2/tree_loader.go
  pkg/controller/rsm2/tree_loader_test.go
  pkg/controller/rsm2/types.go
  pkg/testutil/apps/cluster_consensus_test_util.go
  pkg/testutil/apps/cluster_replication_test_util.go
Labels: feature, size/XL

#6890 fix: cluster is always in 'DeleteCR' after deleted
  controllers/workloads/replicatedstatemachine_controller.go
Labels: enhancement, size/XS

#6892 fix: cluster is always in 'Deleting' after volume expansion
  controllers/apps/transformer_component_ownership.go
  controllers/workloads/replicatedstatemachine_controller.go
  pkg/controller/rsm2/reconciler_deletion.go
  pkg/controller/rsm2/replica_util.go
Labels: enhancement, size/M

#6894 chore: support to queue for volume expansion ops
  apis/apps/v1alpha1/opsrequest_webhook.go
  apis/apps/v1alpha1/opsrequest_webhook_test.go
  controllers/apps/operations/volume_expansion.go
Labels: approved, size/S

#6895 fix: remove dependency of Reconfigure on StatefulSet
  controllers/apps/configuration/combine_upgrade_policy_test.go
  controllers/apps/configuration/config_reconcile_wrapper.go
  controllers/apps/configuration/parallel_upgrade_policy_test.go
  controllers/apps/configuration/policy_util.go
  controllers/apps/configuration/policy_util_test.go
  controllers/apps/configuration/reconfigure_controller.go
  controllers/apps/configuration/reconfigure_policy.go
  controllers/apps/configuration/rolling_upgrade_policy_test.go
  controllers/apps/configuration/simple_policy_test.go
  controllers/apps/configuration/sync_upgrade_policy_test.go
  controllers/workloads/replicatedstatemachine_controller.go
  pkg/controllerutil/rsm_utils.go
Labels: enhancement, dependencies, size/L

#6870 feat(apps): shell trigger support batch reload
  apis/apps/v1alpha1/configconstraint_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
  deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
  pkg/configuration/config_manager/config_handler.go
  pkg/configuration/config_manager/config_handler_test.go
Labels: feature, approved, size/L

#6900 chore: add availablity check for rebuildInstance ops
  controllers/apps/operations/rebuild_instance.go
  controllers/apps/operations/rebuild_instance_test.go
Labels: approved, size/M

#6809 chore: configure the kubeconfig to access multiple clusters
  cmd/manager/main.go
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  pkg/controller/multicluster/setup.go
Labels: approved, size/L

#6842 chore: guarantee the order of operations between components
  apis/apps/v1alpha1/clusterdefinition_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  controllers/apps/clusterdefinition_controller.go
  controllers/apps/clusterdefinition_controller_test.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_cluster_component_test.go
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/model/graph_client.go
Labels: approved, size/XXL

#6820 chore: refine data dump/load actions
  apis/apps/v1alpha1/componentdefinition_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/componentdefinition_controller.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/lorry.go
  pkg/controller/component/component_definition_convertor.go
  pkg/controller/component/lorry_utils.go
  pkg/lorry/client/client.go
  pkg/lorry/client/client_mock.go
  pkg/lorry/client/interface.go
  pkg/lorry/operations/replica/data_dump.go
  pkg/lorry/operations/replica/data_load.go
  pkg/lorry/util/types.go
  pkg/testutil/apps/constant.go
Labels: approved, size/L

#6908 feat: improve to rebuild the instance on specified node
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/rebuild_instance.go
  controllers/apps/operations/rebuild_instance_test.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docker/Dockerfile-tools
  docs/developer_docs/api-reference/cluster.md
Labels: feature, ci, size/L

#6916 feat: support expose dualstack service
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/expose.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: feature, size/L

#6915 feat: support expose dualstack service
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/expose.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: area/user-interaction, feature, approved, size/L

#6896 feat: support mysql rebuild
  pkg/constant/lorry.go
  pkg/lorry/client/client.go
  pkg/lorry/client/client_mock.go
  pkg/lorry/client/httpclient_test.go
  pkg/lorry/client/interface.go
  pkg/lorry/client/suite_test.go
  pkg/lorry/dcs/k8s.go
  pkg/lorry/dcs/types.go
  pkg/lorry/engines/mysql/config.go
  pkg/lorry/engines/mysql/get_replica_role.go
  pkg/lorry/engines/mysql/get_replica_role_test.go
  pkg/lorry/engines/mysql/manager_test.go
  pkg/lorry/highavailability/util.go
  pkg/lorry/httpserver/server.go
  pkg/lorry/operations/replica/rebuild.go
  pkg/lorry/util/ping.go
Labels: feature, size/L

#6918 feat: support to reference objects from multiple components
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  apis/extensions/v1alpha1/zz_generated.deepcopy.go
  apis/storage/v1alpha1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  controllers/apps/component_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  externalapis/preflight/v1beta2/zz_generated.deepcopy.go
  pkg/controller/component/type.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
  pkg/generics/slices.go
Labels: feature, size/XXL

#6923 chore: fix issue move error
  .github/workflows/issues-move.yml
Labels: enhancement, approved, size/XS

#6924 fix: update openapi version to 3.0.0
  go.mod
  go.sum
  pkg/configuration/openapi/cue_gen_openapi.go
  test/testdata/cue_testdata/mysql_openapi.cue
  test/testdata/cue_testdata/mysql_openapi.json
Labels: enhancement, size/L

#6926 bugfix: use openapi v3.0.0 to fix excluseiveMiminum case
  go.mod
  go.sum
  pkg/configuration/openapi/cue_gen_openapi.go
  test/testdata/cue_testdata/mysql_openapi.cue
  test/testdata/cue_testdata/mysql_openapi.json
Labels: bug, enhancement, size/L
