Repository apecloud/kubeblocks, pull requests merged in 2024-09, with the labels that each got.

#8045 chore: P10K optimizations
  go.mod
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/instanceset/revision_util.go
  pkg/lru/cache.go
Labels: approved, size/L

#8066 fix: updateStrategy bug
  pkg/controller/component/rsm_convertor.go
  pkg/controller/instanceset/utils.go
Labels: size/S, pre-approve

#8072 chore: turn off mongodb ha in lorry
  pkg/lorry/highavailability/util.go
Labels: approved, size/XS

#8070 chore: P10K optimizations (#8045)
  go.mod
  go.sum
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/instanceset/revision_util.go
  pkg/lru/cache.go
Labels: approved, size/L

#8031 fix: support leave member by using any pods
  controllers/apps/component_controller_test.go
  controllers/apps/transformer_component_workload.go
  pkg/lorry/client/client.go
  pkg/lorry/client/client_mock.go
  pkg/lorry/client/httpclient_test.go
  pkg/lorry/client/interface.go
  pkg/lorry/operations/replica/leave.go
Labels: approved, size/M

#8067 fix: mongo dump backup failed with incorrect version
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  controllers/apps/transformer_cluster_backup_policy.go
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/M

#8074 chore: add base ref for create pr
  .github/workflows/release-version.yml
Labels: approved, size/XS

#8024 chore: decouple the shared container from the custom image in the exec Action
  pkg/controller/component/kbagent.go
  pkg/controller/component/kbagent_test.go
Labels: approved, size/M

#8038 chore: remove some KB CRDs from the resource category all
  apis/apps/v1alpha1/component_types.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/servicedescriptor_types.go
  apis/dataprotection/v1alpha1/restore_types.go
  apis/experimental/v1alpha1/nodecountscaler_types.go
  apis/workloads/legacy/replicatedstatemachine_types.go
  apis/workloads/v1alpha1/instanceset_types.go
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  config/crd/bases/apps.kubeblocks.io_servicedescriptors.yaml
  config/crd/bases/dataprotection.kubeblocks.io_restores.yaml
  config/crd/bases/experimental.kubeblocks.io_nodecountscalers.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/apps.kubeblocks.io_servicedescriptors.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_restores.yaml
  deploy/helm/crds/experimental.kubeblocks.io_nodecountscalers.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
Labels: approved, size/S

#8023 chore: remove built-in vars in custom labels and annotations
  pkg/controller/component/synthesize_component.go
  pkg/controller/configuration/builtin_env.go
Labels: approved, size/M

#8087 chore: pick support generate primary and public key for sshd to release-0.9
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
  pkg/gotemplate/sshkeygenerator.go
  pkg/gotemplate/sshkeygenerator_test.go
  pkg/gotemplate/tpl_engine.go
  pkg/gotemplate/tpl_engine_test.go
Labels: approved, size/L

#8088 chore: update headless svc labels for the prometheus scrape job
  pkg/constant/labels.go
  pkg/controller/instanceset/object_builder.go
Labels: approved, size/XS

#8086 docs: improve overview
  docs/user_docs/overview/about-this-manual.md
  docs/user_docs/overview/concept.md
  docs/user_docs/overview/introduction.md
  docs/user_docs/overview/kubeblocks_api_layers.png
  docs/user_docs/overview/kubeblocks_general_purpose_arch.png
  docs/user_docs/overview/supported-addons.md
Labels: approved, size/L

#8093 docs: fix overview format
  docs/user_docs/overview/concept.md
  docs/user_docs/overview/introduction.md
Labels: approved, size/S

#8043 feat: support redis(standalone replica) pitr
  apis/dataprotection/v1alpha1/actionset_types.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/dataprotection.kubeblocks.io_actionsets.yaml
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/restore_controller.go
  controllers/dataprotection/utils.go
  deploy/helm/crds/dataprotection.kubeblocks.io_actionsets.yaml
  docs/developer_docs/api-reference/backup.md
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/backup/utils.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/utils.go
Labels: area/user-interaction, size/L, pre-approve

#8095 docs: adjust format
  docs/user_docs/overview/introduction.md
Labels: approved, size/XS

#8097 docs: update overview in release-0.9
  docs/user_docs/overview/about-this-manual.md
  docs/user_docs/overview/concept.md
  docs/user_docs/overview/introduction.md
  docs/user_docs/overview/kubeblocks_api_layers.png
  docs/user_docs/overview/kubeblocks_general_purpose_arch.png
  docs/user_docs/overview/supported-addons.md
Labels: approved, size/L

#8100 fix: missing some annotation when restoring from ops
  controllers/dataprotection/backup_controller.go
Labels: approved, size/S

#8071 chore: add exit error code prompt information
  pkg/kbagent/service/command.go
Labels: approved, size/XS

#8099 fix: exclude dataprotection pods from kb service
  Makefile
  cmd/helmhook/hook/prepare.go
  cmd/helmhook/hook/stop.go
  cmd/helmhook/hook/utils.go
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/templates/service.yaml
Labels: approved, size/M

#8101 fix: missing some annotation when restoring from ops
  controllers/dataprotection/backup_controller.go
Labels: approved, size/S

#8102 chore: exclude dataproctection pods from kb services
  Makefile
  cmd/helmhook/hook/prepare.go
  cmd/helmhook/hook/stop.go
  cmd/helmhook/hook/utils.go
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/templates/service.yaml
Labels: approved, size/M

#8107 docs: add k8s 101
  docs/img/kubeblocks-architecture.png
  docs/user_docs/overview/about-this-manual.md
  docs/user_docs/overview/concept.md
  docs/user_docs/overview/introduction.md
  docs/user_docs/overview/kubernetes_and_operator_101.md
  docs/user_docs/overview/supported-addons.md
Labels: approved, size/L

#8110 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: approved, size/M

#8108 docs: merge docs/api_docs/connect_database into docs/user_docs/connec…
  docs/api_docs/connect_database/_category_.yml
  docs/api_docs/connect_database/connect-database-in-production-environment.md
  docs/api_docs/connect_database/connect-database-in-testing-environment.md
  docs/api_docs/connect_database/overview-of-database-connection.md
  docs/user_docs/connect_database/_category_.yml
  docs/user_docs/connect_database/connect-database-in-production-environment.md
  docs/user_docs/connect_database/connect-database-in-testing-environment.md
  docs/user_docs/connect_database/overview-of-database-connection.md
Labels: approved, size/XL

#8089 feat: support ha records
  deploy/helm/templates/opsdefinition.yaml
  pkg/lorry/client/httpclient_test.go
  pkg/lorry/dcs/dcs.go
  pkg/lorry/dcs/dcs_mock.go
  pkg/lorry/dcs/k8s.go
  pkg/lorry/httpserver/apis.go
  pkg/lorry/httpserver/endpoint.go
  pkg/lorry/httpserver/server.go
  pkg/lorry/operations/replica/switchover.go
  pkg/lorry/operations/types.go
Labels: approved, size/M

#8064 feat: support InstanceSet PVC ownerReference
  apis/apps/v1alpha1/cluster_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  controllers/apps/cluster_controller_test.go
  controllers/apps/transformer_cluster_deletion.go
  controllers/apps/transformer_component_deletion.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/reconciler_deletion.go
Labels: approved, size/M

#8113 feat: support InstanceSet PVC ownerReference
  apis/apps/v1alpha1/cluster_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  controllers/apps/cluster_controller_test.go
  controllers/apps/transformer_cluster_deletion.go
  controllers/apps/transformer_component_deletion.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/reconciler_deletion.go
Labels: approved, size/M

#8117 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: approved, size/XS

#8120 chore: e2e test on vke
  .github/workflows/e2e-kbcli.yml
Labels: approved, size/XS

#8134 fix: failed to call webhook
  deploy/helm/templates/admission/webhookconfiguration.yaml
Labels: approved, size/XS

#8106 fix: endless affinity list when there's a DataPlaneAffinity
  pkg/controller/scheduling/scheduling_utils.go
  pkg/controller/scheduling/scheduling_utils_test.go
  pkg/testutil/apps/cluster_factory.go
Labels: approved, size/M

#8140 chore: change cicd test self-runner to ubuntu-latest
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/release-version.yml
  Makefile
  deploy/helm/Chart.yaml
Labels: approved, size/L

#8115 chore: support inject envFrom by secret
  apis/apps/v1alpha1/config_meta.go
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  controllers/apps/configuration/configuration_controller_test.go
  controllers/apps/configuration/configuration_test.go
  controllers/apps/configuration/reconcile_task.go
  controllers/apps/configuration/suite_test.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/labels.go
  pkg/controller/configuration/config_utils.go
  pkg/controller/configuration/envfrom_utils.go
  pkg/controller/configuration/envfrom_utils_test.go
  pkg/controller/configuration/pipeline.go
  pkg/controller/configuration/template_wrapper.go
  pkg/controllerutil/volume_util.go
  pkg/controllerutil/volume_util_test.go
  pkg/gotemplate/tpl_engine_test.go
  pkg/testutil/k8s/k8sclient_util.go
Labels: approved, size/L

#8132 chore: adjust environment variable append order
  pkg/kbagent/service/command.go
Labels: approved, size/S

#8141 chore: apply user defined labels and annotations to account&tls secret, pvcs, services owned by comp
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/transformer_cluster_service.go
  controllers/apps/transformer_component_account.go
  controllers/apps/transformer_component_service.go
  controllers/apps/transformer_component_tls.go
  controllers/apps/transformer_component_tls_test.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/factory/builder.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/plan/tls_utils.go
  pkg/controller/plan/tls_utils_test.go
Labels: approved, size/L

#8153 chore: apply user defined labels and annotations to account&tls secret, pvcs, services owned by comp (#8141)
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/transformer_cluster_service.go
  controllers/apps/transformer_component_account.go
  controllers/apps/transformer_component_service.go
  controllers/apps/transformer_component_tls.go
  controllers/apps/transformer_component_tls_test.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/factory/builder.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/plan/tls_utils.go
  pkg/controller/plan/tls_utils_test.go
Labels: approved, size/L

#8146 chore: generate and convert to shared account secret for sharding password defined with seed
  controllers/apps/cluster_controller.go
  controllers/apps/transformer_cluster_shared_account.go
  pkg/constant/labels.go
  pkg/constant/pattern.go
Labels: approved, size/L

#8155 chore: chore: generate and convert to shared account secret for sharding password defined with seed
  controllers/apps/cluster_controller.go
  controllers/apps/transformer_cluster_shared_account.go
  pkg/constant/labels.go
  pkg/constant/pattern.go
Labels: approved, size/L

#7889 feat: service-ref supports to refer pods FQDN
  apis/apps/v1/componentdefinition_types.go
  apis/apps/v1/deprecated.go
  apis/apps/v1/servicedescriptor_types.go
  apis/apps/v1/types.go
  apis/apps/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_servicedescriptors.yaml
  controllers/apps/servicedescriptor_controller.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_servicedescriptors.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_service_descriptor.go
  pkg/controller/builder/builder_service_descriptor_test.go
  pkg/controller/component/service_descriptor_utils.go
  pkg/controller/component/service_descriptor_utils_test.go
  pkg/controller/component/service_reference.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
  pkg/testutil/apps/servicedescriptor_factory.go
Labels: approved, size/XL

#8151 feat: specify node for rebuild instance ops
  apis/apps/v1alpha1/opsrequest_types.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/rebuild_instance.go
  controllers/apps/operations/rebuild_instance_inplace.go
  controllers/apps/operations/rebuild_instance_test.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/annotations.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/reconciler_instance_alignment_test.go
  pkg/controller/instanceset/reconciler_status.go
  pkg/controller/instanceset/reconciler_status_test.go
Labels: approved, size/L

#8160 fix: error "no kind is registered for the type v1.Cluster in scheme"
  cmd/dataprotection/main.go
Labels: approved, size/XS

#8161 feat: specify node for rebuild instance ops
  apis/apps/v1alpha1/opsrequest_types.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/rebuild_instance.go
  controllers/apps/operations/rebuild_instance_inplace.go
  controllers/apps/operations/rebuild_instance_test.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/annotations.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/reconciler_instance_alignment_test.go
  pkg/controller/instanceset/reconciler_status.go
  pkg/controller/instanceset/reconciler_status_test.go
Labels: approved, size/L

#8129 feat: redis-restore-by-keys
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/restore.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/const.go
  pkg/controller/plan/restore.go
  pkg/dataprotection/restore/utils.go
Labels: size/XL, pre-approve

#8149 docs: add rabbitmq docs and update other related docs
  docs/img/kubeblocks-architecture-ha.png
  docs/user_docs/create_database/overview-of-create-database.md
  docs/user_docs/installation/install-with-kbcli/install-addons.md
  docs/user_docs/installation/install-with-kbcli/uninstall-kbcli-and-kubeblocks.md
  docs/user_docs/kubeblocks-for-apecloud-mysql/cluster-management/create-and-connect-an-apecloud-mysql-cluster.md
  docs/user_docs/kubeblocks-for-apecloud-mysql/proxy/apecloud-mysql-proxy.md
  docs/user_docs/kubeblocks-for-elasticsearch/manage-elasticsearch.md
  docs/user_docs/kubeblocks-for-kafka/cluster-management/create-a-kafka-cluster.md
  docs/user_docs/kubeblocks-for-milvus/manage-milvus.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
  docs/user_docs/kubeblocks-for-mysql-community-edition/cluster-management/create-and-connect-a-mysql-cluster.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/create-and-connect-a-postgresql-cluster.md
  docs/user_docs/kubeblocks-for-qdrant/manage-qdrant.md
  docs/user_docs/kubeblocks-for-rabbitmq/_category_.yml
  docs/user_docs/kubeblocks-for-rabbitmq/manage-rabbitmq.md
  docs/user_docs/kubeblocks-for-redis/cluster-management/create-and-connect-a-redis-cluster.md
  docs/user_docs/kubeblocks-for-starrocks/manage-starrocks.md
  docs/user_docs/kubeblocks-for-weaviate/manage-weaviate.md
  docs/user_docs/kubeblocks-for-xinference/manage-xinference.md
  docs/user_docs/observability/monitor-database.md
  docs/user_docs/overview/introduction.md
  docs/user_docs/overview/supported-addons.md
  docs/user_docs/upgrade/upgrade with helm/upgrade-kubeblocks-to-0.9.md
Labels: approved, size/XL

#8164 docs: add rabbitmq docs and update other related docs
  docs/img/kubeblocks-architecture-ha.png
  docs/user_docs/create_database/overview-of-create-database.md
  docs/user_docs/installation/install-with-kbcli/install-addons.md
  docs/user_docs/installation/install-with-kbcli/uninstall-kbcli-and-kubeblocks.md
  docs/user_docs/kubeblocks-for-apecloud-mysql/cluster-management/create-and-connect-an-apecloud-mysql-cluster.md
  docs/user_docs/kubeblocks-for-apecloud-mysql/proxy/apecloud-mysql-proxy.md
  docs/user_docs/kubeblocks-for-elasticsearch/manage-elasticsearch.md
  docs/user_docs/kubeblocks-for-kafka/cluster-management/create-a-kafka-cluster.md
  docs/user_docs/kubeblocks-for-milvus/manage-milvus.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
  docs/user_docs/kubeblocks-for-mysql-community-edition/cluster-management/create-and-connect-a-mysql-cluster.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/create-and-connect-a-postgresql-cluster.md
  docs/user_docs/kubeblocks-for-qdrant/manage-qdrant.md
  docs/user_docs/kubeblocks-for-rabbitmq/_category_.yml
  docs/user_docs/kubeblocks-for-rabbitmq/manage-rabbitmq.md
  docs/user_docs/kubeblocks-for-redis/cluster-management/create-and-connect-a-redis-cluster.md
  docs/user_docs/kubeblocks-for-starrocks/manage-starrocks.md
  docs/user_docs/kubeblocks-for-weaviate/manage-weaviate.md
  docs/user_docs/kubeblocks-for-xinference/manage-xinference.md
  docs/user_docs/observability/monitor-database.md
  docs/user_docs/overview/introduction.md
  docs/user_docs/overview/supported-addons.md
  docs/user_docs/upgrade/upgrade with helm/upgrade-kubeblocks-to-0.9.md
Labels: approved, size/XL

#8167 feat: redis restore by keys
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/restore.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/backup.go
  pkg/controller/plan/restore.go
  pkg/dataprotection/restore/utils.go
Labels: area/user-interaction, size/XL, pre-approve

#8142 chore: remove deprecated fields in cluster and component v1 API
  apis/apps/v1/cluster_types.go
  apis/apps/v1/component_types.go
  apis/apps/v1/deprecated.go
  apis/apps/v1/zz_generated.deepcopy.go
  apis/apps/v1alpha1/cluster_conversion.go
  apis/apps/v1alpha1/component_conversion.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/component_controller.go
  controllers/apps/operations/ops_comp_helper.go
  controllers/apps/operations/upgrade.go
  controllers/apps/transformer_cluster_api_normalization.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_cluster_deletion_test.go
  controllers/apps/transformer_cluster_halt_recovering.go
  controllers/apps/transformer_cluster_load_resources.go
  controllers/apps/transformer_cluster_load_resources_test.go
  controllers/apps/transformer_cluster_meta.go
  controllers/apps/transformer_cluster_service.go
  controllers/apps/transformer_component_custom_volumes.go
  controllers/apps/transformer_component_rbac.go
  controllers/apps/transformer_component_validation.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_component.go
  pkg/controller/component/component.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/configuration/resource_wrapper.go
  pkg/controller/factory/builder.go
  pkg/controller/plan/restore.go
  pkg/kbagent/service/command_test.go
  pkg/testutil/apps/cluster_factory.go
  pkg/testutil/apps/cluster_instance_set_test_util.go
Labels: approved, size/XXL

#8154 chore: remove the support for generated components
  controllers/apps/component_controller_test.go
  controllers/apps/configuration/config_reconcile_wrapper.go
  controllers/apps/configuration/configuration_controller.go
  controllers/apps/configuration/configuration_test.go
  controllers/apps/configuration/reconcile_task.go
  controllers/apps/configuration/reconfigure_controller.go
  controllers/apps/operations/rebuild_instance.go
  controllers/apps/operations/switchover.go
  controllers/apps/transformer_cluster_component_status.go
  controllers/apps/transformer_component_account_provision.go
  controllers/apps/transformer_component_load_resources.go
  controllers/apps/transformer_component_pre_terminate.go
  controllers/apps/transformer_component_rbac_test.go
  controllers/apps/transformer_component_vars.go
  pkg/constant/const.go
  pkg/controller/component/component.go
  pkg/controller/component/component_test.go
  pkg/controller/component/service_descriptor_utils.go
  pkg/controller/component/service_reference.go
  pkg/controller/component/service_reference_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/synthesize_component_test.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
  pkg/controller/configuration/configuration_test.go
  pkg/controller/configuration/envfrom_utils_test.go
  pkg/controller/configuration/resource_wrapper.go
  pkg/controller/factory/builder_test.go
  pkg/controller/factory/suite_test.go
  pkg/controller/plan/prepare_test.go
  pkg/controllerutil/cluster_utils.go
  pkg/controllerutil/cluster_utils_test.go
Labels: approved, size/XXL

#8173 chore: remove CV update validation
  apis/apps/v1alpha1/clusterversion_webhook.go
  apis/apps/v1alpha1/clusterversion_webhook_test.go
  deploy/helm/templates/rbac/clusterrole_binding.yaml
Labels: approved, size/S

#8175 chore: skip validate restore in webhook
  apis/apps/v1alpha1/opsrequest_webhook.go
Labels: approved, size/XS

#8171 chore: cleanup the legacy implicit envs
  controllers/apps/component_controller_test.go
  controllers/apps/operations/custom/utils.go
  pkg/constant/annotations.go
  pkg/constant/const.go
  pkg/constant/env.go
  pkg/controller/component/kbagent_test.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
  pkg/controller/configuration/builtin_env.go
  pkg/controller/configuration/tool_image_builder.go
  pkg/controller/factory/builder_test.go
  pkg/controller/instanceset/object_builder.go
  pkg/controller/instanceset/object_builder_test.go
  pkg/kbagent/setup.go
  pkg/kbagent/util/env.go
  pkg/kbagent/util/event.go
Labels: approved, size/XL

#8179 chore: remove CV create validation
  apis/apps/v1alpha1/clusterversion_webhook.go
Labels: approved, size/M

#8166 feat: opsDef support cmpd name prefix and regex matching
  apis/operations/v1alpha1/opsdefinition_types.go
  apis/operations/v1alpha1/opsrequest_types.go
  config/crd/bases/operations.kubeblocks.io_opsdefinitions.yaml
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsdefinitions.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
  pkg/operations/custom.go
Labels: area/user-interaction, approved, size/M

#8076 feat: support to restart components with topology orders
  pkg/operations/restart.go
  pkg/operations/restart_test.go
  pkg/operations/suite_test.go
Labels: area/user-interaction, approved, size/L

#8098 chore: pick update headless svc labels for the prometheus scrape job to release-0.9 (#8088)
  pkg/constant/labels.go
  pkg/controller/instanceset/object_builder.go
Labels: approved, size/XS

#8174 feat: opsDef and bpt support cmpd name prefix and regex matching
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  apis/apps/v1alpha1/opsdefinition_types.go
  apis/apps/v1alpha1/opsrequest_types.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/apps.kubeblocks.io_opsdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/backuppolicytemplate_controller.go
  controllers/apps/backuppolicytemplate_controller_test.go
  controllers/apps/operations/custom.go
  controllers/apps/transformer_cluster_backup_policy.go
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/L

#8181 chore: add crd patch role
  deploy/helm/templates/rbac/clusterrole.yaml
  deploy/helm/templates/rbac/clusterrole_binding.yaml
Labels: approved, size/XS

#8182 chore: remove some useless builders
  go.mod
  go.sum
  pkg/controller/builder/builder_daemon_set.go
  pkg/controller/builder/builder_daemon_set_test.go
  pkg/controller/builder/builder_deployment.go
  pkg/controller/builder/builder_deployment_test.go
  pkg/controller/builder/builder_monitor_service.go
  pkg/controller/builder/builder_monitor_service_test.go
  pkg/controller/builder/builder_stateful_set.go
  pkg/controller/builder/builder_stateful_set_test.go
  pkg/controller/builder/builder_volume_snapshot_class.go
  pkg/controller/builder/builder_volume_snapshot_class_test.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
  pkg/controller/handler/handler_builder_test.go
  pkg/controller/kubebuilderx/plan_builder_test.go
  pkg/controller/kubebuilderx/utils_test.go
  pkg/controller/model/graph_client_test.go
  pkg/controller/model/suite_test.go
  pkg/controller/model/transform_types_test.go
  pkg/controller/model/transform_utils_test.go
Labels: approved, size/XL

#8168 chore: cancel standard pipe for kbagent
  pkg/kbagent/service/action.go
  pkg/kbagent/service/command.go
  pkg/kbagent/service/command_test.go
Labels: approved, size/L

#8187 chore: sync v1 API description with v1alpha1
  apis/apps/v1/cluster_types.go
  apis/apps/v1/component_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/M

#8184 fix: the reclaim policy of the rebuilt PV is incorrect.
  controllers/apps/operations/rebuild_instance_inplace.go
  controllers/apps/operations/rebuild_instance_test.go
Labels: approved, size/M

#8186 chore: fix the phase of the upgrade ops is incorrect
  pkg/operations/ops_comp_helper.go
  pkg/operations/upgrade_test.go
Labels: approved, size/S

#8189 chore: fix the phase of the upgrade ops is incorrect
  controllers/apps/operations/ops_comp_helper.go
  controllers/apps/operations/upgrade_test.go
Labels: approved, size/S

#8178 chore: refine the labels and annotations
  cmd/manager/main.go
  controllers/apps/cluster_controller_test.go
  controllers/apps/cluster_plan_builder.go
  controllers/apps/component_controller_test.go
  controllers/apps/configuration/configuration_test.go
  controllers/apps/configuration/reconfigure_controller.go
  controllers/apps/transformer_cluster_api_normalization.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_cluster_service.go
  controllers/apps/transformer_cluster_shared_account.go
  controllers/apps/transformer_component_account.go
  controllers/apps/transformer_component_deletion.go
  controllers/apps/transformer_component_rbac.go
  controllers/apps/transformer_component_rbac_test.go
  controllers/apps/transformer_component_service.go
  controllers/apps/transformer_component_status.go
  controllers/apps/transformer_component_vars.go
  controllers/apps/transformer_component_workload.go
  controllers/apps/transformer_component_workload_upgrade.go
  controllers/dataprotection/utils.go
  controllers/operations/opsrequest_controller_test.go
  pkg/constant/annotations.go
  pkg/constant/flag.go
  pkg/constant/labels.go
  pkg/controller/component/component.go
  pkg/controller/component/service_reference_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/synthesize_component_test.go
  pkg/controller/component/type.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
  pkg/controller/component/workload_utils.go
  pkg/controller/configuration/envfrom_utils.go
  pkg/controller/configuration/pipeline.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/object_builder.go
  pkg/controller/instanceset/utils.go
  pkg/controller/plan/restore.go
  pkg/controller/plan/restore_test.go
  pkg/controller/plan/tls_utils.go
  pkg/controllerutil/cluster_utils_test.go
  pkg/controllerutil/sharding_utils_test.go
  pkg/operations/custom/utils.go
  pkg/operations/custom_test.go
  pkg/operations/rebuild_instance_inplace.go
  pkg/testutil/apps/cluster_instance_set_test_util.go
Labels: approved, size/XL

#8193 feat: add BuildInstanceName2TemplateMap public api
  pkg/controller/instanceset/instance_template_util.go
Labels: size/M, pre-approve

#8194 feat: add BuildInstanceName2TemplateMap public api
  pkg/controller/instanceset/instance_template_util.go
Labels: size/M, pre-approve

#8191 chore: remove the deprecated apis from the opsRequest
  apis/operations/v1alpha1/opsdefinition_types.go
  apis/operations/v1alpha1/opsrequest_conditions.go
  apis/operations/v1alpha1/opsrequest_conditions_test.go
  apis/operations/v1alpha1/opsrequest_types.go
  apis/operations/v1alpha1/opsrequest_validation.go
  apis/operations/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  controllers/operations/opsrequest_controller.go
  controllers/operations/opsrequest_controller_test.go
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
  pkg/dataprotection/backup/scheduler.go
  pkg/operations/horizontal_scaling.go
  pkg/operations/horizontal_scaling_test.go
  pkg/operations/ops_progress_util_test.go
  pkg/operations/ops_util_test.go
  pkg/operations/reconfigure.go
  pkg/operations/reconfigure_test.go
  pkg/operations/upgrade.go
Labels: approved, size/XXL

#8204 chore: refine the resources each controllers watched
  config/rbac/role.yaml
  controllers/apps/cluster_controller.go
  controllers/apps/component_controller.go
  controllers/apps/component_controller_test.go
  controllers/apps/transform_utils.go
  controllers/apps/transform_utils_test.go
  controllers/apps/transformer_cluster_deletion.go
  controllers/apps/transformer_cluster_secret.go
  controllers/apps/transformer_component_deletion.go
  deploy/helm/config/rbac/role.yaml
  pkg/controller/model/transform_utils.go
  pkg/controller/model/transform_utils_test.go
Labels: approved, size/L

#8016 chore: split service creation
  controllers/apps/transformer_cluster_service.go
  controllers/apps/transformer_cluster_service_test.go
  controllers/apps/transformer_component_service.go
  controllers/apps/utils.go
  pkg/testutil/apps/constant.go
Labels: approved, size/L

#8188 fix: config-related resource cannot be cleaned up after disable addons
  controllers/apps/componentdefinition_controller.go
  controllers/apps/configuration/config_util.go
Labels: approved, size/M

#8206 chore: remove the volume protection and its RBAC resources
  config/rbac/role.yaml
  controllers/apps/component_controller.go
  controllers/apps/component_controller_test.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/componentdefinition_controller_test.go
  controllers/apps/transformer_cluster_ownership.go
  controllers/apps/transformer_component_deletion.go
  controllers/apps/transformer_component_rbac.go
  controllers/apps/transformer_component_rbac_test.go
  controllers/apps/transformer_component_utils.go
  deploy/helm/config/rbac/role.yaml
  deploy/helm/templates/rbac/cluster_pod_required_role.yaml
  pkg/constant/const.go
  pkg/controller/builder/builder_cluster_role_binding.go
  pkg/controller/builder/builder_cluster_role_binding_test.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
  pkg/controller/model/transform_utils.go
  pkg/controller/model/transform_utils_test.go
  test/e2e/testdata/smoketest/kafka/00_kafkacluster.yaml
  test/e2e/testdata/smoketest/llm/00_llmcluster.yaml
  test/e2e/testdata/smoketest/mariadb/00_mariadbcluster.yaml
  test/e2e/testdata/smoketest/mongodb/00_mongodbcluster.yaml
  test/e2e/testdata/smoketest/mysql-57/00_mysqlcluster.yaml
  test/e2e/testdata/smoketest/mysql-80/00_mysqlcluster.yaml
  test/e2e/testdata/smoketest/official-postgresql/00_official_pgcluster.yaml
  test/e2e/testdata/smoketest/orioledb/00_orioledbcluster.yaml
  test/e2e/testdata/smoketest/postgresql/00_postgresqlcluster.yaml
  test/e2e/testdata/smoketest/redis/00_rediscluster.yaml
  test/e2e/testdata/smoketest/tdengine/00_tdenginecluster.yaml
  test/e2e/testdata/smoketest/wesql/00_wesqlcluster.yaml
Labels: approved, size/XL

#8205 chore: collect the log of the backup failed
  controllers/dataprotection/log_collection_controller.go
Labels: approved, size/M

#8208 chore: collect the log of the backup failed
  controllers/dataprotection/log_collection_controller.go
Labels: approved, size/M

#8202 chore: remove the Halt termination policy type
  apis/apps/v1/cluster_types.go
  apis/apps/v1/types.go
  apis/apps/v1alpha1/cluster_conversion.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  controllers/apps/cluster_controller.go
  controllers/apps/cluster_controller_test.go
  controllers/apps/component_controller_test.go
  controllers/apps/transform_utils.go
  controllers/apps/transformer_cluster_deletion.go
  controllers/apps/transformer_cluster_halt.go
  controllers/apps/transformer_cluster_halt_recovering.go
  controllers/apps/transformer_component_deletion.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/annotations.go
  pkg/controller/plan/restore.go
Labels: approved, size/L

#8210 chore: remove the sharding selector of cluster service
  apis/apps/v1/cluster_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  controllers/apps/cluster_controller_test.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_cluster_service.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/flag.go
Labels: approved, size/L

#8209 chore: update supported-addons, divide into categories
  docs/user_docs/overview/supported-addons.md
Labels: approved, size/L

#8207 docs: fix a typo in user docs
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/create-and-connect-a-postgresql-cluster.md
Labels: size/XS, pre-approve

#8215 chore: fix kb start crash
  cmd/manager/main.go
Labels: approved, size/XS

#8218 fix: create redis bpt failed
  controllers/apps/backuppolicytemplate_controller.go
  controllers/apps/componentversion_controller.go
Labels: approved, size/M

#8054 chore: implement switchover operation with kbagent
  pkg/controller/job/job_utils.go
  pkg/controller/job/job_utils_test.go
  pkg/controller/job/suite_test.go
  pkg/operations/switchover.go
  pkg/operations/switchover_test.go
  pkg/operations/switchover_util.go
Labels: approved, size/XL

#8227 chore: set clusterdefinition.componentDefs default to empty list
  apis/apps/v1alpha1/clusterdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
Labels: approved, size/XS

#8230 fix: InPlacePodVerticalScaling not used
  go.mod
  go.sum
  pkg/controller/instanceset/in_place_update_util.go
Labels: approved, size/S

#8222 fix: ConfigMap xxx-rsm-env not found
  cmd/manager/main.go
  controllers/apps/transformer_component_workload_upgrade.go
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  pkg/constant/flag.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/object_builder.go
  pkg/controller/instanceset/object_builder_test.go
  pkg/controller/instanceset/reconciler_assistant_object.go
  pkg/controller/instanceset/reconciler_assistant_object_test.go
  pkg/controller/instanceset/types.go
  pkg/controller/instanceset/utils.go
Labels: approved, size/L
