Repository apecloud/kubeblocks, pull requests merged in 2025-08, with the labels that each got.

#9587 chore: refine the settings of the manager
  cmd/manager/main.go
  controllers/apps/cluster/cluster_controller.go
  controllers/k8score/event_controller.go
  controllers/operations/opsrequest_controller.go
  controllers/parameters/componentparameter_controller.go
  controllers/parameters/reconfigure_controller.go
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  pkg/constant/viper_config.go
Labels: approved, size/L, pick-1.0

#9595 chore: refine the settings of the manager
  cmd/manager/main.go
  controllers/apps/cluster_controller.go
  controllers/apps/configuration/configuration_controller.go
  controllers/apps/configuration/reconfigure_controller.go
  controllers/apps/opsrequest_controller.go
  controllers/k8score/event_controller.go
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  pkg/constant/const.go
Labels: approved, size/L

#9592 fix: volume expansion failed when all pods using InstanceTemplate[pick-1.0]
  apis/operations/v1alpha1/opsrequest_validation.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/operations/volume_expansion.go
  pkg/operations/volume_expansion_test.go
Labels: size/L, pre-approve, nopick

#9600 chore: fix check run error
  .github/workflows/cicd-pull-request.yml
Labels: approved, size/XS, pick-1.0

#9583 fix: post provision action can wait forever for ComponentReady condition
  controllers/apps/component/transformer_component_account_provision.go
  controllers/apps/component/transformer_component_post_provision.go
  controllers/apps/component/transformer_component_post_provision_test.go
  go.mod
  go.sum
  pkg/controller/lifecycle/kbagent.go
  pkg/controller/lifecycle/lifecycle_test.go
  pkg/controllerutil/requeue_errors.go
Labels: approved, size/L, pick-1.0

#9601 feat: opsDefinion supports image mapping for multi service version
  apis/operations/v1alpha1/opsdefinition_types.go
  apis/operations/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operations.kubeblocks.io_opsdefinitions.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsdefinitions.yaml
  docs/developer_docs/api-reference/operations.md
  pkg/controller/component/vars.go
  pkg/operations/custom/action.go
  pkg/operations/custom/action_workload.go
  pkg/operations/custom_test.go
  pkg/operations/custom_workflow.go
  test/testdata/resources/mysql-opsdefinition-sql.yaml
Labels: approved, size/L, pick-1.0

#9605 feat: opsDefinion supports image mapping for multi service version
  apis/operations/v1alpha1/opsdefinition_types.go
  apis/operations/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operations.kubeblocks.io_opsdefinitions.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsdefinitions.yaml
  docs/developer_docs/api-reference/operations.md
  pkg/controller/component/vars.go
  pkg/operations/custom/action.go
  pkg/operations/custom/action_workload.go
  pkg/operations/custom_test.go
  pkg/operations/custom_workflow.go
  test/testdata/resources/mysql-opsdefinition-sql.yaml
Labels: approved, size/L, nopick

#9607 feat: opsDefinion supports image mapping for multi service version
  apis/apps/v1alpha1/opsdefinition_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/crd/bases/apps.kubeblocks.io_opsdefinitions.yaml
  controllers/apps/operations/custom/action.go
  controllers/apps/operations/custom/action_workload.go
  controllers/apps/operations/custom_test.go
  controllers/apps/operations/custom_workflow.go
  deploy/helm/crds/apps.kubeblocks.io_opsdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  test/testdata/resources/mysql-opsdefinition-sql.yaml
Labels: approved, size/L, nopick

#9608 fix: create custom ops failed
  apis/apps/v1alpha1/opsdefinition_types.go
  controllers/apps/operations/custom/utils.go
Labels: approved, size/S, nopick

#9611 chore: tidy up the description of the cmpd API
  apis/apps/v1/componentdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/M, pick-1.0

#9626 fix: cluster is always deleting when some custom ops are running
  controllers/operations/opsrequest_controller.go
Labels: approved, size/S, pick-1.0

#9623 feat: support to scale out replicas from backup
  apis/operations/v1alpha1/opsrequest_types.go
  apis/operations/v1alpha1/opsrequest_validation.go
  apis/operations/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/operations.md
  pkg/controller/plan/restore.go
  pkg/operations/horizontal_scaling.go
  pkg/operations/horizontal_scaling_test.go
Labels: approved, size/XL, pick-1.0

#9635 chore: fix github code scanning alerts
  pkg/common/password.go
  pkg/common/password_test.go
  pkg/controller/component/workload_utils.go
  pkg/controller/sharding/legacy.go
  pkg/kbagent/service/reconfigure.go
  pkg/operations/horizontal_scaling.go
Labels: approved, size/M, nopick

#9639 fix: do not select the replicas being scaled as the data source
  controllers/apps/component/transformer_component_workload_ops.go
Labels: approved, size/S, pick-1.0

#9570 chore: add script to generate rbac summary
  config/rbac/role.yaml
  controllers/parameters/reconfigure_controller.go
  deploy/helm/config/rbac/role.yaml
  hack/rbac-summary.sh
Labels: approved, size/L, pick-0.9, pick-1.0

#9643 chore: ensure the consistency of updating cluster status
  apis/apps/v1/cluster_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  controllers/apps/cluster/transformer_cluster_component_status.go
  controllers/apps/cluster/transformer_cluster_status.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/L, pick-1.0

#9660 chore: revert addon controller use kb sa
  .github/utils/extract_chart_n_image_list.sh
  controllers/extensions/addon_controller_stages.go
  controllers/extensions/const.go
  deploy/helm/dashboards/container-log.json
  deploy/helm/dashboards/kubeblocks-home.json
  deploy/helm/dashboards/kubeblocks-postgresql-detail.json
  deploy/helm/dashboards/kubeblocks-postgresql-overview.json
  deploy/helm/dashboards/loki.json
  deploy/helm/dashboards/nvidia-gpu-exporter.json
  deploy/helm/templates/_helpers.tpl
  deploy/helm/templates/addons/apecloud-mysql-addon.yaml
  deploy/helm/templates/addons/etcd-addon.yaml
  deploy/helm/templates/addons/mongodb-addon.yaml
  deploy/helm/templates/applications/alertmanager-webhook-adaptor-addon.yaml
  deploy/helm/templates/applications/alertmanager-webhook-adaptor-values.yaml
  deploy/helm/templates/applications/apecloud-otel-collector-addon.yaml
  deploy/helm/templates/applications/apecloud-otel-collector-values.yaml
  deploy/helm/templates/applications/aws-loadbalancer-controller-addon.yaml
  deploy/helm/templates/applications/aws-loadbalancer-controller-values.yaml
  deploy/helm/templates/applications/csi-driver-nfs-addon.yaml
  deploy/helm/templates/applications/csi-hostpath-driver-addon.yaml
  deploy/helm/templates/applications/csi-hostpath-driver-values.yaml
  deploy/helm/templates/applications/grafana-addon.yaml
  deploy/helm/templates/applications/grafana-values.yaml
  deploy/helm/templates/applications/prometheus-addon.yaml
  deploy/helm/templates/applications/prometheus-values.yaml
  deploy/helm/templates/applications/snapshot-controller-addon.yaml
  deploy/helm/templates/applications/snapshot-controller-values.yaml
  deploy/helm/templates/applications/vmagent-addon.yaml
  deploy/helm/templates/applications/vmagent-values.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/templates/grafana/configmap-dashboards.yaml
  deploy/helm/templates/grafana/configmaps-datasources.yaml
  deploy/helm/templates/prometheus/alertmanager.yaml
  deploy/helm/templates/prometheus/monitor.yaml
  deploy/helm/templates/prometheus/webhook-adaptor.yaml
  deploy/helm/templates/rbac/clusterrole_binding.yaml
  deploy/helm/templates/serviceaccount.yaml
  deploy/helm/values.yaml
  docs/user_docs/installation/install-kubeblocks.md
  docs/user_docs/upgrade-kubeblocks/faq.md
  i18n/zh-cn/user-docs/installation/install-kubeblocks.md
  i18n/zh-cn/user-docs/upgrade-kubeblocks/faq.md
  pkg/controller/instanceset/revision_util_test.go
Labels: approved, size/XXL, nopick

#9662 chore: fix the random failure in the FlatInstanceOrdinal test
  controllers/workloads/instanceset_controller_test.go
  pkg/controller/instanceset/reconciler_status.go
  pkg/controller/instanceset2/reconciler_status.go
Labels: approved, size/M, nopick

#9664 chore: manage PVCs within the workload
  cmd/manager/main.go
  controllers/apps/cluster/transformer_cluster_deletion.go
  controllers/apps/cluster/utils.go
  controllers/apps/component/component_controller.go
  controllers/apps/component/component_controller_test.go
  controllers/apps/component/suite_test.go
  controllers/apps/component/transformer_component_status.go
  controllers/apps/component/transformer_component_workload.go
  controllers/apps/component/transformer_component_workload_ops.go
  controllers/apps/util/multicluster.go
  controllers/operations/suite_test.go
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  pkg/constant/annotations.go
  pkg/constant/labels.go
  pkg/constant/viper_config.go
Labels: approved, size/XL, nopick
