Repository apecloud/kubeblocks, pull requests merged in 2025-07, with the labels that each got.

#9510 chore: bump datasafed version to 0.2.1
  deploy/helm/values.yaml
Labels: approved, size/XS, pick-1.0

#9507 fix: scale-in after scale-out immediately failed
  controllers/apps/transformer_component_workload.go
Labels: approved, size/S

#9502 chore: remove deprecated cluster field in ServiceRef
  apis/apps/v1/types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/service_reference.go
Labels: approved, size/L, nopick

#9517 fix: pick the format difference between number/boo/float and string for json (#9488)
  cmd/reloader/template/main.go
  pkg/configuration/config_manager/reload_util.go
  pkg/configuration/core/config_util.go
  pkg/configuration/core/config_util_test.go
  pkg/configuration/core/type.go
  pkg/controller/configuration/patch_merger.go
  pkg/controller/configuration/template_merger.go
  pkg/controller/configuration/template_merger_test.go
  pkg/controller/configuration/value_transformer.go
  pkg/unstructured/viper_wrap.go
Labels: approved, size/L, nopick

#9514 feat: export user-defined environment variables to lifecycle actions
  pkg/controller/component/synthesize_component.go
Labels: size/XS, pre-approve, pick-1.0

#9520 chore: fork pr skip pr-check
  .github/workflows/pull-request-check.yml
Labels: approved, size/XS, nopick

#9528 chore: add new properties formatter for nebula addon
  apis/parameters/v1alpha1/types.go
  config/crd/bases/parameters.kubeblocks.io_paramconfigrenderers.yaml
  deploy/helm/crds/parameters.kubeblocks.io_paramconfigrenderers.yaml
  docs/developer_docs/api-reference/parameters.md
  pkg/unstructured/properties.go
  pkg/unstructured/properties_test.go
Labels: approved, size/M, pick-1.0

#9532 fix: use /resize subresource in InPlacePodVerticalScaling when supported (#9349)
  go.mod
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/instanceset/reconciler_update_test.go
  pkg/controller/kubebuilderx/plan_builder.go
  pkg/controller/kubebuilderx/plan_builder_test.go
  pkg/controller/kubebuilderx/reconciler.go
  pkg/controller/kubebuilderx/reconciler_test.go
  pkg/controller/kubebuilderx/suite_test.go
  pkg/controller/model/graph_options.go
  pkg/controller/model/transform_types.go
  pkg/controllerutil/util.go
  pkg/controllerutil/util_test.go
  pkg/dataprotection/backup/utils.go
  pkg/dataprotection/utils/utils.go
  pkg/dataprotection/utils/utils_test.go
Labels: approved, size/L

#9536 fix: use /resize subresource in InPlacePodVerticalScaling when supported (#9349)
  go.mod
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/instanceset/reconciler_update_test.go
  pkg/controller/kubebuilderx/plan_builder.go
  pkg/controller/kubebuilderx/plan_builder_test.go
  pkg/controller/kubebuilderx/reconciler.go
  pkg/controller/kubebuilderx/reconciler_test.go
  pkg/controller/kubebuilderx/suite_test.go
  pkg/controller/model/graph_options.go
  pkg/controller/model/transform_types.go
  pkg/controllerutil/util.go
  pkg/controllerutil/util_test.go
  pkg/dataprotection/backup/utils.go
  pkg/dataprotection/utils/utils.go
  pkg/dataprotection/utils/utils_test.go
Labels: approved, size/L

#9522 chore: rollout for the sharding cluster
  apis/apps/v1alpha1/rollout_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_rollouts.yaml
  controllers/apps/cluster/transformer_cluster_normalization.go
  controllers/apps/rollout/rollout_controller_test.go
  controllers/apps/rollout/rollout_plan_builder.go
  controllers/apps/rollout/transformer_rollout_inplace.go
  controllers/apps/rollout/transformer_rollout_load.go
  controllers/apps/rollout/transformer_rollout_replace.go
  controllers/apps/rollout/transformer_rollout_setup.go
  controllers/apps/rollout/transformer_rollout_status.go
  controllers/apps/rollout/transformer_rollout_teardown.go
  deploy/helm/crds/apps.kubeblocks.io_rollouts.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/testutil/apps/cluster_factory.go
  pkg/testutil/apps/component_factory.go
  pkg/testutil/apps/rollout_factory.go
Labels: approved, size/XXL, nopick

#9533 chore: add new properties formatter for nebula addon (#9528)
  apis/apps/v1beta1/type.go
  config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
  deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/unstructured/properties.go
  pkg/unstructured/properties_test.go
Labels: approved, size/M

#9545 fix: missing rbac rule for pod resize
  config/rbac/role.yaml
  controllers/workloads/instanceset_controller.go
  deploy/helm/config/rbac/role.yaml
Labels: approved, size/S, pick-0.9, pick-1.0

#9555 fix: ignore BucketAlreadyExists errors for OSS
  deploy/helm/templates/storageprovider/oss.yaml
Labels: approved, size/XS, pick-1.0

#9557 chore: fix lint error in test
  pkg/controller/plan/restore_test.go
Labels: approved, size/XS, pick-1.0

#9559 chore: check pr run
  .github/workflows/cicd-pull-request.yml
Labels: approved, size/S, pick-0.9, pick-1.0

#9567 fix: Restore job's label did not respect InstanceTemplate and ordinals
  pkg/dataprotection/restore/builder.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/manager_test.go
Labels: size/M, pre-approve, pick-1.0

#9566 fix: pick support parameter value transformer for yaml formatter
  pkg/controller/configuration/value_transformer.go
Labels: approved, size/XS

#9573 chore: addon controller use kb sa for kb09
  controllers/extensions/addon_controller_stages.go
  controllers/extensions/const.go
  deploy/helm/templates/_helpers.tpl
  deploy/helm/templates/deployment.yaml
  deploy/helm/templates/rbac/clusterrole_binding.yaml
  deploy/helm/templates/serviceaccount.yaml
  deploy/helm/values.yaml
Labels: approved, size/M

#9574 chore: support parameter value transformer for toml formatter
  pkg/controller/configuration/value_transformer.go
  pkg/dataprotection/restore/builder.go
  pkg/unstructured/viper_wrap_test.go
Labels: approved, size/M, pick-1.0

#9575 chore: change the visibility of BuildValueTransformer from private to public
  pkg/controller/configuration/patch_merger.go
  pkg/controller/configuration/template_merger.go
  pkg/controller/configuration/value_transformer.go
Labels: approved, size/XS, pick-1.0

#9584 fix: add map lock for concurrent access in lorry client
  pkg/lorry/client/httpclient.go
Labels: approved, size/M, nopick
