Repository apecloud/kubeblocks, pull requests merged in 2025-02, with the labels that each got.

#8876 chore: call the switchover action only once, do not repeat the call
  pkg/operations/switchover.go
Labels: approved, size/L

#8879 fix: enable pitr failed for postgresql
  pkg/dataprotection/backup/scheduler.go
Labels: approved, size/XS

#8878 chore: update kb install guide
  docs/user_docs/installation/install-kubeblocks.md
  i18n/zh-cn/user-docs/installation/install-kubeblocks.md
Labels: documentation, approved, size/L

#8865 fix: use update instead of patch to set pod's role
  pkg/controller/instanceset/pod_role_event_handler.go
  pkg/controller/instanceset/pod_role_event_handler_test.go
Labels: approved, size/M

#8871 fix: use update instead of patch to set pod's role
  pkg/controller/instanceset/pod_role_event_handler.go
  pkg/controller/instanceset/pod_role_event_handler_test.go
Labels: approved, size/M

#8887 docs: fix url bugs in cn docs
  i18n/zh-cn/user-docs/maintenance/backup-and-restore/backup/backup-repo.md
Labels: approved, size/XS

#8888 docs: fix bugs in backup repo docs in release 0.9
  docs/user_docs/maintenance/backup-and-restore/backup/backup-repo.md
  i18n/zh-cn/user-docs/maintenance/backup-and-restore/backup/backup-repo.md
Labels: approved, size/M

#8893 chore: remove addon snapshot-controller
  deploy/helm/scripts/change_kb_release.sh
  deploy/helm/templates/addons/apecloud-mysql-addon.yaml
  deploy/helm/templates/addons/etcd-addon.yaml
  deploy/helm/templates/addons/mongodb-addon.yaml
  deploy/helm/templates/applications/snapshot-controller-addon.yaml
  deploy/helm/templates/applications/snapshot-controller-values.yaml
  deploy/helm/values.yaml
  docs/user_docs/installation/install-kubeblocks.md
  docs/user_docs/upgrade-kubeblocks/faq.md
  i18n/zh-cn/user-docs/installation/install-kubeblocks.md
  i18n/zh-cn/user-docs/upgrade-kubeblocks/faq.md
Labels: approved, size/L

#8850 chore: support updating TLS certificates
  apis/apps/v1/types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/cluster/transformer_cluster_sharding_tls.go
  controllers/apps/component/component_controller.go
  controllers/apps/component/component_controller_test.go
  controllers/apps/component/transformer_component_tls.go
  controllers/apps/component/transformer_component_tls_test.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/plan/tls.go
  pkg/controller/plan/tls_test.go
  pkg/testutil/apps/cluster_factory.go
Labels: approved, size/XXL

#8895 fix: restore mysql failed
  pkg/controller/plan/restore.go
  pkg/operations/restore.go
  pkg/operations/restore_test.go
Labels: approved, size/L

#8880 chore: the config template referenced might be empty
  controllers/apps/configuration/config_util.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/synthesize_component_test.go
Labels: approved, size/M

#8894 fix: validate the topology as immutable
  apis/apps/v1/cluster_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
Labels: approved, size/S

#8874 fix: remove the pattern validation for ResourceMeta.MountPoint
  apis/apps/v1alpha1/cluster_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
Labels: size/XS, pre-approve

#8897 chore: docker build failed
  docker/custom-scripts/fetch-all-helm-charts.sh
Labels: approved, size/XS

#8898 chore: doc update pod monitors
  docs/user_docs/observability/monitor-database.md
  i18n/zh-cn/user-docs/observability/monitor-database.md
Labels: approved, size/M

#8899 chore: remove incorrect comments for the offlineInstances field
  apis/apps/v1/cluster_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/S

#8854 chore: support define policy rules in helm values
  apis/apps/v1/componentdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/templates/rbac/rbac_manager_additaional_role.yaml
  deploy/helm/values.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/M

#8904 fix: ensure GeneratePassword returns password with mixed cases
  controllers/apps/cluster/transformer_cluster_sharding_account.go
  controllers/apps/component/transformer_component_account.go
  pkg/common/password.go
  pkg/common/password_test.go
Labels: size/L, pre-approve

#8927 chore: fix staticcheck error
  pkg/testutil/apps/cluster_util.go
Labels: approved, size/XS

#8919 fix: ensure GeneratePassword returns password with mixed cases in release-0.9
  controllers/apps/transformer_cluster_shared_account.go
  controllers/apps/transformer_component_account.go
  pkg/common/password.go
  pkg/common/password_test.go
  pkg/controller/factory/builder.go
  pkg/testutil/apps/cluster_util.go
Labels: size/L, pre-approve

#8913 fix: the cluster controller panic
  controllers/apps/cluster/transformer_cluster_component.go
Labels: approved, size/M

#8925 chore: remove the image in the instance template
  apis/apps/v1/types.go
  apis/apps/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/suite_test.go
Labels: approved, size/M

#8935 fix: pg cluster enable backupschedule wal-g-archive config archive_command twice
  pkg/dataprotection/backup/scheduler.go
Labels: approved, size/S

#8932 fix: backup cross-namespace recovery failed when restoring from opsrequest.
  apis/apps/v1alpha1/opsrequest_types.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/restore.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/M

#8936 fix: pg cluster enable backupschedule wal-g-archive config archive_command twice
  pkg/dataprotection/backup/scheduler.go
Labels: approved, size/S

#8933 chore: validate inc backup's repo
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/utils.go
  pkg/dataprotection/restore/utils.go
Labels: approved, size/L

#8947 chore: set the ownership and finalizer for the tls secret
  controllers/apps/component/transformer_component_tls.go
Labels: approved, size/M

#8950 chore: remove volumes from the instance template
  apis/apps/v1/types.go
  apis/apps/v1/zz_generated.deepcopy.go
  apis/operations/v1alpha1/opsrequest_types.go
  apis/operations/v1alpha1/opsrequest_validation.go
  apis/operations/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/component/component_controller_test.go
  controllers/apps/component/transformer_component_workload.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/instanceset/instance_util.go
  pkg/operations/volume_expansion.go
Labels: approved, size/XXL

#8960 chore: helm values for registry config (#8716)
  deploy/helm/templates/configmap.yaml
Labels: size/XS

#8959 chore: optimize delete sub resources logs when cluster is deleted
  controllers/apps/cluster/transformer_cluster_deletion.go
Labels: approved, size/XS

#8804 fix: cluster supports specifing PVC annotations and labels
  apis/apps/v1/types.go
  apis/apps/v1/zz_generated.deepcopy.go
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controllerutil/volume_util.go
Labels: approved, size/L

#8964 chore: optimize delete sub resources logs
  controllers/apps/transformer_cluster_deletion.go
Labels: approved, size/XS

#8962 docs: add 0.9.3 release notes and update relate docs
  docs/release_notes/v0.9.0/0.9.1.md
  docs/release_notes/v0.9.0/0.9.2.md
  docs/release_notes/v0.9.0/0.9.3.md
  docs/user_docs/upgrade-kubeblocks/upgrade-to-latest-version.md
  i18n/zh-cn/user-docs/upgrade-kubeblocks/upgrade-to-latest-version.md
Labels: approved, size/L

#8965 docs: add 0.9.3 release notes and update relate docs on release-0.9 branch
  docs/release_notes/v0.9.0/0.9.1.md
  docs/release_notes/v0.9.0/0.9.2.md
  docs/release_notes/v0.9.0/0.9.3.md
  docs/user_docs/upgrade-kubeblocks/upgrade-to-latest-version.md
  i18n/zh-cn/user-docs/upgrade-kubeblocks/upgrade-to-latest-version.md
Labels: approved, size/L

#8952 fix: improve switch syntax
  pkg/controller/configuration/envfrom_utils.go
Labels: approved, size/XS

#8967 chore: remove the useless credential of ITS
  apis/workloads/v1/instanceset_types.go
  apis/workloads/v1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/instanceset_conversion.go
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/component/transformer_component_workload.go
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_instance_set.go
  pkg/controller/builder/builder_instance_set_test.go
  pkg/controller/component/its_convertor.go
  pkg/controller/instanceset/object_builder_test.go
  pkg/controller/instanceset/suite_test.go
Labels: approved, size/XL

#8953 chore: fix errors in expose action
  pkg/operations/expose.go
Labels: size/S, pre-approve

#8969 chore: bump golangci-lint to 1.64.5
  .github/workflows/cicd-pull-request.yml
  .github/workflows/cicd-push.yml
  .github/workflows/release-version.yml
  .golangci.yaml
  Makefile
  controllers/trace/informer_manager.go
  controllers/trace/object_tree_root_finder.go
  docker/Dockerfile-dev
  pkg/configuration/core/config_patch_test.go
  pkg/configuration/core/config_test.go
  pkg/kbagent/server/streaming_server.go
Labels: approved, size/M

#8577 feat: support rolling update in the cluster API
  apis/apps/v1/cluster_types.go
  apis/apps/v1/component_types.go
  apis/apps/v1/types.go
  apis/apps/v1/zz_generated.deepcopy.go
  apis/workloads/v1/instanceset_types.go
  apis/workloads/v1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/instanceset_conversion.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/cluster/transformer_cluster_component.go
  controllers/apps/component/transformer_component_workload.go
  controllers/apps/componentdefinition_controller_test.go
  controllers/parameters/reconfigure_policy.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_component.go
  pkg/controller/builder/builder_instance_set.go
  pkg/controller/builder/builder_instance_set_test.go
  pkg/controller/component/component.go
  pkg/controller/component/convertor.go
  pkg/controller/component/convertor_test.go
  pkg/controller/component/its_convertor.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/instanceset/reconciler_update_test.go
  pkg/controller/instanceset/update_plan.go
  pkg/controller/instanceset/update_plan_test.go
  pkg/controller/instanceset/utils.go
  pkg/testutil/apps/constant.go
  pkg/testutil/apps/instance_set_factoy.go
Labels: approved, size/XXL

#8973 feat: support rolling update in the cluster API
  apis/apps/v1/cluster_types.go
  apis/apps/v1/component_types.go
  apis/apps/v1/types.go
  apis/apps/v1/zz_generated.deepcopy.go
  apis/workloads/v1/instanceset_types.go
  apis/workloads/v1/zz_generated.deepcopy.go
  apis/workloads/v1alpha1/instanceset_conversion.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/cluster/transformer_cluster_component.go
  controllers/apps/component/transformer_component_workload.go
  controllers/apps/componentdefinition_controller_test.go
  controllers/apps/configuration/reconfigure_policy.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_component.go
  pkg/controller/builder/builder_instance_set.go
  pkg/controller/builder/builder_instance_set_test.go
  pkg/controller/component/component.go
  pkg/controller/component/convertor.go
  pkg/controller/component/convertor_test.go
  pkg/controller/component/its_convertor.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/instanceset/reconciler_update_test.go
  pkg/controller/instanceset/update_plan.go
  pkg/controller/instanceset/update_plan_test.go
  pkg/controller/instanceset/utils.go
  pkg/testutil/apps/constant.go
  pkg/testutil/apps/instance_set_factoy.go
Labels: size/XXL

#8977 fix: redis sentinel get role
  pkg/lorry/engines/redis/get_replica_role.go
  pkg/lorry/engines/redis/redis.go
Labels: approved, size/S

#8620 chore: refactor parameters partV: decouple apps dependence on parameters and tidy up
  cmd/manager/main.go
  controllers/apps/clusterdefinition_controller_test.go
  controllers/apps/component/component_controller.go
  controllers/apps/component/scheme.go
  controllers/apps/component/transformer_component_configuration.go
  controllers/apps/component/transformer_component_deletion.go
  controllers/apps/component/transformer_component_parameters.go
  controllers/apps/component/transformer_component_reload_sidecar.go
  controllers/apps/component/transformer_component_status.go
  controllers/apps/componentdefinition_controller_test.go
  controllers/operations/suite_test.go
  controllers/parameters/componentdrivenparameter_controller.go
  controllers/parameters/componentdrivenparameter_controller_test.go
  controllers/parameters/configuration_test.go
  controllers/parameters/reconcile_task.go
  controllers/parameters/suite_test.go
  controllers/trace/desired_state_handler_test.go
  controllers/trace/dry_run_handler_test.go
  controllers/trace/reconciler_tree.go
  controllers/trace/suite_test.go
  controllers/trace/type.go
  pkg/constant/const.go
  pkg/controller/component/service_reference_test.go
  pkg/controller/component/suite_test.go
  pkg/controller/configuration/config_utils.go
  pkg/controller/configuration/configuration_test.go
  pkg/controller/configuration/operator.go
  pkg/controller/configuration/operator_test.go
  pkg/controller/configuration/pipeline.go
  pkg/controller/configuration/pipeline_test.go
  pkg/controller/configuration/resource_wrapper.go
  pkg/controller/configuration/resource_wrapper_test.go
  pkg/controller/configuration/suite_test.go
  pkg/controller/configuration/template_render.go
  pkg/controller/configuration/template_render_test.go
  pkg/controller/configuration/template_validate.go
  pkg/controller/configuration/template_wrapper.go
  pkg/controller/factory/suite_test.go
  pkg/controller/plan/prepare.go
  pkg/controller/plan/prepare_test.go
  pkg/controller/plan/suite_test.go
  pkg/controller/render/render_utils.go
  pkg/controllerutil/suite_test.go
  pkg/controllerutil/util.go
  pkg/generics/type.go
  pkg/operations/reconfigure_test.go
  pkg/operations/suite_test.go
  test/testdata/config/config-constraint.yaml
  test/testdata/config/config-template.yaml
  test/testdata/config/envfrom-config.yaml
  test/testdata/config/envfrom-constraint.yaml
  test/testdata/operations_config/config-constraint.yaml
  test/testdata/operations_config/config-template.yaml
Labels: approved, size/XXL

#8980 fix: should no change the reclaim policy of PV to Delete
  controllers/apps/component/transformer_component_workload.go
Labels: approved, size/XS

#8982 fix: redis getrole from sentinel
  pkg/lorry/engines/redis/get_replica_role.go
  pkg/lorry/engines/redis/manager.go
  pkg/lorry/engines/redis/redis.go
Labels: approved, size/M
