Repository apecloud/kubeblocks, pull requests merged in 2025-09, with the labels that each got.

#9690 fix: clickhouse switchover failed
  pkg/controller/instance/reconciler_update.go
  pkg/controller/instanceset/reconciler_update.go
Labels: approved, size/XS, pick-1.0

#9692 fix: clickhouse switchover failed during restart
  pkg/controller/instanceset/reconciler_update.go
Labels: approved, size/XS, nopick

#9707 chore: fix go import
  controllers/dataprotection/backup_controller.go
Labels: approved, size/XS

#9713 chore: run BackupRepo precheck job with non-root user
  controllers/dataprotection/backuprepo_controller.go
  pkg/dataprotection/utils/backuprepo.go
Labels: approved, size/S, pick-0.9, pick-1.0

#9727 fix: do not set runAsNonRoot to the init container of datasafed
  controllers/dataprotection/backuprepo_controller.go
  pkg/dataprotection/utils/backuprepo.go
Labels: approved, size/XS, pick-0.9, pick-1.0

#9720 chore: maintain the status of volume expansion in ITS
  apis/workloads/v1/instance_types.go
  apis/workloads/v1/instanceset_types.go
  config/crd/bases/workloads.kubeblocks.io_instances.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/component/transformer_component_status.go
  deploy/helm/crds/workloads.kubeblocks.io_instances.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/workload_utils.go
  pkg/controller/instance/reconciler_status.go
  pkg/controller/instanceset/reconciler_status.go
  pkg/controller/instanceset/reconciler_status_test.go
  pkg/controller/instanceset2/reconciler_status.go
Labels: approved, size/L, nopick

#9736 feat: support specifying an update policy for the upgrade operation
  apis/apps/v1/cluster_types.go
  apis/apps/v1/component_types.go
  apis/apps/v1/componentdefinition_types.go
  apis/apps/v1/types.go
  apis/apps/v1/zz_generated.deepcopy.go
  apis/workloads/v1/instanceset_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/cluster/transformer_cluster_component.go
  controllers/apps/component/transformer_component_workload.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  go.mod
  go.sum
  pkg/controller/builder/builder_component.go
  pkg/controller/builder/builder_instance_set.go
  pkg/controller/builder/builder_instance_set_test.go
  pkg/controller/component/component.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/factory/builder.go
  pkg/controller/instanceset/in_place_update_util.go
  pkg/controller/instanceset/in_place_update_util_test.go
  pkg/controller/instanceset/reconciler_update.go
Labels: approved, size/XL, nopick

#9746 fix: pod update policy for the stopping ITS
  pkg/controller/instanceset/in_place_update_util.go
Labels: approved, size/S, nopick

#9744 chore: fill in the actual component name for the sharding scheduling policy
  controllers/apps/cluster/transformer_cluster_component.go
Labels: approved, size/M, pick-1.0

#9747 fix: pod update policy for the stopping ITS
  pkg/controller/instanceset/in_place_update_util.go
Labels: approved, size/S, nopick

#9748 chore: fill in the actual component name for the sharding scheduling policy
  controllers/apps/cluster/transformer_cluster_component.go
Labels: approved, size/M, nopick

#9753 chore: restart component and check component status
  controllers/parameters/policy_util.go
  controllers/parameters/policy_util_test.go
  controllers/parameters/reconfigure_policy.go
  controllers/parameters/restart_policy.go
  controllers/parameters/restart_policy_test.go
  controllers/parameters/types.go
Labels: approved, size/L, pick-1.0

#9755 chore: refine the lifecycle action API in ITS
  apis/workloads/v1/instance_types.go
  apis/workloads/v1/instanceset_types.go
  apis/workloads/v1/zz_generated.deepcopy.go
  config/crd/bases/workloads.kubeblocks.io_instances.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/component/transformer_component_template.go
  controllers/apps/component/transformer_component_vars.go
  controllers/apps/component/transformer_component_workload.go
  controllers/workloads/instance_controller_test.go
  deploy/helm/crds/workloads.kubeblocks.io_instances.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_instance.go
  pkg/controller/builder/builder_instance_set.go
  pkg/controller/builder/builder_instance_set_test.go
  pkg/controller/component/type.go
  pkg/controller/component/vars.go
  pkg/controller/factory/builder.go
  pkg/controller/instance/reconciler_update.go
  pkg/controller/instance/utils.go
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/instanceset/utils.go
  pkg/controller/instanceset2/instance_util.go
  pkg/controller/lifecycle/kbagent.go
  pkg/controller/lifecycle/lifecycle.go
  pkg/controller/lifecycle/lifecycle_test.go
  pkg/controller/render/builtin_objects.go
  pkg/testutil/apps/instance_factoy.go
Labels: approved, size/XXL, nopick

#9769 chore: upgrade datasafed to 0.2.2
  deploy/helm/values.yaml
Labels: approved, pick-0.9, pick-1.0

#9771 fix: mysql restore is always running
  controllers/dataprotection/restore_controller.go
Labels: approved, size/XS, pick-1.0
