Repository apecloud/kubeblocks, pull requests merged in 2025-01, with the labels that each got.

#8740 chore: update dependent module version
  go.mod
  go.sum
  pkg/configuration/container/container_kill.go
Labels: approved, size/L

#8744 chore: set podService default false
  apis/apps/v1/cluster_types.go
  apis/apps/v1alpha1/cluster_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  controllers/apps/transformer_cluster_component.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
Labels: approved, size/S

#8743 chore: set podService default false
  apis/apps/v1alpha1/cluster_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/transformer_cluster_component.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
Labels: approved, size/S

#8706 docs: update cluster create cli command, yaml examples and monitoring docs
  docs/user_docs/kubeblocks-for-apecloud-mysql/cluster-management/create-and-connect-an-apecloud-mysql-cluster.md
  docs/user_docs/kubeblocks-for-elasticsearch/manage-elasticsearch.md
  docs/user_docs/kubeblocks-for-kafka/cluster-management/create-a-kafka-cluster.md
  docs/user_docs/kubeblocks-for-milvus/manage-milvus.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/create-and-connect-a-postgresql-cluster.md
  docs/user_docs/kubeblocks-for-pulsar/cluster-management/create-pulsar-cluster-on-kubeblocks.md
  docs/user_docs/kubeblocks-for-qdrant/manage-qdrant.md
  docs/user_docs/kubeblocks-for-rabbitmq/manage-rabbitmq.md
  docs/user_docs/kubeblocks-for-redis/cluster-management/create-and-connect-a-redis-cluster.md
  docs/user_docs/kubeblocks-for-starrocks/manage-starrocks.md
  docs/user_docs/observability/monitor-database.md
  i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/cluster-management/create-and-connect-an-apecloud-mysql-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-elasticsearch/manage-elasticsearch.md
  i18n/zh-cn/user-docs/kubeblocks-for-kafka/cluster-management/create-a-kafka-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-milvus/manage-milvus.md
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/cluster-management/create-and-connect-a-postgresql-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-pulsar/cluster-management/create-pulsar-cluster-on-kb.md
  i18n/zh-cn/user-docs/kubeblocks-for-qdrant/manage-qdrant.md
  i18n/zh-cn/user-docs/kubeblocks-for-rabbitmq/manage-rabbitmq.md
  i18n/zh-cn/user-docs/kubeblocks-for-redis/cluster-management/create-and-connect-to-a-redis-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-starrocks/manage-starrocks.md
  i18n/zh-cn/user-docs/observability/monitor-database.md
Labels: approved, size/XXL

#8746 fix: lorry support redis 5.x
  pkg/lorry/engines/redis/manager.go
  pkg/lorry/engines/redis/manager_test.go
Labels: approved, size/M

#8693 feat: supports incremental backup
  apis/dataprotection/v1alpha1/backup_types.go
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  apis/dataprotection/v1alpha1/backuppolicytemplate_types.go
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/dataprotection/actionset_controller_test.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/backuppolicy_controller_test.go
  controllers/dataprotection/backuppolicytemplate_controller_test.go
  controllers/dataprotection/backupschedule_controller_test.go
  controllers/dataprotection/gc_controller_test.go
  controllers/dataprotection/log_collection_controller_test.go
  controllers/dataprotection/restore_controller_test.go
  controllers/dataprotection/utils.go
  controllers/dataprotection/volumepopulator_controller_test.go
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  docs/developer_docs/api-reference/backup.md
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/backup/utils.go
  pkg/dataprotection/restore/builder.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/utils.go
  pkg/dataprotection/types/constant.go
  pkg/dataprotection/utils/utils.go
  pkg/testutil/dataprotection/backup_utils.go
  pkg/testutil/dataprotection/backuppolicy_factory.go
  pkg/testutil/dataprotection/constant.go
  pkg/testutil/dataprotection/utils.go
Labels: approved, size/XXL

#8757 feat: supports incremental backup in release-0.9
  apis/dataprotection/v1alpha1/backup_types.go
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  controllers/dataprotection/actionset_controller_test.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/backuppolicy_controller_test.go
  controllers/dataprotection/backupschedule_controller_test.go
  controllers/dataprotection/gc_controller_test.go
  controllers/dataprotection/log_collection_controller_test.go
  controllers/dataprotection/restore_controller_test.go
  controllers/dataprotection/utils.go
  controllers/dataprotection/volumepopulator_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  docs/developer_docs/api-reference/backup.md
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/backup/utils.go
  pkg/dataprotection/restore/builder.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/utils.go
  pkg/dataprotection/types/constant.go
  pkg/dataprotection/utils/utils.go
  pkg/testutil/dataprotection/backup_utils.go
  pkg/testutil/dataprotection/backuppolicy_factory.go
  pkg/testutil/dataprotection/constant.go
  pkg/testutil/dataprotection/utils.go
Labels: approved, size/XXL

#8729 docs: update kbcli cluster create, yaml, and monitoring docs in release-1.0
  docs/user_docs/kubeblocks-for-apecloud-mysql/cluster-management/create-and-connect-an-apecloud-mysql-cluster.md
  docs/user_docs/kubeblocks-for-apecloud-mysql/cluster-management/delete-mysql-cluster.md
  docs/user_docs/kubeblocks-for-apecloud-mysql/kubeblocks-for-apecloud-mysql.md
  docs/user_docs/kubeblocks-for-elasticsearch/manage-elasticsearch.md
  docs/user_docs/kubeblocks-for-kafka/cluster-management/create-a-kafka-cluster.md
  docs/user_docs/kubeblocks-for-kafka/cluster-management/delete-kafka-cluster.md
  docs/user_docs/kubeblocks-for-milvus/manage-milvus.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/delete-mongodb-cluster.md
  docs/user_docs/kubeblocks-for-mongodb/kubeblocks-for-mongodb.md
  docs/user_docs/kubeblocks-for-mysql-community-edition/cluster-management/create-and-connect-a-mysql-cluster.md
  docs/user_docs/kubeblocks-for-mysql-community-edition/cluster-management/delete-mysql-cluster.md
  docs/user_docs/kubeblocks-for-mysql-community-edition/kubeblocks-for-mysql-community-edition.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/create-and-connect-a-postgresql-cluster.md
  docs/user_docs/kubeblocks-for-postgresql/cluster-management/delete-a-postgresql-cluster.md
  docs/user_docs/kubeblocks-for-postgresql/kubeblocks-for-postgresql.md
  docs/user_docs/kubeblocks-for-pulsar/cluster-management/create-pulsar-cluster-on-kubeblocks.md
  docs/user_docs/kubeblocks-for-pulsar/cluster-management/delete-a-pulsar-cluster.md
  docs/user_docs/kubeblocks-for-pulsar/kubeblocks-for-pulsar.md
  docs/user_docs/kubeblocks-for-qdrant/manage-qdrant.md
  docs/user_docs/kubeblocks-for-rabbitmq/manage-rabbitmq.md
  docs/user_docs/kubeblocks-for-redis/cluster-management/create-and-connect-a-redis-cluster.md
  docs/user_docs/kubeblocks-for-redis/cluster-management/delete-a-redis-cluster.md
  docs/user_docs/kubeblocks-for-redis/kubeblocks-for-redis.md
  docs/user_docs/kubeblocks-for-starrocks/manage-starrocks.md
  docs/user_docs/observability/monitor-database.md
  i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/cluster-management/create-and-connect-an-apecloud-mysql-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/cluster-management/delete-mysql-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/kubeblocks-for-apecloud-mysql.md
  i18n/zh-cn/user-docs/kubeblocks-for-elasticsearch/manage-elasticsearch.md
  i18n/zh-cn/user-docs/kubeblocks-for-kafka/cluster-management/create-a-kafka-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-kafka/cluster-management/delete-kafka-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-kafka/kubeblocks-for-kafka.md
  i18n/zh-cn/user-docs/kubeblocks-for-milvus/manage-milvus.md
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/cluster-management/delete-a-mongodb-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-mongodb/kubeblocks-for-mongodb.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql-community-edition/cluster-management/create-and-connect-a-mysql-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql-community-edition/cluster-management/delete-mysql-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-mysql-community-edition/kubeblocks-for-mysql-community-edition.md
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/cluster-management/create-and-connect-a-postgresql-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/cluster-management/delete-a-postgresql-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-postgresql/kubeblocks-for-postgresql.md
  i18n/zh-cn/user-docs/kubeblocks-for-pulsar/cluster-management/create-pulsar-cluster-on-kb.md
  i18n/zh-cn/user-docs/kubeblocks-for-pulsar/cluster-management/delete-pulsar-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-pulsar/kubeblocks-for-pulsar.md
  i18n/zh-cn/user-docs/kubeblocks-for-qdrant/manage-qdrant.md
  i18n/zh-cn/user-docs/kubeblocks-for-rabbitmq/manage-rabbitmq.md
  i18n/zh-cn/user-docs/kubeblocks-for-redis/cluster-management/create-and-connect-to-a-redis-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-redis/cluster-management/delete-a-redis-cluster.md
  i18n/zh-cn/user-docs/kubeblocks-for-redis/kubeblocks-for-redis.md
  i18n/zh-cn/user-docs/kubeblocks-for-starrocks/manage-starrocks.md
  i18n/zh-cn/user-docs/observability/monitor-database.md
Labels: approved, size/XXL

#8759 chore: update user-docs fix some typos
  docs/03 - debug.md
  docs/04 - basics.md
  docs/user_docs/installation/prepare-a-local-k8s-cluster/prepare-a-local-k8s-cluster.md
  docs/user_docs/kubeblocks-for-apecloud-mysql/cluster-management/scale-for-apecloud-mysql.md
  docs/user_docs/kubeblocks-for-apecloud-mysql/configuration/configuration.md
  docs/user_docs/kubeblocks-for-apecloud-mysql/proxy/apecloud-mysql-proxy.md
  docs/user_docs/kubeblocks-for-elasticsearch/manage-elasticsearch.md
  docs/user_docs/kubeblocks-for-kafka/cluster-management/connect-to-a-cluster.md
  docs/user_docs/kubeblocks-for-kafka/cluster-management/start-stop-a-cluster.md
  docs/user_docs/kubeblocks-for-kafka/configuration/configuration.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/start-stop-a-cluster.md
  docs/user_docs/kubeblocks-for-mongodb/cluster-management/switchover.md
  docs/user_docs/kubeblocks-for-mongodb/configuration/configuration.md
  docs/user_docs/kubeblocks-for-mysql-community-edition/configuration/configuration.md
  docs/user_docs/kubeblocks-for-postgresql/high-availability/high-availability.md
  docs/user_docs/kubeblocks-for-pulsar/configuration/configuration.md
  docs/user_docs/kubeblocks-for-rabbitmq/manage-rabbitmq.md
  docs/user_docs/kubeblocks-for-redis/cluster-management/scale-for-a-redis-cluster.md
  docs/user_docs/kubeblocks-for-redis/configuration/configuration.md
  docs/user_docs/maintenance/backup-and-restore/backup/scheduled-backup.md
  docs/user_docs/maintenance/cross-k8s-deployment/cross-k8s-deployment.md
  docs/user_docs/maintenance/in-place-update/overview.md
  docs/user_docs/maintenance/scale/horizontal-scale.md
  docs/user_docs/observability/monitor-database.md
  docs/user_docs/overview/concept.md
  docs/user_docs/overview/supported-addons.md
Labels: approved, size/M

#8755 chore: fix create cluster with cd/cv failed when existing 0.9 kb
  apis/apps/v1alpha1/conversion.go
  controllers/apps/transformer_cluster_normalization.go
  deploy/helm/templates/conversion-patch-hook.yaml
Labels: approved, size/S

#8731 chore: switchover before updating or deleting pods
  apis/apps/v1/deprecated.go
  apis/apps/v1/types.go
  apis/apps/v1/zz_generated.deepcopy.go
  apis/workloads/v1/instanceset_types.go
  apis/workloads/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/transformer_component_account_provision.go
  controllers/apps/transformer_component_post_provision.go
  controllers/apps/transformer_component_pre_terminate.go
  controllers/apps/transformer_component_service.go
  controllers/apps/transformer_component_status.go
  controllers/apps/transformer_component_workload.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_instance_set.go
  pkg/controller/component/its_convertor.go
  pkg/controller/component/replicas.go
  pkg/controller/component/service_reference_test.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
  pkg/controller/component/workload_utils.go
  pkg/controller/factory/builder.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/instanceset/tree_loader.go
  pkg/controller/instanceset/utils.go
  pkg/controller/instanceset/utils_test.go
  pkg/controller/kubebuilderx/reconciler.go
  pkg/controller/lifecycle/errors.go
  pkg/controller/lifecycle/kbagent.go
  pkg/controller/lifecycle/lfa_account.go
  pkg/controller/lifecycle/lfa_component.go
  pkg/controller/lifecycle/lfa_member.go
  pkg/controller/lifecycle/lifecycle.go
  pkg/controller/lifecycle/lifecycle_test.go
  pkg/controller/lifecycle/suite_test.go
  pkg/controller/multicluster/setup.go
  pkg/controllerutil/volume_util.go
  pkg/controllerutil/workload_utils.go
  pkg/operations/switchover.go
Labels: approved, size/XXL

#8766 chore: support to convert shardings api in conversion webhook
  apis/apps/v1alpha1/cluster_conversion.go
Labels: approved, size/M

#8762 fix: check lifecycle actions to avoid NPE when calling actions during scale-in
  controllers/apps/transformer_component_workload.go
Labels: approved, size/S

#8778 chore: support to rebuild instance from backup for sharding cluster
  apis/operations/v1alpha1/opsrequest_types.go
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
  examples/redis/cluster-cmpd.yaml
  pkg/operations/rebuild_instance.go
  pkg/operations/rebuild_instance_inplace.go
  pkg/operations/rebuild_instance_test.go
Labels: approved, size/L

#8777 chore: support to rebuild instance from backup for sharding cluster
  apis/apps/v1alpha1/opsrequest_types.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/rebuild_instance.go
  controllers/apps/operations/rebuild_instance_inplace.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/L

#8774 fix: instance template's name having dash leads to error. (#8773)
  pkg/controller/component/workload_utils.go
Labels: size/S, pre-approve

#8783 feat: support specifying the volume attributes class for PVCs
  apis/apps/v1/deprecated.go
  apis/apps/v1/types.go
  apis/apps/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/component/transformer_component_workload.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/synthesize_component.go
  pkg/controllerutil/volume_util.go
Labels: approved, size/L

#8788 fix: supports incremental backup config in cluster CR
  apis/apps/v1/cluster_types.go
  apis/apps/v1/zz_generated.deepcopy.go
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  controllers/apps/cluster/transformer_cluster_backup_policy.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/L

#8790 fix: supports specifing incmental backup in release-0.9
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  controllers/apps/transformer_cluster_backup_policy.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/M

#8791 chore: support for switchover in the sharding component by specifying the componentObjectName of the shard
  apis/operations/v1alpha1/opsrequest_types.go
  apis/operations/v1alpha1/opsrequest_validation.go
  apis/operations/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
  pkg/operations/switchover.go
  pkg/operations/switchover_test.go
Labels: approved, size/L

#8786 chore: support switchover for sharding components
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/opsrequest_webhook.go
  apis/apps/v1alpha1/opsrequest_webhook_test.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  controllers/apps/operations/switchover.go
  controllers/apps/operations/switchover_test.go
  controllers/apps/operations/switchover_util.go
  controllers/apps/operations/switchover_util_test.go
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/L

#8797 fix: no start time and end time for volume expansion progress
  pkg/operations/volume_expansion.go
  pkg/operations/volume_expansion_test.go
Labels: approved, size/S

#8808 fix: expose svc for sharding
  pkg/operations/expose.go
Labels: approved, size/XS

#8807 fix: expose svc for sharding
  controllers/apps/operations/expose.go
Labels: approved, size/M

#8803 fix: NPE when adding a new service port
  controllers/apps/transformer_cluster_service.go
Labels: size/S

#8819 fix: NPE when adding a new service port
  controllers/apps/transformer_cluster_service.go
Labels: approved, size/S

#8813 fix: incremetal backup cronJob
  controllers/apps/cluster/transformer_cluster_backup_policy.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/utils.go
  deploy/helm/templates/rbac/clusterrole.yaml
  pkg/dataprotection/backup/scheduler.go
Labels: approved, size/L

#8829 chore: remove unsupport kb 1.0 addon
  .github/workflows/e2e-kbcli-k3s.yml
  .github/workflows/e2e-kbcli.yml
  .github/workflows/release-image.yml
Labels: approved, size/S

#8828 chore: incremental backup cronJob
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/utils.go
  deploy/helm/templates/rbac/clusterrole.yaml
  pkg/dataprotection/backup/scheduler.go
Labels: approved, size/L

#8820 fix: NPE when adding a new service port
  controllers/apps/cluster/utils.go
  controllers/apps/component/utils.go
Labels: approved, size/M

#8416 feat: refactor cmpd's role definition
  apis/apps/v1/componentdefinition_types.go
  apis/workloads/v1/instanceset_types.go
  apis/workloads/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/component/component_controller_test.go
  controllers/apps/component/transformer_component_status.go
  controllers/apps/component/transformer_component_workload_test.go
  controllers/apps/componentdefinition_controller_test.go
  controllers/apps/configuration/policy_util.go
  controllers/apps/configuration/policy_util_test.go
  controllers/k8score/event_controller_test.go
  controllers/operations/opsrequest_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/labels.go
  pkg/controller/builder/builder_component_definition.go
  pkg/controller/builder/builder_instance_set_test.go
  pkg/controller/component/its_convertor.go
  pkg/controller/instanceset/pod_role_event_handler.go
  pkg/controller/instanceset/pod_role_event_handler_test.go
  pkg/controller/instanceset/reconciler_status.go
  pkg/controller/instanceset/suite_test.go
  pkg/controller/instanceset/types.go
  pkg/controller/instanceset/update_plan.go
  pkg/controller/instanceset/update_plan_test.go
  pkg/controller/instanceset/utils.go
  pkg/controller/instanceset/utils_test.go
  pkg/controller/plan/restore.go
  pkg/controller/plan/restore_test.go
  pkg/controllerutil/pod_utils_test.go
  pkg/operations/custom_test.go
  pkg/operations/horizontal_scaling_test.go
  pkg/operations/ops_progress_util_test.go
  pkg/operations/ops_util_test.go
  pkg/operations/rebuild_instance_test.go
  pkg/operations/vertical_scaling_test.go
  pkg/testutil/apps/base_factory.go
  pkg/testutil/apps/cluster_instance_set_test_util.go
  pkg/testutil/apps/componentdefinition_factory.go
  pkg/testutil/apps/constant.go
Labels: approved, size/XXL

#8328 feat: implement cmpd's PolicyRules
  apis/apps/v1/cluster_types.go
  apis/apps/v1/component_types.go
  apis/apps/v1/componentdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/cluster/transformer_cluster_deletion.go
  controllers/apps/component/component_controller.go
  controllers/apps/component/component_controller_test.go
  controllers/apps/component/transformer_component_deletion.go
  controllers/apps/component/transformer_component_rbac.go
  controllers/apps/component/transformer_component_rbac_test.go
  controllers/apps/component/transformer_component_utils.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/templates/rbac/cluster_pod_required_role.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/pattern.go
  pkg/controller/builder/builder_role.go
  pkg/controller/builder/builder_role_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
  pkg/controller/model/graph_client.go
  pkg/generics/type.go
  pkg/operations/custom/action_workload.go
Labels: area/user-interaction, approved, size/XXL

#8816 chore: support resolving vars from multiple components consistently
  apis/apps/v1/componentdefinition_types.go
  apis/apps/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_sidecardefinitions.yaml
  controllers/apps/shardingdefinition_controller.go
  controllers/apps/shardingdefinition_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_sidecardefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/synthesize_component_test.go
  pkg/controller/component/type.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: approved, size/XL

#8822 fix: use eventime as the event version to improve the granularity
  controllers/k8score/event_controller_test.go
  pkg/controller/instanceset/pod_role_event_handler.go
  pkg/kbagent/util/event.go
Labels: approved, size/XS

#8838 chore: apply labels and annotations from the user to the its object
  pkg/controller/factory/builder.go
Labels: approved, size/XS

#8756 chore: support to update and delete system accounts
  apis/apps/v1/componentdefinition_types.go
  apis/apps/v1/types.go
  apis/apps/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/cluster/transformer_cluster_component.go
  controllers/apps/cluster/transformer_cluster_sharding_account.go
  controllers/apps/component/component_controller_test.go
  controllers/apps/component/transformer_component_account.go
  controllers/apps/component/transformer_component_account_provision.go
  controllers/apps/component/utils.go
  controllers/apps/componentdefinition_controller.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/labels.go
  pkg/controller/builder/builder_component_definition.go
  pkg/controller/component/component_version.go
  pkg/controller/component/its_convertor.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/lifecycle/lfa_account.go
  pkg/testutil/apps/cluster_factory.go
  pkg/testutil/apps/component_factory.go
  pkg/testutil/apps/componentdefinition_factory.go
  pkg/testutil/apps/constant.go
  pkg/testutil/apps/kb_agent_util.go
  pkg/testutil/dataprotection/backup_utils.go
Labels: approved, size/XXL

#8845 fix: pg restart failed
  pkg/controller/instanceset/reconciler_update.go
Labels: approved, size/XS

#8849 fix: add missing rbac
  config/rbac/role.yaml
  controllers/apps/component/component_controller.go
  deploy/helm/config/rbac/role.yaml
  deploy/helm/templates/rbac/rbac_manager_role.yaml
  deploy/helm/values.yaml
Labels: approved, size/M

#8860 chore: remove grafana prometheus loki and vm
  .github/utils/extract_chart_n_image_list.sh
  deploy/helm/dashboards/container-log.json
  deploy/helm/dashboards/kubeblocks-home.json
  deploy/helm/dashboards/kubeblocks-postgresql-detail.json
  deploy/helm/dashboards/kubeblocks-postgresql-overview.json
  deploy/helm/dashboards/loki.json
  deploy/helm/dashboards/nvidia-gpu-exporter.json
  deploy/helm/scripts/change_kb_release.sh
  deploy/helm/templates/_helpers.tpl
  deploy/helm/templates/applications/alertmanager-webhook-adaptor-addon.yaml
  deploy/helm/templates/applications/alertmanager-webhook-adaptor-values.yaml
  deploy/helm/templates/applications/aws-loadbalancer-controller-addon.yaml
  deploy/helm/templates/applications/aws-loadbalancer-controller-values.yaml
  deploy/helm/templates/applications/csi-driver-nfs-addon.yaml
  deploy/helm/templates/applications/csi-hostpath-driver-addon.yaml
  deploy/helm/templates/applications/csi-hostpath-driver-values.yaml
  deploy/helm/templates/applications/grafana-addon.yaml
  deploy/helm/templates/applications/grafana-values.yaml
  deploy/helm/templates/applications/prometheus-addon.yaml
  deploy/helm/templates/applications/prometheus-values.yaml
  deploy/helm/templates/applications/vmagent-addon.yaml
  deploy/helm/templates/applications/vmagent-values.yaml
  deploy/helm/templates/grafana/configmap-dashboards.yaml
  deploy/helm/templates/grafana/configmaps-datasources.yaml
  deploy/helm/templates/prometheus/alertmanager.yaml
  deploy/helm/templates/prometheus/monitor.yaml
  deploy/helm/templates/prometheus/webhook-adaptor.yaml
  deploy/helm/values.yaml
Labels: approved, size/XXL

#8855 chore: support multi continuous backup and specified the continuous method in cluster.spec
  apis/apps/v1/cluster_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  controllers/apps/cluster/cluster_controller_test.go
  controllers/apps/cluster/transformer_cluster_backup_policy.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/dataprotection/backup/scheduler.go
  pkg/dataprotection/restore/utils.go
  pkg/dataprotection/types/constant.go
  pkg/testutil/dataprotection/constant.go
  pkg/testutil/dataprotection/utils.go
Labels: approved, size/L

#8863 chore: support to specify the continuous backup method for cluster.spec
  apis/apps/v1alpha1/cluster_types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  controllers/apps/cluster_controller_test.go
  controllers/apps/component_controller_test.go
  controllers/apps/opsrequest_controller_test.go
  controllers/apps/transformer_cluster_backup_policy.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/dataprotection/backup/scheduler.go
  pkg/dataprotection/restore/utils.go
  pkg/dataprotection/types/constant.go
Labels: approved, size/L

#8868 chore: add s3-compatible StorageProvider
  deploy/helm/templates/storageprovider/s3-compatible.yaml
Labels: size/M, pre-approve

#8870 docs: fix docs bugs in installing kbcli, bakcup repo docs
  docs/user_docs/handle-an-exception/full-disk-lock.md
  docs/user_docs/installation/install-kbcli.md
  docs/user_docs/maintenance/backup-and-restore/backup/backup-repo.md
  i18n/zh-cn/user-docs/handle-an-exception/full-disk-lock.md
  i18n/zh-cn/user-docs/installation/install-kbcli.md
  i18n/zh-cn/user-docs/maintenance/backup-and-restore/backup/backup-repo.md
Labels: approved, size/XL

#8869 docs: fix bugs in kbcli, full disk lock and backuprepo docs in release-0.9
  docs/user_docs/handle-an-exception/full-disk-lock.md
  docs/user_docs/installation/install-kbcli.md
  docs/user_docs/maintenance/backup-and-restore/backup/backup-repo.md
  i18n/zh-cn/user-docs/handle-an-exception/full-disk-lock.md
  i18n/zh-cn/user-docs/installation/install-kbcli.md
  i18n/zh-cn/user-docs/maintenance/backup-and-restore/backup/backup-repo.md
Labels: approved, size/XL
