Repository apecloud/kubeblocks, pull requests merged in 2025-05, with the labels that each got.

#9343 chore: zero replicas of the instance template
  pkg/controller/instanceset/instance_template_util.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/reconciler_revision_update.go
Labels: approved, size/M

#9346 chore: incremental backup failed after switchover
  controllers/dataprotection/utils.go
Labels: approved, size/XS

#9337 fix: The previous updated parameters have been overwritten
  controllers/parameters/componentdrivenparameter_controller.go
  controllers/parameters/parameter_controller_test.go
  controllers/parameters/parameter_util.go
Labels: approved, size/M

#9335 fix: parameter cr is not deleted after ops is deleted
  controllers/parameters/parameter_util.go
Labels: approved, size/S

#9345 fix: use first backup source when restoring systemaccount
  controllers/apps/util/utils.go
  controllers/apps/util/utils_test.go
Labels: approved, size/M

#9344 fix: don't apply pod anti-affinity and TopologySpreadConstraints for action job
  pkg/controller/component/component_lifecycle_action_utils.go
Labels: approved, size/XS

#9338 chore: support unstructured parameter reconfigure, such as map defined in CUE
  pkg/configuration/openapi/flatten.go
  pkg/controller/configuration/parameter_utils.go
Labels: approved, size/M

#9315 fix: support restore manager sidecar
  controllers/dataprotection/restore_controller.go
  controllers/dataprotection/restore_controller_test.go
  controllers/dataprotection/volumepopulator_controller.go
  pkg/dataprotection/restore/builder.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/manager_test.go
  pkg/dataprotection/restore/types.go
Labels: approved, size/L

#9348 chore: remove CODEOWNERS
  .github/CODEOWNERS
Labels: approved, size/S

#9354 chore: support rebuild instance with incremental backup
  pkg/operations/rebuild_instance.go
Labels: approved, size/XS

#9356 fix: exist residual resources of the backup
  controllers/dataprotection/backup_controller.go
Labels: approved, size/S

#9349 fix: use /resize subresource in InPlacePodVerticalScaling when supported
  go.mod
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/instanceset/reconciler_update_test.go
  pkg/controller/kubebuilderx/plan_builder.go
  pkg/controller/kubebuilderx/plan_builder_test.go
  pkg/controller/kubebuilderx/reconciler.go
  pkg/controller/kubebuilderx/reconciler_test.go
  pkg/controller/kubebuilderx/suite_test.go
  pkg/controller/model/graph_options.go
  pkg/controller/model/transform_types.go
  pkg/controllerutil/util.go
  pkg/controllerutil/util_test.go
  pkg/dataprotection/backup/utils.go
  pkg/dataprotection/utils/utils.go
  pkg/dataprotection/utils/utils_test.go
Labels: approved, size/L

#9355 feat: support volumes sharing among different instances
  apis/apps/v1/types.go
  apis/apps/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/component/transformer_component_workload_ops.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/annotations.go
  pkg/constant/const.go
  pkg/constant/pattern.go
  pkg/controller/component/service_reference_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/vars_test.go
  pkg/controller/factory/builder.go
  pkg/controller/instanceset/in_place_update_util.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/reconciler_instance_alignment.go
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/plan/restore.go
  pkg/controllerutil/volume_util.go
Labels: approved, size/L

#9361 chore: backup is always deleting
  controllers/dataprotection/backup_controller.go
Labels: approved, size/XS

#9358 chore: replace the custom PVC spec in the cluster API with the native one
  apis/apps/v1/cluster_types.go
  apis/apps/v1/component_types.go
  apis/apps/v1/types.go
  apis/apps/v1/zz_generated.deepcopy.go
  apis/operations/v1alpha1/opsrequest_validation.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/cluster/transformer_cluster_component_test.go
  controllers/apps/component/component_controller_test.go
  controllers/trace/desired_state_handler_test.go
  controllers/trace/dry_run_handler_test.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_component.go
  pkg/controller/component/vars_test.go
  pkg/controllerutil/volume_util.go
  pkg/operations/volume_expansion.go
  pkg/testutil/apps/cluster_factory.go
  pkg/testutil/apps/cluster_util.go
  pkg/testutil/apps/component_factory.go
Labels: approved, size/XXL

#9360 chore: add volume claim templates to the instance template
  apis/apps/v1/types.go
  apis/apps/v1/zz_generated.deepcopy.go
  apis/workloads/v1/instanceset_types.go
  apis/workloads/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/factory/builder.go
  pkg/controller/instanceset/instance_util.go
Labels: approved, size/XXL

#9365 chore: support use selected pods by the parent backup
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  apis/dataprotection/v1alpha1/backuppolicytemplate_types.go
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  config/crd/bases/dataprotection.kubeblocks.io_restores.yaml
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backuppolicydriver_controller.go
  controllers/dataprotection/backuppolicydriver_controller_test.go
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_restores.yaml
  docs/developer_docs/api-reference/backup.md
  pkg/testutil/dataprotection/backuppolicytemplate_factory.go
  pkg/testutil/dataprotection/utils.go
Labels: approved, size/L

#9366 chore: support use selected pods by the parent backup
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  config/crd/bases/dataprotection.kubeblocks.io_restores.yaml
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/dataprotection/backup_controller.go
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_restores.yaml
  docs/developer_docs/api-reference/backup.md
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/L

#9363 fix: ignore its update strategy diff for compatibility
  controllers/apps/transformer_component_workload.go
Labels: approved, size/XS

#9369 fix: validate the service version before use it
  controllers/apps/componentversion_controller.go
Labels: approved, size/S

#9367 chore: disable the default headless service
  apis/apps/v1/componentdefinition_types.go
  apis/workloads/v1/instanceset_types.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/component/transformer_component_workload.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_instance_set.go
  pkg/controller/factory/builder.go
  pkg/controller/instanceset/reconciler_assistant_object.go
Labels: approved, size/L

#9377 fix: update the termination policy of cmp when the cluster is deleting
  controllers/apps/cluster/cluster_controller.go
  controllers/apps/cluster/transformer_cluster_deletion.go
  controllers/apps/cluster/transformer_cluster_deletion_test.go
  controllers/apps/cluster/transformer_cluster_termination_policy.go
  controllers/apps/component/transformer_component_deletion.go
Labels: approved, size/M

#9384 chore: add a label indicating the release stage to the pods
  controllers/apps/cluster/transformer_cluster_service.go
  controllers/apps/component/transformer_component_service.go
  pkg/constant/const.go
  pkg/constant/labels.go
  pkg/controller/factory/builder.go
  pkg/controller/instanceset/utils.go
Labels: approved, size/S

#9283 chore: instance template supports the service version
  apis/apps/v1/types.go
  apis/workloads/v1/instanceset_types.go
  apis/workloads/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/cluster/transformer_cluster_normalization.go
  controllers/apps/component/transformer_component_load_resources.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/component_version.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/factory/builder.go
  pkg/controller/instanceset/instance_util.go
Labels: approved, size/L

#9386 chore: add api docs for parameters and operations
  apis/operations/v1alpha1/doc.go
  docs/developer_docs/api-reference/cluster.md
  hack/docgen/api/gen-api-doc-config.json
  pkg/client/clientset/versioned/typed/operations/v1alpha1/operations_client.go
  pkg/client/informers/externalversions/generic.go
Labels: approved, size/XXL

#9385 chore: support specifying canary pods
  apis/apps/v1/types.go
  apis/apps/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/factory/builder.go
Labels: approved, size/M

#9388 fix: kb crash when restore redis shard cluster
  controllers/apps/cluster/transformer_cluster_restore.go
Labels: approved, size/S

#9389 chore: update api-doc script
  docs/developer_docs/api-reference/add-on.md
  docs/developer_docs/api-reference/cluster.md
  docs/developer_docs/api-reference/dataprotection.md
  docs/developer_docs/api-reference/operations.md
  docs/developer_docs/api-reference/parameters.md
  hack/docgen/api/gen-api-doc-config.json
  hack/docgen/api/template/members.tpl
Labels: approved, size/XXL

#9403 chore: keep the finalizers added externally on the object
  controllers/workloads/instanceset_controller_test.go
  pkg/controller/kubebuilderx/plan_builder.go
  pkg/controller/kubebuilderx/plan_builder_test.go
Labels: approved, size/M

#9406 fix: the last ordinal pod can not be online
  controllers/apps/operations/horizontal_scaling.go
  controllers/apps/operations/horizontal_scaling_test.go
Labels: approved, size/M
