Repository apecloud/kubeblocks, pull requests merged in 2025-03, with the labels that each got.

#8984 chore: support specifying the retention policy for PVCs
  apis/apps/v1/cluster_types.go
  apis/apps/v1/component_types.go
  apis/apps/v1/types.go
  apis/apps/v1/zz_generated.deepcopy.go
  apis/workloads/v1/instanceset_types.go
  apis/workloads/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/cluster/transformer_cluster_component.go
  controllers/apps/component/component_controller_test.go
  controllers/apps/component/transformer_component_deletion.go
  controllers/apps/component/transformer_component_workload.go
  controllers/workloads/instanceset_controller_test.go
  controllers/workloads/suite_test.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_component.go
  pkg/controller/builder/builder_instance_set.go
  pkg/controller/component/component.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/factory/builder.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/reconciler_deletion.go
  pkg/controller/instanceset/reconciler_instance_alignment.go
  pkg/testutil/apps/component_factory.go
  pkg/testutil/apps/instance_set_factoy.go
Labels: approved, size/XL

#8990 chore: remove parameters resource from the component controller
  controllers/apps/component/suite_test.go
  controllers/apps/component/transformer_component_deletion.go
Labels: approved, size/XS

#8834 fix: h-scale opsRequest validation considers replicas and shards limit
  apis/apps/v1/shardingdefinition_types.go
  apis/operations/v1alpha1/opsrequest_validation.go
  config/crd/bases/apps.kubeblocks.io_shardingdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_shardingdefinitions.yaml
  pkg/operations/horizontal_scaling_test.go
Labels: size/L, pre-approve

#9007 fix: all pods are recreated during horizontal scaling when podUpdatePolicy is Recreate
  pkg/controller/instanceset/in_place_update_util.go
  pkg/controller/instanceset/in_place_update_util_test.go
Labels: approved, size/S

#9009 chore: refine package version workflow
  .github/workflows/package-version.yml
  .github/workflows/release-version.yml
Labels: approved, size/L

#8975 chore: skip pre-terminate if the workload is not provisioned
  controllers/apps/component/transformer_component_pre_terminate.go
  controllers/apps/component/transformer_component_pre_terminate_test.go
Labels: approved, size/L

#9003 fix: failed to validate an empty xml
  controllers/parameters/componentparameter_controller.go
  controllers/parameters/parametersdefinition_controller.go
  controllers/parameters/reconfigure_controller.go
  pkg/unstructured/xml_config.go
  pkg/unstructured/xml_config_test.go
Labels: approved, size/M

#9032 fix: don't add finalizer for StorageProvider (to release-0.9)
  controllers/dataprotection/storageprovider_controller.go
  controllers/dataprotection/storageprovider_controller_test.go
  controllers/storage/storageprovider_controller.go
  controllers/storage/storageprovider_controller_test.go
Labels: size/L, pre-approve

#8821 chore: support sharding component hscale to rerender
  apis/apps/v1/componentdefinition_types.go
  apis/parameters/v1alpha1/types.go
  config/crd/bases/parameters.kubeblocks.io_paramconfigrenderers.yaml
  controllers/parameters/componentdrivenparameter_controller.go
  deploy/helm/crds/parameters.kubeblocks.io_paramconfigrenderers.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/payload.go
  pkg/controller/configuration/config_utils.go
Labels: approved, size/L

#9036 fix: invalid sharding phase of Abnormal
  controllers/apps/cluster/transformer_cluster_component_status.go
Labels: approved, size/XS

#9010 fix: orphan rbac resources instead of deleting
  controllers/apps/component/component_controller_test.go
  controllers/apps/component/transformer_component_deletion.go
  controllers/apps/component/transformer_component_rbac.go
Labels: approved, size/L

#9015 fix: the parameters CR are not deleted
  cmd/manager/main.go
  controllers/parameters/parameter_controller.go
  controllers/parameters/parameter_util.go
  controllers/parameters/suite_test.go
Labels: approved, size/M

#9033 chore: support init parameters and custom parameters template
  controllers/parameters/componentdrivenparameter_controller.go
  controllers/parameters/componentdrivenparameter_controller_test.go
  controllers/parameters/componentparameter_controller.go
  controllers/parameters/parameter_controller.go
  pkg/constant/config.go
  pkg/testutil/apps/component_factory.go
Labels: approved, size/L

#9024 chore: improve continuous backup expiration time
  controllers/dataprotection/backup_controller.go
  pkg/dataprotection/backup/utils.go
  pkg/dataprotection/backup/utils_test.go
Labels: approved, size/L

#9029 chore: support semantic equality for CRs resources
  controllers/apps/cluster/transformer_cluster_component.go
  controllers/apps/cluster/transformer_cluster_component_test.go
  controllers/apps/component/transformer_component_workload.go
Labels: approved, size/L

#9039 fix: add InstanceSet related labels to restored PVCs
  pkg/controller/instanceset/utils.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/manager_test.go
Labels: size/M, pre-approve

#9043 chore: fix CRs resources normalize quantity
  controllers/apps/cluster/transformer_cluster_component.go
  controllers/apps/cluster/transformer_cluster_component_test.go
Labels: approved, size/S

#9018 chore: removed deprecated apps/v1beta1
  apis/parameters/v1alpha1/parametersdefinition_types.go
  config/crd/bases/parameters.kubeblocks.io_parametersdefinitions.yaml
  controllers/apps/cluster/scheme.go
  controllers/parameters/componentparameter_controller.go
  controllers/parameters/reconfigure_controller.go
  deploy/helm/crds/parameters.kubeblocks.io_parametersdefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/configuration/config_manager/signal_windows.go
Labels: approved, size/M

#9027 chore: support semantic equality for CRs resources
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_cluster_component_test.go
  controllers/apps/transformer_component_workload.go
Labels: approved, size/L

#9044 chore: cleanup some useless types and fields in ITS
  apis/workloads/v1/instanceset_types.go
  apis/workloads/v1/zz_generated.deepcopy.go
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_instance_set.go
  pkg/controller/builder/builder_instance_set_test.go
Labels: approved, size/XL

#9053 fix: reconfigure ops phase is incorrect
  controllers/apps/operations/reconfigure.go
  controllers/apps/operations/reconfigure_test.go
Labels: approved, size/M

#9020 chore: support that reconfigure follows the update strategy
  apis/workloads/v1/instanceset_types.go
  apis/workloads/v1/zz_generated.deepcopy.go
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/cluster/suite_test.go
  controllers/apps/component/component_controller.go
  controllers/apps/component/component_controller_test.go
  controllers/apps/component/suite_test.go
  controllers/apps/component/transformer_component_reconfigure.go
  controllers/apps/component/transformer_component_status.go
  controllers/apps/component/transformer_component_workload.go
  controllers/apps/component/transformer_component_workload_ops.go
  controllers/apps/component/transformer_component_workload_test.go
  controllers/apps/suite_test.go
  controllers/operations/suite_test.go
  controllers/workloads/instanceset_controller_test.go
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  go.mod
  go.sum
  pkg/controller/instanceset/reconciler_status.go
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/lifecycle/kbagent.go
  pkg/controller/lifecycle/lfa_replica.go
  pkg/controller/lifecycle/lifecycle.go
  pkg/testutil/apps/instance_set_factoy.go
Labels: approved, size/XXL

#9069 fix: missing some labels for restored pvcs
  pkg/controller/plan/restore.go
Labels: approved, size/XS

#9065 fix: KB 1.0 crash install with KB 0.9.3
  deploy/helm/templates/rbac/parameters_componentparameter_role.yaml
  deploy/helm/templates/rbac/parameters_paramconfigrenderer_role.yaml
  deploy/helm/templates/rbac/parameters_parameter_role.yaml
  deploy/helm/templates/rbac/parameters_parametersdefinition_role.yaml
Labels: approved, size/L

#9057 fix: parameter cr phase is incorrect
  controllers/parameters/parameter_util.go
  controllers/parameters/reconcile_task.go
  pkg/controllerutil/config_util.go
  pkg/controllerutil/config_util_test.go
Labels: approved, size/S

#9066 chore: update configs and scripts in sidecar definition
  apis/apps/v1/sidecardefinition_types.go
  apis/apps/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_sidecardefinitions.yaml
  controllers/apps/componentdefinition_controller.go
  controllers/apps/sidecardefinition_controller.go
  controllers/apps/utils.go
  deploy/helm/crds/apps.kubeblocks.io_sidecardefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/sidecar.go
  pkg/controller/component/synthesize_component.go
Labels: approved, size/L

#8991 chore: refine some comments and naming in kubebuilderx
  pkg/controller/instanceset/reconciler_instance_alignment.go
  pkg/controller/instanceset/reconciler_revision_update.go
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/kubebuilderx/controller.go
  pkg/controller/kubebuilderx/controller_test.go
  pkg/controller/kubebuilderx/doc.go
  pkg/controller/kubebuilderx/reconciler.go
Labels: approved, size/M

#9068 fix: missing some labels for restored pvcs
  pkg/controller/plan/restore.go
Labels: approved, size/XS

#9075 fix: cluster is always deleting when it is restoring
  controllers/apps/operations/restore.go
Labels: approved, size/XS

#9074 fix: cluster is always deleting when it is restoring
  pkg/operations/restore.go
Labels: approved, size/XS

#9056 chore: restore accounts from backup cr
  controllers/apps/cluster/transformer_cluster_sharding_account.go
  controllers/apps/component/transformer_component_account.go
  controllers/apps/util/utils.go
  controllers/apps/util/utils_test.go
  pkg/constant/backup.go
  pkg/controller/factory/builder.go
  pkg/dataprotection/restore/utils.go
Labels: approved, size/L

#9078 chore: skip notifying the dependent components being updated
  controllers/apps/component/transformer_component_notifier.go
Labels: approved, size/XS

#9072 chore: backup retention period test failure
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/restore_controller_test.go
Labels: approved, size/M

#9080 chore: backup retention period test failure in release-0.9
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/restore_controller_test.go
Labels: approved, size/M

#9079 chore: fix a flaky case for the config template
  controllers/apps/component/component_controller_test.go
Labels: approved, size/S

#9076 chore: system accounts provision for the sharding cluster
  controllers/apps/cluster/cluster_controller.go
  controllers/apps/cluster/transformer_cluster_normalization.go
  controllers/apps/cluster/transformer_cluster_sharding_account.go
Labels: approved, size/M

#9058 chore: give a separate definition of the instance template for ITS
  apis/workloads/v1/instanceset_types.go
  apis/workloads/v1/zz_generated.deepcopy.go
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/factory/builder.go
Labels: approved, size/L

#9071 chore: split the rendering of the parameter template out from the apps controllers
  controllers/apps/component/transformer_component_reload_sidecar.go
  controllers/parameters/reconcile_task.go
  pkg/controller/configuration/config_utils.go
Labels: approved, size/M

#9060 chore: support sharding reconfigure and clean parameters when deleting ops cr
  controllers/operations/opsrequest_controller.go
  controllers/parameters/config_reconcile_wrapper.go
  controllers/parameters/configuration_test.go
  controllers/parameters/parameter_controller.go
  controllers/parameters/parameter_controller_test.go
  controllers/parameters/parameter_util.go
  controllers/parameters/reconfigure_controller.go
  pkg/operations/reconfigure.go
Labels: approved, size/L

#9082 fix: the static parameter reconfigure did not take effect
  controllers/parameters/policy_util.go
  controllers/parameters/policy_util_test.go
Labels: approved, size/L

#9089 chore: enable configuration controller when DualOperatorsMode is true
  cmd/manager/main.go
Labels: approved, size/M

#9087 chore: tidy up code for upgrading from KB 0.9 to version 1.0
  apis/apps/v1alpha1/cluster_types.go
  apis/apps/v1alpha1/component_conversion.go
  apis/workloads/v1alpha1/instanceset_conversion.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  controllers/apps/component/component_controller_test.go
  controllers/apps/component/transformer_component_workload.go
  controllers/parameters/componentdrivenparameter_controller.go
  controllers/parameters/componentdrivenparameter_controller_test.go
  controllers/parameters/configuration_test.go
  controllers/trace/util_test.go
  controllers/workloads/instanceset_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/templates/rbac/apps_cluster_editor_role.yaml
  deploy/helm/templates/rbac/apps_clusterdefinition_editor_role.yaml
  deploy/helm/templates/rbac/apps_configconstraint_editor_role.yaml
  deploy/helm/templates/rbac/apps_sidecardefinition_editor_role.yaml
  deploy/helm/templates/rbac/clusterrole.yaml
  deploy/helm/templates/rbac/operations_opsdefinition_role.yaml
  deploy/helm/templates/rbac/operations_opsrequest_role.yaml
  deploy/helm/templates/rbac/parameters_componentparameter_role.yaml
  deploy/helm/templates/rbac/parameters_paramconfigrenderer_role.yaml
  deploy/helm/templates/rbac/parameters_parameter_role.yaml
  deploy/helm/templates/rbac/parameters_parametersdefinition_role.yaml
  deploy/helm/templates/rbac/shardingdefinition_editor_role.yaml
  deploy/helm/templates/rbac/workloads_instanceset_editor_role.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_instance_set.go
  pkg/controller/builder/builder_instance_set_test.go
  pkg/controller/factory/builder.go
  pkg/controller/instanceset/in_place_update_util_test.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/object_builder_test.go
  pkg/controller/instanceset/reconciler_assistant_object_test.go
  pkg/controller/instanceset/reconciler_status_test.go
  pkg/controller/instanceset/reconciler_update_test.go
  pkg/operations/reconfigure.go
Labels: approved, size/L

#9092 chore: missing role rbac when upgrading kb 0.9 to 1.0
  deploy/helm/templates/rbac/clusterrole.yaml
  deploy/helm/templates/rbac/rbac_role.yaml
Labels: approved, size/M

#9095 chore: lifecycle action job podTemplate supports well-known labels
  pkg/controller/component/component_lifecycle_action_utils.go
Labels: approved, size/XS

#9103 fix: sync the backup method failed from bpt
  controllers/apps/transformer_cluster_backup_policy.go
Labels: approved, size/S

#9104 chore: don't manipulate the config if no parameters resource defined
  controllers/parameters/componentdrivenparameter_controller.go
  pkg/controller/configuration/parameter_utils.go
Labels: approved, size/XS

#9084 chore: use new config API in the cmpd
  apis/apps/v1/componentdefinition_types.go
  apis/apps/v1/zz_generated.deepcopy.go
  apis/parameters/v1alpha1/componentparameter_types.go
  apis/parameters/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/parameters.kubeblocks.io_componentparameters.yaml
  controllers/apps/component/component_controller.go
  controllers/apps/component/component_controller_test.go
  controllers/apps/component/transformer_component_reload_sidecar.go
  controllers/apps/component/transformer_component_template.go
  controllers/apps/component/transformer_component_workload.go
  controllers/apps/component/transformer_component_workload_ops.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/sidecardefinition_controller.go
  controllers/parameters/componentdrivenparameter_controller.go
  controllers/parameters/paramconfigrenderer_controller.go
  controllers/parameters/policy_util.go
  controllers/parameters/reconcile_task.go
  controllers/parameters/reconfigure_policy.go
  controllers/parameters/relatedresource.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/parameters.kubeblocks.io_componentparameters.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/configuration/config_manager/builder.go
  pkg/configuration/config_manager/builder_test.go
  pkg/configuration/config_manager/config_handler.go
  pkg/configuration/config_manager/config_handler_test.go
  pkg/configuration/config_manager/handler_util.go
  pkg/configuration/config_manager/handler_util_test.go
  pkg/configuration/config_manager/reload_util_test.go
  pkg/configuration/config_manager/type.go
  pkg/configuration/core/type.go
  pkg/configuration/core/type_test.go
  pkg/controller/builder/builder_component_parameter.go
  pkg/controller/builder/builder_component_parameter_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/synthesize_component_test.go
  pkg/controller/component/type.go
  pkg/controller/component/utils.go
  pkg/controller/configuration/annotation_utils.go
  pkg/controller/configuration/config_utils.go
  pkg/controller/configuration/parameter_utils.go
  pkg/controller/configuration/template_merger.go
  pkg/controller/configuration/template_merger_test.go
  pkg/controller/configuration/template_render_test.go
  pkg/controller/configuration/tool_image_builder_test.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
  pkg/controller/render/render_utils.go
  pkg/controller/render/template_render.go
  pkg/controller/render/types.go
  pkg/controllerutil/parameter_schema.go
  pkg/controllerutil/volume_util.go
  pkg/controllerutil/volume_util_test.go
  pkg/testutil/apps/componentdefinition_factory.go
  pkg/testutil/apps/constant.go
Labels: approved, size/XXL

#9108 chore: conversion for configs and scripts in the cmpd
  apis/apps/v1alpha1/componentdefinition_conversion.go
Labels: approved, size/XS

#9111 fix: lorry startup failute due to jobs label change
  pkg/lorry/dcs/k8s.go
Labels: approved, size/XS

#9121 chore: annotation key to skip the pre-terminate action
  pkg/constant/annotations.go
  pkg/controller/component/component_pre_terminate.go
Labels: approved, size/S

#9110 fix: kubeblocks crash when using dual operator
  apis/apps/v1alpha1/componentdefinition_conversion.go
  apis/workloads/v1alpha1/instanceset_conversion.go
  deploy/helm/scripts/change_kb_release.sh
  deploy/helm/templates/conversion-patch-hook.yaml
Labels: approved, size/M

#9088 feat: support retaining the latest backup
  apis/dataprotection/v1alpha1/backuppolicy_types.go
  apis/dataprotection/v1alpha1/backuppolicytemplate_types.go
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backuppolicytemplates.yaml
  controllers/apps/cluster/transformer_cluster_backup_policy.go
  controllers/dataprotection/gc_controller.go
  controllers/dataprotection/gc_controller_test.go
  controllers/dataprotection/suite_test.go
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicytemplates.yaml
  docs/developer_docs/api-reference/backup.md
Labels: approved, size/L

#9132 chore: make the instance status ordered
  pkg/controller/instanceset/reconciler_status.go
Labels: approved, size/XS

#8918 chore: the code assistant workflow
  .github/workflows/code-assistant.yml
Labels: approved, size/S

#9139 fix: validate lifecycle action
  controllers/apps/componentdefinition_controller.go
Labels: approved, size/XS

#9141 chore: the code assistant workflow
  .github/workflows/code-assistant.yml
Labels: approved, size/M

#9137 fix: reconfigure does not take effect
  controllers/parameters/componentdrivenparameter_controller.go
  controllers/parameters/componentdrivenparameter_controller_test.go
  controllers/parameters/parameter_controller_test.go
  controllers/parameters/parameter_util.go
  pkg/controller/configuration/parameter_utils.go
  pkg/controller/configuration/parameter_utils_test.go
  pkg/controller/configuration/template_render_test.go
Labels: approved, size/L

#9143 fix: build sa without role probe
  pkg/controller/component/synthesize_component.go
Labels: approved, size/XS
