Repository apecloud/kubeblocks, pull requests merged in 2025-04, with the labels that each got.

#9149 fix: NPE when the component does not have a ParamConfigRender
  controllers/parameters/componentdrivenparameter_controller.go
  controllers/parameters/componentdrivenparameter_controller_test.go
  controllers/parameters/parameter_util.go
  pkg/controller/configuration/parameter_utils.go
Labels: approved, size/M

#9154 chore: panic during the conversion of the instance templates
  pkg/controller/factory/builder.go
Labels: approved, size/XS

#9155 fix: pod services for the instance template
  controllers/apps/component/transformer_component_service.go
  pkg/controller/component/workload_utils.go
Labels: approved, size/M

#9193 chore: support resolving vars from multiple components consistently (pick from 1f8a6797)
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: approved, size/L

#9195 chore: support sharding component hscale to rerender(pick from d43a9224)
  apis/apps/v1alpha1/type.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusterversions.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  controllers/apps/transformer_component_parameters.go
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterversions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/payload.go
  pkg/controller/configuration/config_utils.go
  pkg/controller/configuration/pipeline.go
Labels: approved, size/M

#9199 chore: upgrade e2e k8s version 1.32
  .github/workflows/e2e-fault.yml
  .github/workflows/e2e-kbcli-k3s.yml
  .github/workflows/e2e-kbcli.yml
  .github/workflows/e2e-performance.yml
  .github/workflows/e2e-smoke.yml
  .github/workflows/release-image.yml
Labels: approved, size/M

#9196 chore: support setting ownership of configs in cmpd
  apis/apps/v1/componentdefinition_types.go
  apis/apps/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_sidecardefinitions.yaml
  config/crd/bases/parameters.kubeblocks.io_componentparameters.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_sidecardefinitions.yaml
  deploy/helm/crds/parameters.kubeblocks.io_componentparameters.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/kbagent_test.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/synthesize_component_test.go
  pkg/controller/component/type.go
Labels: approved, size/L

#9181 chore: support selective backup
  apis/apps/v1alpha1/backuppolicytemplate_types.go
  apis/apps/v1alpha1/opsrequest_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/dataprotection/v1alpha1/actionset_types.go
  apis/dataprotection/v1alpha1/backup_types.go
  apis/dataprotection/v1alpha1/backupschedule_types.go
  apis/dataprotection/v1alpha1/restore_types.go
  apis/dataprotection/v1alpha1/types.go
  apis/dataprotection/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
  config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
  config/crd/bases/dataprotection.kubeblocks.io_actionsets.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
  config/crd/bases/dataprotection.kubeblocks.io_backupschedules.yaml
  config/crd/bases/dataprotection.kubeblocks.io_restores.yaml
  controllers/apps/operations/backup.go
  controllers/apps/operations/custom.go
  controllers/apps/operations/restore.go
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/dataprotection/actionset_controller.go
  controllers/dataprotection/actionset_controller_test.go
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/backupschedule_controller_test.go
  controllers/dataprotection/restore_controller_test.go
  deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
  deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_actionsets.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_backupschedules.yaml
  deploy/helm/crds/dataprotection.kubeblocks.io_restores.yaml
  docs/developer_docs/api-reference/backup.md
  docs/developer_docs/api-reference/cluster.md
  pkg/common/openapiv3schema.go
  pkg/constant/const.go
  pkg/controller/plan/restore.go
  pkg/dataprotection/backup/request.go
  pkg/dataprotection/backup/scheduler.go
  pkg/dataprotection/backup/utils.go
  pkg/dataprotection/restore/builder.go
  pkg/dataprotection/restore/utils.go
  pkg/dataprotection/utils/backup.go
  pkg/dataprotection/utils/envvar.go
  pkg/dataprotection/utils/utils.go
  pkg/testutil/dataprotection/backup_utils.go
  pkg/testutil/dataprotection/constant.go
  pkg/testutil/dataprotection/restore_factory.go
  pkg/testutil/dataprotection/utils.go
Labels: approved, size/XXL

#9197 chore: support obtaining resources through vars
  apis/apps/v1/componentdefinition_types.go
  apis/apps/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_sidecardefinitions.yaml
  controllers/apps/component/transformer_component_notifier.go
  controllers/apps/componentdefinition_controller.go
  controllers/apps/shardingdefinition_controller.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_sidecardefinitions.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/vars.go
  pkg/controller/component/vars_test.go
Labels: approved, size/XL

#9201 chore: supports skipping backup reconciliation
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  pkg/dataprotection/types/constant.go
Labels: approved, size/S

#9202 fix: disable svc ops is always running for sharding component
  controllers/apps/operations/expose.go
Labels: approved, size/XS

#9205 chore: update the latest 0.9 api
  apis/apps/v1alpha1/type.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/parameters/v1alpha1/types.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_configurations.yaml
  config/crd/bases/parameters.kubeblocks.io_paramconfigrenderers.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_configurations.yaml
  deploy/helm/crds/parameters.kubeblocks.io_paramconfigrenderers.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/configuration/config_utils.go
Labels: approved, size/L

#9200 chore: support restarting the pod when the config changes
  apis/apps/v1/componentdefinition_types.go
  apis/apps/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_sidecardefinitions.yaml
  config/crd/bases/parameters.kubeblocks.io_componentparameters.yaml
  controllers/apps/component/component_controller.go
  controllers/apps/component/component_controller_test.go
  controllers/apps/component/transformer_component_template.go
  controllers/apps/component/transformer_component_tls.go
  controllers/apps/component/transformer_component_workload.go
  controllers/apps/component/transformer_component_workload_ops.go
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_sidecardefinitions.yaml
  deploy/helm/crds/parameters.kubeblocks.io_componentparameters.yaml
  docs/developer_docs/api-reference/cluster.md
Labels: approved, size/L

#9135 chore: clean up pod status handling in instanceset controller
  controllers/parameters/policy_util.go
  controllers/parameters/rolling_upgrade_policy.go
  controllers/parameters/sync_upgrade_policy.go
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/instance_util_test.go
  pkg/controller/instanceset/reconciler_instance_alignment.go
  pkg/controller/instanceset/reconciler_status.go
  pkg/controller/instanceset/reconciler_status_test.go
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/instanceset/update_plan.go
  pkg/controllerutil/pod_utils.go
  pkg/dataprotection/utils/utils.go
  pkg/operations/custom/utils.go
Labels: approved, size/L

#9167 chore: adjust ParamConfigRenderer fileFormatConfig api optional
  apis/parameters/v1alpha1/paramconfigrenderer_types.go
  config/crd/bases/parameters.kubeblocks.io_paramconfigrenderers.yaml
  deploy/helm/crds/parameters.kubeblocks.io_paramconfigrenderers.yaml
Labels: approved, size/XS

#9215 fix: kb09 crash
  controllers/apps/transformer_cluster_restore.go
Labels: approved, size/XS

#9211 chore: reset the config template when the external template has not been set
  pkg/controller/component/synthesize_component.go
Labels: approved, size/XS

#9209 fix: cluster deleting should take the termination policy into account
  controllers/apps/transformer_cluster_api_normalization.go
  controllers/apps/transformer_cluster_backup_policy.go
  controllers/apps/transformer_cluster_component.go
  controllers/apps/transformer_cluster_component_status.go
  controllers/apps/transformer_cluster_credential.go
  controllers/apps/transformer_cluster_placement.go
  controllers/apps/transformer_cluster_service.go
  controllers/apps/transformer_cluster_shared_account.go
Labels: approved, size/S

#9216 fix: cluster deleting should take the termination policy into account
  controllers/apps/cluster/transformer_cluster_component.go
  controllers/apps/cluster/transformer_cluster_component_status.go
  controllers/apps/cluster/transformer_cluster_normalization.go
  controllers/apps/cluster/transformer_cluster_placement.go
  controllers/apps/cluster/transformer_cluster_service.go
  controllers/apps/cluster/transformer_cluster_sharding_account.go
  controllers/apps/cluster/transformer_cluster_sharding_tls.go
  controllers/apps/component/transformer_component_account.go
  controllers/apps/component/transformer_component_account_provision.go
  controllers/apps/component/transformer_component_hostnetwork.go
  controllers/apps/component/transformer_component_monitor.go
  controllers/apps/component/transformer_component_post_provision.go
  controllers/apps/component/transformer_component_rbac.go
  controllers/apps/component/transformer_component_reload_sidecar.go
  controllers/apps/component/transformer_component_service.go
  controllers/apps/component/transformer_component_status.go
  controllers/apps/component/transformer_component_template.go
  controllers/apps/component/transformer_component_vars.go
  controllers/apps/component/transformer_component_workload.go
  controllers/apps/component/utils.go
Labels: approved, size/M

#9208 chore: allow updating pending pod in instanceset
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/instanceset/reconciler_update_test.go
Labels: approved, size/L

#9218 chore: use component generation as instanceSet's kb-generation
  controllers/apps/transformer_component_status.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/type.go
  pkg/controller/factory/builder.go
Labels: approved, size/S

#9210 fix: user provided tls 09
  pkg/controller/plan/tls_utils.go
  pkg/controller/plan/tls_utils_test.go
Labels: approved, size/M

#9220 chore: allow updating pending pod in instanceset
  pkg/controller/instanceset/instance_util.go
  pkg/controller/instanceset/reconciler_update.go
Labels: approved, size/M

#9223 chore: declare the default value of the pod management policy
  apis/apps/v1/componentdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  pkg/controller/factory/builder.go
Labels: approved, size/XS

#9224 chore: support set addon charts image pull policy
  controllers/extensions/addon_controller_stages.go
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
  pkg/constant/viper_config.go
Labels: approved, size/S

#9226 chore: support leader id configurable with helm values
  deploy/helm/templates/dataprotection.yaml
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
Labels: size/XS, pre-approve

#9229 chore: fix the random failure of the case for updating pending pods
  pkg/controller/instanceset/reconciler_update_test.go
Labels: approved, size/XS

#9227 fix: config/scripts tempalte has not tpl specified
  controllers/parameters/componentdrivenparameter_controller.go
  controllers/parameters/parametertemplateextension_controller.go
Labels: approved, size/M

#9243 fix: remove component annotation checking for configs
  controllers/parameters/config_related_helper.go
Labels: approved, size/XS

#9249 fix: conflicting Secret management in SA
  controllers/apps/component/transformer_component_rbac.go
Labels: size/XS, pre-approve

#9251 chore: allow the component to be updated when the predecessor does not exist
  controllers/apps/cluster/transformer_cluster_component.go
  controllers/apps/cluster/transformer_cluster_component_test.go
Labels: approved, size/S

#9258 chore: release kubeblocks-tools image not use cache
  .github/workflows/release-image.yml
Labels: approved, size/XS

#9263 chore: fix readme badge
  README.md
Labels: size/XS

#9261 chore: validate the pod management policy in cmpd
  controllers/apps/componentdefinition_controller.go
Labels: approved, size/S

#9252 chore: restore accounts from backup cr
  controllers/apps/transformer_cluster_shared_account.go
  controllers/apps/transformer_component_account.go
  pkg/controller/factory/builder.go
  pkg/controller/factory/builder_test.go
  pkg/dataprotection/restore/utils.go
Labels: approved, size/L

#9280 fix: build sa with specific lifecycle
  pkg/controller/component/synthesize_component.go
Labels: approved, size/XS

#9286 chore: release the connection to kbagent after calling the action
  cmd/kbagent/main.go
  pkg/controller/lifecycle/kbagent.go
  pkg/kbagent/client/client.go
  pkg/kbagent/client/client_mock.go
  pkg/kbagent/client/http_client.go
  pkg/kbagent/client/portforward_client.go
Labels: approved, size/S

#9289 chore: remove wontfix addon
  .github/workflows/e2e-kbcli-k3s.yml
  .github/workflows/e2e-kbcli.yml
  .github/workflows/release-image.yml
Labels: approved, size/S

#9288 chore: release the connection to kbagent after calling the action
  cmd/kbagent/main.go
  pkg/controller/lifecycle/kbagent.go
  pkg/kbagent/client/client.go
  pkg/kbagent/client/client_mock.go
  pkg/kbagent/client/http_client.go
Labels: size/S

#9275 chore: update join member action's envs
  pkg/lorry/engines/custom/manager.go
Labels: approved, size/XS

#9287 chore: support set addon charts image pull policy (#9224)
  controllers/extensions/addon_controller_stages.go
  deploy/helm/templates/deployment.yaml
  pkg/constant/const.go
Labels: approved, size/S

#9290 chore: update inPlace api of the rebuild instance ops
  apis/operations/v1alpha1/opsrequest_types.go
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
Labels: approved, size/S

#9291 fix: post-provision job always pending when component enable pod antiAffinity
  pkg/controller/component/component_lifecycle_action_utils.go
Labels: approved, size/XS

#9293 fix: notify dependent components after other objects
  controllers/apps/component/transformer_component_notifier.go
Labels: approved, size/XS

#9297 fix: follow component's scheduling policy in lifecycle action job
  controllers/apps/operations/switchover_test.go
  controllers/apps/operations/switchover_util.go
  controllers/apps/operations/switchover_util_test.go
  pkg/controller/component/component_lifecycle_action_utils.go
Labels: approved, size/M

#9305 chore: remove deleted env vars from the env CM
  controllers/apps/component/transformer_component_vars.go
  controllers/apps/component/transformer_component_vars_test.go
  controllers/apps/component/transformer_component_workload_ops.go
Labels: approved, size/L

#9312 fix: minReadySeconds not respected during pod update
  pkg/controller/instanceset/reconciler_update.go
  pkg/controller/instanceset/reconciler_update_test.go
Labels: approved, size/L

#9319 fix: minReadySeconds not respected during pod update
  pkg/controller/instanceset/reconciler_update.go
Labels: approved, size/S
