Repository apecloud/kubeblocks, pull requests merged in 2025-06, with the labels that each got.

#9405 fix: the last ordinal pod can not be online
  pkg/operations/horizontal_scaling.go
  pkg/operations/horizontal_scaling_test.go
Labels: approved, size/L

#9413 fix: kb crash when restoring cluster
  pkg/operations/restore.go
Labels: approved, size/XS

#9419 chore: inherit encrytion config from parent backup
  controllers/dataprotection/backup_controller.go
  controllers/dataprotection/backup_controller_test.go
  controllers/dataprotection/utils.go
Labels: approved, size/L

#9424 fix: scaling backup is always deleting
  controllers/dataprotection/backup_controller.go
Labels: approved, size/XS

#9426 chore: update dependencies
  controllers/apps/component/transformer_component_deletion.go
  docker/Dockerfile
  docker/Dockerfile-charts
  docker/Dockerfile-dataprotection
  docker/Dockerfile-dev
  docker/Dockerfile-tools
  go.mod
  go.sum
  pkg/configuration/proto/reconfigure.pb.go
  pkg/configuration/proto/reconfigure_grpc.pb.go
  pkg/kbagent/client/client_mock.go
Labels: approved, size/M

#9427 chore: update dependencies for release-1.0
  controllers/apps/component/transformer_component_deletion.go
  docker/Dockerfile
  docker/Dockerfile-charts
  docker/Dockerfile-dataprotection
  docker/Dockerfile-dev
  docker/Dockerfile-tools
  go.mod
  go.sum
  pkg/configuration/proto/reconfigure.pb.go
  pkg/configuration/proto/reconfigure_grpc.pb.go
  pkg/kbagent/client/client_mock.go
Labels: approved, size/M

#9428 chore: support to restore from encryption backup
  controllers/dataprotection/backup_controller.go
Labels: approved, size/S

#9432 fix: make doc
  Makefile
  go.mod
  go.sum
  hack/docgen/api/go.mod
  hack/docgen/api/go.sum
  hack/docgen/api/main.go
Labels: approved, size/M

#9436 fix: remove GOTOOLCHAIN env for `make api-doc`
  Makefile
Labels: approved, size/XS

#9437 fix: make api-doc
  Makefile
  go.mod
  go.sum
  hack/docgen/api/go.mod
  hack/docgen/api/go.sum
  hack/docgen/api/main.go
Labels: approved, size/M

#9440 chore: redis action support load balancer
  pkg/lorry/engines/redis/manager.go
Labels: approved, size/M

#9415 chore: support setting the host alias and DNS config of pods
  apis/apps/v1/cluster_types.go
  apis/apps/v1/component_types.go
  apis/apps/v1/types.go
  apis/apps/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/cluster/transformer_cluster_component.go
  controllers/apps/component/transformer_component_hostnetwork.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/builder/builder_component.go
  pkg/controller/component/component.go
  pkg/controller/component/synthesize_component.go
  pkg/controller/component/utils.go
Labels: approved, size/XL

#9442 chore: refine Makefile
  Makefile
  docker/docker.mk
Labels: approved, size/L

#9447 chore: auto cherry-pick by label
  .github/workflows/cherry-pick-auto.yml
  .github/workflows/cherry-pick-label-check.yml
  .github/workflows/cherry-pick-usage.yml
  .github/workflows/cherry-pick.yml
  .github/workflows/create-branch.yml
Labels: approved, size/M, pick-1.0

#9404 feat: add an option to merge full and pitr restore job
  pkg/constant/annotations.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/manager_test.go
Labels: approved, size/L

#9451 chore: updates from PVC are lost
  controllers/workloads/instanceset_controller.go
  pkg/dataprotection/restore/manager_test.go
Labels: approved, size/S, nopick

#9452 chore: add volume claim templates to the instance template
  apis/apps/v1/types.go
  apis/apps/v1/zz_generated.deepcopy.go
  apis/workloads/v1/instanceset_types.go
  apis/workloads/v1/zz_generated.deepcopy.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/factory/builder.go
  pkg/controller/instanceset/instance_util.go
Labels: approved, size/XXL, nopick

#9465 chore: upgrade codeql version 3
  .github/workflows/codeql.yml
Labels: approved, size/XS, pick-0.9, pick-1.0

#9472 chore: disable lorry ha for wesql
  pkg/lorry/highavailability/util.go
Labels: approved, size/XS

#9468 chore: fix the bug of dynamically setting the flat instance ordinal
  apis/apps/v1/types.go
  apis/operations/v1alpha1/opsrequest_validation.go
  apis/workloads/v1/instanceset_types.go
  config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
  controllers/apps/cluster/transformer_cluster_component.go
  controllers/apps/component/transformer_component_workload.go
  controllers/apps/shardingdefinition_controller.go
  deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/constant/labels.go
  pkg/controller/factory/builder.go
  pkg/controller/instanceset/instance_util.go
Labels: approved, size/M, nopick

#9469 chore: instance template supports specifying the comp-def
  apis/apps/v1/types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  config/crd/bases/operations.kubeblocks.io_opsrequests.yaml
  controllers/apps/cluster/transformer_cluster_normalization.go
  controllers/apps/component/transformer_component_load_resources.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  deploy/helm/crds/operations.kubeblocks.io_opsrequests.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/controller/component/component_version.go
Labels: approved, size/L, nopick

#9476 chore: Revert "feat: add an option to merge full and pitr restore job (#9404)"
  pkg/constant/annotations.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/manager_test.go
Labels: approved, size/L

#9475 chore: support moving replicas into the instance template
  pkg/controller/instanceset/in_place_update_util.go
  pkg/controller/instanceset/instancetemplate/name_builder_flat.go
  pkg/controller/instanceset/instancetemplate/name_builder_flat_test.go
Labels: approved, size/L, nopick

#9487 chore: update kubeblocks readme
  README.md
Labels: approved, size/XS, pick-1.0, nopick

#9480 feat: specify allowed symbols in password generation
  apis/apps/v1/types.go
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/cluster/transformer_cluster_sharding_account.go
  controllers/apps/component/transformer_component_account.go
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/common/password.go
  pkg/common/password_test.go
Labels: approved, size/L, pick-1.0

#9492 chore: add azureblob storage provider
  deploy/helm/templates/storageprovider/azureblob.yaml
Labels: approved, size/M, pick-0.9, pick-1.0

#9493 fix: incremental backup failed
  controllers/apps/transformer_cluster_backup_policy.go
Labels: approved, size/XS

#9494 chore: support merging full ptir job in release-0.9
  pkg/constant/annotations.go
  pkg/dataprotection/restore/manager.go
  pkg/dataprotection/restore/manager_test.go
Labels: approved, size/L, nopick

#9489 feat: specify allowed symbols in password generation
  apis/apps/v1alpha1/clusterdefinition_types.go
  config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_clusters.yaml
  config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
  config/crd/bases/apps.kubeblocks.io_components.yaml
  controllers/apps/transformer_cluster_shared_account.go
  controllers/apps/transformer_component_account.go
  deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
  deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
  deploy/helm/crds/apps.kubeblocks.io_components.yaml
  docs/developer_docs/api-reference/cluster.md
  pkg/common/password.go
  pkg/common/password_test.go
  pkg/controller/factory/builder.go
Labels: approved, size/L

#9496 chore: remove the backupPolicy conflict event for cluster
  controllers/dataprotection/backuppolicydriver_controller.go
Labels: approved, size/XS, pick-1.0
